### ISSUE TITLE
Banner Line Security Markings

### ISSUE THREAD

**Issue by patricknowlan** [uswds/uswds#1031]
### Description

Government user interfaces that hold sensitive data typically have some sort of data classification / security markings. The most common form for web applications is the use of a banner line on top and or bottom of the web page. I think these banner lines are intentionally designed to catch a users attention, but not because they are visually appealing.
### Ask

Im hoping the designers of some of the web standards would take a crack at a modern approach to incorporating these into web applications.
### To Do
- [ ] create a version of the "usa-disclaimer" component for views with unclassified data
- [ ] create a version of the "usa-disclaimer" component for views with classified data
### Additional Info

Here is a link to a [policy document](http://www.dtic.mil/whs/directives/corres/pdf/520001_vol2.pdf) which provides more than enough detail of security marking requirements. 

Also here are some examples if not familiar with the topic.
![unclassified-example](https://cloud.githubusercontent.com/assets/6303436/13518476/45c557ec-e19c-11e5-975d-2e83ace0e65a.png)

![classified-example](https://cloud.githubusercontent.com/assets/6303436/13518486/5da1abae-e19c-11e5-87ae-8d1d7090d472.png)

**Comment by carodew** [comment]
@patricknowlan interesting idea. We've talked about adding some type of pattern for a site-wide alert or banner, something a little more abstracted from this but could be adapted to this use (as well as other things, such as alpha and beta alerts for in-progress sites, etc). 

I think (on a gut level) it would be good for any such message to include instructions (or a link to instructions) that further explain what this means to the user – should they take (or avoid) any particular actions? 

Our near-term priorities include streamlining the workflow for standing up or designing a simple website, which includes header elements. This might be something we could include on a second pass of that work.

**Comment by patricknowlan** [comment]
I think there might be circumstances where developers would need to display both a security marking banner line as well as beta / alpha info (this could be a UI challenge). I am not sure if it can be done in the same banner/alert element or do these two pieces have to be separate in accordance to the security markings policy? On a side note, the policy actually probably needs to be updated to reflect modern web design...

I agree with you on adding a link to the meaning of the data classifications and or other contents included in the banner. From what I have seen, banner-lines are traditionally text only and do not include links. My thoughts are if they are going to be included in a site, they might as well be useful, so why not add a link for more info. 

I would say the use case for this component is probably geared towards an interactive application but I could also see how they would be incorporated into a simple website. :+1:

**Comment by jbruce-gsa** [comment]
I think, in some ways, we could use/modify the standard alerts to accomplish this mission. The language I should could definitely be done in a more robust call to action fashion; for example, on classified pages, the question is generally: Do you have a need to know?

For the program I am working with, we have added in a recommendation for print styles that would include/display proper file marking and handling labels. Not sure if that is truly related to this topic, but seemed to be in my mind.

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now.
