### ISSUE TITLE
Footer window.resize

### ISSUE THREAD

**Issue by jflowers45** [uswds/uswds#1075]
On https://github.com/18F/web-design-standards/blob/18f-pages-staging/src/js/start.js
The following code fires an awful lot if you're resizing the window, when in reality it probably only needs to fire once the resize completes. 

$(window).resize(footerAccordion);

Would you be interested in a PR that implemented something like this?
https://css-tricks.com/snippets/jquery/done-resizing-event/

**Comment by maya** [comment]
Hi @jflowers45, thanks for opening this!

Looping in @rogeruiz and @msecret, do you think @jflowers45's approach would serve us well?

**Comment by msecret** [comment]
Hi @jflowers45. I agree that the event is firing too much, but I think the better approach is to find a way to eliminate the JS events altogether. We have a goal in our roadmap of "UI components are comprised of clean, semantic code" which this issue fits in well with.

**Comment by jflowers45** [comment]
@msecret sounds good.  Should I close this issue or leave it open for reference?

**Comment by msecret** [comment]
@jflowers45 let's leave it open for now, I've added it to the correct milestone.

**Comment by madmanlear** [comment]
I added #1134, which addresses this issue, but I agree that the js can be removed altogether. I'm happy to take a pass at a solution.

**Comment by maya** [comment]
Wanted to check in if this was still an issue?

**Comment by maya** [comment]
@el-mapache do you have any idea if this is still an issue?

**Comment by el-mapache** [comment]
@maya I'm not exactly sure what marco's comment above means, but the resize event is being debounced and fires what I think is a totally appropriate amount; I think we can close this.
