### ISSUE TITLE
Validators

### ISSUE THREAD

**Issue by DruidSmith** [uswds/uswds#1080]
Suggest adding validators wherever possible, for example date validator - or augment the existing control with a pop-up date picker.  Some other examples of form validation can be seen here:  http://formvalidation.io/validators/

Federal government should also consider provisioning a cross-agency geocoding capability that can validate addresses - validated addresses could then also be displayed in a map view.

For addresses, in some cases other types of data may need to be entered, where a conventional street address does not exist, for example remote/rural sites, which may only have descriptive locations such as PLSS Township/Section/Range or lat/long, or Puerto Rico, which often has milepost references, such as Carretera 34 KM 3.2 - federal government should have consistent guidance, tools and approaches for dealing with and validating those types of address fields.

**Comment by maya** [comment]
Hey thanks @DruidSmith, I've added this as a feature request and we'll see how this fits with our product roadmap: https://github.com/18F/web-design-standards/wiki/Product-Roadmap and component prioritization: https://github.com/18F/web-design-standards/wiki/Component-prioritization:-The-factors-that-guide-our-prioritization-process

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now. 

The geocoding is outside the scope of the project but we want to look into leveraging native HTML validation.
