### ISSUE TITLE
Text Input Hint Location

### ISSUE THREAD

**Issue by joshbruce** [uswds/uswds#1084]
Hello.

Developing reusable UI components for the program and wanted to make a recommendation.

I think the position of the hint for the Text Input element could be better served under the label, as opposed to under the input, for a more consistent pattern across the elements.

**Current Standards**

<img width="1033" alt="screen shot 2016-03-28 at 8 32 18 am" src="https://cloud.githubusercontent.com/assets/15252830/14077975/abf079bc-f4bf-11e5-8e33-4f514f6ac7d4.png">

**Proposed Alternative**

<img width="1019" alt="screen shot 2016-03-28 at 8 32 30 am" src="https://cloud.githubusercontent.com/assets/15252830/14077981/b63fc6a2-f4bf-11e5-8355-8e8df52b1e70.png">

**With Errors**

<img width="1080" alt="screen shot 2016-03-28 at 8 33 52 am" src="https://cloud.githubusercontent.com/assets/15252830/14077989/dc68cd60-f4bf-11e5-82fc-cac93e024397.png">

**Comment by Drakenhart** [comment]
It would also be better for screen readers, as it would make more sense contextually.

**Comment by thisisdano** [comment]
This makes a lot of sense.

**Comment by maya** [comment]
Agree :100:, but the USWDS does not recommend hint text below the input, so not sure what it's in regards to.
