### ISSUE TITLE
[Address form] add more context for use

### ISSUE THREAD

**Issue by carodew** [uswds/uswds#1087]
Adding this as a proxy for Rex Sanders from USGS, who is blocked from GitHub.
## 

Feedback on https://playbook.cio.gov/designstandards/form-templates/#address-form

This "Address form" causes stress and confusion for me.

All my mail goes to a US Postal Service PO Box. I don't receive USPS mail at home due to mail theft. I know many others in my area with the same setup.

The big header “Mailing address” conflicts with the field labels “Street Address” - those are two different things for me, and one cannot substitute for the other.

Do you intend to mail something via the US Postal Service or deliver something via UPS or FedEx? Those are mutually exclusive options for me.

Does this address need to match what’s in another database like drivers license, credit card, or property taxes? Depends on the database.

A form like this needs additional context, which I find lacking on many web sites.

And I struggle with every Amazon order and many other web purchases because they don’t tell you in advance how they deliver.

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now.
