### ISSUE TITLE
Add documentation about dependency files for each component

### ISSUE THREAD

**Issue by crwallace** [uswds/uswds#1146]
**Description**
For each component in the USWDS there is not way to tell if something will render and work correctly with only USWDS css files or if it also needs USWDS javascript files and if those javascript files are dependent upon other things like jQuery.

**Ask**
Please add any/all dependencies to the documentation for that component.

Please Document:
- [ ] css/js vendor files with version numbers, that are required for each component.
- [ ] which scss/css files are required for each component.
- [ ] which js files are required for each component.

**Additional Info**
Thanks so much!

**Comment by maya** [comment]
@crwallace thanks for submitting this issue! Our team is at an offsite so will be a little delayed. 

In general, if there's interactivity the component will likely need need javascript. You can find the javascript files broken out here: https://github.com/18F/web-design-standards/tree/18f-pages-staging/src/js/components. Seems like it's just the accordion, show/hide password (sign in and pw form), and password validator (password reset form).

Let me know if that helps in the meantime.

Agree that this should be clearer and hopefully will be soon!
