### ISSUE TITLE
Footer not sticky

### ISSUE THREAD

**Issue by jessieay** [uswds/uswds#1321]
## Description

I copy-pasted the "slim footer" code into my project that uses the US web design standards. The footer code works great on pages with enough content but on pages with content that doesn't use up the whole browser, there is white space below the footer and it looks weird. What I would like is for the footer to stick to the bottom.

Example of what it looks like now:

![screen shot 2016-07-13 at 10 22 26 am](https://cloud.githubusercontent.com/assets/601515/16812839/c7533b18-48e3-11e6-9a82-c05d7a9b81a1.png)

Rather than there being white space at the bottom, I'd like the footer to be at the bottom.

I tried doing this by setting the body of the web page to `positition: relative` and then giving it a bottom margin that is the same height was the footer. The problem with this was that the footer is responsive and so when the screen got smaller and the footer taller, the body and footer would overlap. 
## Steps to reproduce the issue
1. Add slim footer to page
2. View page without content or with minimal content
## Additional information [optional]

This blog post seems like a helpful guide on creating sticky footers that are also responsive: http://galengidman.com/2014/03/25/responsive-flexible-height-sticky-footers-in-css/

**Comment by jessieay** [comment]
I was able to fix this locally

see `app/assets/stylesheets/core/_layout.scss` at https://github.com/18F/micropurchase/pull/868/files

**Comment by maya** [comment]
I've done this on a few projects, it involves some creative use of flexbox: https://github.com/GSA/dotgov-home/commit/6d139af1f6f682dc895825060dd0bb54bf7c6236

**Comment by el-mapache** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.
