### ISSUE TITLE
[UI component]: Add destructive action link style

### ISSUE THREAD

**Issue by mebates** [uswds/uswds#1339]
## Description

It would be great if the standards had style for a destructive action link (cancel, reject, revoke, etc.) Typically just styled as a regular link with a red color. 
## Additional information [optional]

CFPB has a style at the bottom of their button section: https://cfpb.github.io/design-manual/page-components/buttons.html

**Comment by juliaelman** [comment]
Thank you for your interest and contributing to the Draft U.S. Web Design Standards! We have received notification of your contribution and are currently triaging the work.

**Comment by el-mapache** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.
