### ISSUE TITLE
[Documentation]: Add process and motivation to GitHub Wiki

### ISSUE THREAD

**Issue by awfrancisco** [uswds/uswds#1380]
## Description

Suggestion from Twitter. 
https://twitter.com/BernHyland/status/761438833506332672

> @18F Please consider adding to https://github.com/18F/web-design-standards/wiki … how design standards have evolved, who, when, how. Transparent process helps adoption

Since we've written so many blog posts, it's possible we could just link those instead of writing new documentation.

**Comment by kategarklavs** [comment]
@awfrancisco Hey! Thanks for sharing this. @jameshupp and I recently put together a comprehensive comms plan, and better sharing the Standards' history is one of our action items. On that topic, we're planning (in the next few months) to create a series of case studies, revamp the design principles page, and write more blog posts documenting the ideology underlying the Standards/the process our team follows, and why.

**Comment by maya** [comment]
Added to the wiki: https://github.com/uswds/uswds/wiki#history
