### ISSUE TITLE
[Website]: separating the code snippet placement for variations of a component

### ISSUE THREAD

**Issue by ericadeahl** [uswds/uswds#1425]
We've heard from multiple developers that it's confusing when there are multiple variations of a component displayed on the site, and then the code comes after. For example, in Tables, you see the Bordered Table and the Borderless Table within a gray box, then the code and documentation appear below. This is confusing because:
- The H6 titles of the component variations (ie BORDERED TABLE) aren't visually clear — they're not prominent enough and can easily be confused for part of the component (since they're inside the gray box.)
- Devs looking for the code snippets have to read through the code to find the variation they're looking for.

<img width="473" alt="screen shot 2016-08-29 at 7 43 33 pm" src="https://cloud.githubusercontent.com/assets/5911280/18071110/f8fe79f4-6e20-11e6-8dcd-d6a67a7210cd.png">

To address this, we should separate out the variations from each other. The new headers page is a model of how to address this:
- Any documentation that applies to all of the components on the page appears at the top of the page
- H6 titles turn to H2 titles, and should sit outside the gray box
- Code snippets and any documentation that is particular to a specific variation appear in an accordion under the component variation
- Since we're essentially bumping the variations up a level in hierarchy, they should also appear as navigation items in the side menu (for example, Tables should include side nav links for Bordered Table and Borderless Table)

There's a bit of complexity in where to apply this change, since some of the components have many small parts (ie Buttons.) My thought is that we can make the separation anywhere there's an H6 header - so on Buttons, there would be new sections for Primary buttons, Secondary buttons, Button focus, Disabled button, and Big button.

This change may also affect content: what documentation applies to all variations of a component? Is there new documentation that needs to be created for individual variations?

**Comment by el-mapache** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.
