### ISSUE TITLE
[Refactor HTML/CSS] Refactor sidenav component

### ISSUE THREAD

**Issue by juliaelman** [uswds/uswds#1436]
Reduce unnecessary specificity in sidenav component by de-nesting classe.

Refs https://github.com/18F/web-design-standards/issues/1342

**Comment by maya** [comment]
What needs de-nesting in the sidenav component? The SCSS seems pretty flat to me @msecret

**Comment by maya** [comment]
On another note, I chatted with @donjo before and talked about that there's a difference between the mixin and class name.

`@mixin usa-sidenav-sublist` vs `.usa-sidenav-sub_list`
(mixins can't have underscores)

What do we think about renaming the class to `.usa-sidenav-sublist`? @msecret
