### ISSUE TITLE
Media queries should probably be in em units

### ISSUE THREAD

**Issue by kaelig** [uswds/uswds#1469]
To respect the users' font-size setting, it is typically a good thing to set media queries in `em` (instead of `px` currently).

This article by @zellwk  sums it up very well: http://zellwk.com/blog/media-query-units/

> As you can see from our tests above, the only unit that performed consistently across all four browsers is em. There aren’t any differences between em and rem with the exception of bugs found on Safari.
> 
> `px` media queries performed well in two of the three experiments (with the exception of Safari, again). Unfortunately, `px` media queries remained at `400px` in the third experiment, which makes it a no-go if you intend to support users who change their browser’s font-size value.
> 
> Hence, my conclusion after these experiments is: **Use `em` media queries.**
> 
> If you’re using a library that doesn’t do em media queries, point the developer to this article so they know the implications of their code. Otherwise, feel free to switch to a em based library like [Mappy-breakpoints](https://github.com/zellwk/mappy-breakpoints), [Breakpoint-sass](http://breakpoint-sass.com/) or [sass-mq](https://github.com/sass-mq/sass-mq).

Being the author of sass-mq, I am obviously biased… But you may want to know that it was inspired by the way gov.uk handles media queries. It was built with content websites (News sites in particular) in mind – with two constraints: encourage a mobile-first design, and support IE8 with the minimum effort required. Happy to help answer any of your questions about it!

PS: thank you for open sourcing your code, it's awesome to have visibility on your workflow, practices, and code! Very inspiring.

**Comment by maya** [comment]
Hi @kaelig, thanks so much for opening this issue and bringing to our attention common practices in content/news websites. We'll be able to consider this more when we update our grids component.

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
