### ISSUE TITLE
[UI Component] - Footers class name refactor

### ISSUE THREAD

**Issue by donjo** [uswds/uswds#1505]
## Description

In reviewing the upcoming page template work I noticed that some of the class naming in the footers component is inconsistent. For example, the footers that use both primary and secondary sections use the classes

`usa-footer-primary-section`
`usa-footer-secondary_section`

I propose that they either be changed to 

`usa-footer-section-primary` and `usa-footer-section-secondary`
or 
`usa-footer-primary_section` and `usa-footer-secondary_section`

depending on how you interpret our suggested BEM style*

*someone who more regularly contributes to the frontend here could probably have a better explanation on which one would be correct

**Comment by maya** [comment]
via #2332:
>The footer has a few classes that are incorrectly named given our naming pattern. More information can be found in PR #2330
>
>Because renaming these without doubling up on the classes and leaving some deprecated ones behind would be a breaking change, we'll take care of this in 2.0

**Comment by maya** [comment]
Closed via #2583.
