### ISSUE TITLE
"An official website of the United States government"  Here's how you know  link or button?

### ISSUE THREAD

**Issue by davidstenger** [uswds/uswds#1525]
The "An official website of the United States government  Here's how you know" looks like a link but you coded it as a button. The article below may help.

[http://www.karlgroves.com/2013/05/14/links-are-not-buttons-neither-are-divs-and-spans/]

**Comment by maya** [comment]
The down-pointed arrow to the right of the button offers an affordance to indicate it's an interactive button (even though the text is styled similar to our text links). We haven't heard from users that this has caused a problem with using this element so will close for now. However, if you run into it being a problem for users, feel free to post it here and we can take another look. Thanks!
