### ISSUE TITLE
Please update https://standards.usa.gov/grids/ with full list of available grid css classes

### ISSUE THREAD

**Issue by westerjn** [uswds/uswds#1607]
Users can extrapolate that 1/2 is usa-width-one-half, so we can use:  
usa-width-one-half  
usa-width-one-third  
usa-width-one-fourth  
usa-width-one-sixth  

But now I'm guessing as to whether or not usa-width-seven-twelfths or usa-width-eleven-twelfths is valid or not.   
  
You will save some designers time and have eternal gratitude!

**Comment by juliaelman** [comment]
Thank you for your interest and contributing to the Draft U.S. Web Design Standards! We have received notification of your contribution and will add it to our backlog for future feature consideration.

**Comment by maya** [comment]
Hi @westerjn, the current grid system will be deprecated in version 2.0 so we will not be including any additional updates to its docs. Please see the new grid system: https://v2.designsystem.digital.gov/utilities/layout-grid/.
