### ISSUE TITLE
Standard alternating table row colors for reports

### ISSUE THREAD

**Issue by christyhermansen** [uswds/uswds#1636]
## Description

We are integrating a 3rd party business intelligence/reporting tool into our website and are creating a theme for the reports.  Alternating row colors really helps the readability of the reports.  Have you looked at a standard look and feel for reports.  The table look and feel doesn't work well for large reports.  

Also, we've tried using the grays from the standards for alternating rows. Gray-lightest is a little light to contrast with white on some screen and Gray-lighter is a little dark.  We would recommend something in the middle.  Do you have plans to introduce a recommended table style with alternating rows?

**Comment by juliaelman** [comment]
Thank you for your interest and contributing to the Draft U.S. Web Design Standards! We have received notification of your contribution and will add it to our backlog for future feature consideration.

**Comment by bruffridge** [comment]
We'd like a striped row table option as well.

Something like this:
https://getbootstrap.com/docs/4.0/content/tables/#striped-rows

**Comment by stphnwlkr** [comment]
@bruffridge We had the same requirement. I created https://github.com/stphnwlkr/USWDS-Extended/blob/master/_table.scss (I still need to update the color references).

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).

**Comment by sknep** [comment]
Just an update -- we recently added alternating horizontal row background colors to the USWDS Table component. Check it out here: https://designsystem.digital.gov/components/table/
