### ISSUE TITLE
Users Not Notified that JavaScript is Required

### ISSUE THREAD

**Issue by davidstenger** [uswds/uswds#1646]
**Issue**:
A user who has JavaScript disabled in their browser is not notified on the page that it is required. If JavaScript is required to be enabled in the user's browser, users with JavaScript disabled must be informed that JavaScript is required when they try to access any page of the site.

**Solution**:
If a user has JavaScript disabled when they try to access a page, alert the user that they have it disabled in their browser. This can be done by adding a <noscript> message. Similar to what is done on the Login Page. For example: <noscript>JavaScript must be enabled in your browser in order to use some SYSTEM_NAME_HERE functions.</noscript>

**Comment by maya** [comment]
Hi @davidstenger, thanks for opening this issue. To my knowledge, JavaScript is not required as the site components should be progressively enhanced. You should still be able to access critical information and functions without JS. Is there a specific instance that this is not the case?

**Comment by maya** [comment]
Noting that we go back and test each component without JavaScript to ensure it works as expected. Thanks.
