### ISSUE TITLE
add additional social media options

### ISSUE THREAD

**Issue by bruffridge** [uswds/uswds#1800]
Add additional [css](https://github.com/18F/web-design-standards/blob/develop/src/stylesheets/components/_footer.scss#L360) and [social-icons](https://github.com/18F/web-design-standards/tree/develop/src/img/social-icons) for Instagram and Flickr.

**Comment by juliaelman** [comment]
@bruffridge thank you for posting this issue. 

@bradnunnally going to pass this over to you. Thoughts on adding these two social icons as part of the footer?

**Comment by bradnunnally** [comment]
I think that's a great suggestion @bruffridge, especially for Instagram. I'd be hesitant to suggest Flickr since the future of that platform is unknown but I know a lot of agencies have a pretty deep library that's hosted there.

**Comment by bruffridge** [comment]
Thank you for considering this. Is there an icon library you use that you can point me to? In case you don't add Flickr, I can it to my fork. We do have an extensive library in Flickr.

**Comment by bradnunnally** [comment]
@bruffridge I'm not aware of original source of those icons, but h/t to @juliaelman for pointing out Instagrams branding assets which includes an icon we/you can use for the footer - https://en.instagram-brand.com/assets

**Comment by bruffridge** [comment]
Looks like flickr has a b/w version that would work as well, https://www.flickr.com/about/goodies/

**Comment by maya** [comment]
@bruffridge Added documentation on how to use additional social media icons here: https://github.com/uswds/uswds-site/pull/502 Let us know if this helps with or resolves this issue as well?

**Comment by maya** [comment]
Consolidating the convo from #1752 here. @fulldecent also requested Medium and GitHub options.

**Comment by bruffridge** [comment]
@maya This definitely helps, thanks! I might switch my social media icons to font-awesome for a cleaner look. https://www1.grc.nasa.gov/
