### ISSUE TITLE
Universal System Bar

### ISSUE THREAD

**Issue by philipashlock** [uswds/uswds#1859]
I'd like to propose there be some thought and use cases developed around a "universal system bar" component that would always be present at the top of the page. We can probably come up with a better name for this, but the current name for it in this design system is [The “official government site” banner](https://standards.usa.gov/components/headers/) while Android and Material design refers to it as the [System Bar](https://material.io/guidelines/layout/structure.html#structure-system-bars) and the iOS Human Interface Guidelines refer to them as [Status Bars](https://developer.apple.com/ios/human-interface-guidelines/ui-bars/status-bars/) and "system tray" or [Notification Area](https://en.wikipedia.org/wiki/Notification_area) is common terminology for desktop OS's. This is now a pretty standard UI convention on websites, particularly with user accounts and a logged in state as exemplified here on GitHub or with common uses of the [navbar component in Bootstrap](http://getbootstrap.com/components/#navbar), especially with user accounts or brands that span many different products and properties like Google's services. In addition to helping provide some minimal yet strong consistency across government websites and noting things like “official government site” a few other use cases for this could include: 

- Multilingual options (I think [EAC.gov](https://www.eac.gov/) has a good example of this)
- User login link and user account options when logged in
- Search box
- Notifications - I think this would present a much preferred UX convention to pop-ups and would be consistent with current mobile interface UX conventions. 
- Disclaimers, perhaps temporary urgent disclaimers, or as a place to indicate that you're visiting a beta version of a website or have reached a staging server instead of the official production site. Websites in the EU have a fairly common UX convention for the disclaimer about the EU Cookie policy. 
- System status alerts: If there's a backend service that might be temporarily offline or have degraded performance
- Links to get help, provide feedback, or reach a contact center or contact page

Back in the early days of MyUSA we were prototyping a related concept originally called the [MyGov Discovery Bar](http://beta.pif.gov/mygov/2013/01/15/Introducing-MyGov-Discovery-Bar/). The widespread adoption of standardized javascript components like DAP and through technologies like Google Tag Manager could also allow for some consistent dynamic behavior through this system bar as is often used in environments that span many different contexts. For example, if you changed your language to Spanish on one site, that preference could persist across other sites.

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
