### ISSUE TITLE
Looking for payment ui elements

### ISSUE THREAD

**Issue by annienguyenUSDS** [uswds/uswds#1860]
## Payment ui elements

I'm working on a USDS project and looking for credit card, credit card security back example and bank routing number examples to include to help people when filling out billing information. I was wondering if there are any or a place you can direct me to that use this or other teams I can also reach out to to get the same examples to use. 

Thanks!

**Comment by AndreaSigz** [comment]
Here's a first pass. Borrowed language from acq SOWs:

### Additional Requirements: 

- At sprint-wise intervals, the vendor will open issues that came as the result of usability testing by end-users.

- Contractor shall use US Web Design Standards.

- As part of the [Web Design Standards](https://standards.usa.gov/), contractor shall track web performance with a tool and clearly communicate to the government team when there is slow performance and options they have for improving the site’s performance.

- Tool to track web performance shall be free of cost, track a variety of metrics, with multiple implementation options, and a useful results format.

- All software code delivered under this order shall comply with the [18F open source policy](https://18f.gsa.gov/open-source-policy/) in effect as of the date of award.

- All software code delivered under this order shall comply with the [18F Accessibility Guidelines](https://pages.18f.gov/accessibility/) in effect as of the date of award.

- As part of this being purchased off of the Agile Blanket Purchase Agreement (aBPA), work will be conducted in one or two-week sprints and reviewed at the end of each sprint for acceptability per the Quality Assurance Surveillance Plan (QASP).

- All software code delivered under this order should be less than 10 mb total size; should complete download within 15 seconds; and should use http2.

**Comment by AndreaSigz** [comment]
Hi Annie,

My apologies - that comment was for another thread :(

I'm asking around beyond our team to see if there's anyone to send you to. Right now the Standards don't have any official guidance on it. I will reply to this thread by Thursday with any additional information.

Thanks!

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
