### ISSUE TITLE
[Typography]: Add heading helper classes

### ISSUE THREAD

**Issue by maya** [uswds/uswds#1868]
## Description

In some cases, people need to style heading elements to look like different headings (For example: an h3 element needs to look like an h4) bc they need to maintain document outline order to be accessible. By adding helper classes for headings, people will be able to easily style heading levels to suit the needs of the design, while keeping their code accessible.

**Comment by thisisdano** [comment]
This is related to our styling of base elements, which we know is causing problems. While I think there is room for helper/utility classes for sizing, we may want to extend its scope beyond headers (that is, have a more abstract system of type sizing that users could apply to any type element — like what I did [here](https://federalist-proxy.app.cloud.gov/site/18f/united/build/prototypes/type-scale.html) on cloud.gov/united) and make this change in concert with a change to how we handle base element styling.

**Comment by maya** [comment]
Addressed via a more abstracted[ font size](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-utility-docs/utilities/font-size-and-family/), though I think understanding which font sizes are appropriate for which heading levels would be helpful.
