### ISSUE TITLE
[Typography]: Add font variables for elements and components

### ISSUE THREAD

**Issue by maya** [uswds/uswds#1870]
## Description

Currently, the standards allows you to select a default font for sans-serif and serif, and the code used throughout the code base is based on the default Merriweather headings and Source Sans Pro. 

There needs to be another layer of abstraction when declaring fonts on elements. For example, by default the body font is `body { font-family: $font-sans; }` so if you want to change it you have to override it with CSS. It would be great if you could do this by updating your variable. So `body { font-family: $font-body; }` and  `$font-body: $my-custom-font`. When customizing fonts, this tends to be an issue with headings, body font, form labels, buttons, sidenav, navigation, and possibly more.

**Comment by thisisdano** [comment]
Two-level (or multi-level) variables are something I'd like to discuss as we move forward. That is, something like the relationship between `$var-role` (something more semantic) and `$var-value` (something more utility). This could be used for something like `$color-primary` and `$color-red`, where themes could be set up to access the semantic var, and the semantic var can be assigned a utility var (which may _or may not_ be, itself, assignable/mutable).

The utility vars would function something like a palette.

In general, though, there's a broader question about how we use abstraction to keep customizations to variables and out of custom CSS, which could have implications for ease of upgrade in subsequent versions.

**Comment by maya** [comment]
This looks like it's been implemented in 2.0: https://v2.designsystem.digital.gov/utilities/font-size-and-family/
