### ISSUE TITLE
Importing Accordion.js into Webpack2 build isn't Uglifying

### ISSUE THREAD

**Issue by thoughtassassin** [uswds/uswds#1969]
## Description

Recently the build of my project breaks when it is building a bundle.js. Uglifying fails. The error is: 
```
[INFO] ERROR in bundle.js from UglifyJs
[INFO] Unexpected character '`' [./~/uswds/src/js/components/accordion.js:11,0][bundle.js:56897,18
```
## Steps to reproduce the issue

1. Import Accordion from node_modules
2. Use the following module rule: 
```
           {
                test: path.join(__dirname, '.'),
                loader: 'babel-loader',
                exclude: /(node_modules)/,
                query: {
                    cacheDirectory: true,
                    presets: ['es2015', 'react']
                }
            }
```

**Comment by AndreaSigz** [comment]
Thx @thoughtassassin. @donjo or @msecret have any thoughts on this?

**Comment by toolness** [comment]
Hey, sorry for the late reply here... I'm *guessing* this might be an issue with babel/webpack configuration--judging by the unexpected character it's running into, it might not be transpiling the code to es5 before passing it on to uglify?  Another way to determine this may be by not uglifying it and checking the output--if it contains [string template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) (search for the backtick character) then it likely hasn't been transpiled to es5.

Based on the module rule you provided, it seems like it *should* be transpiled to es5, but webpack/babel can be extremely finicky about configuration; I've spent hours debugging my own configurations, unfortunately.

If you need further help, could you upload a ZIP file containing a minimum project that reproduces the error?

**Comment by maya** [comment]
Closing since there's no response from the issue opener.
