### ISSUE TITLE
Small text inputs become very confusing when AutoFill on Safari Desktop activates

### ISSUE THREAD

**Issue by asarazor** [uswds/uswds#1972]
## Description

Safari's AutoFill prompt takes up the entire input field if the field is short, like in the date input template. I was very confused about how to overcome this and enter a date that was not part of the AutoFill list. I don't imagine this would test very well with a broader audience.

This feels like a problem with Safari's implementation – putting the prompt within the text field – but the pain will be felt by the user anyway.

This can be avoided by [disabling autocompletion](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) if appropriate in the context of use, but is overkill of the template.

## Steps to reproduce the issue

1. Enable AutoFill on Safari `preferences->AutoFill->Using info from my contacts` and ensure it's using a contact card with a DoB.
2. Visit [form-controls/date-input on standards.usa.gov](https://standards.usa.gov/components/form-controls/#date-input)
2. Attain focus on first input field
3. Figure out what to do next if you don't want to enter you own birthday

## Additional information [optional]

![Screen shot of AutoFill Activated and consuming entire input field](https://user-images.githubusercontent.com/19854/26984863-144520f0-4d0f-11e7-8b6e-a4ce6129cb64.png)

**Comment by AndreaSigz** [comment]
Thx @asarazor! @donjo or @msecret any thoughts?
