### ISSUE TITLE
[Images]: Consider adding arrow-up and arrow-left PNG and SVG

### ISSUE THREAD

**Issue by line47** [uswds/uswds#1979]
## Description

I'm wondering if we can add SVG and PNG for `arrow-up` and `arrow-left` to accompany the `arrow-down` and `arrow-right` images here: 
- https://github.com/18F/web-design-standards/blob/develop/src/img/arrow-down.svg
- https://github.com/18F/web-design-standards/blob/develop/src/img/arrow-right.svg

I'm working on a jekyll site that is using the USWDS and would like to use `arrow-up` to show collapsed/expanded states of an accordion.

**Comment by maya** [comment]
Hi, thanks for opening this issue. We'll review this with our team and see how it fits on our roadmap. Stay tuned!

**Comment by maya** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.
