### ISSUE TITLE
Remove screen from media mixin

### ISSUE THREAD

**Issue by bruffridge** [uswds/uswds#1987]
Thoughts on removing screen from the media mixin in _utilities.scss so grid systems stay intact when printing webpages?

**Comment by AndreaSigz** [comment]
Thanks @bruffridge. @donjo or @toolness any thoughts?

**Comment by maya** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.

cc @thisisdano to check if new media mixin has screen or not.
