### ISSUE TITLE
Mobile navigation menu allows tab focus outside of menu

### ISSUE THREAD

**Issue by toolness** [uswds/uswds#2031]
I'm not sure if this is actually an unintended bug or an intended feature, but I figured I'd document it here just in case.

Basically, when in the mobile navigation menu, the user can <kbd>Tab</kbd> the keyboard focus outside of the menu, into the dimmed content of the actual page.

The menu essentially seems to function like a dialog box, and behaves much like one from a mouse/touch standpoint, since taps/clicks outside the menu collapse it, so we might want to make sure it behaves like one from a keyboard standpoint as well.

Doing this is a bit of a lift--see Rob Dodson's [Modals and Keyboard Traps](https://www.youtube.com/watch?v=BoAsayPVogE) video of the [A11y Udacity class](https://www.udacity.com/course/web-accessibility--ud891) for full details--but could help provide the infrastructure we need for providing accessible modals in the future, too (see #911 / #1477).

While we're at it, we might also want to add support for using <kbd>Esc</kbd> to get out of the nav menu too.

**Comment by maya** [comment]
Here is the code for that tutorial: https://github.com/udacity/ud891/blob/gh-pages/lesson2-focus/07-modals-and-keyboard-traps/modal.js
