### ISSUE TITLE
Sass can't easily be used when installing via npm + git

### ISSUE THREAD

**Issue by toolness** [uswds/uswds#2032]
I was trying to create a sample project that used USWDS via the bleeding-edge version on GitHub, rather than the latest official release on `npm`.  However, when I tried to use USWDS's SASS, it failed to compile because the vendor SASS files (e.g. Bourbon) weren't in their expected locations at `lib/bourbon`.

It would be nice if this could "just work" so that folks could easily have projects that use a branch of the standards from git, rather than being required to either use an npm version or use `npm link`.

I'm not sure what the best way to do this is. I noticed that Blendid just adds `node_modules` to the SASS path; if we do that too, we could potentially import our dependencies via their path from `node_modules`.  For example, Bourbon could be loaded via:

```sass
@import "bourbon/app/assets/stylesheets/bourbon"
```

Then folks who wanted to use USWDS via git could install bourbon as a peer dependency, at least... As things are now, they would somehow have to get `@import "lib/bourbon"` to work, which would likely mean manually setting up some kind of gulp-ish task.

Another alternative might be to add all SASS dependencies to `dependencies` (they're currently in `devDependencies`, and then add a `postinstall` task that basically does what `gulp copy-vendor-sass` does.

**Comment by maya** [comment]
Since this issue is primarily about the vendor Bourbon files not being in the right location when using git to load the uswds and we plan to remove Bourbon #2694, this can be closed.
