### ISSUE TITLE
[HTML5 tags]: Prefer HTML5 tags in code examples

### ISSUE THREAD

**Issue by jordangov** [uswds/uswds#2049]
## Description

There are many code examples across the UI Components section which use outdated HTML tags (mostly a lot of `div`s). This issue is a holding place for a task to sweep the code examples and replace `div` tags with the semantic HTML5 appropriate tag (`nav`, `main`, `section`, `aside`, `header`, `footer`, etc)

This will set a precedent for proper modern HTML standards and also supports older browsers in case required. Browsers default unknown tags with `div` styles.

## Additional information

Some specific examples:
* [side navigation](https://standards.usa.gov/components/sidenav/)
* [accordions](https://standards.usa.gov/components/accordions/)

**Comment by AndreaSigz** [comment]
Thanks @jordandds. @donjo @atul

**Comment by msecret** [comment]
I definitely think this could be done in some areas. We'd have to be careful of using context-based tags, like `aside`, `main` for certain components because the components could be used in different contexts. For example, somebody might use the accordion for nav, but it could also be used in main content.

**Comment by maya** [comment]
I know somewhere it was mentioned the side navigation using the `nav` element, but what did the accordion need?

**Comment by jordangov** [comment]
The accordion is all div's now... but probably should be a `<main>` along with `<section>`'s and then (IMO) `<header>`'s versus using a button.

**Comment by maya** [comment]
A `main` makes sense (and perhaps `section` too). I think the button is fine to get the accessible features from it, ideally, we could use a heading but we don't know what heading level someone would need and could see it leading wrong heading levels from copy + paste.

See Heydon Pickering's Collapsable Sections:

```
<main>
  <h2>
    <button aria-expanded="false">
      Section 1
      <svg aria-hidden="true" focusable="false" viewBox="0 0 10 10">
        <rect class="vert" height="8" width="2" y="1" x="4"/>
        <rect height="2" width="8" y="4" x="1"/>
      </svg> 
    </button> 
  </h2>
  <div hidden>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo purus quis mi cursus hendrerit eu eu metus. Aliquam aliquam arcu eget aliquet scelerisque. Pellentesque sodales turpis vitae venenatis vehicula. Ut id porta velit. Ut eu dignissim dui, quis gravida est. Cras quis venenatis mauris, a bibendum enim. Sed at augue libero. Nullam tortor metus, tincidunt ut urna id, posuere placerat orci. Ut quis risus dictum risus facilisis imperdiet quis sed eros.</p>
  </div>
...
</main>
```
https://inclusive-components.design/collapsible-sections/
https://codepen.io/heydon/pen/QqzRvQ

**Comment by jordangov** [comment]
could just be this too: `<header><button> ... </button></header>` (cuts out the need to determine header level)

**Comment by jordangov** [comment]
I would also argue that internal `div` could be a `section` or `article`

**Comment by maya** [comment]
We can try that, thanks 👍

**Comment by maya** [comment]
Here's the PR for the sidenav: #2359

**Comment by maya** [comment]
@jordangov I pushed up the accordions, but I'm seeing this accessibility violation on a page with all the components:
>The main landmark should not be contained in another landmark
via https://circleci.com/gh/uswds/uswds/2111

https://dequeuniversity.com/rules/axe/3.0/landmark-main-is-top-level

Let me know if you have any background on this or if it's a false positive.

**Comment by jordangov** [comment]
commenting on the PR...

**Comment by maya** [comment]
This is done in #2360. Thanks for your help @jordangov!

**Comment by jordangov** [comment]
Thanks!
