### ISSUE TITLE
NSF interview 

### ISSUE THREAD

**Issue by yowill** [uswds/uswds#2074]

**Comment by AndreaSigz** [comment]
- [ ] Conduct interview with Scott Weber about NSF Seed Fund

- [ ] Write up interview

- [ ] Send to Scott & NSF to review

- [ ] Incorporate any edits & publish

**Comment by AndreaSigz** [comment]
This needs to be published with the next release.

**Comment by AndreaSigz** [comment]
Yes, let me find them

**Comment by AndreaSigz** [comment]
Here's NSF. It's ready to go: https://docs.google.com/document/d/16-HzoF66_76inYCt9SvUjbSrE1WPtWF035NU_bgT2Bo/edit#heading=h.x2xmev4dqks

**Comment by maya** [comment]
Published in https://github.com/uswds/uswds-site/pull/505.
