### ISSUE TITLE
[Add font-size for headings/leads when on small screens]:  Size headers more appropriately for screen size

### ISSUE THREAD

**Issue by line47** [uswds/uswds#2089]
## Description
Gain more screen real estate for smaller screens by setting some defaults to reduce the size of header and lead text at smaller screens and increasing them at medium breakpoints and up. 

A variable could be used to divide the text size across the headings. Something like `$small-screen-font-size-divisor: 1.3` then that variable could be applied to all headers to bring the size of the text down when on smaller screens then at larger screens the text size returns to something larger.
```
h1 {
  @include h1();
  font-size: ($h1-font-size / $small-screen-font-size-divisor);
}
```

## Screenshots to show difference in visible content 
The left scaling all headers and lead text down and the right is the current state of headers at small screens.

<img width="792" alt="small screen headers" src="https://user-images.githubusercontent.com/1449852/28851806-e2f3b3dc-76d9-11e7-9afb-655c7a1424f2.png">

**Comment by maya** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.
