### ISSUE TITLE
Notify downstream users to update their govbanner text around .gov domains and HTTPS

### ISSUE THREAD

**Issue by konklone** [uswds/uswds#2093]
To follow up on #1738, #1748, and https://github.com/18F/web-design-standards-docs/issues/315, I think it's worth a proactive communication to users of USWDS to update their banner text to the corrected version.

A couple USWDS users I've spotted with incorrect banner text:

* https://www.usda.gov (noticed because a non-government public user pointed it out to me)
* https://developer.login.gov
* https://sites.usa.gov/
* https://federalist-docs.18f.gov/

I haven't tried to do a thorough inventory or anything. I think it's worth proactively notifying the community with instructions on how to update their banner with the corrected text. I'm happy to support that effort.

**Comment by konklone** [comment]
Also, the USWDS homepage itself has incorrect banner text:

* https://standards.usa.gov

How can we resolve this? I believe inaccurate text on a banner designed to assure users of the authenticity of federal content is a significant issue, and it affects our technical credibility.

**Comment by AndreaSigz** [comment]
@donjo @toolness

**Comment by donjo** [comment]
@konklone started an issue for updating it on the standards site. 

https://github.com/18F/web-design-standards-docs/issues/374

**Comment by toolness** [comment]
I've created a new project called [uswds-crawler](https://github.com/18F/uswds-crawler) which will make it easier for us to scan USWDS sites for deprecations like this. Will add some functionality to make it specifically find sites w/ this issue and post back here once I've got a list.

**Comment by toolness** [comment]
Ok, it looks like the following additional sites are using old gov banner text:

General Services Administration Office of Evaluation Sciences website (https://oes.gsa.gov/)
SBA Certify (https://certify.sba.gov/)
USAJOBS.gov Design System (http://usajobs.github.io/design-system/)

**Comment by konklone** [comment]
Niiiiiiice

**Comment by toolness** [comment]
Thanks! I just added functionality to load sites that don't have any `usa-` classes in headless Chrome, as a way to support single-page apps that load their initial content dynamically, and found another site that's using old gov banner text through it:

FAR Data Collection Pilot (https://fardatacollection.sam.gov)

**Comment by maya** [comment]
Still needs updated text:
- [ ] https://www.usda.gov
- [ ] https://oes.gsa.gov/
- [ ] https://certify.sba.gov/ (although the banner doesn't open)
- [ ] http://usajobs.github.io/design-system/
- [ ] https://fardatacollection.sam.gov

Sites no longer exist:
https://developer.login.gov
https://sites.usa.gov/

Already fixed:
https://federalist-docs.18f.gov/

**Comment by konklone** [comment]
The correct URL is https://developers.login.gov, which still exists.

**Comment by maya** [comment]
@konklone all the sites with public GitHub repositories have PRs with fixes submitted. For the rest, I've notified them by email. Thanks for bringing this up!

**Comment by thisisdano** [comment]
Reopening to put on the near-term roadmap.

**Comment by thisisdano** [comment]
Closing this, as it's more of an ongoing issue, and we probably won't be able to make a real long-term impact here until we introduce a templated, web components version of the banner that makes updating a bit more straightforward
