### ISSUE TITLE
Column widths of: 1/5, 1/7, 1/8, 1/9, 1/10, 1/11

### ISSUE THREAD

**Issue by dalesthill** [uswds/uswds#2094]
## Description

Adding additional fractional width columns would provide flexibility when dynamically generating a number of UI components to fully fill a container.

## Additional information

/_grid.scss

  .usa-width-one-fifth {
    @include span-columns(2.4);
  }

  .usa-width-two-fifth {
    @include span-columns(4.8);
  }

 .usa-width-three-fifth {
    @include span-columns(7.2);
  }

**Comment by AndreaSigz** [comment]
Thanks @dalesthill. @donjo @toolness

**Comment by maya** [comment]
The current grid will be deprecated in favor of this grid system in version 2.0 which should have much of what you're looking for. See: https://v2.designsystem.digital.gov/utilities/layout-grid/ for more info.
