### ISSUE TITLE
Refresh “who is using USWDS” page to reflect the types of users

### ISSUE THREAD

**Issue by yowill** [uswds/uswds#2134]
- [ ] Divide the page up into sections based on site types 
- [ ] Turn into a YAML file 
- [ ] Update docs site to categorize sites appropriately

**Comment by toolness** [comment]
Oh, the one potential downside of converting the markdown to YAML is just that it won't be quite as human-readable, on GitHub at least.  In fact, if we convert it to YAML, we might just want to move it over to the docs repo, instead of keeping it in the USWDS repo... hmmmm.
