### ISSUE TITLE
Update form elements

### ISSUE THREAD

**Issue by rtwell** [uswds/uswds#2136]
I dropped the ball on documenting these visual changes—sorry!

![image](https://user-images.githubusercontent.com/12564977/29838450-da200146-8cc0-11e7-8f74-d65958559b69.png)

#### Error state
- [ ] remove vertical rule
- [ ] add the red SVG `!` to the right of the form field 
- [ ] red `#cd2026` rule around the form field should be 2px
#### Success state
- [ ] add the red SVG `checkmark` to the right of the form field 
- [ ] green `#2e8540` rule around the form field should be 2px

**Comment by nolawi** [comment]
I can take this if that is ok @rtwell

**Comment by joshbruce** [comment]
I appreciate this move a great deal. Will the marks be "against" the text input itself?

The reason I ask is that I have made a generic pattern out of all the form controls. So, putting it on the error wrapper would cause checkboxes to look really odd. :)

**Comment by nolawi** [comment]
I will follow the pattern and have you review the PR

**Comment by sawyerh** [comment]
Heya, just wanted to see where this lands on the roadmap for you all and if this is definitely the path you think you'll be going down with this design? We're currently working on implementing validation on our site and will probably go with this updated design if it's something that will be making it into the Standards in the future.

**Comment by maya** [comment]
@thisisdano: see @sawyerh's comment above.

**Comment by sawyerh** [comment]
Just to be even more of a headache, here are two cases where something like a floating icon might be problematic for our current use case:

1. Fields that span the entire width of a "card"
2. Grouped fields, like the date pattern

A few workaround might be placing the icon "within" the field, or offering a modifier class that doesn't place the icon on the invalid field?

![image](https://user-images.githubusercontent.com/371943/33681156-bc0e82ee-da91-11e7-90b0-ee31ec71c735.png)

**Comment by thisisdano** [comment]
@sawyerh At this point, I would consider this proposal more of a design exploration and not something we consider on the roadmap. The constraints you mention (and others) definitely impact the resilience of this solution, and — at least for now — this is a solution in search of a problem.

**Comment by maya** [comment]
Also, @sawyerh if you do decide to go this route (or another route), please let us know how it tests with users and the problem it solves. That will help inform a possible design solution.

One problem the proposed solution solves is developer convenience: it means you don't have to wrap the input in an element to style the left border. But I'd rather we chose a solution that responds best with end-users rather than developers.
