### ISSUE TITLE
Guidance for downloadable files (e.g., PDFs) including icons and file sizes

### ISSUE THREAD

**Issue by danamuses** [uswds/uswds#2163]
I'd like to see guidance on the use of icons to indicate file types for downloads (e.g., PDFs) and whether/how to style information such as large file size / pages.

**Comment by maya** [comment]
Hi @danamuses, thanks for opening this issue. We'll review this with our team and see how this fits on our roadmap.

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).

We do suggest Font Awesome for icons. See https://designsystem.digital.gov/components/icons/
