### ISSUE TITLE
Remove default antialiasing from header navigation links

### ISSUE THREAD

**Issue by andrewmaier** [uswds/uswds#2172]
My hunch is that the USWDS should be as stylistically agnostic as possible while providing a solid baseline for teams implementing web design standards (HTML, CSS, Javascript) into their projects. 

In keeping with that spirit, I would recommend the team remove the default font-smoothing (`-webkit-font-smoothing: antialiased`) on `.usa-nav-link` elements. This is something I noticed recently on the plainlanguage.gov redesign:

![image](https://user-images.githubusercontent.com/2970/31404044-e4ef45ae-adc8-11e7-9cbd-0a59fa540594.png)

Instead, I'd suggest that this rule be eliminated (in effect,`-webkit-font-smoothing: auto`) so that browsers can choose the appropriate default. I brought this issue to the attention of @hursey013 and then discussed it with @maya, who suggested I file this issue :)

**Comment by maya** [comment]
This is probably a good idea. Just need to review where it stands in the roadmap and verify that we're not degrading things design-wise. We'll need to check how this looks with the default bold nav items with and without the dark background (from the dropdown).

**Comment by AndreaSigz** [comment]
Thanks @andrewmaier for documenting this!

**Comment by andrewmaier** [comment]
I believe this issue may be related to this antialiasing as well:

![image](https://user-images.githubusercontent.com/2970/31461186-c2554286-ae96-11e7-82bd-883266dfd1eb.png)

**Comment by maya** [comment]
@andrewmaier thanks, yeah we used that technique for light text on dark backgrounds as described by http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/ "Antialiasing is useful for certain circumstances, such as for light on dark text...", but maybe we should re-review this or only do it on bold text.

**Comment by maya** [comment]
@andrewmaier just checked and https://github.com/18F/web-design-standards/issues/2172#issuecomment-335917410 is on their codebase, not USWDS, but thanks for sharing.

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
