### ISSUE TITLE
[Links]: External link icon color

### ISSUE THREAD

**Issue by joshbruce** [uswds/uswds#2185]
There was a conversation about the external site icon color looking strange for the visited link (purple versus blue).

https://youtu.be/ZrRRMBaz5Z0?t=14m25s

Here's something I didn't know existed: `currentColor`. For SVGs it will set the fill color to the text color. The PNG fallback would remain the same, but I think we might be getting to a usage point where we don't really need the fallbacks anymore (http://caniuse.com/#search=svg, http://caniuse.com/#feat=svg-css). 

@maya - You were in the external links thread, I think.

@msecret - You might find Tailwind CSS interesting. I haven't gone too far into it, but it seems more like Bourbon the Bootstrap. (Check the YouTube video.)

https://adamwathan.me/css-utility-classes-and-separation-of-concerns/
https://css-tricks.com/currentcolor/

**Comment by maya** [comment]
@joshbruce thanks for opening this issue! When I tried the `currentColor ` technique, it used the text color, not the link color. This may be bc we're using a psuedo-element (`:after`) and background image and not putting the SVG directly in the HTML, but I'm not sure.

**Comment by joshbruce** [comment]
I ran into a similar issue when trying to use the fill color on the SVG concept. I am starting to think it may just not be necessary (see other thread with @thisisdano, at least I think that's who it was).

When the web was new we really needed to orient users to what was going on and what was going to happen; now, I'm not so sure. Every link in Facebook (and many others), for example, go to different sites *and* open in a new tab/window. Makes sense given that you may want to like or comment on the position you were in within the feed. Back in the day opening new tabs/windows was also frowned upon because users would get lost - "I thought I was in this window, but I wasn't". Doesn't seem like that's the case too much anymore. I think Wikipedia still does it because it's the default format for their Markdown parser with footnotes.

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).

**Comment by aduth** [comment]
We've [recently encountered this](https://github.com/18F/identity-idp/pull/5300#discussion_r692477855) as well in our project. @thisisdano Would you be open to a contribution implementing this using the [newer CSS mask-based mixins](https://github.com/uswds/uswds/blob/e1c3a1bcaa89656892b56dad07e353e7ac07a0f8/src/stylesheets/core/mixins/_icon.scss#L66-L150), if it's possible?
