### ISSUE TITLE
Use a sharper, more consistent flag for banner and favicon

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2190]
Transferred from #2033 to handle in-house.

- - -

I think there are good arguments to make about how we display our flag. How do we best preserve the legibility of the flag at small sizes? It's impossible to reproduce a fine level of detail at certain levels of scale, and the art of iconography is in capturing the essential and removing everything else. 

**Success criteria**
- Crisp and clean at the favicon size of 16x16 pixels (or 32x32px displayed as 16x16px)
- Use the same image for the official banner that we use for the favicon
- Clearly reads as the United States flag with no magnification

**Constraints**
- The aspect ratio of the official US flag is essentially 2:1 ([actually 1.9:1](http://www.ushistory.org/betsy/flagetiq3.html)) 
- 7 red bars and 6 white bars, alternating, starting and ending with red
- 50 white stars in a blue rectangle (the union): aspect ratio 1.4:1
- The union height is 7 bars (red to red)

**Solutions**

Scaling down a standard US flag results in a muddy image without clear distinction between the bars, and complete dissolution of the stars. (FYI, it's hard to display this with pixel fidelity in the following screenshots, and every screen has different display density.)

![Screen Shot 2017-10-25 at 12.24.51 PM.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/4dc18e84-cd39-467d-8501-395b09e9ed55)

While this is an "accurate" flag, it doesn't read as accurate. The stars and bars both are reduced to soup. How might we rebuild the flag file to make it read better? Assigning each bar to a single pixel gives a clear distinction between bars, but requires changing the number of bars. Getting closest to the accurate 2:1 ratio results in a flag with 9 bars:

![Screen Shot 2017-10-25 at 12.22.54 PM.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/f887ca63-1c8e-4ac2-9fec-13d2a0e0f1a0)
![Screen Shot 2017-10-25 at 12.39.01 PM.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/24804367-5caa-41ea-82c1-61669ff9966c)

To my eye, this reads as too few bars, and the resulting union is too small to display many stars. Moving to 11 bars results in a flag that's closer to my mental image of the flag:

![Screen Shot 2017-10-25 at 12.23.23 PM.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/9c98cd48-d134-49f5-a9f0-2d893e9cfc34)
![Screen Shot 2017-10-25 at 12.37.34 PM.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/9a559cd1-093e-4a76-8493-7db4c7bfc646)

Additionally, an accurate flag reads as too dark and unsaturated at small size. You could be forgiven for thinking the flags below were reproduced in grayscale, particularly at a glance, and if the brightness on your machine is turned down:

![Screen Shot 2017-10-25 at 1.04.49 PM.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/f55fee3b-9720-48ab-9819-6c8148b843b6)

This brighter version reads more clearly as red at small size. (And I should be clear that the changes are explicitly for very small sizes. They don't hold up at even double the size.):

![Screen Shot 2017-10-25 at 1.11.19 PM.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/b3a2a412-879f-41f7-8be7-62bdf8d783df)

- - -

I know that facts matter, and the flag is the flag is the flag, but in a specialized display environment there are compromises, and as a visual designer I'm focussed on the experiential, and most often hew to the "adhere to the spirit of the law rather than the letter of the law" dictum. And in the mind's eye, the flag looks something like this:

![Screen Shot 2017-10-25 at 12.51.30 PM.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/b0c18f5d-ad2d-42a2-842d-459d11784ae7)

Clear red and white bars, a blue squarish rectangle in the upper-left corner from red bar to red bar with some number of distinct stars set in an offset pattern inset from the boundary, all inside a flag that's more rectangular than an old tv, but less rectangular than a new one.

And all this leads me to suggest a small flag very similar to the flag we currently use:

![Screen Shot 2017-10-25 at 1.18.02 PM.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/310adf62-189c-40e0-9c90-af2cac06aaa5)

But what I might suggest is that we build a cleaner, sharper version (or versions) and do a better job of controlling its display (by, say, limiting its width in the banner to 16px). 

And while I'm being something of an apostate, I may as well say that I'd be open to using a high-contrast black and white version of the flag icon in certain situations. I just want to work to honor the spirit of the flag and present it in the best possible light over multiple display environments. 

:us:

**Comment by tbolt** [comment]
Appreciate the deep dive into this. Another thought I had would be to just use the USA Flag emoji? 🇺🇸

**Comment by jondandois** [comment]
This is all very well thought out, but I think it misses very important context: This flag is to be shown with the text  "This is an official website of the United States government".  

Given this context, it seems that this should be an official flag of the US and not a stylized abstraction.  
![image](https://user-images.githubusercontent.com/21109842/34830768-e67d4686-f6b2-11e7-8b7a-7f4d465a2f54.png)

**Comment by jondandois** [comment]
With the 2018 Winter Olympics underway and seeing the USOC logo with a 13-star American Flag, I thought it would be a good opportunity to push this issue again.  As you might notice from the current and 2016 Olympics, the US team logo uses the 13-star American Flag.  https://www.teamusa.org/brand-usage-guidelines

I only noticed this during the current round of Olympics and wondered at the reason behind this design choice.  While I could not find another official source from within the USOC, I did find this article from the Chicago Tribune August 2016 where the USOC's chief marketing officer is quoted as saying "We use the 13-star, which is an official American flag, on our logo because of sizing," http://www.chicagotribune.com/sports/international/ct-olympic-logo-flag-13-stars-spt-0811-20160810-story.html

Given this, I pitch to USWDS again:  **Why can't an official US flag be used for this icon?**  
Arguments about blurry images and re-sampling from scaling seem to be at odds with the concept of an SVG and the fact that screen resolutions / pixel density continue to increase and are unlikely to decrease. Certainly, if the main argument is that "We still want someone to SEE the stars and stripes, even when the flag is small", then there are many real and official US flags that would suffice.
 
I'd even go so far as to quote USWDS on another topic of misrepresentation in government and point out  #2240  regarding the use of the word "Standards" in the name of the project: 
```

**Comment by maya** [comment]
Hi @jondandois, thank you for your comments. We all can agree that we want to convey the true meaning of the US flag to people seeing at the icon. To do this, it's important for us to have a legible icon which almost immediately conveys its meaning.

>Arguments about blurry images and re-sampling from scaling seem to be at odds with the concept of an SVG and the fact that screen resolutions / pixel density continue to increase and are unlikely to decrease. 

We need to support the ico file type which uses a 16px icon at the minimum. The actual US flag would be blurry as shown above. When used on the site as an SVG, the human eye would not be able to discern the actual flag in all its detail at this size. We also consider folks with vision impairments that are hard of seeing and are committed to using an icon that people with disabilities can see clearly. Lastly, it's industry practice in icon design to use the appropriate fidelity of an icon at different sizes. At the smallest size, icons need a lower fidelity and simplest shapes and can potentially increase fidelity as size increases. 

For example, Iconic has three different sizes for icons depending on its size:
https://useiconic.com/guides/using-iconic-responsively/
https://webdesign.tutsplus.com/articles/all-about-responsive-iconography--webdesign-16232

>I'd even go so far as to quote USWDS on another topic of misrepresentation in government and point out #2240 regarding the use of the word "Standards" in the name of the project:

We've recently changed the name of the project to the U.S. Web Design System. You can read more about it here: https://designsystem.digital.gov/whats-new/updates/2018/01/17/changing-our-name/ 

Thanks again for your comments and I hope this better explains some of our reasoning.

**Comment by jondandois** [comment]
Thanks @maya for those insights. I appreciate that you all have a far better perspective on the concept of iconography than I do, but it seems that there are two conflicting uses of the US Flag, one is for the favicon.ico and one is for the US flag image in the banner "This is an official website of the US Government"

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
