### ISSUE TITLE
Remove scoped styles from Fractal

### ISSUE THREAD

**Issue by donjo** [uswds/uswds#2196]
On a few different components within fractal we use `<style>` to implement styles specific to the code preview [Grid](https://components.standards.usa.gov/components/detail/grid--default.html) is one example). Because these aren't really part of the USWDS we don't want them to show up in the code sample sections on `standards.usa.gov`. We should probably either parse these out or find a different way to style the code previews to separate "real" code from temporary cosmetic things. 

## Components

- [x] src/components/_uswds-header.njk -- the only use for the file is for showing primary and secondary navigations which is not even shown on the preview of the fractal site or on the uswds-site
- [x] src/components/01-type/fonts.njk -- not being pulled in into the uswds-site - OK to ignore
- [x] src/components/02-buttons/buttons.njk -- very minor inline style used to display dark background width. OK to ignore.
- [x] src/components/09-header/header.njk -- this is the ALL headers page. it's not used on the uswds-site so can ignore
- [x] ~~src/components/grid/grid--offsets.njk~~ N/A grid component removed - moved to utilities
- [x] ~~src/components/grid/grid.njk~~ N/A grid component removed - moved to utilities

**Comment by maya** [comment]
The way I'm hearing this can be done:
>you could specify a preview template with an extra element (f.e. `<div class='scope'><your pattern will be rendered here></div>`, and attach the extra background styling to the .scope. Preview template markup is not rendered when the partial is embedded, so the div.scope won’t be there when rendered.

It sounds like we'd need to create a preview template for each component that has scoped styling.

**Comment by maya** [comment]
Looked through each component referenced and found that almost all instances of a scoped style is not shown on the uswds-site and has no effect to the end-user so this issue can be closed. Findings posted in the first comment.
