### ISSUE TITLE
Update Grid example to use fractal_component

### ISSUE THREAD

**Issue by donjo** [uswds/uswds#2197]
after #2196 is completed the docs site should be updated to use the sample code from fractal. 

Additionally, add grid offsets to the example on the docs site.

**Comment by maya** [comment]
I see `{% include code/accordion.html component="grids" %}` on the grids page. Does this mean we're using the fractal code?

**Comment by donjo** [comment]
Not currently. For the docs site to be using the code sample from fractal `_includes/code/components/grids.html` will need to have its contents replaced with 

`{% fractal_component grid %}`

I believe the blocker was trying to come up with a better way to contain the styles so the grid example would look like it does on [designsystem.digital.gov](https://designsystem.digital.gov) instead of the way it looks on [components.designsystem.digital.gov](https://components.designsystem.digital.gov)

**Comment by maya** [comment]
I see, bc we didn't want `<style scoped>...` inserted on the docs site.

**Comment by donjo** [comment]
Yeah, though there are a few other pieces too. The docs site has some custom CSS that's serving the same role as the styles in `<style scoped>` so just references the fractal code directly creates something that's a little off. That would need to be cleaned up a bit.

![screen shot 2018-02-06 at 4 13 25 pm](https://user-images.githubusercontent.com/776987/35887053-a934b57e-0b58-11e8-8647-66e2f0123e0d.png)

One of the ways we talked about doing this in the past was to put a wrapper class around fractal examples so you could clearly write custom styles that only affect the output of sample code (something like `.fractal_example > .usa-grid > * > *`)

**Comment by maya** [comment]
This is done in #2551 and https://github.com/uswds/uswds-site/pull/572 🚢
