### ISSUE TITLE
[Typography] Improve typography spacing

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2215]
**User story**: As a developer using the USWDS, I'd like typography to consistently display proper margins in different use cases (from simple layouts to complex grids).

### ✅ Ideal visual, margins collapse, single div. 
Top and bottom margins on headings and paragraph text
<img width="925" alt="screen shot 2018-08-16 at 1 39 31 pm" src="https://user-images.githubusercontent.com/5249443/44233865-e1f6a880-a159-11e8-9e49-8a58ab3c7160.png">

### ✅with divs wrapped around the heading and p text, with a single background color
<img width="966" alt="screen shot 2018-08-16 at 1 46 13 pm" src="https://user-images.githubusercontent.com/5249443/44234130-a90b0380-a15a-11e8-917c-f9193c772edb.png">

- pretty good with white background

### ❌but when you want to add color to the section, the margins mess it up and don't allow the divs to be filled with color equally 
<img width="970" alt="screen shot 2018-08-16 at 1 45 34 pm" src="https://user-images.githubusercontent.com/5249443/44234152-ba541000-a15a-11e8-813d-fef080726f3b.png">

### ✅removing top and bottom margins of divs fixes this (currently behavior in USWDS)
![36122745-59710eba-0fff-11e8-9c00-73650204475c](https://user-images.githubusercontent.com/5249443/44234227-f25b5300-a15a-11e8-87dd-b7f840e6dcfa.png)
- works well when you add padding between sections

### ❌But when you use a single background without additional sections to add space between, they are collapsed with each other 
<img width="968" alt="screen shot 2018-08-16 at 1 49 44 pm" src="https://user-images.githubusercontent.com/5249443/44234346-377f8500-a15b-11e8-8ad9-c68ae1626a55.png">

## Potential solutions
1. #2343 - only use top margin on `p` text, and remove top and bottom margins of first elements inside certain elements https://github.com/uswds/uswds/issues/2215#issuecomment-365080405
2. GOV.UK uses contextual adjustments to add top padding to headings that appear directly after paragraphs. https://github.com/uswds/uswds/issues/2215#issuecomment-405679277. The code seems only added to `@extends` and classes, not directly to the elements.

## Reference materials
- [Slack convo [Design systems Slack]](https://design-systems.slack.com/archives/C0ENULNQZ/p1509396679000313) 
- [Slack convo [USWDS public Slack]](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1509121102000510)

## Acceptance criteria
- [ ] Understand how heading and paragraph spacing interacts with each other
- [ ] Understand how typography collapses when it's inside and outside divs (where it works as expected and where there are problems)
- [ ] Capture pain points with current design
- [ ] Document how other systems achieve this

**Comment by btn0s** [comment]
For anyone who's not in those Slack groups/channels, is there another way to make the reference material accessible? Or maybe include links to join those channels?

**Comment by maya** [comment]
@btn0s sure, here are links to join the two slacks: https://chat.18f.gov/ and http://slack.design.systems. We can flesh this out more when we move it into our current sprint backlog; it's on our [roadmap](https://standards.usa.gov/whats-new/product-roadmap/) for the year.

**Comment by maya** [comment]
Adding more detail here, which may help provide context @btn0s:

We should be able to provide expected margins in all use cases: alone, with other grid and column elements, with `usa-section` classes, etc...

* Proper relative heading margins
* Proper paragraph text margins

Problems with the current method:
* fails with multiple grids and width classes stacked
* too many classes used to target width classes

From @hursey013 (Slack):

>hey all :wave: i have a question regarding the grid, and whether i’m using it correctly :grimacing: if i understand it right, when you use the grid it removes the top and bottom margin of the first and last elements within each grid box, which sort of feels unexpected to me. if i would like to add some space between the rows of a basic 2x2 grid like the one above, is the idea to create your own custom style to apply margin to the bottom of each grid box (or row), or override the WDS styles to add back in the top margin on the headings and bottom margin on the paragraphs?

Image from Brian of the spacing failing:
![screen shot 2017-10-27 at 12 13 08 pm](https://user-images.githubusercontent.com/5249443/36122233-7b8e7958-0ffd-11e8-8ecb-7d06cdf59933.png)

**Comment by maya** [comment]
One idea I'm experimenting with:
* going one-directional in `p` text margins (to help with multiple grid items stacked)
* zeroing in top margins of elements in the first grid item column items and leaving the rest with their natural spacing
* when using the section classes (`usa-section`) which provide top and bottom spacing, remove top and bottom margins of first and last elements respectively, so that the section's spacing has the proper spacing.

**Comment by maya** [comment]
See how the GOV.UK uses contextual adjustments to add top padding to headings that appear directly after paragraphs.

https://github.com/alphagov/govuk-frontend/blob/master/src/core/_typography.scss#L157

**Comment by thisisdano** [comment]
Are these all styles that would apply only to optionally-prose-scoped elements?

**Comment by thisisdano** [comment]
I like the gov.uk sibling-selector approach.

**Comment by maya** [comment]
>Are these all styles that would apply only to optionally-prose-scoped elements?

Up to us, right now they are not separate from the scoping part part of the code. We kind of left it alone until we had a better solution. Should it be?

>I like the gov.uk sibling-selector approach.

The one issue I see so far with the GOV.UK model is in an instance like this, where you have headings in grid items and rows:

![](https://user-images.githubusercontent.com/5249443/36122745-59710eba-0fff-11e8-9c00-73650204475c.png)

In this case the heading 3 would not have heading top margins applied, is that what we want?

**Comment by maya** [comment]
There probably is some utility in a class to remove the top margin of the first item and bottom margin of the last, right now, `.usa-section` does this, could be called `.clip-margins`

**Comment by maya** [comment]
Fixed in #2696.
