### ISSUE TITLE
Document process for collecting USWDS usage analytics from DAP

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2224]
We use some custom reporting in DAP to collect analytics about USWDS usage, but this process isn't documented. This information is important, but it risks disappearing down a memory hole. 

@AndreaSigz and @tdlowden have done the most work on this, and we have a document 🔐 [here](https://docs.google.com/document/d/16XwjS8SLWo8l9T0IkQ_SRHCZebgkFabIqRcV8EAznbU/edit) that outlines the Regex used int he report and the crappy notes about implementation.

Let's take the time to document this report and how to use it and modify it.

**Comment by AndreaSigz** [comment]
The notes from our convo with Tim are at the bottom of his Regx doc. I think this also sync's up with the updating of the Who is Using list (issue #2134)

**Comment by maya** [comment]
Doc updated with instructions.
