### ISSUE TITLE
Publish recaps in the wiki

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2235]
[description forthcoming]

**Comment by thisisdano** [comment]
Here's one to start: https://github.com/18F/web-design-standards/wiki/Recap:-Ideation-session-1

**Comment by thisisdano** [comment]
Might they be better as issues? It's kind of annoying, since the wiki is so hard to track and harder to use than issues — but issues carry so much baggage. 🤔

**Comment by sawyerh** [comment]
This is great 👍 GitHub's new Team Discussions feature might also work if Issues doesn't feel right: https://github.com/blog/2471-introducing-team-discussions
