### ISSUE TITLE
Maintained button color variants are not documented

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2237]
The button color variants available at https://components.standards.usa.gov/components/detail/buttons--red.html aren't documented on our site. Users don't know these variants exist, which is a particularly acute issue since we changed the styling of `usa-button-secondary` to outline from red. These variants are important. They are often necessary to communicate functionality, and if they don't appear on our site they may as well not exist.

### todo
- [ ] Document all available button variants on standards.usa.gov

**Comment by maya** [comment]
Duplicate of #2171. Will move this text there.
