### ISSUE TITLE
10px font-size on HTML element

### ISSUE THREAD

**Issue by peterbenoit** [uswds/uswds#2262]
I noticed that user font sizes are ignored if you set a font-size on the HTML element, the way it's done this style guide.

To test, change the default font size in your browser to something larger or smaller, and note that the size isn't reflected on https://standards.usa.gov/. I think this might work against the idea of using REMs for font sizes.

While setting a 10px root size is convenient to design and development, I don't think it necessarily a good user experience.

**Comment by maya** [comment]
Hi, thanks for opening this issue. We'll review this with our team and see how it fits on our roadmap. Stay tuned! 

Related to #992

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
