### ISSUE TITLE
Create a lightweight component submission workflow

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2283]
Designers and developers should have a lightweight way to submit components for inclusion to the USWDS. The previous [component workflow (maturity scale)](https://github.com/18F/web-design-standards/wiki/Contribution-Guidelines:-Design) was too cumbersome. Here is a proposal of what that might look like:

## 1. Required questions
* Describe the pattern: what’s its purpose and functionality?
* What user-need does it solve?

### Optional questions
* Have you conducted primary research? If so, provide.
* Do you have secondary research (e.g. articles, outside research)? If so, provide.
* Are there any similar or related patterns in the system already?

## 2. Share the component
Submit sketches, wireframes, design, or code (link to code on their repo, post code directly to the issue, CodePen, or pull request).

---

### Additional thoughts on CodePen
* CodePen template we provide with USWDS CSS and JS pre-linked 
* Tag code on CodePen: `uswds-component`
* Embed CodePens on component showcase page / component testing lab

[🔒 link to google doc](https://docs.google.com/document/d/1nMZXc1zOUteqL9tCtXlY1vFig9xd-GPMaO9rXzmujdk/edit#)

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).

Related to https://github.com/uswds/uswds/issues/2204
