### ISSUE TITLE
Add utilities

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2289]
Utility classes (or helper classes) provide a lightweight way to customize your markup with single-purpose classes. These classes are simple, composable, and reusable. For example: `.usa-red { color: $color-red; }`, `.usa-h1 { font-size: $h1-font-size; }`. We've seen the web community moving in this direction and think that providing helpful classes can enable teams to quickly remix these basic building blocks.

**Comment by francisrupert** [comment]
Recommend **responsive** flexibility, as with any given grid system, e.g...
```html
class="usa-text-size--foo usa-text-size--bar@s usa-text-size--zazz@m"
```
Aside: I'm extremely averse to utility styles in markup, but I recognize the wide variety of audiences USWDS caters to will appreciate a convenient way to do so -- and I've been plenty guilty to using them; besides, most grid systems are nothing more than utility classes. There's a valid discussion to be had that utility styles are "too easy, possibly lazy" and will be used far too liberally. It can be habit-forming and prevents users from growing their style skillsets, let alone understanding what exactly it is they're doing. At any rate...

**Comment by maya** [comment]
Hi @francisrupert, thanks so much for your feedback. Part of why the USWDS didn't launch with color helper classes was for the very reasons you mentioned: we didn't want to promote bad practices within the code. After a couple of years, it's become clearer that folks would find this helpful (especially for prototyping), and thanks to the influence of utility systems like [Tachyons](http://tachyons.io/). We hope to keep this utility set limited in scope (#2272), starting with color, space, and typography -- and extend it to a few layout items later on. 

That's a good point about responsive flexibility. We haven't released responsive typography yet but it's something we're thinking about and have some designs created. We've mostly heard the responsive requests for a grid system, and that would be tackled later on. 

The use of utility classes would have to be taken on by individuals using the system - some folks may prefer to use them, some may choose not to, others may use them for only prototyping, etc. We're hoping each team will make the decision that works best for them. We can likely provide some documentation of best practices though. If you have more thoughts about this, keep them coming.

**Comment by s2t2** [comment]
Hi, I was looking for float utilities like `pull-right` and `pull-left`. See Twitter Bootstrap: https://getbootstrap.com/docs/4.0/utilities/float/.

**Comment by maya** [comment]
@s2t2 thanks for the note. We'll be including float utilities as described here: #2272. You can also get a sneak peek here: #2316, but it may be more useful once we build out the documentation. We'll keep you posted!

**Comment by maya** [comment]
Needs stuff at the bottom of the utes page: advanced docs

**Comment by maya** [comment]
Now that advanced settings are in https://github.com/uswds/uswds-site/pull/590, this is done (!)
