### ISSUE TITLE
Audit dependency list

### ISSUE THREAD

**Issue by donjo** [uswds/uswds#2290]
We recently had an issue where federalist builds were failing because `npm install --dev` was requiring more resources than the default Federalist docker containers could provide (#2288).

That said, this seems like a good time to go through our list of dependencies and see if we're still using everything listed there and whether or not we can utilize a subset of a library instead of pulling down the whole thing.

**Comment by thisisdano** [comment]
Let's just keep an eye on our dependencies. Federalist docker container size is no longer is pressing issue.
