### ISSUE TITLE
Clearer, more specific design and implementation guidance

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2293]
This epic addresses the need to be as clear and helpful as possible about how to build with the kit of parts that we provide. We want to help our developers get started building with the system quickly, and to be a useful resource as they build out their projects. We need to be sure that any system of variables or utilities that we develop is documented and connected to the guidance we provide 

### Issues that could be relevant to this epic

- Documentation of utilities and prototyping path
- Documentation of variables and settings
- Guidance connected to best-practice use of unit values
- Quick start guides

**Comment by maya** [comment]
This is done in 2.0.
