### ISSUE TITLE
Better support and guidance for Federalist and Jekyll

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2294]
This epic addresses the need to improve our explicit support for a Nunjucks/Jekyll-based Federalist [NJF] development path, so we can provide more useful, practical, actionable NJF guidance.

### Issues relevant to this epic

- Collecting and analyzing USWDS Jekyll templates
- Researching and developing best practices for NJF development
- Building Nunjucks/Jekyll components to include in templates
- Documenting a supported process for including USWDS in an NJF project
- Documenting NJF template components in component documentation
- Working with 18F USWDS consulting teams to build out this functionality

**Comment by afeld** [comment]
For starters, we should list the Jekyll templates and explain the use cases for each. [Notes from meeting about this.](https://docs.google.com/document/d/1i459ty10smx1s_hI1cWHe_hig_-iw_DewJrFSCkcRKw/edit)

**Comment by CentralIntel** [comment]
> This epic addresses the need to improve our explicit support for a Nunjucks/Jekyll-based Federalist [NJF] development path, so we can provide more useful, practical, actionable NJF guidance.
> ### Issues relevant to this epic
> 
>     * Collecting and analyzing USWDS Jekyll templates
> 
>     * Researching and developing best practices for NJF development
> 
>     * Building Nunjucks/Jekyll components to include in templates
> 
>     * Documenting a supported process for including USWDS in an NJF project
> 
>     * Documenting NJF template components in component documentation
> 
>     * Working with 18F USWDS consulting teams to build out this functionality
