### ISSUE TITLE
Better typographic flexibility and resilience, with or without webfonts

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2295]
This epic addresses the need to build sites that perform and display well regardless of whether webfonts are used or loaded.

### Issues relevant to this epic

- Address and correct for metric variations between supported typefaces (how does this affect both font size and line height?)
- Research the suitability of webfonts for government applications
- Develop a practical, performant font stack for progressive enhancement
- Scope typeface-specific styles to a trigger that the font has loaded properly
- Research whether we should assigning a size to the `html` element and using `rem` for font sizing
- Explore typefaces that expand the system's expressive gamut

**Comment by scottkellum** [comment]
This might be helpful in some situations so that x-height of both web fonts and fallback fonts are consistent: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust

**Comment by maya** [comment]
This is done in 2.0.
