### ISSUE TITLE
Conduct & publish user interviews

### ISSUE THREAD

**Issue by AndreaSigz** [uswds/uswds#2303]
The HHS team behind the StopBullying site, did a demo at the October monthly users call. We should interview them (following the template of the other interviews) and publish to the site.

**Comment by maya** [comment]
@AndreaSigz were there any updates on this work / will it still continue?

**Comment by AndreaSigz** [comment]
Yes, finishing up turning the three (innovation.gov, stopbullying & Benjamin theme) into articles...rescheduling (sick yesterday) with Brock (Drupal 8 theme). Happy to finish that one up as well

**Comment by AndreaSigz** [comment]
- [ ] Benjamin WP—OK to publish (via email to USWDS inbox)

- [ ] Stopbullying—Waiting on OK from HHS

- [ ] Innovation.gov—Waiting on OK from Amy

- [ ] Drupal 8 theme—Drafting

**Comment by maya** [comment]
@AndreaSigz did you plan to open the pull request for these or to share the doc/content for us to do?

**Comment by AndreaSigz** [comment]
@maya I shared the doc with you all when Benjamin was done. Need me to send again?

**Comment by maya** [comment]
@AndreaSigz sure! that would be great to share it here 👍 May have missed it when you first shared it.

**Comment by AndreaSigz** [comment]
Here ya go: https://docs.google.com/document/d/1X_wdIdpEggJ7yK2aK64hg7vUbVcak-L2UwyjL40tglw/edit?usp=sharing

**Comment by maya** [comment]
@AndreaSigz thanks! should these two be included in the list as well? 

- DDS interview #2076
- NSF interview #2074

**Comment by maya** [comment]
@AndreaSigz are there any updates on the status of the posts above? Thanks!

Looks like these three were left:
- Stopbullying—Waiting on OK from HHS
- Innovation.gov—Waiting on OK from Amy
- Drupal 8 theme—Drafting

**Comment by AndreaSigz** [comment]
I'll have to look in the email, but I think I told them to work with you all to finish

**Comment by maya** [comment]
Could you cc the USWDS team on the emails and we can take it from there? I didn't find any drafts for Stopbullying in the [interviews folder](https://drive.google.com/drive/u/0/folders/1zET097alLq1dq_DS1I9iFdZoeQDoFZQE). Could you share the link to it with us? Thanks

**Comment by maya** [comment]
Closing since we’ve reached out to the remaining two interviewees (the third was not approved), and will re-open/update this if we hear back.
