### ISSUE TITLE
Use Airbnb JS linter config

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2310]
We're using a custom rule set for our [JS linter config](https://github.com/18F/web-design-standards/blob/develop/.eslintrc.yml). We should use [Airbnb's JS linter config](https://www.npmjs.com/package/eslint-config-airbnb-base) instead as [recommended by the 18F Front End Guild](https://frontend.18f.gov/javascript/style/) for consistency. Discovered while researching #2307. Thanks to @joshbruce for bringing this to our attention.

**Comment by joshbruce** [comment]
Anytime @maya 

https://github.com/chjj/marked/issues/999#issuecomment-356060385

According to this comment on marked - ESLint has an option??
