### ISSUE TITLE
No custom 404 template

### ISSUE THREAD

**Issue by BalajiJBcs** [uswds/uswds#2311]
## 404 custom template is not found

This is small UI suggestion:  Custom 404 page is not developed for the site it seems. If some users land in 404 page, he might have the problem with navigation. 

![404page](https://user-images.githubusercontent.com/31539453/34687637-67e74c06-f4d5-11e7-9465-7b8e2ea3fd88.JPG)

**Comment by maya** [comment]
Hi, thanks for opening this issue. A 404 page would be useful to include, but this would be better included in the documentation site repo: https://github.com/18F/web-design-standards-docs Unless you mean the system should include a 404 template?

**Comment by BalajiJBcs** [comment]
Yes, it should be created @maya , 404 templates should be included because if the visitors land in 404 page directly, he would opt to exit the site(The only option he has). On another hand, during the navigation of the site, a visitor might press back button, so he can visit the previous page of the site.

Pardon, I should say 404 templates rather than 404 page, which caused little confusion.

 So it is my opinion to have 404 template page, which is very important.

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
