### ISSUE TITLE
Form Behavior - Next Steps

### ISSUE THREAD

**Issue by AminPIC** [uswds/uswds#2314]
## Description

Essentially looking for guidance and support on how to continue the build out of the standard's forms functions. See Slack thread below:

Lauren Anderson [Yesterday at 1:58 PM] 
in #uswds-public
Hello, I am building a dropdown menu so that users can select an option, click a submit button, and be taken to a specific other page on the site (each dropdown option should take users to a different page). I used this code (https://standards.usa.gov/components/form-controls/#dropdown) to build the dropdown menu and created a button, but I'm not sure where to go from here. How do I integrate hyperlinks, etc. so the submit button sends the user to a specific page associated with an item on the drop down menu? Thanks in advance!
standards.usa.gov
Form controls | U.S. Web Design Standards
Form controls allow users to enter information into a page.

6 replies
Maya Benari [1 day ago] 
Hi @Lauren Anderson, thanks for stopping by. You’ll want to use a form and button to do this. And give your form an action to the page you want it to go to. See: https://www.w3schools.com/html/html_forms.asp
w3schools.com
HTML Forms
Well organized and easy to understand Web building tutorials with lots of examples of how to use HTML, CSS, JavaScript, SQL, PHP, and XML.

Lauren Anderson [23 hours ago] 
Thanks, Maya! It looks like that form you shared is set up to give one action to a page, but I'm looking to give an action to a different page for each form submission. For example, if you choose Option A, the submit option will go to Page A and if you choose Option B, the submit option will go to Page B. This may be because I'm not really using it as a true form.

Maya Benari [19 hours ago] 
That kind of functionality is out of scope for the help we can provide, unfortunately. But you can definitely use our elements to help construct that.

Amin Mehr [14 minutes ago] 
@maya I'm a little confused as to how this falls out of the scope of form controls. For example in the section of check boxes (https://standards.usa.gov/components/form-controls/#checkboxes), the standards provides the check boxes, but not a next step as to what to do with a check box. The way I see it, if a user selects a check box or a dropdown (in this example), then shouldn't there be a submit to apply the selection that they have made? (which would ideally go to the page with their selection or submit their selection to some sort of database)
standards.usa.gov
Form controls | U.S. Web Design Standards
Form controls allow users to enter information into a page.

Maya Benari [6 minutes ago] 
Hi @aminmehr. Sure, to clarify, the USWDS provides the building blocks to create forms, but the custom configuration of them and form behavior is not something we currently provide. It could be something we build out in the future as we invest more in forms guidance, so if it’s something you’d like to see, feel free to open an issue  https://github.com/18F/web-design-standards/issues hope that helps!
GitHub
18F/web-design-standards
web-design-standards - Open source UI components and visual style guide for U.S. government websites.

Amin Mehr [< 1 minute ago] 
Thanks will do!

**Comment by maya** [comment]
Hi, thanks for opening this issue. We'll review this with our team and see how it fits on our roadmap. Stay tuned!

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
