### ISSUE TITLE
Mega-menu Enhancements

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2318]
The mega-menu needs an overhaul (IMO). Features I would like to see addressed:

The four column only layout needs to be  replaced either with a way to specify the number of columns (usa-megamenu-2/3/4/6) or usa-megamenu is essentially the same as usa-grid-full and then just use the standard grid. If a grid overhaul is done, I would prefer the latter.

By default the mega-menu should be boxed either to a min-width (not to exceed max-width) and add a usa-megamenu-full to add the ::before and ::after to give it the edge to edge look. This will be very important if the variable column count feature is added. 

I would like to request that the basic primary navigation add a feature similar to what Vets.gov has done with theirs. This "group by topic" feature would preclude the use of the mega-menu in many cases.

**Comment by maya** [comment]
Hi, thanks for opening this issue. We'll review this with our team and see how it fits on our roadmap. Stay tuned!

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
