### ISSUE TITLE
Return to top footer link not behaving as expected

### ISSUE THREAD

**Issue by arvalarva** [uswds/uswds#2321]
## Description

Using the keyboard, the link behaves correctly and takes the user visually to the top of the page, but a second tab navigation shoots the user back down to the next footer link.

I believe the intent is that keyboard users can return to the top and then tab through that navigation, without tabbing through every link in the long footer. As it is now, this is not the case. See amazon.com for proper behavior in its "return to top" footer link.

## Steps to reproduce the issue

1. Tab to the "Return to top" link at the beginning of the footer.
2. Tab again.
3. Notice that your focus is back down to the footer.

**Comment by maya** [comment]
Thanks for bringing our attention to this @arvalarva. Yes, it seems like moving focus to the top of the page would be the expected and most accessible user experience.

**Comment by maya** [comment]
Fixed in #2403.
