### ISSUE TITLE
Collect design patterns for a shared user research library

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2325]
This is an ongoing list of design patterns we know other agencies have user research for to include in a future shared user research library. More work will need to be done to determine how this may take shape #2297 and is simply a list of design patterns to come back to.

## Design patterns
- Sticky side navigation
  - USA.gov has videos and user research results
- Forms 
  - https://design.cms.gov/ has some research on various design patterns cc @sawyerh 
  - USDS Vets.gov

Inspired by [GOV.UK Design Patterns Wiki](https://paper.dropbox.com/doc/GOV.UK-Design-Patterns-Wiki-hkou7bpzKya8Dadv24V1z).

## ⭐️ Contribute 
If you're working on government websites and have user research on design patterns or UI interactions, please post them to this issue.

**Comment by sawyerh** [comment]
So far we've done two rounds of user testing for the new HC.gov application. The format of the tests were InVision prototypes, so we haven't yet gotten a ton of results around the usability of the form fields themselves. There is one patterns that we've tested that we do have some preliminary results on, with secondary research, that have been encouraging and worth sharing:

## Task list

We've been testing a "task list" pattern as a way to:

1. Introduce a user to the application so they know what's coming up.
1. Allow the user to navigate to previous sections of the application.
1. Allow a user to see their current progress, at a high level, within the application.

This pattern was inspired by [GOV.UK's Task list pages](https://www.gov.uk/service-manual/design/task-list-pages-beta), and they have some [additional research notes here](https://paper.dropbox.com/doc/Task-list-pages-UQUXO53CLWTfwvjaTOboE).

The first iteration we tested was this:

| Step 1 | After completing step 1 | Example form page with "View all steps" link |
| ------ | ------------------------ | -------------------- |
| ![image](https://user-images.githubusercontent.com/371943/36230063-3e40b9f2-11a7-11e8-926e-8351f0532f8a.png) | ![image](https://user-images.githubusercontent.com/371943/36230086-4c5adff4-11a7-11e8-8658-37042e1a607b.png) | ![image](https://user-images.githubusercontent.com/371943/36231353-c4e0e406-11ab-11e8-8549-c17cc3f36676.png) |


We tested this prototype with 9 participants and some of the findings were:

- Most users tended to click the green "Start" button right away, not reading the text on the page. For our case, this is actually fine, and showed that users were able to quickly identify how to start their application, and understood to start from the first step in the list.
- Some users commented about the green button, one of them saying:
  > I like green, green means go
- Users understood that grayed-out steps were disabled, and that they needed to complete the steps one at a time from top to bottom.
- In the design, the step titles were intended to be hyperlinks that would take the user to the same page as the "Start" button. The goal was to provide multiple ways for a user to proceed with their application, or navigate to previously completed step. However, this seemed to cause confusion for some users. Some users weren't sure where the title link would take them, and some thought it might take them to a page describing the step. Our takeaway here was to remove the link from the title in the next iteration.
- In the prototype, when a user is on a question page, they can click a "View all steps" link to navigate back to the task list to see their progress. If a user hadn't yet started the next step, the button would say "Start". This caused confusion for some users. When one user came back to the page and the "Start" button moved to the second step, there was some concern that it would Start another application, and he suggested it would be clearer if it said "Continue". We agree, and in future iterations the CTA will say "Continue" for subsequent steps, even if they haven't been started yet.
- Users seemed to understand that to go back to a previous step, they would click the "Edit" link to the right of the step.


P.S. Let me know if you prefer a different format for sharing future findings.

**Comment by maya** [comment]
@sawyerh this is great stuff. It may make sense to x-post this in #1403 since that issue is closely related.

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
