### ISSUE TITLE
Export static Fractal Web UI build?

### ISSUE THREAD

**Issue by ryanbelisle** [uswds/uswds#2327]
Is there a way to export the standards into static HTML with the Fractal Web UI (including all components and docs, etc.)?
https://fractal.build/guide/web/builder

I tried running **fractal build** and that doesn't work.

Any help would be greatly appreciated!

**Comment by donjo** [comment]
Hi Ryan, 

We happen to have a publicly accessible fractal site that you can find at https://components.designsystem.digital.gov/

As for getting your fractal build command running locally, can you provide any additional details on which error you're seeing and what steps you tried beforehand?

**Comment by ryanbelisle** [comment]
Donjo,

Nevermind I figured it out! I needed to install the Fractal CLI tool. Thanks for replying so quickly.
