### ISSUE TITLE
[Unable to view Fractal components in panel]: Refused to display in a frame because 'X-Frame-Options' is set to 'deny'.

### ISSUE THREAD

**Issue by line47** [uswds/uswds#2335]
None of the components are showing in the fractal frame.
https://components.designsystem.digital.gov/components/detail/labels--default.html

The components display if I open in the external view.
https://components.designsystem.digital.gov/components/preview/labels--default.html

I get the console error:
```
Refused to display 'https://components.designsystem.digital.gov/components/preview/labels--default.html' in a frame because it set 'X-Frame-Options' to 'deny'.
```

**Comment by jseppi** [comment]
This should now be fixed 🎉

**Comment by maya** [comment]
Thank you @line47, @jseppi, @wslack!
