### ISSUE TITLE
Support search in mobile header

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2346]
We recommend a menu on the right of the mobile header with search inside the menu. This makes sense when the menu is the primary thing you want folks to have access to. However, with this design, search is also inside the menu which makes it harder to find. Do we have research showing this is a recommended pattern? 

In USA.gov's user feedback, they found it's hard to find: #1640 
>We hear that users are having a hard time finding the search in mobile and some don't expect to find it under "Menu". 

In contrast, one of the earlier designs which was not implemented has the menu on the left and search on the right. This could be a good approach when search is an important feature of your site.

## Current header
<img width="394" alt="screen shot 2018-02-12 at 4 27 18 pm" src="https://user-images.githubusercontent.com/5249443/36127319-abc70798-1011-11e8-864a-7ecfd70ee015.png">
<img width="394" alt="screen shot 2018-02-12 at 4 27 29 pm" src="https://user-images.githubusercontent.com/5249443/36127320-ad224544-1011-11e8-9817-236abac831fa.png">

## Future possibility
![f8000258-419d-11e5-875e-1f77debcbaae](https://user-images.githubusercontent.com/5249443/36127282-82515012-1011-11e8-8796-2816ff86d240.png)
via: #289

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
