### ISSUE TITLE
Audit the build process

### ISSUE THREAD

**Issue by donjo** [uswds/uswds#2348]
With the addition of utility classes our circleCI build time has increased by quite a bit. It's been a while since we've taken a look at the build/test process and I believe that the package may be building itself more times than necessary

**Comment by maya** [comment]
Looked at post and pre-utilities build times to find the bottlenecks:
![chart 1](https://user-images.githubusercontent.com/5249443/36455340-868c99fe-1654-11e8-87a2-d82a87704b57.png)
[🔒 Source](https://docs.google.com/spreadsheets/d/18PQ1mmra3W22yTa_Pb2Ek4pjc_nGMI5Z5-YCMr6fhcA/edit?usp=sharing)

**Comment by donjo** [comment]
A few things we learned here:

- There was an extra unnecessary build step happening, that is being removed in #2371 
- There is a certain amount of node startup time that can't really be avoided, it takes a bit longer in Circle than it does on local machines but that is to be expected considering our laptops are supercomputers compared to the instances that Circle spins up.
- There may be gains to be had by embracing parallelism, a feature offered in Circle 2.0, but will require some refactoring of our test suite to potentially see gains. We may look into this once an engineer is added to the team.
- There are still mystery variables we have yet to uncover. For example: why does the aXe test suite need to finish in 20000ms to avoid timeout errors?

**Comment by maya** [comment]
Re-opening as this work is continuing.

**Comment by maya** [comment]
Closing this via: #2407. 

With the help of caching and removing unneeded steps, CircleCI build times are now around 1 minute (down from 2-4 minutes) and Federalist build times are 3 minutes (down from 4-6 minutes). Good work @hursey013! 

Updated chart
![chart 4](https://user-images.githubusercontent.com/5249443/37793834-011c2f56-2dcd-11e8-87d4-fb7b21f2b046.png)
