### ISSUE TITLE
508 error content inserted with css

### ISSUE THREAD

**Issue by bruffridge** [uswds/uswds#2367]
We got a 508 error from SortSite on these lines:

https://github.com/uswds/uswds/blob/master/src/stylesheets/elements/_inputs.scss#L91
https://github.com/uswds/uswds/blob/master/src/stylesheets/elements/_inputs.scss#L96
 
Level A
 
2 issues on 6 pages

``` 
Content inserted with CSS is not available to some screen readers, and to people with low vision who turn off style sheets.
Move the content from CSS to the HTML page so that all users can see it.CSS content causes problems in:

• Firefox when the No Style menu item is chosen (CSS content disappears)
• NVDA 2016.2 with IE11 (CSS content not read)
• JAWS 17 with IE11 (CSS content not read)
• JAWS 16 with IE11 (CSS content not read)
• JAWS 15 with IE11 or Firefox 29 (CSS content not read)
• WindowEyes 9.2 with IE11 (CSS content not read)
```

Here's the 508 guideline. I guess the question is whether the "optional" and "required" text is decorative or not. I would say it conveys information and isn't merely decorative.
https://www.w3.org/TR/WCAG20-TECHS/F87.html

**Comment by maya** [comment]
That's a very good call. We weren't aware of the limitations of "content" with those screen readers. Thank you.

**Comment by maya** [comment]
This is the commit where the change from HTML content to CSS content occurred: https://github.com/uswds/uswds/commit/472832d195901bd04263d88005b935bfdabad11d
