### ISSUE TITLE
Resolve open issues in utilities

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2372]
There are some open issues in the [:lock: utilities doc](https://docs.google.com/document/d/1VsHtYGWyzurwGrOj0S-dMZTgeUnl4xBf3HaajivL9o0/edit#) that need to be resolved in code #2287. 
## Scope

- [x] media queries - square values to use USWDS, in the future em?
- [x] fo, ho - resolve issues - write out name
- [x] placeholder - remove

## Production utility properties

- [ ] colors - add in ROYGBIV + cyan, find the scale of colors to add in the system (likely 5) - naming - is it red-50 or red-light in this (leaning to the latter)?
- [ ] colors - resolve the ui, id confusion by potentially using primary + [secondary or accent]
- [x] border radius - add modifiers, edit values
- [x] clear - change name to clearfix, remove left and right from prod, use mixin: https://www.bourbon.io/docs/latest/#clearfix
- [x] display - add table, rethink hide value to none
- [ ] font family and font size - would like to see a more generic, single purpose option as well as family+size
- [x] font weight - include light, normal, bold and fw1 - fw9
- [x] line length -  adjust variable names
- [x] list reset - use the USWDS mixin
- [x] margin - remove some values
- [x] text transform - change names to match CSS values

---

Things that can be resolved in the future through testing:

## Future 

- [x] border radius - observe if the name “radius” works, as opposed to border-radius or br
- [x] color - consider whether some values should be removed
- [x] float and flex - who gets the f?
- [x] font size - naming f1 vs font-size-l
- [x] line height values ambiguous
- [x] text align vs float naming conventions
- [x] Short vs longer names - ambiguous vs easy to type

**Comment by thisisdano** [comment]
## Scope

- [ ] media queries - square values to use USWDS, in the future em?

Using tshirt, will set current USWDS to defaults, but can be set in settings

- [ ] fo, ho - resolve issues - write out name

Using `hover:`, `focus:`, etc

- [ ] placeholder - remove

Removed.


## Production utility properties

- [ ] colors - add in ROYGBIV + cyan, find the scale of colors to add in the system (likely 5) - naming - is it red-50 or red-light in this (leaning to the latter)?

Ongoing issue — currently using the color values from current USWDS, but can add any other in settings.

- [ ] colors - resolve the ui, id confusion by potentially using primary + [secondary or accent]

Ongoing issue — currently using the color values from current USWDS

- [ ] border radius - add modifiers, edit values

Added modifiers.

- [ ] clear - change name to clearfix, remove left and right from prod, use mixin: https://www.bourbon.io/docs/latest/#clearfix

Currently removed — will add back in as clearfix, using settings from USWDS

- [ ] display - add table, rethink hide value to none

Done. Added table-cell, too.

- [ ] font family and font size - would like to see a more generic, single purpose option as well as family+size

Not sure about this. I still feel strongly about regularization and I'm loathe to split.

- [ ] font weight - include light, normal, bold and fw1 - fw9

Can add `light`, `bold`, `normal` and perhaps tie to some settings.

- [ ] line length -  adjust variable names

Folded into `max-width` as `reading` and `reading-sm` but I think this needs more tweaks

- [ ] list reset - use the USWDS mixin

Can do — will change rule to reference that mixin.

- [ ] margin - remove some values

Done

- [ ] text transform - change names to match CSS values

Done

---

Things that can be resolved in the future through testing:

## Future 

- border radius - observe if the name “radius” works, as opposed to border-radius or br

Changed to `border-radius`

- color - consider whether some values should be removed

This work is TBD.

- float and flex - who gets the f?

Both written out now

- font size - naming f1 vs font-size-l

This will have both — either can be activated depending on settings. Using a master scale now that I'd like to change.

- line height values ambiguous

Changed to numerical, but that isn't working — gonna change to something more verbose/explicit

- text align vs float naming conventions

All written out now

- Short vs longer names - ambiguous vs easy to type

Now all longer.

**Comment by maya** [comment]
We've completed everything we could. Closing this and moving the larger issues to their own issue #2400.
