### ISSUE TITLE
Improve the appearance of the range input on Chrome and Safari (Webkit) and on Firefox

### ISSUE THREAD

**Issue by mbucknell** [uswds/uswds#2373]
## Description

On webkit browsers the range appears as follows:
<img width="481" alt="screen shot 2018-03-01 at 8 52 42 am" src="https://user-images.githubusercontent.com/8104736/36851059-f300643c-1d2d-11e8-8736-6f4802053d10.png">

The appearance on Firefox is better but I think it could look better:
![screen shot 2018-03-01 at 8 53 39 am](https://user-images.githubusercontent.com/8104736/36851105-14144454-1d2e-11e8-9a36-dcf268b5ccbd.png)

Since we are intending on using a range input in our UI we will have to override the styling for this input as the appearance on Chrome and Safari is not acceptable.

**Comment by maya** [comment]
Hi there, what version of webkit browsers are you seeing that in?  I'm not able to replicate. This is what I see in latest Chrome and Safari:

<img width="479" alt="screen shot 2018-03-01 at 9 47 43 am" src="https://user-images.githubusercontent.com/5249443/36860403-ff9a498a-1d35-11e8-8ae6-54d4348aad5f.png">

**Comment by mbucknell** [comment]
So a couple of more details. We are building the css from the scss. We are compiling it with node-sass and using uglify for minimization (although I get the same results if I don't use uglify) I did try it without any of our custom style or leaflet (which we also have in the application) and got the same thing. I am using the latest Chrome and Safari as well.

**Comment by maya** [comment]
We don't have an example of it yet, unfortunately, see #2374, but what happens when you visit: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/develop/components/preview/text-input.html and change the text input type to range?

**Comment by mbucknell** [comment]
It it appearing correctly (like your picture). So it must be a problem with compiling from the sass. How do you build the version in dist?

**Comment by mbucknell** [comment]
The latest version (1.5.0)didn't change the appearance for me.

**Comment by mbucknell** [comment]
I think I found the issue. We are building from the source directory. If you go to https://github.com/uswds/uswds/blob/develop/src/stylesheets/elements/_inputs.scss#L249 and add ```-webkit-appearance: none;``` my range input is styled as you have shown.

**Comment by mbucknell** [comment]
Should I put in a PR for the fix?

**Comment by maya** [comment]
@mbucknell Glad you found the issue, but no need to open a PR: we use gulp to build our dist file and it does a few things in the background like running PostCSS which adds browser prefixes for us. This way it's much easier to maintain. Maybe you can add this to your build too? Closing this out, but let us know if anything else comes up.

**Comment by mbucknell** [comment]
I wonder if we need better documentation on how to build the css if we are building using the sass files. We don't use gulp and I'm concerned that we may be missing some other build steps.

**Comment by maya** [comment]
That's a very good point. Added #2375 for this issue. Feel free to add any background info or possible solutions you may think of. Thank you.

**Comment by maya** [comment]
@mbucknell since you are using node-sass would you be able to add it like this https://github.com/postcss/postcss#npm-run--cli?

**Comment by mbucknell** [comment]
I'll give that a try and let you know. Thanks for the suggestion!

**Comment by mbucknell** [comment]
I would need to figure out what options to set in the options.json file. The README doesn't help there. And I think I would still need more guidance as to how the sass is built for USWDS.

**Comment by mbucknell** [comment]
Just to close this out. I was able to use postcss-cli with autoprefixer in our build process and that fixed the styling issue. Thanks again!
