### ISSUE TITLE
Add range slider example and documentation to "Form controls"

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2374]
We currently have a range slider code (#259) in the USWDS, but not an example of it. We should add it. 

We even have usability/implementation documentation for it:  

> • Whenever appropriate, label each end of the slider with what it represents (whether a number range, “large” or “small,” “high” or “low”).
> • Set the `min` and `max` attribute of the `input` element to match whatever instructions or labels accompany the slider.
> • Set the `step` attribute so the slider is not too granular. Sliders should let users input approximate values. By setting the step to “10” or “20,” you keep users from inadvertently selecting values that are more precise than they intended.

Relevant issues: #244, #701

**Comment by maya** [comment]
@thisisdano the range slider is not dependent on 2.0. Any reason it has the 2.0 label and pipeline?

**Comment by thisisdano** [comment]
I think it was just because we thought we could add it easily by the time of the 2.0 release. But it could release earlier — no need to wait.
