### ISSUE TITLE
Add documentation for running USWDS Sass w/o PostCSS

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2375]
The USWDS runs PostCSS as part of its build process to add vendor prefixes. However, some people may be building the Sass directly from the SCSS we provide, without PostCSS. This means that their CSS does not have vendor prefixes added. 

What should the workflow look like for these developers?

## Ideas
- Offer a prefixed version of Sass
- Add documentation for adding it themselves

Discovered in #2373.

**Comment by thisisdano** [comment]
We use PostCCSS? I _do_ see we use autoprefixer, and I feel that's a fine best practice. I'm pretty sure we don't want to prefix manually, but we could give some guidance about what post-compilation steps our sass requires if someone has their own pipeline.

**Comment by maya** [comment]
Yes, autoprefixer is a PostCSS plugin.

**Comment by maya** [comment]
Offering SCSS already prefixed could be a nice option for folks who don't use autoprefixer.
