### ISSUE TITLE
Cursor position change in Text field (iPhone 6, iOS 11.2.6)

### ISSUE THREAD

**Issue by Muntasir101** [uswds/uswds#2377]
This is issue is similar https://github.com/uswds/uswds/issues/277

**Comment by maya** [comment]
Not able to replicate this on an iPhone 7.

**Comment by squidjam** [comment]
I'm able to replicate on iPhone 8, iOS 11.2.6

**Comment by maya** [comment]
Looks like a fix was described in the duplicate issue https://github.com/uswds/uswds/issues/277#issuecomment-351320681. You'll want to make sure you're looking at the [component directly too](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/develop/components/preview/name-form.html). Closing.
