### ISSUE TITLE
Solidify 2.0 release path

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2388]
## 2.0 beta
- [x] Finish building out utility documentation pages https://github.com/uswds/uswds-site/issues/552
- [x] Decide on [other issues](https://github.com/uswds/uswds/labels/2.0) we want to complete for 2.0
- [x] Integrate new variables into USWDS components #2660
- [x] Complete issues in the Release 2.0 pipeline

## 2.0 official
- [x] Design and build new homepage
- [x] Write blog post with the announcement

[🔒Strategy for USWDS Utility Deployment](https://docs.google.com/document/d/1DauDiN74cD4_nV9uZ2dwoWysfX0S_T6ran-H32HwGgU/edit)

**Comment by thisisdano** [comment]
We may have some more homepage and blog post information to come, but they are complete enough for the purposes of this issue
