### ISSUE TITLE
Only run aXe accessibility tests on files with changes

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2411]
I noticed aXe accessibility testing takes quite a bit of time (24s) and wondered if it's possible to only run it on files that have changed, rather than on every file every time. This is how AccessLint works, but also AccessLint only runs on the code that's changed rather than the whole file. This could get out build times from 1 min to 36s. 

Also applies to the uswds-site repo.

cc @hursey013 @toolness for visibility

**Comment by thisisdano** [comment]
Not feasible at this point
