### ISSUE TITLE
Create a TTS microrequest

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2423]
Create a TTS microrequest so that we can get support for the USWDS as people have time available.

Example: https://github.com/18F/staffing-and-resources/issues/471

---

### Project Description

The U.S. Web Design System (USWDS) is the government's very own design system. It helps government teams design and build fast, accessible, mobile-friendly government websites backed by user research.

- Client agencies: It supports teams in the VA, USDS, NASA, Department of Education, USDA, DHS, EPA, FOIA, GSA, NIH, FDA, and [many more](https://designsystem.digital.gov/getting-started/showcase/all/)
- Engagement type: variable length based on staff roles and need
- Problem statement: The USWDS seeks to become a mature and stable design system that enables federal teams to more easily build services and websites to better serve the American people.
- Project impact: Help be a part of the most popular, wide-reaching open source project in the federal government. Empower teams across government to build more effective, human-centered services. Sites using the USWDS had 1.4BB page views in the last quarter. 
- Link to the client folder: [USWDS](https://drive.google.com/drive/u/0/folders/0B_NVRFrsefnvfnhYTkw0ZWpkSjFzQzhCQkt0azFaa05QVFkwNnJFS3AwQjcwWUdZT1ZSRVk)
- Qualification documentation: N/A?
- Reviewed by [x teams TBD (e.g. Design, Product, Engineering chapters)]
- Passion Statement: If you are interested in helping to bring USWDS to a mature design state, this project is for you!
- Direct questions about this engagement to Dan Williams

### Timeline

- Duration of engagement: Ongoing through 10/1/2018

### Staff
- [Product owner] Dan Williams (visual design, vision, content)
- [Front-end design] Maya Benari (accessibility, product manager, community) 
- [Front-end design] Brian Hurst (JavaScript, engineering, devops)

### Requested Staff

- [ ] [Engineer/Developer]

  - Ongoing 
  - flexible hours/week
  - Technical development work, optimize jekyll, improve testing, develop tooling
  - Review technical PRs

- [ ] [Front end] 

  - Ongoing
  - flexible hours/week
  - Front-end bug fixing and optimization

- [ ] [Visual] 

  - Ongoing 
  - flexible hours/week
  - Help design the future visual direction of the USWDS, branding, new website design for our 2.0 release, improve our component Sketch files and sticker sheet

 - [ ] [Content]

    - Ongoing 
    - flexible hours/week
    - Improve the USWDS documentation, IA, homepage content

- [ ] [UX] 

  - Ongoing 
  - flexible hours/week
  - Map user flows, research on current usage, testing system, and research on the user experience.

- [ ] [Product]

  - Ongoing 
  - flexible hours/week
  - Assist Maya in managing USWDS workflow and prioritization of issues, roadmap
  - Provide guidance in product direction 

- [ ] [Strategy]

  - Ongoing 
  - flexible hours/week
  - Ensure the USWDS is outcome focused and develop metrics for measurable impact
  - Provide guidance in product direction 

**Prior to closing this issue**

- [ ] Ping @abrouilette that the issue is ready to close, so he can update some things.

**Comment by thisisdano** [comment]
I like this — I added a very generic `tooling` to the engineering bullet — I don't know what that is, but in my mind it's things like @toolness's contrast checker, etc etc. I know we could develop a list of things.

**Comment by maya** [comment]
Closed as we are not allowed to make pro-bono microrequests.
