### ISSUE TITLE
Jekyll build error using release-2.0 branch from npm

### ISSUE THREAD

**Issue by hursey013** [uswds/uswds#2429]
When attempting to import `uswds` into a sass stylesheet in Jekyll:

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    $string: false is not a string for `quote' on line 695
             Error: $string: false is not a string for `quote' on line 695
             Error: Run jekyll build --trace for more information.
```

**Comment by thisisdano** [comment]
Have a _feeling_ I know the kind of thing this is referring to. It's not an error I've gotten before, though. Is there an open branch I could look at? (Probably) somewhere a `quote()` function is getting a `false` value — I'll need to find out where it's coming from...

Does `jekyll build --trace` actually give you any more info?

**Comment by hursey013** [comment]
@thisisdano think I tracked it down here https://github.com/uswds/uswds/pull/2430
