### ISSUE TITLE
Add font size helper classes in utilities

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2433]
Add font size classes so that people can prototype with text more easily.

I envision someone setting their base font family and heading fonts as a setting which will have the right font size calculations trickling down to them.

## What it could look like
<img width="913" alt="screen shot 2018-04-16 at 2 08 42 pm" src="https://user-images.githubusercontent.com/5249443/38835367-2bb52616-4180-11e8-9985-e7bcc8de6876.png">
Source: https://vueds.com/example/#!/Design%20Tokens?id=fontsize

## How should it be named?
A previous poll for naming font sizes resulted in **9 votes for t-shirt sizes** (`font-size-xs`, `font-size-sm`, `font-size-md`) to **3 votes for numeric scale** (`f1`, `f2`, `f3`). So the class would be: `.usa-font-size-sm`. 

Note: Font family helper classes may be desired as well: `usa-font-sans` and `usa-font-serif`, but I realize this will change the font size calculations. It's questionable whether this is an issue or not. Some folks mentioned they don't care that it's not exact and rather have the control. (may move this to another issue)

**Comment by thisisdano** [comment]
So, I think the issue you've outlined here comes down to the difference and distinction between the system palette and the project theme palette. To the question of whether we will use a relative scale (like t-shirt or base-relative) or a fixed numeric scale (like f#) — I guess I say that we will use both.

The **system palette** is the larger set of values that defines the set of all values used by the system. For typescale, we have a system of 20 values from **f1** (~12px) to **f20** (~140px) identified as the discrete set of typescale values available to any project using the system.

The **project theme palette** is a subset of the system palette and includes only those values used by a specific project. No single project (even complex projects) should use all 20 values in the system palette. It's appropriate that projects use fewer type sizes. Currently, the project theme palette is named with a 9-step base-relative naming system (defining a base value, then naming small, smaller, smallest, etc from it):

| name |default size | use |
| --- | --- | --- |
| micro | f1 (12px) | small helper text; < 1 sentence reading
| smallest | f3 (14px) | fine print ; < 2 sentences reading
| smaller | f5 (16px) | helper text; < 1 paragraph reading
| small | f6 (17px) | body small reading; buttons; long reading
| base | f7 (18px) | body standard reading; buttons; long reading
| large | f10 (24px) | small callout text; small headings; < 1 paragraph reading
| larger | f12 (32px) | large callout text; headings; < 2 sentences reading
| largest | f14 (40px) | small display; big heading; < 8 words reading
| mega | f16 (56px) | big display; < 3 words reading

- - -

![uswds-type-scale](https://user-images.githubusercontent.com/11464021/39065558-fee7de1c-4486-11e8-8aae-7710f6544832.png)

- - -

For now, I am going to avoid the normalization issue, but I will only say to those who "don't care" that it is fine that they don't care, but that I believe it makes sense for the system to care.

Project theme typescale can access use-base assignments or face-based assignments — that is, you can specify a type size using something like `u-font-text-base` or like `u-font-serif-base`.

##### Use-based families
- `text`
- `code`
- `heading`
- `alt`

##### Face-based families
- `sans`
- `serif`
- `mono`
- `cond`

You can set what families/roles your project uses (and set the sizes) in `_project-settings.scss`.

For the utility output, you can use plugins to determine what families and values are output in `_project-utilities-settings.scss`.

The `font` utility default is to use `plugin-font-theme-all` and `plugin-font-theme-roles-all` to output utilities for all the base-relative theme sizes in both the role-based and face-based families. You could use a plugin like `plugin-font-uswds-all` as a prototyping tool to output all the system values as well, like `u-font-sans-f19`.

The basic idea is that projects set their type sizes from values available in the system palette. USWDS includes a usable project theme default set, but your project needs should determine the final settings. The 9 steps in the project theme palette should be sufficient for most projects, even considering responsive needs. (If not, projects can still access the sizes in the broader system palette.)

I think this is consistent with the proposal outlined in the issue, but provides some additional breadth with a broader project theme palette.

**Comment by maya** [comment]
Done, preview here: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-utility-docs/utilities/font-size-and-family/
