### ISSUE TITLE
Some border-width utilities have extra hyphen

### ISSUE THREAD

**Issue by hursey013** [uswds/uswds#2437]
On `release-2.0` branch, there are 8 occurrences of `border-width` in the complied stylesheets containing an extra hyphen like: `u-border--width-half `. It on seems to happen on the classes that do not contain a modifier.

**Comment by thisisdano** [comment]
Fixed in another branch — hopefully ready for merge soon.

**Comment by thisisdano** [comment]
Addressed in https://github.com/uswds/uswds/pull/2422
