### ISSUE TITLE
Feature request: Include a default border styling

### ISSUE THREAD

**Issue by hursey013** [uswds/uswds#2439]
In other utility libraries I've used, there is usually the option to use a class like `border` by itself which has all the necessary attributes to render a default border (usually configured with Sass variables). Then you have the option to pair addition border classes to override any of the defaults, so something like `border border-blue`.

As it stands now, in order to get a border to render all four classes must be included which seems somewhat burdensome: `u-border-width-pixel u-border-color-neutral-base u-border-style-solid u-border-radius-small`.

**Comment by thisisdano** [comment]
I've got this one implemented and coming up!

**Comment by thisisdano** [comment]
Currently implemented in https://github.com/uswds/uswds/pull/2422 if you want to take it for a spin.
