### ISSUE TITLE
Mixing thirds and fourths grids

### ISSUE THREAD

**Issue by johnnyporkchops** [uswds/uswds#2441]
This is not necessarily an issue with the code, but on the website it says to post here if running into an issue. Please let me know if this is not the proper place to request support and I will move this to another forum.
I am working on an agency site on which I find mixed third and fourth grids which do not add up to one.
Here is the structure:
```
<div class="row">
  <div class="usa-width-one-third">
    ...content
  </div>
  <div class="usa-width-one-third">
    <ul class="usa-width-one-half">
     ...content 
    </ul>
    <ul class="usa-width-one-half">
      ...content
    </ul>
  </div>
  <div class="usa-width-one-fourth">
    ...content
  </div>
</div>
```
It has been in production for a while, without any noticeable issue yet. Since i have to make some changes to this structure and I did not see any discussion on the USWDS website about mixing like this, I am asking if this is OK, or if it is not recommended for any reason. Or is the grid system designed to allow this for more control of presentation?

**Comment by maya** [comment]
Hi @johnnyporkchops, if it works for you without any noticeable issues, I'd say it's probably OK. It doesn't end up filling the full width of the grid row, which you've probably noticed, bc it's short one-twelfth of a column. I'd check with your designers to make sure this is intended. Hope that helps.

**Comment by johnnyporkchops** [comment]
Thanks @maya, I will circle back with designers and make sure this is what is intended.
