### ISSUE TITLE
Develop prototype docs for new system functionality

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2453]
As we move to a system based on palettes of style options, how do we introduce and communicate those options, the variables associated with those options, and the way you might use them through utilities?

Right now there are the following docs, in various stages of finesse and thought:

- [Color docs prototype](https://federalist-proxy.app.cloud.gov/preview/gsa/10x/dw-design-refinements/uswds-color-docs-introduction/)
- [Layout grid docs prototype](https://federalist-proxy.app.cloud.gov/preview/gsa/10x/dw-design-refinements/layout-grid/)
- [Spacing units docs prototype](https://federalist-proxy.app.cloud.gov/preview/gsa/10x/dw-design-refinements/uswds-spacing-units/)
- [Type scale docs prototype](https://federalist-proxy.app.cloud.gov/preview/gsa/10x/dw-design-refinements/uswds-type-scale/)

For now, we can use these as a place to quickly prototype new ideas or layouts before thinking about practical implementation. Focus on what we need to say and how.

**Comment by maya** [comment]
Superceded by uswds/uswds-site#552.
