### ISSUE TITLE
Create a migration guide for 1.x to 2.0

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2536]
- [ ] Identify breaking changes that occur to components and system-wide effects
- [ ] Explain how users can update their code to use 2.0

Feedback:
>when the new grid scheme hits, what will happen to sites where the current uswds is in use? a migration guide might be helpful, too

>Mostly I'd imagine a migration guide would be a non-developer-friendly version of a changelog.

**Changelog**: https://github.com/uswds/uswds/releases/tag/v2.0.0-beta

**Comment by stphnwlkr** [comment]
Should look at what bootstrap did when they went to version 4. https://getbootstrap.com/docs/4.0/migration/

**Comment by maya** [comment]
from duplicate issue https://github.com/uswds/uswds-site/issues/701: 
>USWDS users have been using v1.x for a while and have their own assumptions about how to import USWDS into their site. When switching to 2.0, some of these assumptions have changed, or are no longer recommended, or maybe even unsupported. A migration guide would compile the Release Notes into a step by step of how to take your v1 site and make it v2.

**Comment by maya** [comment]
Done in uswds/uswds-site#741.
