### ISSUE TITLE
Test to make sure Chrome and chrome-remote-interface can talk to each other

### ISSUE THREAD

**Issue by toolness** [uswds/uswds#2537]
So one really annoying thing about using headless Chrome for testing is that Chrome is always evolving, which means the Chrome DevTools Protocol (CDP) used to communicate with it is always evolving, which means that chrome-remote-interface needs to be constantly upgraded lest it talk to Chrome using an old version of the CDP, causing super weird errors to occur, which I think is what's going on now.

Ideally some kind of initial test to make sure Chrome and chrome-remote-interface can talk to each other via the CDP should be run before actually running all the aXe tests, as this would provide more helpful error output than the current "super weird errors".

For now though, the problem should be able to be fixed by running e.g. `npm i --save-dev chrome-remote-interface@latest`.

**Comment by thisisdano** [comment]
Lemme try this out — it's frustrating since I _thought_ I'd tried this very thing, but maybe I didn't actually update to the latest package...

**Comment by maya** [comment]
How do we find out which version of Chrome/Chrome DevTools Protocol (I assume `chrome-launcher`?) and `chrome-remote-interface` can talk to each other?

**Comment by maya** [comment]
Done in #2539 and uswds/uswds-site#559, though doesn't fix the issue we were having in uswds-site.

**Comment by thisisdano** [comment]
Closed in favor of #2614
