### ISSUE TITLE
Add script to not run CodeClimate on forks

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2548]
Since we've added CircleCI testing to forks, it will fail bc the fork can't access the environment variables. We should add a script to not run CodeClimate on forks.

**Comment by afeld** [comment]
Workarounds: https://discuss.circleci.com/t/create-separate-steps-jobs-for-pr-forks-versus-branches/13419

**Comment by maya** [comment]
Thanks @afeld, that looks like it'll be helpful to achieve this. We welcome PRs too if you're still looking for projects to jump in on ;)

**Comment by maya** [comment]
@el-mapache when you have a chance, @el-mapache, would be great to get your eyes on this, so community-submitted PRs don't fail on CircleCI.

**Comment by maya** [comment]
Closed via #2572.
