### ISSUE TITLE
When Chrome Autofills an Address field - it hides the select tag's arrow back ground

### ISSUE THREAD

**Issue by lbai001** [uswds/uswds#2554]
## Description

The problem is that the select arrow we are using is a background image, and when chrome autofill kicks in, the yellow background covers the background image. 

## Steps to reproduce the issue

1. go to: https://www.vets.gov/health-care/apply/application/veteran-information/veteran-address
2. fill in the address
3. continue the form
4. click on Back
5. click on any of the lines that are already filled in
6. click on the chrome autofill

## Additional information [optional]

<img width="540" alt="autofillbug" src="https://user-images.githubusercontent.com/15193547/41426332-20aefc5e-6fb8-11e8-8070-b898b7b45c88.png">

**Comment by maya** [comment]
Hi @lbai001, thanks for reaching out. The good news is that this was already fixed last year in #2186. Please make sure you're using the current version of the USWDS to get all of the latest bug fixes, or use the code that was added in the previous PR.
