### ISSUE TITLE
How to get started with uswds and create-react-app?

### ISSUE THREAD

**Issue by fpigeonjr** [uswds/uswds#2561]
## Description

I am looking for how to get started using the uswds component library after using `create-react-app`.

## Steps to reproduce the issue

1. run `create-react-app myawesomeproject`
2. `cd myawesomeproject`
3. `yarn start`
4. help

## Additional information [optional]

* I am looking for something like [react-strap](https://reactstrap.github.io/) to easily use uswds components in a React project.

**Comment by maya** [comment]
Hi @fpigeonjr, thanks for the suggestion. We'll review this with our team and see how it fits on our roadmap. Stay tuned!

**Comment by fpigeonjr** [comment]
awesome @maya! I appreciate the quick response and support. We are looking to integrate the uswds at work (JBSA-Sam Houston, TX) and I am super excited about this project. Thanks for all you do to unify government sites.

**Comment by maya** [comment]
Great, and if this something your team is able to develop we'd be happy to include it on our [Implementations page](https://designsystem.digital.gov/getting-started/implementations/). You're not the first person to ask about React and I know others would find it useful.

**Comment by fpigeonjr** [comment]
We are thinking of adding a npm package to bring in the uswds UI Components as React Components similar to the [react-strap](https://reactstrap.github.io/) project. Would this be helpful for the community?

**Comment by thisisdano** [comment]
@fpigeonjr That sounds promising

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
