### ISSUE TITLE
Use CSS Grid Layout in grid system - discussion

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2564]
We've heard a few people ask us if the new grid system will incorporate CSS Grid Layout. So far, it will not -- it will be based on flexbox. 

**Our reasoning for just using flexbox:**

Our flexbox grid is that it can be expressed in the terms of our utilities — it keeps the entire system expressible in its own terms. If we moved in the direction of a CSS Grid based grid, that would no longer be the case, since we'd need to develop new CSS grid utilities, and that seems like a complexity level we don't even know how to start on.

In general, CSS Grid adds a layer of complexity that (for now) feels like it's way more overhead than we need

**However here are some of their reasoning:**

>I have been paying close attention (perhaps too close ?) to the work Rachel Andrews and others have been publishing via mozilla developer’s outlets, smashing news updates, and other outlets. CSS grid with a suitable flexbox fall back would enable a forward looking foundation for web layouts.   The primary use case is improving the end user experience, with a secondary use case of helping to clean up the underlying mark up.

>since it's (supposed to be supported in all browsers), it would like eliminate any if* statements. Also, I am just learning about it, but it's nice that empty divs that hold their width & height can be used and we don't have to write separately for mobile. I used to have issues with grids within grids ... but this new (7 month old) thing may be an interesting solution

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).

**Comment by stphnwlkr** [comment]
Having attended An Event Apart and seeing the power of CSS Grid as well as learning that [Internet Explorer supports almost everything](https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/), I think this should be reopened and implemented as the primary grid to minimize the need to redo  and relearn the grid system is a few months.

**Comment by maya** [comment]
When I tried to see if we could do this, I got hung up on how to recreate the variable width and auto-fill example shown here in CSS Grid: https://v2.designsystem.digital.gov/utilities/layout-grid/#auto-layout-columns Are you able to do this? When I looked into this, it seemed like the answer was no, and that's what flexbox was for.

**Comment by stphnwlkr** [comment]
I think that is sort of inherent to the grid using minmax(). In some ways, it is a bit of a paradigm shift.

**Comment by joshbruce** [comment]
Would definitely help me out as I started using CSS Grid and therefore no longer use the grid from the USWDS.
