### ISSUE TITLE
How to deal with `$font-path  $image-path` when importing scss files from Node module?

### ISSUE THREAD

**Issue by nolawi** [uswds/uswds#2568]
## Description

In the app am working on, we have rails asset-pipeline and wanted to import uswds `scss` files directly in our scss directly from node_modules like below

`@import '../../../client/node_modules/uswds/src/stylesheets/core/variables';` 

Problem is that the `image-path` `font-path` are not going to the root of my app `/images` and `/fonts.` I would like to change the paths to be  `/assets/images` and `/assets/fonts.` Even if I set the path in my var file as recommended [here](https://github.com/uswds/uswds#set-the-base-asset-path-fonts-and-images).

Am wondering if you can help me understand [how](https://github.com/uswds/uswds/blob/a23f2647a8b37c6f31572fbb10f231a2752f15de/src/stylesheets/core/_variables.scss#L131) works

**Comment by maya** [comment]
Hi, thanks for opening this issue. What path is it producing you after you set it?

**Comment by nolawi** [comment]
Its rerouting to the root of the app @maya

**Comment by maya** [comment]
Could you share the full path of what you used and full path of what you expected? And a link to the code or live site of the project?

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
