### ISSUE TITLE
Capture additional project metrics

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2570]
Capture additional metrics to illustrate a broad picture of the benefits of the USWDS.

We currently measures adoption and use of the USWDS across government through:
- number of federal sites using the USWDS
- number of page views and users coming to USWDS sites

However, we could begin to capture additional metrics to illustrate a broad picture of the benefits of the USWDS: 
- customer satisfaction across participating sites
- accessibility scores
- money saved through use of the no-cost design system

How can we think about capturing those metrics? Are there other metrics we should be thinking about?

_*This was from a note in OPP's metrics dashboard._

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
