### ISSUE TITLE
Side Navigation Location

### ISSUE THREAD

**Issue by mcharg** [uswds/uswds#2575]
## Description

Have you tested the location of the [side navigation](https://designsystem.digital.gov/components/sidenav/) on the left vs. right?  The site I work on has one on the right and I suspect it would be better to move it to the left, but it would be more convincing to have empirical evidence indicating whether the left side is better.

## Additional information [optional]

This is the site I work on with a right nav:
https://revenuedata.doi.gov/explore/

**Comment by maya** [comment]
Hi @mcharg, thanks for reaching out! We have not tested the side navigation location. There's some work out there that suggests it doesn't matter which side it's on. I'd recommend testing it with your users to see which gets the outcomes you desire. See: https://ux.stackexchange.com/questions/31031/how-to-choose-the-better-placement-for-sidebar-left-or-right

**Comment by mcharg** [comment]
Thanks!  Turns out we can easily rig a dev build that moves the nav for testing.  I'll post what we learn here in case it's helpful to others.
