### ISSUE TITLE
2.0 Alpha - Setting for grid-container-max-width does not impact base settings

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2591]
When making width changes to the _settings.scss these have no impact on the default width set in _variables.css (set for widescreen, but the layout is still 1040px). This should not be the case. The default width @site-max-width and $nav-width should probably go away or inherit these values from _settings. I see the todo in the comments and this should be a top priority. Related, $nav-width should not set the breakpoint for the mobile navigation or rename it nav-mobile-breakpoint and have the related values inherit from here.

**Comment by thisisdano** [comment]
Yup — thanks for the reminder on this! That's just the way it should work I think.

**Comment by maya** [comment]
Fixed in #2750.
