### ISSUE TITLE
Add full width container layout

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2592]
Please add a fullscreen (100%) width layout option to settings.

**Comment by stphnwlkr** [comment]
I think it would be beneficial to have fullwidth as an option in _settings.scss ($theme-grid-container-max-width) so that all the locations that read the setting adjust accordingly. Right now the $theme-grid-container-max-width setting is not being used, but I am assuming it will be.

**Comment by ethuim** [comment]
On the Migration guide it says `.usa-grid-full` in v1 should be `.grid-container.padding-x-0` for v2. But it is not the same. I found that `.padding-x-0` was overridden by a desktop media rule. And had to use `.grid-container` with an inline style attribute `padding:0`. 
By the way, To fill the whole screen I used `max-width:none`. 
I was using Version 2.0.1. Thanks!

**Comment by thisisdano** [comment]
This works as of uswds `2.1.0`. Use `$theme-grid-container-max-width: full`
