### ISSUE TITLE
[Header]: Change direction of dropdown arrow when opened

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2616]
via @mariamarrero in #1905

>Have you considered changing the direction of the arrow on the menu to pointing 'up' or replacing it with an 'X' once the menu is opened? It would stand out against other arrows pointing down and will give a visual cue that you need to click on the menu to close it.
>
>PS: We have gotten direct comments from users on these 2 issues.

<img width="605" alt="dropdown up or down" src="https://user-images.githubusercontent.com/5249443/43157292-794dffde-8f31-11e8-95db-36a4b7f649fd.png">

**Comment by maya** [comment]
Here's some feedback I got from Nielson Norman Group's support email around this question:

>I am not aware of any specific research on drop-down caret orientation. However any particular study might not generalize to all situations, because there are several factors that affect the value of this design detail.
>
>In general, it's best to provide explicit signals to differentiate each navigation state. So technically it is better to have the caret position change when the menu is expanded; especially if the menus are click activated (rather than hover activated), to suggest that once the menu is expanded, it can also be collapsed by clicking the 'up' caret.
>
>However if the menu is hover activated and has a background color that has high contrast against the page (such as dark blue over a white page), then the benefit of re-orienting the caret to indicate an open or closed state will likely be negligible, because it's already obvious that the menu is expanded and users don't need to click it again to close it.
>
>Note that the previous comments apply to horizontal menus such as the image you sent. Vertical menus have a different set of challenges and typically they do benefit from having distinct 'open' and 'close' icons.

**Comment by bpdesigns** [comment]
my vote on this would be to point the caret up ^ to indicate open

**Comment by mariamarrero** [comment]
@bpdesigns, that is exactly what we did in USA.gov. :)

**Comment by thisisdano** [comment]
This is what we do in the banner, so let's go ahead and do it here, too. Down caret indicates `openable`, up caret indicates `closable`

**Comment by greensteph** [comment]
There isn't currently a _white Carat Up_ UI element. I'm adding 2 options below using existing elements. Do we use one of these or create the Carat Up in white? @thisisdano @saracope 

Blue Up Carat:
<img width="1105" alt="screenshot 2019-02-22 13 23 12" src="https://user-images.githubusercontent.com/11343071/53264977-07391600-36ab-11e9-8cb1-6b6b1d96ee60.png">
<hr>
White Close X:
<img width="1099" alt="screenshot 2019-02-22 14 05 15" src="https://user-images.githubusercontent.com/11343071/53264988-0dc78d80-36ab-11e9-9667-5a9d711aa64b.png">

**Comment by maya** [comment]
Closed in #2923. 

Nice work 🎉
