### ISSUE TITLE
Ensure functions.scss uses style best practices

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2629]
Since there are no best practices guide for Sass functions, let's take our inspiration from JavaScript function style best practices.

- [ ] Share blog posts on JS function best-practices @el-mapache 
- [ ] Remove vestigial code

**Comment by thisisdano** [comment]
I've done some work on this based on our earlier discussion (https://github.com/uswds/uswds/pull/2626) — though many of the functions and mixins could use another set of eyes.

**Comment by maya** [comment]
We're on the path of this with other issues, e.g. #2685.
