### ISSUE TITLE
Navigation layout issues in Firefox

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2631]
If you change the default magnification (high dpi screens) or browser zoom that moves off 100%, Firefox shifts or centers the navigation (tested on Mac and Windows). This is resolved by removing margin-top:-1px from .usa-nav-inner. Is there a reason for this margin? 

<img width="1193" alt="firefox_issue" src="https://user-images.githubusercontent.com/1405187/43261970-83f9b3fc-90ac-11e8-8b41-0ef4cbe15f0f.png">

**Comment by maya** [comment]
@stphnwlkr thanks for letting us know. That sure is an odd behavior in Firefox! I can't recall exactly why that was added, but if I'd have to guess it may have been for browser quirks (which makes this ironic) or to get it exactly a certain height. Will have to take a look to see if we can safely remove it though.
