### ISSUE TITLE
2.0 Alpha - Theme fonts not based on new font families

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2633]
I attempted to set $theme-font-heading to $theme-font-sans in the settings file, but in typography.scss, the font families are not based on the theme values. When I made the change in typography.scss to use the theme value, the font family is set as source-sans-pro and not "Source Sans Pro Web","Helvetica Neue",Helvetica,Roboto,Arial,sans-serif".

**Comment by thisisdano** [comment]
You're right — we haven't gotten to this yet. Hoping to address variable usage this sprint.

**Comment by thisisdano** [comment]
This work is scheduled for the current sprint

**Comment by maya** [comment]
Done in #2731 .
