### ISSUE TITLE
Header visual bugs in Microsoft Edge

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2638]
In Edge 17, it looks like the navigation items and dropdowns have list styling on them: 
<img width="563" alt="ie 17 - edge" src="https://user-images.githubusercontent.com/5249443/43428085-5a16a578-9411-11e8-8b57-a44b348175e0.png">

In Edge 16, it's similar to the above but w/o the top-level nav bug, only in the dropdown.

**Comment by stphnwlkr** [comment]
I would be curious to know where are you seeing this? I use Edge all the time and have not experienced this issue.

**Comment by maya** [comment]
I checked on an IE simulator and then on a Windows machine. Strangely hard refreshing makes it go away occasionally so it may be a browser/cache quirk? I think we can go ahead and close this if it's not a consistent issue.
