### ISSUE TITLE
2.0 accordion was overwritten by 1.0 accordion

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2648]
It looks like this commit https://github.com/uswds/uswds/commit/118c0b0e8ffc1be0e5e70ece834cc8e225f77155#diff-892b1d25097ad1baaf33cac3a950176c saved over 2.0 work from the develop branch. I see this bc the [new 2.0 accordion](https://github.com/uswds/uswds/pull/2360) was saved over, replaced by the old accordion.

@el-mapache the JS changed in this too, should see how this affects any new work you did here.

What's an unknown is whether other 2.0 work was overwritten as well.

**Comment by thisisdano** [comment]
Oy. Jeez. I wonder what the heck that was all about. 😬 
Can't even remember what stupid event led to this.

@el-mapache Lemme know if we should meet to sort this out.

**Comment by maya** [comment]
Fixed in #2672.
