### ISSUE TITLE
Question: How to build .css files

### ISSUE THREAD

**Issue by awolfe76** [uswds/uswds#2681]
I'm building a React app, using [Create React App](https://github.com/facebook/create-react-app), and I'd like to be able to use the [`import './styleFile.css'`](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-stylesheet) feature that Webpack provides and still use USWDS.

Due to the dependencies between files there doesn't seem to be an easy solution but I'm curious to know if you have a way to generate individual `.css` files for each `.scss` file. I've attempted to do this by cloning the repo and adding `@import` statements when errors occur but that's definitely not ideal. 😄 

For example, I'd like to get:

- [`_buttons.scss`](https://github.com/uswds/uswds/blob/develop/src/stylesheets/elements/_buttons.scss) -> `_buttons.css` (or `buttons.css`)
- [`_inputs.scss`](https://github.com/uswds/uswds/blob/develop/src/stylesheets/elements/_inputs.scss) -> `_inputs.css` (or `inputs.css`)

Thanks!

**Comment by maya** [comment]
Hi @awolfe76, thanks so much for reaching out. Unfortunately, we don't have a way to build or import single files at this point. It's not on our roadmap, but we'll keep you posted if this changes in the future.

**Comment by maya** [comment]
Also, in v2 we may have more separation of components and may be able to do those kinds of imports.
