### ISSUE TITLE
Paragraph bottom margins

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2705]
We changed the paragraph styling to only have top margin, in use I'm seeing some regressions and wanted to consider these:

<img width="604" alt="screen shot 2018-08-28 at 10 51 18 am" src="https://user-images.githubusercontent.com/5249443/44740894-6f1df380-aab0-11e8-8a50-f78391a818ab.png">

<img width="691" alt="screen shot 2018-08-28 at 10 51 28 am" src="https://user-images.githubusercontent.com/5249443/44740895-6fb68a00-aab0-11e8-8e38-d3266291349c.png">

Does it make sense to re-add the bottom margin to give paragraphs that bottom bumper on `.usa-prose`? Or do we want to force folks to add it in manually. I can see it getting easy to forget. @thisisdano

**Comment by maya** [comment]
Another idea, use adjacent sibling selectors, e.g.: `p + * { margin-top: 1em; }`. 
This would still allow us to have sections w/o any added bottom margin.  /cc @thisisdano

**Comment by maya** [comment]
@thisisdano another related issue, should the first `p` also not have a margin like headings? i.e. should it be rewritten as: 
`* + p {margin-top: 1em}` instead of `p {margin-top: 1em}`?

**Comment by thisisdano** [comment]
oh huh! maybe?! it makes sense

**Comment by maya** [comment]
Fixed in #2706.
