### ISSUE TITLE
Update system colors to luminance-normalized values

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2712]
If we normalize each color at each grade around the `gray` luminance value for that grade, we should have a color system that delivers on its promise: to achieve AA Large contrast for magic numbers of 40+ and AA contrast for magic numbers of 50+.

Our new luminance conversion tools will assist in this. Most colors will see only minor adjustments, but some may be a bit more noticeable. See [this chart](https://v2.designsystem.digital.gov/style/color/system-palette-adjust/) for the first pass of automatic adjustments. About 80% of the automatic adjustments are OK as is, the rest can be hand tuned as needed.

**Comment by maya** [comment]
Done in #2713.
