### ISSUE TITLE
Create functions for tokens that currently only have mixins

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2723]
- `radius()`
- `z-index()`
- `line-height()`
- `measure()`
- `font-family()`

Hm... any others?

**Comment by maya** [comment]
I don't think we need it for border radius. This worked: `border-radius: units($theme-border-radius-sm);`

**Comment by thisisdano** [comment]
Aaand it turns out we _did_ already have all these anyway. Turns out the only one I had to add was `font-family()`.

I also made succinct clones of each hyphenated function since it's simple and maybe helpful:

| verbose | succinct
|---|---
|`line-height()` | `lh()`
|`font-weight()` | `fw()`
| `font-family()` | `ff()`
| `letter-spacing()` | `ls()`
|`z-index()` | `z()`

**Comment by thisisdano** [comment]
Resolved by https://github.com/uswds/uswds/pull/2725
