### ISSUE TITLE
Creating a copy of _variables.scss and importing it before USWDS breaks the neat grid

### ISSUE THREAD

**Issue by m8ker** [uswds/uswds#2749]
## Description

When I follow the [Install using NPM](https://github.com/uswds/uswds#install-using-npm) instructions, installing USWDS with npm, then importing a copy of the _variables ahead of importing uswds, my 'usa-width-two-thirds etc" classes lose their styling. "usa-grid" and all other classes I see retain their styling. 

My own SCSS stylesheet has this content: 

```
@import '_po-variables';
@import '../node_modules/uswds/src/stylesheets/uswds';
```
If I comment out the first line, the grid is functional. If I un-comment it, my grid breaks. 

I've tried a few different sass compilers. 

It seems to be related to the breakpoints set in my overriding "_po-variables.scss" file, since if I comment them out, the grid starts working. However, they're identical to how they are defined in the original _variables.scss file. 

```
$small: new-breakpoint(min-width $small-screen $grid-columns-small) !default;
$medium: new-breakpoint(min-width $medium-screen $grid-columns-medium) !default;
$large: new-breakpoint(min-width $large-screen $grid-columns-large) !default;
```

## Steps to reproduce the issue

1. Follow the [instructions](https://github.com/uswds/uswds#install-using-npm) to install.
2. In the overriding "_variables.scss" file, remove "$helvetica" and "$georgia" since these variables don't exist in the code base.
3. Run the project. 
4. Try compiling and viewing with and without the overriding "_variables.scss" file

**Comment by maya** [comment]
Have you tried changing these vars instead e.g. `$medium-screen: 700px;`?

We will be deprecating that grid in our 2.0 release in favor of this [new grid](https://v2.designsystem.digital.gov/utilities/layout-grid/) and unable to support the old.

**Comment by m8ker** [comment]
@maya, thanks for your reply. Changing those variables in the overriding variables.scss file does not fix the issue.  Do you have any other ideas of what might be going on?

I'm trying to develop a theme based on USWDS and I'm wondering how best to move forward, so when 2.0 is available, I can just upgrade and everything will work well. 

- Is the method you describe [here](https://github.com/uswds/uswds#install-using-npm) the best way to set myself up for a smooth upgrade?

- Do you have an estimation of when you're releasing 2.0?

**Comment by m8ker** [comment]
We use USWDS as the base theme for lots of municipal-level transportation project websites. [Here is an example](https://wsblink.participate.online/). We want to switch our approach to a single-page layout with levels of engagement. The idea is that a user will be able to scroll through the site for a summary and be able to dig deeper into particular sections that interest them (we'll probably end up using a modified version of your accordion that is more like a summary section that expands to the full section). 

We've found that most users only spend 3 minutes on our sites, so we need them to understand what they need to know in three minutes, but also offer the ability to engage in surveys and dig into details if they are interested. 

By the way, we love USWDS!

**Comment by maya** [comment]
It doesn't look like we'll be able to support this level of customization of our grid, but encourage you to use custom media queries as needed or transition to our [2.0 grid system](https://v2.designsystem.digital.gov/utilities/layout-grid/).
