### ISSUE TITLE
Break out system tokens into JSON files

### ISSUE THREAD

**Issue by el-mapache** [uswds/uswds#2753]
## Description

Right now, all of our system tokens live directly in SCSS. This makes it impossible to share these values between platforms (for example, a sketch file) or projects. 

We should investigate breaking these out into separate JSON files and using a style dictionary library like [style-dictionary](https://github.com/amzn/style-dictionary/) or [theo](https://github.com/salesforce-ux/theo) to generate SCSS.

Its likely that our design tokens will want to live in a separate repo. This will make it easy to include the tokens in other projects, and transform them as necessary

**Comment by thisisdano** [comment]
This was implemented for colors in https://github.com/uswds/uswds/pull/2756
Any additional work can be in a new issue
