### ISSUE TITLE
Alerts usa-alert-slim version doesn't resize the icon.

### ISSUE THREAD

**Issue by nolawi** [uswds/uswds#2755]
## Description

The icons in this [alerts](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/detail/alerts--slim.html) version does not reduce the size of the icon. 

<img width="283" alt="screen shot 2018-09-19 at 2 58 39 pm" src="https://user-images.githubusercontent.com/1745984/45775013-8b7aff00-bc1c-11e8-94d9-885dc4bcb583.png">

<details><summary>Propose</summary>

<img width="1093" alt="screen shot 2018-09-19 at 11 00 44 am" src="https://user-images.githubusercontent.com/1745984/45762083-94a7a400-bbfb-11e8-9f4a-8e7193ea9b67.png">

</details>

` .usa-alert-slim {
    background-size: Xrem;`

[Location](https://github.com/uswds/uswds/blob/develop/src/stylesheets/components/_alerts.scss#L64)

**Comment by thisisdano** [comment]
Interesting — I'm game to make it smaller. @maya what do you think?

**Comment by maya** [comment]
Is the suggestion to reduce the icon size in `usa-alert-slim` or for all the alerts at small screen sizes or both?

**Comment by nolawi** [comment]
Just the slim version; since the font size is constant on all alerts regardless of screen size, it doesn't make sense to resize the icon on the default.

**Comment by maya** [comment]
This was done in #2946. Thanks @nolawi for bringing this up!
