### ISSUE TITLE
Re-add font-smoothing to buttons (dark background + light text)

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2761]
Should we re-add font smoothing to buttons?

As stated http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/, they recommend using font smoothing on dark backgrounds + light text. Our buttons fall into this category (any others)? 

## w/o font smoothing
<img width="544" alt="screen shot 2018-09-20 at 4 53 53 pm" src="https://user-images.githubusercontent.com/5249443/45852708-019f6480-bcf6-11e8-9d61-775281f9391f.png">
Is legibility reduced bc the pixels spill out making the letters less defined?

## w/ font smoothing
<img width="554" alt="screen shot 2018-09-20 at 4 53 41 pm" src="https://user-images.githubusercontent.com/5249443/45852707-0106ce00-bcf6-11e8-856f-1a39be4d4dcb.png">

**Comment by thisisdano** [comment]
I agree that the reversed text here is far more legible with subpixel rendering disabled. I hesitate to call it _smoothing_, exactly. (At least on a nice retina Mac!) It could be nice to see some examples of renders on a non-Mac, but on the face of it, this seems like a reasonable request.

**Comment by thisisdano** [comment]
This could also apply to nav menus, tags, graphic list. I wonder if there's a good way to automate this in Sass — that is, to make font rendering mode dependent on reversed (white, etc) text?
