### ISSUE TITLE
Search form missing in mobile menu

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2768]
I was just trying to troubleshoot an issue where the search field is now missing in the mobile menu. It appears this is a system issue as the [extended header samples](https://designsystem.digital.gov/components/headers/extended/) now have the same problem. I suspect it is related to changes made in #2603.

**Comment by maya** [comment]
Hi @stphnwlkr, thanks for opening this issue. Yes, this is a bug and hope to get a fix in shortly. Will note that this hide/show search will not be used in the v2 header, it will be open by default.

**Comment by stphnwlkr** [comment]
Thank you.
