### ISSUE TITLE
Minor edits request on the "An official website ..." line

### ISSUE THREAD

**Issue by ToniBonittoGSA** [uswds/uswds#2781]
## Minor edits request

Howdy ~ 

- [ ] There should be a period at the end of the first sentence.
- [x] Can the link on the empty space between the word _know_ and the down arrow be removed? 
Since the text and the image are separate elements, an underlined empty space looks a little odd

## Additional information [optional]

<img width="575" alt="screen shot 2018-09-26 at 9 04 21 am" src="https://user-images.githubusercontent.com/19961574/46081962-d7252f80-c16b-11e8-942f-32827b1d8c30.png">

**Comment by thisisdano** [comment]
I'm conflicted about this first point, as the `An official website...` line is a fragment, which would not normally take a period. But since it is directly followed by an actionable item, it could make sense.

I think we can address the underlining, though. Thanks for catching this.

**Comment by ToniBonittoGSA** [comment]
Hmm.. I can see that
 --  maybe [it wouldn't "need" a period] if there was a single space between the flag and the text, and then a double or triple space between the text and the link? And/or the text was a different font?

**Comment by maya** [comment]
Here is the current design of the government banner:

<img width="452" alt="screen shot 2018-09-26 at 9 59 32 am" src="https://user-images.githubusercontent.com/5249443/46096031-ef4c7d00-c172-11e8-9db2-bc8966890385.png">

via https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/banner.html

The link in a different color helps set it apart.

This version does not have an extra space between the word know and the down arrow.

**Comment by maya** [comment]
@ToniBonittoGSA we've updated the banner with your suggestion of removing the extra part of the underline. Can you take a look and let us know if there's anything else we should consider changing? https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/banner.html

**Comment by maya** [comment]
Fixed in #2786.

**Comment by ToniBonittoGSA** [comment]
Looks great! thanks!
