### ISSUE TITLE
Restrict use of utilities in standard components

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2789]
As much as possible, we don't want a user's utilities settings to adversely affect the performance of standard components. In fact, I might go so far as to say that users should not require any utilities in order for standard components to work properly.

We should find any utilities we use on our standard components and evaluate whether we could do the same thing without them.

**Comment by maya** [comment]
Which components use them?

**Comment by thisisdano** [comment]
Not sure if any! But I noticed that there were a couple manual adjustments to the utilities settings when I was updating `uswds-site` and it raised a red flag that we were using them somewhere

**Comment by thisisdano** [comment]
Fixed with #2823
