### ISSUE TITLE
Lists aren't indented

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2790]
Before lists had an indentation of 1.94em, or around 15px left indentation from the bullet. Now they are fixed and don't appear indented. It even doesn't align to flush left. Using ems made it relative to the font size, good if you have different sizes of text that are lists. 

What I see:
<img width="310" alt="screen shot 2018-09-26 at 2 37 24 pm" src="https://user-images.githubusercontent.com/5249443/46110809-ae1b9380-c199-11e8-859c-c635b240d4a3.png">

<img width="333" alt="screen shot 2018-09-26 at 2 36 31 pm" src="https://user-images.githubusercontent.com/5249443/46110797-a1973b00-c199-11e8-8cc3-dc07c45be98a.png">

What I expect:

<img width="325" alt="screen shot 2018-09-26 at 2 35 52 pm" src="https://user-images.githubusercontent.com/5249443/46110790-9e9c4a80-c199-11e8-978d-a02e941b7a36.png">

**Comment by thisisdano** [comment]
We could move to something like `3ch` here

**Comment by maya** [comment]
Fixed in #2793
