### ISSUE TITLE
Version 2 - Mobile menu oddity in Edge

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2794]
Seeing a very strange behavior in the V2 website. The desktop Edge browser, reduced to show the mobile menu, is showing bullets. This does not appear in Edge on iOS. This is a screenshot comparing Edge and Chrome.
![nav_issue](https://user-images.githubusercontent.com/1405187/46165371-7c203500-c25e-11e8-8888-95bb6ba64948.png)

**Comment by thisisdano** [comment]
Hm! 🤔 Let me take a look at that. Are the bullets just in the mobile menu or do they appear in any other menu or unexpected location?

**Comment by stphnwlkr** [comment]
Just in the mobile menu

**Comment by thisisdano** [comment]
Unfortunately, I'm not able to easily troubleshoot Edge. Can you inspect this and let me know if there's something that looks amiss: particularly in `list-style-type` being attached to the wrong element or something like that?

**Comment by stphnwlkr** [comment]
I am not sure either...compared Chrome to Edge and no difference.

**Comment by stphnwlkr** [comment]
Interesting...apparently it is a known issue.  list-style-type:none not loading on initial page load. Refreshing the page fixes the problem. I have never noticed it.

https://github.com/webhintio/webhint.io/issues/210

**Comment by thisisdano** [comment]
Whoa. Thank you for tracking that down!

**Comment by stphnwlkr** [comment]
I submitted a bug to Microsoft (I think it might be a regression). 

Sort of related but not browser specific -  usa-accordion-bordered does not set list-style-type to none. See https://v2.designsystem.digital.gov/components/typography/#pairings-and-styles

**Comment by thisisdano** [comment]
Awesome — and thanks. Fix is already underway for that accordion issue :)

**Comment by stphnwlkr** [comment]
So will the accordion fix be like buttons where "bordered" is just and extension of usa-accordion ?

**Comment by thisisdano** [comment]
Yes, in general we are moving to a classing model where variant classes are additive to the base class. As in `usa-button usa-button-outline` and `usa-accordion usa-accordion-bordered`

**Comment by stphnwlkr** [comment]
Excellent!

**Comment by maya** [comment]
Should this be closed since it's a Chrome bug?

**Comment by thisisdano** [comment]
Edge bug, but yes :) 👋
