### ISSUE TITLE
Add Public Sans to a new repo within the uswds org

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2796]
Currently, the Public Sans project files are in a very old repo within 18F (https://github.com/18F/18franklin). The info in this repo should be checked and updated, and moved to a home more consistent with its purpose — which, I would say, is within the `uswds` org.

**Comment by maya** [comment]
@thisisdano we can make this move pretty easily, want to do it now?

**Comment by thisisdano** [comment]
May as well — there are still a lot of improvements to make to the repo, but there's no reason to delay moving the repo because of them

**Comment by maya** [comment]
I don't have access to that repo, happy to do it if you give me access to it, otherwise, you can do it in Settings.

**Comment by thisisdano** [comment]
Done. https://github.com/uswds/public-sans
