### ISSUE TITLE
Address any vulnerabilities associated with mem@1.1.0

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2797]
We're seeing Snyk notifications around USWDS and mem@1.1.0. I'm confident that this is not a realistic vulnerability, but it would be nice if it were not a red flag at all. Can we update our use of `mem`?

**Comment by thisisdano** [comment]
@maya @el-mapache What's the best way to do this?

**Comment by maya** [comment]
yeah, we could update mem.

**Comment by thisisdano** [comment]
haha I guess I thought `mem` was a subdependency :)

**Comment by maya** [comment]
it is, you can still update it though

**Comment by thisisdano** [comment]
For reference, according to Snyk, this is an issue with `yargs` which they are working to fix for `12.0.2` (we are on `8.something` but I tried to update to `12.0.1` and that worked without issue): https://github.com/yargs/yargs/issues/1209

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/uswds/pull/2842
