### ISSUE TITLE
Class `usa-date-of-birth` is overly specific about use cases

### ISSUE THREAD

**Issue by dmethvin-gov** [uswds/uswds#2805]
The class name [`usa-date-of-birth`](https://github.com/uswds/uswds/blob/3f3fcca941d7f165a88aebe240abd97448560819/src/stylesheets/elements/_inputs.scss#L360-L394) is very specific, but the actual presentation is just a month, day, and year input that could be used for any date. Could it be changed to a more generic name (`usa-month-day-year` or some such) or if that's too breaking could a more generic alias be added?

**Comment by maya** [comment]
Hi @dmethvin-gov, we agree with you. That's why we changed it to `usa-memorable-date` in v2: https://v2.designsystem.digital.gov/components/form-controls/#date-input Will close this out as it's been addressed there.

**Comment by dmethvin-gov** [comment]
Awesome, thanks!
