### ISSUE TITLE
Print styles for checkboxes

### ISSUE THREAD

**Issue by David-Way** [uswds/uswds#2810]
## Description
When printing a page containing a checkbox in the checked state, there is no clear indication of the fact that the fields are selected/checked -  the thin checkbox outline/box shadow is all that is visible (difficult to notice).

## Steps to reproduce the issue
1. Print a page with a selected checkbox on it
(Chromes print preview pane allows you to see this behavior without having to actually print the page.)

<img width="192" alt="screen shot 2018-10-03 at 21 34 56" src="https://user-images.githubusercontent.com/6078452/46437940-7346cc00-c754-11e8-8989-d2e0e4b41b09.png">

## Additional information 
The reason this happened is because most browsers’ default behavior is to not print background colors and the visual state of the checkbox is dependent on a background color.

**Comment by thisisdano** [comment]
Added to develop in https://github.com/uswds/uswds/pull/2831
