### ISSUE TITLE
Improve documentation around prose scope

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2814]
If the settings variables are the only introduction you have to prose scope, it'll probably be difficult to understand. What can we do to make it clear what prose scope does and how its settings work?

**Comment by greensteph** [comment]
I also just ran into this. I found it confusing and could use some documentation around the settings language and usage.

**Comment by maya** [comment]
Done in #726.

New prose documentation: https://v2.designsystem.digital.gov/components/typography/#prose
