### ISSUE TITLE
V2 Beta 1 - Button variations not working

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2817]
When using usa-button and then a modifier, the modifiers are not overiding the background colors. I had to add !important to all the button-secondary modifiers for them to work.

**Comment by stphnwlkr** [comment]
Took me a minute to reprocude, but it turns out that button-visited wipes out the modifiers.

**Comment by thisisdano** [comment]
Oof. Buttons shouldn't have a `:visited` style. I'll get on that.

**Comment by thisisdano** [comment]
OK, I've got a fix here if you want to check it out: https://github.com/uswds/uswds/pull/2827

**Comment by stphnwlkr** [comment]
Integrated the changes and buttons are working as expected

**Comment by thisisdano** [comment]
Updated!

**Comment by thisisdano** [comment]
@stphnwlkr Does the updated solution in #2827 work for you?

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/uswds/pull/2827/
