### ISSUE TITLE
Add print style for checked checkboxes and radio input in USWDS 2.0

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2820]
See v1 issue (https://github.com/uswds/uswds/issues/2810) and PR (https://github.com/uswds/uswds/pull/2811)

**Comment by thisisdano** [comment]
Also for radio buttons: https://github.com/uswds/uswds/pull/2857

**Comment by thisisdano** [comment]
Checkbox print styles are already in.
Radio print styles are included in https://github.com/uswds/uswds/pull/2950

**Comment by maya** [comment]
Done in #2950.
