### ISSUE TITLE
[USWDS 2.0 Beta Week 1] Getting started

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2839]
## USWDS 2.0 Beta Program Week 1

:wave: and hello and thank you for your interest in the US Web Design System 2.0 Beta program! 

Your feedback is important to the success of the program. Our beta program will run for about two months, during which we hope to improve the clarity and ease of use of the system. We won't be able to make every change, but our goal is to make what we have easier to understand and implement, and to work as expected without major bugs.

As the beta program progresses, I'll be in touch via email with specific questions and requests. I'll also post new issues in this repo for a weekly check-in. My first request is simple:

**1: Visit our uswds project repos:**
- https://github.com/uswds/uswds
- https://github.com/uswds/uswds-site

**2: Leave a comment in our Beta Program week one issue:**
- https://github.com/uswds/uswds/issues/2839  (that's this issue!)

**3: Install USWDS 2.0 Beta on a new or existing project**
- Follow the instructions at https://v2.designsystem.digital.gov/documentation/

**4: Read through the documentation, especially the two new sections:**
- Utilities: https://v2.designsystem.digital.gov/utilities/
- Style: https://v2.designsystem.digital.gov/style/

- - -

Each week, I'll set up a new issue in the `uswds` repo so we call can check in and learn what's new. I'll send you all an email as well.

Use these issues as home base for the beta program. **Please feel free to add issues to any USWDS repo at any point** — or leave comments, questions, and findings via email or in the weekly issue. No issue, comment, or question is too small or too large.

You can email me directly with questions at daniel.williams@gsa.gov or you can find me in Slack at the `TTS/#uswds-public` channel. If you are not already in that Slack, visit https://chat.18f.gov/ to sign up.

The Beta program is open to any interested party. Use the Slack, the Beta Program issues, or email me directly to be involved.

Thanks and :rocket: — onward!

**Comment by jeremyzilar** [comment]
Count me in 🎉

**Comment by stphnwlkr** [comment]
Leaving a comment as requested. I have two sites 98% converted from 1.68 to 2.0 beta - one of which should be live this week...learning curve is not steep, but more like rolling hills.

**Comment by danielnaab** [comment]
Comment as requested - we're using for a few projects at USGS Water Mission Area, and are transitioning to 2.0.

**Comment by donjo** [comment]
👋hello, I'm in

**Comment by stphnwlkr** [comment]
Downloaded the zip, recompiled css (I use the scss files exclusively), tested, deployed to production. No errors - button issue resolved (thank you).

**Comment by stphnwlkr** [comment]
@thisisdano the beta 2 folder has all the bourbon and neat files in the lib folder again.

**Comment by thisisdano** [comment]
Arg. Thanks for letting me know. I updated the release .zip package.

**Comment by maya** [comment]
Thanks for participating in the beta program. Your feedback was really helpful. USWDS 2.0 will release on 4/8.
