### ISSUE TITLE
Print styles for radio buttons

### ISSUE THREAD

**Issue by David-Way** [uswds/uswds#2847]
## Description
When printing a page containing a radio button in the checked state, there is no clear indication of the fact that the fields are selected/checked -  the thin radio button outline/box shadow is all that is visible (difficult to notice).

## Steps to reproduce the issue
1. Print a page with a selected radio on it
(Chromes print preview pane allows you to see this behavior without having to actually print the page.)

<img width="262" alt="screen shot 2018-10-14 at 11 16 24" src="https://user-images.githubusercontent.com/6078452/46915905-8b1b1d00-cfaa-11e8-9b6f-c9067c98ff43.png">

## Additional information 
The reason this happened is because most browsers’ default behavior is to not print background colors and the visual state of the checkbox is dependent on a background color.

**Comment by maya** [comment]
Looks like this was fixed in #2848 and can be closed.

**Comment by maya** [comment]
My mistake, looks like there's an open PR for this #2857 to merge this into `develop`, re-opening.

**Comment by thisisdano** [comment]
This is now merged and will go out in the next 1.x patch release
