### ISSUE TITLE
Border utility mixin is not working properly

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2849]
The `u-border()` utility mixin should accept border-style, units, and color tokens but is only working with border-style now. And it's giving a relatively unhelpful error message.

Thanks for pointing this out @jeremyzilar

**Comment by arch-lord** [comment]
I’ll attempt a fix tomorrow morning after a good night’s sleep. Although I don’t know the project structure very well, I have some ideas as to this issue.

**Comment by thisisdano** [comment]
Thanks @arch-lord — I think I probably know what's going on, but I'd love to have you take a swing at this — if only to approach the issue with fresh eyes.

**Comment by thisisdano** [comment]
OK, I was having trouble reproducing this and can now clarify that the issue seems to be that the mixin is not accepting the string equivalent units values like `'05'`. The numeric values like `0.5` are OK.
