### ISSUE TITLE
Determine if we should we run codeclimate on the 2.0 branch(es)

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2856]
Let's look at how and why we use codeclimate and the implications of adding codeclimate to our 2.0 CI. Do we need to update our tests? Will we find unacceptable complexity? To satisfy this issue we should determine:

- - -

- What is Codeclimate testing on our `master`/`develop` branches?
- Should we use it on the 2.0 branch(es)
- Do we need to update code or tests to make the integration a success?
- Suggest test or code improvements, if necessary.

**Comment by saracope** [comment]
Code Climate will only run on the default branch.  It sounds like it may not be getting fully approved to use. 

I will look at codecov.io as was suggested.

**Comment by maya** [comment]
The 2.0 branch merged into develop (the default branch), so this is no longer relevant. Though if we need to migrate to a different code coverage platform, that can be opened in a new issue.
