### ISSUE TITLE
2.0 beta: Can't add custom font definitions

### ISSUE THREAD

**Issue by yomatters** [uswds/uswds#2870]
The `$theme-font-definitions` variable is supposed to be used to add custom font definitions. However, it's currently difficult to override this variable because the default value (an empty map) is not defined using `!default`. The `$theme-font-definitions` variable should be defined using `!default` in `_settings-typography.scss` so that it can be overridden.

**Comment by thisisdano** [comment]
Good catch — that'll be fixed by the next beta release.

**Comment by yomatters** [comment]
Thanks!

**Comment by yomatters** [comment]
Fixed in 63ce5bf6b75d4962e6de83e49744c70ef716a21c. Thanks!
