### ISSUE TITLE
Multiselectable accordions: using aria-multiselectable is invalid for list roles

### ISSUE THREAD

**Issue by jbalboni** [uswds/uswds#2871]
## Description

The current approach for making an accordion able to have multiple sections open at once is to add `aria-multiselectable` to the `ul` element. However, this attribute is not valid for the [list role](https://www.w3.org/TR/wai-aria-1.0/roles#list). It has a specific [list of roles](https://www.w3.org/TR/wai-aria-1.0/states_and_properties#aria-multiselectable) that don't appear to fit in with an accordion pattern (at least in my non-expert reading). As a result, checkers like aXe flag usage of it as a violation:

![screen shot 2018-11-09 at 9 50 04 am](https://user-images.githubusercontent.com/634932/48269149-e05d1980-e404-11e8-9021-e5292bc9f358.png)

(from https://www.va.gov/disability/va-claim-exam/)

Could there be a non-aria attribute instead that flags accordions as being able to have multiple items open, so that we don't have to use this aria attribute incorrectly?

## Steps to reproduce the issue

1. Install aXe checker Chrome extension
2. Go to https://www.va.gov/disability/va-claim-exam/
3. Run aXe check

**Comment by stphnwlkr** [comment]
@jbalboni I am not a USWDS rep, but I am fairly certain this is why the multiselect option was removed from 2.0 and accordions no longer use the ul element.

**Comment by thisisdano** [comment]
As @stphnwlkr says, this is fixed in USWDS 2.0
