### ISSUE TITLE
"site is secure" and ".gov means it's official" icons filling page when printing

### ISSUE THREAD

**Issue by suprenant** [uswds/uswds#2883]
When I visit https://join.tts.gsa.gov/ as well as some 18F guides (including the [Agile Guide](https://agile.18f.gov/)) and print, I notice that the lock and courthouse icons fill an entire page. 

I do not notice this on some other sites using USWDS. 

From a colleague in TTS Slack:
_It would appear nothing is constraining the SVG sizes. I wonder where the shared print style for the guides comes from_

![screen shot 2018-11-16 at 10 51 09 am](https://user-images.githubusercontent.com/1452369/49038710-4ecf0500-f183-11e8-9f4f-143058e9d5f3.png)
![screen shot 2018-11-16 at 10 51 06 am](https://user-images.githubusercontent.com/1452369/49038711-4f679b80-f183-11e8-9017-1f6577ade282.png)

**Comment by greensteph** [comment]
Hi @suprenant thanks for submitting this issue. We are exploring how to best provide a solution as well as improving print styling overall.

**Comment by suprenant** [comment]
@greensteph sounds good, thanks for the update. I'll look forward to seeing what might come from this. If you ever want any feedback or anything, please let me know.

**Comment by thisisdano** [comment]
This is fixed in USWDS 2.0 with https://github.com/uswds/uswds/pull/2910.
Once the dust clears from 2.0, we can look into getting this into a 1.x release.
