### ISSUE TITLE
Address all current Snyk warnings and PRs

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2889]
Snyk has been hard at work proposing PRs. Are they necessary? If they address the code in sample files, should we make that fix or is the sample file even at all relevant now. Let's use the Snyk PRs as an opportunity to review the sample setups we provide and either edit them or remove them.

- - -

See the following:
- #2888 
- #2882 
- #2869 
- #2859

**Comment by maya** [comment]
Can this issue be closed now since these are merged in: #2963 #2957? /cc @saracope

**Comment by saracope** [comment]
No, one more PR to do on the `develop` branch.
