### ISSUE TITLE
Vender prefixes (might be) needed for `appearance` property

### ISSUE THREAD

**Issue by blacktm** [uswds/uswds#2891]
Hi there. I'm using 2.0.0 Beta 4 on a new project and noticed the `select` input element wasn't getting properly styled. After experimenting, I noticed that `appearance: none;` wasn't taking in Safari, Chrome, Firefox. After adding these vendor prefixes...

```
select {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}
```

...everything is good. Looks like [basic support for `appearance`](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance#Browser_compatibility) isn't quite there yet. Interestingly, the [documentation site](https://v2.designsystem.digital.gov/components/form-controls/#dropdown) has these prefixes present, but can't seem to find them [in the source](https://github.com/uswds/uswds/blob/release-2.0/src/stylesheets/elements/_inputs.scss#L126). Anyways, just wanted to confirm before sending a PR. Thanks!

**Comment by thisisdano** [comment]
Are you compiling your own css or using the precompiled version?

**Comment by thisisdano** [comment]
As far as I can tell, the precompiled css has the proper vendor prefixing, but if you are compiling your own CSS you'll need to use an autoprefixer as described here: https://v2.designsystem.digital.gov/documentation/developers/#sass-compilation-requirements

**Comment by blacktm** [comment]
I forked the uswds-rails gem and updated for 2.0.0 Beta 4: https://github.com/blacktm/uswds-rails/tree/update-2.0.0-beta-4
So it's compiling the Sass. Ah, ok, missed that. We're trying to incorporate USWDS into a Rails application. Dropping in a gem makes it super simple for everyone on Rails, but must be missing that autoprefixing step. I'll do some research, see if I can find a solution.

**Comment by blacktm** [comment]
I found the [`autoprefixer-rails` gem ](https://github.com/ai/autoprefixer-rails), fixed it right up. Thanks.
