### ISSUE TITLE
USWDS 2.0.0-beta.4 does not create state utility classes.

### ISSUE THREAD

**Issue by adunkman** [uswds/uswds#2894]
## Description

As described [in the v2 documentation](https://v2.designsystem.digital.gov/design-tokens/color/state-tokens/), state-based utility classes (like `.bg-success`) should be output in the built CSS. That doesn’t seem to be true, though I’d like it to be! 

I may be missing a boolean toggle to enable these classes, but I can’t seem to figure out what that might be, if so!

## Steps to reproduce the issue

1. `npm init` in an empty directory.
2. Follow the [uswds-gulp](https://github.com/uswds/uswds-gulp) setup guide, but install `uswds@^2.0.0-beta.4` instead of the requested `uswds@^2.0.0-beta`.
3. After updating the gulpfile with output paths, run `gulp init` as described in the setup guide.
4. Search the built CSS file for `.bg-success`, observe it is missing.

## Additional information

~The issue can be seen on the Color page of the in-progress login.gov design system, which is based on USWDS 2.0.0-beta.4 (the green swatches are colorless due to the missing classes):~  (Implemented a temporary work-around, but keeping the below screenshot)

![Screenshot of the Color page of the login.gov Design System](https://user-images.githubusercontent.com/14930/50776408-efc2dc80-1266-11e9-92d7-50ff0e438260.png)

**Comment by thisisdano** [comment]
Thanks for opening this issue!

I will check, but  I _think_ the state colors are disabled intentionally in the default set of utilities (see https://v2.designsystem.digital.gov/utilities/color/), but it might make sense to include them. If we continue _not_ to include them by default, it should be as clear as possible in the docs how to activate them, as it's a pretty common use case.

To activate them, see the `Custom values` section of the color utility page's `Advanced settings` section (https://v2.designsystem.digital.gov/utilities/color/#advanced-settings). You'll need to add the state color palette in `_project-utilities-settings.scss`. _Yes, I see that this is maybe a bit too buried in the docs, and perhaps a simpler bool could be added for this common action..._

**To add the state colors to all color-related utilities,** change the value of the `$global-color-palettes` map to the following:
```
$global-color-palettes: (
  'palette-color-default',
  'palette-color-state'
);
``` 

**To add the state colors to a specific utility,** change the value of the `$[utility]-palettes` map to the following:
```
$[utility]-palettes: (
  'palette-color-state'
);

// for example...

$background-color-palettes: (
  'palette-color-state'
);

```

**Comment by adunkman** [comment]
Ahh, got it! Yep, was able to enable them in https://github.com/18F/identity-style-guide/pull/58: 

```diff
@@ -55,7 +55,8 @@ The following palettes will be added to
*/

$global-color-palettes: (
-  'palette-color-default'
+  'palette-color-default',
+  'palette-color-state'
);

/*
```

Thanks for pointing it out!

**Comment by thisisdano** [comment]
Nice!
