### ISSUE TITLE
Change to print styling

### ISSUE THREAD

**Issue by saracope** [uswds/uswds#2907]
## Description

**Issue**: It is not clear to users that the USWDS does not "handle" print styling. 
**Result**: Users do not add a print stylesheet. Consequently, when the print version of their site looks wonky they equate this to a bug in the design system.
**Consider**: 
1.) Omitting the media type for the condensed style sheet or setting it to 'all'. 
2.) Documenting the descision here and a (possible) recommendation for users to create their own print stylesheets as needed.
**Reasoning**: This would at least allow the site to use any already defined styles it has for a better experience.

TODO
**Investigate**: Any side effects to making this change in the design system, especially with accessibility.

**Comment by thisisdano** [comment]
Fixed in #2910

**Comment by mgifford** [comment]
So is print styling no longer recommended as a best practice by the USWDS?  I looked at all the A-F websites that are using it and surprisingly few had print CSS definitions. Some of the best are:

- https://clinicaltrials.gov/ct2/html/css/print.css?v=43
- https://betobaccofree.hhs.gov/sites/default/files/css/css_z98YhE0GkqAFpYUw9F-u1Zfsq3DJ73sZ6ol42VtOvYE.css
- https://www.ars.usda.gov/css/print.css
- https://18f.gsa.gov/assets/css/print.css
- https://feedback.usa.gov/assets/css/print.css

Some are doing it inline like:

- https://www.fcsic.gov/

There really aren't many USWDS sites that are using print CSS. I don't think a change in documentation is going to do much.

**Comment by arkjoseph** [comment]
@mgifford @saracope - flex box/uswds is not printer friendly and really is not up to par with what most clients expect in regards to printer output.
Ive resolved this on gsa.gov by forcing columns to render using specific widths in % values, in addition ive also replicated what bootstrap does and change the display of grid-row to display:table.  ive also created classes to address 'printer-only' out put or screen only output within markup, not css.
