### ISSUE TITLE
Review examples files

### ISSUE THREAD

**Issue by saracope** [uswds/uswds#2914]
Do we need them? Can they be updated or deleted?

**Comment by saracope** [comment]
Current [examples](https://github.com/uswds/uswds/tree/develop/examples): 
- Compiling CSS with node-sass
- Bundling JavaScript with browserify and webpack
- Automating CSS and JS generation with the Grunt and Gulp task runners

**Comment by mbucknell** [comment]
I think they are very useful for those of us who are building the assets be compiling or bunding uswds into our bundles . However they do need to be updated.

**Comment by Aayush-Joshi23** [comment]
That is important and you don't have to delete that, although it needs an update.

**Comment by thisisdano** [comment]
I think there's utility in these, but they're buried and not featured on the guidance site. Let's move to update these and get them onto some getting started guides.
