### ISSUE TITLE
Modifier classes are ambiguous

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2915]
In USWDS 2.0 we've started using an additive technique for styling variants of base components. For example, if you want a button with the secondary color as its background:

**1.x:** `.usa-button-secondary`
**2.0:** `.usa-button.usa-button-secondary`

We feel good that this is a positive change that makes style composition clearer, more modular, and more reliable. For instance, there's now no need to remember if `secondary` or `outline` comes first in a single-class button that has a secondary color as its outline — you'd use `usa-button usa-button-outline usa.button-secondary` in whatever order.

What's ambiguous is when a particular class is a modifier variant or a base class itself. When do you need to add the base class and a variant and when do you need just a single class?

I propose that variant modifier classes should be separated by a double hyphen (`--`) as in `.usa-button--secondary` or `.usa-accordion--borderless`. This would bring our modified BEM convention a bit closer to standard BEM and make it very clear just how the element should be classed to achieve the desired effect.

The double hyphen is relatively simple to type, is consistent with an existing convention, and provides an important distinction. Is this something we should do for USWDS 2.0 to accompany our switch to modular classing? Would this help developers better understand the necessary classes?

**Comment by thisisdano** [comment]
@maya @hursey013 @uswds/core Do you have any opinions about this?

**Comment by stphnwlkr** [comment]
FWIW, I agree that this was the right way to go. I like your approach to differentiating the base and modifiers.

**Comment by maya** [comment]
If we are going to go so close to BEM, then why not just go fully?

**Comment by thisisdano** [comment]
Mostly because I don't like underscores :)
And, personally, I don't think the distinction between block and element is important enough to warrant the special treatment.

**Comment by stphnwlkr** [comment]
I would add that since you are now setting the standard for the future of government websites (by law), it might make sense to adopt BEM fully. It sets the expected baseline for usage, contributions, and may improve adoption.

**Comment by thisisdano** [comment]
I'm game to consider BEM though I do currently consider it overkill. It'll take a little longer to fully rewrite everything in BEM and I'm not sure if it sets some expectation that our codebase may not always deliver! But the upside could be just as you say.

**Comment by thisisdano** [comment]
OK. BEM it is.

**Comment by thisisdano** [comment]
BEM implementation here: https://github.com/uswds/uswds/pull/2904

**Comment by maya** [comment]
Was this resolved in #2904 or is there more work to do?

**Comment by maya** [comment]
Closed in #2904.
