### ISSUE TITLE
Links line height too small on Footer Big

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2938]
[What I see](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/footer--big.html):
<img width="1084" alt="Screen Shot 2019-03-11 at 11 29 19 AM" src="https://user-images.githubusercontent.com/5249443/54148357-4bd5e880-43f1-11e9-86c1-43775f4e8ff7.png">

[What I expect](https://components.designsystem.digital.gov/components/preview/footer--big.html):
<img width="1110" alt="Screen Shot 2019-03-11 at 11 29 38 AM" src="https://user-images.githubusercontent.com/5249443/54148360-4d9fac00-43f1-11e9-993b-3cc5a2fd70a2.png">

**Comment by thisisdano** [comment]
I'm going to look at this one now

**Comment by maya** [comment]
I checked and I think the 0.5rem left margin on those links may have been meant to bottom or top? As it messes up the alignment now:

<img width="433" alt="Screen Shot 2019-03-11 at 3 14 14 PM" src="https://user-images.githubusercontent.com/5249443/54161828-b21e3380-4410-11e9-802a-0a92eafb7aad.png">

**Comment by thisisdano** [comment]
Removed that left margin

**Comment by maya** [comment]
Closed in #2941.
