### ISSUE TITLE
Side navigation horizontal lines not appearing

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2939]
I noticed the side navigation has only one light gray line at the bottom, but when you updated it, it had lines dividing each item. Was this change intentional or a bug?

[What I see](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/detail/sidenav--compare.html):
<img width="1011" alt="Screen Shot 2019-03-11 at 12 50 54 PM" src="https://user-images.githubusercontent.com/5249443/54153289-77aa9b80-43fc-11e9-8a17-06226fa20bba.png">

What I expect to see via #2750:
![](https://user-images.githubusercontent.com/11464021/45716311-68cce580-bb4b-11e8-9eeb-a90a6ccea5d4.png)

**Comment by thisisdano** [comment]
OK, looking at this now

**Comment by maya** [comment]
Fixed in #2942.
