### ISSUE TITLE
Beta 6 - System Fonts

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2944]
A beta 6 anomaly - If you use just system fonts a stray comma is placed at the front and causes the system fonts not to work

[class*='font-sans-'] {
  font-family: , -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol !important;
}

**Comment by stphnwlkr** [comment]
Turns out there is more to this than just the comma... doing some more research.

**Comment by thisisdano** [comment]
Aw crap — I think I know what this is...
I'm sure I can fix the comma, but does it still fail if the comma goes away?

**Comment by stphnwlkr** [comment]
Yes it is still a problem...see  https://stphnwlkr.dev/

**Comment by thisisdano** [comment]
Hm. OK. This issue is next on my list.

**Comment by stphnwlkr** [comment]
It is the comma...there were 47 instances and I missed a couple of key ones

**Comment by maya** [comment]
Fixed in #2947. @stphnwlkr let us know if there are any other issues!
