### ISSUE TITLE
Beta 6 - Search icon missing

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2945]
In _search.scss (starting at line 27)

@include at-media('mobile-lg') {
      @include u-padding-x(2);
      background-image: none;
      width: auto;
    }
is removing the search icon

**Comment by maya** [comment]
It seems to be working fine here: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/detail/search--default.html

**Comment by stphnwlkr** [comment]
Strange, I removed "background-image: none;" and it fixed the problem. Otherwise it was missing in desktop and mobile.

**Comment by stphnwlkr** [comment]
My mistake...I was seeing two hyphens in usa-search--small but there was only one.
