### ISSUE TITLE
Alerts with the --no-icon variant should have normal left padding

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2948]
Currently, if a `usa-alert` has the `usa-alert--no-icon` variant, the icon disappears, but it leaves a big open space on the left side. 

<img width="551" alt="Screen Shot 2019-03-12 at 9 43 28 AM" src="https://user-images.githubusercontent.com/11464021/54218825-83a16680-44ab-11e9-8885-4dfe2ff8fa8f.png">
<img width="551" alt="Screen Shot 2019-03-12 at 9 42 59 AM" src="https://user-images.githubusercontent.com/11464021/54218830-8734ed80-44ab-11e9-980b-86c7fc58a812.png">

If an alert has `usa-alert--no-icon`, then it should have the same spacing between the bar on the left and the text as it has between the text and the right edge of the alert.

**Comment by maya** [comment]
If you use `usa-alert` without anything else, you get the proper spacing:
<img width="1080" alt="Screen Shot 2019-03-12 at 12 15 39 PM" src="https://user-images.githubusercontent.com/5249443/54229013-a12cfb00-44c0-11e9-9593-7ca9e2f3db41.png">

**Comment by thisisdano** [comment]
Should we update the others to match since `usa-alert--no-icon` does have an effect on them, just not the expected effect.

Or, should we make it so `--no-icon` has no effect on the named alerts?

**Comment by maya** [comment]
Probably makes sense to give `usa-alert--no-icon` the same spacing as `usa-alert`.

**Comment by thisisdano** [comment]
Fixed in #2959
