### ISSUE TITLE
Consider using variable fonts

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2953]
Would simplify our font asset distribution to have all font weights in a single file (or at least fewer files). 

- [Mozilla's variable font guide](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide)
- [Source Sans Pro variable fonts](https://github.com/adobe-fonts/source-sans-pro/tree/release/VAR)
- Merriweather is working on them

I don't have enough background on if this would be a wise move (e.g. browser support, etc). @thisisdano have you done any thinking around this?

**Comment by thisisdano** [comment]
I think browser support isn't there yet, but I would _love_ to start using these. I'll get refreshed on the current state of support tho. Public Sans could also support this without much work.

**Comment by maya** [comment]
Support is there for everything except for IE11 which is the oldest browser we support. Though if they would get an acceptable fallback, I don't think that would be too bad. https://caniuse.com/#search=variable%20fonts

**Comment by davelab6** [comment]
I'm currently the Google Fonts product manager, and thought I'd chip in that while [caniuse.com](https://caniuse.com/#feat=variable-fonts) shows about 80% browser support, the 20% is pretty stubborn old browser installs that just have to die off, and those users are getting used to a more and more degraded web experience.

I've subscribed to this issue, and feel free to ping me on any channel if you have questions about variable fonts.

**Comment by stphnwlkr** [comment]
@davelab6 as great as that would be, the federal government still likes Internet Explorer as the default in many large organizations even when newer browsers are available (VA 400k users). It is not the end-user’s choice.

**Comment by thisisdano** [comment]
Blocked by IE11, closing for now. Maybe later this year! I've labelled this with an `IE11` label so we can revisit these issues when we drop IE11 support.
