### ISSUE TITLE
Note Supported Versions of Node

### ISSUE THREAD

**Issue by joekarasek** [uswds/uswds#2954]
# Supported Versions of Node

Add documentation for which versions of Node are supported (looks like its up to 8, nothing later). 

## Description

First time attempting to contribute and I had a trouble with `npm install`. I was using node v10. Bumping down to node v8 resolved the issue.

## Steps to reproduce the issue

1. Setup your local environment to be using node v10 or later.
2. Run `npm install` 

## Additional information [optional]

Optionally add a `.nvm` file so that developer who use `nvm` to manage multiple versions of node will get a prompt to change versions.

**Comment by joekarasek** [comment]
Oops, accidentally hit close.

**Comment by thisisdano** [comment]
Starting with USWDS 2.0 we will be using a `.nvmrc` file supporting the current LTS version of Node (10.15.1): https://github.com/uswds/uswds/blob/release-2.0/.nvmrc

**Comment by maya** [comment]
I agree that we should probably have documentation on the what Node version to use as well as `nvm`. Glad you got it working eventually.

**Comment by maya** [comment]
@joekarasek If you're interested in contributing to version 2.0, which is where all our latest work is, use the [release-2.0](https://github.com/uswds/uswds/tree/release-2.0) branch.

**Comment by saracope** [comment]
I put together a Docker image for testing, but it could also help solve this problem. If that seems interesting, I can run it by the devops group to get more eyes on and publish it to the repo.

**Comment by maya** [comment]
I know @toolness also did something similar here: https://github.com/toolness/docker-uswds

**Comment by toolness** [comment]
Hi @maya!  Let me know if you have any questions about that docker-uswds thing, happy to answer anything you need.

**Comment by saracope** [comment]
OH, that looks real nice!
