### ISSUE TITLE
Update unstyled lists and buttons to BEM

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2956]
Instead of our standalone unstyled class for buttons and lists, we should be consistent with our new BEM style and use modifiers:

| old | new
| --- | ---
| `usa-button-unstyled` | `.usa-button.usa-button--unstyled`
| `usa-unstyled-list` | `.usa-list.usa-list--unstyled`

**Comment by maya** [comment]
Done in #2974.
