### ISSUE TITLE
Use `ex` unit for measure values

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2960]
I'm finding that the `ch` unit is a poor unit for doing our measure calculation, since the `0` character on which it's based has significant variance from font to font. Since we're already normalizing our font size in such a way that fonts display with a similar x-height at each grade in our font-size system, we should use the `ex` unit for a more consistent and reliable output. The `ex` unit has universal support.

**This is also distorting our measure output tokens in the direction of being generally too wide** — far outside the 50-75 target character count in our guidance. That said, the guidance is maybe a little bit skewed narrow, as a popular readable site like medium.com has a line length of around 75-78 characters, and we could a bit longer than that for something like a small caption.

I'm also proposing that we add an additional token to accommodate some of gamut we'll lose by concentrating our coverage on the guidance range.

| token | desired output | proposed value | current value | current output in Public Sans 
| --- | --- | --- | --- | ---
| `1` | ~50 characters | `44ex` | `40ch` | 51 characters
| `2` | ~66 characters | `60ex` | `60ch` | 80 characters
| `3` | ~72 characters | `64ex` | `66ch` | 88 characters
| `4` | ~78 characters | `68ex` | `72ch` | 95 characters
| `5` | ~86 characters | `74ex` | `77ch` | 100 characters
| `6` | ~96 characters | `88ex` | — | —

| Beta 6 | Beta 7
| --- | ---
| '1' | '1'
| '2' | '4'
| '3' | '5'
| '4' | '6'
| '5' | '6'

**Comment by maya** [comment]
Done in #2964.
