### ISSUE TITLE
Tighten letterspacing of `letterspacing-1`

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2962]
`Letterspacing 1` is the appropriate token for setting the letterspacing for very small text. But 0.05em is a bit too loose for that purpose. I suggest using 0.025em.

**no letterspacing**
<img width="418" alt="Screen Shot 2019-03-17 at 2 08 45 PM" src="https://user-images.githubusercontent.com/11464021/54497965-42032800-48be-11e9-9006-24367303daa6.png">

**0.025em letterspacing**
<img width="420" alt="Screen Shot 2019-03-17 at 2 11 19 PM" src="https://user-images.githubusercontent.com/11464021/54498001-960e0c80-48be-11e9-9fdb-18e1bb09c3bb.png">

**0.05em letterspacing**
<img width="407" alt="Screen Shot 2019-03-17 at 2 08 32 PM" src="https://user-images.githubusercontent.com/11464021/54497971-4af3f980-48be-11e9-8df4-9e56d5723cfd.png">

**Comment by maya** [comment]
Fixed in #2965.
