### ISSUE TITLE
 BEM classes are not styled in the "_inputs.scss" sass file

### ISSUE THREAD

**Issue by iris-i** [uswds/uswds#2971]
## Description

The code for form elements in the design system https://v2.designsystem.digital.gov/components/form-controls/ shows classes for checkboxes using the BEM naming system. However, the stylesheet in github still shows the classes with single hyphens. 

Eg. The design system uses the following classes `usa-checkbox__input` and `.usa-checkbox__label`,
But in _inputs.scss (https://github.com/uswds/uswds/blob/release-2.0.0-beta.6/src/stylesheets/elements/_inputs.scss) I still see the following classes: 
`..usa-checkbox-input` and `.usa-checkbox-label`

**Comment by thisisdano** [comment]
@iris-i Thanks for pointing this out! I think this is a mistake we've already fixed and will update in the next release. Check out the new `_inputs.scss` here: https://github.com/uswds/uswds/blob/release-2.0/src/stylesheets/elements/_inputs.scss

Does that look better?

**Comment by iris-i** [comment]
Awesome. Yep that does look better. Thank you!

**Comment by maya** [comment]
Going to close this as it was fixed in #2952, but thank you for checking!
