### ISSUE TITLE
usa-alert__paragraph should be a variant

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2975]
- It should be renamed as a variant and not a subcomponent
- it should use `max-width` instead of `width`

<img width="354" alt="Screen Shot 2019-03-20 at 10 52 37 AM" src="https://user-images.githubusercontent.com/11464021/54707551-9a286d00-4afe-11e9-9cf9-8bd9f4b66905.png">

**Comment by maya** [comment]
Is the paragraph alert even imlpemented correctly? In the Sketch file, it uses a full width container with a max-width only applied to the paragraph text within in.

<img width="804" alt="Screen Shot 2019-03-20 at 11 04 23 AM" src="https://user-images.githubusercontent.com/5249443/54708161-fb9d0b80-4aff-11e9-8592-ae49f71cfc2a.png">

**Comment by thisisdano** [comment]
Hm. If that's the intended output, an alert variant doesn't even make sense. You could just use a utility to control measure if desired.

**Comment by maya** [comment]
Removed in #2990.
