### ISSUE TITLE
Remove custom padding from the outside of component previews

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2978]
This results in too much padding when the component is imported into our website:

![Screen Shot 2019-03-20 at 1.26.15 PM.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/0ecc50ac-4657-4fd5-ba36-806f0d1ce726)

**Comment by maya** [comment]
Seeing much less padding now, so think this can be closed. 
<img width="1007" alt="Screen Shot 2019-03-22 at 1 38 23 PM" src="https://user-images.githubusercontent.com/5249443/54851637-d64b0180-4ca7-11e9-9d87-10850bd766aa.png">
