### ISSUE TITLE
margin-right not cleared on second element of 1/2 width and third element of 1/3 width

### ISSUE THREAD

**Issue by rwaery** [uswds/uswds#2982]
## margin-right not set to zero on 2nd element of 1/2 width and 3rd of 1/3 width

_grid.scss seems to be missing style for the grid class `usa-one-width-half` and `usa-one-width-third`. I'm comparing them against `usa-width-one-fourth` and `usa-width-one-sixth` which have margin-right set to 0 for the fourth element and sixth element respectively on `$large` breakpoint.

**Comment by maya** [comment]
Hi @rwaery, I'm not able to reproduce this. When I visit the [grids page](https://designsystem.digital.gov/components/grids/), I see no right margins on the last `usa-one-width-half`. Same for `usa-one-width-third`. Screenshot below. 

<img width="1259" alt="Screen Shot 2019-03-21 at 10 29 52 AM" src="https://user-images.githubusercontent.com/5249443/54837880-acccae80-4c84-11e9-91a9-44690722b2cf.png">
 
Are the grid row items inside a `usa-grid`? Are you able to provide more info (e.g. screenshot, code)?
