### ISSUE TITLE
Drop EOT font files from CSS

### ISSUE THREAD

**Issue by miguelsousa** [uswds/uswds#2987]
* EOT fonts are only necessary for IE8 and earlier
* [IE 11 is the oldest browser USWDS supports](https://github.com/uswds/uswds/issues/2953#issuecomment-472212524)
* [IE11 and all current major browsers support WOFF](https://caniuse.com/#search=woff)

**Comment by thisisdano** [comment]
Makes sense. Working on it here: https://github.com/uswds/uswds/pull/2989

**Comment by maya** [comment]
Fixed in #2989.
