### ISSUE TITLE
Validation component alignment design

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2993]
Should we be following the alignment in the Sketch file?
- Smaller "(i)" icon
- Left aligned checkmarks 
- Potentially slightly larger checkmark icons

## Sketch file
<img width="446" alt="Screen Shot 2019-03-25 at 11 15 58 AM" src="https://user-images.githubusercontent.com/5249443/54943843-675fe980-4eef-11e9-8605-8a76dffa6c69.png">

## Current component
<img width="344" alt="Screen Shot 2019-03-25 at 11 12 19 AM" src="https://user-images.githubusercontent.com/5249443/54943731-29fb5c00-4eef-11e9-8e15-3ef421527bb7.png">

**Comment by thisisdano** [comment]
This one could definitely use some love.

**Comment by maya** [comment]
Done in #2994.
