### ISSUE TITLE
Accordion and header dropdown hover state is underlined

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2995]
...and it should not be.

## [Accordion](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/detail/accordion--default.html)
<img width="409" alt="Screen Shot 2019-03-25 at 1 34 58 PM" src="https://user-images.githubusercontent.com/5249443/54952286-e0b50780-4f02-11e9-8d3a-9a2e88f37837.png">

## This also finds its way to the [header](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/header--basic.html)
<img width="168" alt="Screen Shot 2019-03-25 at 1 34 09 PM" src="https://user-images.githubusercontent.com/5249443/54952285-e0b50780-4f02-11e9-9c1e-9297425ac234.png">

**Comment by maya** [comment]
@thisisdano can you confirm whether this is the intended state?

**Comment by thisisdano** [comment]
No, it's a effect of styling `.usa-button--unstyled` as a link. We can force these back into their previous styling.

**Comment by maya** [comment]
Fixed in #2996.
