### ISSUE TITLE
Accordion and its content have a gap in certain settings

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2998]
If `$theme-global-content-styles` is set to `true`, the heading sibling styling will add a gap between the accordion heading and its content

<img width="892" alt="Screen Shot 2019-03-25 at 3 08 17 PM" src="https://user-images.githubusercontent.com/11464021/54957446-0563ac00-4f10-11e9-8e0b-a35b3e8cfea1.png">

**Comment by maya** [comment]
Fixed in #3000.
