### ISSUE TITLE
Menu flashes dropdowns when changing pages

### ISSUE THREAD

**Issue by donpwinston** [uswds/uswds#3015]
## Menu flashes dropdowns when changing pages

I'm using your header component that supports hierarchical menus. When changing pages or refreshing, the menus that contain menu items briefly display the dropdown items. Is it possible to fix this?

I'm using version 1.0.0. I upgraded to version 1.6 but the "problem" remains.

**Comment by maya** [comment]
Thanks for opening this issue. We'll need to investigate this to see what kind of fix would make sense.

Some advice from a colleague:
>Try putting a single line of JS in the head that sets a class on `html`then key the CSS to hide it on that class. The idea being to find out if JS is present as quickly as possible before the menu is drawn, so you know before it's drawn if you can hide it. I'm just not sure if you can put a class on `html` before it's closed.

**Comment by maya** [comment]
@donpwinston though it's not a pattern I'm sure we'll recommend for everyone, one way to fix this is to move your USWDS JS script to your `<head>` so it loads first.

**Comment by maya** [comment]
From another colleague:
>yes, I think we’re in the right camp right now — i’d rather have a flash of content and the content rendered sooner, even if it’s ugly. I think the decision to delay rendering should be made by USWDS consumers by overriding the default.
