### ISSUE TITLE
Issue setting the $theme-link-color in uswds settings

### ISSUE THREAD

**Issue by jeremyzilar** [uswds/uswds#3032]
When setting the default link color on a site, these variables don't seem to be working in the `_uswds-theme-color.scss` settings file:

```
// Links
$theme-link-color:             'green-cool-30v';
$theme-link-visited-color:     'violet-70v';
```

I have tested this across two sites:
- https://workflow.digital.gov/
- https://demo.digital.gov/

On both projects, the `$theme-link-color:` in `_uswds-theme-color.scss` seems to not register.

Here are the files, where I have set the `$theme-link-color` is to some loud, obnoxious color. After building the page, this is not showing up in the web inspector as being set in the CSS.
- workflow | https://github.com/GSA/digitalgov-workflow/blob/master/assets/sass/_uswds-theme-color.scss
- demo | https://github.com/GSA/digitalgov.gov/blob/demo/themes/digital.gov/src/uswds/_uswds-theme-color.scss

**Comment by jeremyzilar** [comment]
My bad.

I didn't know there was a 🏴flag that needed to be set in `_uswds-theme-typography.scss`

```
$theme-global-paragraph-styles: false;
$theme-global-link-styles:      true;
$theme-global-content-styles:   false;
```
All working now!

Would be nice to mention this in the comments in `_uswds-theme-color.scss` since the two settings are interrelated.

**Comment by thisisdano** [comment]
Ah wonderful! I'm glad you got it resolved. Better settings docs is a short-term goal for us.

**Comment by maya** [comment]
Sounds like this can be closed.

**Comment by JayDarnell** [comment]
I'm really struggling to figure out how to update $theme-link-color to a hex value in my **@use "uswds-core" with** declaration. I was able to update $theme-color-base-ink directly in this manner but cannot update $theme-link-color.

```
Error: "Only use quoted color tokens in USWDS functions and mixins. See designsystem.digital.gov/design-tokens/color for more information."

46 │   $value: general.smart-quote($value);
```
