### ISSUE TITLE
Submenu items are not keyboard accessible on Firefox

### ISSUE THREAD

**Issue by jacksonStone** [uswds/uswds#3035]
## Description
It seems the submenu items in the headings examples are not keyboard accessible in Firefox.

Chrome they work great. I can tab through them as expected, but not Firefox. May very well be an issue with the firefox browser itself, but thought it would be worth posting here if there was anything that could be done.

I can open and close the menu, but I cannot seem to navigate to the options shown with a keyboard

## Steps to reproduce the issue

1. Visit https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/header--basic.html

2. Tab over to the first menu item and press enter, and try with the keyboard to tab through the sub links that render.

## Additional information [optional]

* Great work guys and galls. Really cool design system.

**Comment by maya** [comment]
This works fine for me. Could be something in your machine's settings, Firefox settings, or how you're navigating:

<img width="1207" alt="Screen Shot 2019-04-13 at 6 18 42 PM" src="https://user-images.githubusercontent.com/5249443/56087076-c93db000-5e18-11e9-8535-ff3821b61635.png">
