### ISSUE TITLE
Components should use role-based font tokens only

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3042]
If a user decides not to use a certain font type in their project (like `serif`), font functions that use the `false` font-type token will fail. We should rewrite all component font functions to use role-based tokens instead:

```
  caption {
    @include u-font('serif', 'xs');
    font-weight: $theme-font-weight-bold;
    margin-bottom: units(1.5);
    text-align: left;
  }
```

should be something like:

```
  caption {
    @include u-font('body', 'xs');
    font-weight: $theme-font-weight-bold;
    margin-bottom: units(1.5);
    text-align: left;
  }
```

**Comment by vastphnwlkr** [comment]
How much work would it be to add caption, figcaption, blockquote, cite and any other "specialty" text elements to the typography settings? Set the default to body, but give us the option to easily change. Just a thought.

**Comment by thisisdano** [comment]
Yeah — I'd been sketching up just that kind of functionality.
