### ISSUE TITLE
[Footer] Add required links for government sites

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3043]
Add [required web content and links](https://www.digitalgov.gov/resources/required-web-content-and-links/) to footer components (as required by OMB).

See #998 for add'l discussion.

**Comment by maya** [comment]
# A few ideas
## An inline list
<img width="972" alt="Screen Shot 2019-04-17 at 6 12 33 PM" src="https://user-images.githubusercontent.com/5249443/56330342-788dc600-613c-11e9-880b-4a7cfdf5e3c4.png">

### Inline list on Clinical Trials prototype
<img width="1227" alt="Screen Shot 2019-04-17 at 6 09 13 PM" src="https://user-images.githubusercontent.com/5249443/56330357-8b07ff80-613c-11e9-9960-0a77c77655bd.png">

## Vertical list
<img width="1243" alt="Screen Shot 2019-04-17 at 6 17 18 PM" src="https://user-images.githubusercontent.com/5249443/56330502-1f726200-613d-11e9-96d1-1c9573e8929e.png">

## Vertical list on FOIA.gov
<img width="1182" alt="Screen Shot 2019-04-17 at 6 11 20 PM" src="https://user-images.githubusercontent.com/5249443/56330368-9c510c00-613c-11e9-864c-6d24aec0d794.png">

**Comment by thisisdano** [comment]
Added as part of the identifier component
