### ISSUE TITLE
Let the separating character between state variant prefixes and utility names be configurable

### ISSUE THREAD

**Issue by robertromore** [uswds/uswds#3045]
Other CSS frameworks that use colons to separate state variant prefixes from utility names (such as Tailwind CSS) allow the configuration of the separating character(s). This is helpful when using these CSS frameworks with other systems that don't support special characters in class names, such as Pug. 

I myself am seeing an issue when using USWDS with Drupal, and I've opened a related issue here: https://www.drupal.org/project/drupal/issues/3050007.

Further reference for Tailwind CSS can be found here: https://tailwindcss.com/docs/configuration/#separator.

**Comment by thisisdano** [comment]
Oh that's interesting. This should be possible and something we can consider.

**Comment by thisisdano** [comment]
Done in #4085
