### ISSUE TITLE
MIME type ('text/html') is not a supported stylesheet MIME type

### ISSUE THREAD

**Issue by lukasz-formela** [uswds/uswds#3051]
Just a quick question. 
Am I doing something wrong in quickly prototyping a webpage with usage of USWDS? 

`<link rel="stylesheet" type="text/css" href="./node_modules/uswds/dist/css/swds.min.css">`
That's how I tried to use it in my html file. 
The full error from the console :
`Refused to apply style from 'http://127.0.0.1:5500/node_modules/uswds/dist/css/swds.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

I am using VSCode studio with live server.

**Comment by stphnwlkr** [comment]
You have a typo. It is missing a "u" in the file name so attempting to render 404.  Should be "./node_modules/uswds/dist/css/uswds.min.css"

**Comment by dotmike** [comment]
@lukasz-formela - the recommended way of importing node modules references is in the JS file. I think you’ll be better off downloading the built code instead of the node modules if you want to refer it in your HTML page
