### ISSUE TITLE
Primary menu of extended header demo breaks in tablet mode

### ISSUE THREAD

**Issue by benwarfield-usds** [uswds/uswds#3065]
## Description

When the [extended header demo page](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/header--extended.html) is opened with a narrow window, or an an iPhone, clicking on the "Simple Link" entry causes an error in the console, and causes the dismiss button for the menu to stop working.

## Steps to reproduce the issue

1. open [the demo page](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/header--extended.html). If in a non-mobile browser, resize until the mobile navigation menu appears, then reload.
2. click the "simple link" item (third in the menu)
3. click the menu-close button in the top right

Expected: the menu closes
Actual: the menu does not close until/unless you hit Escape (if you are in fact not on mobile).

## Additional information
When the Simple Link entry is clicked, the error is:
```
Uncaught Error: No toggle target found with id: "null"
    at e.exports (toggle.js:17)
    at HTMLAnchorElement.<anonymous> (navigation.js:88)
    at HTMLBodyElement.<anonymous> (index.js:8)
    at HTMLBodyElement.<anonymous> (index.js:4)
    at Array.some (<anonymous>)
    at HTMLBodyElement.<anonymous>
```
When the dismissal button is subsequently pressed, the message is
```
toggle.js:17 Uncaught Error: No toggle target found with id: "null"
    at e.exports (toggle.js:17)
    at j (navigation.js:70)
    at HTMLBodyElement.<anonymous> (navigation.js:96)
    at HTMLBodyElement.<anonymous> (index.js:8)
    at HTMLBodyElement.<anonymous> (index.js:4)
    at Array.some (<anonymous>)
    at HTMLBodyElement.<anonymous> (index.js:3)
```
Going back and clicking the link again produces yet a third stack trace, by way of lines 70 and 85 rather than 70 and 96.

**Comment by thisisdano** [comment]
Oh rats! I wonder what happened here, as this is exactly the problem `2.0.3` was supposed to address. The extended header seems to work as expected on our internal components page (https://components.designsystem.digital.gov/components/preview/header--extended.html), so I wonder what's getting mangled when it appears in the demo.
