### ISSUE TITLE
Q: Is there a hardcoded limit of 3 items in non-megamenu?

### ISSUE THREAD

**Issue by w00fz** [uswds/uswds#3076]
## Question

Is there any reason why non-megamenu (basic-, extended-) menus have a hardcoded limit of 3 items ([source](https://github.com/uswds/uswds/blob/develop/src/components/08-navigation/_nav-primary.njk#L10)).

When looking at the [documentation](https://designsystem.digital.gov/components/header/#basic-mega-menu) under the **Shallow hierarchy** section it even states that:

> You may also use it if each main section listed in the horizontal navigation has six or fewer subsections that you’d like to include in a dropdown menu.

Suggesting that you might need 6 or less items but you would never be able to get to 6.

Is this a bug or is it intentional?

Why does a limit need to be forced at all? I think it's a good idea to recommend in the documentation an ideal amount of items but it is a bit odd to have a limit hardcoded in the template.

Thanks!

**Comment by thisisdano** [comment]
Let's remove this from our template. We don't intend that real projects limit themselves to three items, and we shouldn't imply this in the template. Let's check that we fixed this in our library migration

**Comment by amyleadem** [comment]
@mejiaj This issue no longer seems to apply to our navigation templates. Is it safe to close?

**Comment by brunerae** [comment]
@mejiaj / @thisisdano can this be closed?
