### ISSUE TITLE
node-css-mqpacker archived

### ISSUE THREAD

**Issue by galvarez421** [uswds/uswds#3079]
## Description

The documentation states that media query packing is a requirement when compiling the Sass. https://github.com/hail2u/node-css-mqpacker seems to be recommended tool for this. This package/repo is now archived, so is it still the recommended tool? If not, is there any other tool that you would recommend?

This is perhaps a tangential question, but: if I set [`$utilities-use-important`](https://github.com/uswds/uswds/blob/v2.0.3/src/stylesheets/settings/_settings-utilities.scss#L20) to `true`, is media query packing even necessary?

**Comment by thisisdano** [comment]
Removed in #3262
