### ISSUE TITLE
Fractal 8000A03EA error when running "npm start"

### ISSUE THREAD

**Issue by parmindersandhu-reisys** [uswds/uswds#3081]
when i cloned the repo and tried to run "npm start" i got a syntex error on the fractal.js file. does anyone know what is causing this issue?

**Comment by mejiaj** [comment]
@parmindersandhu-reisys, what version of node are you using? Were there any problems with `npm install`?

**Comment by thisisdano** [comment]
Cannot duplicate this error so closing
