### ISSUE TITLE
Incorrect alert icon alignment: USA alert success slim icon is not vertically aligned

### ISSUE THREAD

**Issue by nickscialli-usds** [uswds/uswds#3083]
## Description

When using the following alert class, the checkmark icon is not vertically aligned in the center: `usa-alert usa-alert--success usa-alert--slim`. This appears to be unique to the `success` case within the `slim` alert type.

## Steps to reproduce the issue

This issue can be reproduced simply by created a USA alert success slim component. 

```html
<div class="usa-alert usa-alert--success usa-alert--slim">
    <div class="usa-alert__body">
        <p class="usa-alert__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</p>
    </div>
</div>
```

This has been reproduced and can be viewed here at the following JS Fiddle link: https://jsfiddle.net/pcy8n2qg/1/. Note that other slim alerts are also presented and have correct icon alignment.

**Comment by thisisdano** [comment]
Sorry for the delay. This sent me down a bit of a rabbit hole looking at how we save and store SVG images, but I'm preparing a fix now.
