### ISSUE TITLE
Need simple how-to get started  - how do I resize the nav bar?

### ISSUE THREAD

**Issue by simsong** [uswds/uswds#3091]
## Description

We are using uswds for an internal website. We are not web developers. We have a navbar on the left and a navbar on top. For some of our pages we have a lot of horizontal data that we need to display. We just want to eliminate the navbar on the right and use the browser's left-right scroller.

Is there an easy way to to this?

The documentation for uswds is all super-long and assumes that the user is a modern designer who knows all about things like nodejs and lots of other open source tools. What would be useful would be a simple 'how to get started' document with simple templates and a description of 'change this value to have this impact.' 

If such a document exists, it would be useful to have a link to it.

**Comment by thisisdano** [comment]
I'm not if we can address the navbar issue, but I'm promoting this into the roadmap board so we can address the overall `How to get started` suggestions.

**Comment by simsong** [comment]
> I'm not if we can address the navbar issue, but I'm promoting this into the roadmap board so we can address the overall `How to get started` suggestions.

Thanks. To give you some more context, we are using the templates on a web server that uses Apache and server-side includes to include the style sheets. No nodejs. Static web pages. It's pretty simple. But it took my designer 2 weeks to figure out what was going on, and we still don't have a full handle on it.
