### ISSUE TITLE
Banner open on page load is distracting

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3092]
Like our accordions, the USWDS gov banner is opened and closed with javascript. The content in these components is accessible whether or not javascript loads because the components start open by default until the javascript loads to close them. 

As a result, even with a fast connection and performant JS, there is a brief moment (usually < 1s) when the banner is open on page load. Slower connections and larger JS files can make this open period more pronounced — staying open for seconds at a time. (For a good example, try loading https://digital.gov/ — especially on a slower connection.)

![banner-fouc](https://user-images.githubusercontent.com/11464021/64196664-350ccd80-ce39-11e9-8f33-6bf60f66d581.gif)

This can be very distracting. Site content that unexpectedly disappears is confusing to site users (_"huh? what was that? was that important?"_) as well as aesthetically uncomfortable, even if you know what to expect (_"i sure wish the content didn't jump all around every time I loaded the page!"_).

The gov banner is one of our most important and most-used components, appearing on every load of every USWDS page. While our general accessibility guidance is to make all site content accessible regardless of the presence of javascript, this is negatively affecting the experience of _all USWDS sites and pages_. 

We need a better solution here. Whatever the solution, it should result in
- no flashing text regardless of bandwidth conditions
- no flashing text regardless of the presence of javascript

There are likely a few ways to approach this issue! The first that cone to mind are:
- We could change our no-js policy for this component
- We could change our no-js policy for all components
- We could use render-blocking js for this component
- We could try to better use caching and preloading for js
- We could rewrite the component to remove the js

Related PRs: 
- https://github.com/uswds/uswds/pull/3075
- https://github.com/GSA/digitalgov.gov/pull/1258

- [x] JA - resolve [zendesk ticket](https://searchusa.zendesk.com/agent/tickets/20791)
- [ ] JA - reply to zenkdesk when complete

**Comment by eddietejeda** [comment]
Mentioned this on Slack, but posting publicly to get wider feedback:

> What about using <noscript>? You can hide/collapse by default with CSS and if <noscript> is triggered, CSS defaults to show/expand. You can preserve policy and not have to rewrite it all.

**Comment by maya** [comment]
Check out Filament Group's "Enhancing Optimistically" technique to style things up-front as they’ll look when JS enhances them + have a fallback when JS doesn't load: https://www.filamentgroup.com/lab/enhancing-optimistically.html

**Comment by thisisdano** [comment]
I've built out some work based on the Filament work that @maya linked above. 

Pull request: https://github.com/uswds/uswds-site/pull/947
[Demo](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-banner-flash-test/) → 

### What it is supposed to do
Essentially, what it does is build a `uswds-loader.js` is called in the `<head>` which asynchronously loads the uswds.js and provides a couple status/feature flag hooks on the `html` element:

`html.no-js` or just `html`: the default state
`html.usa-js-loading`: set by loading the `uswds-loader.js`
`html.usa-js-present`: set when the loader script returns script load

- **If js is blocked or not available:** No special flags are set, and components display as their no-js default.
- **When js is loading:** Add `usa-js-loading` flag pre-render, meaning we can offscreen closed accordion content
- **Once js is loaded:** Remove `usa-js-loading` and visibility is controlled by JS/CSS as usual. `usa-js-present` is largely redundant at the moment, but could provide a useful hook.
- **If js fails to load:** Remove `usa-js-loading` and components display as their no-js default.

### Importantly: Why doesn't the demo link work?
Well mostly because I don't know JavaScript. Basically, I don't know how to put a proper path to `uswds.js.min` from `uswds-loader.js`. The way I've written it, it always looks for the file _relative to the page loaded_ which means a link that works at one level of hierarchy (`path/to/page.html`) fails at a different level (`path/to/deeper/page.html`). I assume someone who knows what they're doing could work from this to build a production-ready solution. :)

### Also...
Noting that if js doesn't load on a mobile device, the whole nav is unusable. Which is no good. Perhaps it's time to reconsider the no-js requirement? Or be _way_ more cognizant of it...

**Comment by sarnikbixal** [comment]
I am going to try to add the onload event to the uwsds.js file instead of trying to attach the event to the script in the site.

**Comment by sarnikbixal** [comment]
@thisisdano if we don't want to introduce more logic into USWDS.js we can do something like this. We add a var on the USWDS main script like var USWDSLibrary = {}; Then we poll with a timeout for that variable - on load of script that variable will now be defined. So in the uswds-loader.js we just add the following:

`var poll = function () {
    setTimeout(function () {
      timeout--;
      if (typeof USWDSLibrary !== 'undefined') {
        // External file loaded
        clearTimeout(fallback);
        removeDefaultClass();
        setTimeout(switchToLoadedClass, 100);
      }
      else if (timeout > 0) {
        poll();
      }
      else {
        // External library failed to load
      }
    }, 100);
  };
  
  poll();`

**Comment by aduth** [comment]
I've found this flash of content quite noticeable as well. I spent some time exploring a few additional options:

- Based on https://github.com/uswds/uswds/issues/3092#issuecomment-533674613, a `noscript`-based approach: #3810
- A CSS-only accordion toggle: #3809

I'd consider these mostly as proofs of concepts, and as such I'm not especially attached to them. If anything, they could serve as points of reference to contrast https://github.com/uswds/uswds-site/pull/947 against.

**Comment by thisisdano** [comment]
Thanks @aduth — I'd love to take a look at these, and I'm particularly fond of a CSS-only solution like hidden checkbox.

**Comment by sarnikbixal** [comment]
@thisisdano - I have implemented a working test version of the polling logic. Please checkout the following branch and run locally to see it in action. 

dw-banner-flash-test

**Comment by aduth** [comment]
In a somewhat similar vein to previously-mentioned early script loading, another option might be to take advantage of the fact that the browser executes scripts synchronously, and optionally recommend to inject an inline script tag at the earliest opportunity to hide the banner in environments that support JavaScript.

```html
<div class="usa-banner__content usa-accordion__content" id="gov-banner">
  <script type="module">document.currentScript.parentNode.setAttribute('hidden', '');</script>
  <div class="grid-row grid-gap-lg">
```

A couple notes:

- Inline script tags like this can be a bit of a can of worms, especially when used in combination with a [content security policy](https://engineering.18f.gov/security/content-security-policy/).
- `document.currentScript` [isn't supported](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript#Browser_compatibility) in Internet Explorer, hence why the example uses [`type="module"`](https://caniuse.com/mdn-html_elements_script_type_module) to progressively enhance to exclude unsupported browsers.
