### ISSUE TITLE
Finishing the Vivid Color Palette

### ISSUE THREAD

**Issue by jlarmstrongiv** [uswds/uswds#3094]
## Description

I would like to use colors from the USWDS Vivid Palette.  However, the palette is incomplete.  The incomplete palette limits color choices to color families that have more colors defined.  Even then, it is difficult to make accessible designs without the darker color variations.

What is the process for adding colors to the design system?  How have colors been chosen previously?  What other considerations should be taken into account?

Finishing the Vivid Palette will complete an important part of the USWDS.  The regular palette is thorough and beautiful, I would love to see the Vivid Palette match it.

## Steps to reproduce the issue

Visit the [Vivid Color Wheel](https://designsystem.digital.gov/design-tokens/color/overview/).

## Additional information

![image](https://user-images.githubusercontent.com/20903247/64219882-4edbfe00-ce95-11e9-81e9-9333adc0046a.png)

**Comment by thisisdano** [comment]
I want to say that I agree that it would be useful to fill out the vivid palette from grades `5`-`80` across color families. This would make it easier to switch between color families, as it would mean removing the risk of missing vivid variants after switching. 

As we work through this issue, I will also publish our color system guidance on allowable luminance ranges for each grade. This should help us all be on the same page around what luminance a grade of, say, `70` needs to be — vivid or not.

<img width="961" alt="luminance-guidance-checker" src="https://user-images.githubusercontent.com/11464021/65624073-f96bac00-df7d-11e9-913a-705d7717e4b0.png">

**Comment by jlarmstrongiv** [comment]
Sounds good 👍 Could you explain/label the table a bit more?  I don’t quite understand it.  

Is the concept having a range of acceptable luminance values (0–1) for the different grades (0, 10, 20… 100) of the color groups (Indigo, Cyan…)?

**Comment by darekkay** [comment]
@thisisdano Doesn't https://github.com/uswds/uswds/pull/3351 close this issue as well?

**Comment by thisisdano** [comment]
@darekkay Yup! Thanks for the heads up. 
Fixed by #3351
