### ISSUE TITLE
Extra space below header nav dropdown

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3096]
There's extra space below each header nav dropdown. Seen on page templates:

## Basic header
<img width="173" alt="Screen Shot 2019-09-09 at 3 22 06 PM" src="https://user-images.githubusercontent.com/5249443/64570559-d3a39d80-d315-11e9-8aef-d16c637b2bd9.png">

## Extended header
<img width="181" alt="Screen Shot 2019-09-09 at 3 23 00 PM" src="https://user-images.githubusercontent.com/5249443/64570560-d3a39d80-d315-11e9-8911-55eeb30cd6e4.png">

**Comment by thisisdano** [comment]
👋 
You know, I was just making a note of this yesterday. I think they should have 1px of space between the highlight bar and the divider, but the items with a dropdown menu have 2px. This seems to come from the lack of explicit line-height on one of the parent elements and it's on my list of things to fix this week :)

**Comment by maya** [comment]
Whatever you go with, as long as it's consistent with the normal nav links, it should be fine. i.e. this is what they look like:
<img width="121" alt="Screen Shot 2019-09-09 at 4 09 09 PM" src="https://user-images.githubusercontent.com/5249443/64572467-50397a80-d31c-11e9-957b-f15562ab58b9.png">
