### ISSUE TITLE
In components: greater separation of DIVs that are responsible for grid layout from the DIVs that are responsible for style

### ISSUE THREAD

**Issue by jeremyzilar** [uswds/uswds#3099]
As a developer who uses the USWDS components on a number of different sites and as someone who teaches others how to use the Design System — I would like to advocate for the components being one of the best teaching tools for how to use the USWDS.

One thing that would help with this is greater separation of the divs that are responsible for grid layout from the divs that are responsible for style in each of the components.

Meaning, don't assign component classes and IDs to the `container`, `row`, or `col` divs. Either assign them before, or within.

**Example:**
```
<section class="solar-system">
  <div class="grid-container">
    <div class="grid-row grid-gap">
      <div class="grid-col-12">
        <div class="planet planet-earth">
          Hello world!
        </div>
        <div class="planet planet-mars">
          Nanu Nanu!
        </div>
      </div>
    </div>
  </div>
</section>
```
It would let each of the components be more of a teaching tool for how to use the USWDS, how to use utilities, and where it's best to extend it _(and where it is not)_

**Comment by thisisdano** [comment]
Let's look at this when we rebuild our templates in patternlab. In many instances we may not want to use the standard grid components and build it into the component Sass, but if we _do_ use the grid, we should separate it as suggested

**Comment by thisisdano** [comment]
I love this idea, but for components we will move away from including the layout grid in component code, and include it only for macro-level layouts
