### ISSUE TITLE
Make the GOV Banner a stand-alone component on the USWDS site

### ISSUE THREAD

**Issue by jeremyzilar** [uswds/uswds#3101]
As a publisher of guidance around using the USWDS, I would like to be able to point to the code for the GOV Banner on the USWDS site, as a stand-alone component.

Related: https://github.com/uswds/uswds/issues/3098 and https://github.com/uswds/uswds/issues/3099

**Comment by saracope** [comment]
Sharing the gov banner component we did for code.gov in case it might be helpful here:
https://github.com/GSA/code-gov-style/pull/84

**Comment by jeremyzilar** [comment]
This is helpful @saracope

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds-site/pull/814
