### ISSUE TITLE
SASS Compiling

### ISSUE THREAD

**Issue by ascreven** [uswds/uswds#3112]
## Description
imports in packages/_uswds_components are unreadable 
`Message:
    node_modules/uswds/dist/scss/packages/_uswds-components.scss
Error: File to import not found or unreadable: base/body.
        on line 5 of node_modules/uswds/dist/scss/packages/_uswds-components.scss
        from line 13 of node_modules/uswds/dist/scss/uswds.scss`

**Comment by thisisdano** [comment]
Hm! Lemme look into this.

**Comment by thisisdano** [comment]
@ascreven Can you provide a bit more context around where you get this error?

**Comment by ascreven** [comment]
It appears when I try to import the main USWDS sass file from node_modules, such as: ```@import 'uswds/dist/scss/uswds';```

**Comment by thisisdano** [comment]
OK, I see the problem — I will work up a fix, pull request, and release shortly.

**Comment by thisisdano** [comment]
@ascreven Try installing from my fix branch and see if it works for you. 

Please try something like `npm install uswds@github:uswds/uswds#dw-uswds-compile-paths` and then attempt to recompile.

**Comment by thisisdano** [comment]
(I'm not feeling certain about my local tests so I'd like to get independent outside confirmation.)

**Comment by robertromore** [comment]
I was seeing the same issue and tried installing `uswds@github:uswds/uswds#dw-uswds-compile-paths` and can confirm that it now seems to be resolved.

**Comment by thisisdano** [comment]
Thank you @robertromore — I expect to have a fix and a new release published asap.
