### ISSUE TITLE
Implementations: Benjamin and Franklin links

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds#3121]
Update the Benjamin and Franklin links on https://designsystem.digital.gov/documentation/implementations/.

The Benjamin theme and Franklin plugin are now in WordPress repos:
* https://wordpress.org/themes/benjamin/
* https://wordpress.org/plugins/franklin

**Comment by stevenbuccini** [comment]
Based on the documentation, it looks there's a separate repo for changing the actual documentation for this code. I went ahead and made a pull request for you [here](https://github.com/uswds/uswds-site/pull/821).

**Comment by thisisdano** [comment]
Completed in https://github.com/uswds/uswds-site/pull/821
Thanks @stevenbuccini!
