### ISSUE TITLE
$theme-site-max-width doesn't seem to do anything

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3125]
The `$theme-site-max-width` variable doesn't seem to hook into any styling. Should it? Is it a redundant feature?

**Comment by mejiaj** [comment]
Checkout the [example](https://github.com/uswds/uswds/commit/73f4e33d9173e83fa1d804eae67da2e140313585#diff-04c6e90faac2675aa89e2176d2eec7d8R304-R313) from 2018. It's still valid, but confusing:

![image](https://user-images.githubusercontent.com/3385219/72567036-a98d5980-387a-11ea-8041-bbeb854f0557.png)

It seems to have been replaced by `$theme-grid-container-max-width: "desktop";`

**Comment by thisisdano** [comment]
Let's figure out what to do with this and be done with it. I would expect that changing this (or some) variable would change the width of banner, heading, footer, etc at the same time.
