### ISSUE TITLE
Nav highlight indicator should disappear when submenu active

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3126]
The bar indicator should disappear when the submenu is active.

```
.usa-nav__link[aria-expanded=true],
.usa-nav__link[aria-expanded=true]:hover {
  &:after {
    display: none;
  }
}
```

**Comment by mejiaj** [comment]
@thisisdano I think #3421 took care of this issue.

**Comment by mejiaj** [comment]
@thisisdano I think we can close this.

https://github.com/uswds/uswds/blob/ab391fee9575f701f88c082401b31c3b37c29dd0/src/stylesheets/components/_header.scss#L166-L170
