### ISSUE TITLE
How to create a set of custom color tokens?

### ISSUE THREAD

**Issue by rhukster** [uswds/uswds#3134]
## How to create a set of custom color tokens?

We're implementing a web site but the agency has a specific set of colors that need to be used that don't quite align to the USWDS2-provided color tokens.

## Description

We're modifying the `_uswds-theme-color.scss` file and trying to set the `$theme-color-primary*` colors so they align with the agency required colors.  However, these variables only work with color tokens.  We're having trouble locating where an how to add custom color tokens that are outside the default ones.  I can see how to add a specific color in the `_uswds-theme-utilities.scss` file for various things (color, background, border, etc), but these generate specific colors, not general colors that can be used in the primary section.

Do you have any advice on how to achieve this?

Cheers,

**Comment by thisisdano** [comment]
Taking this up in https://github.com/uswds/uswds/issues/3209
