### ISSUE TITLE
Revisit SCSS Modularity w/ SASS Modules 

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3138]
## Revisit SCSS Modularity w/ SASS Modules : 

https://css-tricks.com/introducing-sass-modules/

`@use` and `@forward` will allow us to more easily include partials we might need and prevent duplicate CSS on compile.

I imagine initially we could forward the tokens and then `@use` when actually building the component.

Pretty generic request, but this might be a goal we work towards. Maybe for a 3.x release.

**Comment by thisisdano** [comment]
I'm very interested in this. I only read about Sass modules a few days ago!

**Comment by OrangeDrangon** [comment]
I was going to open an issue in regard to this but upon finding this here is the only information that I have not seen mentioned:

There is a path to [migration](https://sass-lang.com/documentation/cli/migrator) with a CLI tool. I am not sure how well it works or what it would lead to but is most likely worth looking into as at least a starting point for any potential migration in the future.

**Comment by mejiaj** [comment]
There was a first pass of this I was testing locally during the holidays, the result is in this commit:
 mejiaj/uswds@623faa0a8009d178779bb9109da796745c17b10d

Right now it error's out on:
```bash
Error in plugin "sass"
Message:
    src/stylesheets/settings/_settings-components.scss
Error: Undefined variable.
   ╷
60 │ $theme-hero-image: "#{$theme-image-path}/hero.png" !default;
   │                       ^^^^^^^^^^^^^^^^^
   ╵
  src/stylesheets/settings/_settings-components.scss 60:23  @use
  src/stylesheets/packages/_required.scss 10:1              @use
  src/stylesheets/uswds.scss 5:1                            root stylesheet
```

And before that I was getting other issues, but I guess it's a good start.

**Comment by thisisdano** [comment]
Not using Sass modules at the moment because they still don't have enough support in our ecosystem.
