### ISSUE TITLE
Update uswds-gulp and uswds-sandbox to latest USWDS version

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3141]
The sandbox and gulp files are using 2.1.0 when the current version is 2.2.1. Can this be updated?

https://github.com/uswds/uswds-sandbox/blob/master/package.json#L34

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds-sandbox/pull/31 and https://github.com/uswds/uswds-gulp/commit/166e81c6405bb8cf30856ff4bc8b0ab69b18b4cf
