### ISSUE TITLE
Draft initial assumptions and hypotheses

### ISSUE THREAD

**Issue by pglevy** [uswds/uswds#3149]
We want to collect our initial assumptions and hypotheses about a card component so that we know where we are as a team at the start of the design process. The point of this exercise is to identify as many existing assumptions as we can and convert them into testable hypotheses.

The 18F Method Cards suggest the following to formalize a hypothesis.

- We believe that doing/building/creating [this]
- for [this user]
- will result in [this outcome].
- We’ll know we’re right when we see [this metric/signal].
- But, this could be harmful for [this user].
- It could be harmful if [this outcome happens].

**Steps**
- [ ] Identify as many assumptions as we can about cards
- [ ] Convert these into hypotheses
- [ ] Add these hypotheses to the canonical issue (https://github.com/orgs/uswds/projects/1#card-29123284)
- [ ] Solicit feedback

**Acceptance Criteria**
- Well-formed hypotheses
- Added to canonical issue
- [_Something about feedback_]

**Comment by thisisdano** [comment]
Here are a couple resources for how we might structure assumptions and hypotheses:
**18F Design Hypothesis method card:** https://methods.18f.gov/decide/design-hypothesis/
**Harm prompts addition:** https://github.com/18F/methods/issues/420

**Comment by thisisdano** [comment]
Captured in https://github.com/uswds/uswds-team/issues/1
