### ISSUE TITLE
Button Component page on designsystem.digital.gov is not loading

### ISSUE THREAD

**Issue by openbrian** [uswds/uswds#3159]
https://designsystem.digital.gov/components/button/

It just prints "502 Bad Gateway: Registered endpoint failed to handle the request."

**Comment by thisisdano** [comment]
I'm seeing it load for me, but I _have_ seen this error before and I'm guessing it's something coming from cloud.gov and Federalist.

@amirbey Do you have any clue why this would be happening?

**Comment by openbrian** [comment]
For what it's worth.  It's only this page for me.  Others work.
--
Brian DeRocher

**Comment by amirbey** [comment]
hi @thisisdano - it appears it is due to a insufficient memory on the proxy server ... i have incremented the memory and am watching the logs. i will add more if needed.
