### ISSUE TITLE
Landscape analysis of principles and guidance

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3161]
Draft the principles and preliminary guidance...
-	Landscape analysis of principles and guidance

**Comment by pglevy** [comment]
What do we know from other design systems that have this component?
What is their guidance (usability, accessibility, etc.)?
Output:
Links to existing documentation, examples
Collection of what's out there on a "digital whiteboard"
Analysis and comments on what to take from examples

**Comment by thisisdano** [comment]
[This doc](https://docs.google.com/spreadsheets/d/1_OQG0I2hlnblwWdIhmtvEFLNgxOvEzb6t2rIHKYPVSc/edit?usp=sharing)🔒should be a good starting point for a landscape analysis.

**Comment by pglevy** [comment]
Relevant recent article: [UI Case study: state styles of card component with accessibility in mind](https://blog.prototypr.io/ui-case-study-state-styles-of-card-component-with-accessibility-in-mind-2f30137c6108)

**Comment by thisisdano** [comment]
Landscape analysis working doc: https://github.com/uswds/uswds/wiki/Card-Landscape-Analysis

**Comment by pglevy** [comment]
@thisisdano, I moved the working doc for the principles to a [new wiki page](https://github.com/uswds/uswds/wiki/Card-Principles-(Draft)) since we're tracking that as a separate issue (#3166).
