### ISSUE TITLE
Landscape analysis of existing government usage/solutions

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3162]
- Draft the principles and preliminary guidance...
- Landscape analysis of existing government usage/solutions

**Comment by pglevy** [comment]
Collect examples from governments sites who have their own version of this component
Look at other government design systems (Gov.UK, design.cms.gov, VA, PTO, etc.)
Output:
Collection of links and screenshots
Collection of code snippets

**Comment by thisisdano** [comment]
[This doc](https://docs.google.com/spreadsheets/d/1_OQG0I2hlnblwWdIhmtvEFLNgxOvEzb6t2rIHKYPVSc/edit?usp=sharing)🔒should be a good starting point for a landscape analysis.

**Comment by thisisdano** [comment]
Landscape analysis working doc: Landscape analysis working doc: https://github.com/uswds/uswds/wiki/Card-Landscape-Analysis
