### ISSUE TITLE
Draft component principles

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3166]
- [ ] Principles and guidance added to canonical issue
- [ ] Principles and guidance published to website in draft component
- [ ] Sync on existing work
- [ ] Finalize the guidance into a doc
- [ ] Know _how_ we're going to publish it

**Comment by pglevy** [comment]
- [ ] Post draft to issue
- [ ] Solicit feedback from community and stakeholders/testers (from Investigation Phase)
- [ ] Leave open for and encourage comments for at least 2 weeks (sprint)
- [ ] Publish draft to website

Acceptance Criteria:
Assure alignment with USWDS service and product principles (Answers to questions of Service and USWDS Product principles describing how the component is adhering to them.)

**Comment by pglevy** [comment]
Created separate wiki page for [Card Principles working doc](https://github.com/uswds/uswds/wiki/Card-Principles-(Draft)).

**Comment by pglevy** [comment]
@thisisdano, Added some thoughts and questions on a second approach to the [draft principles](https://github.com/uswds/uswds/wiki/Card-Principles-(Draft)).

**Comment by thisisdano** [comment]
Captured in https://github.com/uswds/uswds-site/pull/913
