### ISSUE TITLE
Localize text in components (such as the .gov banner)

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds#3206]
## Description

When I'm on a site like https://www.cuidadodesalud.gov/es/ or https://ca.usembassy.gov/fr/, I'd expect to see the text in the .gov banner in the site's selected locale/language.

It is in Spanish on https://www.usa.gov/espanol/.

## Steps to reproduce the issue

1. Go to a website that is available in Spanish.
2. Toggle the language/locale to Spanish.
3. Look at the .gov banner and confirm it is in Spanish.

## Other Information

* Based on a quick review of current implementations, consider starting with English and Spanish (working with the Gobierno team for the Spanish)
* Example: Search.gov localization files: https://github.com/GSA/punchcard/tree/master/localizations

**Comment by thisisdano** [comment]
We did this when we updated the banner. Other localization work will happen in another issue.
