### ISSUE TITLE
Add tap target size guidance to button component

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3207]
Our buttons and other tap targets use a minimum size of 48px (`6 units`). We should include this minimum tap target size in our button guidance. See https://www.smashingmagazine.com/2012/02/finger-friendly-design-ideal-mobile-touchscreen-target-sizes/ for more.

**Comment by maya** [comment]
What does tap target refer to? Width, height, or both?

**Comment by thisisdano** [comment]
Both — that is Apple's [Human Interface Guide](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/) says "Provide ample touch targets for interactive elements. Try to maintain a minimum tappable area of 44pt x 44pt for all controls."

**Comment by maya** [comment]
If that's the case, then the default buttons do not meet that. They are 39px tall or 9px short of the 48px you're trying to maintain. 

<img width="225" alt="Screen Shot 2020-04-28 at 11 45 28 AM" src="https://user-images.githubusercontent.com/5249443/80527088-ac531c80-8948-11ea-9f8f-5a10c7a3ce6d.png">

44pt translates to px a little differently too.
<img width="515" alt="Screen Shot 2020-04-28 at 12 18 22 PM" src="https://user-images.githubusercontent.com/5249443/80528208-6c8d3480-894a-11ea-836d-0bad290952eb.png">

**Comment by maya** [comment]
Or if you wanted to just detect touch devices: https://medium.com/@ferie/detect-a-touch-device-with-only-css-9f8e30fa1134

**Comment by thisisdano** [comment]
Ha. Well given how few actual controls I can find on the web that actually conform to this guidance, it might appear to be less realistic than I would have guess.

**Comment by maya** [comment]
The header nav button and accordion buttons do account for this being at least 48px tall. I don't think it would be bad to look at getting buttons up to this standard. If the look is a problem, consider targeting touch screens or smaller screen sizes. 

<img width="228" alt="Screen Shot 2020-04-28 at 2 46 52 PM" src="https://user-images.githubusercontent.com/5249443/80540938-1ecef700-895f-11ea-9bcb-2cf3201c15b1.png">

<img width="446" alt="Screen Shot 2020-04-28 at 2 44 46 PM" src="https://user-images.githubusercontent.com/5249443/80540866-f6df9380-895e-11ea-8fa3-a54d80d54aaa.png">

In general, when I use the default button on my mobile devices, it does feel a little tiny.

## desktop vs. mobile buttons
![IMG_6538](https://user-images.githubusercontent.com/5249443/80541948-fe07a100-8960-11ea-87c4-fc6475d0c863.jpg)
![IMG_6537](https://user-images.githubusercontent.com/5249443/80541954-019b2800-8961-11ea-93a0-166291412a7b.jpg)

## with a human thumb for scale 

![IMG_6539](https://user-images.githubusercontent.com/5249443/80541926-f21bdf00-8960-11ea-8e76-ee89847f0e3e.JPG)

**Comment by thisisdano** [comment]
OK, I'm going to close this issue, since it's not quite as simple as I originally thought it might be. If we want to move toward a bigger default button, this should probably be in the context of better research and guidance around target sizing.
