### ISSUE TITLE
Alert success icon should be a checkmark but is identical to error icon

### ISSUE THREAD

**Issue by nickscialli-usds** [uswds/uswds#3230]
## Description

The alert success icon is supposed to be a checkmark but is currently an exclamation point. It is identical to the icon for error alerts. See the [Alert component site](https://designsystem.digital.gov/components/alert/) for the identical icons. 

The icon was correct, but misaligned, as of this commit: https://github.com/uswds/uswds/blob/3eba7caf3c9abc5fb032b88a04c9c866bbb1c9dc/src/img/alerts/success.svg

But appears to have been inadvertently changed to the error icon during this commit: https://github.com/uswds/uswds/blob/9d431ceb5842e028b8a6c4ad3b996db00a70804b/src/img/alerts/success.svg

## Steps to reproduce the issue

1. View alert icons at https://designsystem.digital.gov/components/alert/

### Incorrect success icon screenshot

![Issue Screenshot](https://user-images.githubusercontent.com/49658917/69281318-13a8bb80-0bb6-11ea-83cf-99c15d766a13.png)

**Comment by thisisdano** [comment]
Ugh, yuck. Thanks for pointing that out — i'll get that fixed asap.

**Comment by thisisdano** [comment]
Fixed in #3233

**Comment by nickscialli-usds** [comment]
Thank you!
