### ISSUE TITLE
Need to have NPM vulnerabilities in USWDS Version 1 remediated

### ISSUE THREAD

**Issue by governmentSponsored** [uswds/uswds#3235]
## Description

We're currently are having issues with npm vulnerabilities using USWDS v1. Have seen 80+ high vulernabilities, almost all relating to the dependency set-value needing to be at 3.0.1 or 2.0.1. We need to be able to use USWDS v1 without any high vulnerabilities (and preferably no medium or low either).

Details:
* NPM - 6.11.3
* Node - 12.11.1

## Steps to reproduce the issue

1. Use USWDS Version 1
2. Run `rm package-lock.json` if there are any existing package-lock.json file
3. Run `npm install --package-lock`
4. Run `npm audit fix`
5. After all of that, the vulnerabilities should show up in command line. Somewhere in the neighborhood of 80-90 high ones.

## Additional information [optional]
Here are some steps that reduced, but did not eliminate the high vulnerabilities:
```shell
cd <PATH_TO_USWDS>/node_modules/option-cache && npm install set-value@latest --save
cd <PATH_TO_USWDS>/node_modules/union-value && npm install set-value@latest --save
cd <PATH_TO_USWDS>/node_modules/engine && npm install set-value@latest --save
cd <PATH_TO_USWDS>/node_modules/templates && npm install set-value@latest --save
cd <PATH_TO_USWDS>/node_modules/expand-object && npm install set-value@latest --save
cd <PATH_TO_USWDS>/node_modules/expand-args && npm install set-value@latest --save
cd <PATH_TO_USWDS>/node_modules/question-cache && npm install set-value@latest --save
cd <PATH_TO_USWDS>/node_modules/common-config && npm install set-value@latest --save
cd <PATH_TO_USWDS>/node_modules/cache-base && npm install set-value@latest --save
cd <PATH_TO_USWDS>/node_modules/map-schema && npm install set-value@latest --save
cd <PATH_TO_USWDS>/node_modules/engine && npm install assign-deep@latest --save
npm update set-value --depth 4
npm update assign-deep --depth 4
cd <PATH_TO_USWDS>/ && npm install
npm audit fix
```

Relevant research and support documents:
* `cd node_modules/option-cache && npm install set-value@latest --save` - have tried this in every location that uses set-value
* `npm update set-value --depth 4`
* `npm audit fix`

Their vulnerability is listed here https://npmjs.com/advisories/1012 as **Prototype Pollution**. All packages will have `set-value` and `assign-deep` set to the secure versions, but for some reason the audit still brings them up.

**Comment by thisisdano** [comment]
Thanks for putting this issue together. `v1.6.13` should have only 4 moderate vulnerabilities.
Fixed in https://github.com/uswds/uswds/pull/3244
