### ISSUE TITLE
npm install --save uswds@latest - is installing v1.6.13

### ISSUE THREAD

**Issue by stephencross** [uswds/uswds#3255]
## Description

When following the npm installation instructions at https://designsystem.digital.gov/documentation/developers/   the command:

`npm install --save uswds@latest `

is installing v1.6.13, not version 2.

When searching npm (npm search uswds) 1.6.13 is listed as the current version.

**Comment by thisisdano** [comment]
Oh that's no good. Fixed now. 

This is good for us to know, though. The `latest` version is simply the most recently published, not the highest stable version. I will add this to our release process.

**Comment by thisisdano** [comment]
We'll prevent this from happening in the future with https://github.com/uswds/uswds/issues/3257
Thanks for bringing it to our attention, @stephencross

**Comment by stephencross** [comment]
Thanks for the quick response!
