### ISSUE TITLE
Build process should not require media query packing

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3262]
Media query packing is an extra requirement to the build process, necessary to reorder the output from the utilities builder to give it the proper CSS source order. Our current mq packing solution is deprecated (see #3079) and complicates the user build process.

- Is there another post-processing tool that could serve the same purpose as our current mq packer?
- Could we rebuild the utilities builder so such a requirement is no longer necessary?
- Can any solution we implement be as fast or faster than the current solution?

**Comment by mejiaj** [comment]
X-Post from https://github.com/uswds/uswds-gulp/issues/11

Also note:
The original has this media-query `@media all and (min-width: 64em) and (min-width: 64em)`

---

`gulp-group-css-media-queries` is not actively maintained, unfortunately.

Here are some I've looked at:
New (left) / Old (right)

- [postcss-sort-media-queries](https://github.com/solversgroup/postcss-sort-media-queries)
![image](https://user-images.githubusercontent.com/3385219/73094214-bd9e1000-3ea5-11ea-8179-02c7a97c30b4.png)

- [postcss-combine-media-query](https://github.com/SassNinja/postcss-combine-media-query)
Doesn't sort media queries.
![image](https://user-images.githubusercontent.com/3385219/73093268-c261c480-3ea3-11ea-97da-8659af74a742.png)


## Outdated
- [gulp-group-css-media-queries](https://github.com/avaly/gulp-group-css-media-queries#readme)
- [gulp-clean-css](https://github.com/scniro/gulp-clean-css) up-to-date, but based on clean-css which [isn't maintained anymore](https://github.com/jakubpawlowicz/clean-css/issues/1105).

**Comment by thisisdano** [comment]
`postcss-sort-media-queries` seems like a good interim step to include this functionality via gulp, but using a maintained package.

**Comment by sawyerh** [comment]
Just +1'ing this – I've struggled for an hour or so today trying to get utility classes to override certain styles. One issue was #3293 and another seems related to the media query declaration being included later in the file, though I am using `require("postcss-sort-media-queries")({ sort: "mobile-first" })` in my PostCSS configuration.

I'm not familiar with the current implementation, but have found `!important` to be useful (and appropriate) for utility class declarations.
