### ISSUE TITLE
Replace Fractal as a component development and documentation tool

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3263]
Fractal is no longer a reliable tool for developing and documenting our components. It introduces a number of vulnerabilities into our dependencies and is no longer reliably maintained. Newer tools like [Storybook](https://storybook.js.org/) or [PatternLab](https://patternlab.io/) could be a better forward-looking solution. We need to understand the pros and cons of possible solutions, and how any documentation and development solution we implement could be useful to other teams, in addition to our own internal core team.

**Comment by stphnwlkr** [comment]
I like Storybook. Nice listing of a variety of tools available at https://designsystemsrepo.com/tools/. Some not appropriate for this project, but it give you a good idea of what is out there.

**Comment by DanielMiller-agile6** [comment]
I really like Storybook as well.  It supports most of the popular frontend JS frameworks now.  Although in my experience, not all framework support is as mature as React... things seems to be improving quickly though so I might be wrong about this now :)

There's also a [@storybook/html](https://github.com/storybookjs/storybook/tree/master/app/html) package which helps for developers who don't use any framework, and just want to use storybook as a CSS framework development tool or for a UI pattern library.

A few months ago, the Storybook team released a "[Design Systems for Developers](https://www.learnstorybook.com/design-systems-for-developers/)" book online which was really helpful to me.  While the title seems fairly generic, most of the book is an explanation of using Storybook for design systems and component libraries.  Most of the examples in the book use React, but it could still be helpful for users of other frameworks.

**Comment by chazchumley** [comment]
Pattern Lab node version with NPM and Gulp would be great for non-REACT sites.  Plus I am willing to help build that out :) It would then allow for govt sites and there heavy adoption of Drupal.

**Comment by afeijoo** [comment]
Customer feedback: "I cannot scroll up and down on the left pane in Chrome on Windows 10, only in IE on Windows 10 (I cannot even use page up or page down) on https://components.designsystem.digital.gov/."

**Comment by maya** [comment]
Storybook has a twig option with [storybook-twig](https://github.com/markhuot/storybook-twig) (@mejiaj mentioned this was a reason why PL was chosen). Storybook seems to be the superior UI library tool today.

**Comment by mejiaj** [comment]
Is storybook-twig still under active development? Only release was in May 2019. But I agree, storybook is interesting and it'd be worth another look.

**Comment by maya** [comment]
You could probably base something off of that work, and update all the dependencies and maintain it yourself. Doesn’t seem like a whole lot there. Storybook is very well maintained.

**Comment by mejiaj** [comment]
Completed with final phase of migration https://github.com/uswds/uswds/pull/4511.
