### ISSUE TITLE
Gov banner needs a distinguishing landmark label

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3264]
Both the gov banner and the main header are `<header>` elements. This is OK, but since they are both `banner` landmarks, we'll need to use ARIA labels to distinguish them. The label could be something like `aria-label="official government website"` for the gov banner. Would the primary header need a label as well?

@iamjolly What are the necessary considerations here?

**Comment by thisisdano** [comment]
Alternately, we could refactor the banner to not use the `<header>` element. While it would still need a label, we would also have to assign an ARIA role. Would it most accurately be a `banner` or a generic `region`?

**Comment by iamjolly** [comment]
> Both the gov banner and the main header are <header> elements. This is OK, but since they are both banner landmarks, we'll need to use ARIA labels to distinguish them. The label could be something like aria-label="official government website" for the gov banner. Would the primary header need a label as well?

You will likely want to use another label for the primary header, but it could be something simple like "primary" or "site header" as its label. 

However, I'd recommend changing the official U.S. Gov a `<header>` to be a `<div>` and including that inside the primary `<header>` for pages/sites that have that toggled on, if possible.

**Comment by iamjolly** [comment]
> @iamjolly What are the necessary considerations here?

Sorry for not fully answering that question, @thisisdano... the following is my attempt at that.

For landmark regions, the consideration is essentially "Do the landmark regions make sense in context for someone using assistive technology?" This brings up two things in the case of the USWDS banner regions:
1. Structure: with two `header` elements so close together, it makes more logical/practical sense to combine them into one area, as they're really one area of the site. I imagine that a site will either include the U.S. gov info or it won't—sitewide. So, there's no real distinction to be made between the info in it and the primary header. Including the U.S. gov info in a generic container element like a `div` within the primary `header`, you also won't need to address the second item here, which is unique labels.
2. Labeling of landmarks: When there are two or more of the same landmark region, then you will want to assign unique, descriptive labels for each. This is most often seen and needed when there are multiple `nav` elements on a page, but this also applies to other regions. This will help an AT user to understand the contents and purpose of each region and navigate to them (or skip over them) as they deem appropriate.

The W3C has published [a helpful resource on ARIA Landmarks](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/index.html) which you may find more useful (and accurate) than my advice. 

The last bit I'd suggest is recruiting some screen reader users to test out your approach(es) to determine what is the most usable, friendly implementation. I think at this point, there are no serious technical accessibility issues to the current or proposed approaches. This is really fine-tuning the usability to ensure we're giving everyone the best possible experience. :)

**Comment by thisisdano** [comment]
For modularity reasons, we couldn't nest the banner inside the primary `header`, so we've opted to wrap the whole banner in a `section` with the ARIA label "Official government website" — that way we avoid multiple `banner` landmarks and provide a good label for the Official website information. Implemented in USWDS 2.6.0.
