### ISSUE TITLE
SCSS Compiling error

### ISSUE THREAD

**Issue by allavy** [uswds/uswds#3276]
I downloaded the package on my Mac and created a sample file. I used link rel="stylesheet" href="assets/css/uswds.css" / as styles reference, and Dreamweaver sent me an error message - 
**Error: '4' is not a valid flex value.
On line 47 of ../uswds/sccs/core/mixins/utilities/_flex.scss in 'u-flex'**   
... (and a list of affected files)...

When I ran Koala compiler on uswds.scss it gave me the same error. 
I did not make any changes after downloading.

I have Dreamweaver 2019, node-sass.

Please advise what I can do in this situation.

**Comment by mejiaj** [comment]
@allavy, I'm not sure if Koala is using the latest version of SASS. The changelog shows it was last updated in 2017.

Does Dreamweaver have it's own compiling built-in for sass? Or is this some pre-defined task you've setup for it.

**Comment by allavy** [comment]
Koala might not, but it still perfectly compiles other sccs packages, from other frameworks, with the latest updates. Thats why I still use it, but maybe better stop now.

That's what I found on my Mac - /Applications//Adobe Dreamweaver CC 2019/Adobe Dreamweaver 2019.app/Contents/Resources/node-core/services/Compilers/node_modules/node-sass/bin/node-sass . Not sure where else to look.

regarding 2.4.0 - this is my first time with uswds ever - never tried it before. I am not a cool programmer. Want to make a few little edits in scss, but keep getting an error.

**Comment by mejiaj** [comment]
It's okay, we can try to figure this out. I don't have Dreamweaver, so unfortunately I won't be able to test there.

I'll try Koala.

**Comment by allavy** [comment]
@mejiaj  thanks a lot!
What I see in Dreamweaver also - in Configuration/SassFrameworks folders base, bourbon, neat
not sure if it means anything in this case

**Comment by mejiaj** [comment]
@allavy is there a `package.json` or something that would say the version of `node-sass` that dreamweaver uses?

It might be that your version needs to be updated. 

I was able to replicate the issue with Koala, I think it's having some trouble with this line:
```scss
// _megamenu.scss:14
.usa-megamenu {
  .usa-col {
    @include u-flex(1);
    @include at-media($theme-header-min-width) {
      @include u-flex(12 / $theme-megamenu-columns);
    }
  }
}
```

---

I was able to fix by using the latest version of node-sass.

I would either try:

- Try to upgrade the version of node-sass Dreamweaver uses.
- Look at using https://github.com/uswds/uswds-gulp
  - make sure you have [node](https://nodejs.org/en/) installed
  - install gulp-cli globally
  - Go into your project directory and run `npm install`
  - Run watch task

We also have a [slack channel](https://chat.18f.gov/) you can sign up for additional assistance.

**Comment by allavy** [comment]
@mejiaj  for me it gave a different error - line in bold
`@mixin u-flex($value...) {
  $value: unpack($value);
  $important: null;
  @if has-important($value) {
    $value: remove($value, "!important");
    $important: " !important";
  }
  @each $this-value in $value {
    $match: false;
    @each $property, $map in $flex-utililies {
      @if not $match and map-has-key($map, $this-value) {
        #{$property}: get-uswds-value($property, $this-value...) #{$important};
        $match: true;
      }
    }
    @if not $match {
      **@error '`#{$this-value}` is not a valid `flex` value.';**
    }
  }
}`

My colleague installed 2.4.0 and it gave him an error too. So he switched to 2.3.1 and it worked fine.

Thanks for your help, I'll start with updating node.

**Comment by mejiaj** [comment]
@allavy `2.3.1` worked with Koala, Dreamweaver, or both? That error you posted above is related to the code I posted earlier.

If it's working with either/both on `2.3.1` then I think we have another issue.

**Comment by allavy** [comment]
@mejiaj it did not work for me eventually.
I'll follow your advice and ask techs to update Node version (I cannot do that because I am not an admin)
And I'll see how it goes. 
Thanks a lot!
