### ISSUE TITLE
USWDS Footer Email Link Update

### ISSUE THREAD

**Issue by DanielJPino-ux** [uswds/uswds#3279]
Please update the USWDS footer link from uswds@gsa.gov to: uswds@support.digitalgov.gov

We are cutting over to a new email address and need to have the new address updated across the board. 

Thank you.

## Description

Include a high-level description of the issue. What did you expect to happen? What happened instead? What would you like to see changed?

Include any benefits, challenges, or considerations. This can be short and sweet.

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information [optional]

* Relevant research and support documents
* Screen shot images
* Notes
* And so on

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/uswds-site/commit/4412fb1d71e67a0c66045cc97ab9389617c7276b
