### ISSUE TITLE
Mutli-line strings are breaking webpack sass compiles.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3285]
Sass loader breaks when using latest `2.4.0` SASS changelog.

**Comment by mejiaj** [comment]
@thisisdano I took another look at the webpack issue from [here](https://github.com/greenca6/uswds-tester/tree/uswds-2.4.0-bug).

I definitely see the benefits of having it in SASS, but unfortunately we'd have to use or write a separate loader that would handle this properly. 

An alternative I've mocked up can be found on `feature/USWDS-3285`. This moves the message to `changelog.js` and is currently shown on `gulp build` it looks like this:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/3385219/72646168-19fbaf80-393b-11ea-8407-88ba6cd0e7ee.png">

I'm sure we can keep improving this, but I just wanted to provide this as an option.

Another alternative is having a `CHANGELOG.md` file in the root directory.

**Comment by thisisdano** [comment]
I really like where this is going

**Comment by sawyerh** [comment]
Was just coming here to report the same. I've been struggling to get a Sass file to compile using either `sass` or the `@csstools/postcss-sass` packages, due to what I think is the same issue. Seeing the following error:

```
> postcss styles/**/[!_]*.scss -d build --ext css

Error: Expected ".
   ╷
14 │ --------------------------------------------------------------------
   │                                                                     ^
   ╵
  node_modules/uswds/dist/scss/core/_notifications.scss 14:69  @import
  node_modules/uswds/dist/scss/packages/_required.scss 21:9    @import
  node_modules/uswds/dist/scss/uswds.scss 5:9                  @import
  styles/app.scss#sass 1:9                                     root stylesheet
    at Object._newRenderError (/Users/sawyer/Dev/Sites/mass/uswds-mayflower/node_modules/sass/sass.dart.js:10899:19)
```

**Comment by sawyerh** [comment]
To recreate the issue from my previous comment, you can:

1. Visit
2. Enter the following into the Sass panel:
```
/*  notifications.scss
    ---
    Adds a notification at the top of each USWDS
    compile. Use this file for important notifications
    and updates to the design system.

    This file should started fresh at each
    major version.

*/

/* stylelint-disable string-no-newline  */
$uswds-notifications: "\a
--------------------------------------------------------------------
\2709  USWDS Notifications
--------------------------------------------------------------------
2.4.0: If your component settings aren't working as expected, make
sure you're importing the components settings in your Sass entry
point (often styles.scss) with `@import \"uswds-theme-components\"`.
A bug in 2.0 omitted that import.

- We added `$theme-show-notifications: true` to general settings
--------------------------------------------------------------------
2.2.0: We changed the names of some settings.

- $theme-navigation-width \2192  $theme-header-min-width
- $theme-megamenu-logo-text-width \2192  $theme-header-logo-text-width
--------------------------------------------------------------------
2.0.2: We changed the names of some settings and mixins.

- $theme-title-font-size \2192  $theme-display-font-size
- @include title \2192  @include display
- @include typeset-title \2192  @include typeset-display";

$uswds-notification-disable-message: "
--------------------------------------------------------------------
These are notifications from the USWDS team, not necessarily a
problem with your code.

Disable notifications using `$theme-show-notifications: false`
in your general settings file.
--------------------------------------------------------------------\a";
/* stylelint-enable  */
```

3. From "Options", change the compiler to Dart Sass (which I think is the "official" compiler for Sass these days)
![image](https://user-images.githubusercontent.com/371943/72998730-552f3000-3dcc-11ea-9f1d-ce0a2c47f8ab.png)

**Comment by sawyerh** [comment]
Related: https://github.com/sass/dart-sass/issues/783

**Comment by mejiaj** [comment]
@thisisdano As an immediate fix the following works in both dart and just compiles regularly, but doesn't appear in webpack.
``` scss
$uswds-notifications:
"\000A --------------------------------------------------------------------" +
"\000A ✉️ USWDS Notifications" +
"\000A --------------------------------------------------------------------" +
"\000A 2.4.0: If your component settings aren't working as expected, make" +
"\000A sure you're importing the components settings in your Sass entry" +
"\000A point (often styles.scss) with `@import \"uswds-theme-components\"`." +
"\000A bug in 2.0 omitted that import." +

"\000A - We added `$theme-show-notifications: true` to general settings" +
"\000A --------------------------------------------------------------------" +
"\000A 2.2.0: We changed the names of some settings." +

"\000A - $theme-navigation-width \2192  $theme-header-min-width" +
"\000A - $theme-megamenu-logo-text-width \2192  $theme-header-logo-text-width" +
"\000A --------------------------------------------------------------------" +
"\000A 2.0.2: We changed the names of some settings and mixins." +
"\000A - $theme-title-font-size \2192  $theme-display-font-size" +
"\000A - @include title \2192  @include display" +
"\000A - @include typeset-title \2192  @include typeset-display";

$uswds-notification-disable-message:
"\000A --------------------------------------------------------------------" +
"\000A These are notifications from the USWDS team, not necessarily a" +
"\000A problem with your code." +
"\000A" +
"\000A Disable notifications using `$theme-show-notifications: false`" +
"\000A in your general settings file." +
"\000A --------------------------------------------------------------------";
```

---

Webpack
![image](https://user-images.githubusercontent.com/3385219/73004770-7f352200-3dcd-11ea-9cbd-6e566aec0b3b.png)

**Comment by mejiaj** [comment]
@thisisdano checkout `feature/USWDS-3285`. I've kept the `changelog.js` message. But I've also added a new plugin called [auto-changelog](https://www.npmjs.com/package/auto-changelog). 

It'll run with `npm run release` and generate a CHANGELOG.md file.

---

### gulp build
![image](https://user-images.githubusercontent.com/3385219/73086691-b58aa400-3e96-11ea-9026-28c500da886c.png)

### Generated CHANGELOG.md
(from `npm run changelog or npm run release`)
![image](https://user-images.githubusercontent.com/3385219/73086808-eec31400-3e96-11ea-86fb-1a2292a8c0cf.png)

Do you think something like this would be useful or should we stick to SCSS like in my previous [comment](https://github.com/uswds/uswds/issues/3285#issuecomment-577767560)?

**Comment by thisisdano** [comment]
@mejiaj I like that and think it could be useful — but for the purposes of this issue and `2.4.1` fix, I'd like to scope the solution to:

- A notification that appears at compile, regardless of compile method
- I could accept a message that appears when updating the package via `npm`, but I think (at least for now) I'd prefer a message that appears regardless of source and compile method.

I suspect this means "just rewrite `notifications.scss` with concatenated single-line strings"
