### ISSUE TITLE
Accordion - change plus and minus image color

### ISSUE THREAD

**Issue by ajanickiv** [uswds/uswds#3286]
## When using the accordion we need to ability to change the background and text color of the button

When applying a new color css value to the accordion button, the color of the text changes but the color of the image does not.
![image](https://user-images.githubusercontent.com/16595489/72988916-3d02e500-3dbb-11ea-836e-c99e613dff0e.png)

How do I change those image colors via CSS? 

## Steps to reproduce the issue

1. Implement an USWDS accordion
2. Write a CSS class to change background color and color
3. Images do not change color

## Additional information [optional]

CSS
.accordion-background__blue {
    background-color: #005ea2;
    color: #FFFFFF;
}

HTML
<button class="usa-accordion__button accordion-background__blue"
              type="button"
              id="accordion-button"
              aria-expanded="false">
              label
</button>

**Comment by mejiaj** [comment]
@ajanickiv

Right now you'd have to update the fill of the SVG 
```html
<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64"><title>plus</title><path fill="#FFFFF" fill-rule="evenodd" d="M36 0c1.111 0 2.056.425 2.833 1.272.778.849 1.166 1.88 1.166 3.091V24h19.636c1.125 0 2.095.335 2.907 1.006l.184.16c.849.778 1.272 1.723 1.272 2.834v8c0 1.112-.425 2.057-1.272 2.834-.849.778-1.88 1.166-3.091 1.166H39.999v19.636c0 1.125-.335 2.094-1.006 2.906l-.16.185c-.778.848-1.722 1.272-2.833 1.272h-8.001c-1.111 0-2.056-.424-2.834-1.272-.778-.849-1.166-1.88-1.166-3.09V39.998H4.363c-1.125 0-2.094-.335-2.906-1.006l-.185-.16C.424 38.054 0 37.11 0 36v-8.001c0-1.111.424-2.056 1.272-2.834C2.121 24.387 3.152 24 4.363 24H24V4.363c0-1.125.335-2.094 1.006-2.906l.16-.185C25.944.423 26.889 0 28 0z"/></svg>
```

Or modify the accordion so the SVG is inline and you can do `fill: #fff`

**Comment by mejiaj** [comment]
There's a current PR open that includes code to override the color of a SVG background. It uses svg mask as a way to set the icon and `background-color` to set the color.

https://github.com/uswds/uswds/pull/3489

**Comment by bonez0607** [comment]
Would it be possible just to include a "white" variation in the img directory? Similar to `angle-arrow-down-white`, seems like there would be enough instances where this would be a valid option rather than using mask

**Comment by mejiaj** [comment]
@bonez0607 yes, since `2.10.0`+ there's a `usa-icons-bg` directory. You should be able to add a new white filled icon there and use it like so:

```scss
@include add-background-svg(
  "usa-icons-bg/expand_more--white"
);
```

**Comment by thisisdano** [comment]
Let's add a simple `--white` variant to the default codebase

**Comment by thisisdano** [comment]
The `--white` variants will be in USWDS 2.10.2:
- `usa-icons-bg/add--white.svg`
- `usa-icons-bg/remove--white.svg`
- `usa-icons-bg/expand_more--white.svg`

We will continue to make this simpler and more automatic in subsequent releases.
