### ISSUE TITLE
Identifying required fields in forms, rather than just optional fields

### ISSUE THREAD

**Issue by cmajel** [uswds/uswds#3295]
## Description

Currently, USWDS guides users to call out optional fields, rather than required fields. This guidance currently lives under [the Address form's usability guidance section](https://designsystem.digital.gov/components/form-templates/#address-form). 
<img width="600" alt="Screen Shot 2020-01-30 at 5 06 19 PM" src="https://user-images.githubusercontent.com/2374206/73495799-42e16300-4385-11ea-8197-6d3bb6933b34.png">

I believe this pattern originated with [Gov.uk's form guidance](https://govuk-elements.herokuapp.com/form-elements/#form-optional-fields). But, there has been other research showing that only marking optional fields can be confusing, and it's easier for users to fill out forms when required fields are called out. 

Supporting research:
* [Baymard, E-Commerce Checkouts Need to Mark Both Required and Optional Fields Explicitly (Only 24% Do So)](https://baymard.com/blog/required-optional-form-fields) - specifically the "Why It’s Problematic to Mark Only Optional Fields" section
* [NNG, Marking Required Fields in Forms](https://www.nngroup.com/articles/required-fields/)

### Proposed change
* Switch this guidance to showing required fields. (Or provide a rationale for keeping it as is)
* If a change should be made, create a style for required fields
* Move the guidance on showing required vs optional fields up to the `General accessibility guidance for forms` section of the [Form templates page](https://designsystem.digital.gov/components/form-templates/), rather than within Address forms.

**Comment by Jacklynn** [comment]
Some additional context is that an [aria label for required fields is required for WCAG 2.0](https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/minimize-error-cues.html#minimize-error-cues-examples-head) and it would make sense to marry the experiences. 

Labeling both is the least cognitive load, but at the very least letting users know the success criteria explicitly is the establish pattern.

**Comment by jonadecker** [comment]
It's interesting that the [Gov.uk Design System website](https://design-system.service.gov.uk/), currently in beta and replacing the Gov.uk Elements site linked above, has no guidance around required fields that I could find except for error messaging if a field is empty. Perhaps they're revisting their thinking as well?

**Comment by cmajel** [comment]
@jonadecker I did a bit of digging and they do still say to mark optional fields, not required in the [questions pages pattern page](https://design-system.service.gov.uk/patterns/question-pages/), in the Asking users questions section. I'd be curious though about the underlying research behind that decision and how it has tested.

**Comment by jonadecker** [comment]
> ...they do still say to mark optional fields, not required in the [questions pages pattern page](https://design-system.service.gov.uk/patterns/question-pages/), in the Asking users questions section. 

Good catch. Even looking through the patterns, "questions" did _not_ jump out at me :)

**Comment by thisisdano** [comment]
We'll be addressing this in the next sprint. Sorry it's sat in the backlog for so long...

**Comment by thisisdano** [comment]
See also WCAG 2.0 H90 (Indicating required form controls using label or legend): https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H90

**Comment by maya** [comment]
A bit of user research data you might find useful: people tended to skip fields when they're explicitly marked `optional`.

**Comment by brunerae** [comment]
Closing in favor of https://github.com/uswds/uswds-site/issues/1163

**Comment by thisisdano** [comment]
Though this particular issue is closing, we're finally moving on this!
