### ISSUE TITLE
Improve gulp task performance

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3297]
## Description

Some gulp tasks are taking much longer than they're supposed to. For example, `gulp-copy-dist-sass` reports to take a few milliseconds, but ends up hanging at the end — up to 11s sometimes!

This is causing some tests like `include.spec.js` (called from `gulp test`) to timeout, fail, and sometimes crash.

In this case, the cause for slowdown in `gulp-copy-dist-sass` seems to be coming from `dutil`, which is what we're using for logging.

## Steps to reproduce the issue
1. Run a task such as `copy-dist-sass`
2. Notice how it hangs at the end for up to 12s
3. Comment out line 77 on `sass.js`
4. Run `copy-dist-sass` again

## Additional information [optional]
Before 12s
![uswds-slow-gulp-01](https://user-images.githubusercontent.com/3385219/73675966-0f4e5380-4679-11ea-99f8-5f1df072510f.gif)

After 2s
![uswds-slow-gulp-02](https://user-images.githubusercontent.com/3385219/73676362-dcf12600-4679-11ea-9bd7-7ad1dfed4e24.gif)

**Comment by thisisdano** [comment]
Closing since we've done a lot of this
