### ISSUE TITLE
Font Use

### ISSUE THREAD

**Issue by SaraHerbst** [uswds/uswds#3299]
I apologize if this is obvious, I just couldn't find strict confirmation of this anywhere.
Are we restricted to only using one or more of the mentioned fonts Source Sans Pro, Merriweather, and/or Public Sans. Or are these fonts offered as recommendations? If we are restricted to these fonts, are there any others that are permissible? 
Thank you.

**Comment by thisisdano** [comment]
Others are permissible, those are just the defaults and the fonts we ship with the package. We only include the font files for Source Sans Pro, Merriweather, Public Sans, and Roboto Mono, but the design system ships with defined typeface tokens for 

'georgia'
'helvetica'
'merriweather'
'open-sans'
'public-sans'
'roboto-mono'
'source-sans-pro'
'system'
'tahoma'
'verdana'

See https://designsystem.digital.gov/design-tokens/typesetting/font-family/
You can also define your own typeface tokens, though we don't yet have documentation outside the inline documentation [here](https://github.com/uswds/uswds/blob/61aa949daba69b87b1c17058ff2ee8faee14eddb/src/stylesheets/theme/_uswds-theme-typography.scss#L84).  Hope that helps!

**Comment by SaraHerbst** [comment]
Phenomenally helpful. Thank you!
