### ISSUE TITLE
Upcoming Sass deprecations and breaking changes related to @import

### ISSUE THREAD

**Issue by sawyerh** [uswds/uswds#3300]
[In October 2019, Sass released a new module system](https://sass-lang.com/blog/the-module-system-is-launched), introducing `@use` and `@forward` – both of which are likely going to be useful for USWDS. This change also meant that `@import` Sass support will eventually be removed: 

> The Sass team wants to allow for a large amount of time when `@use` and `@import` can coexist, to help the ecosystem smoothly migrate to the new system. However, doing away with `@import` entirely is the ultimate goal for simplicity, performance, and CSS compatibility. As such, we plan to gradually turn down support for `@import` on the following timeline:

> - One year after both Dart Sass and LibSass have launched support for the module system or two years after Dart Sass launches support for the module system, whichever comes sooner (1 October 2021 at latest), we will deprecate `@import` as well as global core library function calls that could be made through modules.

> - One year after this deprecation goes into effect (1 October 2022 at latest), we will drop support for `@import` and most global functions entirely. This will involve a major version release for all implementations.

> This means that there will be at least two full years when `@import` and `@use` are both usable at once, and likely closer to three years in practice.

**Comment by mejiaj** [comment]
Related to #3138

**Comment by thisisdano** [comment]
Right now, we can't move on to the the module system since so much of our userbase uses systems like jekyll that do not support it easily. We'll revisit in another six months or so.
