### ISSUE TITLE
Add card component code

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3301]
[Problem Statement](3148)
[Initial Assumptions and Hypothesis](3149)
[Landscape Analysis](3161)
[Lanscape Analysis of Existing Gov Solutions](3162)

---

[Draft Card Principles](https://github.com/uswds/uswds/wiki/Card-Principles-(Draft))

**Comment by mejiaj** [comment]
Created `feature/USWDS-3301` and started prototyping.

### Basic card
![image](https://user-images.githubusercontent.com/3385219/74366051-e1fa5780-4d94-11ea-9dac-12b03223cbb8.png)

### Raised card
![image](https://user-images.githubusercontent.com/3385219/74366099-f76f8180-4d94-11ea-946c-befa8ae8887e.png)

### Media card
![image](https://user-images.githubusercontent.com/3385219/74366131-08b88e00-4d95-11ea-8cdd-85fde1fb916e.png)

### Icon card
![image](https://user-images.githubusercontent.com/3385219/74367179-0eaf6e80-4d97-11ea-81d9-d9f98d858a67.png)

**Comment by pglevy** [comment]
Looking good, @mejiaj! Some initial thoughts... 

- On the Media Card, there can be weird interplay between the image and the border, both with the variety of contrast you can have and how it looks where the bottom corners of the image sit inside the border. Maybe experiment with an un-bordered image sitting "on top" of the bordered body of the card?
- For the border color, I'm still not sure I completely understand the [success criteria for "non-text contrast" ](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) but something to keep in mind if people are interacting with the card itself (as a control), not just elements contained within the card.
- For the Icon card, I know I've been out of the loop for a bit, but how is that different from a button? 😄 

Is there a code pen or some live example we can play around with?

**Comment by mejiaj** [comment]
@pglevy I'll see about adding this somewhere so you can mess w/ it.

**Comment by mejiaj** [comment]
@pglevy sorry for the wait!

I've created a codedpen for you to edit. It seemed like a darker boarder would be too distracting from the content. These are all a result from some rapid prototyping, so happy to implement any improvements.

For the icon card I thought of 2 situations:
1. When showcasing a feature of a product - breaks the rule of a card must have action
1. When creating an actionable tile

I created it this way to start a discussion as to whether or not a card must be actionable and this as one of those edge cases.

https://codepen.io/mejiaj/pen/RwPrOzr?editors=1100

**Comment by maya** [comment]
Consider providing an option for a row of cards to be the same height (for example: using flexbox). Otherwise, a grid of cards can look uneven.

**Comment by mejiaj** [comment]
@maya , good point. My only concern with that is the client's expectation to have all cards equal height vs just rows.

Here's a small demo we did with cards and different types of content if you're curious
https://codepen.io/mejiaj/pen/abOExZp

**Comment by thisisdano** [comment]
I'll say that a `stretch` alignment option is in my list of considerations for settings/variants.

**Comment by mejiaj** [comment]
Absolutely, some things under consideration:
- Stretch/height
- Border yes/no?
- Border thickness
- Border color?
- Shadow intensity
- Background color
- Font family
- Padding

Happy to hear everyone else's thoughts on "good defaults" 🙂
