### ISSUE TITLE
Leading numbers cause problems in font tokens and display names

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3302]
Given a setting like the following:

```
$theme-typeface-tokens: (
  99-foo: (
    display-name: "99 Foo",
    cap-height: 345px
  ),
  foo-99: (
    display-name: "99 Foo",
    cap-height: 345px
  ),
);
```

The compile process will 1) throw an error when parsing the first key (`99-foo`); and 2) output a `font-family` rule without quotes around the `99 Foo` display name, throwing an error in the browser.

> OK: `font-family: "99 Foo";`

> error: `font-family: 99 Foo;`

**Comment by mejiaj** [comment]
@thisisdano is this still the case? I didn't get an error on the above code.

**Comment by thisisdano** [comment]
Maybe this is no longer an issue since we starting using Dart Sass?
