### ISSUE TITLE
How is the JS connected to the nunjucks files?

### ISSUE THREAD

**Issue by LucasClaude** [uswds/uswds#3305]
I am just wondering how the nunjucks components are connected with their respective js files.

**Comment by mejiaj** [comment]
@LucasClaude , which JS files specifically?

The nunjucks components are fed to fractal, which let's you spin up a local instance of a pattern library.

The JS for USWDS enables the interactive components (like accordion) to function properly. Those components are also tested against the test scripts found in `./spec`

**Comment by LucasClaude** [comment]
@mejiaj For example) the password reset form uses `<a href="javascript:void(0);"
        class="florida-show-multipassword"
        aria-controls="password-reset confirmPassword">Show my typing</a>`
I see that there is a js file for toggling the view portion, but I am wondering how/where the two are connected. I can't seem to find anywhere that the two communicate. Thanks for your help!

**Comment by LucasClaude** [comment]
@mejiaj Any ideas? Thanks again!

**Comment by mejiaj** [comment]
I would say they aren't connected. The components are just samples and bits of code that get fed to documentation. 

`password.js` just depends on the right classes being there.

Please correct me if I'm wrong @thisisdano
