### ISSUE TITLE
Date component is scrollable -- intentional?

### ISSUE THREAD

**Issue by Jacklynn** [uswds/uswds#3310]
## Date component interaction is unexpected

-->

## Description

Our team noticed that the date component can be entered by moving our arrow keys up and down, including into negative digits: 
![date mov (1)](https://user-images.githubusercontent.com/2560618/74369478-495eda00-4d8a-11ea-861c-bf9c1a3c021d.gif)

I would expect it to be a regular text boxes (with validation), but wondered if there were some other considerations I'm not aware of? My screen reader notices it's a "incremental text field" and I wonder if that might be confusing for someone who thinks they have to step increase to their year?

## Steps to reproduce the issue

1. On the date input component (https://designsystem.digital.gov/components/form-controls/)
2. have a field in focus and hit your arrow keys up or down
3. notice that the numbers increase and decrease

**Comment by thisisdano** [comment]
This no longer an issue. We are now using “text” instead of “number” inputs for exactly the reasons you mention
