### ISSUE TITLE
Checked checkbox not showing on first print attempt in Chrome, other browsers?

### ISSUE THREAD

**Issue by mmazanec22** [uswds/uswds#3312]
## Description

When a user prints a page that has a checked checkbox on it, the checkbox appears empty the first time.  When a user prints the same page a second time without refreshing, the checkbox shows up as checked.  This does not happen for other types of input, like radio buttons or text.

## Steps to reproduce the issue

1. Try printing [USWDS form controls](https://designsystem.digital.gov/components/form-controls/#checkbox), observe unchecked checkbox
2. Try printing the same thing a second time, observe checked checkbox

## Additional information

* I got the checkbox to show up on first print in Chrome and FF on Linux only by copying and pasting the USWDS checkbox print styles to our `@media print` section
* It looks like [other people have had this issue elsewhere](https://github.com/gregnb/react-to-print/issues/195) (not with this library)

**Comment by thisisdano** [comment]
Closing this to use https://github.com/uswds/uswds/issues/3137 as the canonical issue for this bug
