### ISSUE TITLE
Add aria-live announcement containers to templates

### ISSUE THREAD

**Issue by sslawrence521** [uswds/uswds#3315]
I am wondering if aria-live announcement containers are inserted at run-time, such as the below?

<div class="visually-hidden" id="polite" aria-live="polite"></div>
<div class="visually-hidden" id="assertive" aria-live="assertive"></div>

**Comment by mejiaj** [comment]
@sslawrence521 , could you provide more detail please?

AFAIK, aria-live is used for situations where we want to notify users content has been changed. Dynamic content, for example.
