### ISSUE TITLE
[﻿﻿Visual Regression]: Screenshots show markup instead of component.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3317]
## Description

Looking through some of the visual regression screenshots in `spec/screenshots` there are screenshots like this:
 
### nav-secondary_large-desktop.png
<img width="919" alt="image" src="https://user-images.githubusercontent.com/3385219/74456411-652ab480-4e4c-11ea-96d7-ba521af03a8e.png">

### nav-primary_large-desktop.png
<img width="978" alt="image" src="https://user-images.githubusercontent.com/3385219/74456487-88556400-4e4c-11ea-96b3-aa3ddad0605d.png">

## Steps to reproduce the issue

1. Run `npm run test:visual:update`
2. Go to `spec/screenshots/`
3. Look at `nav-secondary_large-desktop.png` and `nav-primary_large-desktop.png`

## Additional information [optional]
- This is on the current version v2.4.0
- These components are prefixed with an underscore, which I believe means to hide them in fractal. We should skip these components from generating screenshots if that is the case.

**Comment by thisisdano** [comment]
Let's evaluate this visual regression testing as a part of our CI workstream
