### ISSUE TITLE
Simplify system/code

### ISSUE THREAD

**Issue by sophieschoice** [uswds/uswds#3321]
Hi all,

I just wanted to give some generic feedback on this project. I have used it since the beginning on my own personal projects. For a new version of one of my own projects I decided to use the latest release of the design system.

To be honest it was a bit shocking to conclude that the basic css-file, after deleting things I wont need still measures in at 86 kb minified. At a first glance it seems to be the reworked grid system. That is a whole-a-lotta more code than in version 1. And if I am not mistaken, there is a lot duplicate  too.

Let's look at this:

`@media all and (min-width: 64em) {
.desktop\:grid-col {-webkit-box-flex: 1;-ms-flex: 1 0 0px;flex: 1 0 0; width: auto;max-width: 100%; }
.desktop\:grid-col-fill {-webkit-box-flex: 1;-ms-flex: 1 0 0px;flex: 1 0 0;width: auto;max-width: 100%;}
`

Why using a desktop selector if you sate a minimum width query of 64 em? And both values are the same. Wouldn't it be better to do it as follows?

`@media all and (min-width: 64em) {
    .grid-col, .grid-col-fill {-webkit-box-flex: 1;-ms-flex: 1 0 0px;flex: 1 0 0;width: auto;max-width: 100%;}`

I think the best thing would be for this project is to have a base.css file that defines the grid and basic typgraphy. 
A separate css supplies headers, navigation, side-nav, footer, etc. That would make it much easier to:
1. create a CSS with the only the things you need for your project
2. to give maintainers of the project an easier chance to simplify code per object/component.

I really would hate it to ssee this project go to the bloated, complicated code of Bootstrap and Foundation.

**Comment by thisisdano** [comment]
So, I do agree that we want to give teams a way to include only the CSS they need for their projects and to purge unnecessary CSS in production. We'll be comprehensively addressing modular imports this year. I also agree that the CSS output here is redundant. I set up a new issue to resolve this: https://github.com/uswds/uswds/issues/4032

Regarding the prefixing, these have a `desktop:` prefix as a way to target this behavior at a certain breakpoint. So you could have something like `div.grid-col-1.desktop:grid-col` for an element that's one column wide until `desktop` width, at which point it fills the available space.
