### ISSUE TITLE
Use of <h3> on text in the footer

### ISSUE THREAD

**Issue by sslawrence521** [uswds/uswds#3325]
Hello. I am wondering about your use `<h3>` on Name of Agency and Agency Contact Center in the footer of the layout example here: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.5.0/components/preview/layout--landing.html. My understanding is a heading tag should not be used for formatting only. It should always be an actual heading for the content that follows, i.e., if no content follows, it’s not a heading. Has the world moved on and left me behind again? ;)

**Comment by thisisdano** [comment]
Nope, you're right! We changed this to a `p` in `2.10.1`.
