### ISSUE TITLE
Create templates for common, required pages

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds#3330]
Capturing this feedback from a Federal Web Council member:

It would be useful to have templates for common, required pages on federal executive branch websites, such as the About Page, /open, /digitalstrategy, etc.

See [Required Web Content and Links](https://digital.gov/resources/required-web-content-and-links/) and the [Checklist of Requirements for Federal Websites and Digital Services](https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/) on Digital.gov for common, required content and links.

**Comment by thisisdano** [comment]
Closing since this is not on our current roadmap, but added an `under consideration` label so we can reevaluate in the future.
