### ISSUE TITLE
Generating Multiple Themes

### ISSUE THREAD

**Issue by evanmac123** [uswds/uswds#3331]
#3078  Description

We are working on the California Judicial Court system and using USWDS and Pattern lab to build out components that will be used across multiple websites. We were hoping to have the ability to generate/pick from multiple "themes" that reflect different CSS styling but share the same underlying twig and yml structures. 

We were looking to have a single class in the body tag dictate which styles to use with basic functionality on the front end looking something like this.
https://bradfrost.com/blog/post/creating-themeable-design-systems/

We have run into a roadblock due to the token system generating a centralized css off of the primary tokens imported in the global.scss. We would love to know if you have any suggestions on this or if you know anyone that has implemented similar functionality that would allow us to generate multiple themed versions that could be switchable on the front end.

**Comment by thisisdano** [comment]
Do you need to be able to switch themes on-the-fly? If not, could each of the themes use their own CSS file? Like having three different Sass entry points and three sets of themed settings. The project could then determine which CSS file to attach to their project.

`uswds-theme-A.scss` → `settings-A` → `custom-A.scss` → `CSS-theme-A.css`
`uswds-theme-B.scss` → `settings-B` → `custom-B.scss` →  `CSS-theme-B.css`
`uswds-theme-C.scss` → `settings-C` → `custom-C.scss` →  `CSS-theme-C.css`

I understand that this is not incredibly elegant! But it would provide multiple, somewhat switchable themes that would work with the same markup. A more elegant solution for a future could be version of USWDS that uses something like CSS custom properties, which could then be redefined on the fly, but that (obviously) does not yet exist. 

This was just my first thought though! There is probably a better option I've not yet considered.

**Comment by robertromore** [comment]
@thisisdano I am also interested in this functionality. I've created a [WIP branch](https://github.com/robertromore/uswds/pull/1) in my own fork that allows the usage of[ CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) for colors. With this, you can define something like the following in a separate stylesheet to override colors:
```scss
:root {
  --theme-color-primary-darker: #49dafe;
}
```
Which results in something approximately like:
```css
.usa-banner__button:hover {
  color: #49dafe;
  color: var(--theme-color-primary-darker, var(--theme-color-blue-warm-80v, #162e51));
}
```
The biggest drawback to this approach I can see is that it is unsupported in Internet Explorer.

**Comment by thisisdano** [comment]
I think there's a future state of USWDS that uses custom properties, and we may get to this is future work. But I am closing this as it's not on our current roadmap. Tagging it for future consideration.
