### ISSUE TITLE
[ci] - Remove Snyk scan on deploy.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3338]
## Description

Snyk scan is already run on build. We should remove the scan in `config.yml` so it doesn't run again on deploy.

Snyk failed on release-2.5.1 when it had already passed previously.
https://circleci.com/gh/uswds/uswds/4605#build-parameters/containers/0

**Comment by mejiaj** [comment]
@thisisdano  #3366 fixes this right?

**Comment by thisisdano** [comment]
Yup, fixed.
