### ISSUE TITLE
Add component and guidance for archived content

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds#3340]
## Description

Add a new component and guidance to flag content as archived. Some sites include a banner block above the page content saying `This page has been archived, etc. etc.`.

Currently, the only opinion in USWDS is that such a page should exist in the service of the `Promoting continuity` design principle.

## Additional information

* See, for example, https://obamawhitehouse.archives.gov/, https://2009-2017.state.gov/, and https://2014-2017.commerce.gov/.

cc: @dawnpm

**Comment by thisisdano** [comment]
Closing since this is not on our [current roadmap](https://designsystem.digital.gov/about/product-roadmap/). Tagged for future consideration.
