### ISSUE TITLE
Add basic install instructions for Angular

### ISSUE THREAD

**Issue by wilsonmichaelc** [uswds/uswds#3341]
1. npm install --save uswds@latest
2. add "node_modules/uswds/dist/css/uswds.min.css" to the "styles" section of angular.json
3. add "node_modules/uswds/dist/js/uswds.min.js" to the "scripts" section of angular.json

**Comment by mkmurali** [comment]
May need to include fonts and img folders as well to assets.
```
            "assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "*",
                "input": "node_modules/uswds/dist/fonts",
                "output": "assets/fonts/"
              },
              {
                "glob": "*",
                "input": "node_modules/uswds/dist/img",
                "output": "assets/img/"
              }
            ],
            "styles": [
              "node_modules/uswds/dist/css/uswds.min.css",
              "src/styles.css"
            ],
            "scripts": ["node_modules/uswds/dist/js/uswds.min.js"]
```

**Comment by mkmurali** [comment]
You may checkout for full working sample here: https://github.com/softrams/uswds-angular-starter Planning to add more tighter integration with additional components.

**Comment by rahuldongre-us** [comment]
Another angular users sample for reference.
https://github.com/wasatchinfotech/angular-uswds-starter-project

**Comment by ajanickiv** [comment]
It would be great is these instructions also included how to access the uswds component JS functions in an Angular app. `on`, `off`, `init`, etc as detailed in the JS customization section found here https://designsystem.digital.gov/documentation/developers/

**Comment by rahuldongre-us** [comment]
You can achieve this with angular component and life cycle methods.

Here is link : 

https://github.com/wasatchinfotech/angular-uswds-starter-project/tree/master/src/app/shared/components/base-card

Refer as child component in parent class

https://github.com/wasatchinfotech/angular-uswds-starter-project/blob/master/src/app/landing/landing.component.html

Click on `Toggle Card Visibility` button

`<div class="grid-row flex-row">
                <div class="grid-col"><button (click)="toggleCard()" class="usa-button usa-button--outline">Toggle Card
                        Visibility</button></div>
                <div class="grid-col">
                    <app-base-card #landingCard [isHidden]="false"></app-base-card>
                </div>
            </div>`

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/17654466/84839216-870a9280-b00a-11ea-8959-656a1c03b636.png">

**Comment by jpaulinog** [comment]
> It would be great is these instructions also included how to access the uswds component JS functions in an Angular app. `on`, `off`, `init`, etc as detailed in the JS customization section found here https://designsystem.digital.gov/documentation/developers/

I also need to re initialize the the uswds a component JS function when the dom is ready, specifically the accordions. How I can achieve this?

**Comment by ajanickiv** [comment]
This is how we accomplished that (I doubt this is the expected way, but this is what we could get to to work)
Import the JavaScript file into the Angular component
`import * as comboBox from '../../../../../../node_modules/uswds/src/js/components/combo-box';`
Add the USWDS component to the component template's with a boolean switch
```
            <div class="grid-col" *ngIf="showComboBox">
                Sample combo Box
                <div class="usa-combo-box">
                    <select class="usa-select usa-combo-box__select" name="fruit" id="fruit" required>
                        <option value>Select a fruit</option>
                        <option value="apple">Apple</option>
                        <option value="banana">Banana</option>
                        <option value="watermelon">Watermelon</option>
                    </select>
                </div>
            </div>
```
Default the DOM switch to false
In the ngAfterViewInit, turn the switch on and call the init method - both wrapped in timeouts
```
    ngAfterViewInit() {
        this.changeDetectorRef.detectChanges();
        setTimeout(() => {
            this.showComboBox = true;
        }, 50);
        setTimeout(() => {
            comboBox.init(document);
        }, 500);
    }
```

**Comment by diego-ruiz-rei** [comment]
Has anyone gotten more complex form components like the date picker working with Angular forms? I'm only getting empty values when submitting the form

**Comment by mejiaj** [comment]
@thisisdano we already have guidance at the bottom of the [JS customization section in guidance](https://designsystem.digital.gov/documentation/developers/#js-customization). Is this issue still valid?
