### ISSUE TITLE
Create a character limit component.

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3349]
## User Story

As a front-end developer, I need a way to help users know how much text they can enter upfront when there is a limit on the number of characters.

## Examples
* [GOV.UK](https://design-system.service.gov.uk/components/character-count/)
* [Shopify](https://polaris.shopify.com/components/forms/text-field) *(set 'showCharacterCount' to true)*
* [Material](https://material.io/components/text-fields/#anatomy) *(in 'Assistive elements' - 'Character counter')*

## Checklist
- [x] Create low-fidelity design
- [x] Review & discuss low-fi design (designer + developers)
- [X] SKIPPED Get user feedback on low-fi designs (optional - if team feels is needed)
- [ ] Code
- [ ] Conduct usability test with working code (optional - if team feels is needed)

**Comment by Ben-Judy-Flexion** [comment]
**Design:**
![Character limit (wireframes) State 1_ default](https://user-images.githubusercontent.com/56978395/76870425-ae996580-6837-11ea-8de2-01143095f35a.png)
![Character limit (wireframes) State 2_ typing - under character limit](https://user-images.githubusercontent.com/56978395/76870426-af31fc00-6837-11ea-92c0-eb9e6b644ff0.png)
![Character limit (wireframes) State 3_ typing - close to character limit](https://user-images.githubusercontent.com/56978395/76870428-af31fc00-6837-11ea-9073-142dfed7cd92.png)
![Character limit (wireframes) State 4_ typing - at character limit](https://user-images.githubusercontent.com/56978395/76870429-afca9280-6837-11ea-8f4c-a7c9865f59bf.png)

**_Figma source for design:_**
https://www.figma.com/file/jLPd8N0c0BHH6Bd3vFDFaw/Form-Component-Wireframes?node-id=0%3A1

**Comment by wbyoko** [comment]
@Ben-Judy-Flexion should there be a comment at every empty state? or should there be a message?

**Comment by Ben-Judy-Flexion** [comment]
Great question, @wbyoko. I updated the design to include guidance around this. Let me know what you think. (Let's iterate on this together if you think there is a better approach.)

Also, I found this article helpful:
http://www.breck-mckye.com/blog/2012/05/character-count-design-some-guidelines/

**Comment by jaredcunha** [comment]
If you want to follow GDS, they do bold red only after you pass the limit. The bold works so it's not a color only indicator. 

<img width="778" alt="Screen Shot 2020-03-19 at 1 59 08 PM" src="https://user-images.githubusercontent.com/1094951/77099217-f829b200-69e9-11ea-85b8-e1a96e0c50e3.png">

<img width="781" alt="Screen Shot 2020-03-19 at 1 59 23 PM" src="https://user-images.githubusercontent.com/1094951/77099233-fd86fc80-69e9-11ea-90d5-e33a9d82d2f3.png">

<img width="785" alt="Screen Shot 2020-03-19 at 1 59 29 PM" src="https://user-images.githubusercontent.com/1094951/77099243-024bb080-69ea-11ea-9488-1e72f7edd8ea.png">

**Comment by Ben-Judy-Flexion** [comment]
Updated the design to reflect our collective decision that the character limit message should appear at all times, even before the user has placed focus on the form field or entered text.

**Comment by Ben-Judy-Flexion** [comment]
I updated the design again to address @jaredcunha's comment about the font styling for the character count message. I made it more like GDS, but with a twist: when the user has 10 or fewer characters before they reach the limit, the message is **bold**. Let me know what you think of this.

**Comment by wbyoko** [comment]
@Ben-Judy-Flexion Should 0 characters be red when it's not a validation error?

**Comment by jaredcunha** [comment]
@wbyoko No. The case of 0 characters remaining is still within the limit and permissible. We should not update the styling until the threshold is passed.

**Comment by wbyoko** [comment]
@jaredcunha, that's what I was expecting. @Ben-Judy-Flexion could you update the design to reflect that?

**Comment by Ben-Judy-Flexion** [comment]
It's a question of styling inline messages within a form (e.g. immediately under or adjacent to form elements.) There is no established pattern for this in USWDS, yet. I'm in agreement that it probably shouldn't be red, but I advocate for some styling that draws attention to the message when the user approaches the limit, and increased attention when they reach the limit.
I like how Stack Exchange does it. As the number of characters grows, the message gradually changes color until it finally turns red.
see: http://www.breck-mckye.com/blog/2012/05/character-count-design-some-guidelines/

**Comment by jaredcunha** [comment]
@Ben-Judy-Flexion I do wonder if the secondary styling could cause some confusion. The subtle color changing may not be perceived or misleading users with color blindness. Here's the research GDS completed on their component:

https://github.com/alphagov/govuk-design-system/wiki/Character-count-testing-and-user-research

>Some users only acknowledged the character count after they had gone past the set limit or when an error message prompted them after they clicked 'continue'. However, both groups were able to amend the amount of characters they had put in and continue with the task.

> We feel this is acceptable, as drawing too much attention to the component may actually distract users from completing their primary task.

**Comment by Ben-Judy-Flexion** [comment]
I don't understand what could possibly be confusing about text color changing for any users. As for colorblind users, it's irrelevant if they can't see it.
I have no problem doing things exactly like GDS -- clearly they've done the research and design iteration to get somewhere good. "Good artists copy, great artists steal." But (and I only ask this as a practical question) then do we need to create design artifacts at all? I have no interest in essentially re-creating a good design that already exists in the world, just to check the 'design' box in our efforts.

**Comment by jaredcunha** [comment]
I think it's more the shift from a warning state to an error state that might not be as noticeable. There's also the transition from normal weight to bold. But I also read into the second quote where drawing too much attention to the component could distract users from their task.

**Comment by Ben-Judy-Flexion** [comment]
Fair points, all. How do we feel about checking the Wireframes/Design box in the checklist? Or do we need further exploration & iteration?

**Comment by jaredcunha** [comment]
I don't think this one needs as much iteration, as far as the artifacts go.

**Comment by jaredcunha** [comment]
I think this is why i thinking it's also worth making the text bold after the character limit is surpassed… the warning state is triggered after the first character is entered, which as a user, I would find distracting. 
![Screen Recording 2020-03-23 at 02 28 PM](https://user-images.githubusercontent.com/1094951/77350269-9bdcd000-6d12-11ea-8daa-a63d5003d702.gif)

**Comment by Ben-Judy-Flexion** [comment]
Moved back to "Doing" column on our Project board, as all Checklist items are not ready for review.

**Comment by jonadecker** [comment]
Keep in mind, too, that color change may be perceivable (user _can_  see a change) but not necessarily informative  to users with color vision deficits, which may cause confusion. There are many variations of color blindness so we can't assume a change in color is not perceivable. It just may not be perceived in the way you expect.

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds/pull/3370
Released in https://github.com/uswds/uswds/releases/tag/v2.7.0
