### ISSUE TITLE
Provide updated guidance for numeric fields.

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3350]
## User Story

As a front-end developer, I need to know how to implement numeric form fields in a way that is functional and accessible.

## References

* [GOV.UK current guidance](https://design-system.service.gov.uk/components/text-input/#numbers)
* [GOV.UK research/blog post](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/)

## Checklist
- [x] Wireframes/Design
- [x] Documentation
- [x] Code
- [x] Design assets

**Comment by jaredcunha** [comment]
I have a pull request on this.
https://github.com/uswds/uswds/pull/3354

@thisisdano Would love your thoughts on removing the `min` and `max` validation, which is something that is sacrificed by switching to `text`. GDS seems to be okay without it, but what do you think?

**Comment by thisisdano** [comment]
I am comfortable with this. The justification in https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/ is pretty conclusive imo. I also agree that it's ok to lose the the min/max validation — the `max` validation in the date field has been a problem anyway since it requires a manual increment every year to stay up-to-date — and min/max is a pretty crude validation anyway.

I think the site _will_ need some updated guidance, in addition to the release notes and a callout in a monthly call.

**Comment by thisisdano** [comment]
For the year field, it _might_ be useful to do something like a 4 char pattern if we want to encourage full dates

**Comment by jaredcunha** [comment]
That is currently captured in form hint. Were you thinking of a modification?

<img width="567" alt="Screen Shot 2020-03-20 at 12 46 59 PM" src="https://user-images.githubusercontent.com/1094951/77186232-f672f380-6aa8-11ea-9ea6-a334e833d468.png">

**Comment by thisisdano** [comment]
Possibly? I guess I was thinking that if we're removing the min/max validation, is there any simple kind of guardrail we can add the the field? I don't feel strongly that it needs to be there, but curious.

**Comment by jaredcunha** [comment]
@thisisdano oh, gotcha! Yeah, you can use `minlength="4"` and `maxlength="4"`

**Comment by jaredcunha** [comment]
Pull request on documentation site: https://github.com/uswds/uswds-site/pull/890

**Comment by thisisdano** [comment]
Let's remove the leading `0` from the hint text. I think it creates an unnecessary implication that the field requires it: `For example: 04 28 1986` → `For example: 4 28 1986`

Any reason we shouldn't do this?

**Comment by jaredcunha** [comment]
@thisisdano updated: https://github.com/uswds/uswds/pull/3371/commits/c2ebaa3ed14a13dda36e7336f03ab25d25c0a9ae

**Comment by jaredcunha** [comment]
Also, @thisisdano if that commit looks good and the PR on `uswds` is approved, should I just go ahead and merge it?
