### ISSUE TITLE
Create a combo box component. 

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3352]
## User Story

As a front-end developer, I need a way to help users select an item from a large collection of options in a way that is compact, convenient, and accessible.

## Functional Examples
* GOV.UK accessible-autocomplete [repo](https://github.com/alphagov/accessible-autocomplete) - [example](https://alphagov.github.io/accessible-autocomplete/examples/)
* [Lightning](https://www.lightningdesignsystem.com/components/combobox/)
* [Shopify](https://polaris.shopify.com/components/forms/autocomplete#navigation)

## References
* [Building an accessible autocomplete control - Adam Silver - 02/02/2020](https://adamsilver.io/articles/building-an-accessible-autocomplete-control/)
* [What we learned from getting our autocomplete tested for accessibility - GOV.UK - 05/15/2018](https://accessibility.blog.gov.uk/2018/05/15/what-we-learned-from-getting-our-autocomplete-tested-for-accessibility/)

## Checklist
- [x] Create low-fidelity design
- [x] Review & discuss low-fi design (designer + developers)
- [x] SKIPPED - Get user feedback on low-fi designs (optional - if team feels is needed)
- [ ] Code
- [ ] Conduct usability test with working code

**Comment by Ben-Judy-Flexion** [comment]
**Design:**
![Combo box (wireframes) State 1_ default](https://user-images.githubusercontent.com/56978395/76870966-75152a00-6838-11ea-8aa2-43217696232b.png)
![Combo box (wireframes) State 2_ typing in text field](https://user-images.githubusercontent.com/56978395/76870967-75152a00-6838-11ea-91eb-2c714f34f059.png)
![Combo box (wireframes) State 3_ hover or focus on list item](https://user-images.githubusercontent.com/56978395/76870969-75adc080-6838-11ea-904d-8f9ea9aca71e.png)

**_Figma source for design:_**
https://www.figma.com/file/jLPd8N0c0BHH6Bd3vFDFaw/Form-Component-Wireframes?node-id=0%3A1

**Comment by Ben-Judy-Flexion** [comment]
We discussed usability testing (or other forms of user feedback on the design) and decided combo box might be the right component to start with, so I'm posting these thoughts here.

I suggest we take a case-by-case approach to determine what testing is appropriate, per component. No need for a blanket, one size fits all approach.

I added two boxes to the Checklist for this Issue:
- [ ] Get user feedback on low-fi designs (optional - if team feels is needed)
- [ ] Conduct usability test with working code (optional - if team feels is needed)

We can either get user feedback early using design prototypes (no code), or with working code. Thus two steps in the process. Testing with design, we can cheaply and quickly compare feedback on multiple, alternate designs that are significantly different. Testing with working code, we can get more fine-grained feedback on little nuances of the interactions and implementation.

As indicated, they are both optional steps. I suggest we have a quick team discussion for each component and ask these questions:

- **How** necessary is usability testing/user input for us to confidently publish a highly usable and accessible component? (Some very basic components that are well established online will likely require no testing with users. Others may require comprehensive testing.)
- **Who** are the test participants?
- **When** will the test take place? (Meaning, at what point in our design-dev process, as explained above.)
- **Where** will the test take place? (In these COVID-19 days, obviously online. But using which [methods](https://xd.adobe.com/ideas/process/user-testing/top-7-usability-testing-methods/) and [tools](https://usabilitygeek.com/8-usability-testing-tools-when-on-a-budget/)?
- **How** will we analyize the results? (It's all well and good to conduct testing, but how will we know what we have learned?)

**Comment by Ben-Judy-Flexion** [comment]
Team, I'm checking the "Review & discuss low-fi design" box. William and I discussed different aspects of this component yesterday and I feel like we're in alignment on the finer points of the design.
I'm also marking the "Get user feedback on low-fi designs" checklist item as "Skipped." I don't feel it's necessary for this component -- but please share if you feel otherwise.
