### ISSUE TITLE
Create a date picker component. 

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3355]
## User Story

As a front-end developer, I need a way to help users select a single date in a way that is compact, functional, and accessible.

## Examples
* [USPTO](https://uspto.github.io/designpatterns/1.x/docs/components/formControls.html#date-picker)
* [Mercury](https://www.canadapost.ca/cpc/en/designsystem/mercury/components/combinations/date-picker.page?)
* [Shopify](https://polaris.shopify.com/components/forms/date-picker#navigation)
* [Atlassian](https://atlaskit.atlassian.com/packages/core/datetime-picker)
* [Carbon](https://www.carbondesignsystem.com/components/date-picker/code/)

## Reference
* [A New Day: Making a Better Calendar - Gerard Cohen - 12/05/2018](https://www.24a11y.com/2018/a-new-day-making-a-better-calendar/)

## Checklist
- [ ] Create low-fidelity design
- [ ] Review & discuss low-fi design (designer + developers)
- [ ] Get user feedback on low-fi designs (optional - if team feels is needed)
- [ ] Code
- [ ] Accessibility validation
- [ ] Conduct usability test with working code
- [ ] Create hi-fi design assets (Adobe XD, Sketch, Figma)
- [ ] Review & approve hi-fi design assets

**Comment by Ben-Judy-Flexion** [comment]
**Design:**
_The following design should be considered "low fidelity" -- not matching the visual style of USWDS. Let @Ben-Judy-Flexion know if high fidelity designs are needed._
![Single date picker (wireframe) State 1_ default](https://user-images.githubusercontent.com/56978395/76871789-801c8a00-6839-11ea-8f3c-d9b31e6502a6.png)
![Single date picker (wireframe) State 2_ focus on input field](https://user-images.githubusercontent.com/56978395/76871791-80b52080-6839-11ea-9d35-03feec6d4011.png)
![Single date picker (wireframe) State 3_ hover on month](https://user-images.githubusercontent.com/56978395/76871793-80b52080-6839-11ea-92ae-aef4b1414858.png)
![Single date picker (wireframe) State 4_ select month](https://user-images.githubusercontent.com/56978395/76871794-814db700-6839-11ea-94fa-efb5be432e3d.png)
![Single date picker (wireframe) State 5_ hover on year](https://user-images.githubusercontent.com/56978395/76871797-814db700-6839-11ea-9698-72fef973cd8d.png)
![Single date picker (wireframe) State 6_ select year](https://user-images.githubusercontent.com/56978395/76871798-81e64d80-6839-11ea-8a5b-946fa804ec54.png)

**_Figma source for design:_**
https://www.figma.com/file/jLPd8N0c0BHH6Bd3vFDFaw/Form-Component-Wireframes?node-id=0%3A1

**Comment by Ben-Judy-Flexion** [comment]
I updated the low-fi design to reflect a few things @wbyoko and I talked about:
- separating the calendar icon from the input field
- using a double arrow for changing the year, single arrow to change the month
