### ISSUE TITLE
Create a tooltip component. 

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3356]
## User Story

As a front-end developer, I need a way to show users additional, optional information on demand in a way that is accessible.

## Examples
* [USPTO](https://uspto.github.io/designpatterns/1.x/docs/components/tooltips.html)
* [Certify](https://ussba.github.io/certify-design-system-documentation/components/tooltips.html)
* [Mercury](https://www.canadapost.ca/cpc/en/designsystem/mercury/components/elements/tooltip.page)

## Reference
* [Building a fully-accessible help tooltip - Sara Soueidan - 01/24/2017](https://www.sarasoueidan.com/blog/accessible-tooltips/)
* [Tooltips & Toggletips - Inclusive Components - 07/25/2017](https://inclusive-components.design/tooltips-toggletips/)

## Checklist
- [x] Create low-fidelity design
- [x] Review & discuss low-fi design (designer + developers)
- [x] Get user feedback on low-fi designs (optional - if team feels is needed)
- [x] Code
- [x] Conduct usability test with working code (optional - if team feels is needed)
- [x] Create hi-fi design assets (Adobe XD, Sketch, Figma)
- [x] Review & approve hi-fi design assets
- [ ] Publish design assets (update downloadable files for Adobe XD, Sketch, Figma)

**Comment by Ben-Judy-Flexion** [comment]
**Design:**
_The following design should be considered "low fidelity" -- not matching the visual style of USWDS. Let @Ben-Judy-Flexion know if high fidelity designs are needed._
![Tooltips (wireframes) State 1_ default (question mark image)](https://user-images.githubusercontent.com/56978395/76872484-79dadd80-683a-11ea-8a42-b8ebb6ad0dab.png)
![Tooltips (wireframes) State 2_ hover on image](https://user-images.githubusercontent.com/56978395/76872486-7a737400-683a-11ea-89c6-0b47517b1d86.png)
![Tooltips (wireframes) State 3_ default (underlined text)](https://user-images.githubusercontent.com/56978395/76872487-7a737400-683a-11ea-80e2-3340defac952.png)
![Tooltips (wireframes) State 4_ hover on text](https://user-images.githubusercontent.com/56978395/76872488-7b0c0a80-683a-11ea-9a30-d834d3e0d9a3.png)

**_Figma source for design:_**
https://www.figma.com/file/jLPd8N0c0BHH6Bd3vFDFaw/Form-Component-Wireframes?node-id=0%3A1

**Comment by jaredcunha** [comment]
Basic guidance and principles for tooltips:

- Only use tooltips on focusable elements, such as `<a>` and `<button>`. Never use on `<span>` or `<div>`. 
- Tooltips are displayed on hover or focus
- Tooltip triggers will be set to `nowrap`
- Tooltip text is placed inside a `title` attribute, so they will still function without javascript.
- Tool positioning will be determined by `data-`attributes. By default, it will appear on top of of the trigger.
- Tooltips should only provide short, helpful nuggets of info such as definitions. If the information is critical to the user, that information should not be hidden from view.
- Should be used when buttons are only an icon

Because tooltips occur on hover or focus, they may not contain interactive content such as links and buttons.

**Comment by Ben-Judy-Flexion** [comment]
Good start to the guidance, I like these.
Might be helpful to explain the "why" behind a few. Triggers set to nowrap, got it -- but help me understand why that is the case, so I can think more critically about how to use tooltips.

**Comment by jaredcunha** [comment]
@Ben-Judy-Flexion I was going to add that for the tooltip page on USWDS. The reason is that when the tooltip trigger wraps, positioning the tooltip becomes awkward because it has to find a center (either horizontal or vertical) that is now less apparent.

**Comment by jaredcunha** [comment]
I'm going to take the one written for Certify: https://ussba.github.io/certify-design-system-documentation/components/tooltips.html

I'll make several changes:
- Refactor the JS
- Add positioning options: top(default)/right/bottom/left. It will always be centered
- Make the tooltip background darker, probably using the base color.

**Comment by jaredcunha** [comment]
Tooltip supports these accessibility principles: 
https://www.accede-web.com/en/guidelines/rich-interface-components/tooltips-aria/
