### ISSUE TITLE
Create a date range picker component. 

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3357]
## User Story

As a front-end developer, I need a way to help users select a date range in a way that is compact, functional, and accessible.

## Examples
* [USPTO](https://uspto.github.io/designpatterns/1.x/docs/components/formControls.html#date-picker)
* [Mercury](https://www.canadapost.ca/cpc/en/designsystem/mercury/components/combinations/date-picker.page?)

## Reference
* [Designing The Perfect Date And Time Picker - Vitaly Friedman - 07/05/2017](https://www.smashingmagazine.com/2017/07/designing-perfect-date-time-picker/)

## Checklist
- [ ] Create low-fidelity design
- [ ] Review & discuss low-fi design (designer + developers)
- [ ] Get user feedback on low-fi designs (optional - if team feels is needed)
- [ ] Code
- [ ] Conduct usability test with working code (optional - if team feels is needed)
- [ ] Create hi-fi design assets (Adobe XD, Sketch, Figma)
- [ ] Review & approve hi-fi design assets
- [ ] Publish design assets (update downloadable files for Adobe XD, Sketch, Figma)

**Comment by Ben-Judy-Flexion** [comment]
**Design:**
_The following design should be considered "low fidelity" -- not matching the visual style of USWDS. Let @Ben-Judy-Flexion know if high fidelity designs are needed._
![Range date picker (wireframe) State 1_ default](https://user-images.githubusercontent.com/56978395/76872677-bdcde280-683a-11ea-8d94-74e3200b0759.png)
![Range date picker (wireframe) State 2_ focus on start field](https://user-images.githubusercontent.com/56978395/76872678-bdcde280-683a-11ea-8aa9-0c0826e7da24.png)
![Range date picker (wireframe) State 3_ hover over start date](https://user-images.githubusercontent.com/56978395/76872681-be667900-683a-11ea-88a2-f0af50d1b882.png)
![Range date picker (wireframe) State 4_ Start date selected (auto focus on end date field)](https://user-images.githubusercontent.com/56978395/76872682-beff0f80-683a-11ea-95dc-5b3584b471f4.png)
![Range date picker (wireframe) State 5_ Hover over end date](https://user-images.githubusercontent.com/56978395/76872684-beff0f80-683a-11ea-9ff0-e3ac1e784099.png)
![Range date picker (wireframe) State 6_ End date selected](https://user-images.githubusercontent.com/56978395/76872689-bf97a600-683a-11ea-9313-c6cfa7b3ce6c.png)

**_Figma source for design:_**
https://www.figma.com/file/jLPd8N0c0BHH6Bd3vFDFaw/Form-Component-Wireframes?node-id=0%3A1
