### ISSUE TITLE
Create a time picker component. 

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3358]
## User Story

As a front-end developer, I need a way to help users select a time in a way that is compact, functional, and accessible.

## Examples
* [USPTO](https://uspto.github.io/designpatterns/1.x/docs/components/formControls.html#time-picker)
* [Lightning](https://www.lightningdesignsystem.com/components/timepicker/)

## Reference
* [Designing The Perfect Date And Time Picker - Vitaly Friedman - 07/05/2017](https://www.smashingmagazine.com/2017/07/designing-perfect-date-time-picker/)

## Checklist
- [ ] Create low-fidelity design
- [ ] Review & discuss low-fi design (designer + developers)
- [ ] Get user feedback on low-fi designs (optional - if team feels is needed)
- [ ] Code
- [ ] Conduct usability test with working code (optional - if team feels is needed)
- [ ] Create hi-fi design assets (Adobe XD, Sketch, Figma)
- [ ] Review & approve hi-fi design assets
- [ ] Publish design assets (update downloadable files for Adobe XD, Sketch, Figma)

**Comment by Ben-Judy-Flexion** [comment]
**Design:**
_The following design should be considered "low fidelity" -- not matching the visual style of USWDS. Let @Ben-Judy-Flexion know if high fidelity designs are needed._
![Time picker (wireframe) State 1_ default](https://user-images.githubusercontent.com/56978395/76872820-eb1a9080-683a-11ea-8a6d-bd175a7fc113.png)
![Time picker (wireframe) State 2_ invalid time](https://user-images.githubusercontent.com/56978395/76872821-eb1a9080-683a-11ea-80bc-bacec195c061.png)

**_Figma source for design:_**
https://www.figma.com/file/jLPd8N0c0BHH6Bd3vFDFaw/Form-Component-Wireframes?node-id=0%3A1
