### ISSUE TITLE
Create a document upload component.

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3360]
## User Story
As a front-end developer, I need a way to help users select a file in a way that is compact, convenient, and accessible.

## Examples
* [Carbon](https://www.carbondesignsystem.com/components/file-uploader/code/)
* [Lightning](https://www.lightningdesignsystem.com/components/file-selector/)

## Checklist
- [x] Create low-fidelity design
- [x] Review & discuss low-fi design (designer + developers)
- [x] Get user feedback on low-fi designs (optional - if team feels is needed)
- [x] Code
- [x] Conduct usability test with working code (optional - if team feels is needed)
- [x] Create hi-fi design assets (Adobe XD, Sketch, Figma)
- [x] Review & approve hi-fi design assets
- [x] Publish design assets (update downloadable files for Adobe XD, Sketch, Figma)

**Comment by Ben-Judy-Flexion** [comment]
**Design:**
_The following design should be considered "low fidelity" -- not matching the visual style of USWDS. Let @Ben-Judy-Flexion know if high fidelity designs are needed._
![Document upload (wireframes) State 1_ default](https://user-images.githubusercontent.com/56978395/76873528-dbe81280-683b-11ea-9e4e-1219a8fecd44.png)
![Document upload (wireframes) State 2_ add file](https://user-images.githubusercontent.com/56978395/76873529-dbe81280-683b-11ea-8b56-88105d3287fe.png)
![Document upload (wireframes) State 3_ confirmation](https://user-images.githubusercontent.com/56978395/76873531-dc80a900-683b-11ea-9476-cdd8d872dd5e.png)

**_Figma source for design:_**
https://www.figma.com/file/jLPd8N0c0BHH6Bd3vFDFaw/Form-Component-Wireframes?node-id=0%3A1

**Comment by jaredcunha** [comment]
@thisisdano I'm about to start working on this component. Before we start modeling this component, I'd like to get an idea of what degree of complexity you prefer. We can build some simliar to [Polaris Drop Zone](https://polaris.shopify.com/components/actions/drop-zone), which has a richer interaction to

**Comment by thisisdano** [comment]
There are certainly similarities to the interaction in those two examples. Looks like they both have a drop target and an upload button. The Polaris example has (to my mind) a more intuitive UI, though perhaps it's too "big" for our most common use cases. That said, what _are_ our most common use cases?

We'll learn as we test, but I'm inclined toward a larger drop zone, but I don't think it needs to big as the Polaris zone, and I don't think it _necessarily_ needs non-drop hover effects. (But it should have an "active" state when a valid file is dragged over it.) Something like a combination between Polaris and Shopify could look something like the GitHub binary uploader for releases:

<img width="774" alt="Screen Shot 2020-04-07 at 10 46 29 AM" src="https://user-images.githubusercontent.com/11464021/78702329-40d3dd00-78bd-11ea-8ef0-ed2eb6a66324.png">

I think GH is missing a clear upload button/link in theirs, but the size is OK.

And yes, it doesn't need to do the actual uploading, as you say.

**Comment by kellular** [comment]
Hello! I'm a designer working at Nava PBC. My team recently built and shipped a website for the State of Vermont that allows Vermonters to upload required documents for state benefits like SNAP. In case it's helpful for tackling this component, I wanted to share a GIF of the upload functionality we built: 

![upload-flow](https://user-images.githubusercontent.com/12240896/82345102-ddac8e80-99c2-11ea-81ce-c40588429149.gif)

**Comment by Ben-Judy-Flexion** [comment]
Community feedback request doc for this component:
https://docs.google.com/document/d/1ehXwzfzyYYlJf9pMpu3kDEMnFJMpZvWWV23PMXtGs20/edit

**Comment by Ben-Judy-Flexion** [comment]
@jaredcunha re: color change on :hover for the file upload background:
Why don't we do something in the [Blue](https://designsystem.digital.gov/design-tokens/color/system-tokens/#blue) palette?
How about blue-10 (#d9e8f6)?

I'm recommending @wbyoko  use blue-50 (#2378c3) for the date picker [calendar icon](https://github.com/uswds/uswds/issues/3355), so the :hover color changes would be shades of the same blue color family.

Would look a little something like this:
![image](https://user-images.githubusercontent.com/56978395/83292043-0f85d800-a1af-11ea-91ee-24b07dba861e.png)

I think it's a relatively subtle color change that should be considered a pleasant enhancement for sighted users who can see it, not core functionality that needs full consideration for accessibility -- but let me know if you think otherwise.

**Comment by jaredcunha** [comment]
@Ben-Judy-Flexion I think that should be fine. We can probably also make the border a darker blue as well.
