### ISSUE TITLE
Create a follow up component.

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3361]
## User Story

As a front-end developer, I need a way to help users enter dynamic additional information in a way that is accessible.

## Examples
* [Certify](https://ussba.github.io/certify-design-system-documentation/patterns/questions.html)
* [CMS - Radio boxes with children](https://design.cms.gov/components/choice/)

## Checklist
- [ ] Create low-fidelity design
- [ ] Review & discuss low-fi design (designer + developers)
- [ ] Get user feedback on low-fi designs (optional - if team feels is needed)
- [ ] Code
- [ ] Conduct usability test with working code (optional - if team feels is needed)
- [ ] Create hi-fi design assets (Adobe XD, Sketch, Figma)
- [ ] Review & approve hi-fi design assets
- [ ] Publish design assets (update downloadable files for Adobe XD, Sketch, Figma)

**Comment by Ben-Judy-Flexion** [comment]
**Design:**
_The following design should be considered "low fidelity" -- not matching the visual style of USWDS. Let @Ben-Judy-Flexion know if high fidelity designs are needed._
![Follow-ups (wireframes) State 1_ default](https://user-images.githubusercontent.com/56978395/76873948-75172900-683c-11ea-9058-1b2e0373d33e.png)
![Follow-ups (wireframes) State 2_ follow-up displayed](https://user-images.githubusercontent.com/56978395/76873952-75afbf80-683c-11ea-95fe-b54091f3b374.png)

**_Figma source for design:_**
https://www.figma.com/file/jLPd8N0c0BHH6Bd3vFDFaw/Form-Component-Wireframes?node-id=0%3A1

**Comment by jaredcunha** [comment]
Added another example to the main issue text in the first comment. Saw it as a reply to a comment in the `uswds-public` Slack (https://gsa-tts.slack.com/archives/C3F14AHSQ/p1584573967152100)
