### ISSUE TITLE
Create a progress bar component. 

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3362]
## User Story

As a front-end developer, I need a way to help users understand the steps required to complete a task.

## Examples
* [Atlassian](https://atlassian.design/guidelines/product/components/progress-tracker)
* [Lightning](https://www.lightningdesignsystem.com/components/path/)
* [Carbon](https://www.carbondesignsystem.com/components/progress-indicator/code/)
* [Mercury](https://www.canadapost.ca/cpc/en/designsystem/mercury/components/combinations/progress-bar.page)
* [FPAC Design System - USDA](https://usda-fsa.github.io/fsa-design-system/components/progress/)
* [NASA - coming soon!](https://design.login.gov/components/progress-indicators/)
* [USAJobs Design System](https://usajobs.github.io/design-system/progress-indicator/)
* [Australian Government Design System](https://designsystem.gov.au/components/progress-indicator/)

## Checklist
- [x] Create low-fidelity design
- [x] Review & discuss low-fi design (designer + developers)
- [x] Get user feedback on low-fi designs (optional - if team feels is needed)
- [x] Code
- [x] Conduct usability test with working code (optional - if team feels is needed)
- [x] Create hi-fi design assets (Adobe XD, Sketch, Figma)
- [x] Review & approve hi-fi design assets
- [ ] Publish design assets (update downloadable files for Adobe XD, Sketch, Figma)

**Comment by jaredcunha** [comment]
Some info on stack exchange about progress indicators. This might be useful in carving out some of the guidance:
https://ux.stackexchange.com/questions/3454/how-do-you-indicate-progress-to-users-in-a-multi-step-form

I think it'd be worth chatting with the USA.gov team about their progress indicator and seeing what kind of research they've done and how they'd feel about its broader usage outside usa.gov.

**Comment by jaredcunha** [comment]
Here is Saleforce's Progress Indicator, different from the Path component above:
https://www.lightningdesignsystem.com/components/progress-indicator/

**Comment by jaredcunha** [comment]
Good accessibility notes here: https://stackoverflow.com/questions/52932018/making-a-step-progress-indicator-accessible-for-screen-readers
