### ISSUE TITLE
 Discovery: Replace Fractal with Storybookjs

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3380]
## Description

Fractal is development has slowed down enough where serious vulnerabilities are appearing. What can Storybookjs offer out of the box and how does that work with our current system.

https://storybook.js.org/

- How easy is it to integrate this into USWDS to replace fractal?
- How would we use these components in USWDS-Site?

Relates to:
- #3378
- #3263 
- #3379 

## Additional information

A good example of what storybook offers:
https://circuit.sumup.com/?path=/story/introduction-welcome--page

**Comment by thisisdano** [comment]
Done
