### ISSUE TITLE
 Discovery: Replace Fractal with Pattern Lab

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3381]
## Description
What does Pattern Lab feature out of the box that can help us replace Fractal? Short term vs long term. 

Keeping in mind an eye towards increasing functionality so we can offer the component library to users who want to spinoff their own.

- How easy is it to integrate this into USWDS to replace fractal?
- How would we use these components in USWDS-Site?

Relates to:
- #3378  
- #3263 
- #3380

**Comment by thisisdano** [comment]
Done.
