### ISSUE TITLE
[sass] Flex fill on IE11.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3386]
## Description

`@include u-flex("fill");` documented here:
https://designsystem.digital.gov/design-tokens/flex/

Using it to grow vertically results in something like this:

### IE11
![image](https://user-images.githubusercontent.com/3385219/78803765-0170c380-7985-11ea-819f-2eae2970d050.png)

---

Changing it from:
```scss
flex: 1 0 0 → flex: 1 0 auto
```
Fixes it in IE11.

## Steps to reproduce the issue

1. Checkout `feature/USWDS-3301`
2. Go to commit `8fbfc1c`
3. Compile SCSS 
4. `npm run start`
5. Open `http://localhost:3000/components/preview/card--equal-height` in IE11

---
Updated

## Expected behavior
Flex fill **should** behave consistently across all browsers

**Comment by thisisdano** [comment]
@mejiaj Can you look at all our flex utilities/tokens and make sure they're doing what we expect them to do in IE11?
