### ISSUE TITLE
New color palette is out of sync with the docs

### ISSUE THREAD

**Issue by darekkay** [uswds/uswds#3398]
This is a follow-up to the changes introduced in #3351 (based on #3329).

The colors seem to be ouf of sync with the documentation. Example:

- `indigo-cool-80v`: [json](https://github.com/uswds/uswds/pull/3351/files#diff-f90bd710129d47d1d9eafa1fac673ad0) = `#222fbf`, [docs](https://designsystem.digital.gov/design-tokens/color/system-tokens/#indigo-cool) = `#1b2b85` ([source code](https://github.com/uswds/uswds-site/pull/877/files#diff-009705f1f3d45c6d3451a9dff737a4f7R875)).

I _think_ the docs version are correct, because the new palette used in this repository is not fully accessible. Example:

- [`blue-20`](https://github.com/uswds/uswds/pull/3351/files#diff-9bd1244f000e7ffdfd41f891fd070fa9R11): `#aacdec`
- [`indigo-cool-70v`](https://github.com/uswds/uswds/pull/3351/files#diff-f90bd710129d47d1d9eafa1fac673ad0R29): `#3e4ded`
- Contrast ratio: 3.63 - Doesn't pass WCAG AA

With the values from the docs:
- `blue-20`: `#aacdec`
- `indigo-cool-70v`: `#222fbf`
- Contrast ratio: 5.68 - Passes WCAG AA

I didn't check all the values, but from my automated script I only got contrast ratio issues for `indigo-cool-vivid-70+` (it doesn't mean that other values are not ouf of sync).

**Comment by darekkay** [comment]
@thisisdano This one is probably for you 😃

**Comment by darekkay** [comment]
I've written a small script to find all differences. Here they are:

-  'indigo-cool-vivid-60': '#4150f2'
-  'indigo-cool-vivid-70': '#3e4ded'
-  'indigo-cool-vivid-80': '#222fbf'
-  'red-vivid-60': '#b50909'
-  'red-vivid-70': '#8b0a03'

**Comment by thisisdano** [comment]
Oh rats — I'll make an update. Thank you!

**Comment by thisisdano** [comment]
I believe these should be the correct values:

`indigo-cool-vivid-60`: `#3E4DED `
`indigo-cool-vivid-70`: `#222FBF`
`indigo-cool-vivid-80`: `#1B2B85`
`red-vivid-60`: `#b50909`
`red-vivid-70`: `#8b0a03`

**Comment by thisisdano** [comment]
Working on this now and it'll be in the next release.

**Comment by thisisdano** [comment]
Fixed by https://github.com/uswds/uswds-site/pull/948 — thanks @darekkay!
