### ISSUE TITLE
USWDS Color: Add luminance checking into testing and CI.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3400]
## Description

As a USWDS contributor I want to check that the color passes accessibility. Add color test in `npm test` and into CI.

We want to be sure a color family passes:
| Color Difference        | a11y Baseline |
| ------------- |:-------------|
| 40      | ✅ AA Large |
| 50     | ✅ AA |
| 70 | ✅ AAA  |

The strictest check is AAA, if a color passes with a difference of 70 (AAA) then we don't need to check `AA & AA Large`.

**Comment by thisisdano** [comment]
An MVP here, and perhaps the simplest, most effective test would be to check each color against our [grade guidance](https://designsystem.digital.gov/design-tokens/color/overview/#magic-number).

grade | minimum luminance | maximum luminance
-- | -- | --
0 | 1.000 | 1.000
5 | 0.850 | 0.930
10 | 0.750 | 0.820
20 | 0.500 | 0.650
30 | 0.350 | 0.450
40 | 0.250 | 0.300
50 | 0.175 | 0.183
60 | 0.100 | 0.125
70 | 0.050 | 0.070
80 | 0.020 | 0.040
90 | 0.015 | 0.012
100 | 0.000 | 0.000

**Comment by mejiaj** [comment]
This could possibly be closed with this color work #3966.

**Comment by thisisdano** [comment]
We should add a very simple test as part of our CI tests refresh

**Comment by thisisdano** [comment]
Closing since our current luminance guidance will assure proper contrast
