### ISSUE TITLE
Re-check Card Component accessibility

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3402]
Re-test Card Component for Accessibility at the following links...

*On its own*:
[https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-card-kitchen-sink/components/preview/card--kitchen-sink.html](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-card-kitchen-sink/components/preview/card--kitchen-sink.html "https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-card-kitchen-sink/components/preview/card--kitchen-sink.html")

*Within the context of uswds site*:  
[https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-card-kitchen-sink/components/preview/kitchen-sink.html](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-card-kitchen-sink/components/preview/kitchen-sink.html "https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-card-kitchen-sink/components/preview/kitchen-sink.html")

...with the following questions in mind:
-   Does the markup of the card affect accessibility?
-   Does alt text interfere with images?
-   Does the order of the images matter?

**Comment by nks-bix** [comment]
results of re-test in shared drive. https://drive.google.com/open?id=1ChTqXV3cUAe5OKhf59jH-LsHazLr9Ej_

**Comment by mejiaj** [comment]
@nks-bix @thisisdano, I think this can be considered `done` right?
