### ISSUE TITLE
Discovery: Moving from Fractal to Jekyll/Storybook/Patternlab

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3404]
What can USWDS do, short-term, to move from Fractal to something else like PatternLab or Storybook?

Sample of longterm goals and questions:
- Universal template format.
- Reduce number of things to change.
- What do we want the component library to do?

Three audiences:
- Users who don't need much guidance
- Users who do need more guidance
- Users who want to have their own copy of USWDS and expand upon it and collaborate upon it.

**Comment by nks-bix** [comment]
@thisisdano @chazchumley's availability will likely be around the end of May. In preparation for that, we should chat together to get clarification about:

> Restructuring the scss into a PatternLab structure means Documentation generation will no longer be possible and will need to be a manual process.  (meaning:  true Documentation of USWDS and USWDS' PatternLab will not be intertwined.). The components in PatternLab will have subtle documentation but nothing like it is on the website.

**Comment by thisisdano** [comment]
We will be moving to PatternLab for a short-term solution
