### ISSUE TITLE
Breadcrumb component landscape analysis

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3405]
Conduct a landscape analysis to find out who and how breadcrumbs are being implemented within the federal digital space.

## What we found
Landscape analysis: https://bixal.invisionapp.com/freehand/document/tSS644yrC
Preliminary analysis: https://github.com/uswds/uswds/wiki/Breadcrumbs-Landscape-Analysis

## Next steps for subsequent issues
- [ ] Get initial accessibility recommendations 
- [ ] Create a prototype.
- [ ] Identify key questions and scenarios especially around small-screen/mobile usage
- [ ] Collect feedback from interviews and usability

**Comment by nks-bix** [comment]
Beginnings of breadcrumb component landscape analysis:  https://bixal.invisionapp.com/freehand/document/tSS644yrC?

**Comment by pglevy** [comment]
Started capturing [landscape analysis and related guidance here in the wiki](https://github.com/uswds/uswds/wiki/Breadcrumbs-Landscape-Analysis).

**Comment by nks-bix** [comment]
- Consult with MegB for accessibility recommendations to incorporate into prototype.
- Identify some key questions and scenarios especially around small-screen/mobile usage
- Collect feedback from interviews

**Comment by thisisdano** [comment]
Captured the output and next steps in the canonical issue: https://github.com/uswds/uswds/issues/3452
