### ISSUE TITLE
Create breadcrumb component guidance

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3407]
Create the documentation guidance for the Breadcrumb Component in the USWDS design guide.

**Comment by pglevy** [comment]
Captured some initial recommendations and other issues to think for guidance in [Research Findings](https://github.com/uswds/uswds/wiki/Breadcrumbs-Research-Findings).

**Comment by pglevy** [comment]
Hi @thisisdano , Here is a [first pass at guidance for breadcrumbs](https://github.com/uswds/uswds/wiki/Breadcrumbs-Draft-Guidance). I put it on the wiki for now to keep things in markdown, so feel free to make changes there or move to the uswds-site page. I made some assumptions about what you might want to include so open to your feedback.

Following up on our schema discussion the other day, I looked more into RDFa vs. Microformat. It looks like RDFa is generally more capable and is currently a [W3C recommendation](https://www.w3.org/TR/rdf-schema/). Microdata on the other hand does have a [working draft](https://www.w3.org/TR/microdata/).

As a quick experiment, I mocked up an [RDFa version of the current prototype](https://github.com/pglevy/uswds/blob/56fc3ff956129fa9648a5d0f2de54a8dc86295f5/src/components/breadcrumb/breadcrumb--ordered.njk) and tested the code snipped using the [Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool/u/0/) if you're interested in checking that out. 

Look forward to your feedback on the guidance.

**Comment by thisisdano** [comment]
Closed in https://github.com/uswds/uswds-site/pull/967
