### ISSUE TITLE
Mockup of breadcrumb component

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3408]
Create a mockup of the breadcrumb component to iterate upon before building a working prototype.

**Comment by nks-bix** [comment]
Beginnings of mockup of breadcrumb component:  https://codepen.io/pglevy/pen/oNjBBow?editors=1100

**Comment by pglevy** [comment]
Started mocking up some [variations here in codepen](https://codepen.io/pglevy/full/oNjBBow).

**Comment by pglevy** [comment]
Moving onto prototyping and initial user testing. Closing issue.
