### ISSUE TITLE
Conduct breadcrumb component Accessibility Audit

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3411]
Conduct accessibility tests on the breadcrumb component prototype with an emphasis on "**A**" of the CARED component evaluation framework.

Accessibility:
-  Added to scanner: Scanned with USWDS aXe scanner.
-   Tested with semi-automated accessibility tool: Passes and addresses any issues in a semi-automated tool like [Accessibility Insights](https://accessibilityinsights.io/)
-   Accessibility tests written: Any additional tests written and executed with npm test
-   Passes WCAG 2.1 AA and Section 508: TK
-   Call out keyboard nav and screen reader tests?

**Comment by nks-bix** [comment]
initial thoughts that have been taken into consideration while building the prototype include from MegB:

> Outside of this advice:
> [https://www.aditus.io/patterns/breadcrumbs/](https://www.aditus.io/patterns/breadcrumbs/
> "https://www.aditus.io/patterns/breadcrumbs/") I would say remember
> that your breadcrumbs must match exactly in name the navigation
> level(page) that they represent, so you if you have a breadcrumb
> called “Get Help” it must refer to the only one place that is called
> Get Help as well.
> 
> I’d also advise against using longer, truncated breadcrumbs because
> they look like they could be confusing to users with a cognitive
> disability.
> 
> Be sure to check to see how they behave on mobile. I am not sure about
> how responsive a design will be the breadcrumbs are included on the
> mobile version- they may not be shown in that instance if they are
> not needed because they are secondary.

**Comment by nks-bix** [comment]
[508 audit results](https://drive.google.com/open?id=1Mn41JZwuk4l6UNLlSc9Vnx-1F8mXhGEb)

**Comment by thisisdano** [comment]
@mejiaj Anything else we need to do to close this out. Write tests? Assure it's scanned properly?
