### ISSUE TITLE
Update Settings Pages for breadcrumb component

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3413]
Update Settings Pages for breadcrumb component

**Comment by thisisdano** [comment]
We want to remove all settings associated with custom separators. This will require:

### uswds
- [ ] Remove settings from component settings file
- [ ] Remove settings from component theme file
- [ ] Update Breadcrumb Sass
- [ ] Re-measure footprint

### uswds-site
- [ ] Update Settings data file `variables.yml`
- [ ] Update Breadcrumb component guidance page

**Comment by mejiaj** [comment]
https://github.com/uswds/uswds/pull/3533

- [x] Remove settings from component settings file
- [x] Remove settings from component theme file
- [x] Update Breadcrumb Sass
