### ISSUE TITLE
Breadcrumb component news-blog announcement post

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3417]
Describe your work to the public. Explain what you did, why you did it, and how to use the new breadcrumb component. 

- [x] Create [Draft gDoc](https://docs.google.com/document/d/1B7ihmhfTwnX8NONOhgPIprcrgImhVCn_0amqFghSWA0/edit#)
- [ ] Client review and approval
- [x] Create [Github page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/ja-breadcrumb-blog/whats-new/updates/2020/09/28/breadcrumb-component/)
- [ ] TTS Comms 
- [ ] OSC, if needed
- [ ] Publish
- [ ] Digital.gov short post

**Comment by thisisdano** [comment]
We won't be writing a blog post for Breadcrumb!

**Comment by katieekline** [comment]
@thisisdano and @afeijoo This draft [blog post](https://docs.google.com/document/d/1B7ihmhfTwnX8NONOhgPIprcrgImhVCn_0amqFghSWA0/edit#) is ready for your review.

**Comment by afeijoo** [comment]
@thisisdano This draft [breadcrumb blog post](https://docs.google.com/document/d/1B7ihmhfTwnX8NONOhgPIprcrgImhVCn_0amqFghSWA0/edit#) is ready for your review.

**Comment by jAigret-Bix** [comment]
@mejiaj In the page, can you please remove the word "latest" in the sentence, "This latest release provides a smart way of easily creating accessible links on any background." Otherwise the copy is good.

**Comment by jAigret-Bix** [comment]
@thisisdano [Github page ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/ja-breadcrumb-blog/whats-new/updates/2020/09/28/breadcrumb-component/)is ready. We need your content review. Missing a social sharing image.

**Comment by jAigret-Bix** [comment]
@thisisdano  @katieekline Decision on 10/29: we will not publish blogs unless there is a specific comms plan needed. this blog will be edited into an Introduction paragraph and added to the top of the guidance page. PR and branch deleted. A new issue will be created and this one can be closed.
