### ISSUE TITLE
Create Breadcrumb Component page

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3418]
Include a guidance page on the USWDS website (a uswds-site pull request connected to any related code work in the uswds repo). This documentation page should include:

 - Name 
 - Description 
 - Example Code 
 - When to use 
 - When to consider something else 
 - Usability guidance 
 - Accessibility guidance
 - Implementation guidance (if necessary) 
 - Resources Package information

**Comment by mejiaj** [comment]
Added [here](https://github.com/uswds/uswds-site/pull/967).
