### ISSUE TITLE
Conduct user-interviews for breadcrumb component

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3420]
Conduct user-interviews for breadcrumb component.

- Who
- What format
- When

**Comment by pglevy** [comment]
- [Research Plan](https://github.com/uswds/uswds/wiki/Breadcrumbs-Research-Plan)
- [Research Findings](https://github.com/uswds/uswds/wiki/Breadcrumbs-Research-Findings)
- [Landscape Analysis](https://github.com/uswds/uswds/wiki/Breadcrumbs-Landscape-Analysis)

**Comment by pglevy** [comment]
Themes from interviews and other findings and initial recommendations captured in [Research Findings](https://github.com/uswds/uswds/wiki/Breadcrumbs-Research-Findings). Closing issue.
