### ISSUE TITLE
Develop approach for announcing and gathering component feedback

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3424]

**Comment by KimberlyHodges** [comment]
Updated Draft approach for announcing and gathering new component feedback; put into Google Sheet: 
https://docs.google.com/spreadsheets/d/1a30-qwRNJZe0zPoNhtGdxSdV0rwKe6d6a3YCc2Xqy68/edit#gid=730216502

**Comment by KimberlyHodges** [comment]
Conducting brief/small internal survey on USWDS users who use GitHub and those who don't to ensure we're providing easy path to provide feedback. Designers, a primary user, may be using the USWDS Sketch file to make mockups, but they may not have Github accounts because it's not something they use regularly. Even though developers are not using a "GitHub package" for USWDS, they likely have a presence on Github, so this would be simple path to provide feedback.

**Comment by afeijoo** [comment]
@KimberlyHodges I added some direct comments/edits into the gSheet.

**Comment by KimberlyHodges** [comment]
@afeijoo I've added some updates to the sheet. 

Update on Informal Survey:
Informal Survey of our Visual Designers to ask if they have GitHub account and use it as a channel for building a community and providing feedback on component

In a team of 7, only 1 of them has a github account.

Only one other team member said they'd be willing to open a github account to get access to the files. Other team members felt it was a "barrier to entry"

The team member that has the github account opened it to get the USWDS files. They said it was a big learning curve and there was a lot of information to sift through to eventually get the specific files they were looking for.

Another sentiment that came from the team is that they feel Github is the wrong place to keep those files. Github is more geared towards developers, and so if they want the files to reach designers, they don't think Github is the right place

**Comment by KimberlyHodges** [comment]
@afeijoo I'm conducting a follow up information survey to help determine best communication paths to reach visual designers, user experience designers and content strategists who typically do not have GitHub accounts:

Step 2:  I'm going back to our Visual, Interaction Designers; UX Designers; Content Strategists to ask what's the easiest path to provide feedback? 
1. How likely would they be to provide feedback via social media
2. How likely would they be to provide feedback via email request with link to survey
3. What's their preferred path for providing feedback. What can we do to increase chances?

**Comment by KimberlyHodges** [comment]
Reached back to Creative Director and UX Director. Responses still coming in.

**Comment by thisisdano** [comment]
What do we need to do to close up this issue? I'd like to write this up as a generalized procedure for collecting feedback and not tie this specifically to card.

**Comment by afeijoo** [comment]
We need to QA and generalize the draft in https://docs.google.com/spreadsheets/d/1a30-qwRNJZe0zPoNhtGdxSdV0rwKe6d6a3YCc2Xqy68/edit. It is on my radar and to-do list. You're welcome to jump in now or after I take a pass.

**Comment by KimberlyHodges** [comment]
@afeijoo reviewed your response to my comments. Started Google doc for canned content. Need to confirm with you that we want canned content for every channel and every stage (x4)

**Comment by thisisdano** [comment]
When we have a process, this should be published to the wiki. That would close this issue.

**Comment by KimberlyHodges** [comment]
We discussed in stadn-up, but noticed I didn't update here. I've drafted canned content for all of the major communication channels in associated google doc. [except website] @afeijoo I'll defer to you if you want to remove content from spreadsheet and provide one general link to google doc or if we can add anochored links to unique content per channel.

**Comment by afeijoo** [comment]
@KimberlyHodges Can you please add the associated Google doc here?

**Comment by KimberlyHodges** [comment]
https://drive.google.com/open?id=1J3g197dynjkPEHCVR6u3wRH4QgPl57w7rsiQNjWaxq8(url)

**Comment by afeijoo** [comment]
@thisisdano and I chatted about this. He'll take one more pass on it and will then publish it on the wiki.

**Comment by afeijoo** [comment]
@katieekline Let's write a new issue for this work and then close this issue. Can you find 15 minutes when we're both free in the next few days to cowork on the new issue?

**Comment by afeijoo** [comment]
Closed by https://github.com/uswds/uswds-team/issues/26.
