### ISSUE TITLE
Media block (object) sometimes cuts off last part of text in IE11

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3425]
We found a bug/quirk with the media block (object) component in IE11 where the last part of the word would get cutoff. It's not something we could consistently reproduce. Rather, it would randomly work/fail just on refresh. Removing `usa-media-block__body` or `overflow: hidden` from our paragraph text element seemingly fixed this. On another try, adding a `padding: 0;` to the link it fixed it.

Wondering if it's the combo of flexbox and `overflow: hidden` that caused this?

## What we saw (IE11)
<img width="808" alt="Dashboard" src="https://user-images.githubusercontent.com/5249443/79791980-03327380-8303-11ea-9378-6a1c41f518d9.png">

## What we expected
<img width="824" alt="Screen Shot 2020-04-20 at 12 30 00 PM" src="https://user-images.githubusercontent.com/5249443/79791959-ff065600-8302-11ea-9b05-fa6f63d1a5d0.png">

## Code used
```html
<div class="alert--info bg-accent-cool-lighter width-full">
    <div class="grid-container padding-y-105 display-flex flex-align-center">
      <img class="usa-media-block__img width-205" src="/assets/img/info-circle.svg" alt="">
      <p class="usa-media-block__body line-height-sans-3 margin-y-0">If you’re having a <strong>medical emergency</strong>, call 911. If you aren’t sure, <a class="usa-link" href="https://www.hhs.gov/blog/2020/04/17/when-to-seek-emergency-care.html" target="_blank">read when to seek emergency care</a>.</p>
    </div>
  </div>
```

## Possible solution
The USWDS media block is based on the [original media object by Nicole Sullivan](http://www.stubbornella.org/content/2010/06/25/the-media-object-saves-hundreds-of-lines-of-code/) from 2010. USWDS may want to consider moving to a flexbox-based media object like [Bootstrap's media object](https://getbootstrap.com/docs/4.0/layout/media-object/), which has some added features like alignment variations. They also include a note about how to support IE 10-11 with it.

**Comment by mejiaj** [comment]
I was able to replicate with the markup above pretty consistently in IE11.

![image](https://user-images.githubusercontent.com/3385219/81314960-53257000-904f-11ea-96f0-0fabc9523da2.png)

If we were to go this route:
```scss
.usa-media-block {
  display: flex;
  align-items: flex-start;
}

.usa-media-block__img {
  @include media-block-img;
}

.usa-media-block__body {
  flex: 1;
}

```
https://philipwalton.github.io/solved-by-flexbox/demos/media-object/

We'd have to add a wrapper to the media object. But it seems to render consistently in IE11.
