### ISSUE TITLE
Add align self to flex utilities

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3426]
Add align self to flex utilities so that you can individually change the alignment of flexbox items. In the [USWDS flex utilities](https://designsystem.digital.gov/utilities/flex/) you can only add alignment utilities to the flexbox container. See: https://getbootstrap.com/docs/4.0/utilities/flex/#align-self

**Comment by thisisdano** [comment]
This has been on my radar for a while, and I agree that it's time to add these

**Comment by thisisdano** [comment]
Done in #3588
