### ISSUE TITLE
Create page template for a login page

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds#3432]
## Description

Landing pages to login into an application are a common type of page across GSA and federal websites. It would be good to create a login [page template](https://designsystem.digital.gov/page-templates/) to provide a consistent experience across sites.

## Examples of GSA Login Pages

* https://autovendor.fas.gsa.gov
* https://domains.dotgov.gov/dotgov-web/
* https://extportal.pbs.gsa.gov/pbs/home/
* https://facadatabase.gov
* https://fairs.reporting.gov
* https://frpg.gov
* https://login.fr.cloud.gov/login
* https://lop.gsa.gov/
* https://mysmartplans.gsa.gov/
* https://property.reporting.gov
* https://rocis.gov
* https://search.usa.gov/login
* https://secure.login.gov/
* https://travel.reporting.gov
* https://www.fdms.gov/fdms/login.do
* https://www.pbs-billing.gsa.gov/

**Comment by justinward1** [comment]
ret.gsa.gov

**Comment by mejiaj** [comment]
Mockups for displaying different options:

https://codepen.io/mejiaj/full/NWGOKRV

Mobile first made completely using USWDS utilities. Accessibility tested with AXE browser plugin.

**Comment by thisisdano** [comment]
Done in USWDS 2.10

**Comment by justinward1** [comment]
Thank you, Dan. I hope you're doing well.

Justin
