### ISSUE TITLE
Server logs returning 404s on bg images that use add-background-svg mixin

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3436]
Server logs returning 404s for background images that use `add-background-svg` mixin. 

![server-logs-svg](https://user-images.githubusercontent.com/5249443/80248232-5dde0f00-8624-11ea-8e3f-e800f87bba9d.png)

I wonder if it's browser support related or something else? https://caniuse.com/#search=linear-gradient

**Comment by mejiaj** [comment]
The linear-gradient is related to this [CSS Tricks article](https://css-tricks.com/a-complete-guide-to-svg-fallbacks/#fallback-svg-css-background-image).

What browser are you seeing this in, it looks like chrome?

I was able to successfully use the mixin using:
```scss
// _uswds-theme-general.scss
$theme-image-path: '../img';

// My custom style
@include add-background-svg("403_Illustration");
```

**Comment by maya** [comment]
Not sure, it came from the people managing our server and they didn't let me know. My guess would also be some older or obscure browser. Will close this as I'm not working on this anymore, but at least you have a heads up.
