### ISSUE TITLE
Improve accessibility of search input

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3442]
https://codepen.io/mejiaj/pen/ZEbBXxZ?editors=1100

**Comment by mejiaj** [comment]
The above is markup for a USWDS-based search element that tested well when doing accessibility testing.

We should test this example and the current USWDS search in different screen readers and see how they differ and how we can use this to make improvements (if any) to the search component.

**Comment by afeld** [comment]
@iamjolly pointed out an issue with the "clear" control specifically: https://github.com/18F/handbook/pull/2085#issuecomment-674275929

**Comment by thisisdano** [comment]
This clear control is something added by webkit browsers. Should we be manually disabling it? 
https://github.com/18F/handbook/pull/2085#issuecomment-674936765

https://stackoverflow.com/questions/20804016/editing-input-type-search-pseudo-element-button-x

**Comment by afeld** [comment]
https://webkit.org/reporting-bugs/

**Comment by iamjolly** [comment]
Reported to webkit team's bugzilla system: https://bugs.webkit.org/show_bug.cgi?id=215579

**Comment by thisisdano** [comment]
@mejiaj Can you be more clear in this issue what accessibility issues we have with the search component? Otherwise I'm  inclined to close this issue, since search hasn't come up on our accessibility radar otherwise.

**Comment by mejiaj** [comment]
@thisisdano it was just the title that further explains what's expected for input. I agree, we can close this.
