### ISSUE TITLE
Replace `Autoprefixer Settings` to Browserslist config and add `not dead` to recommendations

### ISSUE THREAD

**Issue by ai** [uswds/uswds#3450]
Hi. I am the creator of Autoprefixer and Browserslist. On the [For developers](https://designsystem.digital.gov/documentation/developers/) page we have a text:

> Autoprefixing uses a service like gulp-autoprefixer to automatically add vendor prefixes to the precompiled stylesheets. Don’t add vendor prefixes to your custom styles manually — it is more reliable to use autoprefixing. We use the following autoprefixer settings:
> '> 2%','Last 2 versions', 'IE 11'

I suggest to change it to:

> We use the following Browserslist config:
> '> 2%','Last 2 versions', 'Not dead', 'IE 11'

### Browserslist

In modern front-end, we have many tools, which use current target browsers. For example, `babel-preset-env` adds polyfills according to your target browsers.

This is why [Autoprefixer](https://github.com/postcss/autoprefixer#options) and [Babel](https://babeljs.io/docs/en/babel-preset-env#browserslist-integration) officially recommend to not put target browsers for tool settings and put it to Browserslist config (`.browserslistrc`), which will be used by all front-end tools.

Using `Browserslist config` words instead of `autoprefixer settings` will promote this best practice.

### `not dead`

[`Last 2 versions`](https://browserl.ist/?q=last+2+versions) contains many browsers, which are very rare and have no security updates anymore. For instance, Blackberry 7. Browserslist has a special `dead` query for all browsers from the `last 2 versions` which has no security updates for 24 months. Right now it is `IE 10`, `IE_Mob 11`, `BlackBerry 10`, `BlackBerry 7`, `Samsung 4`, and `OperaMobile 12.1`. Using `not dead` with `last X versions` is part of [official Browserslist recommendations](https://github.com/browserslist/browserslist#best-practices).

### Browser support section

Since Browserslist is a very popular tool (it is used by Autoprefixer, Babel, Mozilla’s webhint, ESLint/Stylelint/webpack plugins) we can also add the config to [Browser support](https://designsystem.digital.gov/documentation/developers/#browser-support) section, but I am not sure about it.

**Comment by thisisdano** [comment]
Thank you for checking in on this @ai. And thank you for your work on these important resources. This makes a lot of sense and we're going fit it into an upcoming block of work.
