### ISSUE TITLE
Radio and checkboxes legend formatting issue

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3464]
Radio and checkbox code example uses a screen reader–only class, but in most cases, we need to have a visible legend on those form controls. When you remove the class, the legend is too close to the controls.

## Without `.usa-sr-only` class
<img width="287" alt="Screen Shot 2020-05-11 at 7 34 38 PM" src="https://user-images.githubusercontent.com/5249443/81632200-8bfe7580-93be-11ea-8d1d-f71027006290.png">

## Without `.usa-sr-only` class and with `.usa-legend` class
<img width="318" alt="Screen Shot 2020-05-11 at 7 34 08 PM" src="https://user-images.githubusercontent.com/5249443/81632202-8d2fa280-93be-11ea-8f32-dc7310599a87.png">

**Comment by thisisdano** [comment]
I think this legend formatting should look just like a standard label, so it fits in with the rest of a form. @mejiaj can you integrate this into your PR?
