### ISSUE TITLE
Allow disabled combo box enhancement

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3474]
As a USWDS user. I would want a disabled/readonly select to continue to be disabled after enhancement to a combo box.

 ## Additional information

Setting the input as disabled currently does disable the combo box as expected. This is making sure that enhancement process carries over this initial state.

**Comment by ConnorDY** [comment]
After this is implemented...
If the `<select>` starts out enabled and then I set the `disabled` attribute to `true` later based on some action, will the combo box also be disabled?

**Comment by wbyoko** [comment]
@ConnorDY you would want to edit the properties of the combo box input directly. The select will be hidden from view and would not be available to receive focus.

**Comment by thisisdano** [comment]
Done in #3484
