### ISSUE TITLE
Combo Box component does not fire a change event on the select when the value is changed

### ISSUE THREAD

**Issue by ConnorDY** [uswds/uswds#3475]
## Description

When changing the selection for the new Combo Box component, I expect a proper `change` event to be fired on the `<select>`. Currently no event is fired when USWDS programmatically sets the `value` property for the `<select>`.

## Steps to reproduce the issue

1. Copy the example code for a combobox from [here](https://designsystem.digital.gov/components/form-controls/#combo-box)
2. Add an event listener to the select:
```javascript
document.getElementById('fruit').addEventListener('change', (event) => {
  console.log(event);
});
```
3. Run the code and select an option in the combo box
4. No `change` event is fired so no event is logged to the console

## Additional information [optional]

~Unrelated, but the combo box also does not respect `disabled` or `readonly` attributes on the `<select>`.~ I see the following issue was created for this: #3474.

**Comment by wbyoko** [comment]
Seems to describe the situation and solution https://stackoverflow.com/questions/1224728/how-do-i-programmatically-change-a-select-so-that-it-fires-its-onchange-behavior
