### ISSUE TITLE
Combobox down arrow icon inconsistent in coded version and Sketch

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3494]
## Sketch version (thinner)
![download (2)](https://user-images.githubusercontent.com/5249443/83300171-58885d00-a1ac-11ea-891f-ba5da9982cff.png)

## Coded component version (thicker)
<img width="454" alt="Screen Shot 2020-05-13 at 12 09 20 PM" src="https://user-images.githubusercontent.com/5249443/83300173-59b98a00-a1ac-11ea-9f13-1b612f5cb111.png">

**Comment by mejiaj** [comment]
Resolved in https://github.com/uswds/uswds-for-designers/releases/tag/v2.4.0
