### ISSUE TITLE
Add multi-select to combo box

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3499]
## Example

<img width="662" alt="Screen Shot 2020-06-03 at 12 13 17 PM" src="https://user-images.githubusercontent.com/5249443/83679474-4e8fa100-a594-11ea-9cc5-663ee4eb7ed7.png">

https://semantic-ui.com/modules/dropdown.html#multiple-search-selection

https://sarahmhigley.com/writing/select-your-poison/

**Comment by arkjoseph** [comment]
@maya - have you done any work on this? im also looking for a multi select input but cant locate in documentation

**Comment by maya** [comment]
No, I've not. It's not in the USWDS.

**Comment by thisisdano** [comment]
Closing since this is not on the current roadmap, but tagging for future consideration. I think this would be nice to have.
