### ISSUE TITLE
Add a multi-page form template

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3500]
Forms are pervasive throughout govt websites so it would be useful to show how to do them right in a holistic form flow.

## Questions to address
- Names of progress button (Next, Continue)
- Location of buttons left vs right
- Back button usage. names (or Cancel, Save and continue) and location
- Button group considerations for mobile (sticky vs non-sticky) and location
- Amount of questions per page (one thing per page vs grouping)

There are also several other aspects to consider:
- Start pages
- Step by step navigation
- Task list pages
- Confirmation pages

## Example
https://design-system.service.gov.uk/patterns/question-pages/

**Comment by thisisdano** [comment]
I'm closing this for now since it's not on our current roadmap. Patterns are likely going to be a big part of the FY22 roadmap, which will kick off in October.
