### ISSUE TITLE
Can't resolve ttf files from sass file

### ISSUE THREAD

**Issue by bparksdev** [uswds/uswds#3506]
Hi,

I carefully followed the posted installation steps, including the "easy" gulp setup with the proper gulpfile.js edits (using info from https://github.com/uswds/uswds-gulp) and the main install page.

I then added my import statement to App.js:
``
import './uswds/sass/styles.scss'
``
When I tried to start, I immediately saw:
_Module not found: Can't resolve '../../../node_modules/uswds/src/stylesheets/core/fonts/merriweather/Latin-Merriweather-Bold.ttf' in '/home/brian/webdev/uswdstest/src/uswds/sass'_

There is no such folder as "node_modules/uswds/src/stylesheets/core/fonts" so that's not surprising, but is there another config file I need to modify or did I miss a step somewhere? I know I can get it to work the index.html way, but I'd like to use the advanced features if possible.

**Comment by thisisdano** [comment]
Did `styles.css` compile properly when you ran `gulp init` after installing `uswds-gulp`?

**Comment by bparksdev** [comment]
Looks like it.
[style.css.txt](https://github.com/uswds/uswds/files/4766050/style.css.txt)

**Comment by thisisdano** [comment]
Hm! So `styles.scss` is compiling to `styles.css` properly via gulp, but something is happening when you import the Sass into `App.js`. I don't know enough about the `App.js` import to know what happens to the Sass in that pipeline. Is `App.js` triggering its own transpile, triggering gulp, or something else? What do you expect to happen?

I'm not yet sure where that bogus path is coming from... Does your error give any more stack trace information?

**Comment by mejiaj** [comment]
@bparksdev if you're using uswds-gulp I think you'd need to import the compiled CSS. Unless your app already has SCSS compilation in place, then you might not need uswds-gulp.

Are you using a framework? Are you able to provide us some steps to try to reproduce?

**Comment by bparksdev** [comment]
I started with create-react-app. So is the idea to use the generated styles.css, and if you make changes to the scss, simply recompile styles.css? I'm still newish to react, packages, etc.

**Comment by mejiaj** [comment]
@bparksdev, if you're going to be customizing the output CSS then you'd need to compile it.

Create-react-app shows you how that might look like. These [doc's](https://create-react-app.dev/docs/adding-a-sass-stylesheet/) might help.

**Comment by cannandev** [comment]
I'm having the same issue using create-react-app. Per docs, I've imported the uswds.scss like this: 
`@import '~uswds/dist/scss/uswds'`
in my `App.scss` file. On save, it begins to compile, then fails with the following error:

```
Failed to compile.

./src/App.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/App.scss)
Module not found: Can't resolve '../node_modules/uswds/dist/scss/core/fonts/merriweather/Latin-Merriweather-Bold.ttf' in '/Users/me/Sites/redux-todo/src'
```

Anyone solve this?

**Comment by pullias** [comment]
I had this same issues with a create-react-app project.
The solution was App.js import ./App.scss
The contents of App.scss are:

```
@import '~uswds/src/stylesheets/theme/_uswds-theme-general.scss';
@import '~uswds/src/stylesheets/theme/_uswds-theme-typography.scss';
@import '~uswds/src/stylesheets/theme/_uswds-theme-spacing.scss';
@import '~uswds/src/stylesheets/theme/_uswds-theme-color.scss';
@import '~uswds/src/stylesheets/theme/_uswds-theme-utilities.scss';

$theme-image-path: '~uswds/src/img';
$theme-font-path: '~uswds/src/fonts';
$theme-hero-image: '~uswds/src/img/hero.png';

@import '~uswds/src/stylesheets/packages/_required.scss';

@import 'uswds';
```

**Comment by plummer-flex** [comment]
The intended use case is not to import the theme files from `~uswds`. The intent is to copy the theme files into a project, adjust them to fit design needs, and then compile the uswds with the set theme variables.

In CRA, it would look like:

```
// App.scss

@import "./local/theme/path/uswds-theme-general";
@import "./local/theme/path/uswds-theme-typography";
@import "./local/theme/path/uswds-theme-spacing";
@import "./local/theme/path/uswds-theme-color";
@import "./local/theme/path/uswds-theme-utilities";
@import "./local/theme/path/uswds-theme-components";

@import "uswds";  // or whatever individual components you wanted

@import "./local/theme/path/uswds-theme-custom-styles";


// App.js
import "./App.scss";
```

**Comment by thisisdano** [comment]
I'm adding this into our current roadmap under `Getting started` so we can be sure to address issues like this when discussing integrating USWDS into a React project.
