### ISSUE TITLE
Layout grid breakpoint classes do not scale column width properly. 

### ISSUE THREAD

**Issue by DeLucaJ** [uswds/uswds#3519]
## Description

Using the breakpoint classes for layout grid does not change the width of the columns. All of the columns take up the width of the entire row and automatically render below each other. 

Disabling the width property of the parent class "grid-col" in developer tools produces the desired output but is clearly not a solution. 

## Example

```
<div class="grid-container">
	<div class="grid-row">
		<div class="grid-col-2">
			<p>Content</p>
		</div>
		<div class="grid-col-2">
			<p>Content</p>
		</div>
	</div>
</div>
```

**Comment by mejiaj** [comment]
@DeLucaJ which breakpoint classes did you try?

I created a codepen [here](https://codepen.io/mejiaj/pen/QWydmqE) if you'd like to fork and modify it with the things you've tried.

**Comment by DeLucaJ** [comment]
Sorry about the lateness. It must be something with my current application that is not interacting well, because everything seems to be working fine in codepen. Sorry for troubling you.

**Comment by mejiaj** [comment]
No worries! If you come across any issues feel free to open another issue. You can also join us on [slack](https://chat.18f.gov/). Maybe someone else has come across the same issue.
