### ISSUE TITLE
Provide guidance on linking to non-HTML files

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds#3521]
## Description

Many federal websites link to non-HTML like this example:

`A Strategy for American Innovation (PDF, 1.22 MB, 120 pages, October 2015)`

They occasionally leave off year or pages and sometimes add other agency-specific information.

It may be better for accessibility to place at least the "(PDF)" text inside the link to provide context for screen reader users. The same is true for the external link disclaimers that use something like https://fontawesome.com/v4.7.0/icon/external-link.

## Additional information

* [Original #uswds-public Slack thread](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1592834839158100)
* [WebAIM Links to Non-HTML Resources](https://webaim.org/techniques/hypertext/hypertext_links#non_html)
* [W3C Providing link text technique](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H30) (see example 6)
* [New Zealand's usability standard for linking to non-HTML files](https://www.digital.govt.nz/standards-and-guidance/design-and-ux/usability/linking-to-non-html-files/)
* [EPA's Web Standard for PDF Links](https://www.epa.gov/web-policies-and-procedures/web-standard-pdf-links)

**Comment by thisisdano** [comment]
This will be addressed in https://github.com/uswds/uswds-site/pull/1157

**Comment by thisisdano** [comment]
Done
