### ISSUE TITLE
Building custom CSS from tokens

### ISSUE THREAD

**Issue by darthmall** [uswds/uswds#3529]
Is there a recommended way to import the relevant SCSS for using the tokens without pulling in any of the CSS rules generated by the design system? I find that I end up pulling in a lot of CSS I don't need even if I'm careful about only importing specific packages in `styles.scss`.

I'd like to be able to use the mixins like `@include u-shadow(4)` and `@include typeset("heading", $theme-h5-font-size, $theme-heading-line-height)` to build my own CSS so that it's compact while adhering to the design system.

**Comment by thisisdano** [comment]
There is! Check this out: https://gist.github.com/thisisdano/7c6f117da94a3b89f7d4ecabe77a8c92
This lets you import only the core design language: tokens, mixins, and functions — but no actual CSS.

**Comment by darthmall** [comment]
That's perfect, thanks!
