### ISSUE TITLE
Footer: Allow customizable max-width

### ISSUE THREAD

**Issue by fafnirical** [uswds/uswds#3532]
## Description

The footer navs's max-width is currently hardcoded as `units("desktop")`. This can cause design issues when adjusting the `$theme-site-max-width` variable (or other `$theme-*-max-width` variables).

I propose a variable be introduced to allow USWDS Sass consumers to adjust the footer nav's max-width to keep it in sync with other max widths (like the header). To avoid breaking changes, the variable should default to `desktop`.

## Additional information [optional]

* `.usa-footer__nav` setting `max-width`: https://github.com/uswds/uswds/blob/develop/src/stylesheets/components/_footer.scss#L22
* `.usa-footer__primary-container` setting `max-width`: https://github.com/uswds/uswds/blob/develop/src/stylesheets/components/_footer.scss#L40

**Comment by thisisdano** [comment]
This seems like a good idea to me
