### ISSUE TITLE
Update the address template

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds#3538]
## Description
*Tasks to complete - Updated 12/17*
- [x] change street name label to `Street address`
- [x] change apt/suit.other to `Unit type`
- [x] place `Unit type` and `Unit number` on the same line, suggested 60/40 relationship
- [x] sentence case
- [x] determine if possible auto-complete metadata enhancements  for future
- [x] share updated PR with USCIS
- [x] [test accessibility](https://drive.google.com/file/d/1egyiB3f3VwTg6uGd6atPEPhvG7V0DjPU/view?usp=sharing) [sent 12/21][results scheduled for 1/6, retest 1/8]

*Tasks to complete - Updated 11/5*
[Reference:](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/cc-address-form/components/detail/address-form.html)

- [x] street address line two label: change to "Apt/Suite/Other" See USPS
![USPS](https://user-images.githubusercontent.com/67592482/99986246-f08e8a00-2d7c-11eb-8844-5ed0fa6fde2d.png)

- [x] street address line two:  add  combo box with all options listed in [USPS example](https://pe.usps.com/text/pub28/28apc_003.htm).
  - add "other" option to this list. 
  - Format: abbreviation - full word. Typing the abbreviation or full word grabs both the abbreviation and full word.
  - alphabetical order by full word
- [x] State combo box: Format "abbreviation - full word" Typing the abbreviation or full word grabs both the abbreviation and full word. See usps example:

![Screen Shot 2020-11-23 at 11 09 24 AM](https://user-images.githubusercontent.com/67592482/99986036-b2916600-2d7c-11eb-8b1b-d2eac5439d36.png)
![Screen Shot 2020-11-23 at 11 09 42 AM](https://user-images.githubusercontent.com/67592482/99986063-ba510a80-2d7c-11eb-85c3-71b8ab131ed4.png)
  - include all US territories and armed forces.
  - alphabetical order by full word
- [x] Update the guidance on https://designsystem.digital.gov/components/form-templates/#address-form to incorporate and link to related guidance: [USPS Publication 28](https://pe.usps.com/text/pub28/28c1_001.htm) defines the mailing standards in the United States (see this summary of applicable standards 🔒 for easier reference and search)

_________________________
**ORIGINAL ISSUE INFO**

We received the following feedback on [address form template](https://designsystem.digital.gov/components/form-templates/#address-form) component: 

### Current Template

<img width="632" alt="Screen Shot 2020-07-07 at 4 48 36 PM" src="https://user-images.githubusercontent.com/400690/86841280-be041f00-c071-11ea-98b9-536d7deb129c.png">

### USCIS Example

The [USCIS Change of Address app](https://egov.uscis.gov/coa/addressChange.do) is an example of a well-structured form. 

<img width="322" alt="Screen Shot 2020-06-17 at 1 32 46 PM" src="https://user-images.githubusercontent.com/400690/86935858-4c78af00-c10b-11ea-82c2-1c082854d93a.png">

## Additional information

Some good reference on the mailing address standards:

* [USPS Publication 28](https://pe.usps.com/text/pub28/28c1_001.htm) defines the mailing standards in the United States (see [this summary of applicable standards](https://drive.google.com/file/d/1T1dmOfuBoOypUw4FbOSYtOHaTGUGE9MC/view?usp=sharing) 🔒 for easier reference and search)
* Specifically, look at the USPS Publication 28 appendixes for the [unit types](https://pe.usps.com/text/pub28/28apc_003.htm) and [bytes](https://pe.usps.com/text/pub28/28c1_004.htm)
* It is recommended that Commercial Mailers use [CASS™ approved](https://postalpro.usps.com/certifications/cass) software to analyze, parse, correct, validate, and format addresses according to the standard. 
* List of [CASS™ Vendors](https://postalpro.usps.com/cass/Vendor_ServiceBureaus_CurrentCycle)
* [USPS Mailer’s Technical Advisory Committee (MTAC)](https://postalpro.usps.com/mtac#anchor-5) works to improve mailing address quality and they have created the MTAC- Address Quality Methodologies document as a list of best practices/standards for commercial mailers
* The [Universal Postal Union](http://www.upu.int/en.html) is responsible for managing the address standards for all of it’s 131 member countries. Each member country has a different layout and organization of the data elements when sending mail to a foreign country. They maintain the [S42 Standard](http://www.upu.int/en/activities/addressing/s42-standard.html), which provides the layout and format for each member country.

**Comment by jAigret-Bix** [comment]
@afeijoo @chazchumley confirm tasks needed to complete: 1. remove "street address 2"  line in current template 2. replace with line: Apt/floor/suite  and line: unit number, as seen in USCIS example provided
![Screen Shot 2020-09-14 at 4 29 52 PM](https://user-images.githubusercontent.com/67592482/93135059-b0899780-f6a7-11ea-886e-2891d300ad6b.png)

**Comment by mejiaj** [comment]
@chazchumley the current template lives in `src/components/07-form/templates/address-form.njk`.

Here's what the form looks like. [Preview →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/components/preview/address-form.html)

---

You can branch off of `develop`, something like `cc-address-form`. Once you're ready for a PR run through the checklist items in that PR.

![image](https://user-images.githubusercontent.com/3385219/93139187-e0d03680-f6a5-11ea-8bf2-087b513eab9b.png)

For accessibility testing I use the AXE browser plugin and manually run it through voiceover on Safari.

**Comment by afeijoo** [comment]
@jAigret-Bix and @chazchumley Yes, plus: 3. Replace `ZIP` with `ZIP code` and 4. Update the guidance on https://designsystem.digital.gov/components/form-templates/#address-form to incorporate and link to the references above.

**Comment by jAigret-Bix** [comment]
Example from USPS. Note address line two. "Apt/Suite/Other"
![Screen Shot 2020-11-02 at 2 09 30 PM](https://user-images.githubusercontent.com/67592482/97908830-3c698880-1d15-11eb-91a5-31a19c958947.png)

**Comment by mejiaj** [comment]
Guidance is updated in this PR https://github.com/uswds/uswds/pull/3629

**Comment by mejiaj** [comment]
We should test and validate if any of these `autocomplete` attributes would enhance the template

>"street-address"
    A street address. This can be multiple lines of text, and should fully identify the location of the address within its second administrative level (typically a city or town), but should not include the city name, ZIP or postal code, or country name.
"address-line1", "address-line2", "address-line3"
    Each individual line of the street address. These should only be present if the "street-address" is not present.
"address-level4"
    The finest-grained administrative level, in addresses which have four levels.
"address-level3"
    The third administrative level, in addresses with at least three administrative levels.
"address-level2"
    The second administrative level, in addresses with at least two of them. In countries with two administrative levels, this would typically be the city, town, village, or other locality in which the address is located.
"address-level1"
    The first administrative level in the address. This is typically the province in which the address is located. In the United States, this would be the state. In Switzerland, the canton. In the United Kingdom, the post town.
"country"
    A country or territory code.
"country-name"
    A country or territory name.
"postal-code"
    A postal code (in the United States, this is the ZIP code).

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by chazchumley** [comment]
@mejiaj I know for all government sites, having auto-complete on fails security scans and it has always been requested to have auto-complete turned off.

**Comment by jAigret-Bix** [comment]
Feedback:  I am not sure if you set data field length standards but if so you might want to limit the fields. I was able to type over 100 characters into the Street address and City fields. Our previous investigation into City name length in the united states showed that 50 characters would meet all of the current city names. Street address is a little more complicated but 50 characters should cover that too. The problem come when you use the address to send mail. Space on the envelope address block area may not allow 50 characters in each of these areas so you then have to abbreviate the City name or wrap the street address line up. But this may be getting more into the individual use cases or deeper than the scope of what you are trying to do.

**Comment by jAigret-Bix** [comment]
Team has decided not to add a character count to the address form as this gets into individual test cases. email sent on 1/5 to USCIS giving them an update and asking for recommendations if the zip code field should be limited to numbers and dashes only.

**Comment by jAigret-Bix** [comment]
@thisisdano  @mejiaj 1/7 from USCIS: "To my knowledge the USPS Domestic Zip Codes are all numbers and consist of 5 digits, dash then 4 digits. For international postal codes there are some letters used. Universal Postal Union should have that data but I think you have to pay for it. Here is a list on [Wikipedia](https://en.wikipedia.org/wiki/List_of_postal_codes) (accuracy may not be good)."

**Comment by jAigret-Bix** [comment]
1/7 confirmed w @thisisdano  --  will constrict the zip-code field to numbers / dash. A sentence will be added into the guidance specifying this is domestic address template.
