### ISSUE TITLE
Data Table with Features

### ISSUE THREAD

**Issue by krunal-odedra** [uswds/uswds#3553]
Data Table with Features like Multi-Section, Group Actions, Sorting by Column Header

## Description

**Feature List :** 
- **Sorting** : sort by column header ( sort icon needed ).
- **Filtering** : filter content of the table by header.
- **Filtering** : tagged filter on table.
- **Group Action & Multi-Select Checkbox** : to have a group action table raw/elements like copy, delete, mark as read.
- **Expandable Row** : accordion style expandable row for detail
- **Raw Action** : allows you to perform actions at each row level.
- **Table Search** : allow you to search content of the table.
- **OverFlow Menu** : More action on each row of the table.

## Additional Help

Carbon Design System : https://www.carbondesignsystem.com/components/data-table/usage

**Comment by thisisdano** [comment]
We'll be adding sort to our tables, but the rest of these are not in our roadmap, Tagging for future consideration
