### ISSUE TITLE
File Input: Create disabled state styling

### ISSUE THREAD

**Issue by jaredcunha** [uswds/uswds#3556]
## Description
The file input needs to have some styling for a disabled state. While disabling the input prevents interactions, there should be a visual affordance that the component is not active. 

Any solution should be CSS-only, so that if an application that toggles between disabled/enabled states is low touch, and simply swaps out classes and attributes. Changes to content could burden developers using this component and impact backward compatibility.

**Comment by jaredcunha** [comment]
Here's a possible solution:
<img width="537" alt="Screen Shot 2020-07-17 at 5 17 16 PM" src="https://user-images.githubusercontent.com/1094951/87831398-658f0780-c851-11ea-8e6a-41a84a410a4c.png">

This disabled state would not have a hover effect. Two things I'm not certain about:
- The color contrast on the text still meets WCAG AA standards. It's just opacity of `.5` and not specific color. Not sure if that's a consistent approach.
- Is the strikethrough necessary?

**Comment by mejiaj** [comment]
There are disabled colors here you could use:
https://github.com/uswds/uswds/blob/af260eb4fbe2acaf46f261071fdb68c5fd07292e/src/stylesheets/settings/_settings-color.scss#L119-L123

**Comment by jaredcunha** [comment]
Oh, that's awesome, @mejiaj. Thank you!
