### ISSUE TITLE
Reverse engineer JavaScript current build process and see how it can be "lightened"

### ISSUE THREAD

**Issue by sarnikbixal** [uswds/uswds#3562]
Troubleshoot current JavaScript build for USDWS_all.js and check if dependencies can be cleaned up and lightened. Research event delegation for modularized components and see how to implement in a new build.

**Comment by jAigret-Bix** [comment]
Current sprint 7.27: create all build.  
Next sprint 8.10: build individually, convert remaining components.

**Comment by jAigret-Bix** [comment]
Sprint 8:10: 
•	Build individually 
•	Convert remaining components

**Comment by thisisdano** [comment]
Looks like we will leave the use of behaviors.js as-is.
