### ISSUE TITLE
Provide USWDS components in the global scope.

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3570]
Currently you [need to have a bundler](https://designsystem.digital.gov/documentation/developers/#js-customization) to individually work with components outside of a generic implementation.

This limits the sites where custom components can be used as many modern site dynamically load HTML after the page loads which isn't compliant with the current process.

Adding a `USWDS` variable to the global scope allows developers the opportunity on more dynamic sites that don't use a bundler to be able to initialize and interact with components.

**Comment by thisisdano** [comment]
@mejiaj Can you give an update on this one?

**Comment by sarnikbixal** [comment]
We do have something in place for this. Although it is a bit un intuitive it will provide for modules to be imported and initialized within modern frameworks (React/Angular/Vue). If you scroll down from the JS documentation you will see:

`import USWDS from "../node_modules/uswds/src/js/components";
const { characterCount, accordion } = USWDS; // deconstruct your components here`

This section explains how to be able to handle components on rendered only pages.

**Comment by Swimburger** [comment]
I'm trying to create a sample on jsbin or jsfiddle to reproduce some issues we're having with USWDS, but I can't find a way to develop a minimal reproducible sample without a uswds global variable for components.
Is there guidance to grab uswds component JavaScript straight in the browser?
