### ISSUE TITLE
Combo Box: Update z-index for Combo Box list

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3571]
## Description

The combo box list doesn't have a high enough z-index to overlap other positioned element such as the buttons for another combo box it could be placed above.

The z-index should be increased to make sure it covers non dialog items.

<img width="459" alt="Screenshot 2020-08-03 09 58 02" src="https://user-images.githubusercontent.com/1385752/89196565-01b64f80-d570-11ea-81e8-170ad2ff8d11.png">

<img width="426" alt="Screenshot 2020-08-03 09 58 14" src="https://user-images.githubusercontent.com/1385752/89196568-03801300-d570-11ea-9008-dec716c5a397.png">

**Comment by Pharmasolin** [comment]
@wbyoko hi, fix was merged into dev branch, I think this issue can be closed.

**Comment by wbyoko** [comment]
@thisisdano ^^^
