### ISSUE TITLE
File input preview class names are not valid BEM syntax

### ISSUE THREAD

**Issue by aduth** [uswds/uswds#3573]
## Description

The [File Input component](https://designsystem.digital.gov/components/form-controls/#file-input) assigns a class name to preview images which is not valid per conventional [BEM syntax naming](http://getbem.com/naming/).

Example:

```
usa-file-input__preview__image--generic
```

My understanding is that a BEM class name should have at most a single occurrence of the double-underscore `__` separating the block and element.

From [base documentation](https://github.com/uswds/uswds):

>Uses a [BEM](http://getbem.com/) approach for naming CSS selectors. Blocks are separated from elements with two underscores (`__`).

Instead, I would expect: `usa-file-input__preview-image--generic`

## Steps to reproduce the issue

1. Navigate to [File Input demo](https://components.designsystem.digital.gov/components/preview/file-input.html)
2. In the "Multiple files" demo, choose an image file to upload
3. Inspect the rendered image to see assigned class names

## Additional information

Relevant source:

https://github.com/uswds/uswds/blob/37fb18514f856101148ba7e0de4c1c16118ff048/src/js/components/file-input.js#L21

https://github.com/uswds/uswds/blob/37fb18514f856101148ba7e0de4c1c16118ff048/src/stylesheets/elements/form-controls/_file-input.scss#L132-L176

**Comment by thisisdano** [comment]
Good catch. cc @mejiaj
