### ISSUE TITLE
Improve documentation on how to initialize dynamic components from javascript.

### ISSUE THREAD

**Issue by mbucknell** [uswds/uswds#3575]
## Description

We have a need to be able to create components dynamically from javascript. Although documentation is included on JS customization (https://designsystem.digital.gov/documentation/developers/#js-customization), it is lacking in details, such as how to access the individual components, what functions are available, and what those functions do. For my team, we are implementing a dynamic date range picker and I found that we needed to use the init function for both datePicker and dateRangePicker. The init function isn't mentioned at all in the documentation. Other functions such as add are available, but not hide, show, or toggle. I was able to determine what to do by debugging the USWDS code.

This would benefit those who use single page frameworks such as Vue, React, and Angular, as well as those of us using other ways to dynamically create components to more easily implement USWDS components.

**Comment by jkreft-usgs** [comment]
#3570 is related

**Comment by ConnorDY** [comment]
>I found that we needed to use the init function for both datePicker and dateRangePicker. The init function isn't mentioned at all in the documentation.

@mbucknell How did you do this? What is the init function?

**Comment by mbucknell** [comment]
I successfully initialized tooltips and date pickers using the .on function as described in the the new documentation. However, for the dateRangePicker, I need to do the following:
```
components.datePicker.init(dateRangeContainer);
components.dateRangePicker.on(dateRangeContainer);
```
where dateRangeContainer was the nod containing the markup for the start and end date pickers. If I used "on" rather than "init" to initialize the date pickers, the calendar icons would appear but you could not open the calendar widgets. The guidance should be updated to include this special case.

**Comment by ConnorDY** [comment]
@mbucknell I've got the Date Picker as a standalone React component that calls `datePicker.on(containerEl)` when created and then the Date Range Picker as a wrapper for two Date Picker components that calls `dateRangePicker.on(containerEl)` when created. `containerEl` refers to the internal wrapping/parent `<div>` element around each component and the usage looks like:
```jsx
<DateRangePicker>
  <DatePicker>
    Start Date Label
  </DatePicker>

  <DatePicker>
    End Date Label
  </DatePicker>
</DateRangePicker>
```

Everything works as expected this way so I don't think you should need to call `init` instead of `on` for the Date Picker components.

**Comment by mbucknell** [comment]
That's very similar to my implementation, but mine doesn't work. I am using D3 to render the HTML. As I said before, if I use "on" for both the date picker and the dateRangePicker, I get the calendar icons, but clicking them does not work. I am using rollup to bundle and buble to compile the javascript. Perhaps that is the difference.
