### ISSUE TITLE
Sync sass modules  to up-to-date code base

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3582]
Description:
Sync up sass modules on the branch `use-sass-modules` to make sure it's up-to-date with latest USWDS features.
Right now it's at 2.7.0. We have a PR for syncing it up to 2.8.0 
Hope to incorporate this new standard into the patternlab work.

Acceptance criteria: 
- [ ] sass modules is up-to-date with latest USWDS 2.8.0 release.

**Comment by mejiaj** [comment]
@thisisdano I've created a branch for testing on USWDS-Site called [`jm-use-sass-modules`](https://github.com/uswds/uswds-site/tree/jm-use-sass-modules).

Working through issues that pop up. Right now it's mostly working, just running into issues w/ [`_uswds-theme-custom-styles.scss`](https://github.com/uswds/uswds-site/blob/jm-use-sass-modules/css/_uswds-theme-custom-styles.scss#L16)

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds/pull/3612
