### ISSUE TITLE
USWDS - Typography: Allow for responsive font-sizing in settings.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3590]
## Description

As a USWDS user, I'd like to be able to set different font sizes on different breakpoints.

This idea originally popped up in slack [here](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1597781227017000).

## Additional information [optional]
Currently you can use responsive utilities to set the sizing, but it would be nice to do this via SASS settings. First we need to see what this level of effort is.

**Comment by thisisdano** [comment]
This is not on our current roadmap, but I've tagged it for later consideration
