### ISSUE TITLE
2.9.0 Release

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3597]
2.9.0 Release 

- cut off date` 9/4`  
- official release `9/10`
- monthly call `9/17`
- USWDS fundamentals and getting started guide
- sample contract language for 21st century IDEA

**Tasks**
- [x] Anchor
- [x] Step indicator
- [x] Time picker
- [x] Guidance surrounding how we talk about components (Katie)
- [x] Run NPM audit, capture audit in POAM

**Comment by thisisdano** [comment]
Released: https://github.com/uswds/uswds/releases/tag/v2.9.0
