### ISSUE TITLE
Research and Develop NPM Packaging and Javascript Imports of Modular Components

### ISSUE THREAD

**Issue by sarnikbixal** [uswds/uswds#3602]
Research and develop a package that can be used to include components as modules in the following types of projects:

- Vanilla JavaScript/Jquery
- React
- Angular
- View

**Comment by sarnikbixal** [comment]
Research has concluded we will continue with the current state of the javascript. We will re-factor the current NPM package to be more lean and include entry points to each component for easier importation of modules in modern javascript frameworks without affecting the integrity of the development platform.

**Comment by jAigret-Bix** [comment]
Issue can be closed
