### ISSUE TITLE
Bring existing SASS module into site repo

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3617]
Bring existing SASS module into site repo

- [X] Import SASS modules into site (done)
- [x] Port over current styles 
- [x] Create strategy for importing and customization 
- [x] Testing

**Comment by thisisdano** [comment]
Done in 2.10 Alpha 0 and testing in 2.01 Beta 0:
https://github.com/uswds/uswds/releases/tag/v2.10.0-alpha.0
https://github.com/uswds/uswds/releases/tag/v2.10.0-beta.0
