### ISSUE TITLE
Accent warm button variation is missing from button components

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3618]
All theme colors are displayed on the Button component page except for accent warm. I expect to see all theme colors including accent warm: https://components.designsystem.digital.gov/components/detail/buttons--default.html

<img width="1276" alt="Screen Shot 2020-09-11 at 10 57 34 AM" src="https://user-images.githubusercontent.com/5249443/92957580-a0f71e00-f41d-11ea-8052-044de8f21016.png">

Related to https://github.com/uswds/uswds-site/issues/1047

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/uswds/pull/3623
