### ISSUE TITLE
Table formatting: use nth-child and hover for improved readability

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3619]
## Zendesk ticket #19902

The Office of Justice Programs websites utilize USWDS via Drupal. Table content is integral but user feedback indicates readability could be enhanced, particularly for low-vision audiences. We’ve reviewed the digital.gov 2020 Product Roadmap and Component Maturity Lifecycle on Github. We’re hoping to ascertain if it’s feasible to incorporate the below request into official USWDS components or if similar is already in the pipeline. Specifically, we are interested in nth-child and hover for improved readability. Please see below for code sample and rationale. Any information you could provide would be greatly appreciated.

Codepen Demo: https://codepen.io/JenStagner/pen/QWNrjBr (https://codepen.io/JenStagner/pen/QWNrjBr)

Code Request Example:

tr:nth-child(even) {background-color: #f1f3f4}

tr:nth-child(odd) {background-color: #fff}

tr td:hover {background-color: #b1e5f3;}

WebAIM Color Contrast Check:

Background/foreground color contrast ratio combinations all exceed WCAG AA, AAA standards, at 11:09:1, 12:34:1, and 9:01:1.

Supporting Documentation:

Zebra tables for readability: https://www.w3.org/WAI/tutorials/tables/tips/ (https://www.w3.org/WAI/tutorials/tables/tips/)

Nth child for readability: https://www.w3.org/Style/Examples/007/evenodd.en.html (https://www.w3.org/Style/Examples/007/evenodd.en.html)

**Comment by jprasmussen** [comment]
In the code pen example, how do you all feel about highlighting the entire `tr` instead of just the hovered `td`.

Changing this: 
```
tr td:hover {
  background-color: #b1e5f3;
}
```
to this:
```
tr:hover td {
  background-color: #b1e5f3;
}
```
Which should produce this:
<img width="1103" alt="Screen Shot 2020-09-14 at 12 06 46 PM" src="https://user-images.githubusercontent.com/1149100/93121890-d3ee1b80-f682-11ea-8744-d80220a35a1e.png">

**Comment by sknep** [comment]
We haven't added a hover state yet, but alternating horizontal "zebra" stripes were added in the latest USWDS Table update: https://designsystem.digital.gov/components/table/
