### ISSUE TITLE
Create interview guide for Accelerator

### ISSUE THREAD

**Issue by Ben-Judy-Flexion** [uswds/uswds#3634]
Create an [interview guide](https://docs.google.com/document/d/1Do9Yq3P6G1eFc6cYBVtq3PURH-DtpPrpBxRvMCILRvk/edit) for the USWDS Accelerator project.

**Comment by Ben-Judy-Flexion** [comment]
Interview guide here: https://docs.google.com/document/d/1CixY91rx0XXWJeJJcI66IoiEdK6TMmosyN4qBx_to6k/edit

**Comment by afeijoo** [comment]
@Ben-Judy-Flexion Can you please move the guide to the [Accelerator project folder](https://drive.google.com/drive/folders/1RXhtHz952jronAVNIy7YQSd9nPKgAy9A)?

**Comment by Ben-Judy-Flexion** [comment]
Done! The Interview Guide is now [here](https://docs.google.com/document/d/1Do9Yq3P6G1eFc6cYBVtq3PURH-DtpPrpBxRvMCILRvk/edit), in the GSA Google Drive space.
