### ISSUE TITLE
Landscape Analysis: Pagination

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3642]
**Landscape Analysis: Pagination**
[Roadmap item](https://github.com/orgs/uswds/projects/4#card-35974199)

- [x] Research and compile legacy Documentation
-Links to existing background information, including possible existing research done by other teams, and applicable policies, standards, or guidelines that apply
- [x] Evaluate the usability of the feature
- [x] Heuristic Analysis, Landscape Analysis or Competitive Analysis
- [x] Write a summary of the findings from the analysis.
- [x] Update research plan
- [x] Review w Client 10/7

[Landscape Analysis](https://docs.google.com/document/d/1jdOTlbP45lCsD-GLNcizdifKw7u3p4vEzPPHPlHvvsE/edit?usp=sharing)
[Visual Reference](https://docs.google.com/document/d/1As9N9UYoWEQcm6TPPq-76u82MCCgDLZWVcweO_--xoc/edit?usp=sharing)

**DoD**
All tasks are complete

**Comment by allie-shaw** [comment]
10/13 – Updated and sent for review [via Slack](https://gsa-tts.slack.com/archives/C050HRGN7/p1602702563114500).
@jAigret-Bix
