### ISSUE TITLE
Landscape Analysis: Tabs

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3643]
** Landscape Analysis: tabs**
[Roadmap item](https://github.com/orgs/uswds/projects/4#card-35974114)

- [x] Research and compile legacy Documentation
-Links to existing background information, including possible existing research done by other teams, and applicable policies, standards, or guidelines that apply
- [x] Evaluate the usability of the feature
- [x] Heuristic Analysis, Landscape Analysis or Competitive Analysis
- [x] Write a summary of the findings from the analysis
- [x] Update research plan
- [x] Review w client 10/7

[Landscape analysis](https://docs.google.com/document/d/1Nfk_pFMfVX24wouclR204A9ruziklSFLYpAT4alFDRk/edit?usp=sharing)
[Visual reference](https://docs.google.com/document/d/1EyA4hXK2DsOu8vGWHCLrjgcJ596VypbhNxsOLJ4G-1o/edit?usp=sharing)

**DoD**
All tasks complete

**Comment by allie-shaw** [comment]
10/13 Revised and sent for review [via Slack](https://gsa-tts.slack.com/archives/C050HRGN7/p1602702563114500).
@jAigret-Bix
