### ISSUE TITLE
Establish Team Agreements

### ISSUE THREAD

**Issue by Ben-Judy-Flexion** [uswds/uswds#3646]

**Comment by Ben-Judy-Flexion** [comment]
Create a Team Agreements doc and have the entire team contribute & agree.
For reference, here are the [team agreements from the 10x Advanced Form Controls Phase 3 project](https://drive.google.com/file/d/1rEN3iUPZ9am2tOei0ARNTD8t38THbLpH/view?usp=sharing).

**Comment by Ben-Judy-Flexion** [comment]
Here is our [Team Agreements doc](https://docs.google.com/document/d/1MJNckPv3sm-FTxPgfkhG7cZjEiTfS6Ja3Z2Dv6fJ_wI/edit).

**Comment by debjudy** [comment]
Team discussed on Wednesday after standup

[Working team agreements ](https://docs.google.com/document/d/11YmdeMknq-kC-LMzMvaTRtjvI_AGy9twx8iq3oaLCnA/edit?usp=sharing)

Follow-ups
- Mural for ideas on guiding principles and collorabation
- Engineering process
- Interview process

**Comment by debjudy** [comment]
Description of board columns added. Kim created Mural for brainstorming activity.  Ben linked Interview process.

**Comment by debjudy** [comment]
Update team agreements with values and norms and moved to GSA https://docs.google.com/document/d/1MTcG1hH5EltJ5Y_MeSOXENRGNCeW5d6-PphAgzpg_X4/edit#heading=h.gjdgxs
