### ISSUE TITLE
Indentifier requirements creating problems

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#3653]
If you have "light" or "bold" turned off (set to false) in the theme settings, there is a compilation error because the new identifier component (_identifier.scss) requires "light" (line 78) and "bold" (line 81).

**Comment by thisisdano** [comment]
Yeah, I see where that could happen. Perhaps we can add some kind of conditional for "light" at least (falling back to "normal"). Bold might be a little more challenging, as the fallback is not so obvious. I'm disinclined to make this a setting to try and preserve as much continuity between implementation as possible, but we can work to better handle false values. 

As a temporary fix, you could adjust the value of `$theme-font-weight-light` to `400` and `$theme-font-weight-bold` to whatever the "best equivalent" might be in your project.

**Comment by stphnwlkr** [comment]
Light is the issue for me, since I have 300 as the body font. In the theme settings there should just be the option to set light, regular, and bold to match the design if it is not inheriting defaults.
