### ISSUE TITLE
Update  documentation regarding character count.

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3658]
See https://github.com/uswds/uswds-site/issues/968

There is a nuance for using modern libraries such as Angular/React.

** To import an individual component **

import USWDS from '../node_modules/uswds/src/js/components';
const { characterCount } = USWDS; // deconstruct your components here
Please see below how to implement for each:

React (hooks):

function App() {
  useEffect(() => {
     characterCount.on(ref);
  })
}
Angular (hooks):

export class App implements OnInit {
  constructor() {}

  ngOnInit() {
    characterCount.on(ref);
  }
}

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds/pull/3723
