### ISSUE TITLE
Create attribution styling and guidance

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3675]
Possible content
* Content source -- individual, agency, etc.,
* Link to source
* Date(s) - original publish, last update date, etc.
* Version history

Examples
* CDC: https://www.cdc.gov/coronavirus/2019-ncov/daily-life-coping/caring-for-children.html
* Coronavirus FAQ: https://faq.coronavirus.gov/how-can-i-protect-myself/
* Gov.UK Coronavirus: https://www.gov.uk/government/publications/coronavirus-covid-19-meeting-with-others-safely-social-distancing
* BBC: https://www.bbc.com/news/world-us-canada-54035099

10/14 review # 2 on Dan's list

DESIGN ASSETS
- [x] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback
- [ ] 20% - Draft user story & clarify the problem(s) / user needs
- [x] 30% - Low-fi design review
- [ ] 40% - Get community feedback on initial, Hi-fi designs
- [ ] 50% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews)
- [ ] 20% - Draft guidance review no. 1 (minimum 2 bullets each section)
- [ ] 40% - Get community feedback on draft guidance
- [ ] 50% - Draft guidance review no. 2 (accessibility focus)
- [ ] 60% - Draft guidance review no. 3 (w/ Dan)
- [ ] 80% - Add component to research report and slide deck
- [ ] 100% - PR approved by Dan

CODE
- [ ] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [ ] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [ ] 40% - Get community feedback or conduct tests with users, round 1
- [ ] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [ ] 80% - Get community feedback or conduct tests with users, round 2
- [ ] 100% - PR approved by Dan

**Comment by afeijoo** [comment]
Example from NASA: https://activate.larc.nasa.gov/

**Comment by jonadecker** [comment]
Throwing this back into the backlog as it has been de-prioritized in favor of Link guidance

**Comment by thisisdano** [comment]
No longer on the roadmap but tagged for future consideration
