### ISSUE TITLE
Create Media Player component 

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3678]
Need to figure out where where something like a YouTube embed be insufficient?

* Support for hi-res video, low res video and audio.
* Accessibility: degradation for slower connections, closed captioning, transcripts

Examples
* CDC (video): https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/prevention.html
* Gov.UK Coronavirus (video):
 https://www.gov.uk/government/publications/covid-19-guidance-for-taking-swab-samples/how-to-use-a-nose-swab-kit-to-test-for-covid-19-a-guide-for-social-care-staff
 https://www.gov.uk/coronavirus (halfway down page)
* NHS.UK (audio) https://www.nhs.uk/conditions/stress-anxiety-depression/moodzone-mental-wellbeing-audio-guides/

Zendesk inquiry on this topic
[20196](https://searchusa.zendesk.com/agent/tickets/20196)

### Tasks
- [ ]  Landscape Analysis
- [ ]  Sketch/Design in Figma
- [ ]  Identify users for testing
- [ ]  Usability Testing
- [ ]  Client Review
- [ ]  Finalize Design/Convert to Sketch
- [ ]  Documentation

**Comment by thisisdano** [comment]
No longer on the roadmap but tagged for future consideration
