### ISSUE TITLE
Expand Identifier component

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3681]
Expanded identifier for cross-agency task forces where there can be 5-20+ agencies involved

### Tasks
- [ ]  Landscape Analysis
- [ ]  Sketch/Design in Figma
- [ ]  Identify users for testing
- [ ]  Usability Testing
- [ ]  Client Review
- [ ]  Finalize Design/Convert to Sketch
- [ ]  Documentation

**Comment by thisisdano** [comment]
No longer on the roadmap but tagged for future consideration
