### ISSUE TITLE
Publish research report

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3684]
Target is 10/21 to deliver research report

- [x] Discuss report outline
- [x] Determine where/how it will be published (Previously discussed published on USWDS wiki)
- [x] Create a comms/outreach plan

**Comment by debjudy** [comment]
Collaborated on draft and focused on audience.  Will create deck and assign sections to get build information. 
Details of approach: https://docs.google.com/document/d/1gCUHA25xfa-bxmQVYPB0Gzh6z459iYh3MLlAIG6iAP0/edit?usp=sharing

**Comment by debjudy** [comment]
@afeijoo The last task on this is to create a comms plan.  Since we are focusing on executive readout, do we need a comms plan at this point?

**Comment by afeijoo** [comment]
@debjudy and @jonadecker Please take a look at the draft goals, objectives, and comms plan in the [outline](https://docs.google.com/document/d/1gCUHA25xfa-bxmQVYPB0Gzh6z459iYh3MLlAIG6iAP0/edit). After your review, I'll route to our outreach team for their awareness.

**Comment by jonadecker** [comment]
Looks really good @afeijoo. Reviewed and made some suggestions and comments.

**Comment by debjudy** [comment]
@afeijoo Ammie - looks good. I particularly like the follow-up thank you email to interviewees.  
Before calling complete task complete though, @uxforgood Natalie would you please review and let us know if you have any concerns?

**Comment by uxforgood** [comment]
@afeijoo and @debjudy left a couple questions/comments but don't see any concerns!
