### ISSUE TITLE
USWDS - Breadcrumb: Possible invalid margin token.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3692]
### Describe the bug
Breadcrumb has a negative margin in [_breadcrumb.scss:78](https://github.com/uswds/uswds/blob/develop/src/stylesheets/components/_breadcrumb.scss#L78)

```scss
.usa-breadcrumb__list {
  @include unstyled-list;
  @include u-display("block");
  @include u-margin(-$theme-focus-width);
  @include u-padding($theme-focus-width);
}
```

Which is causing this error:
```bash
Message:
    node_modules/uswds/dist/scss/core/mixins/utilities/_margin.scss
Error: '`-"2px"` is not a valid `margin` token. You should correct this. Standard `margin` tokens:  neg-1px, neg-2px, neg-05, neg-1, neg-105, neg-2, neg-205, neg-3, 1px, 2px, 05, 1, 105, 2, 205, 3, 4, 5, 6, 7, 8, 9, 10, 15, 05em, 1em, 105em, 2em, 0'
   ╷
11 │     margin: get-uswds-value(margin, $value...) #{$important};
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/uswds/dist/scss/core/mixins/utilities/_margin.scss 11:13  margin-n()
  node_modules/uswds/dist/scss/core/mixins/utilities/_margin.scss 60:3   u-margin()
  node_modules/uswds/dist/scss/components/_breadcrumb.scss 78:3          @import
  node_modules/uswds/dist/scss/packages/_uswds-components.scss 28:9      @import
  node_modules/uswds/dist/scss/uswds.scss 13:9                           @import
  _scss/styles.scss 31:9                                                 root stylesheet
```

### Steps to reproduce the bug
1. clone https://github.com/mejiaj/digitalgov-pra/tree/jm_update-uswds-2.9.0
1. cd into `digitalgov-pra`
1. npm install
1. bundle install
1. npm run start
1. See error

### Expected behavior
To compile properly and not complain about an invalid value or use the `neg-2` as a value.

### Screenshots
Add screenshots to help provide context, if applicable.

### System setup
- **USWDS version: 2.9.0**
- **Device: Laptop**
- **Operating system: OSX v10.15.6**
- **Browser and version: Firefox 82.0b4 (64-bit)**

### Additional context
Add any other context about the problem.

**Comment by thisisdano** [comment]
We should probably split this out of the mixin and use something like the following to be as flexible as possible without a lot of additional code:

```scss
margin-left: #{units($theme-focus-width)} * -1;
margin-right: #{units($theme-focus-width)} * -1;
```

**Comment by thisisdano** [comment]
As a quick fix, they could change the value of `$theme-focus-width` to `2px` (no quotes) instead of `"2px"` (with quotes)
