### ISSUE TITLE
public-sans.digital.gov accessibility testing

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3734]
Task on https://github.com/uswds/uswds-team/issues/7
In FY 2020, based on the Modernization Plan for public-sans.digital.gov🔒, we will make the following improvements on https://public-sans.digital.gov:

 - [x] Incorporate a11y testing (est. 10-20 hours)

- [x] Test key pages (home and specimen). Begin w lighthouse and move to accessibility insight. Good selection of representative pages.

**Comment by mejiaj** [comment]
@thisisdano should we be using `master` or `develop`? They seem to be very different.

---

Created a test branch called `jm-a11y-testing` based off of `master`. It removes some packages, updates nvmrc, and adds a local accessibility test.

✅ No a11y issues found on home/specimen page.

**Comment by mejiaj** [comment]
## PR submitted
https://github.com/uswds/public-sans/pull/179

**Comment by thisisdano** [comment]
OK, all done.
