### ISSUE TITLE
October monthly call (10.15) & activities

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3743]
- [x] Monthly call prep meeting 10/6
- [x] Pre activities: [script submission and review](Monthly call Script)
 - [x] Prep // run through meeting
 - [x] Monthly call 10/15
 - [x] Post call sync
 - [x]  [Create post-call draft slack post](https://docs.google.com/document/d/1kC-LWAryXNcnbeeM--XIldquzu4snrYuBiTXziSryAk/edit#heading=h.p3hvn8jllvv2) in gDoc template for review and approval
 - [x] Share out call recap [#uswds-public](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1605809405294200).

**Comment by thisisdano** [comment]
Holding until we can also launch the design assets and the beta release
