### ISSUE TITLE
A few issues with the Date Picker component

### ISSUE THREAD

**Issue by ConnorDY** [uswds/uswds#3749]
### Describe the bug
I've found a few problems with the Date Picker component:
1. If you try to set a default or existing `value` on the `<input />`, the field is cleared out once the USWDS JS loads.
2. While setting the `disabled` attribute on the `<input />` works, the `readonly` attribute still allows changing the date via the calendar.
3. Similar to a previous issue with the combo box, the date picker does not emit proper change events  (see: https://github.com/uswds/uswds/pull/3487).

### Steps to reproduce the bug
Recreating these issues should be pretty self-explanatory given the description of the issues.

### Expected behavior
1. The `value` attribute should not be overwritten when the USWDS JS loads.
2. The `readonly` attribute on the `<input />` should also disable the calendar button like the `disabled` attribute does.
3. Changing the value via the calendar should emit the proper change event on the `<input />`.

**Comment by kkoskelin** [comment]
I've looked at the source and I see that the original element gets cloned and hidden.  I wonder if the original element and the cloned element were to "switch places" so that the original does not get its `id` wiped out, and all listeners or behaviors attached to one become attached to the opposite that some issues might be resolved.

**Comment by ConnorDY** [comment]
> I've looked at the source and I see that the original element gets cloned and hidden. I wonder if the original element and the cloned element were to "switch places" so that the original does not get its `id` wiped out, and all listeners or behaviors attached to one become attached to the opposite that some issues might be resolved.

I think this is the right way to go about it. The component is very difficult to use in Angular and React with the current implementation. I'm pretty sure I could find ways to workaround this, but it'll look very hacky.

**Comment by wbyoko** [comment]
How's it going, I think I can chime in a bit on these.

1. It is currently using `data-default-value` to set the default value. You can set value for JS fallback. [ref](https://designsystem.digital.gov/form-controls/05-date-picker/)
2. Just to note, would you expect the functionality/styling to be different for `readonly` and `disabled`?
3. It should be emitting change events. How are you verifying that it is not happening?

**Comment by ConnorDY** [comment]
1. Awesome. That works. Thanks!
2. I wouldn't expect a difference in the case of this component.
3. You're right. I was expecting an `input` event when typing, but I am seeing `change` events when the date changes.

Now my main problem is that I'm not sure how to go about programmatically changing the value, readonly, or disabled state after the component is initialized.

**Comment by wbyoko** [comment]
If you have access to the DatePicker component you can use `enable` or `disable` programmatically. Also there is a `setCalendarValue` procedure that you could use to set the calendar dates.


 [docs](https://designsystem.digital.gov/form-controls/05-date-picker/)
[setCalendarValue function](https://github.com/uswds/uswds/blob/c93429e1171d4c281c66f45db6948874058be975/src/js/components/date-picker.js#L803)

**Comment by ConnorDY** [comment]
Thanks a ton @wbyoko! I think that handles everything but the `readonly` support.
