### ISSUE TITLE
Date Picker component does not initialize properly if created after page load

### ISSUE THREAD

**Issue by ConnorDY** [uswds/uswds#3753]
### Describe the bug
If you create the DOM structure for a Date Picker component anytime after the page has finished loading, the component will not initialize.

### Steps to reproduce the bug
1. Clone this repo: https://github.com/ConnorDY/uswds-date-picker-bug
2. Install dependencies (`npm ci`)
3. Run the app (`npm start`)
4. Click the button to remove the component from the DOM, then click the button again to re-add it.
5. Notice that the input shows up, but the calendar icon/button never gets added. Typing into the input causes an error.

### Expected behavior
The Date Picker component should initialize fine when created anytime after the page loads.

**Comment by timmywertz** [comment]
I'm also experiencing this issue.

**Comment by wbyoko** [comment]
You may want to look through this article in terms of interacting with JavaScript components inside of React https://reactjs.org/docs/integrating-with-other-libraries.html

This is an example that deals with initializing a USWDS component dynamically with React. https://github.com/flexion/ef-cms/blob/57e5546cbfd9e433f4a183147ad82aac56926673/web-client/src/views/CaseDeadlines/DatePickerComponent.jsx

**Comment by ConnorDY** [comment]
> This is an example that deals with initializing a USWDS component dynamically with React. https://github.com/flexion/ef-cms/blob/57e5546cbfd9e433f4a183147ad82aac56926673/web-client/src/views/CaseDeadlines/DatePickerComponent.jsx

I tried this exact same thing, but calling `on` doesn't seem to make any difference. There are no errors in the console either.
I've updated my reproduction repo to show this.

**Comment by jkreft-usgs** [comment]
we also ran into this issue (not with react directly, but its tied to any type of dynamic javascript) https://github.com/uswds/uswds/issues/3575

**Comment by ConnorDY** [comment]
I mistakenly assumed `on` should be passed the `.usa-date-picker` element, just like the date picker's `setCalendarValue`, `enable`, and `disable` methods. Passing the container element works.
