### ISSUE TITLE
Analysis of government websites (categorizing features, types, etc.)

### ISSUE THREAD

**Issue by ardenk** [uswds/uswds#3754]
Look at US government website (using USWDS and not), and try to categorize them based on their features, purpose, etc.

**Comment by sknep** [comment]
Let me know if this is something I can participate in; it seems like it might be an ideal entry into the project.  :)

**Comment by debjudy** [comment]
@ardenk is this something we are still looking to do?

**Comment by ardenk** [comment]
@debjudy yes I think. I just asked about picking it up [in this Slack message](https://flexion.slack.com/archives/C018UB8K4H5/p1605024293010600), but was told to look at components. cc @uxforgood

**Comment by debjudy** [comment]
Closing issues as work may pivot to Blueprint.
