### ISSUE TITLE
Component value matrix

### ISSUE THREAD

**Issue by ardenk** [uswds/uswds#3755]
- [x] add components from interviews into Mural
- [x] write up (short) descriptions for each component @uxforgood 
- [x] internal workshop to matrix value and LOE for proposed components
- [x] Dan workshop to review, edit, and select components to focus on

**Comment by debjudy** [comment]
@ardenk While I recognize we have more to review o the document, I think the tasks on this specific item are complete.  Agree?

**Comment by uxforgood** [comment]
@debjudy Yes, we can close.
