### ISSUE TITLE
Create password strength meter

### ISSUE THREAD

**Issue by jaredcunha** [uswds/uswds#3756]
## Rationale

Keeping online accounts secure is paramount. This is a component that can be used in conjunction with the login/sign up guidelines. 

Accordring to [Nielsen Group](https://www.nngroup.com/articles/password-creation/):
> Detailed password-composition requirements force users to jump through what feels like arbitrary hoops. People comply because the site forces them, but they end up creating easily guessable phrases. Satisfying the requirements does not necessarily result in secure passwords when real humans are making them up just to get past the registration screen.

> The Solution: Motivate people to create better passwords by showing how secure the password is.  

> A study by Egelman et al. (2013) found that strength meters motivated users to create stronger passwords. 

## Things to consider / Obstacles

- It is important for the meter's algorithm to make an accurate assessment of password strength. Factors that might affect that strength might be a mix of characters, actual words, commonality, and length. 
- How to handle disallowed characters or password requirements. A strength meter can alert a user that the password is "Good" even though it is invalid in that system.
- Can it handle localization?
- The "when not to use" guidance might be particularly important here to eliminate some of this confusion.
- How to handle for non-visual users? If this is a live region, it might be distracting as the user is typing.
- How many color shifts necessary?

## Possible libraries and examples:
- https://github.com/dropbox/zxcvbn (by dropbox, hasn't been updated in a while but still seems pretty solid)
- https://css-tricks.com/password-strength-meter/
- https://design.login.gov/components/password-strength-meters/

Using a library such as this might provide the most accurate level of password strength, but might restrict agencies from providing their own settings - though, there is a risk in allowing this if the custom settings allow certain weak passwords to slip through.

## Proposed ideas
<img width="766" alt="Screen Shot 2020-10-08 at 10 04 32 AM" src="https://user-images.githubusercontent.com/1094951/95480382-d548f600-0959-11eb-893c-18007c3952ba.png">
<img width="800" alt="Screen Shot 2020-10-08 at 11 34 55 AM" src="https://user-images.githubusercontent.com/1094951/95480806-530d0180-095a-11eb-88b6-7bacc1c250b8.png">

The section option might be preferable because it can handle mobile devices more effectively. The height can be increased if it is too subtle, but the visible fluctuations that occur as the user types might be sufficient.

### Tasks
- [ ]  Landscape Analysis
- [ ]  Sketch/Design in Figma
- [ ]  Identify users for testing
- [ ]  Usability Testing
- [ ]  Client Review
- [ ]  Finalize Design/Convert to Sketch
- [ ]  Documentation

**Comment by debjudy** [comment]
Explored as part of sign-in and create account templates. Not doing at this point in time.
