### ISSUE TITLE
Add icon list component

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3772]
Code: https://github.com/uswds/uswds/pull/3876
Documentation: https://github.com/uswds/uswds-site/pull/1140

TODO
- [x] First code review (@thisisdano)
- [x] Check heading order (@thisisdano)
- [x] First guidance review (@thisisdano)
- [x] Second code review (@mejiaj)
- [ ] Further dev review (_optional_)
- [x] Merge code into `uswds-2.11.0`
- [ ] Second guidance review (@katieekline)
- [ ] Further content review (_optional_)
- [x] Link guidance to `uswds-2.11.0` (@thisisdano)
- [x] Update guidance to new formatting (@thisisdano)
- [x] Merge guidance into `uswds-2.11.0-docs`
- [ ] Update design assets if necessary (@thisisdano)

- - -

Formerly Fancy Unordered List

10/14 review # 2 on Dan's list

DESIGN ASSETS
- [x] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback
- [x] 20% - Draft user story & clarify the problem(s) / user needs
- [x] 30% - Low-fi design review
- [x] 40% - Get community feedback on initial, Hi-fi designs
- [x] 50% - Hi-fi Sketch assets review
- [x] 60% - Hi-fi Adobe XD assets review
- [x] ~80% - Sketch and XD assets review w/ Dan + merged into master working files~
- [x] ~100% - PR approved by Dan~

GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews)
- [x] 20% - Draft guidance review no. 1 (minimum 2 bullets each section)
- [x] 40% - Get community feedback on draft guidance
- [x] 50% - Draft guidance review no. 2 (accessibility focus)
- [x] 60% - Draft guidance review no. 3 (w/ Dan)
- [x] 70% - Update usage example for guidance page
- [x] ~80% - Add component to research report and slide deck~
- [x] ~100% - PR approved by Dan~

CODE
- [x] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [x] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [x] 40% - [Get community feedback or conduct tests with users, round 1](https://docs.google.com/document/d/1swgju-bXcnDGR0vdqXZJqXmpkK35uUyD_1dbEANu62g/edit)
- [x] ~60% - Code review no. 3 (Federalist preview) - accessibility focus~
- [x] ~80% - Get community feedback or conduct tests with users, round 2~
- [x] ~100% - PR approved by Dan~

**Comment by ardenk** [comment]
Looks like some government website have already made this:
https://www.ready.gov/cybersecurity

![image](https://user-images.githubusercontent.com/2301104/96258406-47ee4d00-0fbc-11eb-97c8-0aa24dca365c.png)

Maybe we can chat with some folks at ready.gov to understand how they use this component and what research they have done.

**Comment by JoiCUX** [comment]
This is from the VA.gov Design System
 
![Screen Shot 2020-10-16 at 11 05 53 AM](https://user-images.githubusercontent.com/72038397/96275389-af49d400-0f9f-11eb-9e39-e2e1f1143ae5.png)

**Comment by JoiCUX** [comment]
Added additional bullet to guidance based on the latest community feedback.

**Comment by Ben-Judy-Flexion** [comment]
@mitchmoccia where can I find the latest Federalist previews for this component? I'm ready to start building the Sketch and Adobe XD design assets. Thanks!

**Comment by mitchmoccia** [comment]
Awesome @Ben-Judy-Flexion here it is:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3772-icon-list/components/detail/icon-list--default.html
Thanks!

**Comment by ardenk** [comment]
Community feedback here: https://docs.google.com/document/d/1swgju-bXcnDGR0vdqXZJqXmpkK35uUyD_1dbEANu62g/edit
