### ISSUE TITLE
Summary Box component

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3774]
~High-ish in page heirarchy than featured content, focused on driving a user toward one action (e.g., enroll for your benefits now) Could be part of a hero banner or elsewhere on page Similar to CARD component~

~Provide callout space with prebuilt components where agnecies can highlight important actions (sign up, apply here, etc)~

~Access/Highlight related content within a page/post without confusing it with primary content~
~- must clearly define when to use this as opposed to an information alert or CTA with a button~

_New description [Draft]: Surfacing key information, capturing attention, providing next steps_

10/14 review # 5 on Dan's List

DESIGN ASSETS
- [x] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback
- [x] 20% - Draft user story & clarify the problem(s) / user needs
- [x] 30% - Low-fi design review
- [ ] 40% - Get community feedback on initial, Hi-fi designs
- [ ] 50% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews)
- [x] 20% - Draft guidance review no. 1 (minimum 2 bullets each section)
- [ ] 40% - Get community feedback on draft guidance
- [x] 50% - Draft guidance review no. 2 (accessibility focus)
- [ ] 60% - Draft guidance review no. 3 (w/ Dan)
- [ ] 80% - Add component to research report and slide deck
- [ ] 100% - PR approved by Dan

CODE
- [x] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [x] 20% - Code review no. 2 (Federalist preview) - visual design focus
        _*We have access to crossbrowsertesting.com and AWS Workspace with NVDA for a11y testing_
- [ ] 40% - Get community feedback or conduct tests with users, round 1
- [ ] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [ ] 80% - Get community feedback or conduct tests with users, round 2
- [ ] 100% - PR approved by Dan

OTHER
- [ ] Update [Detailed Emergency Response Report](https://docs.google.com/document/d/1JucCEw2WdtHcxbKesnv0mHHNQYm2a_ffzpA2j0xatCM/edit) for this component

**Comment by ardenk** [comment]
Shared designs with Mitch on Wednesday 11/18

**Comment by 3DX8** [comment]
Comments in latest PR
https://github.com/uswds/uswds/pull/3853

**Comment by 3DX8** [comment]
@jonadecker @ardenk Summary box has been updated with the removal of the checkmark sample section pending completion of icons and development of the Icon list component.

Federalist link:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3774-Summary-Box/components/detail/summary-box.html

Updated PR:
https://github.com/uswds/uswds/pull/3853/commits/434d93832d25b9f6ef27016d0df576b9fb3be576

**Comment by 3DX8** [comment]
Added role="complementary" per Jona's suggestion:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3774-Summary-Box/components/detail/summary-box.html
