### ISSUE TITLE
Process List

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3777]
## GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews)
- [x] 20% - Draft guidance review 1 (minimum 2 bullets each section)
- [x] 40% - Get community feedback on draft guidance (11/17-11/20)
- [x] 60% - Draft guidance review 2 (11/30/2020)
- [x] 80% - Draft guidance review 3 w/ Dan (12/1/2020)
- [ ] 100% - PR approved by Dan

## CODE
- [x] 10% - Code review 1 (Federalist preview) - interaction design focus
- [x] 20% - Code review 2 (Federalist preview) - visual design focus
- [x] 40% - Get community feedback or conduct tests with users, round 1
- [x] 60% - Code review 3 (Federalist preview) - accessibility focus
- [x] 80% - Get community feedback or conduct tests with users, round 2
- [ ] 100% - PR approved by Dan

## DESIGN ASSETS
- [x] 10% - Collect and analyze examples, draft research insights, draft list of features
- [x] 20% - Low-fi design review
- [x] 40% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

**Comment by JoiCUX** [comment]
This is from the VA.gov Design System
 
![Screen Shot 2020-10-16 at 11 05 53 AM](https://user-images.githubusercontent.com/72038397/96275389-af49d400-0f9f-11eb-9e39-e2e1f1143ae5.png)

**Comment by JoiCUX** [comment]
@thisisdano 

Here is my first design draft of the "Fancy Ordered List":

### Simple Wireframe

![Order List Wireframe](https://user-images.githubusercontent.com/72038397/97358125-2a996880-1871-11eb-97a6-c87dccf3444f.png)

### Styled with Real Content

![Process List](https://user-images.githubusercontent.com/72038397/97358138-2f5e1c80-1871-11eb-959c-3f459b79f3e7.png)

**Comment by JoiCUX** [comment]
Here is the federalist link to the [code in progress](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3777-fancy-ordered-list/components/detail/graphic-list.htm): l

**Comment by Ben-Judy-Flexion** [comment]
@JoiCUX and @3DX8 what is the next milestone you intend to check off the list, and when do you anticipate being ready to ask for two team members to review it?

**Comment by 3DX8** [comment]
@Ben-Judy-Flexion I just checked off the first bullet under Code. I see the link posted above is not resolving so here it is:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3777-fancy-ordered-list/components/detail/process-list.html

**Comment by JoiCUX** [comment]
@Ben-Judy-Flexion I am finishing up the first two boxes under Guidance

**Comment by 3DX8** [comment]
@Ben-Judy-Flexion @JoiCUX @jaredcunha  Here are the latest Process List code updates. This includes refined code and a variant class which removes the vertical line (scroll to see variant sample):
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3777-fancy-ordered-list/components/detail/process-list.html

**Comment by jaredcunha** [comment]
This is looking pretty good.  I think that the connector line is a _little bit_ off-center. I've had instances like this where I had to go into the subpixel realms.

Couple quick things:
1. I think for this you'll want to add some properties to ensure this doesn't breaking when placed inside `usa-prose`. 
<img width="1632" alt="Screen Shot 2020-11-02 at 9 39 27 AM" src="https://user-images.githubusercontent.com/1094951/97880626-660fb900-1cef-11eb-800a-8194c915e05e.png">

2. On narrower screens, the circles are cut off at the edge of the viewport. 
<img width="610" alt="Screen Shot 2020-11-02 at 9 41 12 AM" src="https://user-images.githubusercontent.com/1094951/97880890-b555e980-1cef-11eb-98d1-10ed0027bb7d.png">

3. Might be a Dan question, but on any content within a list item, might want to look into setting a `max-width` with one of the `measure` design tokens to keep the number of characters per line management if placed in a very wide container.
<img width="1571" alt="Screen Shot 2020-11-02 at 9 43 27 AM" src="https://user-images.githubusercontent.com/1094951/97881192-141b6300-1cf0-11eb-859b-b421e2cb6785.png">

**Comment by 3DX8** [comment]
Great feedback, thanks @jaredcunha

**Comment by jaredcunha** [comment]
This is also just VERY nitpicky, but perhaps the variant `usa-process-list--no-line` could be `usa-process-list--no-connection` - just a personal opinion about favoring naming that doesn't describe visual presentation. Not really a hill I'd die on.

**Comment by 3DX8** [comment]
All for it Jared... It makes more sense than "no-line"

**Comment by 3DX8** [comment]
@JoiCUX @jaredcunha all your comments addressed:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3777-fancy-ordered-list/components/detail/process-list.html

- line x position tweaked
- variant class name for line removal changed to "no-connection"
- padding addressed for smaller screens
- handled usa-prose
![image](https://user-images.githubusercontent.com/19338309/97996286-8f931800-1db5-11eb-86ef-686c2c9ef41a.png)

**Comment by JoiCUX** [comment]
I updated the design to better align with the step indicator.  Smaller circles with thicker line strokes.

**Comment by 3DX8** [comment]
@JoiCUX here are the updates plus the early version of Icon List:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3777-fancy-ordered-list/components/detail/process-list.html

**Comment by JoiCUX** [comment]
@3DX8 let's sync tomorrow to work on the variant and accessibility section of the component guidance.

**Comment by JoiCUX** [comment]
@3DX8 is working on the accessibility section and finalizing the variant section.  Once complete we will share with the USWDS Slack and directly with VA.gov who have a similar component.

**Comment by 3DX8** [comment]
@jaredcunha @JoiCUX Just updated the last PR to include some refactoring and changing the structure from embedded in the Lists folder to a top level Process List item in the left nav. Everything has been tested in IE11 and Edge, let me know your thoughts, thanks!

https://github.com/uswds/uswds/pull/3822/files

https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3777-fancy-ordered-list/components/detail/process-list.html

**Comment by 3DX8** [comment]
@jaredcunha updated the PR based on your feedback:
https://github.com/uswds/uswds/pull/3822/files

**Comment by JoiCUX** [comment]
@3DX8 do you think you are ready for community feedback?

**Comment by 3DX8** [comment]
@JoiCUX Yes I think so! I was awaiting some feedback from Dan regarding the number of customizable variables but I think we can get community feedback at this point.

**Comment by JoiCUX** [comment]
### Hi-fi Sketch assets review
- [ ] Start from the most current assets. The most current assets are in the develop branch of the the uswds-for-designers repo. Clone the uswds-for-designers repo and open the develop branch or download the branch directly. We recommend cloning the repo and managing its updates using Github Desktop. This is the simplest way to keep your files up to date and prepare them for submission.  
- [ ] Install the assets as described in the documentation. See the README for complete instructions.
- [ ] File version: Create new assets in a copy of the latest Sketch (sketch/uswds-project) and XD (adobe-xd/uswds-components.xd) release files (don’t accidentally start from an older version.)
- [ ] Artboard arrangement: Place the new assets in an artboard where you would expect to find them. Create a new artboard if that is the most logical thing to do, and arrange alphabetically with the other artboards.
- [ ] Asset design: Create assets that match the example in the guidance, plus any additional states or variants that may be helpful to designers. Add mobile variants if needed.
- [ ] Symbols: Use Sketch and XD Symbols consistently, where appropriate. Create new components (symbols) if needed.
--Make a list of any new symbols you created, so they can be merged back into the master files.
- [ ] Overrides: Use Overrides (Sketch) effectively.
- [ ] Resize: Apply Resize (Sketch) and Responsive Resize (XD) features, so the component scales as well as possible when a designer resizes it.
- [ ] Variable content: Ensure the component can gracefully handle small, medium, and large amounts of content.
- [ ] Interaction states: Create Symbols or instances for each interaction state designers would need (default, selected, disabled, etc.)
--However, don’t overdo it. The guiding question should be, “will a designer actually use that state in a mockup?” There’s probably no need to create assets for every possible interaction state. Our goal is not to provide assets for interactive prototyping, simply for static mockups. The need for :hover is questionable.
- [ ] Naming: Name and organize layers and objects consistently and intuitively in Sketch and XD.
- [ ] Grouping: Group components so they are easily selectable for copy/paste — but don't group components with their header. A single click should select the component.
- [ ] Use Public Sans: Use Public Sans with normalized font size. This results in whole-number font sizes. 
- [ ] Class names as layer names: Use class names as layer names when appropriate to assure a common vocabulary between designers and developers
- [ ] Limit customizations:  Favor prebuilt symbol variants over customizable "main" symbols
- [ ] Color variables: Use color variables for colored text and borders (but understand that color variables aren't overrideable)
- [ ] Spacing between variants: Use 72px of vertical space between variants

**Comment by JoiCUX** [comment]
@3DX8 FYSA here is the draft [sketch file](https://drive.google.com/file/d/1_-CtaM__8GJD04_WPjoUjR6tgskInnrs/view?usp=sharing):

**Comment by JoiCUX** [comment]
Here is the draft [XD File](https://drive.google.com/file/d/1nsghYuCJEyN4wOnNzKiX9zJh_xcwjkEs/view?usp=sharing)

**Comment by JoiCUX** [comment]
Jam session with @Ben-Judy-Flexion yesterday to go over sketch files. He went over the design tokens inside of the library file.

**Comment by JoiCUX** [comment]
Finishing up edits to guidance based on community feedback and will  submit for a two to go and review by Dan by COB tomorrow.

**Comment by JoiCUX** [comment]
Met with Dan and got preliminary sign off on guidance. He is looking at the Implementation section more closely.

**Comment by 3DX8** [comment]
New Process list build... This addresses comments from the guidance doc and from our meeting with Dan today (changing bullet to counter, removal of no-connector variant etc...): 
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3777-fancy-ordered-list/components/detail/process-list.html

PR updated:
https://github.com/uswds/uswds/pull/3822/commits/8d45ff9a66077ada0a551616d0d886b9c162b7f3
