### ISSUE TITLE
[File Input] Create and expose methods for disabling/enabling the component after initialization/creation

### ISSUE THREAD

**Issue by ConnorDY** [uswds/uswds#3791]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to disable the File Input component after it has been initialized. For example, if we wanted to disable the input while the file is being uploaded, we cannot do so.

**Describe the solution you'd like**
I have created a PR to solve this: https://github.com/uswds/uswds/pull/3760

**Describe alternatives you've considered**
For now we would have to hide the file input from the page and showing something in its place.

**Additional context**
It would also be helpful to have a way to clear the file input programmatically.
Currently we have to destroy the component and recreate it to "clear" the chosen file.

**Comment by thisisdano** [comment]
Done!
