### ISSUE TITLE
Investigate twig.js

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3821]
- [x] Research Twig.js implimentation for pattern lab

**Comment by sarnikbixal** [comment]
After thoroughly looking through the patternlab build script I feel it is too much trouble to try and modify it to allow for the use of Twig.js. I would like to close this research ticket and open a new ticket with a prototype task to replace the patternlab build task with a custom task which will compile our markup using Twig.js

**Comment by jAigret-Bix** [comment]
New issue: #3844

**Comment by thisisdano** [comment]
Closed and moving to #3844
