### ISSUE TITLE
[SPIKE] Aria and semantics for Alert component

### ISSUE THREAD

**Issue by mgifford** [uswds/uswds#3832]
**Is your feature request related to a problem? Please describe.**

I took a look at the [Alert component](https://designsystem.digital.gov/components/alert/) and noticed that there was room for improved semantics.  I've been watching at others:
  https://github.com/alphagov/govuk-design-system-backlog/issues/2
  https://github.com/canada-ca/design-system-systeme-conception/issues/112
  https://github.com/alphagov/govuk-design-system-backlog/issues/71

Some interesting work going on about how to describe/display them here:
  https://design.canada.ca/components/alerts.html

**Describe the solution you'd like**

I'd like specific instructions on the use of aria. 

**Describe alternatives you've considered**

There are examples above.  I do think it is worth exploring design systems by other governments and exchanging best practices and user research with people with disabilities. Also investigating ways to explain it to developers/designers.

**Comment by thisisdano** [comment]
Let's spend a little time to unpack this and make a concrete suggestion and issue. Combine with #4589
