### ISSUE TITLE
Prototype a build script for pattern lab that uses Twig.js to compile the markup.

### ISSUE THREAD

**Issue by sarnikbixal** [uswds/uswds#3844]
We would like to use Twig.js to compile our twig templates so that the user is not required to have php installed.

I would like to replace the current patternlab.build() task in out Gulpfile with a custom task that uses Twig.js to compile the twig - therefore allowing the user to only depend upon Node.js.

**Comment by jAigret-Bix** [comment]
Decision to try a more simple approach captured in:  https://github.com/uswds/uswds/issues/3857. This issue can be closed.
