### ISSUE TITLE
.text-base- utility classes missing from output CSS

### ISSUE THREAD

**Issue by darthmall** [uswds/uswds#3845]
### Describe the bug
I think I've done everything I need to do to ensure that the `.text-base-` color utility classes are in my output CSS, but they aren't in my compiled CSS.

### Steps to reproduce the bug
1. `@import "packages/uswds-utilities"` in main stylesheet (`styles.scss`)
2. Set `$global-color-palettes: ("palette-color-theme");` in `_uswds-theme-utilities.scss`
3. Set `class="bg-black text-base-lightest"` on a `<p>` tag
4. Build everything and load the page
5. Background color is black, but so is the text. I've grepped the output CSS as well and `text-base-lightest` is not present.

### Expected behavior
The paragraph background should be black and the text should be white

### System setup
- **USWDS version:** 2.9.0
- **Device:** Dell Latitude 7300
- **Operating system:** Ubuntu 18.10
- **Browser and version:** Firefox 83.0

### Additional context
I'm not using the entirety of the USWDS, I'm importing the components I use piecemeal to try and keep my CSS smaller. So I'm wondering if there's an import that I missed, or a setting I have wrong.

**Comment by mahoneycm** [comment]
The utility class seems to be working appropriately for me when adding the class to a <p> tag within my components. Have you tried implementing other utility classes to see if they work?

**Comment by darthmall** [comment]
I just tested this again and I'm no longer having this problem. My best guess is that I hadn't enabled these utilities in <samp>_uswds-theme-utilities.scss</samp> at the time.

I think we can probably close this issue.

**Comment by mejiaj** [comment]
Glad to hear it's been solved. Closing this issue.

Thanks @mahoneycm for looking into this and @darthmall for checking back in.
