### ISSUE TITLE
Combine font files for designers

### ISSUE THREAD

**Issue by melissajschaff** [uswds/uswds#3847]
### Describe the bug
There are currently 2 folders for fonts in `uswds-for-designers`.
1. [Fonts](https://github.com/uswds/uswds-for-designers/tree/main/Fonts): contains only Merriweather
2. [fonts](https://github.com/uswds/uswds-for-designers/tree/main/fonts): contains rest of fonts (4)

To get all necessary fonts, you have to go to multiple folders. It is easy to overlook this step, especially if you are new to GitHub and USWDS. 

To ensure a designer has all font files, combine to one folder ( recommend:`fonts` to follow naming convention used for the rest of the folders)

### Steps to reproduce the bug
1. Go to [uswds-for-designers](https://github.com/uswds/uswds-for-designers)
2. Click on [Fonts](https://github.com/uswds/uswds-for-designers/tree/main/Fonts) for Merriweather
3. Go to back to [uswds-for-designers](https://github.com/uswds/uswds-for-designers)
4. Click on [fonts](https://github.com/uswds/uswds-for-designers/tree/main/fonts) for other 4 fonts. 

### Expected behavior
I expect there to be only one folder for "fonts"

### Screenshots
Add screenshots to help provide context, if applicable.

### System setup
- **USWDS version:** 2.0
- **Device:** Mac OS
- **Operating system:** Any
- **Browser and version:** Any

### Additional context
This is really just an organization issue, not an error with USWDS. Combining the folders could lead to additional issues, if the folders are linked to from other places.

**Comment by thisisdano** [comment]
Oh that's unexpected, let's fix that!
