### ISSUE TITLE
File Input's accept attribute does not support MIME types or multiple file extensions when dragging and dropping file(s)

### ISSUE THREAD

**Issue by ConnorDY** [uswds/uswds#3848]
### Describe the bug
If using a MIME type with the `accept` attribute (such as `application/pdf`), the proper files are accepted when clicking the `input` to select the files. However, the same files when dragged and dropped give the "This is not a valid file type"  error message.

There is also an issue when multiple file extensions are specified when dragging and dropping. For example, if I set the `accept` attribute to be `.pdf,.txt`, I can select files with both extensions when using the file browser, but I can't drop any files of these types when dragging and dropping.

This appears to happen because the USWDS code checks if the value of `accept` is included in the name of the file:
```javascript
const acceptedFiles = fileInputEl.getAttribute("accept");

// ... skipping some code here ...

for (let i = 0; i < e.dataTransfer.files.length; i += 1) {
  const file = e.dataTransfer.files[i];
  if (allFilesAllowed) {
    allFilesAllowed = file.name.indexOf(acceptedFiles);
    if (allFilesAllowed < 0) {
      break;
    }
  }
}
```

### Steps to reproduce the bug
1. Use one or more MIME types or file extensions with the `accept` attribute on the `input` element.
2. Attempt to drag and drop one or more valid files of that MIME type or file extension
3. See "This is not a valid file type" error

### Expected behavior
Dragging and dropping should accept the same files that are allowed when clicking the `input` element to browse for files.

### Screenshots
![image](https://user-images.githubusercontent.com/945062/100109847-42e1b080-2e3a-11eb-917b-ffea6176a544.png)

### System setup
- **USWDS version:** 2.9.0
- **Device:** N/A
- **Operating system:** N/A
- **Browser and version:** N/A

### Additional context
N/A

**Comment by ConnorDY** [comment]
My recommendation for fixing this is splitting the value of the `accept` attribute:
```javascript
const acceptedFiles = fileInputEl.getAttribute("accept").split(',');
```

And then checking against `file.type` and `file.name` like so:
```javascript
for (let j = 0; j < acceptedFiles.length; j += 1) {
  const fileType = acceptedFiles[j];
  allFilesAllowed = file.name.indexOf(fileType) > 0 || file.type === fileType;
  if (!allFilesAllowed) break;
}
```

Let me know if y'all would like me to make a PR for this or if your team can tackle this.

**Comment by aduth** [comment]
Another potential problem is that [the specification](https://html.spec.whatwg.org/multipage/input.html#file-upload-state-(type=file)) for `accept` allows for values of `audio/*`, `video/*`, `image/*`, to match any subtype.

While I'm not a maintainer of the project, I think the above suggestion is on the right track, and could support wildcards, optionally relying on the fact that it can only be one of the literal values `audio/*`, `video/*`, `image/*` (by the spec above, the `*` wildcard can't just be used anywhere).

**Comment by sperro** [comment]
I'm still seeing this issue with the latest version. When allowing multiple files and specifying multiple extensions in the accept attribute, drag and drop validations work for the first extension in the accept list but fails for the others. Ex: if I had ` ....accept=".pdf, .docx, .txt" multiple>` drag and drop will work for .pdf but not for .docx or .txt
