### ISSUE TITLE
Review ARIA on ER components

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3864]
Review ER components for opportunities to effectively leverage ARIA roles

- [X] Site alert
- [X] Summary box
- [x] Tap Tiles
- [x] Process list
- [x] Better mobile tables
- [x] Collection

**Comment by jonadecker** [comment]
Site alert: was set to role="alert" but removed (not consistent with expected use of alert). Already using semantic HTML.
Summary box: recommend "complementary" for appropriate use cases
