### ISSUE TITLE
Identifier component - wrong link name

### ISSUE THREAD

**Issue by maya** [uswds/uswds#3869]
Should be Budget and Performance rather than Performance reports per https://digital.gov/resources/required-web-content-and-links/

**Comment by afeijoo** [comment]
The link text on digital.gov is _suggested_ link text. 

We are working with the Federal Web Council and digital.gov team to update the guidance on https://digital.gov/resources/required-web-content-and-links/.

**Comment by thisisdano** [comment]
Blocked by https://github.com/uswds/uswds/issues/3744

**Comment by afeijoo** [comment]
We are updating the guidance in https://github.com/uswds/uswds/issues/3744. The link name in the identifier component will remain as-is.
