### ISSUE TITLE
Pagination: Prototype

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3870]
Pagination: Build and test Prototype
- [x] 10% Develop prototype 
- [x] 20% Code review w client/team [interaction design focus]
- [x] 40% Update prototype based on feedback
- [x] 60% [first accessibility test](https://drive.google.com/file/d/19t8_tHiJRW9JKTetgEITrAy96gLWHVyy/view?usp=sharing) [1/6/21]
- [x] 80% Code review w client/team [visual design focus]
- [x] 100% Collect and incorporate [community feedback](https://docs.google.com/spreadsheets/d/119LwnZa2I5w0qIzxhG7x7nRHgr1t3TVUll0ITZmk05w/edit#gid=0) https://github.com/uswds/uswds/issues/3921

**Comment by allie-shaw** [comment]
Draft Guidance: https://docs.google.com/document/d/1d-8MJXUZKcYfba9jXQzMvvoHFHdNNItZMMXsco7ELn0/edit?usp=sharing
