### ISSUE TITLE
Choose Date for Ending Support for IE11

### ISSUE THREAD

**Issue by mgifford** [uswds/uswds#3877]
**Is your feature request related to a problem? Please describe.**
Support for IE is falling quickly on the web and maintaining IE11 users is becoming increasingly expensive for CMS tools to maintain.  Government continues to be one of the biggest users of this legacy software despite security challenges.  Announcing an end date for support within the USWDS will help determine how much longer existing frameworks will need to support it. 

**Describe the solution you'd like**
I'd like to see that as of 2.11 that IE11 is no longer officially supported by the USWDS.  

https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666

**Comment by afeijoo** [comment]
Thanks @mgifford! USWDS [follows the 2% rule](https://designsystem.digital.gov/documentation/developers/#browser-support ). We officially support any browser above 2% usage as observed by [analytics.usa.gov](https://analytics.usa.gov). 

Last month IE11 was at 3.6% over the past 90 days. This month it is 2.9%, and we'll continue to monitor it.

**Comment by mgifford** [comment]
That is great! Thanks.

**Comment by rofrol** [comment]
IE11 is below 2%

![image](https://user-images.githubusercontent.com/28787/118159605-80a0b880-b41d-11eb-9dd2-9a8ae6f10d7f.png)

**Comment by afeijoo** [comment]
@rofrol es, we also saw it dipped below 2%. We're monitoring it, and we plan to update it after it stays below 2% for a few months. It's close!

**Comment by shaal** [comment]
This is now official - 
`Internet Explorer 11 desktop application will be retired and go out of support on June 15, 2022`

https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/

**Comment by mherchel** [comment]
Followup on this: IE11 usage is at 1.1%
![image](https://user-images.githubusercontent.com/1605905/144921629-34dfa5ee-7503-48b2-b8b1-23cbd527cab8.png)

**Comment by sw-yx** [comment]
update:  Internet Explorer is now so small that it just shows as "Other"

![image](https://user-images.githubusercontent.com/6764957/165642262-52cb4bc2-8148-4688-af7a-b96485d08200.png)
