### ISSUE TITLE
Date picker has wrong anchor links

### ISSUE THREAD

**Issue by igorkorenfeld** [uswds/uswds#3878]
On the [Form controls](https://designsystem.digital.gov/components/form-controls/) components page the guidance for the `date picker` has links to `date input fields` that links back to the top of the form-controls page, instead of the the `date input fields` section. It looks like the url it links to is `https://designsystem.digital.gov/form-controls/#date-input` which is missing the `/components` portion. 

![image](https://user-images.githubusercontent.com/52677065/101801116-dfef4b00-3ac2-11eb-851e-65e940b6d595.png)

**Comment by thisisdano** [comment]
Fixed in new docs format here: https://github.com/uswds/uswds-site/pull/1136
Fixed in old docs format here: https://github.com/uswds/uswds-site/pull/1168
