### ISSUE TITLE
Blueprint report

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3882]
- [x] Conduct remaining interviews (1 group, 6 individual) - start: 11/9 end: 11/20
- [x]  Synthesis for each interview (ongoing) start - 11/9 end: 11/20
- [x] Cross-synthesis (ongoing) - start: 11/9 end: 11/25
- [x] Identify opportunity areas and path to scale/explore - start: 11/16 end: 11/25
- [x] Draft report (content) - start: 11/30 end: 12/11
- [x] Draft design for report (indesign for PDF) - start: 12/4 end: 12/11
- [x] Designed report (indesign for PDF) - start: 12/7 end: 12/17
- [ ] Feedback/edit on designed report

**Comment by kimschulke** [comment]
Update 12/11:

Blueprint content getting close - wrapping up some work to connect the narrative

Working on options for design/format of PDF report and website hero graphic.

**Comment by debjudy** [comment]
Update 12/31: 
Review version of report sent on 12/23.  
Formal email turnover sent on 12/31.
Awaiting feedback to finalize.
