### ISSUE TITLE
Blog post to announce components (due Jan 15)

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3883]
Generate a blog post to announce components release.

**Comment by Ben-Judy-Flexion** [comment]
I posted a first rough draft here:
[https://docs.google.com/document/d/14ZhLuC4keq1yIT1RiNQ47WME22Yw2dnMRvZrEiLPEu4/edit#heading=h.bgjlr21w2uow](https://docs.google.com/document/d/14ZhLuC4keq1yIT1RiNQ47WME22Yw2dnMRvZrEiLPEu4/edit#heading=h.bgjlr21w2uow)
