### ISSUE TITLE
Finish up design assets for 8 ER components

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3885]
# SKETCH

## Sketch artboards

Updated artboards
1. Form controls
2. Icons
3. Table

New artboards
1. Authentication pages templates
2. Collection
3. Icon list
4. Process list
5. Site alert
6. Summary box

## Sketch file to-do

- [x] All artboards: clean up internal AH and BH headers on all artboards. Reset to default symbol size. Rename to default symbol name. Delete duplicate symbol. (In the 2.9.0 Sketch file, there were two master internal/BH symbols. One was an unnecessary duplicate which had 19 instances. I replaced all those instances with the first symbol, and deleted the duplicate symbol.)
- [x] All updated & new components: add new artboards.
- [x] All updated & new components: temporarily position all updated and new artboards 1000px higher for easy review.
- [x] All updated & new components: finish creating 'rough draft' desktop & mobile designs.
- [x] All updated & new components: create new phone frame symbol for mobile width variants.
- [x] Form controls: clean up and reorganize everything on this artboard, ensuring consistent spacing and alignment of elements
- [x] Form controls: add new symbols for checkbox and radio button (There were some missing interactive states.)
- [x] Form controls: create mobile width for tiles.
- [x] Form controls: revise the Tile example content to match the changes made to the site.
- [x] Icons: place each Material icon on artboard.
- [x] Icons: create a new symbol for each icon.
- [x] Table: completely rebuild tables and table symbols from the ground-up. (Created four new symbols: two th's and tw td's. Deleted old symbols and instances for tables.)
- [x] Table: adjust each cell symbol so the text boxes maintain proper margin, padding, line height, and text wrapping when resizing the width or height of an instance.
- [x] Authentication pages templates: create new Footer and Identifier desktop-width symbols and add them to the bottom of each variant design.
- [x] Authentication pages templates: resize Identifier desktop-width symbol to be 1024px wide for consistency. (Footer and Identifier were not the same width. Footer was 1024px wide. Identifier was 1012px.)
- [x] Authentication pages templates: Add rectangles behind the updated Footer and Identifier symbols to give the appearance of a wider container. (The Footer and Identifer symbols were built for different sizes. I created new symbols and resized Identifier to 1024 px wide. However, these symbols don’t resize gracefully. Adding these rectangles is not the cleanest way to do it, but it would take a lot more time to rebuild the symbols so they resize appropriately.)
- [x] Authentication pages templates: create new Footer and Identifier mobile-width symbols. Resize Identifier from 345px wide to 340px wide.
- [x] Collection: rename and adjust variants to match changes made for release
- [x] Collection: create mobile width for all variants
- [x] Icon list: apply a Tint to adjust color of each icon symbol, to match the example on the site.
- [x] Process list: create new symbol for numbers.
- [x] Process list: create mobile width for all variants.
- [x] Summary box: create desktop and mobile size variants.

# ADOBE XD

## Adobe XD artboards

Updated artboards
1. Form controls (renamed from forms-and-inputs)
2. Table

New artboards
1. Authentication pages templates
2. Collection
3. Icons
4. Icon list
5. Process list
6. Site alert
7. Summary box

## Adobe XD file to-do

- [x] All artboards: re-order artboards in the Layers panel so they are in alphabetical order.
- [x] All artboards: rename artboards in Layers panel in sentence case for consistency with Sketch.
- [x] All artboards: resize to 1100px wide (or wider as needed) and space evenly 100px apart, for consistency.
- [x] All updated & new components: add new artboards.
- [x] All updated & new components: temporarily position all updated and new artboards 1000px higher for easy review
- [x] All new components: add title text box (name of component.)
- [x] Form controls: rename artboard. (Was Forms and Inputs.)
- [x] Form controls: add new symbols for Tiles.
- [x] Form controls: revise entire artboard to match the Sketch version. (The elements in the Adobe XD version of Form controls
- [x] Table: completely rebuild tables and table symbols from the ground-up.
- [x] Icons: place each Material icon on artboard.
- [x] Icons: create a new symbol for each icon.

## Notes from review 12/30/20
- [x] Tables: ensure correct vertical padding for all rows, accounting for the number of lines of text.
- [x] Identifier: build in XD, create symbol, add where needed
- [x] Use t-shirt font sizes
- [x] Sketch - use icon symbol for linking to external site
- [x] Fix errors in Tiles
- [x] Icons - add new icons in Sketch
- [x] Site Alert should be full width for mobile
- [x] Site Alert: page title should be below the site alert box
- [x] Site Alert: correctly position the icon

**Comment by Ben-Judy-Flexion** [comment]
Here's a snapshot of work in progress on the Sketch file. Feedback welcome!

I have a pretty good start start on:
- Collection
- Tap tiles (Form controls)
- Icons
- Process list
- Site alert
- Summary box
- Tables

Have yet to start on these:
- Icon list
- Sign in templates

[20201214-1012-CT.zip](https://github.com/uswds/uswds/files/5690039/20201214-1012-CT.zip)

**Comment by Ben-Judy-Flexion** [comment]
Here's an updated work-in-progress Sketch file.
I also updated the task list in this Issue description. Still lots of fine-tuning to do and mobile variants to create.
[archive-20201216-1515-CT-uswds-project_Accelerator_fork_2.9.0.sketch.zip](https://github.com/uswds/uswds/files/5705539/archive-20201216-1515-CT-uswds-project_Accelerator_fork_2.9.0.sketch.zip)

**Comment by Ben-Judy-Flexion** [comment]
Here are updated work-in-progress Sketch and Adobe XD files.

At this point, I feel like Sketch is 95% done (or 'good enough' done.) Just a few difficult issues with symbols to work out.
Adobe XD file is probably only 10% done, but should go much more quickly than Sketch did.

In both files I am taking somewhat of a long route, rebuilding some things from the ground-up to make the files more internally consistent, cleaning up and organizing things, etc. For example, I completely rebuilt Table components in Sketch, and I'm doing a complete rebuild of Form controls in Adobe XD to match what is in Sketch. If we want to just get this out the door ASAP, I can forego this kind of rebuilding and instead just minimally create assets for the new components.

I am maintaining the task list in this Issue description. I'll continue to add tasks as I realize what is left to do.
[archive-20201228-0845-CT-uswds-components_fork_2.9.0.zip](https://github.com/uswds/uswds/files/5747707/archive-20201228-0845-CT-uswds-components_fork_2.9.0.zip)

**Comment by Ben-Judy-Flexion** [comment]
Here are updated work-in-progress Sketch and Adobe XD files.

I'd say they're "done" enough to ship. There's an infinite amount of pixel-pushing and symbol optimizing that could be done. But at some point it becomes gold-plating. This is ready for review.

[archive-20201230-1400-CT-uswds-components_fork_2.9.0.zip](https://github.com/uswds/uswds/files/5755545/archive-20201230-1400-CT-uswds-components_fork_2.9.0.zip)

**Comment by Ben-Judy-Flexion** [comment]
PR submitted in the uswds-for-designers repo:
https://github.com/uswds/uswds-for-designers/pull/82
