### ISSUE TITLE
Design custom icons

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3886]

**Comment by debjudy** [comment]
@jaredcunha @ardenk Have the new icons been put into a PR yet?

**Comment by jaredcunha** [comment]
@debjudy I'm waiting on approval. Last I heard, I think some additional work/info was needed.

**Comment by ardenk** [comment]
We just got approval from Dan [in Slack](https://gsa-tts.slack.com/archives/C01ATNBSTTP/p1612809274002200?thread_ts=1612550056.019600&cid=C01ATNBSTTP)

New icons are available in the [Custom Icons folder in Drive](https://drive.google.com/drive/u/1/folders/1r1t9p3xF1LYvBWZQ3DLdo4rdZLxtXFeN)

**Comment by jaredcunha** [comment]
@ardenk There are duplicate names for the following icons:
- construction
- flickr
- twitter
- youtube

Have the social media icons been updated in any way? 

This what the current construction icon looks like:
<img width="213" alt="Screen Shot 2021-02-09 at 8 01 08 PM" src="https://user-images.githubusercontent.com/1094951/107449435-8ed6f400-6b11-11eb-98bc-fa49c3a2a16d.png">

**Comment by jaredcunha** [comment]
Here's the yml file with meta descriptions:
https://github.com/uswds/uswds/pull/3988/files

**Comment by ardenk** [comment]
>Duplicate name for construction
Suggest naming the new one "construction worker"

>Have the social media icons been updated in any way?
Nope, they are the same!

**Comment by thisisdano** [comment]
Done
