### ISSUE TITLE
Component briefs & turnover to Core team

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3912]
- [x] Create component brief https://flexion.slack.com/archives/C018UB8K4H5/p1608666268210700
- [x] Schedule component handoff meetings. 2-3 components per meeting

_**Write component briefs - due Wednesday EOD**_
- [x] Summary Box @ardenk @mitchmoccia 
- [ ] Site Alert @Ben-Judy-Flexion 
- [ ] Collection @Ben-Judy-Flexion 
- [x] Icons @ardenk @jaredcunha 
- [x] Process List @ardenk @mitchmoccia 
- [x] Authentication Pages @ardenk @jaredcunha 
- [x] Table @sknep 
- [x] Touch Targets @jaredcunha 
- [x] Icon list @ardenk @mitchmoccia 

- [ ] Review all **Friday** @uxforgood 
- [ ] Turnover to Core team by Feb 4

**Comment by thisisdano** [comment]
Done
