### ISSUE TITLE
Focus outline issue on radio buttons and checkboxes in Firefox browser

### ISSUE THREAD

**Issue by ajanickiv** [uswds/uswds#3916]
### Describe the bug
The focus outline for radio buttons and checkboxes extends left about 2 rems past the radio button and checkbox display area

### Steps to reproduce the bug
1. Open Firefox browser
2. Go to https://designsystem.digital.gov/components/form-controls/#radio-buttons or https://designsystem.digital.gov/components/form-controls/#checkbox
3. Focus on radiobutton/checkbox

### Expected behavior
Focus outlines the radio button and checkbox like it does in other browsers

## Firefox
![image](https://user-images.githubusercontent.com/16595489/103300183-4bdf1800-49cc-11eb-829e-e93f6e24b08c.png)
![image](https://user-images.githubusercontent.com/16595489/103300214-631e0580-49cc-11eb-95c5-7d1672916b46.png)
## Chrome
![image](https://user-images.githubusercontent.com/16595489/103300541-0c64fb80-49cd-11eb-8099-93bb6e1d982f.png)
![image](https://user-images.githubusercontent.com/16595489/103300619-42a27b00-49cd-11eb-8b69-eb9e798149b7.png)

### System setup
- V2.10.0
- Laptop
- Windows 10
- Firefox 84.0.1 (64-bit)

### Additional context
Custom CSS that fixes the problem
```
@-moz-document url-prefix() {
    .checkbox-radio-focus {
        display: flex;
        text-indent: 0;
        padding-left: 0;
    }
    .checkbox-radio-focus-tile {
        text-indent: 0;
        padding-left: 0.5rem !important;
    }
    .checkbox-radio-focus-tile-hint {
        text-indent: 2rem;
    }
}
```

**Comment by mejiaj** [comment]
Good find @ajanickiv! I found removing `text-indent` from the `::before` worked as well. 

I have a PR open for this in: #3918.
