### ISSUE TITLE
Pagination community feedback (Round One)

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3921]
Create, post, and capture community feedback on Pagination component

-  10% discover new github conversation feature (?) 
- [x] 20% Create [community feedback draft](https://docs.google.com/document/d/1IFP6OK_gCCdwY1AsGOlMUHmEf4q-SxbH_cJWxfxea3Y/edit)
- [x] 30% Client review [1/5]
- [x] 40% Changes, review no 2 [due EOD 1/6]
- [x] 50% Client approval  
- [x] 80% Send out for [community feedback](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1610562979047600)(1/13)
- [x] 90% [collect and analyze feedback](https://docs.google.com/spreadsheets/d/119LwnZa2I5w0qIzxhG7x7nRHgr1t3TVUll0ITZmk05w/edit#gid=0) (1/22)
- [x] 100% Share out findings w client (2/1)

**Comment by allie-shaw** [comment]
Feedback questions
https://docs.google.com/document/d/1IFP6OK_gCCdwY1AsGOlMUHmEf4q-SxbH_cJWxfxea3Y/edit#

**Comment by mejiaj** [comment]
@jAigret-Bix re: github conversation feature — maybe this **Q&A** section in [Discussions](https://github.com/uswds/uswds/discussions)
