### ISSUE TITLE
Add table sorting

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3935]
Code: https://github.com/uswds/uswds/pull/3950
Documentation: https://github.com/uswds/uswds-site/pull/1152

TODO
- [ ] First code review (@thisisdano)
- [x] Check heading order (@thisisdano)
- [x] First guidance review (@thisisdano)
- [x] Second code review (@mejiaj)
- [x] Further dev review (@scottqueen-bixal)
- [x] Merge code into `uswds-2.11.0`
- [ ] Second guidance review (@katieekline)
- [ ] Further content review (_optional_)
- [x] Link guidance to `uswds-2.11.0` (@thisisdano)
- [x] Update guidance to new formatting (@thisisdano)
- [x] Merge guidance into `uswds-2.11.0-docs`
- [ ] Update design assets if necessary (@thisisdano)

- - -

Ability to reorder table based on one of the columns
Assumptions 
* "sort by" drop down
* include in guidance when is it appropriate to make a sortable table
* Will use JavaScript
Note: for massive datasets, this might get harder.

**DESIGN ASSETS**
- [x] 10% - Collect and analyze examples; draft research insights and list of features for team/client feedback
- [x] 20% - Draft user story & clarify the problem(s) / user needs
- [x] 30% - Low-fi design review
- [x] 40% - Get community feedback on initial, Hi-fi designs
- [x] 50% - Hi-fi Sketch assets review
- [x] 60% - Hi-fi Adobe XD assets review
- [x] ~80% - Sketch and XD assets review w/ Dan + merged into master working files~
- [x] ~100% - PR approved by Dan~
----
**GUIDANCE**
- [x] 10% - Summarize insights from research (desk + interviews)
- [x] 20% - Draft guidance review no. 1 (minimum 2 bullets each section)
- [x] 40% - Get community feedback on draft guidance
- [x] 50% - Draft guidance review no. 2 (accessibility focus)
- [x] ~60% - Draft guidance review no. 3 (w/ Dan)~
- [x] ~80% - Add component to research report and slide deck~
- [x] ~100% - PR approved by Dan~
----
**CODE**
- [x] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [x] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [x] 40% - Get community feedback or conduct tests with users, round 1
- [x] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [x] ~80% - Get community feedback or conduct tests with users, round 2~
- [x] ~100% - PR approved by Dan~

**Comment by sknep** [comment]
Related issues:
https://github.com/uswds/uswds/issues/3292
https://github.com/uswds/uswds/issues/3553

**Comment by sknep** [comment]
See notes in https://github.com/uswds/uswds/pull/3950#issuecomment-764159203
