### ISSUE TITLE
Add modal component

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3936]
Code: https://github.com/uswds/uswds/pull/3981
Documentation: https://github.com/uswds/uswds-site/pull/1155

TODO
- [x] First code review (@thisisdano)
- [x] Check heading order (@thisisdano)
- [ ] First guidance review (@thisisdano)
- [x] Second code review (@mejiaj)
- [x] Further dev review (_optional_)
- [x] Merge code into `uswds-2.11.0`
- [ ] Second guidance review (@katieekline)
- [ ] Further content review (_optional_)
- [x] Link guidance to `uswds-2.11.0` (@thisisdano)
- [x] Update guidance to new formatting (@thisisdano)
- [ ] Merge guidance into `uswds-2.11.0-docs`
- [ ] Update design assets if necessary (@thisisdano)

- - -

* How to display a lightbox/modal
* When is it appropriate
* How to make accessible

https://cfpb.github.io/design-manual-archive/page-components/modals.html

Talking about the hierarchy of content "interruption" - modal = STOP and read, banner = important, featured content = group of related content to highlight. "users consume important info and then get back into what they need to do". There's often a lot of usability/accessibility issues with modals when done incorrectly

DESIGN ASSETS
- [x] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback
- [x] 20% - Draft user story & clarify the problem(s) / user needs
- [x] 30% - Low-fi design review
- [x] 40% - Get community feedback on initial, Hi-fi designs
- [x] 50% - Hi-fi Sketch assets review
- [x] 60% - Hi-fi Adobe XD assets review
- [x] ~80% - Sketch and XD assets review w/ Dan + merged into master working files~
- [x] ~100% - PR approved by Dan~

GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews)
- [x] 20% - Draft guidance review no. 1 (minimum 2 bullets each section)
- [x] 40% - Get community feedback on draft guidance
- [x] 50% - Draft guidance review no. 2 (accessibility focus)
- [x] 60% - ~Draft guidance review no. 3 (w/ Dan)~
- [x] 80% - ~Add component to research report and slide deck~
- [x] 100% - ~PR approved by Dan~

CODE
- [x] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [x] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [x] 40% - Get community feedback or conduct tests with users, round 1
- [x] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [x] 80% - Get community feedback or conduct tests with users, round 2
- [x] 100% - ~PR approved by Dan~

**Comment by ardenk** [comment]
Reviewed prototype and design with Dan on Friday, synced up in UX standup. Next steps:
 - [ ] set up guidance doc @ardenk 
 - [ ] set up component brief doc @ardenk 
 - [ ] set up community feedback doc @npage123 
 - [ ] provide content for prototype @npage123 
 - [ ] implement 3 modal sizes (define width of modal and content) @jaredcunha 
 - [ ] fine-tuning session @ardenk @npage123 @jaredcunha 

We'll all contribute to filling in the documentation.

**Comment by smustgrave** [comment]
Not sure this is the correct ticket.  But we have a client looking to add a modal.  We had to use bootstrap which we really didn't want.  If USWDS has one in the works how best could I get involved to help?  I have 508 training so could also help there.
