### ISSUE TITLE
Enhance printer friendly formatting

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3940]
Code: https://github.com/uswds/uswds/pull/4015
Documentation: https://github.com/uswds/uswds-site/pull/1158

TODO
- [ ] First code review (@thisisdano)
- [x] Check heading order (@thisisdano)
- [ ] First guidance review (@thisisdano)
- [x] Second code review (@mejiaj)
- [ ] Further dev review (_optional_)
- [ ] Merge code into `uswds-2.11.0`
- [ ] Second guidance review (@katieekline)
- [ ] Further content review (_optional_)
- [ ] Link guidance to `uswds-2.11.0` (@thisisdano)
- [x] Update guidance to new formatting (@thisisdano)
- [ ] Merge guidance into `uswds-2.11.0-docs`
- [ ] Update design assets if necessary (@thisisdano)

- - -

As agencies move away from PDFs (accessibility issues) and are using HTML/CSS to format pages that are taking the place of documents, designers want to make sure that the formatting is maintained if the user chooses to print.

Assumptions
* All page elements are single-column-first and tagged properly to easily print (this description needs help from engineering, what makes something print friendly?)
* Including expanded accordions

DESIGN ASSETS
- [x] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback
- [x] ~20% - Draft user story & clarify the problem(s) / user needs~
- [x] ~30% - Low-fi design review~
- [x] ~40% - Get community feedback on initial, Hi-fi designs~
- [x] ~50% - Hi-fi Sketch assets review~
- [x] ~60% - Hi-fi Adobe XD assets review~
- [x] ~80% - Sketch and XD assets review w/ Dan + merged into master working files~
- [x] ~100% - PR approved by Dan~

GUIDANCE
- [x] ~10% - Summarize insights from research (desk + interviews)~
- [x] ~20% - Draft guidance review no. 1 (minimum 2 bullets each section)~
- [x] ~40% - Get community feedback on draft guidance~
- [x] ~50% - Draft guidance review no. 2 (accessibility focus)~
- [x] ~60% - Draft guidance review no. 3 (w/ Dan)~
- [x] ~80% - Add component to research report and slide deck~
- [x] ~100% - PR approved by Dan~

CODE
- [x] ~10% - Code review no. 1 (Federalist preview) - interaction design focus~
- [x] ~20% - Code review no. 2 (Federalist preview) - visual design focus~
- [x] ~40% - Get community feedback or conduct tests with users, round 1~
- [x] ~60% - Code review no. 3 (Federalist preview) - accessibility focus~
- [x] ~80% - Get community feedback or conduct tests with users, round 2~
- [x] ~100% - PR approved by Dan~

**Comment by mitchmoccia** [comment]
# Icon list core site
# PR
https://github.com/uswds/uswds/pull/3876

# Fed link
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3772-icon-list/components/detail/icon-list--default.html

------------------------------------------------------------------------

# Icon list guidance site
# PR
https://github.com/uswds/uswds-site/pull/1140

# Fed link
https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/accelerator/icon-list2/components/icon-list/
