### ISSUE TITLE
Create guidance on usage of helper text

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3941]
How helper text is displayed and what it should be used for
Better understand the availability of helper text and guidance around character count.

GUIDANCE
- [ ] 10% - Summarize insights from research (desk + interviews)
- [ ] 20% - Draft guidance review no. 1 (minimum 2 bullets each section)
- [ ] 40% - Get community feedback on draft guidance
- [ ] 50% - Draft guidance review no. 2 (accessibility focus)
- [ ] 60% - Draft guidance review no. 3 (w/ Dan)
- [ ] 80% - Add component to research report and slide deck
- [ ] 100% - PR approved by Dan

**Comment by ardenk** [comment]
@debjudy is this hint text in an input field?

**Comment by debjudy** [comment]
@ardenk This one was from the component list.  Here is what was there for it 

Better understand the availability of helper text and guidance around character count. 
How helper text is displayed and what it should be used for

https://docs.google.com/spreadsheets/d/16TcEzfqtJTQonRfspJpXAWlzsKeV3kbfteTIWxS6v_0/edit#gid=1883555298
