### ISSUE TITLE
Modified Federalist deploy build process

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3958]
Problem: Not able to preview PL lab through Federalist. Need solution for PL based preview into Federalist. PL uses PHP to compile the twig templates. Federalist environment does not allow for the installation of PHP. 

Updated tasks 1/26 Meeting w Dan and dev team:
-[x] create a testing branch on USWDS
-[x] try to store circle ci build artifacts 
-[ ] if yes, change federalist source directory
-[ ] create a federalist repo

Acceptance criteria
-[ ] clone of USWDS repo and all current branches. including federalist build artifacts
-[x] create trigger and a script (cron job) with write permissions to the new repo
-[ ] if yes, change federalist source directory to new repo

Definition of Done
- [ ] a script w write permissions pointing to new repo
- [x] have a new repo with corresponding branches that include a circle ci build artifact
- [ ] have Federalist successfully coping those artifacts over to their servers

**Comment by sarnikbixal** [comment]
In order to continue we need to have circle CI granted WRITE permissions to github. Automated commits to allow the artifact to be saved to a repo location. Another solution has halted progress on this current one.

**Comment by thisisdano** [comment]
Thankfully, we won't need to do this, and can use a node-based compile
