### ISSUE TITLE
Summary Box Text Overflow/Responsiveness

### ISSUE THREAD

**Issue by ascreven** [uswds/uswds#3965]
### Describe the bug
Text in the summary box component is overflowing on some viewports when summary is inside of of grid columns

### Steps to reproduce the bug
Add grid-row and grid-cols outside of summary box and paragraphs inside box text

```
<div class="grid-row">
  <div class="grid-col-2">
    <div class="usa-summary-box" role="complementary">
      <div class="usa-summary-box__body">
        <h3 class="usa-summary-box__heading">Key information</h3>
        <div class="usa-summary-box__text">
          <p>
            Morbi nec semper nulla. In hac habitasse platea dictumst. Donec bibendum volutpat varius. Lorem ipsum dolor
            sit amet, consectetur adipiscing elit. Proin sollicitudin egestas fermentum. Sed ornare lectus et urna
            maximus vulputate. Nunc et consectetur lacus, varius vulputate arcu. Cras porta tempus magna sed dictum.
            Nullam rutrum dui sed mi bibendum gravida. Sed congue aliquet enim a sodales. Fusce ut lacus ipsum.
            Vestibulum ac imperdiet leo, sed convallis dui. Aenean pulvinar, ex eu lobortis pharetra, dolor massa
            molestie massa, et volutpat lorem neque accumsan purus. Integer volutpat eros a tempus pulvinar. Nam
            consectetur eget erat vitae dictum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum facilisis maximus nulla a fermentum.
            Duis finibus ligula id ex ornare, vel rhoncus odio posuere. Vivamus iaculis lectus in orci laoreet
            fringilla. Cras sodales euismod dignissim. Sed dignissim, libero et tincidunt commodo, elit tortor
            sollicitudin neque, semper rutrum sem nunc eu magna. Proin cursus volutpat elit, semper scelerisque arcu
            vulputate sed. Maecenas in tellus a velit iaculis aliquam venenatis finibus eros. Aliquam auctor neque
            tempor, faucibus dolor ac, placerat lectus. Praesent vel massa libero. Pellentesque vel finibus velit, eget
            lobortis lorem. Integer vel lorem faucibus, interdum ante sit amet, imperdiet urna. Donec dignissim mauris
            lacus, et molestie lectus accumsan eu. Sed vel blandit diam. Pellentesque mollis ipsum a interdum sodales.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
```

### Expected behavior
Padding automatically resizes depending on viewport size and text word-break being set

### Screenshots
<img width="244" alt="Screen Shot 2021-02-01 at 4 25 21 PM" src="https://user-images.githubusercontent.com/11817992/106520151-5187bc00-64aa-11eb-8411-61077bf44b43.png">
<img width="1118" alt="Screen Shot 2021-02-01 at 4 23 12 PM" src="https://user-images.githubusercontent.com/11817992/106520228-72501180-64aa-11eb-918a-ca1c8f2df1e4.png">

### System setup
- **USWDS version:** 2.10.0
- **Device:** MacBook Pro (15-inch, 2018)
- **Operating system:** Catalina
- **Browser and version:** Chrome v.88.0.4324.96

**Comment by mitchmoccia** [comment]
@ascreven We addressed this by removing the `display: table-cell` designation in `.usa-summary-box__body` and adding an at-media-max rule to include `word-wrap: break-word;` to the `.usa-summary-box__heading` class at smaller screen sizes. Here's the result on smaller viewports:

![image](https://user-images.githubusercontent.com/19338309/109217683-1ebca500-7784-11eb-9a25-06f832a8deac.png)

Federalist link:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3965-summary-box-text-overflow-fix/components/detail/summary-box.html

[PR issued](https://github.com/uswds/uswds/pull/4039) and it should be picked up in the next release. Thank you!

**Comment by thisisdano** [comment]
Hi, I've reviewed this and I don't think we should make the change to `word-wrap` since I would prefer the text overflow than a word wrap unexpectedly. This could lead to misunderstandings. `Key informati on` seems like a typo, and this this extreme narrow width situation is an edge case where the fix may be worse than the problem.
