### ISSUE TITLE
Second level of side navigation is not distinct enough from the first level

### ISSUE THREAD

**Issue by actuallyjenn** [uswds/uswds#3967]
I think there were a few different iterations of how the side navigation used to be but as it stands, it is difficult to distinguish the first and second level of the side nav.

![image](https://user-images.githubusercontent.com/6501138/106989994-fb7c7800-6738-11eb-99ca-a9823f0ad0dd.png)

I noticed this as an issue specifically on the smeqa.usds.gov site when I was navigating to the different subheadings here. It was too subtle to be able to tell from a font size change (no indent, etc) which was a second level link vs a first level one:
![image](https://user-images.githubusercontent.com/6501138/106990220-6f1e8500-6739-11eb-90ae-38bac0c1c654.png)

Interestingly enough, I think it could be handled a couple of different ways:

How it works on USWDS site: 
![image](https://user-images.githubusercontent.com/6501138/106990062-2070eb00-6739-11eb-922a-9e7559087952.png)

Seen on the sprint.usds.gov site:
![image](https://user-images.githubusercontent.com/6501138/106990093-2f579d80-6739-11eb-84cb-5f421183bcef.png)

Seen on the ux-guide.18f.gov site:
![image](https://user-images.githubusercontent.com/6501138/106990109-3aaac900-6739-11eb-8218-c6a697cbd035.png)

**Comment by maya** [comment]
@actuallyjenn we also open #3994 with another idea, though might not be the way to go.

**Comment by thisisdano** [comment]
We fixed the indent issue that was making this particularly hard to distinguish :)

<img width="1055" alt="Screen Shot 2021-02-24 at 4 37 34 PM" src="https://user-images.githubusercontent.com/11464021/109085494-a2ac5980-76be-11eb-8f5c-3e61395e2a2c.png">

We will be moving forward with further improvements to how we highlight the current page and its parents (ancestors?)
