### ISSUE TITLE
Publish and comms for blog March 22 - USWDS

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3975]
Publish Post (No. 3) USWDS Working with the...

PR: https://github.com/uswds/uswds-site/pull/1166
Comms: https://docs.google.com/document/d/14ZhLuC4keq1yIT1RiNQ47WME22Yw2dnMRvZrEiLPEu4/edit?ts=60187b02#heading=h.ec3qj24pk3xi

**Comment by jAigret-Bix** [comment]
Blog is live 3/24. issue is ready for acceptance @afeijoo

**Comment by afeijoo** [comment]
https://designsystem.digital.gov/whats-new/updates/2021/03/24/working-with-uswds-team/
