### ISSUE TITLE
Publish and comms for Blog March 1 - Emergency response 

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3976]
March 1: Emergency response blog post 1 (uswds)
https://github.com/uswds/uswds-site/pull/1164

Live post:
https://designsystem.digital.gov/whats-new/updates/2021/03/01/improving-emergency-response/ 

[Comms plan ](https://docs.google.com/document/d/14ZhLuC4keq1yIT1RiNQ47WME22Yw2dnMRvZrEiLPEu4/edit?ts=60187b02#heading=h.qija0d6k3uhh)

**Comment by afeijoo** [comment]
Done. Blog post published and shared on Slack and Twitter.

https://designsystem.digital.gov/whats-new/updates/2021/03/01/improving-emergency-response/
