### ISSUE TITLE
Combobox component does not have error styling

### ISSUE THREAD

**Issue by ajanickiv** [uswds/uswds#3978]
### Describe the bug
Cannot apply error styling to the Combobox component

### Steps to reproduce the bug
1. Add usa-error--input to a `<select>` wrapped in a `<div>` with the usa-combo-box class

### Expected behavior
Error styling applies to input similar to the dropdown component
```
            <form class="usa-form">
                <label class="usa-label" for="options">Dropdown label</label>
                <select class="usa-select usa-input--error" name="options" id="options">
                    <option value>- Select -</option>
                    <option value="value1">Option A</option>
                    <option value="value2">Option B</option>
                    <option value="value3">Option C</option>
                </select>
                <label class="usa-label" for="fruit">Select a fruit</label>
                <div class="usa-combo-box">
                    <select class="usa-select usa-input--error"
                            name="fruit"
                            id="fruit">
                        <option value>Select a fruit</option>
                        <option value="apple">Apple</option>
                        <option value="apricot">Apricot</option>
                        <option value="avocado">Avocado</option>
                    </select>
                </div>
            </form>
```

### Screenshots
![image](https://user-images.githubusercontent.com/16595489/107086201-a89dd180-67c7-11eb-82f2-68e89de84cfe.png)

### System setup
- **USWDS version:** 2.10.0
- **Device:** Laptop
- **Operating system:** Windows 10
- **Browser and version:** Edge 88.0.705.56

**Comment by ajanickiv** [comment]
This also applies to the time picker
`                <div class="usa-form-group">
                    <label class="usa-label" id="appointment-time-label" for="appointment-time">Appointment time</label>
                    <div class="usa-hint" id="appointment-time-hint">hh:mm</div>
                    <div class="usa-time-picker">
                        <input class="usa-input usa-input--error" id="appointment-time" name="appointment-time" type="text" aria-describedby="appointment-time-label appointment-time-hint">
                    </div>
                </div>`

**Comment by mejiaj** [comment]
These are dynamically enhanced components, which would require to add the new error class on validation anyways.

**Comment by mejiaj** [comment]
@thisisdano this is safe to close. The elements are dynamically enhanced, which requires JS to add the right error class.
