### ISSUE TITLE
Restructure JS files to component directory

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3986]
Restructure JS files to component directory
LOE: 1-2 weeks (about a sprint)

- [x] move JS to corresponding component folders
- [x] update gulp build task (as needed)

**acceptance criteria**
- [x] once moved, the USWDS build should compile w/o errors
- [x] test that everything is working
- [x] Follow up issue: Research testing options, omit Fractal #3998 created.

**Comment by sarnikbixal** [comment]
Consolidated all JS components into their corresponding folders. Had to move out password.js to its own component - we will not expose this as it requires to be inside of a form. It is used in two templates. Please see the PR for further details.

Unit testing will not be available with the current pattern lab infrastructure. A ticket is in the works for rebuilding the unit test/ regression testing platform. We can then test/update all tests for all components in that issue.
