### ISSUE TITLE
Group guidance for varying lists - default, process, and icon.

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#4001]
Currently icon list and process list are standalone components and default list is grouped with Typography component.

**Comment by thisisdano** [comment]
We'll be breaking list out of typography, and will be deprecating nav groups in favor of filterable tags and keywords a la icons

**Comment by thisisdano** [comment]
Fixed by https://github.com/uswds/uswds-site/pull/1136
Preview → https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-reorganize-components/components/overview/
