### ISSUE TITLE
Support Spanish version of 404 template

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#4009]
Tasks

- [x] Reach out to USAGov en Español team
- [x] Draft copy for Spanish code variants
- [x] Review and update guidance for for multilingual considerations, if any
- [x] Update YML settings file (similar to Search and Banner components)
- [x] Update Spanish code variations on USWDS site 
- [x] Update guidance on USWDS site

DOD
All tasks above are done.

**Comment by afeijoo** [comment]
Blocked pending release of 404 page templates in 2.11: https://github.com/uswds/uswds/issues/3693

**Comment by afeijoo** [comment]
The Spanish versions for the [404 page template](https://docs.google.com/document/d/175kuLRfoZfIUZRs9X_iTzOz267eH2BLgXirWn3r2ark/edit)🔒 is done and ready to be implemented. Note that we identified a minor update that will need to be made to the English versions too.

Also reviewed the guidance and no additions are needed.

Ready for you @thisisdano or @mejiaj!

**Comment by jAigret-Bix** [comment]
closing this issue, released in v2.12
