### ISSUE TITLE
Support Spanish version of Authentication templates

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#4012]
Tasks

- [x] Reach out to USAGov en Español team
- [x] Draft copy for Spanish code variants
- [x] Review and update guidance for for multilingual considerations, if any
- [ ] Update YML settings file (similar to Search and Banner components)
- [ ] Update Spanish code variations on USWDS site 
- [ ] Update guidance on USWDS site

DOD
All tasks above are done.

**Comment by afeijoo** [comment]
In progress. Working with the USAGov en Español team on Spanish variants and guidance.

**Comment by afeijoo** [comment]
The [Spanish versions for the 3 authentication pages templates](https://docs.google.com/document/d/1e9MrW5o6uDZjq3v1a2TAGYUfcm1IFD2hV3pbNhS1h7s/edit):lock: is done and ready to be implemented. Note that we identified some minor updates that will need to be made to the English versions too.

Also reviewed the guidance and no additions are needed.

Ready for you @thisisdano or @mejiaj!

**Comment by mejiaj** [comment]
@afeijoo is it safe to move this to `Sprint Backlog` so we can prioritize and assign?

**Comment by afeijoo** [comment]
@mejiaj Yes, I moved to the `Backlog`.
