### ISSUE TITLE
Draft content and messaging plan surrounding  "core components" page

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4021]
[This plan](https://docs.google.com/document/d/1ySdXCiQ09K-IcSDOCCF4SrgWKE_U8dba4PJ6IbFJt_w/edit#) lays out the proposed content and messaging surrounding a new "core components" page. The core components page will be a new page within a newly designed [components landing page](https://github.com/uswds/uswds/issues/4038)

- [x] Create [draft guidance and comms plan](https://docs.google.com/document/d/1ySdXCiQ09K-IcSDOCCF4SrgWKE_U8dba4PJ6IbFJt_w/edit#heading=h.fs21icmzxpcy) around how to use Banner and Identifier together.
- [x] Client review and feedback 
- [x] Second draft:  identifier and banner to be the "core components." Add  header/footer as pre-existing (same link as above)
- [x] review second draft

**DOD**
- [x] all tasks are complete
- [x] Link this issue to the components landing page issue #4038 
dependent on https://github.com/uswds/uswds/issues/3744

**Comment by jAigret-Bix** [comment]
[Content and messaging](https://docs.google.com/document/d/1ySdXCiQ09K-IcSDOCCF4SrgWKE_U8dba4PJ6IbFJt_w/edit#heading=h.fs21icmzxpcy) surrounding a Core Components section on the new component landing page has been created. This work is captured in the backlog for future consideration: https://github.com/orgs/uswds/projects/6#card-56949170. Ready for acceptance and close @afeijoo

**Comment by afeijoo** [comment]
LGTM
