### ISSUE TITLE
2021: Component library migration

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4023]
**Description:** Move our internal library from Fractal to Storybook

- Storybook should do everything our internal library was doing before
- Needs to run the same NPM tests that it runs now 
- Develop and display components
- Powers USWDS site
- Does the same things for end users, same JS, SASS entry point, etc. End users do not notice a change

**Milestone:** https://github.com/uswds/uswds/milestone/75

**Comment by brunerae** [comment]
Closing in favor of more actionable tasks: https://github.com/uswds/uswds/issues/4370 https://github.com/uswds/uswds/issues/4440
