### ISSUE TITLE
Pagination: create design assets

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4026]
See detailed process list [Design assets](https://docs.google.com/document/d/12N_4bxlxsjtjQkvgCqwvWQyECneqE43qsljkmwCEmDE/edit#heading=h.c99hu4kbcpn4) - detailed checklists and good practices

- [ ] create/update Sketch /Adobe HD 
- [ ] Hi-fi Sketch assets review
- [ ] Hi-fi Adobe XD assets review
- [ ] review w/ Dan + merged into master working files

**Comment by mejiaj** [comment]
Closing this as uswds/uswds-for-designers/pull/86 got merged.
