### ISSUE TITLE
Intro to "Components" landing page

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4036]
A new [intro to the component landing page](https://docs.google.com/document/d/1MBi0CeKNjkrfUmnMjrKrQA0c1AdDKrkynUEarYJw1uU/edit?usp=sharing) has been created. Component specific intros were pulled from the preview page and tweaked. 

**Description**
Create content for [components landing  page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-reorganize-components/components/overview/). Include an Introduction and index of components with descriptions. 
- [x]  Create [Draft](https://docs.google.com/document/d/1MBi0CeKNjkrfUmnMjrKrQA0c1AdDKrkynUEarYJw1uU/edit?usp=sharing):  expanded introduction for the new landing page
- [x] Review included descriptions of each components
- [x] internal review
- [x] Client review

**Comment by thisisdano** [comment]
Integrated as a part of https://github.com/uswds/uswds-site/pull/1136
