### ISSUE TITLE
New Component landing page

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4038]
https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-reorganize-components/components/overview/

- [x] finalize landing page copy #4036 (days)
- [x] update layout/design as needed (days)
- [ ] Test and review DW PRs (hour)

associated `core components` page  #4021

**Comment by thisisdano** [comment]
Fixed by https://github.com/uswds/uswds-site/pull/1136
