### ISSUE TITLE
Docs update: usa-button--inverse requires usa-button--outline

### ISSUE THREAD

**Issue by dispatchrabbi** [uswds/uswds#4046]
## Description

I've been using USWDS to put together [a website for my podcast](https://www.whyyoushouldvote.com/) and I've really enjoyed using it! While the docs are occasionally a little tough to jump around at first (there's a lot of info to take in), after using them for a while, I got the hang of it. However, I did notice one thing that is unclear and/or unremarked-upon by the docs.

Specifically, there's no indication that an inverse-style button also requires the outline variation to work. That is, these two buttons look the same:

```html
<button class="usa-button">Click me!</button>
<button class="usa-button usa-button--inverse">Click me!</button>
```

You need to add the `usa-button--outline` class as well for `usa-button--inverse` to have any effect, and that isn't mentioned anywhere on [the component's page](https://designsystem.digital.gov/components/button/) except in the component code example (which is collapsed by default and which I did not look at because I was following the instructions under the *Implementation* section).

It would be beneficial to future web developers to mention that the inverse variant needs both classes.

P.S.: I did not include repro steps because they seemed... unnecessary. If process requires them, let me know and I'll add them.

**Comment by thisisdano** [comment]
Related to #3074

**Comment by thisisdano** [comment]
Closing in favor of https://github.com/uswds/uswds/issues/3074
