### ISSUE TITLE
Using a custom font disables default font stack and breaks font display

### ISSUE THREAD

**Issue by maya** [uswds/uswds#4048]
### Describe the bug
When adding a custom font, it would not load the default stack along with my custom font. 

Rather, it displays as:
`font-family: Inter,;`
which breaks the font from appearing bc of the comma.

 unless I added it manually in `$theme-font-sans-custom-stack` [as seen here](https://github.com/CDCgov/SimpleReport_Public_Site/blob/main/_sass/_uswds-theme-typography.scss#L197), then it works as expected.

I expect not to have to manually add the custom font stack and the default stack just works.

**Comment by mejiaj** [comment]
Resolved in https://github.com/uswds/uswds/pull/4084
