### ISSUE TITLE
File Input: Format validation is limited to drag-and-drop

### ISSUE THREAD

**Issue by aduth** [uswds/uswds#4053]
The File Input component only validates accepted formats on drag-and-drop interactions. While most browsers will filter files in a file picker dialog when an `accept` attribute is present, most will still allow the user to override this filter and select any file. If the expectation is that the File Picker will validate any files, it should run the validation on all changes, not only drop events.

### Steps to reproduce the bug

1. Navigate to https://designsystem.digital.gov/components/form-controls/#section-form-controls-08-file-input
2. In the "Input accepts only specific file types" (PDF, TXT) example, click the link to "choose from folder"
3. Change the filter to allow any file to be selected
4. Choose any file

**Expected behavior:** I am warned that the file is not a valid type.

**Actual behavior:** The file is selected, and no warnings are shown.

### Screenshots

Overriding filter format in macOS Chrome:

![image](https://user-images.githubusercontent.com/1779930/109360514-5fd0ba00-7855-11eb-8428-7119a3cc94b8.png)

After selecting an invalid file:

![image](https://user-images.githubusercontent.com/1779930/109360551-6d863f80-7855-11eb-8fa6-498f558859ba.png)

### System setup

- **USWDS version:** v2.10.1
- **Operating system:** macOS, Windows 10
- **Browser and version:** Chrome 88.0.4324.192, Internet Explorer 11

### Additional context

Existing validation occurs here:

https://github.com/uswds/uswds/blob/1f9bb1cca8afdd1d00481f00bf32a38169790058/src/js/components/file-input.js#L356-L363

Validation should probably occur during `onchange` as well:

https://github.com/uswds/uswds/blob/1f9bb1cca8afdd1d00481f00bf32a38169790058/src/js/components/file-input.js#L366-L368

The existing `preventInvalidFiles` may need to be adapted, because it assumes a drop event where files are assigned on the [`event.dataTransfer` property](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/files):

https://github.com/uswds/uswds/blob/1f9bb1cca8afdd1d00481f00bf32a38169790058/src/js/components/file-input.js#L210

**Comment by mejiaj** [comment]
Moved to `2.12.0` release due to ongoing development.
