### ISSUE TITLE
Allow for dynamic initialization of tooltip component

### ISSUE THREAD

**Issue by jakerella** [uswds/uswds#4055]
**Is your feature request related to a problem? Please describe.**

I dynamically add elements to my page, some of which need a tooltip. Adding the tooltip classes and attributes does not allow the USWDS tooltips to be visible (although the browser default UI is) because the JS code has already initialized the components that were present at page load.

**Describe the solution you'd like**

I would like the ability to "trigger", in some way, the initialization of a tooltip (or multiple) given a root node. It looks like the code already does this through the `init` method of the component, so I just need a way to hit that. I would like to NOT modify the USWDS codebase to do this.

**Describe alternatives you've considered**

I've poked around at the JS code, but since nothing is exposed on the global context, I don't see a way to re-execute the tooltip init method for a given (sub)root node.

**Comment by jakerella** [comment]
I have created a short term workaround for this. It only works for "top" tooltips, but could be made to work with other positions. The key was to trigger the adding and removing on classes myself.

In my html, I manually created the tooltip body at the same time that I create the tooltip trigger element:

```
<span class="usa-tooltip__body usa-tooltip__body--top" id="tooltip-[some id]" role="tooltip" aria-hidden="true">My tooltip text</span>`
```

In my stylesheet, I changed to styles on the tooltip body. The `display` was set to `none`, but that was unnecessary as the `opacity` is also `0` (note that this is bad for non-visual users). The `bottom` was reset because I ended up using `top` instead.

```
.usa-tooltip__body {
    display: block;
    bottom: auto;
}
```

In my JS, I added a `mouseover` and `mouseout` handler for the table I was adding elements to dynamically

```
someParentElem.addEventListener('mouseover', (e) => {
    let tooltipTrigger = findTrigger(e.target)  // helper method to get the correct parent
    // now find the tooltip described by the trigger and add the "is-visible" class
    someParentElem.querySelector('#' + tooltipTrigger.getAttribute('aria-describedby')).classList.add('is-visible')
})
someParentElem.addEventListener('mouseout', (e) => {
    // do the reverse of above
})
```

Last thing was to set the top and left of each tooltip body after I created them. Not too difficult, but also not a perfect solution:

```
Array.from(row.querySelectorAll('.usa-tooltip')).forEach((trigger) => {
    const triggerPos = trigger.getBoundingClientRect()
    const tip = row.querySelector('#' + trigger.getAttribute('aria-describedby'))
    tip.style.top = (trigger.offsetTop - triggerPos.height - 20) + 'px'
    tip.style.left = (trigger.offsetLeft + (triggerPos.width / 2)) + 'px'
})
```

**Comment by thisisdano** [comment]
@mejiaj Can you confirm that this was fixed by #4319?

**Comment by mejiaj** [comment]
Component **doesn't** automatically initialize.

**Testing steps**

1. Go to [tooltips page](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/iframe.html?args=&id=components-tooltip--tooltip&viewMode=story)
2. Open devtools → console
3. Insert markup sample below
4. Verify it doesn't initialize

**Markup sample**

```js
// Create element
const dynamicTooltip = document.createElement("button");

// Add attributes
dynamicTooltip.setAttribute("type", "button");
dynamicTooltip.setAttribute("data-position", "top");
dynamicTooltip.setAttribute("title", "A dynamic tooltip");
dynamicTooltip.classList.add("usa-button", "usa-tooltip");
dynamicTooltip.textContent = "My dynamic tooltip";

// Append to document
document.body.appendChild(dynamicTooltip);
```

**Comment by amyleadem** [comment]
@mejiaj The tooltip appears to automatically initialize when I run this in codepen: https://codepen.io/amyleadem/pen/WNzGWgV

Will you let me know if you see any issues with this implementation? If not, I will consider this fix verified.

**Comment by mejiaj** [comment]
@amyleadem thanks for that codepen. That looks correct. I've updated my comment.

**Comment by jakerella** [comment]
Hi @mejiaj and @amyleadem, thanks for the continued hard work on USWDS!

Unfortunately, the recent changes have _not_ resolved the issue. Here is a [codepen showing the issue](https://codepen.io/jakerella/pen/JjLNNOE) which was forked from @amyleadem's codepen. The problem here is that the tooltip does not initialize when elements are dynamically added _after loading_. Codepen runs the code in a slightly different manner which hides the issue.

My fork shows how the problem still exists by attempting to add a new button to the page based on a user click. You'll notice that the button is actually exactly the same in terms of classes and attributes, but does not get it's tooltip initialized. If you inspect the HTML, you can see that `<span class="usa-tooltip">` for the dynamically generated button is missing (and of course all of the other elements that need to be there).

What I need is to be able to add an element to the page at an arbitrary time _after loading_ and somehow initialize a tooltip on that element.

**Can we reopen this issue?**

**Comment by jakerella** [comment]
@mejiaj or @amyleadem any chance someone can verify that this issue is not resolved per my comment above?

**Comment by amyleadem** [comment]
Apologies for the delayed response. Thanks for sending this update and demo. We really appreciate the thorough response. I will reopen the issue so that the team can take another look. Let us know if you have any other questions or comments!

**Comment by hobbez** [comment]
There is a general issue with dynamically added components not getting initialized and sometimes causing JavaScript errors. See https://github.com/uswds/uswds/issues/4903 for more info. A proper fix for all, not just tooltip, would be appreciated.

**Comment by mejiaj** [comment]
@hobbez there are things that we _can_ do to improve the experience, but we have to look at each component individually.

Overall we can improve:
1. Initial scaffolding check on interaction (where it makes sense)
2. Give users public methods they can call in their own for frameworks

We looked briefly at using things like mutationObserver, but decided the LOE was too high for too little reward. The best solution we can give at the moment is allow users to hook into component functionality.

**Comment by jakerella** [comment]
So glad to see this fixed! Is there a "canary" or pre-release minified JS file we can use to test things like this out in a codepen? Or do we need to wait for an official "latest stable" release?
