### ISSUE TITLE
Provide better support for color icons that adapt to theme settings

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#4064]
### Describe the bug
Any attempt to change `$theme-text-color` to anything other than 'ink' leads to an error. 

From @aduth 
> It does seem like there might be a bug here, in that [this code](https://github.com/uswds/uswds/blob/aead326413aee55858faa17fc689610eff9d3063/src/stylesheets/core/mixins/_alert-status-styles.scss#L10) expects to find icons of various alert types (warning, etc) in [the img/alerts folder](https://github.com/uswds/uswds/tree/350a02ea0d1b427d1a8205bd779e02f8fd0b01b5/src/img/alerts) ending in `-white`, but there’s only the error icon there.

### Steps to reproduce the bug
1. Change the value of `$theme-text-color` to anything other than `ink`
2. Look at the info alert, it will no longer have an icon and there will be an error in the console

This may affect more than just the alert.

### Expected behavior
In addition to updating the text color, the system should be able to display icons that match the theme color in relevant components.

### Additional context
We want to use our color icon mixins to place these icons into an alert.

**Comment by jAigret-Bix** [comment]
@thisisdano can this issue be closed?
