### ISSUE TITLE
Incorrect text color on current items in sidenav

### ISSUE THREAD

**Issue by asarazor** [uswds/uswds#4073]
### Description

The color of the current sidenav item is now `base-dark`. Previously it was `primary`. I believe this was not intentional, but a regression introduced in #3838. The color specified in `a:not(.usa-button)` (compiled specificity: `0.2.1`), inside the nav-list mixin, replaces less specific primary color set on `.usa-current` (compiled specificity: `0.2.0`).

If in fact this was an intentional design change, then documenting it in the release notes would be helpful. 

### Steps to reproduce

View latest [component on documentation site](https://designsystem.digital.gov/components/sidenav/)

### Expected behavior

The current pages and sub pages should use the `primary` color. Compare to a site using the vanilla sidenav styles on > uswds-2.10 e.g. [oig.hhs.gov/newsroom](https://oig.hhs.gov/newsroom/ )

### Screenshots

As of v2.10+
<img width="460" alt="image" src="https://user-images.githubusercontent.com/19854/110153344-ec78fc00-7db0-11eb-8a58-108ceeeb62bf.png">

v2.8.1
<img width="445" alt="image" src="https://user-images.githubusercontent.com/19854/110153240-cb181000-7db0-11eb-9a88-0dd9bd1df42c.png">

### System setup

USWDS version: 2.10.0
Browser and version: Chrome 87.0

### Possible solution

The original PR for #3838 caused a similar specificity problem in #3967. It may be best to reconsider how to solve the original anchor button problem using a less greedy or less specific selector.

### Additional context

I think this has been missed because the USWDS documentation site intentionally chose to use `base-darker` in their own custom styles. So people are habituated to that look.

**Comment by asarazor** [comment]
This issue appears to be related design-wise to #3994, which is on the core teams roadmap. Assuming it will be addressed there with an updated design pattern, this could be closed.

**Comment by thisisdano** [comment]
I think this should be considered a bug right now, and we'll get it fixed.
