### ISSUE TITLE
Print styles not working

### ISSUE THREAD

**Issue by maya** [uswds/uswds#4076]
### Describe the bug
I've installed the code from #4015 to get print styles on our site in https://github.com/CDCgov/prime-simplereport-site/pull/79, but it has no effect on printing and still appears broken.

I've verified `@media print` appears in the stylesheet.

Print utility CSS isn't working either.

**Major issues:** 
- Govt banner is fully expanded
- Image issues:
  - misaligned
  - cutoff
  - too large at times
- Sidenav appears first

**Other issues:** 
- Uses Times New roman font
- Step list is just a regular list

### Steps to reproduce the bug
1. Go to /resources/using-simplereport/select-your-testing-facility/
2. Try to print the page
3. Go to print preview
4. See messed up print preview

### Expected behavior
A clear view of the page

### Screenshots

**What I see**

**Page 1**
<img width="471" alt="Screen Shot 2021-03-09 at 1 23 44 PM" src="https://user-images.githubusercontent.com/5249443/110540367-47756080-80db-11eb-92bd-33f161f98428.png">

**Page 2**
<img width="469" alt="Screen Shot 2021-03-09 at 1 23 51 PM" src="https://user-images.githubusercontent.com/5249443/110540387-4c3a1480-80db-11eb-8409-137510f09344.png">

**What I expect to see** (at least something similar)
<img width="400" src="https://user-images.githubusercontent.com/5249443/110526890-33296780-80cb-11eb-9551-018ae61bafe5.png">

### System setup
- **USWDS version:** `accelerator/3940-printer-friendly`
- **Device:** macbook
- **Operating system:** big sur
- **Browser and version:** latest chrome

Related #3940

**Comment by maya** [comment]
Had to remove the preview link as it's being used for another feature.

**Comment by thisisdano** [comment]
I'm not sure what's happened here, but it looks like no stylesheets were loaded at all. That said, we won't be proceeding with that version of print styles. I think it needs to be rethought and we're going to focus on known printing issues before trying to do anything more invasive.

How does your page print with "conventional" USWDS CSS?

**Comment by maya** [comment]
@thisisdano the uswds-jekyll template uses `media="screen"` for the stylesheet link which does not allow the stylesheet to load during printing. Removing this makes the stylesheet load.
