### ISSUE TITLE
Draft content: high level system benefits

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4094]
Draft new content providing high-level system benefits "why use USWDS" 
-shared w AF 3/25

DoD 
o	[Draft content ](https://docs.google.com/document/d/1oMVCGtugcmx1rMjtYz5OsGHzO0wbZfTW43Udix_Rhg8/edit#)of system benefits/value proposition for review
-create an understanding of how where this content will be used, create follow up issues.

**Comment by KMullan944** [comment]
Latest copy: https://docs.google.com/document/d/1oMVCGtugcmx1rMjtYz5OsGHzO0wbZfTW43Udix_Rhg8/edit

**Comment by jAigret-Bix** [comment]
Reviewed by AF 3/25

**Comment by KMullan944** [comment]
Copy passed off to Katharine & James for design/dev of page, so it can be ready by Apr 15, Monthly Call.

**Comment by jAigret-Bix** [comment]
System benefit [content is created](https://docs.google.com/document/d/1oMVCGtugcmx1rMjtYz5OsGHzO0wbZfTW43Udix_Rhg8/edit#) for [page build](https://github.com/uswds/uswds/issues/4150). Issue is complete and ready for acceptance @afeijoo

**Comment by afeijoo** [comment]
🎉  https://designsystem.digital.gov/about/key-benefits/
