### ISSUE TITLE
Alert icon: The alert icon is displaying incorrectly on Chome browser

### ISSUE THREAD

**Issue by Gnuk** [uswds/uswds#4111]
## Description

On `usa-alert` component using `usa-alert--info` variant, we expect to see  a information icon on Google Chrome, bu we see a black rectangle. We should see a info icon instead (like in Firefox).

## Steps to reproduce the issue

1. Create a project using SCSS and add, in the default style file:

Example for `src/style.scss` and img files inside `img` and font inside `fonts` directories.

```scss
$theme-font-path: 'fonts';
$theme-image-path: 'img';

@import '../node_modules/uswds/dist/scss/uswds';
```

2. Compile your scss file
3. Create a HTML file and add this code inside your body:

```html
<div class="usa-alert usa-alert--info" >
  <div class="usa-alert__body">
    <h4 class="usa-alert__heading">Informative status</h4>
    <p class="usa-alert__text">Lorem ipsum dolor sit amet, <a class="usa-link" href="javascript:void(0);">consectetur adipiscing</a> elit, sed do eiusmod.</p>
  </div>
</div>
```

4. Open in Google Chrome: you will see a black rectangle
5. Open in Firefox: you will see the icon

## Additional information

* Relevant research and support documents

I found that `mask` is supported in Firefox but not in Google Chrome. But if I Add the `-webkit-mask` instead of `mask` to show the icon, it works.

* Screen shot images

> Google Chrome:

![Chrome alert info](https://i.imgur.com/LXHeSB6.png)

> Firefox:

![Firefox alert info](https://i.imgur.com/ThEYCYm.png)

* Notes
  * I think it could be interesting to manage `-webkit-mask` in order to fix the problem
  * The version is 2.11.1

**Comment by nonomoho** [comment]
I have the same problem on Chrome and Edge.

**Comment by sawyerh** [comment]
Sass compilation requires the usage of something like [`autoprefixer`](https://github.com/postcss/autoprefixer), which would compile the CSS so that it includes `-webkit-mask`: https://designsystem.digital.gov/documentation/developers/#sass-compilation-requirements

**Comment by Gnuk** [comment]
Thank you @sawyerh, it's now ok with postcss and autoprefixer so I close the issue!
