### ISSUE TITLE
Pagination: release prep activities

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4112]
Final steps for release 

- [x] Updates to design and review (KC)
- [x] [Final guidance ](https://docs.google.com/document/d/1d-8MJXUZKcYfba9jXQzMvvoHFHdNNItZMMXsco7ELn0/edit#heading=h.p3hvn8jllvv2)updates 3/30
- [x] Updates to code (JM) 
- [x] [PR](https://github.com/uswds/uswds/pull/4121) and updated guidance to Dan by 3/30)

- [x] 508 [test page](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-library-add-pagination/patterns/test-patterns-usa-pagination-usa-pagination-page/test-patterns-usa-pagination-usa-pagination-page.rendered.html) test team hand off 4/5 [Link to test results](https://drive.google.com/file/d/1r6NSBS8fQnxsX3fUkhQA5xQEwEGdevSv/view?usp=sharing)

DoD:
All tasks complete

**Comment by KMullan944** [comment]
Current state of pagination guidance: https://docs.google.com/document/d/1d-8MJXUZKcYfba9jXQzMvvoHFHdNNItZMMXsco7ELn0/edit#heading=h.p3hvn8jllvv2

**Comment by katharine-carr** [comment]
Thanks @mejiaj ! Here are my notes:

- The page numbers are showing up as purple/visited link color for me - weird! Maybe its me?

- Could there be some space added between the prev/next links and the page buttons? In my doc I used 40 px space. Maybe try that and see how it looks.

- I am really squinting but I think there is an outline showing on the current-page-indicator state and hover state. Are we able to have no outline on the page buttons when in those states? Or perhaps the outline can match the fill color. 

- For the prev/next links, what do you think about having the text just underline on hover? Im thinking the current hover might not be punchy enough for text alone, but interested to know what you think.

**Comment by jAigret-Bix** [comment]
These final release ready tasks are complete. Next [issue for site page build ](https://github.com/uswds/uswds-site/issues/1205)is created. Issue is complete and ready for acceptance @afeijoo
