### ISSUE TITLE
Button: Disabled button pointer events styling may be unnecessary or is at least inconsistent

### ISSUE THREAD

**Issue by aduth** [uswds/uswds#4122]
### Describe the bug

Disabled buttons currently apply a `pointer-events: none` style that prevents pointer interactions (mouse clicks, hover) from taking effect:

https://github.com/uswds/uswds/blob/3dc296ec56cd621fe52d918701fd94621d96a198/src/stylesheets/core/mixins/_button-disabled.scss#L5

This can stop click handlers from being triggered if a user clicks on the button using a mouse, but importantly it does nothing to prevent a user from "clicking" the button when using the keyboard.

Instead, I'd expect one or the other of the following:

- If the intention is to prevent click interactions, this should be consistent for clicks which occur by keyboard presses, which may require JavaScript.
- Alternatively, for use-cases where someone may want to give the visual appearance of a disabled button without preventing interactions, the `pointer-events: none;` provides an inconsistent experience and should be removed.
   - (Anecdotally, this is the use-case in our project)

Note that this is only relevant for disabled buttons which don't already use [a `disabled` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled), where click, hover, _and keyboard focus_ interactions would already be disabled, and should be the typical implementation where these behaviors are desired.

### Steps to reproduce the bug

1. Go to https://codepen.io/aduth/pen/NWdGQQG
2. Click on the button. Observe that there is no alert shown.
3. Focus the button by clicking into the preview frame and tabbing to the button.
4. "Click" the button by pressing the <kbd>Space</kbd> key. Observe that an alert is shown.

### Expected behavior

The alert is consistently either never shown or always shown, regardless if the the click occurs by mouse or by keyboard.

### System setup

- **USWDS version:** 2.11.1
- **Operating system:** macOS Catalina
- **Browser and version:** Chrome 89

**Comment by sean1138** [comment]
adding the disabled attribute to a button with the usa-button usa-button--disabled class should work.
https://codepen.io/sean1138/pen/xxgZRJm

**Comment by mejiaj** [comment]
Sorry for the wait, I'll add this to our development review so we can take a good look this week or next.

**Comment by mejiaj** [comment]
_Moved comment from PR to issue._

I agree, it gives developers a false sense of confidence. But I think we should only remove this if we have JS in place to ensure they're truly disabled.

And/or we could also update the [button guidance](https://designsystem.digital.gov/components/button/) to recommend using `disabled` and note that the class is purely for styling purposes.

**Comment by aduth** [comment]
> And/or we could also update the [button guidance](https://designsystem.digital.gov/components/button/) to recommend using `disabled` and note that the class is purely for styling purposes.

Personally, this would be my preference. I can't imagine a situation where it wouldn't be appropriate to use the browser-native `disabled` attribute if one wants the behavior associated with a disabled field. While there's not many use-cases for a "visually disabled" button appearance, I think the CSS class is an appropriate solution, and is consistent with other visual-only stateful emulation classes like `usa-focus`, `usa-button--active`, and `usa-button--hover`.

**Comment by thisisdano** [comment]
Added a PR in `uswds-site` to update the button guidance: https://github.com/uswds/uswds-site/pull/1232
