### ISSUE TITLE
Dropdown/Select tag validation example in Documentation

### ISSUE THREAD

**Issue by pcast01** [uswds/uswds#4126]
**Is your feature request related to a problem? Please describe.**
Looking to see an example of validation I can use for a dropdown/Select html control.

**Describe the solution you'd like**
Can an example be put in the Validation area inside https://designsystem.digital.gov/components/validation/

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mejiaj** [comment]
@pcast01 do you have an example use case in mind?

**Comment by pcast01** [comment]
@mejiaj After posting this I see that I just had to code that part myself with a select dropdown. I was thinking there could be an example of how to use it with a dropdown and thought it was missing. 

for instance I would just change the className based on my own regex match in React.

````
className={
    this.state.fundingDropdown &&
    this.state.fundingDropdown.match(regexFunding)
      ? 'usa-checklist__item usa-checklist__item--checked'
      : 'usa-checklist__item'
}
`

**Comment by pcast01** [comment]
Feel free to close this since I beleive maybe there isn't an example you can put up. Thanks for responding.
