### ISSUE TITLE
USWDS - Library: Consolidate Gulp Tasks

### ISSUE THREAD

**Issue by scottqueen-bixal** [uswds/uswds#4127]
## Description

Current [library develop version ](https://github.com/uswds/uswds/tree/library--develop) has gulp tasks partially ported from `config/gulp` into `/gulp-tasks`. We should work to bring these directories together.

**Comment by scottqueen-bixal** [comment]
pushing code for this to https://github.com/uswds/uswds/tree/gsq-library-consolidate-gulp-tasks

**Comment by mejiaj** [comment]
Work was merged in part of https://github.com/uswds/uswds/pull/4140
