### ISSUE TITLE
USWDS - Library: Update Gulp Tasks to v4 Composition

### ISSUE THREAD

**Issue by scottqueen-bixal** [uswds/uswds#4128]
## Description

Some of the current gulp work should be resolved into gulp4 composition.

ie. current release tasks

## Additional information

https://gulpjs.com/docs/en/getting-started/creating-tasks

**Comment by scottqueen-bixal** [comment]
pushing code for this to https://github.com/uswds/uswds/tree/gsq-library-consolidate-gulp-tasks

**Comment by mejiaj** [comment]
Work was included in https://github.com/uswds/uswds/pull/4140
