### ISSUE TITLE
USWDS -  Library: Remove node-sass dependency

### ISSUE THREAD

**Issue by scottqueen-bixal** [uswds/uswds#4129]
## Description
some gulp integrations are still relying on node-sass, ie. gulp-sass, and should be replaced with dart-sass compilation.

## Additional information 
* gulp-sass is [outdated ](https://www.npmjs.com/package/gulp-sass)and lacking support
* [node-sass is deprecated](https://github.com/sass/node-sass/issues/2952)

**Comment by jAigret-Bix** [comment]
Complete and closing issue
