### ISSUE TITLE
USWDS -Library : include USWDS logo with "dark" theme

### ISSUE THREAD

**Issue by scottqueen-bixal** [uswds/uswds#4131]
## Description

our current version includes the logo in default light theme of the side bar, but displays pattern lab logo when toggled to dark.

## Additional information

![Screen Shot 2021-03-26 at 11 42 14 AM](https://user-images.githubusercontent.com/37077057/112657025-5c1a5e00-8e28-11eb-9c18-bdced0d8e147.png)
![Screen Shot 2021-03-26 at 11 42 05 AM](https://user-images.githubusercontent.com/37077057/112657027-5c1a5e00-8e28-11eb-9e82-3cbde4f3154e.png)

**Comment by mejiaj** [comment]
Pattern lab issue, closing.
