### ISSUE TITLE
USWDS - Library: Update code examples on USWDS-Site.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#4136]
Use the new library to power the component examples on USWDS-Site.

- [x] Update `build-uswds-if-needed` task
- [x] Update references to `uswds/dist` assets in gulp tasks 
- [x] Update code examples in `_includes/code/components`
- [x] Update references in Docs
- [x] Update `_plugins/fracal_component.rb`
- [x] Fix regressions on Component pages
  - [x] Broken input prefix/suffix demo
  - [x] Sidenav only shows 1 example 
  - [x] Missing logo in Footers
  - [x] Add all file input examples
  - [x] Add all table examples
  - [x] Add missing `usa-focus` styles
  - Fix code example formatting:
    - [x] Accordion
    - [x] Alert
    - [x] Borderless table
    - [x] Button group
    - [x] Buttons
    - [x] Card
    - [x] File input
    - [x] Footer
    - [x] Icon list
    - [x] Primary navs
    - [x] Site alert
    - [x] Step indicator

[Accordion for example](https://github.com/uswds/uswds-site/blob/main/_includes/code/components/accordion.html)

**Comment by thisisdano** [comment]
Very nice!
