### ISSUE TITLE
Following Link Guidance: Identifier Component

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds#4137]
As a user I want the links shown in the identifier component to reflect updated link guidance so that links are treated consistently. 

We released new [link guidance](https://designsystem.digital.gov/components/link/) in 2.11 and follow-on updates in https://github.com/uswds/uswds/issues/4125. We need to update the identifier component to follow the recommendations.

related to #4301

**Comment by brunerae** [comment]
@thisisdano this issue can be closed

**Comment by thisisdano** [comment]
Identifier conforms to our current link guidance
