### ISSUE TITLE
Visited Link Class displaying wrong color

### ISSUE THREAD

**Issue by adrianavecchiodhs** [uswds/uswds#4145]
### Describe the bug
Using the usa-color-text-visited class does not display the visited hyperlink color

### Steps to reproduce the bug
1. Go to https://www.dhs.gov/xlibrary/dhsweb/_site/typography.html
2. Scroll down to Links header
3. See "This is a visited link"
4. Link text is blue, but should display as violet-70v

### Expected behavior
usa-color-text-visited class "is a visited link" should display the link visited color designated in the custom theme, violet-70v

### System setup
- **USWDS version: Latest as of 04/06/2021
- **Device: Macbook Pro
- **Operating system:
- **Browser and version: Chrome, Safari, and Firefox

**Comment by mejiaj** [comment]
@adrianavecchiodhs we're going to close this issue for now. The example for visited is for documentation purposes only, but we'll keep an eye out to see if others want this included.

You can do the same by adding the visited link color:

```scss
.your-demo-visited-link {
  color: color($theme-link-visited-color);
}
```
