### ISSUE TITLE
Summary box component not on component packages list in styles.scss

### ISSUE THREAD

**Issue by phernand42** [uswds/uswds#4159]
### Describe the bug
I'm trying to add the summary box component as a package in my project but I noticed the summary box component is not listed in the current list of [individual component packages in style.scss file](https://github.com/uswds/uswds/blob/develop/src/stylesheets/theme/styles.scss). Will this option be available in a later release? 

### System setup
- **USWDS version: 2.11.1

**Comment by mejiaj** [comment]
Thanks for reporting this! We're looking into it.
