### ISSUE TITLE
Card: body-exdent variant has no scss rules

### ISSUE THREAD

**Issue by btwegmann** [uswds/uswds#4164]
### Describe the bug
The `.usa-card__body--exdent` variant has no scss rules associated with it.
### Steps to reproduce the bug
 1. Add the `.usa-card__body--exdent` class to a card-body element
 2. Observe no styling changes

### Expected behavior
The body element should extend out over the card border, just like the other `exdent` variants

**Comment by mejiaj** [comment]
@btwegmann would you mind sharing an example use case for this? The intent behind the body was to have it contain mostly text. 

I see the benefit of adding it for consistency, but I'm curious to see how it's being used.

**Comment by btwegmann** [comment]
> @btwegmann would you mind sharing an example use case for this? The intent behind the body was to have it contain mostly text.
> 
> I see the benefit of adding it for consistency, but I'm curious to see how it's being used.

So I don't have a specific use case in mind for this. I was actually playing around with the Card to see how the different variants (listed here: https://designsystem.digital.gov/components/card/) looked and noticed that the body-exdent one did not have any rules associated with it.

**Comment by mejiaj** [comment]
Closing since #4210 got merged.
