### ISSUE TITLE
modal

### ISSUE THREAD

**Issue by vijaypunyapu** [uswds/uswds#4177]
## Description

Include a high-level description of the issue. What did you expect to happen? What happened instead? What would you like to see changed?

Include any benefits, challenges, or considerations. This can be short and sweet.

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information [optional]

* Relevant research and support documents
* Screen shot images
* Notes
* And so on

**Comment by mejiaj** [comment]
@vijaypunyapu please provide information regarding your bug so we can help.

**Comment by vijaypunyapu** [comment]
@mejiaj , I am not sure when i created this ticket, guess it might be a mistake. Sorry for that. you can close this.

**Comment by mejiaj** [comment]
Thanks for the update!
