### ISSUE TITLE
Input Groups: Form group margin is inconsistent in error state

### ISSUE THREAD

**Issue by aduth** [uswds/uswds#4189]
### Describe the bug

The top margin applied by `.usa-form-group--error` (`2rem`) is inconsistent with `.usa-form-group` or the ungrouped `.usa-label`, which both apply a top margin of `1.5rem`. In practice, this can cause an undesirable page layout shift when toggling a form group between its unmodified and error states.

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/components/text-input/
2. Right click and "Inspect Element" on the error message preview
3. In the browser DevTools, remove the class `usa-form-group--error` from the wrapping form group
4. Observe that the top margin shifts

### Expected behavior

The margin between the form group and the preceding element should remain consistent to avoid page content shifting, regardless whether it's in an error state.

### Screenshots

https://user-images.githubusercontent.com/1779930/117032141-3e65d180-accf-11eb-8266-184b57340a48.mov

### System setup

- **USWDS version:** 2.11.2
- **Operating system:** macOS Catalina 10.15.7
- **Browser and version:** Chrome Version 90.0.4430.93

### Additional Context

The margin for the error modifier class is explicitly applied here:

https://github.com/uswds/uswds/blob/1908d1391bc59410624ca1934cc70b7404e8f443/src/stylesheets/elements/form-controls/_global.scss#L52-L54

This may suggest that it is an intentional change, though it's unclear for what reason this might be. At the time it had been implemented, there were no base styles for `.usa-form-group`, which were added later in #4056. Therefore, it may be reasonable to expect that this custom style for `.usa-form-group--error` could be removed, and allowed to inherit from `.usa-form-group`.

**Comment by jAigret-Bix** [comment]
Thank you for submitting this issue. Our team will look into it.
