### ISSUE TITLE
Flag icon is low resolution

### ISSUE THREAD

**Issue by rfultz** [uswds/uswds#4191]
**Is your feature request related to a problem? Please describe.**

When trying to optimize our site, the flag icon on the left of the usa-banner is setting off 'serves images with low resolution' warnings. The png is only 16 pixels wide in 2021 when every device is ultra high resolution.

It's the first image on every page of our site and represents our country and it's the lowest resolution, blurriest image on the site.

**Describe the solution you'd like**

Could we get larger flag image options? At this point, even exporting the original source at double the current width would help.

**Describe alternatives you've considered**

Should we just use our own image that's as close to this one (and maybe a more accurate blue)? I don't like the idea of only our site using a different flag.

Would it be out of bounds for us to create one/some and submit as pull request(s)?

**Additional context**

There was previously an [issue](https://github.com/uswds/uswds/issues/2190) filed for this but it was over three years ago.

**Comment by jAigret-Bix** [comment]
PRs are welcome, feel free to create one.

**Comment by aduth** [comment]
I had trouble tracking down a higher-resolution source version of this image. I can't find one in this repository, nor in the [Sketch design assets](https://designsystem.digital.gov/download/).

Oddly enough, I did find one in [our project source](https://github.com/18F/identity-idp/blob/main/app/assets/images/us-flag.png):

![image](https://user-images.githubusercontent.com/1779930/124150126-43d96100-da5f-11eb-8837-b6da757516ee.png)

While this could work to scale down and appear nicer for higher pixel-density displays, I think ideally this would be updated to use an SVG rather than PNG. Not sure if that exists anywhere, or if a new one could be created.

**Comment by aduth** [comment]
> Oddly enough, I did find one in [our project source](https://github.com/18F/identity-idp/blob/main/app/assets/images/us-flag.png):

This isn't quite the same graphic; there are more stars and stripes in this version, and the colors are slightly different.

But based the original comment from #2190, I was able to rebuild what I think is the "current version":

<img src="https://gist.githubusercontent.com/aduth/08f3fb95aeb63c63dddc9171062c033d/raw/159987d5bc217f5317436f745e99d3f188f0494d/flag.svg" width="160" height="110">

SVG source:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 110">
<rect width="160" height="110" fill="#fff"/>
<rect width="160" height="10" fill="#DD0E07"/>
<rect y="100" width="160" height="10" fill="#DD0E07"/>
<rect y="80" width="160" height="10" fill="#DD0E07"/>
<rect y="60" width="160" height="10" fill="#DD0E07"/>
<rect y="40" width="160" height="10" fill="#DD0E07"/>
<rect y="20" width="160" height="10" fill="#DD0E07"/>
<rect width="80" height="70" fill="#2E3E8E"/>
<rect x="10" y="10" width="10" height="10" fill="#fff"/>
<rect x="20" y="30" width="10" height="10" fill="#D4D7E7"/>
<rect x="60" y="30" width="10" height="10" fill="#D4D7E7"/>
<rect x="40" y="30" width="10" height="10" fill="#D4D7E7"/>
<rect x="50" y="10" width="10" height="10" fill="#D4D7E7"/>
<rect x="30" y="10" width="10" height="10" fill="#D4D7E7"/>
<rect x="10" y="10" width="10" height="10" fill="#fff"/>
<rect x="10" y="50" width="10" height="10" fill="#D4D7E7"/>
<rect x="50" y="50" width="10" height="10" fill="#D4D7E7"/>
<rect x="30" y="50" width="10" height="10" fill="#D4D7E7"/>
<rect x="10" y="10" width="10" height="10" fill="#D4D7E7"/>
</svg>
```

**Comment by rfultz** [comment]
Excellent—thanks, @aduth! I guess it would be 'official' if it's already included in the repo, right?

**Comment by aduth** [comment]
> Excellent—thanks, @aduth! I guess it would be 'official' if it's already included in the repo, right?

I can't say with 100% certainty it's the same as `us_flag_small.png`, but it is a manually-recreated version of the one from the screenshot in #2190:

>And all this leads me to suggest a small flag very similar to the flag we currently use:
>
>![screenshot](https://camo.githubusercontent.com/522e400b47e2258a5229d7944d4f8194f6bb39ea06b53854e5fa5b39b930b91f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3537343862633264626639333837316363643962626561612f33313061646636322d313839632d343065302d396339302d616632636163303661616135)

I'd defer to the project maintainers as to whether it's the same, or if there's an "official" copy. 🤷 

It's also worth noting that browser or OS might scale the SVG in a way where the presentation is different than the current, low-resolution graphic... for better or worse (anti-aliasing, etc).

**Comment by mejiaj** [comment]
Thanks for the feedback. We could try to dig up the old icon and create an SVG version or tweak this one slightly. It seems to be more blurry once generating other sizes.

![favicon-32x32](https://user-images.githubusercontent.com/3385219/125469392-5caab3fa-72ef-464b-be7a-aa8e0a639fdf.png)

We need to select an icon to use and identify which sizes we'll support. There are a variety of USWDS favicons in https://github.com/uswds/uswds/tree/develop/src/img/favicons, should we just provide those sizes?
