### ISSUE TITLE
Dart Sass deprecation warnings: slash as division

### ISSUE THREAD

**Issue by maya** [uswds/uswds#4204]
We're [trying to move to Dart Sass](https://github.com/CDCgov/prime-simplereport/pull/1681), but getting warnings on `watch-css` and `compile-scss` about some deprecations in Dart Sass:

![](https://user-images.githubusercontent.com/7571965/119365794-fb3cc400-bcb8-11eb-9ffb-6101f82e768a.png)

See: https://sass-lang.com/documentation/breaking-changes/slash-div

Related #4129 
/cc @scottqueen-bixal @mejiaj

**Comment by mejiaj** [comment]
On my radar, thanks for creating an issue! Tagging and adding it to our backlog.

**Comment by maya** [comment]
np! there's also automatic migration which should make that hopefully easy to do: https://sass-lang.com/documentation/breaking-changes/slash-div#automatic-migration

**Comment by afeijoo** [comment]
See related conversation and feedback in the thread, https://twitter.com/sawyerh/status/1398737919968436224.
