### ISSUE TITLE
Update footer images

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4207]
- [x] Research severity and possible solutions
- [ ] correct issue as stated in zendesk ticket https://searchusa.zendesk.com/agent/tickets/22719

**Comment by mejiaj** [comment]
The issue reported on footer social nav:

>**Accessibility Alerts: 1**
>Graphics Alerts: (1)
>1. Ensure that background images are decorative.

Converting the social icons to inline SVG and adding aria-labels gets rid of the issue.

Things that didn't work:
- Reported despite screenreader only text
- Adding a tooltip still gets flagged
- Added aria-label with title  also gets flagged

**Comment by mejiaj** [comment]
Spoke about this on standup. The solution we're going with is setting the background image separately.
