### ISSUE TITLE
Cannot find any way to update preset breakpoint widths

### ISSUE THREAD

**Issue by LeraAtwater** [uswds/uswds#4230]
I've been combing through the theme (I'm using it through the USWDS Base theme for Drupal) trying to find a way to alter the preset breakpoint widths.

I can see the widths tokens here, and their sizes are mentioned in comment (nice, thank you):
uswds/src/stylesheets/theme/_uswds-theme-utilities.scss 

I'd like to know where those sizes come from so I can alter them in my custom version of the theme.

Solutions:
1. Document or make apparent somehow where they can be changed

I'll be really embarrassed if it's right there in front of my face. I spent hours combing the theme directly, the node_modules folder for it in the Drupal contrib theme version, and paging through the documentation online.

**Comment by jAigret-Bix** [comment]
USWDS uses themes to generate these utilities. You can override them from `false` to `true` if you need them to be available in your styles. Does this answer your question? @mejiaj

**Comment by LeraAtwater** [comment]
@jAigret-Bix , I found where the theme calculates the breakpoints. It inside node_modules. I tried to adjust the numbers there to produce the correct calculation for the variables but could not get it to work. Consulted with my colleagues who are also using it and they gave up and hard-coded the breakpoint numbers.

I'm not sure how I can override the numbers. I don't want to turn them off and hardcode. I want to use the variables, but I need to be able to change their values.

**Comment by mejiaj** [comment]
@LeraAtwater you shouldn't be modifying anything in node modules. You should have a SCSS partial before importing USWDS that has your overrides in it. You can get a better idea of how that should be set up with the [Quickstart guide on the USWDS website](https://designsystem.digital.gov/documentation/fundamentals/).

In the `_uswds-theme-utilities.scss` in your project you'll have a map called `$theme-utility-breakpoints` and you'll set whatever breakpoints you need enabled to `true`.

For example:
```
$theme-utility-breakpoints: (
  // 160px:
  "card": false,
  // 240px:
  "card-lg": false,
  // 320px:
  "mobile": false,
  // 480px:
  "mobile-lg": true,
  // 640px:
  "tablet": true,
  // 800px:
  "tablet-lg": true,
  // 1024px:
  "desktop": true,
  // 1200px:
  "desktop-lg": false,
  // 1400px:
  "widescreen": true
);
```

Here we enabled two new breakpoints, `tablet-lg` and `widescreen`. Now we can access them with the `@include at-media("desktop-lg")`.

**Comment by LeraAtwater** [comment]
Thanks, @mejiaj . That was, of course, the first place I went. While you can change the breakpoints to true or false, you CANNOT alter the calculated pixel number there. I need the breakpoints, true, but I need my own numbers, not the numbers that seem to be irrevocably set here.

What can you recommend for someone who needs 1000px instead of 1024px for desktop?

**Comment by katieekline** [comment]
Thank you very much for reaching out. Please note that it is important to leave the node_modules code intact. $system-spacing is a system default setting that does not change the breakpoints of the site you are building but instead alters the system itself. Most of the time, there isn't a need to change the breakpoints for desktop because the design will accommodate the different pre-set media queries. 

We recommend working with your developers to adjust your theme.

**Comment by LeraAtwater** [comment]
@katieekline , thanks for your answer. I am the developer. I've ten years experience. I haven't been able to do it, nor have any other of my professional colleagues. We are having to resort to hack-arounds.

The answer that the breakpoints in place don't need to be changed because they accommodate peoples' needs is incorrect. It's not like I *want* to argue with USWDS code for fun. I am required to use 1000px as a breakpoint, and 1024 is not acceptable. So here I am, trying to find out how because it's obfuscated. And most responses I get are about turning breakpoints on and off and how I just need to be satisfied with that.

I'm a bit frustrated, pardon me. I still don't have an answer.

**Comment by jdfountain** [comment]
@katieekline how do we add a new breakpoint? 1400px as the largest breakpoint is not acceptable. There is a big difference between 2500px monitor and a 1400px monitor.

**Comment by jdfountain** [comment]
@LeraAtwater Did you ever find out how to add a new breakpoint?

**Comment by mejiaj** [comment]
We responded via slack [here](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1627939288008300?thread_ts=1627063760.018800&cid=C3F14AHSQ).

We don't recommend modifying breakpoints and use at your own risk.

---

@thisisdano this is safe to close.

**Comment by ctrladel** [comment]
@mejiaj can you post the response here? Interested in how this was resolved as I need a breakpoint larger then 1400 but don't have access to that slack.

**Comment by thisisdano** [comment]
Post as requested:

It's highly recommended to not mess with system properties. I don't understand that absolute 1000px requirement.But seeing as this has proved so frustrating for you and your team for so long. I hope this works for you:

Add this custom function in your code

```
/*
----------------------------------------
map-deep-set()
----------------------------------------
Update a key deeply nested

@author Hugo Giraudel
@param {Map} $map - Map to update
@param {Arglist} $keys - Keys to access to value to update
@param {*} $value - New value (last member of `$keys`)
@return {Map} - Updated map
----------------------------------------
*/
@function map-deep-set($map, $keys.../*, $value */) {
  $map-list: ($map,);
  $result: null;

  @if length($keys) == 2 {
    @return map-merge($map, (nth($keys, 1): nth($keys, -1)));
  }

  @for $i from 1 through length($keys) - 2 {
    $map-list: append($map-list, map-get(nth($map-list, -1), nth($keys, $i)));
  }

  @for $i from length($map-list) through 1 {
    $result: map-merge(nth($map-list, $i), (nth($keys, $i): if($i == length($map-list), nth($keys, -1), $result)));
  }

  @return $result;
}
```

In your `styles.scss` comment out `@import "uswds"`.
Instead do something like:

```
@import "packages/required";

//! Override system property because of client requirement - REMOVE ASAP
$system-properties: map-deep-set(
  $system-properties,
  breakpoints,
  standard,
  "desktop",
  px-to-rem(1000px)
);

@import "packages/global";
@import "packages/uswds-components";
@import "packages/uswds-utilities";

// Finally custom styles
@import "uswds-theme-custom-styles";
```

Now you can use your new value in mixins and utilities. Hopefully that gets you unblocked for now and you can work towards removing this hack in the near future.

**Comment by mahoneycm** [comment]
For those still interested, we're working on adding the ability to set custom breakpoints in #6048 !
