### ISSUE TITLE
Links: update guidance//create and populate research templates

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4245]
- [x] Share out of findings on 6/23 https://drive.google.com/file/d/1c6Q8F93VfJGTCvOWHnizB67HSJe0Yb2C/view?usp=sharing
- [x] [Update guidance](https://docs.google.com/document/d/1QG_5zqZSmye1dvf9TsASqnUS_7Fg7P6mM-V5uAYkGJY/edit#heading=h.y8adww1snny3) to reflect findings (KK)
- [x] Create github [research report](https://docs.google.com/document/d/1jn9ZTo5EVRVMf53wJQswo4O2cLrOLqd9xQkNIT-2rCU/edit#heading=h.ofl5q7yrbbz ) and [research plan](https://docs.google.com/document/d/1QX8m7SGllflqMi50tiHiCoEdmuVy8aDUYsissw5oDOk/edit#heading=h.drmoc9aosa6f) template (SS)
DoD
- [x] DW final review of  templates and structure
- [x] Compile content into templates (SS/KM/KK)
- [x] Follow-up issue for publication https://github.com/uswds/uswds/issues/4276

**Comment by sofya-UX** [comment]
**Update:** I finished the Link component research report [(p.6-13 of this document)](https://docs.google.com/document/d/1jn9ZTo5EVRVMf53wJQswo4O2cLrOLqd9xQkNIT-2rCU/edit#heading=h.ofl5q7yrbbz), specifically:
- I applied Dan's template and adjusted copy, quotes added, etc. It's all ready for @KMullan944 editorial pass.
- After Kathryn is done with edits, please flip it to Dan for a final approval and decision-making when he is back from vacation. I flagged questions for his decisions in comments. 
--If Dan's approval is needed for [the GitHub version of the research plan and component brief](https://docs.google.com/document/d/1QX8m7SGllflqMi50tiHiCoEdmuVy8aDUYsissw5oDOk/edit#heading=h.drmoc9aosa6f) to be considered final [Issue 4276](https://github.com/uswds/uswds/issues/4276), please flip it to him as well.

**Comment by jAigret-Bix** [comment]
Findings have been shared out, template and structure created and approved. Ready for acceptance.

**Comment by thisisdano** [comment]
Published:
[Link Research Findings](https://github.com/uswds/uswds/wiki/2021-07-29-External-Link-Indicator-Research-Findings) →
[Link Usability Test Plan](https://github.com/uswds/uswds/wiki/Usability-Test-Plan:-External-Link-Indicators) →
[Link Component Brief](https://github.com/uswds/uswds/wiki/Component-brief:-Links) →
