### ISSUE TITLE
Q: Is it OK that `desktop` breakpoint is being using on iPad Pro?

### ISSUE THREAD

**Issue by smustgrave** [uswds/uswds#4250]
Currently the width of ipad pro is 1024px which is the exact match for the desktop to tablet breakpoint.  But with an ipad I would assume we would want tablet instead of desktop.  Any suggestions how to get around this issue?

**Comment by smustgrave** [comment]
Something that's really confusing me is if I use 1024px in our code to trigger tablet it works at 1024px.  But the uswds components using 64em (which is 1024px) does not trigger.  My browser font size is all default settings.

**Comment by smustgrave** [comment]
wondering if anyone has a suggestion to get around this? Again the breakpoint 1024 is being treated as desktop but we would like tablet.

**Comment by mejiaj** [comment]
So `1024px` gives you the expected result, but `64em` doesn't? Do you have an example?

**Comment by smustgrave** [comment]
Our website https://www.pandemicoversight.gov/ when you go to 1024 the navigation stays in desktop but if you go 1023 it goes to tablet

If you like the 7card section the html usa-card-group is using (max-width: 1024px) and (min-width: 640px) and triggering as tablet.

**Comment by mejiaj** [comment]
> (max-width: 1024px) and (min-width: 640px) and triggering as tablet

That's expected since your tablet styles go to 1024px. Most breakpoints in USWDS from `$theme-utility-breakpoints` start at `min-width`.

You can see how the media queries work by looking at[ `_at-media.scss`](https://github.com/uswds/uswds/blob/1908d1391bc59410624ca1934cc70b7404e8f443/src/stylesheets/core/mixins/_at-media.scss).

**Comment by smustgrave** [comment]
So if I'm understanding correctly if you are to use uswds you need to use min-widths and not max-widths or things like this will be an issue?

**Comment by smustgrave** [comment]
So I'm not a big CSS guy but should 1024 be treated as tablet? That's the size of an ipad pro.  Or an override variable?

But if we are required to use min-width to work best with uswds can we get that posted somewhere for developers to know please?

**Comment by mejiaj** [comment]
If you're using max-width it'll be slightly less than the specified breakpoint.

Maybe it's time to revisit the media queries for modern tablets. Does the 1024px layout make it difficult to navigate on an iPad? Currently, you can't override that value, only use a bigger media query. We've seen similar requests to override before.

There's a small note on it in the [_For Developers_ section](https://designsystem.digital.gov/documentation/developers/). Happy to hear your thoughts on how this can be made more prominent.

**Comment by smustgrave** [comment]
It does make it slightly difficult because our menu links clash but that's a "us" problem since we max-width a lot.  The issue I believe is we should have done USWDS min-width so our breakpoints and USWDS breakpoints trigger the same.

Now for Ipad Pro 1024 I'm not sure if that should be a tablet or not? I checked some sites on my tablet and they don't seem to go tablet so I'm not sure.

**Comment by smustgrave** [comment]
https://designsystem.digital.gov/utilities/layout-grid/ this page says desktop should be 1040px though?

**Comment by smustgrave** [comment]
Based on that should it be using 65em vs 64em?

**Comment by smustgrave** [comment]
<img width="374" alt="Screen Shot 2021-10-05 at 5 05 26 PM" src="https://user-images.githubusercontent.com/10660823/136102650-26c87db8-9d24-4dae-852b-20374f8f608d.png">

This may be an issue with the cards but here's another example at 1024px

**Comment by mejiaj** [comment]
Bug on site, we need to fix. Thanks for catching that. It should be 64em - 1024px.

**Comment by mejiaj** [comment]
Can you provide a link to verify? Not seeing it on the homepage you sent.

**Comment by smustgrave** [comment]
For the delay but thank you for this!

**Comment by smustgrave** [comment]
This has creeped up again a few projects now.  At 1024 desktop is difficult. So would recommend either at 1024 go to tablet.  Or add a desktop-sm breakpoint

**Comment by smustgrave** [comment]
So put some more thought into it and wonder if a new breakpoint would really be best? I'm not sure if tablet should trigger sooner either as 1024 seems large enough just awkward because it's a grey area.  

But a new breakpoint would mean replacing current "desktop" with "desktop-sm" so it can remain the breakpoint for 1024.  Then "desktop" would get a new value like 1088 or something (just guessing).  But can understand this would require replacing a lot and could break current setups.  So not sure.  Willing to try and get a PR for whatever is decided as this keeps popping up with this grey area.

**Comment by mejiaj** [comment]
@smustgrave there are more breakpoints you can enable. Be aware that this will have performance implications with utilities. You should only enable the breakpoints you need.

```scss
$theme-utility-breakpoints: (
  'card':              false,   // 160px
  'card-lg':           false,   // 240px
  'mobile':            false,   // 320px
  'mobile-lg':         true,    // 480px
  'tablet':            true,    // 640px
  'tablet-lg':         false,   // 880px
  'desktop':           true,    // 1024px
  'desktop-lg':        false,   // 1200px
  'widescreen':        false,   // 1400px
);
```

https://designsystem.digital.gov/utilities/layout-grid/#uswds-theme-utilitiesscss

**Comment by smustgrave** [comment]
Yes those don't solve the issue though.  At 1024 uswds is still using "desktop" but that's the width of an ipad pro for example.  So css has to be updated for the tablet.

**Comment by smustgrave** [comment]
We may just start using the desktop-lg breakpoint and treat the desktop as this ipad pro area.
