### ISSUE TITLE
Pagination background sets text color, reverts background

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#4252]
$theme-pagination-background-color does not get applied correctly for the current item. When setting the background to blue-70v, the text color is changed but the background reverts to white and the other items are barely visible. 
![image](https://user-images.githubusercontent.com/1405187/124470891-33c8c680-dd6a-11eb-943d-90be3142377f.png)

**Comment by mahoneycm** [comment]
Hello,
 
When setting `$theme-pagination-background-color` you are telling the component what you plan the background color to be, in order for the component to automatically set the buttons and text to have proper color contrast. 
 
Setting the background color of its container will then change the background to the requested color, and the pagination's color will match it.
 
Ex.)
Set bg color:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/25211650/132409256-56e9da82-5cd9-4eb8-bca1-027cb12b4392.png)

Set pagination background color:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/25211650/132409278-3329345b-2061-4497-b659-e90b04735f24.png)


 

Results in
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/25211650/132409289-34ce9b67-6de4-4d73-928b-e804a4613d98.png)
