### ISSUE TITLE
Unable to add additional typeface token

### ISSUE THREAD

**Issue by JonMcL** [uswds/uswds#4255]
I am struggling to add a custom font family token. Hopefully I have the terminology correct. My ultimate goal is to be able to do the following:
```
.usa-navbar h1 {
  @include u-font('logo', 15);
}
```
This particular font, Roboto, is currently only used in this one place.

I have managed to replace 'sans' and 'serif' family tokens with custom fonts, but I suspect that might have been blind luck.

Here is a sample of what I have tried:
```
$theme-typeface-tokens: (
  roboto: (
    display-name: "Roboto",
    cap-height: 371px, // this is not necessarily correct
  ),
);

// Header site name
$theme-font-type-logo: "roboto";

$theme-font-logo-custom-stack: false;

$theme-font-logo-custom-src: (
  dir: 'roboto',
  roman: (
    100: false,
    200: false,
    300: false,
    400: false,
    500: false,
    600: false,
    700: 'roboto-v27-latin-700',
    800: false,
    900: false,
  ),
  italic: (
    100: false,
    200: false,
    300: false,
    400: false,
    500: false,
    600: false,
    700: false,
    800: false,
    900: false,
  ),
);
```

I have also tried `@include u-font("roboto", 15);`

I have also tried "logo" as the key in $theme-typeface-tokens.

The error I am getting is:
messageOriginal: "'logo' is not a valid USWDS font-family token. Valid tokens: cond, icon, lang, mono, sans, serif, ui, heading, body, code, alt"

What am I missing? Or is it impossible to add a custom token?

**Comment by mejiaj** [comment]
@JonMcL you can only set a custom font on an existing token. It's not possible to add your own custom font token. You can view all of the available font tokens here:
https://github.com/uswds/uswds/blob/50c7659acbe32b51015bfff9a55ec377dfe9baa6/src/stylesheets/core/_variables.scss#L149-L188

**Comment by JonMcL** [comment]
Understood. I think the code comments in _uswds-theme-typography.scss, which reference a custom _typeface_ token, confused me a little (or gave me false hope).

Thank you for the info!
