### ISSUE TITLE
Siteimprove: Kramdown issues

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4263]
https://drive.google.com/file/d/1PnvCp1vXSM_DXur2Hzkl_1WcE6Pz5t50/view?usp=sharing

- [ ] Role not inside the required context - A
Action: USWDS team will submit an issue to Kramdown.

- [ ] Container element is empty - A
Action: USWDS team will submit an issue to Kramdown.

**Comment by mejiaj** [comment]
PR submitted:
https://github.com/gettalong/kramdown/issues/729
