### ISSUE TITLE
Links are not clearly identifiable - A

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4264]
Site improve: https://drive.google.com/file/d/1PnvCp1vXSM_DXur2Hzkl_1WcE6Pz5t50/view?usp=sharing

- [x] USWDS team will double check the background and investigate using an underline for the footnote link

**Comment by mejiaj** [comment]
Created PR for underlining footnote links
https://github.com/uswds/uswds-site/pull/1247
