### ISSUE TITLE
Flag Layout Card responsiveness 

### ISSUE THREAD

**Issue by astiefvater** [uswds/uswds#4268]
### Describe the bug
The images and text in flag layout cards start getting messed up when they're placed in a row of two together at smaller screen sizes. Issues with responsiveness that cause both the left and right flag cards to malfunction on screens between 642px and 800px wide, where the flag image and text gets cut off and/or pushed to the side. 

### Steps to reproduce the bug
1. Create two flag cards in a row together
2. Preview screen on tablet size (768px wide)

### Expected behavior
- Flag layout cards should be responsive on smaller tablet screen sizes
- All text and images from flag cards should be easily visible and understandable
- Flag layout cards in rows should be able to respond in rows together
- Buttons should not overflow cards

### Screenshots
<img width="628" alt="uswds-flag-layout-card-768px" src="https://user-images.githubusercontent.com/4297158/125859270-1f91f4d5-d7f1-4c35-b91f-56f88ebddec2.png">

### System setup
- USWDS version: 2.12.0
- Device: HP Elitebook
- Operating system: Windows 10
- Browser and version: Chrome, Firefox, Edge (latest)

**Comment by mejiaj** [comment]
Hello! You can try adjusting the grid breakpoints in your markup or enable `tablet-lg` and [`_uswds-theme-utilities.scss`](https://github.com/uswds/uswds/blob/8f33279010e53ba823752f3bc2e61b97f8675ba6/src/stylesheets/theme/_uswds-theme-utilities.scss#L45) and use that to adjust your card grid layout.

**Comment by astiefvater** [comment]
Thanks James! We built our page using the code example directly from the https://designsystem.digital.gov/components/card/ page. Which is also where we took the above screenshot. Would you like me to open the issue for you on https://github.com/uswds/uswds-site ?

**Comment by mejiaj** [comment]
Hi @astiefvater, we won't be enabling this breakpoint by default. But you can enable it or adjust it on your own site.
