### ISSUE TITLE
Date and date range picker: Make instructions skippable

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4271]
Explore removing screen reader instructions per 508 testing results. 

When the screen reader is reading instructions,  keystrokes (arrow) do not work. 508 tester suggestion is to remove the instructions bc this is confusing and takes too long to read.

>Event start date mm/dd/yyyy
Type in text.
Toggle calendar button menu
Modal dialog
6 July 2021 Tuesday Button
To activate press Enter.
You can navigate by day using left and right arrows. Weeks by using up and down arrows. Months by using page up and page down keys. Years by using shift plus page up and shift plus page down. Home and end keys navigate to the beginning and end of a week.

NVDA Speech Viewer:

>Event start date edit Event start date mm/dd/yyyy blank
Toggle calendar menu button subMenu
You can navigate by day using left and right arrows. Weeks by using up and down arrows. Months by using page up and page down keys. Years by using shift plus page up and shift plus page down. Home and end keys navigate to the beginning and end of a week

**Comment by mejiaj** [comment]
I was able to jump past instructions and navigate as expected in two ways via NVDA:
1. Using the standard NVDA controls `F` or `SHIFT + F` keys to go to previous and next dates
2. Using `NVDA + SPACE + ARROW` to enter form mode and move from one date to the next

If we remove these instructions from being announced, it'd be useful to include them in the [guidance](https://designsystem.digital.gov/components/date-picker/).
https://github.com/uswds/uswds/blob/8f33279010e53ba823752f3bc2e61b97f8675ba6/src/js/components/date-picker.js#L1114-L1118

**Comment by mejiaj** [comment]
Instructions **are** skippable. We need to decide if we're going to include this guidance on the component's documentation.

**Comment by brunerae** [comment]
Decision to add to Accessibility section of Component page. New issue: https://github.com/uswds/uswds-site/issues/1636
