### ISSUE TITLE
Hide a header image

### ISSUE THREAD

**Issue by alyssagalik** [uswds/uswds#4273]
## Using tile layout, how to use image for tiles but hide the image on the actual webpage

Example on federalist:
https://federalist-9dc074d2-9bb0-4720-8e37-036899ae1463.app.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/landing-page-tiles/about/

Github file example: 
https://github.com/gsa-oes/office-of-evaluation-sciences/blob/landing-page-tiles/_about/1-mission.md

**Comment by mejiaj** [comment]
@alyssagalik could you add a bit more information?

I see the image in the example you've shown is a background image, which essentially is hidden. Are you trying to hide it from screenreaders?

**Comment by alyssagalik** [comment]
Hi! I got this issue resolved elsewhere using hide-image:
