### ISSUE TITLE
Link Research: publish to wiki

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4276]
Publish Link project brief and research plan to wiki

 [the GitHub version of the research plan](https://docs.google.com/document/d/1QX8m7SGllflqMi50tiHiCoEdmuVy8aDUYsissw5oDOk/edit#heading=h.drmoc9aosa6f) and [the component brief](https://docs.google.com/document/d/1jn9ZTo5EVRVMf53wJQswo4O2cLrOLqd9xQkNIT-2rCU/edit#heading=h.ofl5q7yrbbz) 

Sync w DW 8/12. DW will do a final review this week. Ready to move to formatting for wiki early next week. 

- [x] pages formatted for wiki (SS)
- [x] create a link to wiki from the component page (JM)
- [x] push content to wiki (JM)

**Comment by sofya-UX** [comment]
- Both [the GitHub version of the research plan](https://docs.google.com/document/d/1QX8m7SGllflqMi50tiHiCoEdmuVy8aDUYsissw5oDOk/edit#heading=h.drmoc9aosa6f) and [the component brief](https://docs.google.com/document/d/1jn9ZTo5EVRVMf53wJQswo4O2cLrOLqd9xQkNIT-2rCU/edit#heading=h.ofl5q7yrbbz) are ready for Dan's review. Please let him know when he is back.

**Comment by KMullan944** [comment]
@sofya-UX I have edited these two content pieces for Github & they are both ready for Dan's review @thisisdano

**Comment by thisisdano** [comment]
Done!

**Comment by thisisdano** [comment]
- https://github.com/uswds/uswds/wiki/2021-07-29-External-Link-Indicator-Research-Findings
- https://github.com/uswds/uswds/wiki/Component-brief:-Links
- https://github.com/uswds/uswds/wiki/Usability-Test-Plan:-External-Link-Indicators
