### ISSUE TITLE
Example of complex image description needed in collection--media.njk

### ISSUE THREAD

**Issue by mgifford** [uswds/uswds#4279]
### You've got a complex image included but don't describe it properly.
Add a clear and concise description of the bug.

collection--media.njk includes the following complex image:
`<img class="usa-collection__img" src="https://www.performance.gov/img/blog/wosb1.jpg" alt="Alt text">`

This is just an example, but it is important that there is a good example for complex images. I've added the Alt text in the [Pull Request](https://github.com/uswds/uswds/pull/4278) "Woman Owned Small Business Federal Contracts" but this is insufficient for the example provided.

The USWDS does need to define the preferred way of handling complex images. Several approaches have been [provided by the W3C](https://www.w3.org/WAI/tutorials/images/complex/) and [WebAim](https://webaim.org/techniques/alttext/#complex). 

Which do you want people to implement when using your design system?

**Comment by thisisdano** [comment]
I agree that there's room in USWDS for more guidance about complex descriptions. This is something we begin to address in our Data Visualization guidance, but I don't agree that it's necessary in the Collection component. 

These thumbnails — while, in some way, _technically_ contain complex imagery, they're not meant to convey the data or information included in the image. The say something closer to "the idea of graphs and charts" more than "a specific chart that conveys specific data". Said another way, no sighted user will get meaningful data from the image, so we do not need to convey meaningful data in the `alt` text.
