### ISSUE TITLE
Depending on how modal is initialized in React, there's different strange behavior

### ISSUE THREAD

**Issue by Swimburger** [uswds/uswds#4300]
### Describe the bug
We are trying to create a reusable Modal component using React, but integrating the JavaScript from USWDS has been challenging.
We're following the suggestions from [USWDS docs ](https://designsystem.digital.gov/documentation/developers/) on importing the components and using the `.on`/`.off` functions.

To demonstrate the different approaches we have taken, each with its own quirks, I have provided [a sample for you](https://github.com/Swimburger/uswds-sample/blob/master/src/App.js).
(I wanted to use JSBin or JSFiddle, but since the components aren't available without a bundler I have to create a sample with a bundler, so I'm providing a sample which you'll have to clone and run locally)

I'm not sure if these are bugs or not as there's no guidance on how to use JavaScript for specific components. I'm just guessing and experimenting until I get the components to work.
**So my question is, how should we initialize the buttons and modals?
And shouldn't modal 1 and 3 work?**

## Modal 1

For this modal implementation, I have created a ModalButton and Modal1 component.
The button component will run `modal.on(modalButtonElement)` after added to DOM and `modal.off(modalButtonElement)` before removal from DOM.
I think this button works fine I think, and I think the issue lays with the Modal1 component.

The modal component also runs `modal.on(modalElement)` after added to DOM and `modal.off(modalElement)` before removal from DOM.
After `modal.on` invocation, the `.usa-modal` element should be removed from the DOM by USWDS JS and added to the document.body wrapped in a couple of wrapper div-elements, but this doesn't happen.
When you click on the button to show the modal, there are some classes and attributes added to different places in the DOM tree, but no modal is ever shown because the modal was never initialized properly, or so I assume...

### Steps to reproduce the bug
1. Run the sample
2. Navigate to /modal1
3. Open elements tab in devtools
4. Observe nothing happens, although some attributes are added to button, modal, and body.

### Expected behavior
I would expect the modal to behave as it does in the styleguide.

## Modal 2

For this modal implementation, I have created a Modal2 component, but no dedicated ModalButton component as it is not needed.
The modal component runs `modal.on()` after added to DOM and `modal.off()` before removal from DOM.
Since I'm not passing a specific DOM element to on/off, it will use the entire DOM tree including the button and modal DOM.
This works completely as expected if you only have one modal, but if you have multiple modal, the on/off code will be run multiple times which breaks the functionality.

Instead of having `modal.on()/off()` in the modal component, I could put it on our root component, or specific page component as to avoid running it multiple times, but I'd like to avoid that. It wouldn't be as easy to use and would put more responsibility on the consumer of the component to run extra JavaScript that really should be part of the component itself.

### Steps to reproduce the bug
(not really a bug, I don't expect this one to work unless there's only 1 modal)
1. Run the sample
2. Navigate to /modal2
3. Click on "Open Modal 1" button
4. The backdrop shows, but no modal shows

### Expected behavior
Expect modal 1 or 2 to work.

## Modal 3

For this modal implementation, I have created a ModalContainer component which simply wrap all the button and modal HTML.
The container component will run `modal.on(modalContainerElement)` after added to DOM and `modal.off(modalContainerElement)` before removal from DOM.

This version is able to open the modal, but none of the buttons on the modal work, so you can't close the modal.

### Steps to reproduce the bug
1. Run the sample
2. Navigate to /modal3
3. Click on "Open Modal" button
4. The modal opens
5. Try to click buttons to close the modal or try to click the backdrop to exit, which doesn't do anything.

### Expected behavior
I would expect the modal to close when the modal buttons or backdrop is clicked.

### System setup
- **USWDS version: 2.12.1**
- **Browser and version: Chrome/Edge latest stable**

### closing

Based on my experimentation the modals only fully work when using on/off when applied to the entire DOM, as long as you only run it once per modal and not multiple times or it breaks.

There's also some extra code that I added to remove modal wrappers in document.body before React removes the components. If there are some built-in JS functions for that, that would be useful, though this part is easy so not a problem if not present.

**Comment by Swimburger** [comment]
We're experiencing the same issue with combo box and file input

**Comment by thisisdano** [comment]
@mejiaj Can you confirm this is now fixed?

**Comment by Swimburger** [comment]
I updated my sample using USWDS 3.0.1 and the modal work as expected 👍 🎉
See branch USWDS3: https://github.com/Swimburger/uswds-sample/tree/USWDS3

**Comment by mejiaj** [comment]
@Swimburger thanks for confirming and providing a branch, very helpful!!
