### ISSUE TITLE
Remove unnecessary cruft in SVGs

### ISSUE THREAD

**Issue by mgifford** [uswds/uswds#4306]
This is all bundled in this PR, but we really should have our SVGs be optimized and consistently formatted.

https://github.com/uswds/uswds/pull/4304

I don't know if `data-prefix="fas" data-icon="angle-double-left”` or `class="svg-inline--fa fa-angle-double-left fa-w-14"` are documented anywhere. Not sure why this info is doing in a SVG file. May not be useful, but might just cause some quirky behavior too.  

I don't know if it is still considered a best practice in SVG circles to use `<?xml version="1.0" encoding="UTF-8”?>` but it isn't actually necessary. 

Are there places where we actually want to use `fill-rule=“evenodd" in these simple SVGs? 

Might even be possible to re-use more of these SVGs. They are way more flexible than PNGs so maybe we could use less of them and just provide different color instructions via CSS.

**Comment by thisisdano** [comment]
I believe that many of these issues are no longer applicable with our current icon set and SVG sprite. 

@mejiaj Let's do another sweep on our SVGs as we prepare the new sprite changes in https://github.com/uswds/uswds/pull/4665 — can we normalize all our icons with SVGO or a similar compressor?

**Comment by mejiaj** [comment]
Closed by https://github.com/uswds/uswds/pull/4683.

**Comment by amyleadem** [comment]
@thisisdano Reassigning to you to see if we can resolve Issue https://github.com/uswds/uswds/issues/4752 with PR https://github.com/uswds/uswds/pull/4683
