### ISSUE TITLE
Research LOE to migrate Unit Tests to Storybook

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#4309]
Unit testing depends on `patternlab-utils.js`. Let's take an initial look at what the LOE to migrate unit testing to Storybook would look like.

- [ ] LOE of unit testing the [storybook way](https://storybook.js.org/docs/react/workflows/unit-testing)
- [x] What about re-working `patternlab-utils.js` to test based on a built storybook instance

**Comment by brunerae** [comment]
@mejiaj Can you provide more context here? Reasoning for why we would move unit tests to Storybook, etc.

**Comment by mejiaj** [comment]
Unit testing has always had a dependency on the pattern library. Previously we had to build the entire component library to be able to test. This was solved in 460e509.

We've talked about modernizing the testing library and using components instead of depending on separate templates. I'd like to get at least an idea of the LOE and pros/cons of this approach.

**Comment by mejiaj** [comment]
We were able to get initial unit tests working without the need of a custom script. We can close this for now.
