### ISSUE TITLE
bluehost for .gov domain 

### ISSUE THREAD

**Issue by rbraz1989** [uswds/uswds#4315]
## Description

Include a high-level description of the issue. What did you expect to happen? What happened instead? What would you like to see changed?

Include any benefits, challenges, or considerations. This can be short and sweet.

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information [optional]

* Relevant research and support documents
* Screen shot images
* Notes
* And so on

**Comment by jAigret-Bix** [comment]
This is out of scope for USWDS. You might need to contact bluehost and ask your question there. 

@thisisdano  This issue can be closed
