### ISSUE TITLE
 Can't resolve '../../node_modules/uswds/src/stylesheets/img/hero.png'

### ISSUE THREAD

**Issue by Gennady77** [uswds/uswds#4317]
Compilation of SCSS after including styles into index.scss my ReactJs project endup with error:
Error: Can't resolve '../../node_modules/uswds/src/stylesheets/img/hero.png' in '~\Documents\projects\timdb\src\scss'

### Steps to reproduce the bug
1. Install reactjs project
2. Install uswds by instruction
3. import styles.scss compled file into scss/index.scss file of project
4. npm start
5. see  error

**Comment by mejiaj** [comment]
Try updating your webpack config to resolve the filepaths using something like `file-loader`.

This isn't a bug, safe to close.
