### ISSUE TITLE
Disabled Select / Dropdown is not grayed out

### ISSUE THREAD

**Issue by cameronbuck** [uswds/uswds#4322]
### Describe the bug
Disabled dropdowns are not grayed out like disabled inputs.

### Steps to reproduce the bug
1. Setting the `disabled` attribute on a `select` element.

### Expected behavior
1. A `disabled` `select` element should be grayed and have the same styling as `disabled` `input`s.

### Screenshots
![disabled-dropdown](https://user-images.githubusercontent.com/3236810/133507483-2c7e3fe9-3466-44a2-ac12-f4eb6d2caa71.jpg)

### System setup
- **USWDS version:** uswds@2.12.0
- **Device:** Macbook
- **Operating system:** Catalina (10.15.7)
- **Browser and version:** Chrome 93.0.4577.63

### Additional context
I was doing some snooping on the HTML / CSS, and it seems like the `background-color` to gray it out is there but that it's being overriden.

**Comment by mejiaj** [comment]
These are set via the browser styles. I don't see a background color being set on Edge with the browser styles anyways.

Should we explicitly set disabled styles for text inputs, dropdowns, and form elements in general @thisisdano?

**Comment by amyleadem** [comment]
@thisisdano @mejiaj 
I have included a screenshot that showcases disabled visual cues in Chrome, Firefox, Safari, and Edge for OS. This screenshot displays the following:
- Standard .usa-select element
- Disabled .usa-select element
- Disabled select element without .usa-select class
- Standard .usa-input element
- Disabled .usa-input element
- Disabled input element without .usa-input class

![Image](https://user-images.githubusercontent.com/93996430/193339979-915af696-7857-4e10-84a3-60004b40b606.png)

I also have a link to a [live demo](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/al-test-disabled-select/iframe.html?args=&id=components-form-inputs-select--select&viewMode=story) in PR https://github.com/uswds/uswds/pull/4969 in case it is hard to glean the style differences from the screenshot. 

Things to note: 
- Each browser has its own set of default styles for disabled form elements.
- USWDS overrides some default disabled styles in a way that makes it less clear that the element is disabled. 

I lean towards wanting to take a look at developing `disabled` styles for USWDS form elements that provide clearer visual cues that the element is disabled. However, we would need to be careful of poor contrast ratio and look into accessibility implications.
