### ISSUE TITLE
Draft: `getting started` copy for Developer user group

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4324]
See Google Doc for full copy: https://docs.google.com/document/d/1mrPoM8fERauDOcdSQkePyaSkgpD7BdnjRwpu98tqX-8/edit

- [x] research pulled for initial users and intro section (SS) 

DoD
- [x] content audit (KK)
- [x] draft outline (KK)
- [x] full copy written (MC)
- [x] share full copy with Dan and James for review (MC)

**Comment by brunerae** [comment]
Ready for Dan's review at https://docs.google.com/document/d/1IhFDFirGwrBVgIDZ7FwJzPhCQwfuJJVu/edit?usp=sharing&ouid=104922772952783735615&rtpof=true&sd=true
