### ISSUE TITLE
External links: regex search and spreadsheet

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4328]
Use regex search to find and update site external links to reflect updated link guidance
- [x] create a spread sheet of changes for double checking policy adherence  w AFF

**Comment by jAigret-Bix** [comment]
@mejiaj @katieekline Are we good to close this ticket? it looks like this is mainly the export of the external link spreadsheet. cc @brunerae

**Comment by brunerae** [comment]
@thisisdano This can be closed
