### ISSUE TITLE
Draft: Designer GS Outline

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4332]
See Google Doc for copy:https://docs.google.com/document/d/1jt51Y1QVWyjewVhnEtUAnwhYAESNof1GVanvAxTBbWk/edit
- [x] research pulled for initial users and intro section (SS) 

DoD
- [x] content audit (KK)
- [x] draft outline (KK)

**Comment by brunerae** [comment]
Assigning to myself in lieu of Mikki Stacey and Lauren Vocke, who are actually working on this task. I am also going move this out of the Sprint.

**Comment by sofya-UX** [comment]
@thisisdano Past research assessment is recommended for these two studies with the goal to factor insights from these research activities into the current work the team is doing on updating the getting started guides:
- DHS interviews (Oct-Nov 2020) - [notes](https://drive.google.com/drive/u/0/folders/1c8Pqk8B-hFpRmFuo4ElQZ8RraVkzp2Tw)
- USWDS cross-functional users' hybrid study (survey and interviews) (Dec 2019) - [Findings Report](https://docs.google.com/presentation/d/1Ca26nEAi8tRSe9xWxJOpIIfssEgPIvGt/edit#slide=id.p3)
- USWDS for Designers [walkthrough] - [Summary](https://docs.google.com/document/d/18Ra7QqphqTNAXU7h469_u1Z6Arcd7PX-/edit#heading=h.1fob9te)
