### ISSUE TITLE
Mobile header console error

### ISSUE THREAD

**Issue by ajanickiv** [uswds/uswds#4361]
### Describe the bug
When clicking the Menu or close menu button when the header is in the mobile view, an error is shown in the console.

### Steps to reproduce the bug
1. Load an application that is using the USWDS Header component
2. Make browser width small enough to change header to mobile view
3. Click Menu button
4. See error in console
5. Click Close menu button
6. See error in console
Uncaught TypeError: Cannot read properties of null (reading 'update')
    at HTMLButtonElement.t (node_modules\uswds\dist\js\uswds.min.js:1)
    at HTMLBodyElement.<anonymous> (node_modules\uswds\dist\js\uswds.min.js:1)
    at HTMLBodyElement.<anonymous> (node_modules\uswds\dist\js\uswds.min.js:1)
    at Array.some (<anonymous>)
    at HTMLBodyElement.<anonymous> (node_modules\uswds\dist\js\uswds.min.js:1)
    at ZoneDelegate.invokeTask (zone.js:406)
    at Zone.runTask (zone.js:178)
    at ZoneTask.invokeTask [as invoke] (zone.js:487)
    at invokeTask (zone.js:1600)
    at HTMLBodyElement.globalZoneAwareCallback (zone.js:1637)

### Expected behavior
No console errors

### Screenshots
![image](https://user-images.githubusercontent.com/16595489/137777303-92337adc-68ca-47cf-afa9-1c6512cc2a45.png)
![image](https://user-images.githubusercontent.com/16595489/137777352-bf3cbb9d-46db-4c23-b78b-897434de24e6.png)

### System setup
- **USWDS version: 2.12.1**
- **Device: Laptop**
- **Operating system: Windows 10**
- **Browser and version: Edge 94.0.992.50**

### Additional context
Web Application is Angular based

**Comment by mejiaj** [comment]
Might be related https://github.com/uswds/uswds/pull/4319

**Comment by brunerae** [comment]
Believe this was fixed in #4319; need confirmation

**Comment by mejiaj** [comment]
@brunerae no longer seeing this in Firefox v97

![image](https://user-images.githubusercontent.com/3385219/150824216-0956c205-f70d-4194-9fa2-d2952d1f1971.png)

**Comment by ajanickiv** [comment]
Just an FYI - Our header was using a font awesome icon
`<button class="usa-nav__close">
<i class="fas fa-times" aria-label="close">
</button>`
I switched it to use the close.svg and the error went away
`<button class="usa-nav__close">
<img src="assets/@uswds/uswds/dist/img/usa-icons/close.svg" role="img" alt="Close" />
</button>`
