### ISSUE TITLE
Angular build output dist folder contains all fonts and images in output

### ISSUE THREAD

**Issue by Petrovski** [uswds/uswds#4362]
### Describe the bug
When using this package in an Angular project and running the `ng build` command, the output contains all of the fonts and images being imported from what I assume is the minified CSS file. If there is a way around this that is already known, I apologize for the unneeded issue, but I don't know of one other than me modifying my webpack configuration inside my Angular project. Some images get loaded into `assets/img`, some don't.

### Steps to reproduce the bug
1. Go to you bash terminal and cd in the Angular project root, make sure uswds package is installed in the package.json
2. Run `ng build` in your terminal
3. Go to the output folder (dist/<project-name> or dist, or whatever you set it to)
4. See huge list of fonts and img's/svg files.

### Expected behavior
These should be bundled into a fonts/images folder under the assets folder, which the user may accomplish by setting up there `angular.json` or webpack config files, but there should be instructions on how to set it up to make sure that happens. 

### Screenshots
<img width="491" alt="Screen Shot 2021-10-19 at 12 52 30 PM" src="https://user-images.githubusercontent.com/40745333/137956384-5d61d754-a7fa-4cbb-9433-7ee6bffbf23b.png">

### System setup
- **USWDS version: ^2.12.1,
- **Device: MacBook Pro
- **Operating system: macOS
- **Browser and version: Chrome Version 94.0.4606.81

### Additional context
Add any other context about the problem.

**Comment by gscottqueen** [comment]
you probably want to add something like the following to your angular config

```json
            "assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "*",
                "input": "node_modules/uswds/dist/fonts",
                "output": "assets/fonts/"
              },
              {
                "glob": "*",
                "input": "node_modules/uswds/dist/img",
                "output": "assets/img/"
              }
            ],
            "styles": [
              "node_modules/uswds/dist/css/uswds.min.css",
              "src/styles.css"
            ],
            "scripts": ["node_modules/uswds/dist/js/uswds.min.js"]
```

We don't provide official support for application config, as they are often custom to the integration. But there are lot's of examples out there in the community such as https://github.com/softrams/uswds-angular-starter/blob/master/angular.json#L22-L40 where you can get some good considerations.
