### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by fpigeonjr** [uswds/uswds#4371]
### Describe the bug
When running `npm run build` in Gatsby/React project I am getting a warning that `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`.

```log

5:33:57 PM: warning ./node_modules/uswds/dist/js/uswds.min.js
5:33:57 PM: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

```
### Steps to reproduce the bug

1. Run `npm run build` in a Gatsby project

### Expected behavior
Not to give warning on build.

### Screenshots

<img width="1141" alt="Screen Shot 2021-10-26 at 5 43 16 PM" src="https://user-images.githubusercontent.com/4629398/138971613-e22b22af-f3be-4dee-bb23-c992fa29d8d1.png">

### System setup
- **USWDS version:**"uswds": "^2.12.1"
- **Device:** Mac
- **Operating system:**macOS Big Sur
- **Browser and version:** na

### Additional context

Setup is based on the [Federalist USWDS Gatsby repo](https://github.com/18F/federalist-uswds-gatsby).

**Comment by jkjustjoshing** [comment]
I wish I had written down what I was trying to do that caused me to stumble across this issue, because I don't remember why I 👍ed it. Sorry! Hopefully @fpigeonjr has more helpful info.

**Comment by fpigeonjr** [comment]
@mejiaj: I opened this issue when I was working on a closed source project at my old job. I have no way of verifying if this is still an  issue so I would recommend to just close it.

**Comment by mejiaj** [comment]
@fpigeonjr congrats on the new job and thanks for responding! Closing.
