### ISSUE TITLE
CSS social link classes point to nothing

### ISSUE THREAD

**Issue by bmhosenf** [uswds/uswds#4396]
## Description

The following css classes seem to point to nothing and there are no icons in the build for them as well:

- usa-social-link--linkedin
- usa-social-link--email

## Steps to reproduce the issue

1. Here is an example: ![image](https://user-images.githubusercontent.com/89036668/141159710-5f639c1e-99d2-46f3-904f-dcf5c692cd9f.png)
2. No icon appears in the element.

**Comment by mejiaj** [comment]
You're right, we currently don't have linkedin or an email social icon. It's not currently on our roadmap, but we welcome any contributions.

Related to #4176.

**Comment by mejiaj** [comment]
The `usa-social-link--{{ icon }}` classes no longer exist since https://github.com/uswds/uswds/commit/e00227b32bd56d295c22b8d0eb3e1da41c0bb12b.
