### ISSUE TITLE
The "18F’s Front End Guide" Link and Other Links on the Front End Developers Page Redirect to a Different Pages

### ISSUE THREAD

**Issue by jfc3-dol** [uswds/uswds#4403]
### Describe the bug
The link "18F’s Front End Guide" which there are at last two occurrences on the Front End Developers page ( https://designsystem.digital.gov/documentation/developers/ ) is redirecting to a different page ( https://engineering.18f.gov/frontend/ ).  I assume you want to point it to the CSS link ( https://engineering.18f.gov/css/ ) under the "Related topics" heading.

A similar issue applies for the "18F Front End Guide" link ( https://engineering.18f.gov/frontend/ ) related to formatting being redirected too.

The link "Twig" gets a page not found error when clicked.

### Steps to reproduce the bug
Link redirects to a different page.

### Expected behavior
Would expect the link to be corrected to point to the new page location.

### Screenshots
N/A

### System setup
It's your docuemtntation.

### Additional context
N/A

**Comment by mejiaj** [comment]
Twig link is fixed in #4366.

**Comment by thisisdano** [comment]
These are all fixed
