### ISSUE TITLE
Copy change suggestion for the Banner component for improved accessibility using screen readers

### ISSUE THREAD

**Issue by AmandaD-USDS** [uswds/uswds#4419]
## Problem
The USDS team that is working to improve the [Child Tax Credit site](https://www.whitehouse.gov/child-tax-credit/) has been running some usability testing with people with disabilities. Some of these participants included those using a screen reader. We discovered that, when users are listening to a screen reader (these are often run at very fast speed), the copy on the USWDS banner component becomes confusing for them.

Because of this, we would like to suggest a slight change to the banner copy.

The reason for this suggested change is that, when the screen reader reads the copy, it comes out sounding like "Unofficial website of the United States government". This led one participant to comment,  "if this is the unofficial website, I wonder where the official websites are?". So we think this could be a positive change.

## Suggested Solution
We suggest a small change to the copy on the banner component to make it clearer for accessibility using a screen reader.

**Current copy:** <br>
An official website of the United States government.

**Suggested copy:**<br>
This is a United States government website.

## Alternatives
Any copy change that would not be misinterpreted by a screen reader to make the website sound "unofficial".

## Additional Context
This is the component we are referring to: https://designsystem.digital.gov/components/banner/

**Comment by brunerae** [comment]
Decision at this time is to update the aria-label to remove "an" from the read-out so that it reads "official" instead of "an official".
