### ISSUE TITLE
Sanitizer module not exported correctly when using Webpack

### ISSUE THREAD

**Issue by hursey013** [uswds/uswds#4455]
### Describe the bug
The recently added [Sanitizer](https://github.com/uswds/uswds/blob/develop/src/js/utils/sanitizer.js) module is not exported correctly when using Webpack, causing the components that rely on it to not load properly.

### Steps to reproduce the bug
1. Add uswds to a Webpack based build
2. Navigate to the combobox component
3. Observe in the browser console that `g.escapeHTML` is undefined

### Expected behavior
All JavaScript should compile properly

### Screenshots
Add screenshots to help provide context, if applicable.

### System setup
- **USWDS version:** 2.1.3, Webpack: 5.65.0
- **Device:**
- **Operating system:**
- **Browser and version:** Chrome Version 97.0.4692.71 (Official Build) (x86_64)

### Additional context
Exporting the module using CommonJS (`module.exports`) resolves the issue.

**Comment by scottqueen-bixal** [comment]
digging into debugging this - started an example repo [here](https://github.com/scottqueen-bixal/uswds-combo-box-example), unfortunately, I don't see the console error.

the sanitizer script does export the factory on [line 21](https://github.com/uswds/uswds/blob/develop/src/js/utils/sanitizer.js#L21)

Are you recommending that we also need to export the entire script?  Any chance of putting together a fix in a PR we can take a look at further?
