### ISSUE TITLE
Q: How do I add the `Sort` button to a sortable table?

### ISSUE THREAD

**Issue by sganti024** [uswds/uswds#4472]
Hi, My question is do I need to add an button manually in table header column to sort the records? Will it not add by default by adding "data-sortable" attribute to table header element. I noticed this difference when I tried to take reference from Component code. I copied this piece of code from - https://designsystem.digital.gov/components/table/#sortable-table-rows

```
<button tabindex="0" class="usa-table__header__button" title="Click to sort by Name in ascending order.">
  <svg class="usa-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
    <g class="descending" fill="transparent">
      <path d="M17 17L15.59 15.59L12.9999 18.17V2H10.9999V18.17L8.41 15.58L7 17L11.9999 22L17 17Z"></path>
    </g>
    <g class="ascending" fill="transparent">
      <path transform="rotate(180, 12, 12)" d="M17 17L15.59 15.59L12.9999 18.17V2H10.9999V18.17L8.41 15.58L7 17L11.9999 22L17 17Z"></path>
    </g>
    <g class="unsorted" fill="transparent">
      <polygon points="15.17 15 13 17.17 13 6.83 15.17 9 16.58 7.59 12 3 7.41 7.59 8.83 9 11 6.83 11 17.17 8.83 15 7.42 16.41 12 21 16.59 16.41 15.17 15"></polygon>
    </g>
  </svg>
</button>
```

Please advise. Also please suggest on how to bind to data from TS file (instead of hardcoding data in UI). Thank you.

**Comment by brunerae** [comment]
Hi @sganti024 ! Would you be able to provide screenshots or code snippet depicting this issue? Thanks!

**Comment by sganti024** [comment]
Hi, My question is do I need to add an button manually in table header column to sort the records? Will it not add by default by adding "data-sortable" attribute to <th column header>. I noticed this difference when I tried to take reference from Component code. I copied this piece of code from - https://designsystem.digital.gov/components/table/#sortable-table-rows

<button tabindex="0" class="usa-table__header__button" title="Click to sort by Name in ascending order.">
  <svg class="usa-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
    <g class="descending" fill="transparent">
      <path d="M17 17L15.59 15.59L12.9999 18.17V2H10.9999V18.17L8.41 15.58L7 17L11.9999 22L17 17Z"></path>
    </g>
    <g class="ascending" fill="transparent">
      <path transform="rotate(180, 12, 12)" d="M17 17L15.59 15.59L12.9999 18.17V2H10.9999V18.17L8.41 15.58L7 17L11.9999 22L17 17Z"></path>
    </g>
    <g class="unsorted" fill="transparent">
      <polygon points="15.17 15 13 17.17 13 6.83 15.17 9 16.58 7.59 12 3 7.41 7.59 8.83 9 11 6.83 11 17.17 8.83 15 7.42 16.41 12 21 16.59 16.41 15.17 15"></polygon>
    </g>
  </svg>
  </button>


Please advise. Also please suggest on how to bind to data from TS file (instead of hardcoding data in UI). Thank you.
