### ISSUE TITLE
external link and expand more icons (mask-image) not showing correctly

### ISSUE THREAD

**Issue by kengdoj** [uswds/uswds#4478]
### Describe the bug
Mask-images are not displaying correctly in Chrome, Edge. Firefox is ok.

### Steps to reproduce the bug
1. Go to [federalist build sample](https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/preview/atbcb/usab-uswds/kengdoj-inchmarks/about/meetings.html).
2. At top, 'Here's how you know' link should be followed by expand more icon. 
3. Scroll down to 'Board Meeting Archives'
4. See error: each date should be followed by an external link icon. 

### Expected behavior
Icons should display.

### Screenshots

1. Expand icon not displayed
![expand](https://user-images.githubusercontent.com/21043936/151014473-f914eb64-4cf1-473c-abbc-5cdde412dcd9.png)
2. External link icons not displayed
![external link](https://user-images.githubusercontent.com/21043936/151014514-bd444444-c919-4d58-8061-8901c1a85fe4.png)

### System setup
- **USWDS version: 2.13.1**
- **Device: Desktop**
- **Operating system: Windows**
- **Browser and version: Edge Version 97.0.1072.69**

### Additional context
Since Firefox is ok, this [browser compatibility chart](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image) suggests -webikit- is needed.

On our [live site](https://www.access-board.gov/about/meetings.html), the expand icon is not displaying but the external icons are ok. We have not yet updated to the latest USWDS on the live site.

**Comment by mejiaj** [comment]
@kengdoj autoprefixer is a compilation requirement for USWDS. It's built-in if you've used USWDS-Gulp in the past or the newer [USWDS-Compile](https://github.com/uswds/uswds-compile).

**Comment by bruce-usab** [comment]
@mejiaj @apburnes we would ask for more hand-holding here.  I believe we were using Gulp in the past, so I am not clear when/where we dropped that.  But it sounds like USWDS-Compile would be the better fix going forward.

**Comment by mejiaj** [comment]
@bruce-usab not a problem at all. 

[USWDS-Compile](https://www.npmjs.com/package/@uswds/compile) is a new package based on the original work done in USWDS-Gulp. So if you've used USWDS-Gulp in the past or are using it now, you can use uswds-compile as a replacement. You can read the setup instructions [here](https://github.com/uswds/uswds-compile#installation).

--- 

If you're using your own custom gulpfile you need a `.browserslistrc` file that defines what browsers you want prefixes for:
```
// .browserslistrc
# Supported browsers
> 2%
last 2 versions
IE 11
not dead
````
https://github.com/uswds/uswds-compile/blob/main/.browserslistrc

Then you need to make you have the following packages installed: gulp-postcss, postcss, and autoprefixer. And then you can update your SCSS task like the one in [`uswds-compile`](https://github.com/uswds/uswds-gulp/blob/0aa819bc382538ff0186b7845c8844068cd4656f/gulpfile.js#L82-L112). You can see in the example we pass autoprefixer with postcss after the SCSS is processed.

**Comment by kengdoj** [comment]
Thanks, @mejiaj. I think we are good.
