### ISSUE TITLE
Skip Side Nav and Skip Main Content links remove elements from page - Chrome Only

### ISSUE THREAD

**Issue by JackRyan1989** [uswds/uswds#4479]
**Issue:** 
Clicking the Skip Side Nav or Skip to Main Content links removes the side nav or main content from the page. 

I'm encountering this issue using Google Chrome 97 on MacOS 11.

**To replicate:** 
1. Open this Federalist Preview Link: [https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/preview/usdoj-crt/beta-ada/chrome-bug-demo-uswds](https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/preview/usdoj-crt/beta-ada/chrome-bug-demo-uswds)
2. Navigate to a page with a side nav - try /topics/intro-to-ada/
3. Upon arriving at the page, press the TAB key to open the 'Skip to Page Navigation' link
4. Press ENTER key or click on the link
5. The Side Nav should disappear from the page
6. Repeat steps 3-4 but for the 'Skip to Main Content' link
7. You should see the main content has been removed from the page.

**Hypothesis**
Setting the style inline on the containing div for the side nav and main content seems to be the issue. 
The outline parameter is set dynamically in line 20 of /uswds/src/js/components/skipnav.js
I'm pretty sure that setting any inline style will remove the content from the page, but I only know this through playing with Chrome Dev Tools. 
I don't get _why_ this is the case.

This does not happen on Safari, Firefox, or Edge. 

I have a work-around in place at the moment, but it doesn't work with screen reader keyboard commands.
I wonder if setting the border to 0 is a best practice in this case since the code is resetting the focus in DOM? It's not exactly removing focus, but it is removing any visual indication of focus.

**Comment by JackRyan1989** [comment]
Turns out this issue was due to the UBlock Origin extension in Chrome. Disabling the extension removed the issue.
 
<img width="1297" alt="Screen Shot 2022-01-28 at 11 27 33 AM" src="https://user-images.githubusercontent.com/14644234/151586288-1b854fac-2042-476b-a814-c53df56a8e37.png">

**Comment by mejiaj** [comment]
Great, thanks for following up @JackRyan1989!
