### ISSUE TITLE
Alternate buttons styles not rendering

### ISSUE THREAD

**Issue by plummonke** [uswds/uswds#4514]
### Describe the bug
When using `usa-button` elements, some of the alternate styles fail to render. Namely, `usa-button--secondary`, `usa-button--base`, and `usa-outline` fail to render. The styles are present in the stylesheet but `usa-button` always wins out despite having the same specificity.

### Steps to reproduce the bug
1. Create a button with both `usa-button` and `usa-button--secondary` (or one of the other classes)

### Expected behavior
The styling of `usa-button` should be swapped with the styling of the alternate class.

### Screenshots
Screenshot (1 of 2) showing alternate style being superceeded by `usa-button` on all three buttons. (Button 3 shows collision of standard and outline styling.) (Chrome browser depicted.)
![uswds_buttons](https://user-images.githubusercontent.com/35630362/153496497-1875be9c-593f-4aa2-8d98-70337762829c.PNG)

Screenshot (2 of 2) showing alternate style applying after the color styling for `usa-button` has been disabled in browser. (Chrome browser depicted.)
![uswds_buttons_after](https://user-images.githubusercontent.com/35630362/153496514-94d456d0-ae17-430e-a08f-85c3050dccf0.PNG)

### System setup
- **USWDS version:** 2.10.1
- **Device:** HP 840 G3 laptop
- **Operating system:** Win10
- **Browser and version:** Chrome 98.0.4758.82 and Firefox 97.0

### Additional context
n/a

**Comment by aduth** [comment]
Is it possible that your CSS build step is reordering styles, such as through [`csso`'s `restructure` option](https://github.com/css/csso#syntaxcompressast-options)? Reason for asking is that [the outline styles](https://github.com/uswds/uswds/blob/49454674c5bae56e85cfd08a955f06df79e1b179/src/stylesheets/elements/_buttons.scss#L90) occur after [the base styles](https://github.com/uswds/uswds/blob/49454674c5bae56e85cfd08a955f06df79e1b179/src/stylesheets/elements/_buttons.scss#L8), so I would expect them to take precedent at equal specificity.

**Comment by plummonke** [comment]
Closing due to lack of action by our team.
