### ISSUE TITLE
[Footer] At exactly 480px viewport width, collapsable components display incorrectly 

### ISSUE THREAD

**Issue by jkjustjoshing** [uswds/uswds#4524]
### Describe the bug
The CSS to switch between the collapsed and expanded view of the "big footer" uses the media query `(min-width: 30em)` but the Javascript uses the media query `(max-width: 30em)`. This causes an edge case at exactly 30em (480px) viewport width.

### Steps to reproduce the bug
1. Go to https://designsystem.digital.gov/components/footer/
2. Resize your viewport to 479px or smaller. Note that the "Big Footer" link sections are collapsable sections
3. Resize your viewport to 481px or larger. Note that the "Big Footer" link sections are all visible
4. Resize your viewport to exactly 480px. Note that the "Big Footer" link sections are collapsed, but don't display correctly.
 
### Expected behavior
At 480px, commit to either fully expanded or fully collapsed, not halfway in between

### Screenshots
&nbsp; | &nbsp;
----------- | ----------
&gt; 480px ✅ | <img width="212" alt="image" src="https://user-images.githubusercontent.com/813192/154362560-bed72c35-ef67-4a17-803e-726f19c1d01a.png">
&lt; 480px ✅ | <img width="209" alt="image" src="https://user-images.githubusercontent.com/813192/154362626-537f4c15-0294-4aa2-bc1a-96f6b2a346c6.png">
= 480px ❌ | <img width="210" alt="image" src="https://user-images.githubusercontent.com/813192/154362677-a4de6f6f-2b38-42d9-88a7-eb12bf248401.png">

### System setup
- **USWDS version:** 2.13.1
- **Operating system:** Windows 10
- **Browser and version:** Chromium 98.0.4758.87

**Comment by jkjustjoshing** [comment]
@thisisdano the solution in #4531 fixes the issue 95%, but I think on high DPI screens the viewport width can exist between values (for example, [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1120090)), so if you want to stick with `max-width` you might want to go with the following instead
```js
`(max-width: ${HIDE_MAX_WIDTH - 0.1}px)`
```

**Comment by thisisdano** [comment]
OK, good point — I'll revisit. Thanks!
