### ISSUE TITLE
How can I get 2 Extended header with megamenu components to work on the same page?

### ISSUE THREAD

**Issue by davidrdesouza** [uswds/uswds#4541]
I am using server side includes to bring in two Extended header with megamenu components. 

One if for a global nav which will appear on every page and the other is for local navigation, to be used for sections of the site.

No problem bringing them both in. They both work until they need to go mobile. At that point, the menu-btn for each component opens both megamenus. I can't find the spot in the javascript to change this.

Any suggestions? 

Hopefully I'm asking this correctly

**Comment by amyleadem** [comment]
Hello @davidrdesouza, 
I know this is a late response, so I appreciate your patience and hope there is a chance this still might be helpful. 
The core team had a chance to discuss this topic and our primary guidance is that a page should have only one menu button that controls all mobile site navigation. 

The USWDS header component was built with the intention of having only one on a page. If you would like to have both a header component and a secondary navigation component on a single page, we recommend that you build a custom solution that allows both navigation elements to be integrated into a single navigation panel on mobile and is triggered by a single menu button.

I hope this helps. Please reach out if you have any questions or comments.

**Comment by davidrdesouza** [comment]
So, basically, you waited six months to say “figure it out yourself”
