### ISSUE TITLE
tablet-lg 800px or 880px

### ISSUE THREAD

**Issue by lebeza** [uswds/uswds#4549]
I am a little confused about what the exact width is for the tablet-lg breakpoint.
Your documentation says 800px but functions at 880px
Could you clarify, please? 

![800](https://user-images.githubusercontent.com/49002558/156229784-792c23be-f2ad-41cd-8e65-03607e34fb49.png)
![880](https://user-images.githubusercontent.com/49002558/156229812-a2817a17-7bef-4efb-9f68-3fc629c44659.png)

**Comment by mejiaj** [comment]
Hey there @lebeza! Thanks for pointing that out. We've since fixed it in this [PR](https://github.com/uswds/uswds-site/pull/1455).

Not sure how often the search results are indexed, but hopefully that gets corrected on all the results. I only see one currently.

**Comment by jkjustjoshing** [comment]
@mejiaj this page still has incorrect values https://designsystem.digital.gov/utilities/layout-grid/

**Comment by lebeza** [comment]
More questions.....
1.  was the issue just on the documentation?
2.  Does the USWDS node pacakge has the wrong value too? 
3. If so do i have to update the uswds package?

**Comment by mejiaj** [comment]
@jkjustjoshing I must be missing it; could you provide a screenshot or an example of where?

I know previously it was in utilities example
![image](https://user-images.githubusercontent.com/3385219/157887724-f313ca10-d340-48cf-b598-3762723a6a73.png)

**Comment by mejiaj** [comment]
Sorry, @jkjustjoshing and @lebeza! You're absolutely right. I've submitted a PR correcting the values. 

The code is right, it's just the documentation.

**Comment by lebeza** [comment]
@mejiaj sorry for bugging you but is the correct value is 880px? because 15 days ago you changed it to 800 and today back to 880. which one is correct?

**Comment by mejiaj** [comment]
@lebeza the breakpoint works at 880px, sorry for the confusion.
