### ISSUE TITLE
Beta: Components that use grid classes need to have a grid dependency in their package

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#4558]
A component like `Banner` uses grid classes in its layout, so its package needs a `@forward "usa-layout-grid";` in its dependencies. Let's make sure our package dependencies include all the dependencies — including grid — that they need to display properly.

**Comment by brunerae** [comment]
Completed in https://github.com/uswds/uswds/releases/tag/v3.0.0-beta.4
