### ISSUE TITLE
Prototype new GitHub issue templates

### ISSUE THREAD

**Issue by elisaachen** [uswds/uswds#4691]
**Is your feature request related to a problem? Please describe.**
Right now it can be intimidating and overwhelming for USWDS users to submit feature requests or bugs especially if they aren't familiar with GitHub. Where do they type their input? Is there a certain way they need to write their issue? In short, the template isn't very user friendly and inclusive for a wider audience who have varying levels of GitHub expertise. 

**Describe the solution you'd like**
GitHub has a released a new issue [template](https://github.com/carbon-design-system/carbon-web-components/issues/new?assignees=jeffchew%2Cljcarot%2Coliviaflory%2Cannawen1&labels=bug&template=bug_report.yaml&title=%5BYOUR+TITLE%5D%3A+Brief+description) in public Beta that makes it much easier and simpler to how best to submit an issue/feature request. Can we use [this](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) documentation to create a prototype for USWDS? By making this high value/low effort change, we can make it easier for USWDS to contribute.

**Describe alternatives you've considered**
No other alternatives have been considered outside of the status quo. 

**Additional context**
[Here](https://github.com/carbon-design-system/carbon-web-components/issues/new?assignees=jeffchew%2Cljcarot%2Coliviaflory%2Cannawen1&labels=Feature+request&template=feature_request.yaml&title=%5BYOUR+TITLE%5D%3A+Brief+description) is the beta feature request template
[Here](https://github.com/uswds/uswds/issues/new?assignees=&labels=type%3A+feature+request&template=feature_request.md&title=) is our feature request template

**Comment by elisaachen** [comment]
In our prototype, maybe we might also want to pre-populate labels (e.g. bug) for the issue template and even include a section where users can acknowledge the Code of Conduct and checking for duplicate issues like how they do it in [Carbon Design System](https://github.com/carbon-design-system/carbon/issues/new?assignees=&labels=type%3A+bug+%F0%9F%90%9B&template=BUG_REPORT.yaml&title=%5BBug%5D%3A+)

**Comment by amyleadem** [comment]
@elisaachen @mejiaj @mahoneycm 
I have been able to create a [prototype in a demo repo](https://github.com/amyleadem/issue-template/issues/new/choose).

I was able to add default assignees and labels to the template. For this demo, I could only add what was available to my repo.

**Comment by amyleadem** [comment]
ave

**Comment by amyleadem** [comment]
Apologies for accidentally closing. Clumsy clicking!

**Comment by amyleadem** [comment]
@elisaachen I went ahead and added a bug report demo to the [issue types ](https://github.com/amyleadem/issue-template/issues/new/choose) in the demo repo. Please let me know next steps, particularly if either (or both) of these are ready to build inside our USWDS repos. Thanks!

**Comment by elisaachen** [comment]
Thanks @amyleadem ! For the labels, should the label be Feature Request instead of Enhancement and then @brunerae would confirm during triage? Also should we add the label of "needs confirmation"? How do we make sure these get triaged and not lost?

**Comment by amyleadem** [comment]
Hello @elisaachen and @brunerae,
I have copied over the relevant labels from USWDS into the demo repo and have added them to the [issue templates](https://github.com/amyleadem/issue-template/issues/new/choose) for review. Now, the bug report has the labels `Type: Bug`, `Status: Triage`, `Needs: Confirmation`, and the feature request form has `Type: Feature Request`, `Status: Triage`. Please let me know if you want to see anything else!

**Comment by mejiaj** [comment]
These look great!

**Comment by elisaachen** [comment]
So `Needs: Confirmation` is only a bug related thing? Or do we need to confirm if the FR is an FR vs. Enhancement?

**Comment by amyleadem** [comment]
@elisaachen @mejiaj @brunerae 
Oh another question. What should we do for default title templates? 
I added these as the defaults for now:
`USWDS - Feature: [YOUR TITLE]`
`USWDS - Bug: [YOUR TITLE]` 

My thinking was that it might be easier to navigate some tabs of the project board at a glance if we saw both repo and issue type up front. But there are also other ways to do this (or not do this). 

Also, for reference here is our formatting for PR titles: `[Website] - [UI component]: Brief statement describing what this pull request solves.`

Let me know if you'd like to see a change.

**Comment by elisaachen** [comment]
@amyleadem I think those titles make sense to me (but I am also not someone who works in GH so 🤷 .

**Comment by amyleadem** [comment]
> So `Needs: Confirmation` is only a bug related thing?

In my experience, bugs always need confirmation and feature requests only sometimes do. For that reason I think it is best to not automate a `needs` label for FRs. But I will happily defer to others on this topic because I might have a different understanding of the semantics here.

**Comment by elisaachen** [comment]
@mejiaj @amyleadem  - Could we add in the Description section some text to also include: "Let us know if that impacts major or minor functionality and if you have workaround." This helps us assign which Severity label to it. 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/56040216/173418362-5a161d4d-d86b-427a-a7a7-cf3fed2391d4.png">

**Comment by amyleadem** [comment]
> @mejiaj @amyleadem - Could we add in the Description section some text to also include: "Let us know if that impacts major or minor functionality and if you have workaround." This helps us assign which Severity label to it. 

@elisaachen To consolidate conversation, I have responded to this comment [inside the PR](https://github.com/uswds/uswds/pull/4789#issuecomment-1155193122). Please let me know if you have questions.
