### ISSUE TITLE
Print out archive size on release

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#4693]
On release we should output:
- [x] Archive size
- [x] Source size (before zip)

Information is showing by default with npm v8.11.0

**Comment by mejiaj** [comment]
@amyleadem when running the command `npx gulp release` I now see the tarball details, could you please confirm?

![image](https://user-images.githubusercontent.com/3385219/177360637-b1245f93-1001-496d-b03c-8160e94f0b7a.png)

This wasn't printing before, so I just wanted to make sure.

**Comment by amyleadem** [comment]
> when running the command npx gulp release I now see the tarball details, could you please confirm?

@mejiaj  I am not seeing the same details. Here is what I see when I run the release command in `develop`:

![image](https://user-images.githubusercontent.com/93996430/177369485-f4c77493-012e-4c2d-984d-fe76de07675a.png)

No mention of "Tarball Details" like your screenshot shows. 

For good measure, I also ran it on `jm-release-updates` (assuming it was up-to-date) and got the same result (No tarball details).

**Comment by mejiaj** [comment]
@amyleadem was this on a clean `npm install`?

**Comment by amyleadem** [comment]
@mejiaj Yes. Just checked that everything was up to date, did another clean install and re-ran to confirm. Same result.

**Comment by mejiaj** [comment]
Package information shows with NPM `8.11.0`, thanks @amyleadem!

**Comment by mejiaj** [comment]
Decided against because NPM 8+ already includes this information.
