### ISSUE TITLE
Improve contribution model

### ISSUE THREAD

**Issue by elisaachen** [uswds/uswds#4704]
### **What**
___
Clearly define and make visible **_how_** users contribute to USWDS.

### **Intended outcome**
___
 USWDS users know what they can contribute, how, and where. 

### **Done when**
___
- [x] Conduct research on current state contribution model
- [x] Create feature request view in GitHub
- [x] Update GitHub contribution guidance 
- [x] Develop Contributing website page 
- [x]  #4691 
- [x] Identify "good first issues"
- [x] Document contributing governance workflows
- [x] https://github.com/uswds/uswds-site/issues/1655
- [x] https://github.com/uswds/uswds/issues/4810
- [x] Clarify ways to share research and design assets 
- [x] Track contribution metrics

**Comment by brunerae** [comment]
Closing as complete
