### ISSUE TITLE
June Newsletter

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds#4705]
June Newsletter should make another plug for migrating/upgrading to USWDS, 

Then maybe a formalized invitation to ask how it's going.

**Comment by bonnieAcameron** [comment]
Draft is here: https://docs.google.com/document/d/1r6z2PPJm6jfo3himUi1zxLKfaKtiU-1wh7YK9pjj1nE/edit#

**Comment by thisisdano** [comment]
Done!
