### ISSUE TITLE
SyntaxError: Identifier 'init' has already been declared

### ISSUE THREAD

**Issue by poundingCode** [uswds/uswds#4706]
## Description

installing USWDS per the guidance throws syntax errors on modules.

C:\ My path\myproj> npx gulp -init
SyntaxError: Identifier 'init' has already been declared
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:117:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:337:14)
    at async link (node:internal/modules/esm/module_job:70:21)

## Steps to reproduce the issue

1. follow instructions per https://designsystem.digital.gov/documentation/getting-started/developers/phase-one-install/
2. follow instructions per https://designsystem.digital.gov/documentation/getting-started/developers/phase-one-install/#step-2-initialize-your-project-in-node
3. npx gulp init
4. receive sadness...

**Comment by amyleadem** [comment]
@poundingCode Thanks for letting us know about this. We will investigate and let you know what we discover.

**Comment by poundingCode** [comment]
I was able to resolve my issue - it turned out that some of the dependent libraries didn't install properly.

**Comment by amyleadem** [comment]
@poundingCode Glad you found a solution. Thanks for letting us know!
