### ISSUE TITLE
Create inclusive pattern library

### ISSUE THREAD

**Issue by elisaachen** [uswds/uswds#4750]
### **What**
___
Develop tools and guidance similar to [VA's pattern guidance](https://design.va.gov/patterns/) and [Gov.uk's design patterns](https://design-system.service.gov.uk/patterns/) for the USWDS, with an eye to effective and inclusive solutions to common user tasks in the service of transactional applications (e.g. applying for benefits).

### **Intended outcome**
___
Develop a set of USWDS patterns that promote inclusive design practices across the federal government.

### **Done when**
___
- [x] Conduct research on patterns
- [x] Host meetup with stakeholders and high impact service providers (HISPs) on inclusive design patterns
- [x] Deliver prioritized list of patterns and components
- [x] Complete draft of patterns and supporting components
- [x] Review patterns with stakeholders
- [x] Publish final patterns to a new section of the USWDS product website
- [x] Publish new components to support the new patterns

**Comment by brunerae** [comment]
Closing as complete
