### ISSUE TITLE
Improve USWDS website information architecture

### ISSUE THREAD

**Issue by elisaachen** [uswds/uswds#4755]
### **What**
___
Changes to the way content is organized across desigsystem.digital.gov

### **Intended outcome**
___
To improve findability of content and overall user experience

### **Done when**
___
- [ ] https://github.com/uswds/uswds-site/issues/1785
- [ ] Conduct planned research activities
- [ ] https://github.com/uswds/uswds-site/issues/1827
- [ ] Make a plan for implementing IA changes

**Comment by brunerae** [comment]
Closing because we no longer need this roadmap tracking issue.
