### ISSUE TITLE
June POAM report and security vulnerability resolution

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4774]
## Description
Documents: [POAM sheet ](https://docs.google.com/spreadsheets/d/16oHvPopiALjFn2FXmR-IgNshBKnt5lyQNcV15VZZ5dk/edit#gid=0)

1. [x] Update POAM report sheet (Amy)
1. [x] Resolve security vulnerabilities (Charlie)

**Comment by amyleadem** [comment]
@mahoneycm I have updated the POAM report with the alerts from our repos. I think this one is actually pretty straightforward! Let me know if you have any questions.

**Comment by mahoneycm** [comment]
Available updates made and merged!
