### ISSUE TITLE
Decide where we track package stats

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4782]
We need to decide where we'll track package stats.

**Comment by mejiaj** [comment]
Google sheets. 

We need to identify later which package stats we'll share publicly (release notes _or_ website).

**Comment by brunerae** [comment]
Final Decision:

Package stats will be tracked in the [Performance Metrics](https://docs.google.com/document/d/1SaMdczrKaWmlcdoAvLkFgJusqJSX7qGz0mEbIyE30o0/edit#heading=h.hjl9o4h1kkbn) document.
