### ISSUE TITLE
Upgrading USWDS, @extend css class not showing in SCSS @forward

### ISSUE THREAD

**Issue by billyhunt** [uswds/uswds#4795]
### Describe the bug
When upgrading 

### Steps to reproduce the bug
I am upgrading to the US Web Design System 3, and am running into an interesting problem related to extending css classes from the USWDS.  

Some of my class extends do not seem to be working.   Here is my code.

Custom Component:
```//extends.scss

@use "uswds-core" as *;

.usa-checkbox__label-extend {
  @extend .usa-checkbox__label;
}
```

Main Stylesheet:
```
//style.scss
/*
* * * * * ==============================
* * * * * ==============================
* * * * * ==============================
* * * * * ==============================
========================================
========================================
========================================
*/

// -------------------------------------
// Import theme settings
@forward "uswds-theme";

// -------------------------------------
// Import the necessary USWDS packages
@forward "uswds";

// -------------------------------------
// Import theme custom styles

// layout needs to be first
@forward "custom/layout";
@forward "custom/variables";
@forward "custom/card";
@forward "custom/complaint";
@forward "custom/alerts";
@forward "custom/banner";
@forward "custom/buttons";
@forward "custom/combo-box";
@forward "custom/footer";
@forward "custom/form";
@forward "custom/header";
@forward "custom/ie";
@forward "custom/intake.scss";
@forward "custom/pagination";
@forward "custom/progress";
@forward "custom/skipnav";
@forward "custom/table";
@forward "custom/typography";
@forward "custom/utils";
@forward "custom/confirmation";
@forward "custom/landing";
@forward "custom/privacy";
@forward "custom/subpage";
@forward "custom/touchpoints";
@forward "custom/links";
@forward "custom/modal";
@forward "custom/print";
@forward "custom/error";
@forward "custom/extends";
```

The class “usa-checkbox__label-extend” will not pull from the original "usa-checkbox__label" USWDS class.  If I change the last line of “style.scss” from 
```@forward "custom/extends";```
to
```@import "custom/extends";```

it works.  

It also works if I copy the code from “extends.scss” and put it in “style.scss”.

Does anyone have any thoughts?  This is my first time working with @forward and @use.

### System setup
- 3.0.1
- Mac
- Monterey
- Chrome Version 101.0.4951.64 (Official Build) (x86_64)

### Additional context
Add any other context about the problem.

**Comment by brunerae** [comment]
hey @billyhunt! Just letting you know we've seen this and will get back to you ASAP!
