### ISSUE TITLE
Component: In-page navigation

### ISSUE THREAD

**Issue by Nijal-collab** [uswds/uswds#4801]
Description:
Code:  
Documentation: 

TODO
- [x] First code review (@thisisdano)
- [ ] Check heading order (@thisisdano)
- [ ] First guidance review (@thisisdano)
- [x] Second code review (@mejiaj)
- [ ] Further dev review (_optional_)
- [ ] Merge code into current release
- [ ] Second guidance review
- [ ] Further content review (_optional_)
- [ ] Link guidance (@thisisdano)
- [ ] Update guidance to new formatting (@thisisdano)
- [ ] Merge guidance into docs
- [ ] Update design assets if necessary (@thisisdano)

- - -

DESIGN ASSETS
- [x] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback - done
- [x] 20% - Draft user story & clarify the problem(s) / user needs
- [x] 30% - Low-fi design review
- [ ] 40% - Get community feedback on initial, Hi-fi designs
- [ ] 50% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] ~80% - Sketch and XD assets review w/ Dan + merged into master working files~
- [ ] ~100% - PR approved by Dan~

GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews)- done ##/##
- [x] 20% - Draft guidance review no. 1 (minimum 2 bullets each section) - done ##/##
- [ ] 40% - Get community feedback on draft guidance
- [ ] 50% - Draft guidance review no. 2 (accessibility focus)
- [ ] 60% - Draft guidance review no. 3 (w/ Dan)
- [ ] ~80% - Add component to research report and slide deck~
- [ ] ~100% - PR approved by Dan~

CODE
- [x] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [x] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [ ] 40% - Get community feedback or conduct tests with users, round 1
- [ ] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [ ] 80% - Get community feedback or conduct tests with users, round 2
- [ ] ~100% - PR approved by Dan~

**Comment by jonadecker** [comment]
Feedback from 7/5 sync:

> Is design _too_ matchy to left sidebar and a possible area of confusion? Certain amount of visual tension between the two. Maybe just left bar vs. box? Explore some options to differentiate. Like the idea of “progress bar” effect along left side

**Comment by mitchmoccia** [comment]
Currently working on the new, not-so-much-like the left side nav treatment, and this version will be dynamically generated based on h2s or h3s or both. Will have the demo ready for Monday.

**Comment by brunerae** [comment]
Closing as this now exists: https://designsystem.digital.gov/components/in-page-navigation/

**Comment by brunerae** [comment]
Closing as this now exists: https://designsystem.digital.gov/components/in-page-navigation/
