### ISSUE TITLE
Feature request view link goes to a project board

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#4818]
### Describe the bug

Our CONTRIBUTING.md says "If you want to find other feature requests open for upvoting, check out our feature request view sorted by status" but that link brings me to a project board with no information about upvotes. This view is confusing and I expect to see a list of all feature requests open for voting, sorted by popularity (the current number of votes they're received). 

### Steps to reproduce the bug

1. Open [CONTRIBUTING.md](https://github.com/uswds/uswds/blob/develop/CONTRIBUTING.md)
2. Look for `If you want to find other feature requests open for upvoting, check out our feature request view sorted by status` and follow the link

### Expected Behavior

Instead of `feature request view sorted by status`, we should link to `feature requests sorted by upvotes` since this is is most useful view for feature requests. [This view sorted by upvotes](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Status%3A+Voting+Open+%F0%9F%91%8D%22+sort%3Areactions-%2B1-desc) is where I'd expect to go to see what feature requests are currently in `Voting Open` status and how many votes they're received.

### Related code

n/a

### Screenshots

n/a

### System setup

n/a

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by PrajwalBorkar** [comment]
/assign
I can work on this issue.
