### ISSUE TITLE
USWDS - Bug: Update USWDS npm description to point users to @uswds

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#4843]
### Describe the bug

Currently, when you search for "USWDS npm" in Google, you are pointed to the old [uswds package]( https://www.npmjs.com/package/uswds). Additionally, when you search for "uswds" on [npmjs.com](https://www.npmjs.com/search?q=uswds), "uswds" is the first match while "@uswds/uswds" is the fifth entry. 

The current package is `@uswds/uswds`, but there is no reference to 3.0 or the new package on the `uswds` package page to help direct the user. This can lead users to think that the most recent version of the Design System is 2.13.3, instead of the actual current version, which is 3.0.2.

Related Slack thread: [USWDS-public, 07/05/22](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1657030530687139)

### Steps to reproduce the bug

1. On Google, search for "USWDS npm"
2. Go to the first item that pops up
3. See that the current version is 2.13.3, with no reference to USWDS 3.0 or @uswds/uswds

### Expected Behavior

Users should easily be able to search for and find the most recent version of the design system in npm. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
Closed with #4846.
