### ISSUE TITLE
USWDS - Bug: Mobile header items inaccessible to touch screen readers

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#4866]
## Describe the bug
The menu items inside the mobile header nav can not be selected when using VoiceOver Gestures or TalkBack on touch devices.

## Steps to reproduce the bug
1. Open designsystem.digital.gov in Safari on an iOS mobile device
2. Active VoiceOver gestures by triple-clicking the side or home button
3. Navigate to menu button by using a single finger to swipe right (to go forward) or left (to go back)
    - Note: To return to `skip to content` element, tap four fingers on the top half of the screen
4. Once menu button is selected, double tap on screen to open it
5. Attempt to navigate to items in menu by touch or by single finger swipe right/left
6. Discover that only items behind the menu are accessible
    - To contrast, try the same actions on menu button in https://www.w3.org/WAI/tutorials/

## Instructions for setting up VoiceOver Gestures
Using VoiceOver Gestures:
1. Turn on VoiceOver shortcut by visiting Settings > Accessibility > Accessibility Shortcut --> assign triple click to "VoiceOver"
2. Navigate to desired website
3. Triple click the side button to activate voiceOver
4. Use the gestures in [this guide from deque](https://dequeuniversity.com/screenreaders/voiceover-ios-shortcuts) to navigate

## Findings:
- Issue appears first in [3.0.0-beta.3](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-3.0.0-beta.3/iframe.html?id=components-header--default&args=&viewMode=story)

**Comment by mejiaj** [comment]
@amyleadem related, possibly duplicate https://github.com/uswds/uswds/issues/4787

**Comment by amyleadem** [comment]
Duplicate issue. Closing this in favor of #4787.
