### ISSUE TITLE
Discussion of Tabs Component Proposal

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds#4883]
In the developer sync, we discussed crafting a reply to #4784 collaboratively. I've drafted a response. Please feel free to add your feedback. Track your changes or add in comments so that we can follow the conversation. 

Thanks!https://docs.google.com/document/d/16fs5Sfx6h_CaMCeDJytuBY6uoI9EMF2NXrxgKyrUTkg/edit#heading=h.es3wxq569omw

**Comment by bonnieAcameron** [comment]
@mejiaj @amyleadem @brunerae @thisisdano @jaclinec Hi all! Can you take a look at the google doc and add your comments/suggestions with tracking? thank you!

**Comment by thisisdano** [comment]
Done
