### ISSUE TITLE
USWDS - Bug: Character count invalid text styling overridden

### ISSUE THREAD

**Issue by cateprNIH** [uswds/uswds#4896]
### Describe the bug

Using the [character count component](https://designsystem.digital.gov/components/character-count/), if the character count goes over the max limit, the invalid "# characters over limit" text appears. This text should be styled as red text but the `usa-character-count__message--invalid` class is being overridden by the default `usa-hint` class.

### Steps to reproduce the bug

1. Go to <https://designsystem.digital.gov/components/character-count/>
2. Enter in enough text in either example to go over the character limit.
3. The "# characters over limit" text should show, but is not a the red invalid color.
4. Inspect the `usa-character-count__message` element.
5. See the `usa-hint` class styling is overriding the `usa-character-count__message--invalid` class styling.

### Expected Behavior

The `usa-character-count__message--invalid` class should have higher CSS specificity to override the `usa-hint` styling and show the character count message text with the correct styling.

### System setup

- USWDS Version: 3.0.1
- Device: Macbook Pro
- Operating System: Mac OSX 12.4
- Browser and version: Chrome 103

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
Confirmed. Should be resolved in #4976.

**Comment by mejiaj** [comment]
Fixed in [develop](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-form-inputs-character-count--character-count) as part of release 3.2.0.

![image](https://user-images.githubusercontent.com/3385219/225693731-8f8eb3c5-96ed-41c2-816e-6979f721ed3c.png)
