### ISSUE TITLE
USWDS - Feature: Update 2x dependencies

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#4899]
### Is your feature request related to a problem? Please describe.

For security we should update USWDS 2x dependencies.

### Describe the solution you'd like

- Run an NPM audit
- Bump patch versions where possible
- Evaluate any updates that are higher than patch

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds/pull/4901
