### ISSUE TITLE
Monthly Call Metrics Analysis

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds#4900]
Can we find any correlation between the "type" of Monthly Calls we do and the attendance or CSAT?

(ref: Bonnie/Dan 1:1 on Aug 3, 2022)

**Comment by bonnieAcameron** [comment]
Link to Progress: https://docs.google.com/spreadsheets/d/19c2uz6vqIgm904BpkSfF7OazyU8Nd-SIxVJ1C8hLhHE/edit?usp=sharing

**Comment by brunerae** [comment]
To be presented at 09/14 CS/UX sync

**Comment by bonnieAcameron** [comment]
The 9/14 sync was cancelled, here's the link to the presentation:[ MC Analysis Slides](https://docs.google.com/presentation/d/1r3lC9RjSeK7KlphKJNKaZ-pGhCgFQq2wXSA2ILKCZgo/edit#slide=id.g15899c284c6_0_5)
