### ISSUE TITLE
USWDS - Bug: Prefix/suffix does not use disabled input styling

### ISSUE THREAD

**Issue by patrickcate** [uswds/uswds#4913]
### Describe the bug

If an input has a prefix/suffix and the input is disabled, the disabled styling does not apply to the prefix/suffix. Disabled inputs have a light gray background, but the prefix/suffix's have a white background.

### Steps to reproduce the bug

1. Create a USWDS input with a prefix, suffix, or both.
2. Add the `disabled` attribute to the USWDS input.
3. The input will have a light gray background, but the prefix/suffix's will have a white background.

### Expected Behavior

When an input is disabled, its styling is also applied to any prefix/suffix's on the input.

### Related code

```
<form class="usa-form">
  <label class="usa-label" for="example-input-suffix">Weight, in pounds</label>
  <div class="usa-input-group usa-input-group--sm">
    <input
      id="example-input-suffix"
      class="usa-input"
      pattern="[0-9]*"
      inputmode="numeric"
      disabled
    />
    <div class="usa-input-suffix" aria-hidden="true">lbs.</div>
  </div>
</form>
```

### Screenshots

![Screen Shot 2022-08-08 at 11 03 49 AM](https://user-images.githubusercontent.com/6277206/183473144-d6390904-8762-4d13-a5ca-1dc9eef3bdcc.png)

### System setup

- USWDS version: 3.0.2
- Device: Macbook Pro
- Operating System: OSX 12.4
- Browser and version: Chrome v103

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mahoneycm** [comment]
The error appears for me on chrome. Will investigate further.
