### ISSUE TITLE
Before 08/24: Review FEDSIM and AAS repos ahead of consult

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4923]
> I am responsible for updating the GSA sites FEDSIM and AAS to USWDS version 3. In the process, I believe I may have made a few mistakes and I am unable to resolve issues with either. 
> 
> I would like to request a developer spend some time with me on both the FEDSIM and AAS sites in order to get their GitHuh repositories corrected so we can build these sites and continue to make updates.
> 
> Here are the GitHub repositories that are in error:
> 
> FEDSIM test
> https://github.com/richgarner71/FEDSIM_test
> 
> AAS root (LastWorking branch)
> https://github.com/gsa/aas_root/tree/LastWorking

**Comment by amyleadem** [comment]
Closing because this was completed.
