### ISSUE TITLE
Check for dependencies ahead of 2.13.4 release

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4940]
Do another check for dependencies ahead of 2.13.4 release.

**Comment by mejiaj** [comment]
We should consider using `npm shrinkwrap` to lock  down packages and their children. The benefit of this over only fixed versions is that children are locked too.

**Comment by mejiaj** [comment]
Closing in favor of https://github.com/uswds/uswds/issues/5189. We're going to try to limit the scope of security issues with dev dependencies by removing them unless absolutely necessary.
