### ISSUE TITLE
Create draft of updated required field guidance

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4942]
Based on research conducted in https://github.com/uswds/uswds-site/issues/1163, draft updates to the written guidance.

- [x] Update the written guidance and templates to use required labelling

**Longer Term**
- [ ] Call out the guidance change as a new and potentially breaking change using something like a tag.
- [ ] Be sure to publicize this change through monthly call, perhaps also a blog post and social media

**Comment by jaclinec** [comment]
Here is the new copy for labeling required fields guidance: https://docs.google.com/document/d/1sYY6bsEsy9trPgyx0wI-sBqlO7hPNYLEIn0GkI8C2ek/edit?usp=sharing
