### ISSUE TITLE
USWDS - Bug: secondary nav link separators are visible to screen readers

### ISSUE THREAD

**Issue by nick-mon1** [uswds/uswds#4944]
### Describe the bug

Secondary links line separator is being read by screen readers as follows: “Link About Vertical Bar, Link Subscribe Vertical Bar…"

### Steps to reproduce the bug

1. Navigate to digital.gov homepage
2. Use JAWS or ChromeVox to read the navigation

### Expected Behavior

Screen reader should read “Link About, Link Subscribe …"

### Related code

We could style with `border-left` instead of `content`.

https://github.com/uswds/uswds/blob/8d2c7716890606e342877e916d1622eb8f1eaa0b/packages/usa-nav/src/styles/_usa-nav.scss#L345-L349

### Screenshots

Secondary navigation within the primary navigation.

<img width="373" alt="Screen Shot 2022-09-14 at 4 34 26 PM" src="https://user-images.githubusercontent.com/104778659/190258188-a6980535-fe60-4441-9320-58254d3b3007.png">

### System setup

This occurs on both PC and Mac with Chrome browser with USWDS 3.0

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
Bug is not reproducible in NVDA or VoiceOver.
