### ISSUE TITLE
Draft recommendations for font usage in sites that have multiple languages

### ISSUE THREAD

**Issue by mitchmoccia** [uswds/uswds#4950]
In the September 2022 USWDS monthly call, a question was asked regarding fonts not having complete characters sets for multiple languages. 

Some initial findings:

More than 97% of websites use UTF-8 encoding
https://w3techs.com/technologies/cross/character_encoding/ranking

The default character encoding in HTML-5 is UTF-8.
https://www.w3schools.com/charsets/ref_html_utf8.asp

This is a good font to recommend for sites with three or more languages:
Noto: A typeface for the world
https://fonts.google.com/noto

The vast majority of modern computer fonts use Unicode mappings, even those fonts which only include glyphs for a single writing system, or even only support the basic Latin alphabet.

Primarily, you should try to find a list of fonts so that each of the fonts covers all the characters needed and declare that list as the font-family value.

What is the most complete Unicode font?
The hands-down most comprehensive coverage would be Roman Czyborra's GNU Unicode Font project. It is intended to collect a complete and free 8×16/16×16 pixel Unicode font. It currently covers 34,445 characters (out of ~40,000+ defined characters).

Utilizing the lang attribute can help with designating a font fallback schema as detailed here:
https://www.w3.org/International/questions/qa-lang-why#:~:text=The%20lang%20(or%20sometimes%20the,the%20text%20on%20the%20page.

**Comment by mitchmoccia** [comment]
Updated the component guidance for language selector to include the following in both the Three or More Languages and Language selector unstyled sections. @maomeara63 @jonadecker standing by for any edit requests.
https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/mm-language-selector/components/language-selector/#language-selector-with-three-or-more-languages

- **Language links should contain a span element with the lang attribute.** Every language link in the language selector dropdown, that is different from content of the current page, should be defined using the lang attribute on a `<span>` tag wrapping the relevant text (e.g., “`<span lang="es">Hola</span>` means Hello”). Please see the link for reference [H58: Using language attributes to identify changes in the human language](https://www.w3.org/WAI/WCAG21/Techniques/html/H58).
- **All anchor tags should contain an aria-label attribute.** The aria-label attribute will provide a label for objects that can be read by assistive technology. See the link for references [ARIA6: Using aria-label to provide labels for objects](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA6)
- **The title attribute can be used to provide a visual hover text for desktop users.** Use the title attribute to supplement link text. [H33: Supplementing link text with the title attribute](https://www.w3.org/TR/WCAG20-TECHS/H33.html)

**Comment by thisisdano** [comment]
Completed
