### ISSUE TITLE
USWDS - Bug: Unable to find %usa-prose-p selector when importing uswds-typography in one file and uswds-core in another

### ISSUE THREAD

**Issue by esheehan-gsl** [uswds/uswds#4962]
### Describe the bug

I’m trying to configure USWDS inside an `@layer` rule using the `load-css` function from `sass:meta`. When I try to `@use "uswds-core"` in my own Sass modules so that I can access the tokens for my styles, I get a `target selector not found` error for `%usa-prose-p`.

### Steps to reproduce the bug

1. Create a `_uswds-theme.scss` module [per the documentation](https://designsystem.digital.gov/documentation/settings/)
2. Create a `_uswds.scss` that forwards the theme file and `uswds-typography`
3. Create another Sass file with `@use "uswds-core" as uswds` to define a rule that uses a USWDS token
4. Create a Sass file that imports both `_uswds.scss` and your third Sass file using `load-css`
5. Build Sass file number 4

### Expected Behavior

The output should contain the styles from `uswds-typography` as well as whatever styles you added to your Sass file in step 3.

### Related code

I have a demo of the bug here: https://github.com/esheehan-gsl/uswds-layer-test

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mahoneycm** [comment]
Hello,

We recommend using `@forward` to forward the `uswds` and `layout` packages in your `style.scss` file as recommended in the [settings documentation](https://designsystem.digital.gov/documentation/settings/#configuring-custom-uswds-settings).

Is there a larger benefit that you were hoping to achieve using `@layer`, `@load-css`, and `sass:meta`?

**Comment by esheehan-gsl** [comment]
> Is there a larger benefit that you were hoping to achieve using @layer, @load-css, and sass:meta?

Well, yes. The benefit is being able to use `@layer` with USWDS.

Using `@load-css` and `sass:meta` are just the only way I can find to import USWDS into a CSS layer, because many of the modules export styles directly, instead of exporting mixins containing the styles.

Placing all of the USWDS styles inside a layer makes it easier to override rules without getting into silly specificity battles. I’m pretty sure that customizing frameworks is one of the primary motivations for adding layers to the spec in the first place. It’s certainly an example that gets used a lot.

**Comment by mahoneycm** [comment]
Related: https://github.com/uswds/uswds/pull/4576

**Comment by mahoneycm** [comment]
Working on: #5043

**Comment by esheehan-gsl** [comment]
Thanks! 🙏🏻
