### ISSUE TITLE
Submit Top Tasks survey for PRA clearance

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4974]
Submit PRA paperwork to begin the PRA clearance process for the top tasks research study (see #4934 for details).

**Comment by jaclinec** [comment]
The ICR form and survey communications were submitted for PRA clearance on 11/10/2022. An email was sent to Aaron Stienstra per the [PRA approval process documentation.](https://docs.google.com/document/d/1r0-AQ6DChw3FoZEV9q6K9dnhEa05uwLyPcEzLAV74FI/edit?usp=sharing)

**Comment by jaclinec** [comment]
As I have not heard from my original PRA contact, I have now submitted the PRA paperwork (as of today) to the GSA Regulatory Secretariat Division (RegSec). I have received a response, so it seems the process is moving forward now.
