### ISSUE TITLE
USWDS - Bug: External Links punctuation break

### ISSUE THREAD

**Issue by mlloydbixal-zz** [uswds/uswds#4977]
### Describe the bug

With external links at the end of a sentence it will always potentially drop the period down to the next line because it doesn't think it is part of the text

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/components/link/ 
2. Select the paragraph element containing "This is a link that goes to an external website"
3. Give it a width of 350px
4. As you adjust the width you can find where the period will break off onto the next line

### Expected Behavior

Breaks happen in the text and not at the period

### Screenshots

<img width="433" alt="Screen Shot 2022-10-06 at 12 33 46 PM" src="https://user-images.githubusercontent.com/97538658/194369780-ae7873de-83df-4cf4-80dc-9086f0e5b83c.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
@mlloydbixal which browser? On edge I see this:

![image](https://user-images.githubusercontent.com/3385219/199500903-f1885813-229e-4438-9cd7-ca9c415b4623.png)

**Comment by mejiaj** [comment]
Confirming. Seeing this on [link page](https://designsystem.digital.gov/components/link/) at 426px.

![image](https://user-images.githubusercontent.com/3385219/202553932-252dd262-1f96-4fc9-9170-fc8698975166.png)
