### ISSUE TITLE
Update to latest Node LTS

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#5010]
### Is your feature request related to a problem? Please describe.

USWDS tries to stay at the current Node LTS, which is currently ~`18.12.2`~ `18.18.1`. Our `nvmrc` file pins us to Node 16. 

### Describe the solution you'd like

Let's update to the current LTS (~`18.12.2`~ `18.18.1`) and update our `nvmrc` and our CI settings to match, for both the `uswds` and `uswds-site` repos at first. But each of our repos should use the current LTS.

### Describe alternatives you've considered

These isn't a problem with the current setup, so an alternative is to do nothing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by thisisdano** [comment]
I'm going to mark this as blocked since current Storybook uses Webpack 4 and Webpack 4 does not support Node 17 and higher. We'll need to wait until we can build with Storybook 7 and Webpack 5 to make this upgrade. Since there doesn't seem to be any compelling reason to upgrade to the most recent LTS, we'll just revisit later.

**Comment by mejiaj** [comment]
We need to schedule this due to Cloud Pages dropping support for Node 16 - https://github.com/cloud-gov/pages-build-container/issues/437.
