### ISSUE TITLE
USWDS - Bug: utility breakpoints

### ISSUE THREAD

**Issue by alex9000** [uswds/uswds#5011]
### Describe the bug

I'm using "@uswds/uswds": "^3.0.2"

In the [docs](https://designsystem.digital.gov/utilities/) under utility breakpoints, it lists those set as true or false by default.

Utility breakpoints | $theme-utility-breakpoints |   | map | Set which mobile-first breakpoints are output for the utilities.
-- | -- | -- | -- | --
  | "card" | false |   |  
  | "card-lg" | false |   |  
  | "mobile" | false |   |  
  | "mobile-lg" | true |   |  
  | "tablet" | true |   |  
  | "tablet-lg" | false |   |  
  | "desktop" | true |   |  
  | "desktop-lg" | false |   |  
  | "widescreen" | false

### Steps to reproduce the bug

In order to enable the mobile breakpoint, I set the following value in _uswds-theme.scss
  $theme-utility-breakpoints:
    (
      "mobile": true,
    ),

### Expected Behavior

I will be able to use utilities like mobile:utility and desktop:utility. Instead the desktop breakpoint was disabled while the mobile was enabled.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by JoshingYou1** [comment]
I had this issue as well. The only solution I was able to come to was to include the `"desktop"` breakpoint. Once I did that, the others worked as intended.

**Comment by alex94143** [comment]
If the user customizes utility by setting a breakpoint to true, does that set the default breakpoints to false by design?

**Comment by mahoneycm** [comment]
Hello @alex9000 ! 

When modifying any settings stored as a map, you need to set all elements of the map, not just the element you wish to change.

For example:
```scss
@use "uswds-core" with (
  $theme-utility-breakpoints: (
      "card": false,
      "card-lg": false,
      "mobile": true,
      "mobile-lg": true,
      "tablet": true,
      "tablet-lg": false,
      "desktop": true,
      "desktop-lg": false,
      "widescreen": false,
    )
);
```

You can find this note on utility pages with map settings, such as under the [responsive variants](https://designsystem.digital.gov/utilities/color/#responsive-variants-2) sections.

We'll also take a look at our documentation to consider other locations this information may be helpful, such as the docs page you provided!

**Comment by alex9000** [comment]
Thanks, @mahoneycm , I don't recall seeing those instructions before, but it doesn't mean they weren't there.
