### ISSUE TITLE
USWDS - Feature: Add customizable attribute for "offset top" to more accurately scroll to targets

### ISSUE THREAD

**Issue by mitchmoccia** [uswds/uswds#5023]
### Is your feature request related to a problem? Please describe.

Due to the varying height and behaviors of headers and navbars, a new customizable variable or attribute would improve the in-page nav UX.

### Describe the solution you'd like

This is an important one that will allow for the adjustment of where a selected in-page nav link scrolls to from the top. Currently offsetTop alone is not accurate enough, we need this customizable, calibration mechanism to dial it in.

A developer will be able to easily add the data- attribute `data-offset-top` to the aside element in the HTML to precisely target where they want the scroll to effect to land. 

NOTE: This is needed ASAP for the USWDS documentation site!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by amyleadem** [comment]
Closing this issue because a top offset was added in https://github.com/uswds/uswds/commit/fbd8b19183426cd5c07c50635e924ec678425828 as part of PR https://github.com/uswds/uswds/pull/5026.
