### ISSUE TITLE
USWDS - Feature: Improve usability of input mask

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#5025]
### Is your feature request related to a problem? Please describe.

While the input mask component passes a general usability bar, we could improve its performance by giving better guidance around what to input in a masked component, better error messaging when users input invalid characters, and better input prompts to help users along. 

There's a bit of a mismatch in expectations with the current input mask, since the hint, cursor placement, and mask indicate that users should enter literals (for example the hyphens in the telephone number `123-324-4434`), but they cannot. And when they cannot, there's no way for them to know why they cannot.

This should be a fast follow-up on the Input Mask component.

### Describe the solution you'd like

1. The cursor should "jump" literals and place the cursor where the user is expected to enter the content. Users should get the literals "for free" and not have to decide whether they need to add them.
2. Hint text should make expectations clear for both sighted users and AT users. 
3. There should be some kind of error messaging — particularly for AT users — that explains why certain characters can't be entered
4. Decide whether excluded characters should ever appear in the input. Currently they "flash" in the input before disappearing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by mejiaj** [comment]
This will be closed as part of #5227.

**Comment by thisisdano** [comment]
Closed in favor of #5054
