### ISSUE TITLE
USWDS - Feature: Add customizable data- attribute for intersection observer option root margin

### ISSUE THREAD

**Issue by mitchmoccia** [uswds/uswds#5029]
### Is your feature request related to a problem? Please describe.

Currently root margin is hardcoded in the JS of the in-page nav component. Ideally, we should allow for developers to dial this in themselves for their specific page layouts.

### Describe the solution you'd like

We could add another data- attribute on the `aside` element that allows for a custom root margin setting. Currently it is set at the following, mainly because that's what works with the USWDS component site:

```
0px 0px -85% 0px
```
That's saying (starting from the top of the browser) observe the observables 0px from the top, 0px from the right, 85% from the bottom of the window, and 0px from the left.

But what if a developer wanted to just set it to 0px all the way around? We could offer this in the HTML `aside` tag:

```
data-root-margin="0px"
```

If no data- attribute is present, a default one in the JS would be used.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by amyleadem** [comment]
The ability to accommodate a root margin data attribute was added in PR https://github.com/uswds/uswds/pull/5037.
