### ISSUE TITLE
USWDS - Bug: CSS loader shows module not found 

### ISSUE THREAD

**Issue by paragdiwan** [uswds/uswds#5033]
### Describe the bug

I am using `next js` along with `uswds 3.2.0` version using `scss` support. 

Following the steps in the document to add a `IncludePaths` in `webpack config` gives an error when trying to reference the `uswds`  file.

**
error : - styles/global.scss
Module not found: can't resolve - '../node_modules/uswds/dist/scss/core/fonts/roboto-mono/roboto-mono-v5-latin-300.woff2'
**

> 

### Steps to reproduce the bug

1. Install NextJS 
2. Install Sass ( npm install sass)
3. Install Uswds  
4. update next.config.js 
`sassOptions: {
      includePaths: [
        "./node_modules/@uswds/uswds/packages"
      ],
    },`

5. Add a global.scss in `styles`
6. reference `uswds.scss` file.

### Expected Behavior

Should not see any error and the component should render properly.

### Screenshots

![Screenshot 2022-11-10 at 17 43 52](https://user-images.githubusercontent.com/1788241/201100109-393e51be-90e6-436c-854c-d65f34a592d5.png)

### System setup

USWDS version 3.0.2
MacOS
Chrome latest.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mahoneycm** [comment]
Hello @paragdiwan !

You should be able to resolve this by setting `$theme-font-path` wherever you define your USWDS settings.

You can either do this by using [uswds-compile](https://designsystem.digital.gov/documentation/getting-started/developers/phase-two-compile/#using-uswds-compile) to build your assets into your directory and referencing them there. _(What we recommend)_

```scss
@use "uswds-core" with (
  $theme-font-path: "../path/to/assets/uswds/fonts",
)
```


Or by setting a relative path to the fonts directory within node_modules 

You'll likely have to do the same for `$theme-image-path`.

You can find more information in our documentation about using [JS frameworks](https://designsystem.digital.gov/documentation/developers/#js-customization) under the [Set the Base Asset Paths](https://designsystem.digital.gov/documentation/developers/#js-customization:~:text=the%20source%20Sass.-,Set%20the%20base%20asset%20paths%20(fonts%20and%20images),-The%20values%20of) section
