### ISSUE TITLE
USWDS - Enhancement: Allow customization of in-page nav target

### ISSUE THREAD

**Issue by danny-englander** [uswds/uswds#5050]
### Describe the bug

The new In-page navigation component picks up what I would classify as unwanted headings from elsewhere on the page. If you review the screen shot below, you will see that there are headings that do not add any value to the in page nav and are also confusing.

<img width="1529" alt="2022-11-22_09-12-33" src="https://user-images.githubusercontent.com/609623/203337126-71de9eb8-b1d2-43be-add8-213fc793a3ac.png">

### Steps to reproduce the bug

- Create a page that has a breadcrumb above the content area. For example

```html
<nav role="navigation" aria-labelledby="system-breadcrumb" class="usa-breadcrumb">
    <h2 id="system-breadcrumb" class="visually-hidden"><a id="section_0" class="usa-anchor"></a>Breadcrumb</h2>
    <ol class="usa-breadcrumb__list">
          <li class="usa-breadcrumb__list-item">
                  <a class="usa-breadcrumb__link" href="/"><span>Home</span></a>
              </li>
          <li class="usa-breadcrumb__list-item">
                  <a class="usa-breadcrumb__link" href="/uswds-components"><span>USWDS 3 Component Library</span></a>
              </li>
        </ol>
  </nav>
```

- The below on the page, create a content area and in-page nav. 
- Note that that the hidden h2 is picked up by in-page nav and it is also visually hidden as well. 

### Expected Behavior

 I would recommend the following improvements / fixes

- Create a data attribute to specifically name the content container that the in-page nav picks up headings for. For example,  `data-content-container="my-content-region"` -- only use headings from this region and no others elsewhere on the page
- ignore visually hidden heading tags

### System setup

- Using UWDS 3.3.0

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
@mitchmoccia would you be able to confirm whether this is a bug or not?

**Comment by mitchmoccia** [comment]
@danny-englander @mejiaj Hi Danny, I like your suggestion. Currently the in-page nav uses the `main` element as the region that headings will be queried and used for the nav. 

Could you please confirm:
- do you have a `main` element?
- is the nav code you posted inside that main element?

Also, is it possible to post the link to the page your screen shot came from? Thanks!
Mitch

**Comment by danny-englander** [comment]
@mitchmoccia The issue here is that I am putting the inpage nav inside the main container, basically in the content area. So it would be ideal if the in-page nav is not tied to the `<main>` page element. I've tested my page with Axe and all my semantic regions check out fine so there is no issue as far as that goes. if you like I can post a gist or something for the use case.

**Comment by mitchmoccia** [comment]
Can you post a screen shot of your code so I can see the structure relative to `main` (or post a link to the page)? Do you have the `aside` placed per the instructions here: https://designsystem.digital.gov/components/in-page-navigation/

e.g.:

```
<div class="usa-in-page-nav-container">
  <aside class="usa-in-page-nav"></aside>
  <main id="main-content" class="main-content">
     [ Page content ]
  </main>
</div>
```

I tend to agree that using a data- attribute might be better than tying it to the main element. This is something we can consider updating for future release.

**Comment by danny-englander** [comment]
@mitchmoccia here is a gist to help:

https://gist.github.com/danny-englander/6750a75f20adab770e22e52a8b6dad45

As you can see, I am using the in-page nav well inside the `<main>` element and the `<aside>` on this page (see screenshot of the left sidebar USA sidebar component) has nothing to do with the in page nav (right side). I hope this helps. I think there could be a lot of paradigms where this type of use case would be needed.

**Comment by danny-englander** [comment]
ok thanks! I think this use case would be common for complex CMSs.

**Comment by amyleadem** [comment]
Note: I created issue https://github.com/uswds/uswds/issues/5392 to separate out the issue of hidden headers appearing in the component.
