### ISSUE TITLE
USWDS - Input Mask refactor

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds#5054]

**Comment by mitchmoccia** [comment]
The input mask rewrite is in a good place and a PR has been created against the idp-staging branch:

https://github.com/uswds/uswds/pull/5104

Component page:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/mm-input-mask/?path=/story/components-form-inputs-text-input-mask--ssn

Updated guidance page:
https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/mm-input-mask-guidance/components/input-mask/

Highlights include:
- Countless improvements implemented based on feedback from version 1 and more
  - Primarily instant feedback and error handling has been implemented (similar to character count)
- Feedback from all our syncs integrate
- JSDocs added to each function
- Unit tests worked out for all five examples
- Guidance created on how to implement the new version

**Comment by mejiaj** [comment]
@amyleadem do you feel this is possible for 3.7.0 (end of this sprint) or should we bump back?

**Comment by brunerae** [comment]
This now duplicates #5442
