### ISSUE TITLE
USWDS - 404 template: Check if Spanish copy needs to be updated

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5060]
Once the English version has final approval, we should evaluate if the copy in the Spanish version of the 404 error template needs to be updated to match the changes made in [#5045](https://github.com/uswds/uswds/pull/5045)

English version Issue: https://github.com/uswds/uswds/issues/4980

**Comment by mejiaj** [comment]
@amyleadem we will have to update the Spanish version too.

**Comment by mejiaj** [comment]
@amyleadem 

>Lo sentimos, pero no pudimos encontrar la página que busca. Es posible que el administrador del sitio la haya eliminado, movido, o la haya hecho indisponible de otra manera.


Thanks to @ybom for the translation!

**Comment by amyleadem** [comment]
Thanks, @mejiaj. I'll add these changes to PR https://github.com/uswds/uswds/issues/4980
