### ISSUE TITLE
USWDS - Feature: Ability to have <Table/> headers sticky to the top

### ISSUE THREAD

**Issue by etanb** [uswds/uswds#5077]
### Is your feature request related to a problem? Please describe.

For usage of `<Table/>` components with massive data sets, it is hard to remember what each column denotes. Scrolling back up isn't a good solution for 100s of rows of data as you'll lose your place, and converting everything to `stacked` is a huge design change.

### Describe the solution you'd like

An additional CSS utility class like `usa-table--sticky-header` that would have the header information of a table sticky to the top of the page as a user scrolls.

### Additional context

I've created this working solution within the USWDS for review: https://github.com/uswds/uswds/pull/5074

Would love to make this a reality!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by amycole501** [comment]
Sample link created by @amyleadem [https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/al-sticky-table-header/iframe.html?args=&id=components-table--sticky-header&viewMode=story](url) 

I used JAWS to listen to the example sticky header table and before I would say it's accessible, it needs to have the table header row declared as the header row. When I listen to it it doesn't tell me which column the data cells are in. It just reads the cell data out loud and if I couldn't see the table I wouldn't know what the meaning of the data cell is. 
It does say aloud "sticky header" which for someone using a screen reader may not be relevant.
