### ISSUE TITLE
USWDS - Bug: Preview Image ID logic issue

### ISSUE THREAD

**Issue by ajanickiv** [uswds/uswds#5088]
### Describe the bug

If a file takes a long time to load in the file input, the loading spinner is not replaced with a preview image
![image](https://user-images.githubusercontent.com/16595489/209997231-52a56ea6-b0ce-40f7-b114-e583d75ed2ed.png)
This error appears in the console:
`Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at w.onloadend (index.js:292:22)`

### Steps to reproduce the bug

1. Go to [USWDS File input example page](https://designsystem.digital.gov/components/file-input/)
2. Click 'choose from folder' link in file input component
3. Choose a file that will take at least 1 second to load into input - my case is a .xls file greater than 1 MB from a network shared drive
4. File will load, but spinner is not replaced with preview image and error is displayed in console.

### Expected Behavior

The spinner should be replaced with correct preview image and no errors are shown in console.

### Related code

In index.js for the file input, both the `reader.onloadstart` and `reader.onloadend` functions call `createUniqueID(makeSafeForID(fileName))`. This function uses `Date.now()` as part of creating the unique ID for the preview image element. 

If enough time passes between `onloadstart` and `onloadend`, the preview image IDs created don't match. `onloadstart` creates the preview with the spinner, but when `onloadend` queries the DOM to remove the spinner and add the correct preview image, it can't find the preview image element because it is searching with a different ID that the element was created with, thus the spinner isn't removed and an error is thrown because `onloadend` couldn't find the preview image element.
Here is an example using the same code `Math.floor(Date.now() / 1000)`
id created on page load - 
![image](https://user-images.githubusercontent.com/16595489/209999445-8c7100d8-8363-4b07-83d6-2379a0e45cfd.png)
id created 750 ms later using setTimeout - 
![image](https://user-images.githubusercontent.com/16595489/209999872-98549727-82f2-48e9-a9b7-3b7411b17b4a.png)

### System setup

- USWDS Version 3.1.0
- Device: HP Laptop
- Operating System: Windows 10 Enterprise
- Browser: Edge 108.0.1462.54

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mahoneycm** [comment]
I was able to replicate the bug. Moving to ready to schedule!

**Comment by tankurvi** [comment]
I have created PR that has fixes for this issue. 
https://github.com/uswds/uswds/pull/5106
