### ISSUE TITLE
USWDS - Bug: Cant compile Angular application after npm install

### ISSUE THREAD

**Issue by ssgtob1** [uswds/uswds#5097]
## Description

Cant compile Angular application after npm install @uswds and adding to styles.css

1. new angular project
2. npm install @uswds/uswds --save
3. add:
```
@use "uswds-core" with (
  $theme-show-compile-warnings: false,
  $theme-show-notifications: false,
);

@forward "node_modules/@uswds/uswds/packages/uswds/_index.scss";
```

to styles.css
5. add:
```
{ loader: "sass-loader",
          options: {
            sassOptions: {
              includePaths: [
                "./node_modules/@uswds/uswds/packages"
              ],
            },
          },
 },
```
to webpack.config.js
6.  run ng build 
7.  error:
./src/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
2 │ ┌ @use "uswds-core" with (
3 │ │   $theme-show-compile-warnings: false,
4 │ │   $theme-show-notifications: false,
5 │ │ );
  │ └─^
  ╵
  src\styles.scss 2:1  root stylesheet

./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
5 │ @forward "uswds-global";
  │ ^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@uswds\uswds\packages\uswds\_index.scss 5:1  @forward
  src\styles.scss 5:1                                       root stylesheet

## Additional information [optional]
Angular CLI version 13.1.2
NPM version 8.19.2
Node version 18.12.0

**Comment by bjois** [comment]
Were you able to get past this?

**Comment by ssgtob1** [comment]
No I have not

**Comment by bjois** [comment]
The key for me was to add `stylePreprocessorOptions` section to `angular.json` to teach the SCSS compiler to know where to look (More info here: https://angular.io/guide/workspace-config#style-preprocessor-options)

```
"stylePreprocessorOptions": {
              "includePaths": [
                "./node_modules/@uswds/uswds/packages"
              ]
            }
```

In addition, adding the entries to tell USWDS where to look for the `fonts` and `img` to resolve those paths:

adding in the 

```
 "assets": [
      ...
              {
                "glob": "**/*",
                "input": "./node_modules/@uswds/uswds/dist/fonts/",
                "output": "/assets/uswds/fonts/"
              },
              {
                "glob": "**/*",
                "input": "./node_modules/@uswds/uswds/dist/img/",
                "output": "/assets/uswds/img/"
              }
            ]
```

After that, you don't even need to reference the paths explicitly:

```
// styles.scss

@use "uswds-core" with (
    $theme-font-path: "/assets/uswds/fonts",
    $theme-image-path: "/assets/uswds/img"
);

@forward "uswds";
```

Hope this helps. I also went down the webpack route, but no webpack needed!

Everything seems to work including mixins:

```
// Example of mixin usage

@use "uswds-core" as *;

section {
    @include u-border('red-warm-50v');
}
```

**Comment by mahoneycm** [comment]
Hello @ssgtob1,

Were you able to properly compile USWDS styles with @bjois's suggestion?

**Comment by mahoneycm** [comment]
Hello again @ssgtob1,

Just following up again to see if this is still an ongoing issue for you or if you were able to work past it!

**Comment by mahoneycm** [comment]
Closing because this is an Angular compilation error and not USWDS. I was able to resolve using the preprocessor options mentioned above, or by including the required assets locally on my project.
