### ISSUE TITLE
Begin planning for building research panel

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#5101]
Recruiting participants for UX research studies can be time consuming and difficult. We aim to make the effort easier by building a panel of research participants that we can quickly and regularly draw from for research studies involving testing the USWDS website or design system. Please note we do NOT intend to build a participant panel for general end users (i.e. the American public). This panel will consist of users of the design system itself and meant to test the experience of using the USWDS.

**Comment by jaclinec** [comment]
A [rough draft plan](https://docs.google.com/document/d/1CLhSJvLD0VGSaAlWpDTk9RMMF3TY3dWYuVIysaCb3T8/edit?usp=sharing) has been created.

Next steps are to review the plan with the team and see what to put into practice.
