### ISSUE TITLE
USWDS - Feature: WOFF2 only fonts

### ISSUE THREAD

**Issue by scottkellum** [uswds/uswds#5103]
### Is your feature request related to a problem? Please describe.

Allow woff2 font files without the need for woff and ttf to be added as custom fonts.

Looking at caniuse.com US statistics, woff2 support is at 96.57% with generic font-face support at 97.37%. That’s a 0.8% difference.

This difference is mostly made up of legacy IE users, with those browsers supporting woff files. ttf-only web font support is at 0.22%.

As browsers that don’t support woff2 are many many versions old, it might be a better experience to deliver fast-loading local fonts to these legacy machines.

Also note most type foundries are only delivering woff2 now and converting font files is sometimes disallowed in the license.

### Describe the solution you'd like

Deliver woff2 fonts only

### Describe alternatives you've considered

We could leave it as-is

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by mejiaj** [comment]
Merged in #5108.
