### ISSUE TITLE
In-page nav enhancements

### ISSUE THREAD

**Issue by mitchmoccia** [uswds/uswds#5105]
[PR](https://github.com/uswds/uswds/pull/5124)
[Preview](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/mm-in-page-nav-parent-update/iframe.html?args=&id=components-in-page-navigation--default&viewMode=story)

based on feedback from [https://github.com/uswds/uswds/issues/5050 ](https://github.com/uswds/uswds/issues/5050)

**Comment by amyleadem** [comment]
Closing this issue because the feature was added in https://github.com/uswds/uswds/pull/5387
