### ISSUE TITLE
## CARED component evaluation rubric DEMO

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds#5110]
## CARED component evaluation rubric
What we expect and evaluate from any new USWDS component
## USWDS vision
Empowered agency teams sharing solutions, using effective human-centered design practices, and improving the lives of the public.
## Product principles

- Start simple. First solve the problem, then go from there. Favor existing tools.
- Make the easiest thing the best thing. Provide good defaults. Optimize for usability, both on our components and our documentation. Scale expertise by favoring common needs. 
- Avoid lock-in. Favor open formats, modular solutions, and standards-based approaches.
- Be predictable. Be repeatable. Over-communicate, avoid surprises, and support continuous integration. Automate as soon as possible and avoid idiosyncratic custom solutions. Document, follow, and continuously improve repeatable processes.
- Show our work. The process is part of the product. Overdocument and overcommunicate.
## CARED component evaluation rubric
CARED is a simple mnemonic to remember the USWDS component evaluation framework. In general, any component we publish needs to be Clear, Accessible, Resilient, Evidence-based, and Documented.

## Scoring

5 | Exemplary
-- | --
4 | Passes tests / exceeds standards
3 | Passes tests / meets standards
2 | Needs improvement
1 | Does not exist

</div></b>

## CARED Rubric (for USWD core team only)

CARE Criteria | Link to Assessment | Score 
-- | -- |  -- 
Clear | [Assessment](https://github.com/uswds/uswds/issues/5111) | 5
Accessible | [Assessment](https://github.com/uswds/uswds/issues/5111) | 3
Resilient | [Assessment](https://github.com/uswds/uswds/issues/5111) | 3
Evidence-based | [Assessment](https://github.com/uswds/uswds/issues/5111) | 3
Documented | [Assessment](https://github.com/uswds/uswds/issues/5111) | 4

</div><br /></b>

**Comment by brunerae** [comment]
Closing in favor of our Component Lifecycle work. https://github.com/uswds/uswds-team/issues/308
