### ISSUE TITLE
USWDS-Site - External link: fix text-indent

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5115]
I see this section uses `usa-content-list`. The external-link mixin could benefit from this change too

https://github.com/uswds/uswds/blob/69cf6929585b5c95ed9700a4502830f84e497e95/packages/uswds-core/src/styles/mixins/general/external-link.scss#L14

_Originally posted by @mejiaj in https://github.com/uswds/uswds-site/pull/1851#discussion_r1003615987_

**Comment by amyleadem** [comment]
Not able to replicate this issue. I do not see `text-indent` declared in lists in `develop`.

**Comment by amyleadem** [comment]
@mejiaj I created this issue based on a comment of yours, however, after it doesn't seem like text-indent is ever altered or declared for links in `develop`. Do you want me to go ahead and add `text-indent: initial` as a precaution?

**Comment by mejiaj** [comment]
@amyleadem closing this as it no longer applies, this seemed to be a uswds-site issue.
