### ISSUE TITLE
USWDS - Bug: Memorable date component breaks the layout on very narrow screens

### ISSUE THREAD

**Issue by danny-englander** [uswds/uswds#5135]
### Describe the bug

On very narrow screen widths, the Memorable date component breaks the page layout causing side scrolling. 

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/components/memorable-date/
2. use a mobile device of 320 pixels wide or simulate that in responsive browser testing
3. note that the memorable date component goes off screen

### Expected Behavior

Most likely, the fields should stack on narrow screens

### Screenshots

<img width="320" alt="2023-02-06_14-17-42" src="https://user-images.githubusercontent.com/609623/217277319-23296cc1-44d1-429d-a23b-8d41d5aaa610.png">

### System setup

Chrome, Mac OS

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
Confirming that fields start to be cut off at ~435px at default zoom. This could also make fields inaccessible to users who rely on screen magnifiers. 

Labelling this as a possible quick win because it could potentially be solved by adding `flex-wrap: wrap`.
