### ISSUE TITLE
USWDS - Component lifecycle: Define acceptance criteria for each evaluation phase

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5139]
Define what must be done before an item can move to the next (or previous) phase.

Note: Use the [CARED evaluation rubric] (https://docs.google.com/document/d/14V8GEIc3544XJz2RIFJcTQ6G8qa_lbHuo2d6ZsIIHro/edit#heading=h.k7ksyjrv9u1k) as the foundation.

Note: We should consider internal and community audiences

## Some things to consider:
- [ ] Identify which phases need evaluation criteria
- [ ] Identify evaluation criteria for each phase
- [ ] Estimate LOE for each evaluation step
- [ ] Define process style (Asynchronous, hackathon/workshop) and order of operation for each evaluation
- [ ] Define who is responsible for evaluation at each phase

- [ ] Create evaluation checklists by discipline
    - [ ] Accessibility
    - [ ] Content/Guidance writeup
    - [ ] Design?
    - [ ] Development
    - [ ] UX

**Comment by bonnieAcameron** [comment]
@cory-churches and @amyleadem This might be a duplicate issue. This work has been completed and captured in other issues.
