### ISSUE TITLE
USWDS - Component lifecycle: Clarify roles and responsibilities

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5142]
## Tasks
- We need to understand who is responsible for what at each phase. We should consider how much community involvement we want throughout the process.
- Consider identifying members of the core team on our site (or elsewhere) 

## Questions to consider
- Do we create stakeholders by discipline?
- What happens if support disappears or LOE grows beyond expectation?

**Comment by brunerae** [comment]
Closing this during component lifecycle Issue restructure.
