### ISSUE TITLE
USWDS - Component lifecycle: Create high-level outline of UX needs

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5159]
## Task
Create a top-level outline of how UX can fit into the component lifecycle. This can be a simple overview and does not need a lot of detail at this phase.

This outline will inform both our evaluation methodology and the lifecycle flow. 

## Considerations
- In what phases should UX research/testing be integrated?
- What should we evaluate in each phase?
- What resources would we need in each phase? What is the estimated level of effort?

Optional, but it would be great if we could have outlines of both the ideal state and the feasible state given our current resources. If that isn't possible, then just an outline of the feasible state would be great.

**Comment by jaclinec** [comment]
I have started a draft here: https://docs.google.com/document/d/1vy6jljHgPqPeJloiXQNWLxr4At3D7n3X2PlW7pwfjMo/edit?usp=sharing

**Comment by jaclinec** [comment]
Draft is ready for review - please add any comments or questions.

**Comment by jaclinec** [comment]
The draft is ready for another review by one dev (@amyleadem @mejiaj @mahoneycm ), also @amycole501 and @thisisdano : https://docs.google.com/document/d/1vy6jljHgPqPeJloiXQNWLxr4At3D7n3X2PlW7pwfjMo/edit?usp=sharing

**Comment by jaclinec** [comment]
Thanks everyone for your feedback! This document is in a good place and can be considered 'done,' with the understanding that this will be a 'living' document that may evolve over time.
