### ISSUE TITLE
USWDS - Bug: `$theme-card-border-width: 0` results in invalidate `calc` values

### ISSUE THREAD

**Issue by cateprNIH** [uswds/uswds#5162]
### Describe the bug

The card component border width is controlled by the `$theme-card-border-width` Sass variable. Setting this to `0` results in the border radius calc CSS being invalid because `0` does not include a unit of measurement like `0px`.

**Example:**
`border-top-left-radius: calc(.25rem - 0);`
instead of 
`border-top-left-radius: calc(.25rem - 0px);`

### Steps to reproduce the bug

1. Set `$theme-card-border-width` to `0`
2. Compile Sass to CSS.
3. Inspect CSS for a card component in the browser dev tools.
4. The `calc` function is listed as invalid because it does not include a unit of measurement for the `0` value. 

### Expected Behavior

The CSS generated should have a unit of measurement for `0` so any calc functions operate correctly.

### Screenshots

![Screenshot 2023-02-23 at 11 20 30 AM](https://user-images.githubusercontent.com/87388914/220974358-7df31e45-7543-4c88-b2d7-82ffe33f8691.png)
![Screenshot 2023-02-23 at 11 20 36 AM](https://user-images.githubusercontent.com/87388914/220974363-29bceeaf-c7f1-4912-b9f8-a527c2e897f3.png)

### System setup

- USWDS version: 3.3.0
- Device: Macbook Pro
- Operating system: OSX 13.1
- Browser and version: Chrome v110

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by thisisdano** [comment]
We're going to assign severity and complexity in the next phase of triage.

**Comment by mahoneycm** [comment]
Found an additional issue with setting `$theme-card-border` to string tokens (like `"05"`, `"105"`, `"205"`).

The border function error message reads: 
> Accepted values: 1px, 2px, 05, 1, 105, 2, 205, 3, 0

But when setting the variable to any of the string tokens, it breaks the negative margin calculations. 

`@include u-margin-x(-$theme-card-border-width);` is used throughout `_usa-card` exdent variants. This results in 
`-"105"` which breaks the scss because it is not a USWDS unit.

**Comment by mejiaj** [comment]
Additional problems reported in [slack thread](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1689706024819129?thread_ts=1689705029.037649&cid=C3F14AHSQ)

>question: I see the "border width" there, but when I click on units, it takes me to https://designsystem.digital.gov/design-tokens/spacing-units/
>Which lists the units. According to that, `5` is valid. However, it doesn't work when I pass that in
