### ISSUE TITLE
USWDS - Bug: 508 color contrast test for disable buttons

### ISSUE THREAD

**Issue by ttnguyen2** [uswds/uswds#5171]
### Describe the bug

The gray color contrast on the white text of  disabled buttons do not pass508 color contrast test.

### Steps to reproduce the bug

Install ANDI browser plug in to test 508 for a page: https://www.ssa.gov/accessibility/andi/help/install.html
Go to page https://designsystem.digital.gov/components/button/, open ANDI browser tool, on color contrast test on ANDI, it gave errors: 

[Disabled Element Alerts: (1)]
[Page has 8 disabled elements; Disabled elements do not require sufficient contrast.]

### Expected Behavior

Can you update to have the gray background darker to have the disable buttons pass the 508 color contrast test?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
Thank you for flagging this, @ttnguyen2. We are actually already working on a fix for color contrast on our disabled elements (including buttons)! If you want to follow along, you can subscribe to updates for [this issue](https://github.com/uswds/uswds/issues/5051). Let me know if you have any questions!

**Comment by thisisdano** [comment]
Closing in favor of https://github.com/uswds/uswds/issues/5051
