### ISSUE TITLE
USWDS - File input: Evaluate sample label copy

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5211]
# Summary
In the [file input component examples](https://designsystem.digital.gov/components/file-input/), the demo `label` text should be a helpful example that can be used in the real world. However, the sample `label` text in our component demos do not provide particularly helpful information about the related input. For example, the default file input example has a label of "Input accepts a single file". We should evaluate if there is an opportunity to improve this text and provide more helpful real-world examples.

## Expected behavior 
Input `label` elements should describe the purpose of the related input. Additionally, the label can also provide instructions to the user about how to enter information into the input (example: date format type)

**Comment by bonnieAcameron** [comment]
After taking a closer look at this, the texts that say "Input accepts a single file," "Input accepts only specific file types," (and other similar directives on the page) are not actually functioning as labels for the related input. They function as sub-headings within the Component Preview section. 



Proposed solutions:

1. Add "about file input" section similar to what we just drafted in [In page navigation](https://designsystem.digital.gov/components/in-page-navigation/) where we delve a little deeper into the functionality, limitations, and customization possibilities regarding file types. 
2. Consider changing the styling of what are now inaccurately coded as "label" to something like an h2.


I realize this is a bit of a rogue insight @amyleadem , so let's discuss!

**Comment by bonnieAcameron** [comment]
I'll schedule time with you @amyleadem so we can chat about this.

**Comment by bonnieAcameron** [comment]
we decided to go with the H2 solution

**Comment by bonnieAcameron** [comment]
The work is being completed here:
- https://github.com/uswds/uswds/issues/5519 (uswds)
- https://github.com/uswds/uswds-site/pull/2213 (uswds-site)
