### ISSUE TITLE
USWDS - Bug: Tooltip documentation claims the tooltip positioned "top" when not specified; Incorrectly positions bottom left

### ISSUE THREAD

**Issue by danbrady** [uswds/uswds#5218]
### Describe the bug

The [tooltip documentation](https://designsystem.digital.gov/components/tooltip/#using-the-tooltip-component-2) says: 

> By default, tooltips appear on the top of their related element.

and

> * data-position="top": On top, horizontally centered. If the data-position attribute is omitted, the tooltip will appear on top by default.

However, when `data-position` is not specified at all, the tooltip is incorrectly positioned bottom left of trigger.

### Steps to reproduce the bug

1. Create a button with `class="usa-tooltip"` and `title` but no `data-position` attribute.

### Expected Behavior

Tooltip should appear as if `data-position="top"` is set.

### Related code

```
<div class="padding-8">
  <div class="margin-4">
    <button type="button" class="usa-button usa-tooltip" title="Tooltip">Show tooltip</button>
  </div>
</div>
```

[Codepen demo](https://codepen.io/danbrady/pen/QWZwjaN)

### Screenshots

![image](https://user-images.githubusercontent.com/381190/230648182-7bde66e3-dd79-48c3-972b-063322e595c3.png)

### System setup

- 3.4.1
- Desktop
- MacOS 11.7.4
- Chrome v111.0.5563.146 

### Additional context

Would be happy to tackle this if confirmed!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
Thank for taking this on! I can confirm using a tooltip **without** position set results in incorrect placing.

```html
<button type="button" class="usa-button usa-tooltip"  title="No position set on this tooltip">Hello world</button>
```
