### ISSUE TITLE
Review Touchpoints processes

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds#5232]
Confirm how Touchpoints feedback will be handled moving forward.

**Comment by sarah-sch** [comment]
@brunerae - updating the description on this issue so that it is scoped to the current sprint. We discussed at sprint planning at 2/20 that to close this issue we need to confirm what the Touchpoints process will be going forward. Our recollection is that it will be handled the way Zendesk is. Can you confirm that is the plan and who will be the point person or point people on monitoring and responding to feedback?

**Comment by brunerae** [comment]
Hi @sarah-sch / @jaclinec - combing through old GH notifications. Our established process is that, on a monthly basis as part of reporting, I will create Issues for any reported items in Zendesk. I am closing this Issue!
