### ISSUE TITLE
USWDS - Breadcrumb: Override breadcrumb no-wrap on variant

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#5257]
Related to this DigitalGov PR [Refactor breadcrumb component to USWDS #6057](https://github.com/GSA/digitalgov.gov/pull/6057).

**Originally set in default**
https://github.com/uswds/uswds/blob/29eebc4abe3d9c9d968bd3ef54cff9e8add449eb/packages/usa-breadcrumb/src/styles/_usa-breadcrumb.scss#L90

**But not overridden in wrap**
https://github.com/uswds/uswds/blob/29eebc4abe3d9c9d968bd3ef54cff9e8add449eb/packages/usa-breadcrumb/src/styles/_usa-breadcrumb.scss#L193-L202

Resize to 500px~:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3385219/234953565-57aafa38-6e5d-47f6-88fe-ce43d147cdee.png">

**Original link**
[Incorporating user experience practices into data-driven development of a biomedical software tool – Digital.gov](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/nl-refactor-breadcrumb-component/event/2023/05/03/incorporating-user-experience-practices-into-data-driven-development-of-a-biomedical-software-tool/)

**Comment by nick-mon1** [comment]
@mejiaj I'll pick this up since it's related to https://github.com/GSA/digitalgov.gov/pull/6057
