### ISSUE TITLE
USWDS - Bug: Heading order issue with in-page navigation

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#5279]
### Describe the bug

Incorrect heading order on https://designsystem.digital.gov/components/packages/.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/3385219/231802302-61bfc715-5d2c-460a-b92e-5a132298880c.png">

### Steps to reproduce the bug

If you use ANDI you can click on it and show structures then view the headings list

### Expected Behavior

Ideally H1 would be the first heading level on the page. H4 wouldn't show up until an H2 and H3 appear before it

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by amyleadem** [comment]
Closing in favor of https://github.com/uswds/uswds/issues/5488. 
This appears to be a duplicate and #5488 has slightly more detail.
