### ISSUE TITLE
USWDS - Bug: Chrome is removing the lock (https) icon

### ISSUE THREAD

**Issue by gdasher** [uswds/uswds#5283]
### Describe the bug

Google has announced that chrome is removing the lock (https) icon as part of establishing that https is now the default on the web.  As such, the guidance in the banner on many federal websites is misleading.  It currently says:

![image](https://github.com/uswds/uswds/assets/5343613/25d7542a-7e57-490d-ad22-e4b89bef338d)

In the new world, not-secure websites will have a warning: 

https://blog.chromium.org/2023/05/an-update-on-lock-icon.html
https://blog.google/products/chrome/milestone-chrome-security-marking-http-not-secure/

This language should be changed to track the direction browsers are moving as it seems reasonably likely other major browsers will also move in this direction, for example flagging that websites should not have a security warning

### Steps to reproduce the bug

1. Go to many federal websites
2. Expand "How do I know" the site is valid

### Expected Behavior

Explanation is consistent with iconography in the browser.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by thisisdano** [comment]
Yes this is a duplicate.
