### ISSUE TITLE
Explore using SiteImprove on Site

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds#5314]
This ticket will be considered done once we understand if we can add Siteimprove to USWDS and if so, what are the next steps.

**Comment by annepetersen** [comment]
Definitely interested in the result here. If I can be of help figuring it out, let me know.

**Comment by amycole501** [comment]
USA has SI but not GSA as a whole.

**Comment by annepetersen** [comment]
Looking into the use of site scanning tools across TTS, I found this market research: https://docs.google.com/document/d/1hzNRRPL1SiJmw4EpTgXjtaPePnGZ0EFNPRyIWUxV6_Y/edit

Also have a few other leads I'm working on.

**Comment by annepetersen** [comment]
We have access to [AMP](https://gsa.levelaccess.us/), so starting there

**Comment by thisisdano** [comment]
Let's go with what we can learn from AMP and Lighthouse and go from there. I don't think it's worth pursuing siteimprove now

**Comment by annepetersen** [comment]
Turns out I have a path forward through another GSA office, so reopening this long enough to confirm.

**Comment by annepetersen** [comment]
Access granted to myself, @thisisdano, @amycole501, @alex-hull, and @sarah-sch. All set here, I hope! 🎉

**Comment by annepetersen** [comment]
Access granted to myself, @thisisdano, @amycole501, @alex-hull, and @sarah-sch. All set here, I hope! 🎉
