### ISSUE TITLE
USWDS - Bug: Disabled color settings configuration errors

### ISSUE THREAD

**Issue by patrickcate** [uswds/uswds#5334]
### Describe the bug

After upgrading to USWDS version `3.5.0` when I try and compile the Sass, I get the following error:
  
```shell
node_modules/@uswds/uswds/packages/uswds-core/src/styles/functions/utilities/color.scss
Error: "Only use quoted color tokens in USWDS functions and mixins. See designsystem.digital.gov/design-tokens/color for more information."
   ╷
46 │   $value: general.smart-quote($value);
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@uswds/uswds/packages/uswds-core/src/styles/functions/utilities/color.scss 46:11                 color()
  node_modules/@uswds/uswds/packages/uswds-core/src/styles/mixins/helpers/checkbox-and-radio-colors.scss 36:32  -checkbox-and-radio-colors()
  node_modules/@uswds/uswds/packages/uswds-core/src/styles/mixins/helpers/checkbox-and-radio-colors.scss 12:3   checkbox-colors()
  node_modules/@uswds/uswds/packages/usa-checkbox/src/styles/_usa-checkbox.scss 5:1                             @forward
  node_modules/@uswds/uswds/packages/usa-checkbox/src/styles/_index.scss 4:1                                    @forward
  _index.scss 8:1                                                                                               @forward
  _index.scss 4:1                                                                                               @forward
  _index.scss 51:1                                                                                              @forward
  assets/sass/styles.scss 7:1 
```

### Steps to reproduce the bug

1. Compile USWDS Sass with USWDS version `3.4.1` to confirm Sass compiles correctly.
2. Update USWDS to version `3.5.0`.
3. Try compiling USWDS Sass, should receive compiling error.

### Expected Behavior

Sass should compile without errors after upgrading to version `3.5.0`.

### Screenshots

![Screenshot 2023-06-13 at 3 00 50 PM](https://github.com/uswds/uswds/assets/6277206/964a0051-907c-4107-af8f-280b4736217c)

### System setup

**USWDS version:** 3.5.0
**Device:** MacBook Pro
**Operating system:** Mac OS 13.4
**Browser and version:** Chrome 114.0.5735.106

### Additional context

I have tested on 2 separate USWDS projects with version `3.5.0` and both threw the error.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by aduth** [comment]
We're seeing this after upgrading as well. I _suspected_ it might be related to how we customize theme colors to use hardcoded hex values (e.g. something like `@forward 'uswds-core' with ($theme-color-base: '#000');`). I'm still seeing errors after removing those, but they're different, so not confident it's related. But we haven't had any issues in the past, only now with v3.5.0. Unsure if there's a better way to be customizing colors if this is truly the issue.

**Comment by aduth** [comment]
> I _suspected_ it might be related to how we customize theme colors to use hardcoded hex values (e.g. something like `@use 'uswds-core' with ($theme-color-base: #000);`)

On this thought, it can be minimally reproduced with the following snippet, which builds successfully on v3.4.1, but not on v3.5.0:

```scss
@use 'uswds-core' with (
  $theme-color-disabled: #767676
);
@forward 'uswds';
```

It might be related to changes from #5167 (cc @amyleadem).

Looking at how [the `color` function](https://github.com/uswds/uswds/blob/develop/packages/uswds-core/src/styles/functions/utilities/color.scss) is implemented, it might not be intended to support arbitrary hex values for theme color variables (at least not without specific exemption "flags"), but historically this has worked fine, and I'm not sure what the recommended alternative would be.

**Comment by rachidatecs** [comment]
I'm seeing the same issue related to $theme-color-disabled

**Comment by amyleadem** [comment]
Confirming that this issue happens when `$theme-color-disabled` is defined with a hex value in place of a color token.

**Comment by amyleadem** [comment]
Thanks @aduth for the help with troubleshooting. I am able to replicate the error when I change the value of `$theme-color-disabled` to a hex value in place of a color token. 

@patrickcate, @rachidatecs Can you share the value of your project's `$theme-color-disabled` setting? If it is a hex value, can you try switching it to one of the [USWDS color tokens](https://designsystem.digital.gov/design-tokens/color/system-tokens/) and let me know if that resolves the error?

**Comment by patrickcate** [comment]
> Can you share the value of your project's $theme-color-disabled setting? If it is a hex value, can you try switching it to one of the [USWDS color tokens](https://designsystem.digital.gov/design-tokens/color/system-tokens/) and let me know if that resolves the error?

Yes, the `$theme-color-disabled` property is using a hex value. Switching to a color token did fix the Sass compiling error. Not being able to use hex values for the disabled color is inconsistent with the other theme related color values, since I am using hex values for many others like base, primary, secondary, etc.

**Comment by amyleadem** [comment]
Thanks for the information, @patrickcate. I will take a look at what is going on here.
