### ISSUE TITLE
IAAF conference pitch

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds#5341]
Ticket will be considered done once the conference pitch has been submitted to IAAF committee members.
https://docs.google.com/document/d/1mXgEkipnffIx4fxQpPcXj6Zo5aOI6hZBGIL9e0e1BFg/edit?usp=sharing

The deadline for session proposals for the 2023 Interagency Accessibility Forum (IAAF) has been extended to Friday, June 30th, 2023. Please see the attached document for additional information. In your proposal, please include a 

short biography, 
session description,
 learning objectives, 
and your desired session length (45, 60, or 90 minutes)

https://www.section508.gov/iaaf/
If you are interested in presenting a workshop or discussion, please complete the [call for proposals (PDF)](https://assets.section508.gov/files/presentations/IAAF%202023%20Call%20for%20Proposals.pdf) and submit as an attachement to [iaaf@gsa.gov](mailto:iaaf@gsa.gov) by Friday, June 30, 2023.

**Comment by brunerae** [comment]
Closing as complete.
