### ISSUE TITLE
USWDS - Bug: "dot gov" icon is off center

### ISSUE THREAD

**Issue by Gaelan** [uswds/uswds#5352]
### Describe the bug

The icon in [uswds/packages/usa-banner/src/img/icon-dot-gov.svg](https://github.com/uswds/uswds/blob/90a493564c4768baf494fa8946fccef74253f000/packages/usa-banner/src/img/icon-dot-gov.svg) (the "dot gov" icon for the banner component) is not centered within the circle.

### Steps to reproduce the bug

1. Open icon-dot-gov.svg in your image editor of choice.
2. Create rectangles extending from each edge of the central icon to the edge of the circle, like so:
<img width="652" alt="Screenshot 2023-06-23 at 4 22 20 PM" src="https://github.com/uswds/uswds/assets/4495750/a5f452b1-89f6-4e81-b79d-6e06c6b64811">

3. Observe that one rectangle has a higher width than the other one (~18.9 vs ~20.5). It's not vertically centered either (it's too far up), though that might be justifiable as the icon isn't symmetrical vertically.

### Expected Behavior

The icon is centered horizontally, and possibly vertically.

### System setup

* USWDS version: latest "develop" branch. Icon unchanged since at least v3.0.0, the git history gets murky after that.

### Additional context

The other icon in the banner (the https lock icon) is fine.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by patrickcate** [comment]
I can confirm this issue and have created https://github.com/uswds/uswds/pull/5370 with a fix.
