### ISSUE TITLE
USWDS - Bug: usa-icon-list package does not allow '2xs' for $theme-body-font-size variable

### ISSUE THREAD

**Issue by paulathevalley** [uswds/uswds#5357]
### Describe the bug

With the following uswds-theme customization: 

```scss
@use 'uswds-core' with (
  $theme-body-font-size: '2xs'
)
```

The following error appears and the page will not render:
```
  node_modules/@uswds/uswds/packages/usa-icon-list/src/styles/_usa-icon-list.scss 75:13  @forward
  node_modules/@uswds/uswds/packages/usa-icon-list/src/styles/_index.scss 5:1            @forward
  node_modules/@uswds/uswds/packages/uswds/_index.scss 29:1                              @forward
  src/styles/osg.scss 9:1                                                                @use
  src/components/Accordion/Accordion.module.scss 1:1                              root stylesheet
[sass] Undefined operation "false * 1.5".
   ╷
75 │     height: $icon-size * $icon-list-icon-size-factor;
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

### Steps to reproduce the bug

1. In `uswds-theme.scss`, set the following customization: 
```scss
@use 'uswds-core' with (
  $theme-body-font-size: '2xs'
)
```
2. Visit any page in the browser to see this error, although it also appears in the terminal

### Expected Behavior

I expect the page to render.

### Related code

https://github.com/uswds/uswds/blob/218b91a2048074f534f776bdf1369cf51ae96508/packages/usa-icon-list/src/styles/_usa-icon-list.scss#L16-L24

### System setup

- USWDS version: 3.5.0
- Device: Mac
- Operating System: OSX 12.5
- Browser: Safari 15.6, Chrome 114.0.5735.106

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
Confirming that setting `$theme-body-font-size: "2xs"` does cause the error described in the issue description. 

Labelling this as `Needs: Discussion` so that we can discuss why `2xs` and `3xs` were not included in `$theme-body-font-sizes` and the overall impact.

**Comment by amyleadem** [comment]
> **Note**
>There are two solutions currently proposed for this issue:
> - https://github.com/uswds/uswds/pull/5356
> - https://github.com/uswds/uswds/pull/5363
