### ISSUE TITLE
USWDS - Feature: Improve appearance of icons in buttons

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#5359]
### Is your feature request related to a problem? Please describe.

Using `usa-icon` inside of a `usa-button` has alignment issues.

### Describe the solution you'd like

Using `usa-icon` inside of a `usa-button` should be properly aligned.

1. Don't rely heavily on calculations for alignment/spacing.
1. Use simpler selectors (potentially `:has()`).
1. Include a separate story or control for this change.

### Additional context

From PR #4493.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by andycochran** [comment]
It'd be nice it buttons could also use `usa-link--external` and get the external icon inline with the button text.

**Comment by mejiaj** [comment]
@andycochran can you share an example of what you're seeing and the version of USWDS?

**Comment by andycochran** [comment]
Here's what I'm seeing in USWDS 3.12.0 (deployed to the docs site). In the screenshot below, I've added the `.usa-link--external` class to all the default Button elements. Note the differences in the default buttons and secondary buttons: 
- The `launch` icon gets added after the text, but it's not vertically centered 
- `margin-top` on `.usa-link--external::after` makes the Button taller 
- `margin-left` on `.usa-link--external::after` adds `2px` to the space between the text and the icon that Flex already provides

<img width="1442" alt="Image" src="https://github.com/user-attachments/assets/48479e84-7cb1-4de0-b4cd-9fb25b536563" /> 


But perhaps the `.usa-link--external` class is not intended to be used with Buttons? I suppose it is a modifier for `.usa-link` not `.usa-button`. Please let me know if I'm trying to misuse this class. 

If it should be supported, `.usa-button.usa-link--external::after { margin-top: 0; margin-left: 0; }` would fix all of the above.
