### ISSUE TITLE
USWDS - Bug: Header navigation layout broken in Safari desktop just below desktop breakpoint

### ISSUE THREAD

**Issue by rachidatecs** [uswds/uswds#5371]
### Describe the bug

The header navigation is buggy in some systems in Safari just at or below the desktop breakpoint. When you click on "MENU", some parts of the page/nav seem to load mobile styles while others load desktop styles resulting in a broken layout. Tested on [https://designsystem.digital.gov/](https://designsystem.digital.gov/), [https://www.dhs.gov/, https://www.cisa.gov/](https://www.dhs.gov/), [https://www.cisa.gov/](https://www.cisa.gov/), [https://digitalcorps.gsa.gov/](https://digitalcorps.gsa.gov/) (all sites using uswds with the header component relatively out of the box)

### Steps to reproduce the bug

1. Navigate to any uswds website in Safari on a non-mobile device
2. Expand/contrat your viewport to just below desktop breakpoint
3. Click on "MENU"
4. NOTE: See system setup section below. This bug is reproducible on certain systems in Safari, not on others.

### Expected Behavior

The header nav is expected to expand over the content. Instead, on (e.g.) [https://designsystem.digital.gov/](https://designsystem.digital.gov/) the header expands then disappears and the overlay is still active over the content.

### Screenshots
GIF demoes mobile view first, then the problematic ~1024 screen size issue.
![safari-bug (2)](https://github.com/uswds/uswds/assets/107004823/6d1db477-5977-4a15-8c8f-0fc89c9c37c5)

### System setup

**Bug is visible on:**

macOS Ventura 13.4.1
Safari 16.5.1 (18615.2.9.11.7)
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15

macOS Big Sur 11.7.8
Safari 16.5.1 (16615.2.9.11.7, 16615)
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15

macOS Monterey 12.6.7
Safari 16.5.1 (17615.2.9.11.7, 17615)
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15

**Bug not visible on:**
macOS Big Sur 11.7.8
Safari 16.5.1 (16615.2.9.11.7, 16615)
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
Confirming that I was able to replicate this issue at approximately 1009px - 1023px. 

Here are details on my setup:
- MacOS Ventura - Version 13.4.1
- Safari - Version 16.5.2 (18615.2.9.11.10)

**Comment by amyleadem** [comment]
Update:  I am not able to replicate this on the [header component story](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-header--default)  but the error does occur on the [documentation page story](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/al-in-page-nav-parent/?path=/story/pages-documentation-page--documentation-page). 

I believe this points to an issue with how Safari calculates screen width when a vertical scrollbar is present. For example, if you turn on the ruler in the web inspector and set the window to 1009px when the menu is closed, you'll see that the width changes to 1024px when the menu is open.
