### ISSUE TITLE
USWDS-Site - Bug: Input mask example shows wrong cursor on hover

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#5376]
### Describe the bug

Input mask component example shows `cursor: not-allowed` on hover - [component page](https://designsystem.digital.gov/components/input-mask/).

### Steps to reproduce the bug

1. Go to [input mask page](https://designsystem.digital.gov/components/input-mask/).
2. Hover over input in example.
3. Confirm disabled styles are showing.

### Expected Behavior

Disabled styles shouldn't be showing on hover.

### Screenshots

<img width="887" alt="image" src="https://github.com/uswds/uswds-site/assets/3385219/30ff3500-1ba4-41f0-b0c3-516e7993a74e">

### System setup

- USWDS 3.5.0

### Additional context

Only seems to be happening on input mask. Other inputs like [character count](https://designsystem.digital.gov/components/character-count/) are OK.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by amyleadem** [comment]
### Note
- This issue originated from changes in https://github.com/uswds/uswds/pull/5295
