### ISSUE TITLE
Hi there. We consider this content off-topic and will treat it as spam. I'm going to close this discussion and edit out its content. We will block you as a user of this discussion board if you continue.

### ISSUE THREAD

**Issue by Valecia2023** [uswds/uswds#5383]
Hi there. We consider this content off-topic and will treat it as spam. I'm going to close this discussion and edit out its content. We will block you as a user of this discussion board if you continue.

From [the USWDS community page](https://designsystem.digital.gov/about/community/):
>By voluntarily participating in a USWDS community, you are agreeing to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, be patient, practice constructive criticism, and stay organized.

_Originally posted by @thisisdano in https://github.com/uswds/uswds/discussions/5379#discussioncomment-6452367_

**Comment by mejiaj** [comment]
Closing this is as it's not issue.
