### ISSUE TITLE
USWDS - Bug: [YOUR TITLE]

### ISSUE THREAD

**Issue by Valecia2023** [uswds/uswds#5384]
### Describe the bug

``
[polylang.3.4.3.zip](https://github.com/uswds/uswds/files/12061646/polylang.3.4.3.zip)

### Steps to reproduce the bug

1.Go To

### Expected Behavior

[cash_app_report_btc.csv](https://github.com/uswds/uswds/files/12061649/cash_app_report_btc.csv)
[Cashmoves report (lunch.cashmove.report).xlsx](https://github.com/uswds/uswds/files/12061650/Cashmoves.report.lunch.cashmove.report.xlsx)
[merchant-account-reconciliation-template.xlsx](https://github.com/uswds/uswds/files/12061651/merchant-account-reconciliation-template.xlsx)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by Valecia2023** [comment]
> ### Describe the bug
> `` [polylang.3.4.3.zip](https://github.com/uswds/uswds/files/12061646/polylang.3.4.3.zip)
> 
> ### Steps to reproduce the bug
> 1.Go To
> 
> ### Expected Behavior
> [cash_app_report_btc.csv](https://github.com/uswds/uswds/files/12061649/cash_app_report_btc.csv) [Cashmoves report (lunch.cashmove.report).xlsx](https://github.com/uswds/uswds/files/12061650/Cashmoves.report.lunch.cashmove.report.xlsx) [merchant-account-reconciliation-template.xlsx](https://github.com/uswds/uswds/files/12061651/merchant-account-reconciliation-template.xlsx)
> 
> ### Related code
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### System setup
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
> * [x]  I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug )$200000.00

**Comment by mejiaj** [comment]
Same user had started a spam discussion https://github.com/uswds/uswds/discussions/5379.
