### ISSUE TITLE
USWDS - Bug: font-family-size does not set font-family

### ISSUE THREAD

**Issue by hobbez** [uswds/uswds#5385]
### Describe the bug

Setting font-FAMILY-SIZE does not set font-family, only font-size. This is something that worked in 3.4 but no longer in 3.5.

### Steps to reproduce the bug

Set a class of font-family-size; e.g.,:

`<div class="font-mono-lg">Test 123<br>Works in 3.4 but not in 3.5</div>`

### Expected Behavior

font-family-size should set both font-family and font-size

### Additional context

[Slack thread discussion →](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1689607510062829)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mahoneycm** [comment]
Confirming that I was able to reproduce the bug. @mejiaj pointed out that it may be related to the new sass map behavior introduced in `3.5.0`

**Comment by danbrady** [comment]
Curiosity got to me on this. :) We need a small update to point to the right, updated settings  variable. Submitted a PR.
