### ISSUE TITLE
USWDS - Component lifecycle: Integrate CX into phases doc

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5405]
Add customer experience guidance where needed to the component lifecycle phases document.

**Comment by bonnieAcameron** [comment]
Ready for acton: https://docs.google.com/document/d/1TjOjgqX4JEd2jnNMlcHohQWqlFHONID4qVJuUkMNxvA/edit#heading=h.jt35q1w4hkhd

**Comment by amyleadem** [comment]
@bonnieAcameron I just requested access to that doc

**Comment by thisisdano** [comment]
Done!
