### ISSUE TITLE
USWDS - Bug: Unused aria_disabled control on Button storybook preview

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds#5436]
### Describe the bug

The storybook preview for our Button component has a leftover, unused, `aria_disabled` control. The control is only referenced in `usa-button.json` and not included in the template or `argTypes`. Looks like it was leftover after we updated disabled form elements.

### Steps to reproduce the bug

1. Visit button storybook preview
2. Try to enable `aria_disabled` control all button views
3. Nothing changes
4.`aria_disabled` is only mentioned in `usa-button.json`

### Expected Behavior

The `aria_disabled` control was removed from the button story and included in the `all states` display as a part of #5063 and should be removed from the default button `.json` file.

### Additional context

It looks like this was initially removed as a part of 8c0c8b6 but when inspecting the changed files for #5063, `usa-button.json` appears to have been omitted somehow. All of the other variants show as having this removed as a part of this work. It maybe have been replaced accidentally as part of the collaborative work done on that large PR.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
@mahoneycm This appears to be a duplicate of [#5395](https://github.com/uswds/uswds/issues/5395). I recommend we close this issue in favor of that one.

**Comment by mahoneycm** [comment]
Closing in favor of #5395
