### ISSUE TITLE
USWDS - JSON tokens: Confirm that token YML data on uswds-site is accurate

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5439]
## Tasks
- [x] Check data in the data/tokens directory for inconsistencies with uswds
- [x] Identify if there are any gaps between uswds and uswds-site

## Results
[USWDS/USWDS-site token comparison document](https://docs.google.com/spreadsheets/d/1gP8OTD3Od3CuTxkNdc5yiLAovTeyFNG3HD3vJ1AaKLQ/edit#gid=0) (Google sheets :lock:)
- Generally, the structure of the data in the YML files might prove different enough from USWDS to make automated translation to JSON difficult. We should consider manual translation from uswds Sass.
- Some tokens like `$system-spacing` are defined using `spacing-multiple()` in USWDS, but uswds-site uses translated values. This might create complications when moving values into JSON.
- uswds-site YML files are missing some values like "black transparent". There are also other data gaps. We should work to improve the data on site according to the notes in the comparison document.
- It isn't immediately clear what is considered a token. Some of the tokens found in https://designsystem.digital.gov/design-tokens are defined in `uswds-tokens`, some in `uswds-core`. 

## Outstanding questions
- What do we do when tokens in USWDS are defined with USWDS functions (Example: `spacing-multiple()`)?
- Which tokens do we want to convert?

**Comment by mejiaj** [comment]
Closing this issue as we've confirmed that not all tokens are available on site. 

Moving the question for functions to #5507.
