### ISSUE TITLE
CC a11y audit only - typography component

### ISSUE THREAD

**Issue by cory-churches** [uswds/uswds#5445]
Description

Audit the typography component for WCAG compliance and critical checklist checks using three manual accessibility testing methods.
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)

This ticket will be considered done once the following content has been written and associated WCAG checks are in place for the typography component:
WCAG criteria related to [typography component](https://designsystem.digital.gov/components/typography/) elements
How to perform manual testing (critical checklists) and related user-focused questions for downstream teams to test. a. Zoom mag to 200% b. Keyboard c. JAWS The results will be added into the spreadsheet. You can use this document as a starting reference: https://docs.google.com/document/d/1l8KP9A77rg6IF7YME0CvadMMczZKU5FMHvBqkyWFIfM/edit?usp=sharing
[List of all components is here](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

Checklist publishing: https://github.com/uswds/uswds-site/issues/2485

**Comment by amycole501** [comment]
This review is done; however I have several questions such as:
1. Can we include links to the heading style guidance?
2. Can we move typography from a component to a style section?
3. Can we include contrast minimum and other WCAG success criteria as guidance on the page (there is no mention of accessibility in the current version of the page)?
4.  Can we include recommendations for how people with different disabilities experience specific font styles so users can make informed choices as to the font styles they select?
