### ISSUE TITLE
CC a11y audit only - table component

### ISSUE THREAD

**Issue by cory-churches** [uswds/uswds#5450]
Audit the link component for WCAG compliance and critical checklist checks using three manual accessibility testing methods.
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
This ticket will be considered done once the following content has been written and associated WCAG checks are in place for the table component:
WCAG criteria related to [table component](https://designsystem.digital.gov/components/table/) elements
How to perform manual testing (critical checklists) and related user-focused questions for downstream teams to test. a. Zoom mag to 200% b. Keyboard c. JAWS The results will be added into the spreadsheet. You can use this document as a starting reference: https://docs.google.com/document/d/1l8KP9A77rg6IF7YME0CvadMMczZKU5FMHvBqkyWFIfM/edit?usp=sharing
[List of all components is here](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by amycole501** [comment]
Working on documenting WCAG criteria for each table type; standard, scrollable, responsive stacked and sortable

**Comment by amycole501** [comment]
Complete but probably a good idea to review it. There were a lot of moving pieces.
