### ISSUE TITLE
Monthly Siteimprove report review

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds#5453]
Someone on the a11y team will log in monthly and review the Siteimprove report for USWDS. Items to note:
New A or AA issues
New broken links or QA issues
Issues in CSS that affect multiple pages

**Comment by amycole501** [comment]
Documented issues will be stored in [Google drive](https://drive.google.com/drive/folders/1oHPIo2pFbDnwwwXJpEW4IIbC2xHIaIiM?usp=sharing).

issues will be re-tested manually if possible and validated and put into GH for addressing or dismissed as a false positive.

The ideal is to continually improve the score of the site from it's starting point at 87% compliant.

**Comment by amycole501** [comment]
August's report is complete.

**Comment by brunerae** [comment]
Closing as complete.
