### ISSUE TITLE
Create note-taking template for usability testing

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds#5460]
We need a template for taking notes for usability testing sessions. I created a simple [draft of a template ](https://docs.google.com/document/d/1UxPYEltYQCn3QFk1_FT3ywI00b8-6kX12toACwSjask/edit?usp=sharing)here and we can iterate on it as we get more testing under our belt.

It is saved in Research > Usability Testing folder.

**Comment by thisisdano** [comment]
Done!
