### ISSUE TITLE
Research and draft site map and accessibility compliance guidance

### ISSUE THREAD

**Issue by cory-churches** [uswds/uswds#5468]

**Comment by amycole501** [comment]
[Research findings are here](https://docs.google.com/document/d/1sMQIEpWqnKQOeDlETX2ngFbMMQ4L_tjxTf022oS4mp8/edit?usp=sharing).

**Comment by brunerae** [comment]
This research has been completed and is now tracked in https://github.com/uswds/uswds-site/issues/2225
