### ISSUE TITLE
USWDS - Input mask: Remove date story

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5483]
## Summary
Consider removing the input mask date story because input mask cannot successfully validate dates (Example: it is possible to submit 99/99/9999 without error) 

The update should meet the standards outlined in the [Input mask requirements doc](https://docs.google.com/document/d/1kLHaCl5PceSByz0NvZqSc-ot7tSjcbe1EJPbBAZM7LY/edit#heading=h.fa3sv1ray42g) (:lock: Google docs).

We should be able to use the work for this originally done in https://github.com/uswds/uswds/pull/5227.

**Comment by mejiaj** [comment]
Closing because no longer needed.
