### ISSUE TITLE
USWDS - Bug: "format-tokens" script outdated

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds#5486]
### Describe the bug

In our `package.json`, we have a 'format-tokens` script:
```json
"format-tokens": "node ./src/utils/style-format.js --file './packages/uswds-tokens/colors' --output './packages/uswds-core/src/styles/tokens/color'",
```

We no longer have the `style-format.js` util so the script does not work.

### Steps to reproduce the bug

1. On develop, run `npm run format-tokens`
2. Inspect error message

### Expected Behavior

Script should run without error. If it is no longer needed, it should be removed.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
**For discussion**

- [ ] What was this script doing?
- [ ] Can we still use it?
- [ ] Do we want to replace or re-work this script?
- [ ] Refine this issue further

@mahoneycm can you add this to a future dev sync agenda?
