### ISSUE TITLE
Release notes: Track 3.6.1 changelogs and release notes

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5492]
> **Warning**
> The release notes do not include entries for #5502, #5391 or #5461 because they are not user-facing.

# Release notes

# What's new in USWDS 3.6.1

## Bug fixes
Package | A11y | Breaking | Description
:-- | :-- | :-- | :--
`usa-banner` | No | No | **Improved horizontal alignment in the `icon-dot-gov.svg` icon.** (https://github.com/uswds/uswds/pull/5370)
`usa-breadcrumb` | No | No | **Fixed a bug that prevented text from wrapping to a new line in the `.usa-breadcrumb--wrap` variant.** (https://github.com/uswds/uswds/pull/5497)
`usa-card` | No | No | **Fixed a margin bug on header-first variants that caused exdent card media to overlap headers.** (https://github.com/uswds/uswds/pull/5423)
`usa-header` | No | No | **Fixed a Safari-only bug that caused the mobile menu to unexpectedly close at a narrow range of window widths.** (https://github.com/uswds/uswds/pull/5443)
 `usa-modal` | No | No | **Updated how the modal JavaScript resets body padding and improved body padding detection.** Now the component will rely on the CSS to reset body padding rather than injecting an inline style with JavaScript. (https://github.com/uswds/uswds/pull/5493)
`usa-tooltip` | No | No | **Restored the `opacity: 0` style rule to the tooltip body's initial state.** This prevents the component from flickering if its position needs to be recalculated. (https://github.com/uswds/uswds/pull/5475)
`uswds-core` | Yes | No | **Updated radio and checkbox tile styling to have lighter borders.** The border colors now more closely resemble the border colors in release 3.4.0. (https://github.com/uswds/uswds/pull/5494)
`uswds-core` | Yes | No | **Fixed a bug that prevented VoiceOver from reading stacked table content while using Safari.** ( https://github.com/uswds/uswds/pull/5477)

## Dependencies and security

| Dependency name              | Previous version | New version |
| :---------------------------- | :--------------: | :---------: |
|  |  |  |

---

 `[N]` vulnerabilities in regular dependencies (dependencies for USWDS projects installed with `npm install @uswds/uswds`)

 `[N] moderate, [N] high` vulnerabilities in devDependencies (development dependencies)

---

**Release TGZ SHA-256 hash:** ``

**Comment by amyleadem** [comment]
# Release notes template

# What's new in USWDS [N.N.N]

## Features

Package | A11y | Breaking | Description
:-- | :-- | :-- | :--
 |  |  | 


## Bug fixes
Package | A11y | Breaking | Description
:-- | :-- | :-- | :--
 |  |  | 

## Breaking changes

> [!WARNING]

## Dependencies and security

| Dependency name              | Previous version | New version |
| :---------------------------- | :--------------: | :---------: |
|  |  |  |


---

 `[N]` vulnerabilities in regular dependencies (dependencies for USWDS projects installed with `npm install @uswds/uswds`)

 `[N] moderate, [N] high` vulnerabilities in devDependencies (development dependencies)

---

**Release TGZ SHA-256 hash:** ``

**Comment by mejiaj** [comment]
We could remove the entries listed below.


### Button `aria_disabled` note.

This change is also internal and could be removed from the table. The PR itself has a note about not needing documentation.

usa-button | No | No | Removed the outdated aria_disabled data item from the button story. (#5474)
-- | -- | -- | --

---

### Input prefix/suffix

This note can also be removed as it's internal.

usa-input-prefix-suffix | No | No | Removed redundant media query from the input prefix and suffix Sass. (#5433)
-- | -- | -- | --

**Comment by mahoneycm** [comment]
Looks good to me! One optional update to the radio/checkbox tile update to add additional context on _why_ we made this change. Feel free to modify!

### Radio / checkbox tile note

| Package | A11y | Breaking | Description |
|-------|-------|-------|-------|
| uswds-core	| Yes | No | **Updated radio and checkbox tile styling to have lighter borders.** ( #5494) User testing showed this could help with comprehension for users with visual processing disorders. |

**Comment by amyleadem** [comment]
Thanks @mejiaj and @mahoneycm. 
1. I have removed the aria_disabled item for #5474
2. I am a bit conflicted about removing the note for #5433. This change _should_ have no affect on the rendered styles, but it does affect an asset that users will use in their project. I am inclined to leave this change in there _in case_ there are any unintended consequences. Thoughts?
3. For #5494, I am feeling less confident about the connection between lighter borders and visual processing disorders. I'd just like to find more evidence for it before making the claim. A safer explanation is that we are reverting the borders to more closely resemble the border colors in 3.4.0. Thinking it would be wiser to remove all references to VPD for this, at least until we get findings from the a11y team. Any thoughts?

**Comment by mejiaj** [comment]
@amyleadem 

2. At this stage I'd leave it out, but @thisisdano would have final word. I see your point about a user asset. Since it was a duplicate nested media query, there should be no impact. We decided in the PR not to document and not to create a changelog. 
3. That makes sense, but we prioritized based on that visual issue so a note makes sense. If we have an issue to track this confirmation, I'm OK leaving it out. Was this prioritized before confirmation because of the low LOE?

**Comment by amyleadem** [comment]
2. I'll leave it out for now. We can add it back in if necessary. Preserving the code here for quick restoration if desired:
    ```
    `usa-input-prefix-suffix` | No | No | **Removed redundant media query from the input prefix and suffix Sass.** (https://github.com/uswds/uswds/pull/5433)
    ```
3. This was prioritized for a few reasons. We initially started looking into the the tile borders because of a user request stating that they had trouble reading the content when the tile border was present because of visual processing disorder. When we investigated the issue, we noticed that there was a visual regression that inadvertently darkened the borders when we introduced disabled styles in 3.5.0. So we figured the first step was to restore the previous lighter appearance in the hopes that it would reduce visual noise and help users, but I do not have evidence that that actually helps. The primary reason in my eyes is that we wanted to patch the inadvertent change and it was a low LOE.

**Comment by mahoneycm** [comment]
@amyleadem Something to consider, the change to a darker border wasn't completely inadvertent. The darker tile color helped the tiles to pass the color contrast standards, which was the goal of the disabled color contrast PR. 

This is a color contrast analysis as of `3.5.0`. See the Non-text contrast at the bottom of the report:

![image](https://github.com/uswds/uswds/assets/25211650/8fe5553f-4e96-480e-9353-0d7163f57732)

Reverting the color actually dips the color out of the "Non-text Contrast" (AA) standards, but I thought was fine given the visual noise accessibility issue flagged within the PR.

Color contrast analysis after lightening the border:

![image](https://github.com/uswds/uswds/assets/25211650/9a2c4875-1130-4c3c-b169-d86348293aa8)

How do you all feel about this? Part of me thinks the border to pass the contrast limit for UI components, but part of me thinks its ok given it isn't the only UI element for the checkbox/radio button.

Since we gave disabled elements the changelog:
> Form elements with the disabled or aria-disabled attribute now get consistent styling and have proper color contrast 

I see the value in adding a reason for why we reverted the tile color.

**Comment by amyleadem** [comment]
Thanks for the explanation @mahoneycm. In my eyes the border is purely decorative and does not have any meaning that should be conveyed to low-vision users. For that reason I don't think there is a need to meet contrast standards. I'll check in with @amycole501 and @alex-hull to see what they think.

**Comment by thisisdano** [comment]
Closing this. Thanks for the conversation here. I've folded the release notes into the 3.6.1 release PR (https://github.com/uswds/uswds/pull/5532) and the final release notes!
