### ISSUE TITLE
USWDS POAM - October 2023

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5512]

**Comment by amyleadem** [comment]
@mahoneycm assigning this to you as a test for the October milestone. Not sure if it is useful, so feel free to do with it what makes the most sense for you.

**Comment by mahoneycm** [comment]
Sounds good! Should I close it as it was completed already? Or do you want me to keep it open for now?

**Comment by amyleadem** [comment]
Feel free to close it if it is done! What do you think about creating one for the November milestone?

**Comment by mahoneycm** [comment]
Created https://github.com/uswds/uswds/issues/5575 and added it to the November milestone 👍
