### ISSUE TITLE
USWDS - Bug: Input Mask breaks when input is not direct child of form.

### ISSUE THREAD

**Issue by chrislarrycarl** [uswds/uswds#5517]
### Describe the bug

The insert for the generated span to mask the input is currently targeted at the closest form `input.closest(CONTEXT).insertBefore(shell, input);` which works for the [example in the documentation](https://designsystem.digital.gov/components/input-mask/) because the input is a direct child of the form. However, when nested under any additional markup the insert fails (`The node before which the new node is to be inserted is not a child of this node.`).

### Steps to reproduce the bug

1. Create a masked input where the input element is nested in any extra markup that prevents it from being a direct child of the form.
2. Open the page the form is present on.

### Expected Behavior

The input should be masked.

### Related code

`packages/usa-input-mask/src/index.js` line 38 is currently

```
  input.closest(CONTEXT).insertBefore(shell, input);
```

but should be

```
input.parentNode.insertBefore(shell, input);
```

### System setup

- USWDS version: 3.6.0

### Additional context

This issue is [resolved in Version 2](https://github.com/uswds/uswds/pull/5227), however, it's unclear when that will be released so I've submitted a [stand alone PR with only this fix](https://github.com/uswds/uswds/pull/5518) - sorry if this is noise.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
Added tag `Needs: confirmation` so we can properly understand the issue before solutioning.

**Comment by mahoneycm** [comment]
After some troubleshooting with another user on Slack I was able to confirm this issue.

## Steps taken to reproduce

1. Create a form element with multiple input mask elements as direct children of form.
2. Input mask displays as expected.
3. Nest one of the input masks inside of a `<div>`
4. Nested input mask displays as an empty input
5. There is an error in the console.

## Additional context

### Console error

```js
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

### Slack thread
[Public slack discussion →](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1706580032285309)
