### ISSUE TITLE
USWDS - Usability Testing: Banner findings

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds#5530]
## Description

Banner findings, recommendations, and next steps from the [Aug-Sep 2023 Usability Testing Findings Report 🔒](https://docs.google.com/document/d/1z1BRxYZq_m65IdsRKsMzDYSpYYHKsqYgelQe7w_qDUQ/edit?usp=sharing)

## Findings takeaways

2 users were confused by the banner component.

- U7 confused it for a header. She said “I was thinking then that might be more menu options. Because usually any buttons like that that are collapsed at the top of the page like that are usually menu, navigation things.”
- U4 (has some vision) commented that it was another example of something labeled as a button that wasn’t a button. Looks more like a dropdown menu/combobox, or a link.

### 💡 Banner original recommendations:

- We should test this in our next test and gather more data.

### Finding 1: Banner can be confusing to AT users

Is there a difference between banner and how other accordions are read to screen readers?

### Issues

- [ ] Issue

**Comment by simevidas** [comment]
Sorry if I’m chiming in. Have you considered using the `<details>` element to make the banner expandable. Relying on standard elements is generally better for accessibility.
