### ISSUE TITLE
USWDS - Feature: [Add IBM Plex to opensource typeface list]

### ISSUE THREAD

**Issue by mjabbink** [uswds/uswds#5540]
### Is your feature request related to a problem? Please describe.

[Typography ](https://designsystem.digital.gov/components/typography/#included-typefaces)

### Describe the solution you'd like

Including IBM Plex in this list would be amazing. It’s a world class design, with Arabic, Chinese (Q1-2024), Devanagari, Greek, Hebrew, Japanese, Korean, and. Thai). Chinese will have Traditional and Simplified version. We also have aVariable Sans serif. We are in the middle stage of completing Plex Math.
  
IBM Plex is available from [GoogleFonts](https://fonts.google.com/?query=ibm+plex) and [Adobe Fonts](https://fonts.adobe.com/search?query=IBM+Plex).

https://designsystem.digital.gov/components/typography/#included-typefaces

### Additional context

www.ibm.com/design/language/typography/typeface

www.ibm.com/plex

Google legibility knowledge module speaks to details/features that IBM Plex utilizes in its design.
https://fonts.google.com/knowledge/readability_and_accessibility/introducing_accessibility_in_typography

Beautifully Accessible uses IBM Plex as their typeface of choice for their communications on Instagram. Plex also fits into their legibility recommendations [here](https://www.instagram.com/p/CxbDQZRNl-W/?igshid=MTc4MmM1YmI2Ng%3D%3D&img_index=1).

I think you in advance for any consideration on this subject. Feel free to contact me further or our my teammates on the IBM Accessibility team (Phill Jenkins and Michael Gower)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by thisisdano** [comment]
Closing in favor of https://github.com/uswds/uswds/issues/5496. If there's any context in this issue you feel is important, please add it to https://github.com/uswds/uswds/issues/5496.
