### ISSUE TITLE
USWDS - Bug: theme-site-margin-width unit won't compile

### ISSUE THREAD

**Issue by arkjoseph** [uswds/uswds#5559]
### Describe the bug

According to Units docs, a value of 6 can be expected while compiling 
https://designsystem.digital.gov/design-tokens/spacing-units/#spacing-unit-tokens-2

The value of 6 for 
$theme-site-margins-width is being rejected

### My entry point
`@forward "uswds-theme";
@forward "uswds-theme-custom-styles";
@forward "uswds-global";`

### Steps to reproduce the bug

1. go into _uswds-theme.scss

`@use "uswds-core" with ($theme-site-margins-width: 6)`

results in 
`Error: "`12` is not a valid `padding` token. You should correct this. Standard `padding` tokens:  1px, 2px, 05, 1, 105, 2, 205, 3, 4, 5, 6, 7, 8, 9, 10, 15, 0"╷ 19 │     padding-left: get-uswds-value("padding", $value...) #{$important};
   │                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

### Expected Behavior

3.0.2 of framework accepted the unit as 6 (48px or 3rem)  
This is the continued expected behavior of the unit of 6 for $theme-site-margin-width

### Screenshots

![Screenshot 2023-10-12 at 12 31 26 PM](https://github.com/uswds/uswds/assets/4149649/0345c669-b178-42ad-b8ca-90064c7aaeaa)

### System setup

- 3.6.1
- GULP Compile method

### Additional context

Current 3.0.1 uswds site-margin-width was 6 / 3rem.  Grid container 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
Confirming that this error occurs with values that do not create standard units when multiplied by 2. Likely related to [this line](https://github.com/uswds/uswds/blob/develop/packages/uswds-core/src/styles/mixins/helpers/alert-status-styles.scss#L93) in alert styles.
