### ISSUE TITLE
USWDS - Bug: Google Chrome and MS Edge crash when VoiceOver cursor interacts w/process list counter 

### ISSUE THREAD

**Issue by mirrorstage** [uswds/uswds#5562]
### Describe the bug

- Given a session where I am using Google Chrome or Microsoft Edge, and have the MacOS VoiceOver screenreader active 
- When I traverse a web page using VoiceOver's keyboard navigation and encounter a Process List counter component
- Then the browser crashes with "Error Code 11"
- Does not occur on Firefox 118.0.2 (64-bit) or Safari 17.0 (18616.1.27.111.22, 18616)

### Steps to reproduce the bug

1. Use a MacOS device
2. In Chrome or Edge, go to https://designsystem.digital.gov/components/process-list/
3. On the MacOS device, activate VoiceOver 
4. Using VoiceOver's navigation keys, traverse the page until you reach the "Component Preview" section
5. Continue into this section until the screenreader focuses on and announces the 3-item list (e.g., the first Process List example on the page)
6. Navigate with VoiceOver past the list element to the first item in the Process List
7. Browser crashes

### Expected Behavior

VoiceOver would announce the name, role, and other relevant properties of the first Process List item, and the browser would not crash

### Screenshots

In the attached screen capture, I am using Google Chrome. The focus is on the Component Preview element. I move the focus forward with tab, then back with shift-tab, then navigate into the Process List itself using VoiceOver navigation.

https://github.com/uswds/uswds/assets/6709726/457b8b3e-b9b7-4c06-9fd1-74fd6cf51cb3

### System setup

* Device: 2023 MacBook Pro M2 Max
* OS: Ventura 13.6
* Browsers: 
  * Chrome: 118.0.5993.70 (Official Build) (arm64)
  * Edge: 18.0.2088.46 (Official build) (arm64)

### Additional context

I originally discovered this on a CDC web application that I contribute to: https://training.simplereport.gov/app/results/upload/submit?facility=45b96eb2-1df1-46a0-a0a5-824f6a1e283f

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by werdnanoslen** [comment]
Confirmed by multiple people on my team on mac v14 Chrome v118.0.5993.70. Works fine on Safari and Firefox
![confirmed](https://github.com/uswds/uswds/assets/764090/aead7080-0dd7-4afe-bd68-882038f87e07)

**Comment by jaredcunha** [comment]
I can confirm this is happening. I was just about to write the same ticket.

**Comment by mirrorstage** [comment]
I found it in our app a few weeks ago, just got around to writing it up. 

Yes, also found in Edge.

**Comment by jaredcunha** [comment]
Could be a browser issue. I've noticed that if I disable all instances of `display: flex` on `.usa-process-list__item::before`, the behavior no longer occurs.

I'm using the latest Chrome build, but it has happening before I updated it.

**Comment by jaredcunha** [comment]
I tested the pen in Chrome Canary and the issue was NOT occurring, so I guess help is on the way!

**Comment by mirrorstage** [comment]
Checked on https://designsystem.digital.gov/components/process-list/ with latest versions (below). Traversing the process list items no longer causes the browser to crash. Closing.

* Google Chrome, 118.0.5993.88 (Official Build) (arm64)
* Microsoft Edge, Version 118.0.2088.57 (Official build) (arm64)
