### ISSUE TITLE
Header Initialization/FocusTrap in Angular App

### ISSUE THREAD

**Issue by ajanickiv** [uswds/uswds#5570]
## Description

This is probably more of a question than an issue

### Details
Angular 16 application
USWDS 3.6.1
Issue: FocusTrap is null and causes the following console error when clicking the Menu or Close button in Mobile mode.
![image](https://github.com/uswds/uswds/assets/16595489/05a48311-e678-4a56-8a06-7680f635919c)

### Background
In an Angular App, USWDS JS is loaded in the `scripts` array in the `angular.json` file like this:
`"scripts": [
    "node_modules/@uswds/uswds/dist/js/uswds-init.min.js",
    "node_modules/@uswds/uswds/dist/js/uswds.js"
]`

When the Angular App starts up the navigation module `init()` methods runs before Angular has bootstrapped the application.

USWDS navigation module init function

```
init(root) {
      const trapContainer = root.matches(NAV) ? root : root.querySelector(NAV);

      if (trapContainer) {
        navigation.focusTrap = FocusTrap(trapContainer, {
          Escape: onMenuClose,
        });
      }

      addSafariClass();
      resize();
      window.addEventListener("resize", resize, false);
    }
```

This leads to the `trapContainer` being `null` since there is no DOM content and it is querying for the `usa-nav` class. Therefore the setting of `navigation.focusTrap` does not occur and `focusTrap` is `null`.

Later when the user interactions with the MENU or X button in the mobile menu, the `toggleNav` logic is called.

```
const toggleNav = (active) => {
  ...
  navigation.focusTrap.update(safeActive); // focusTrap is null so error fires in console and the focus is not trapped to the MENU or X button
  ...
}
```

Is there a way to reinitialize the `navigation` object and it's `focusTrap` after the dom is populated with content?

I have tried calling `navigation.init()` in my Angular component like shown [here](https://designsystem.digital.gov/documentation/developers/#js-customization-2) but that seems to create another instance of the `navigation` object, not overwrite the initial `navigation` object that has `focusTrap` equal to `null`.

**Comment by mahoneycm** [comment]
Hello @ajanickiv,

Just confirming I was able to successfully recreate this issue. I tried experimenting with different [Angular hooks](https://angular.io/guide/lifecycle-hooks#lifecycle-event-sequence) to see if I could get it to initialize after the content is loaded, but I was unsuccessful. Have you tried any other hooks?

Since our team doesn't work with Angular regularly, you may have some luck reaching out to other users on the public Slack channel. If you aren't already on the channel, you can join using the [sign-up form](https://chat.18f.gov/).

Another helpful resource may be GSA's [Angular USWDS repo](https://github.com/GSA/ngx-uswds).

I'll bring this up for discussion with the rest of the devs to discuss if there's an underlying issue on the USWDS end that might help to resolve this!

**Comment by ajanickiv** [comment]
I have tried different Angular lifecycle hooks, but that doesn't solve the actual problem, which is to reinitialize the original navigation object so the `trapContainer` is no longer `null`. The GSA's header component didn't shed any light. I will inquire in the Slack channel next.

**Comment by ajanickiv** [comment]
Recap: When clicking the Menu or Close buttons in the Header menu when in mobile mode, the focusTrap is null and this error fires in the console: Uncaught TypeError: Cannot read properties of null (reading 'update') at HTMLButtonElement

**Solution**
The USWDS JavaScript needs to be loaded _after_ the Angular App is bootstrapped and the DOM creation starts.

**Part 1**
In `angular.json` in the `scripts` area where the USWDS JavaScript is defined, add `inject: false` and a `bundleName`. This will stop the JavaScript from loading initially, allowing it to be loaded manually later after the DOM creation starts.
```
"scripts": [
    {
        "input": "node_modules/@uswds/uswds/dist/js/uswds.min.js",
        "inject": false,
        "bundleName": "uswds"
    },
    "node_modules/@uswds/uswds/dist/js/uswds-init.min.js",
]
```
After making this change, be sure to build the project, typically done by running the `ng build` command.

**Part 2**
The USWDS JavaScript needs loaded manually since `inject` was set to `false`. There are a variety of ways to do this. The simplest I found was to load it with a `<script>` tag in the `index.html`, setting `src` to the `bundleName` + '.js'.
```
<body>
   <app-root></app-root>
   <script src="uswds.js"></script>
</body>
```

This loads the USWDS JavaScript after the DOM creation starts, allowing the focusTrap code to work and no errors in the console.
![image](https://github.com/uswds/uswds/assets/16595489/72827cec-f23a-4447-a061-d7cb6be3ded8)

**Comment by mahoneycm** [comment]
@ajanickiv Thank you for providing your solution! So glad you were able to sort it out. No doubt we'll return to this if other people run into JS issues with Angular + USWDS 😄
