### ISSUE TITLE
Character count: Lightweight landscape analysis to understand the implications of implementing a 'hard cutoff'

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds#5573]
Recent usability testing revealed that 3 participants prefer a hard cutoff when they have exceeded the character limit. In other words, they prefer the system to stop allowing them to type characters. 

It is unclear if the best solution is to prevent users from typing, and we want to better understand the implications of implementing such a solution. We will look at a few other design systems to discover accepted conventions for hard cutoffs in character counts.

**Update:**

Creating a new issue based on the landscape analysis findings and team discussion:

- [x] #5625

**Comment by jaclinec** [comment]
Here is the draft of the [lightweight landscape analysis](https://docs.google.com/document/d/1vu8-BZ4hlnDO68HtAnuKRtFbtB2FxlqsBGOlq7g6-yw/edit?usp=sharing). :lock:

It's a work in progress.

**Comment by jaclinec** [comment]
## Character count lightweight landscape analysis ([See report](https://docs.google.com/document/d/1vu8-BZ4hlnDO68HtAnuKRtFbtB2FxlqsBGOlq7g6-yw/edit?usp=sharing) :lock:)
Q4 2023
### Research questions and approach: 

What is the convention to use when a user exceeds the character count limit? Specifically, s**hould the component prevent typing once a limit has been reached, or allow users to exceed the limit?** What solutions exist in other design systems?

I checked various design systems indexed in this [Design System Gallery](https://component.gallery/design-systems/).

I also did search engine keyword searches. Keywords searched:

- Character count & [design system, or name of specific design system like Carbon]
- Character count exceed limit
- Character count max limit

### Key findings
**There does not seem to be a universally adopted convention when it comes to exceeding character count limits.** Some design systems allow the hard cutoff (3 in our sample) and some claim you should allow users to exceed the limit (4 in our sample) but give proper feedback.

Of those design systems that allow users to exceed the limit (Gov.uk Design System and Digital Scotland Design System), **the rationale was that allowing users to exceed the limit “is non-destructive, so users can enter or paste too much data and get a warning instead of losing any of it.”**

### Recommendation 
**Character count should allow users to exceed the limit; however, we should implement additional visual AND audible feedback to users once they reach the limit.** For instance, an audible ‘ding’ coupled with the outlining the character count box in red. 

This solution could address the issue the visually impaired research participants in recent usability testing had about exceeding the limit without knowing it and having to go back to edit their text, which some said was annoying.

### Details: Design systems’ character count solutions
**NOTE:** Many design systems reviewed did not address character count at all or did not offer guidance specific to our research questions. Examples include: Atlassian, Dell Design System, Polaris, Material Design, and more.

[**Gov.uk Design System**](https://design-system.service.gov.uk/components/character-count/#:~:text=a%20character%20count.-,How%20it%20works,-It%20tells%20users)
Prevents typing? NO

“This component does not restrict the user from entering information. The user can enter more than the character limit, but are told they’ve entered too many characters. This lets them type or copy and paste their full answer, then edit it down.”

[Gov.uk research findings:](https://github.com/alphagov/govuk-design-system/wiki/Character-count-testing-and-user-research#the-research-findings:~:text=The%20research%20findings)
“Some users only acknowledged the character count after they had gone past the set limit or when an error message prompted them after they clicked 'continue'. However, both groups were able to amend the amount of characters they had put in and continue with the task.

We feel this is acceptable, as drawing too much attention to the component may actually distract users from completing their primary task.”


[**Carbon Design System**](https://carbondesignsystem.com/components/text-input/usage/#character-counter) 
Prevents typing? YES

“Once the max number of characters is reached the text area should prevent the user from entering any additional character and provide messaging to the user that a limit has been met.”


[**Goldman Sachs**](https://design.gs.com/components/input/text-area#status)
Prevents typing? UNCLEAR

Does not address exceeding limits, but offers error state:


[**Polaris**](https://polaris.shopify.com/components/selection-and-input/text-field?example=text-field-with-character-count#:~:text=Text%20field-,Text%20field,-A%20text%20field)
Prevents typing? YES

They do not offer any guidance for it, but the component preview prevents typing once you exceed the limit.


[**Atlassian**](https://atlassian.design/components/textfield/examples#max-characters)
Prevents typing? YES

“Text fields can be set with a maximum character limit for constraining the amount of content that can be entered. Inline validation can also be set to alert the user and clarify the request.”


[**Ontario Design System**](https://designsystem.ontario.ca/components/detail/text-inputs.html#:~:text=Don%27t%20do%20this%3A-,Do%20not%3A,-limit%20the%20number)
Prevents typing? UNCLEAR

They don’t directly address it. They do recommend against using character limits at all.

“Do not:
limit the number or type of characters the user can input
instead, give clear instructions and/or an error message if needed”


[**Digital Scotland Design System**](https://designsystem.gov.scot/components/character-count)
Prevents typing? NO

“Using the character count component is better than simply using a maxlength attribute on the input element, because:
it is non-destructive, so users can enter or paste too much data and get a warning instead of losing any of it
users can see how many characters they have remaining as they type”

They offer more guidance on implementation:

“A character limit can be set in two ways:

1. Maxlength attribute. Use a maxlength attribute on the input element. This progresive enhancement is the most user-friendly way to do it because if for any reason the component is not initialised the character limit will still be imposed. The maxlength attribute is removed when the component initialises to allow the user to overflow the input without losing any of their input data. They will instead be shown a warning that they have exceeded the character limit.
2. data-maxlength attribute. Using a data-maxlength attribute to specify the character count behaves largely the same way as using a maxlength attribute, but without the fallback to using the native behaviour for an input field with a maxlength.”


[**SKY UX** (Blackbaud)](https://host.nxt.blackbaud.com/skyux/components/character-count?docs-active-tab=design)
Prevents typing? NO

Note: They don’t offer guidance or reasoning for allowing users to go over the limit.



[**Newskit**](https://www.newskit.co.uk/components/character-count/#:~:text=input%20attribute%20types.-,States,-The%20character%20count)
Prevents typing? NO

Note: They don’t offer guidance or reasoning for allowing users to go over the limit.

**Comment by jaclinec** [comment]
This issue is ready for review. Would like to have 1 person from the a11y and engineering practice areas take a look. @amycole501 @alex-hull @amyleadem @mahoneycm @mejiaj

**Comment by amycole501** [comment]
Character count overview and issue identification was great as was the landscape analysis. 

1. I like the audible "ding" suggestion for all users to be notified if typing past the limit. 

2.  If a person is copying and pasting into the text box: (we might want to test this)
If there's a way to warn someone "the character limit has been exceeded" BEFORE the person pastes in text that would be great. Is that possible? It would be an error prevention technique. Like a pop up box that says "Pasted text exceeds limit" then a "paste anyway" or "cancel paste" option. Then a person can go in and make edits in the text box if they choose to paste the text. It would also give the person an option to continue editing in another program if they're pulling text out of another platform. 

3. One thing we may not have tested is how error handling occurs. CAN a person hit "submit" and only the content up to the limit is submitted? Or if they hit submit, does the character count error out until the person only has the amount of text allowed in the box?

**Comment by mahoneycm** [comment]
I'm a big fan of Twitter's implementation of Character Count. 

- Allows you to overflow text count
- Offers two clear visual indications that the user has exceeded the limit
   - Red highlight text
   - Red, negative character count value
- Clear readouts for screen readers letting users know how many characters they are over the limit.

![image](https://github.com/uswds/uswds/assets/25211650/33f3d806-c936-436b-b2e6-149ecb35f69f)

Rather than disabling the post button, I would allow users to click post, then return an error message or alert explaining once again that the user is over the character limit.

Addressing @amycole501's # 2 & 3 points:

2. I believe this would be possible with some JavaScript but I wonder if that is too disruptive and/or distracting for users. As mentioned in some of the other design systems, it may be better to allow users to paste it in order to not lose the data, then refine their answer.

3. I'm also curious if the text area will cause an error in a form. From MDA:

> The input will fail constraint validation if the length of the text value of the field is greater than maxlength UTF-16 code units long. Constraint validation is only applied when the value is changed by the user.
>
> ...should the length be longer than the maxlength allows, the read-only [tooLong](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/tooLong) property of a [ValidityState](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState) object will be true. [^1]

> **tooLong**: A boolean value that is true if the value exceeds the specified maxlength for [HTMLInputElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) or [HTMLTextAreaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement) objects, or false if its length is less than or equal to the maximum length... If true, the element matches the [:invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid) and [:out-of-range](https://developer.mozilla.org/en-US/docs/Web/CSS/:out-of-range) CSS pseudo-classes. [^2]

[^1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength#:~:text=While%20the%20browser%20will%20generally%20prevent%20user%20from%20entering%20more%20text%20than%20the%20maxlength%20attribute%20allows%2C%20should%20the%20length%20be%20longer%20than%20the%20maxlength%20allows%2C%20the%20read%2Donly%20tooLong%20property%20of%20a%20ValidityState%20object%20will%20be%20true.
[^2]: https://developer.mozilla.org/en-US/docs/Web/API/ValidityState#:~:text=CSS%20pseudo%2Dclasses.-,tooLong,-Read%20only

**Comment by jaclinec** [comment]
I presented this to Dan in our 1:1 and he liked the idea of implementing the audible 'ding' as well. We agreed that it should only ding once when the user exceeds the limit, but not keep dinging every time they enter a character over the limit.

We also both like the red highlights of the exceeded text from Twitter's example while also highlighting the box in red.

As for Amy's questions:
2. I agree with Charlie that this could be too distracting for users and think its probably fine to try our other solutions first to see how they perform.
3. I imagined it would trigger an error message upon hitting submit if the limit is exceeded, rather than submitting whatever text fits up to the limit (cutting the rest off). I think that also provides a better experience - allowing the user to correct the field so they don't unintentionally submit something incomplete (which could have consequences like delaying a process for them...like delaying getting govt benefits or something).

Requesting a review from @annepetersen

**Comment by mahoneycm** [comment]
In practice, would a ding be enough for users to understand they have hit the limit? In my opinion, the ding should be accompanied by a message stating that the user is over the limit. Perhaps ding during texting and have the message once the user stops?

**Comment by jaclinec** [comment]
@mahoneycm Yes absolutely, the ding would be followed by a message that they have gone over the limit. It should already be announcing how many characters left, and how many they've gone over. But for 'fast typers' who do not wait to hear that feedback, the ding could give them pause so they could stop to hear it.

**Comment by annepetersen** [comment]
Thanks for this analysis and discussion: the Q&A following was also super helpful to clarify the intended implementation. Worth prototyping and testing at this point, I think!

**Comment by jaclinec** [comment]
Creating a new issue based on our discussion and next steps we need to take: 

- [ ] Character count: Implement audible cue, such as a ding, when character limit is exceeded
