### ISSUE TITLE
USWDS - Alert/Site alert: Fix content alignment issues 

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5583]
## Summary
When `$theme-site-margins-width` receives custom values, it can cause the the content inside the alert component to overlap or become misaligned with the banner and other components. For example, setting `$theme-site-margins-width: 1px` results in the following:

![image](https://github.com/uswds/uswds/assets/93996430/b9f74c14-2329-4901-9f8b-a14495bbd2a5)

Setting the value to `$theme-site-margins-width: `15` results in the following:

![image](https://github.com/uswds/uswds/assets/93996430/e9688191-8a08-464a-858a-c70c1719f914)

And `$theme-site-margins-width: `6`:

![image](https://github.com/uswds/uswds/assets/93996430/f118d56f-58ea-479a-be0b-2cd9d404c7ac)

We should recalculate the padding and margins on this component so that they consistently align with the other components that use  `$theme-site-margins-width`.

**Comment by mejiaj** [comment]
Realistic example on [USWDS Site - Implementations](https://designsystem.digital.gov/documentation/implementations/).

**Desktop view**
<img width="1900" alt="image" src="https://github.com/uswds/uswds/assets/3385219/87e768d0-5873-4a64-b196-15a11c7ee784">
