### ISSUE TITLE
USWDS - Feature: Only build in-page nav when content headers are present

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5610]
## Problem summary
When there are no h2 or h3 headers in the main content region on a page, the in-page navigation component builds out with empty content. It shows only the "On this page" header and the link section has no content. This can be confusing to users who might think the component is broken. 

![image](https://github.com/uswds/uswds/assets/93996430/b339374c-a6bb-4ccb-8b3c-e2fa52e67f00)

## Describe the solution you'd like
The in-page navigation component should be be added to a page _only_ when the designated content section has headers that will be pulled into the component. 

For example, with the default configuration, the in-page navigation component should only be added to the page when there are `h2` and/or `h3` headers in the `<main>` element. 

## Resources
Related to this [question in ZenDesk](https://gsa-solutionshelp.zendesk.com/agent/tickets/14331) (🔒).

**Comment by brunerae** [comment]
This can be closed in favor of #5967
