### ISSUE TITLE
Unlocking the power of accessibility research - Fable training

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds#5613]
This ticket will be considered done once the recordings have been watched and notes taken.

Fable webinar recording: [https://vimeo.com/882235044/3b3f6d7412?share=copy](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvimeo.com%2F882235044%2F3b3f6d7412%3Fshare%3Dcopy&data=05%7C01%7Camy.cole%40bixal.com%7C628a7b358c04456b4ab708dbe09d27ee%7C31448150d5ea4e0ebf6351be057306d3%7C0%7C0%7C638350737818410175%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kWNdXDJm5%2BOaQomDrCJV3Tl73Y%2B3RTjhDSXnWWIAzPM%3D&reserved=0)
Fable usability session: [https://vimeo.com/882602500/b6e4b83816?share=copy](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvimeo.com%2F882602500%2Fb6e4b83816%3Fshare%3Dcopy&data=05%7C01%7Camy.cole%40bixal.com%7C628a7b358c04456b4ab708dbe09d27ee%7C31448150d5ea4e0ebf6351be057306d3%7C0%7C0%7C638350737818410175%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9k0%2F1mclqkwZ02BCSC1bjNV1EhN%2FcsQjwidb3iWd1Iw%3D&reserved=0)

**Comment by amycole501** [comment]
Really insightful! https://docs.google.com/document/d/1qE0AF0gAiNxEUOL0llDnCkPzVQC8RJFXtTlGPPnKkgc/edit?usp=sharing

Got tips on how to conduct ux research with disabled participants as well as usability and accessibility pointers for websites from an experienced AT user and tester.

**Comment by brunerae** [comment]
Closing as complete.
