### ISSUE TITLE
USWDS - Bug: USWDS Not Loading Open Sans fonts

### ISSUE THREAD

**Issue by cfarmer-fearless** [uswds/uswds#5623]
### Describe the bug

I'm building a React component library using Vite and USWDS, similar to [react-uswds](https://github.com/trussworks/react-uswds).  I would like to use open sans for my fonts, which I understand is provided by USWDS.  I've followed the steps on the USWDS design token docs for using this font.

First, I set up Sass and created a uswds-theme.scss file and put the following in it:
```Sass
@use "uswds-core" with (
  $theme-font-type-cond: false,
  $theme-font-type-icon: false,
  $theme-font-type-lang: false,
  $theme-font-type-mono: "roboto-mono",
  $theme-font-type-sans: "open-sans",
  $theme-font-type-serif: "merriweather",
  $theme-font-role-ui: "sans",
  $theme-show-notifications: false
);
```
Next, in my global sass file, I have the following:
```Sass
@forward "uswds-theme";
@use "uswds-core" as *;

:root {
  @include u-font-family("sans");
}
```
When I open my project in the browser, I expect open sans fonts to be rendered.  Indeed, I am seeing the open sans font stack in my browser dev tools
<img width="613" alt="image" src="https://github.com/uswds/uswds/assets/98106992/f7b065b7-6170-4473-a33d-7bd8acacde79">
But the actual rendered font is not open sans
<img width="613" alt="image" src="https://github.com/uswds/uswds/assets/98106992/079fe71a-1caa-43b2-ab7a-2f3e3bf543a6">

I noticed that open sans is not part of the sets of fonts that ship with USWDS.  What else do I need to do to use the open sans font with USWDS?

### Steps to reproduce the bug

1. Install Vite
2. Create a new Vite project with the react-ts template
3. Install USWDS as a dependency
4. Install Sass as a dependency
5. Add the following to the vite.config.ts
```
css: {
    preprocessorOptions: {
      scss: {
        includePaths: ["./node_modules/@uswds/uswds/packages"],
      },
    },
  },
```
6. Create a _uswds-theme.scss and global.scss file
7. Set these two files up as described above
8. Run the app with `npm run dev`
9. Open the app at http://localhost:5143
10. Open the browser dev tools and inspect the computed styles

### Expected Behavior

The browser loads open sans font files from the network instead of local .SF NS files.

### System setup

- USWDS version 3.5.0

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mahoneycm** [comment]
Hello @cfarmer-fearless !

We've had users experience similar issues with other frameworks such as their image or font paths not being referenced correctly. If you aren't using USWDS-compile, you'll need to make sure your fonts are being added to your project correctly.

One [user](https://github.com/uswds/uswds/issues/5097#issuecomment-1402984849) achieved this in Angular by setting their asset paths:

```
 "assets": [
      ...
              {
                "glob": "**/*",
                "input": "./node_modules/@uswds/uswds/dist/fonts/",
                "output": "/assets/uswds/fonts/"
              },
              {
                "glob": "**/*",
                "input": "./node_modules/@uswds/uswds/dist/img/",
                "output": "/assets/uswds/img/"
              }
            ]
```

Unfortunately, our team isn't very familiar with Vite, but I did find a discussion on their GH where another user was trying to get assets from node_modules: https://github.com/vitejs/vite/discussions/13138#discussioncomment-5858583

If you'd like, feel free to join our [public Slack](https://chat.18f.gov/) channel. There you might be able to connect with other USWDS + Vite users who may assist you better. For more information visit the [USWDS Community](https://designsystem.digital.gov/about/community/) page.

Let me know if these methods work for you or if there's anything else I can assist you with!

**Comment by brunerae** [comment]
Going to update our site documentation to include more information about preventing this sort of issue. @mahoneycm / @brunerae will add link to new Issue once defined and we'll close this Issue.

**Comment by mahoneycm** [comment]
Tracking documentation issue here: https://github.com/uswds/uswds-site/issues/2472

Closing as this is likely not a USWDS issue.
