### ISSUE TITLE
Web Components: Define implementation of web components for design system

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#5640]
## Done when

- [x] Comparative analysis of native, open wc, lit, and stenciljs.
- [x] Outline pros/cons and impact on codebase
- [x] Understand impact to product values
- [x] Create Issues for discrete next steps and document in https://github.com/uswds/uswds-team/issues/312

Compiling in [Google Doc](https://docs.google.com/document/d/1exZtf3Hn4XDw8aytJVtUi2dnhJ5SWxfBtdXVn7CG3S4/edit#heading=h.fa3sv1ray42g) [🔒]

**Comment by aduth** [comment]
In trying to follow the related issues, it's unclear to me if these are the only options being considered for web components? I'd be curious if there was consideration of using the raw native APIs for web components, which could help avoid the overhead of a framework or vendor lock-in.

In an earlier comment at https://github.com/uswds/uswds/issues/3445#issuecomment-674060672, I'd also prototyped an example "Custom elements implemented using Preact" which I still think would be a compelling approach.

**Comment by mejiaj** [comment]
@aduth that's fair. This issue was initially captured and additional refinement is required. 

An initial test of native was done in #5761. The main focus of this work was to see how much of the existing code we could use. As well as what are possible limitations of a native web approach.

The approach we want to take is as close to native as possible. We're researching and speaking to other teams that support web components. Based on that we're looking at are:

1. Native components
2. [Open WC](https://open-wc.org/)
3. [Lit](https://lit.dev/)
4. [StencilJS](https://stenciljs.com/)

Besides 1 - these are light layers on top of native web API's that can target multiple frameworks like Angular or React.

**Comment by mejiaj** [comment]
Initial research findings (also captured in [GDOC 🔒](https://docs.google.com/document/d/1exZtf3Hn4XDw8aytJVtUi2dnhJ5SWxfBtdXVn7CG3S4/edit#heading=h.fa3sv1ray42g)).

StencilJS is a tool we've identified and want to use based on the criteria mentioned above. Initially, it's heavier than the other tools identified. It includes a lot of the things we care about out of the box, like SASS support. More importantly it offers a lightweight, native based API that can target other frameworks. Which would allow us room to better support other teams.

There are other existing projects, like the VA Design System that already uses StencilJS that'll allow us to collaborate with more easily.
