### ISSUE TITLE
Create draft of revised accessibility page

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds#5663]

**Comment by amycole501** [comment]
Alex and Amy will take the current [accessibility page](https://designsystem.digital.gov/documentation/accessibility/) content and revise it with updates prior to the January MC.

Updates will include guidance specifications, updated language, and efforts we undertake to test and confirm our components are accessible.

**Comment by amycole501** [comment]
Draft is [here in shared drive](https://docs.google.com/document/d/1n4DcDUbL5jVDVT3HY7TE6I4LLrY0CmKUhUDKCo873E8/edit?usp=sharing)

**Comment by thisisdano** [comment]
Done
