### ISSUE TITLE
USWDS - Feature: Configurable text for usa-file-input

### ISSUE THREAD

**Issue by deebloo** [uswds/uswds#5666]
### Is your feature request related to a problem? Please describe.

The current file input has hard coded text for "dragText" and "chooseText" this is not ideal for websites in multiple languages.

### Describe the solution you'd like

I would like to override those values via data-* attributes when defining the component. There are a number of hard coded english strings other than the two mentioned

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by brunerae** [comment]
Closing as it duplicates https://github.com/uswds/uswds/issues/5238

**Comment by deebloo** [comment]
@brunerae makes sense I guess the update for one can be applied to both
