### ISSUE TITLE
USWDS - Date Picker: Provide helpful error feedback when incorrect format is entered.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#5692]
Currently, users don't get any feedback that their input format is incorrect.

**Comment by jaclinec** [comment]
@mejiaj the [W3C design system offers some examples of form errors for dates ](https://design-system.w3.org/styles/form-errors.html)that look promising:
<img width="530" alt="image" src="https://github.com/uswds/uswds/assets/109540526/b851405c-1996-442a-b21b-9ae95b0eb9d8">

We could try something similar to this, but if the user enters the wrong format the error message could say something like "Please enter a valid date format MM/DD/YYYY" or similar.

**Comment by mejiaj** [comment]
This issue is scoped to only [USA Date Picker](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-form-inputs-date-picker--restricted-date&p=all).


<img width="400" src="https://github.com/uswds/uswds/assets/3385219/6d5106b5-2822-41a7-8743-48182dc6bad6" />



Work in #5879 shows that Date Picker component does have an error state that can be set.


<img width="400" src="https://github.com/uswds/uswds/assets/3385219/b12d2785-a2ba-4c4b-b00d-b0c8e5d76c91" />

[Preview link →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cm-create-error-stories/?path=/story/patterns-forms--test-error-form-elements) 

---

@jaclinec @mahoneycm would you consider this issue to be valid or can we close it?

**Comment by jaclinec** [comment]
@mejiaj I think that the work in #5879 resolves this issue, so this can one can be closed.

**Comment by mejiaj** [comment]
Great, thanks for that update!
