### ISSUE TITLE
USWDS - Bug: File Input not loading modified HTML until refresh

### ISSUE THREAD

**Issue by AnmolS1** [uswds/uswds#5694]
### Describe the bug

USWDS is not updating the HTML for the file input element when navigating to a page using the Angular router. This issue is observed in an Angular 17 application where the USWDS library is expected to modify the HTML for the file input component automatically.

### Steps to reproduce the bug

1) Navigate to a page containing a file input component using the Angular router.
2) Observe that the USWDS styles and modifications for the file input component are not applied immediately.
3) Manually refresh the page, and the USWDS modified file input element becomes visible.

### Expected Behavior

The USWDS library should automatically modify the HTML for the file input component when navigating to a page, without requiring a manual page refresh.

### Related code

[git repo demonstrating the issue](https://github.com/AnmolS1/uswds-fileinput-error-demo)
[github page for the repo](https://anmols1.github.io/uswds-fileinput-error-demo/)

### System setup

- USWDS version: 3.7.1
- Device: Macbook Pro 2019
- OS: MacOS Sonoma 14.0
- Browser: Google Chrome 120.0.6099.129
- Angular framework version: 17
- Node version: 21

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by deebloo** [comment]
to avoid this you might have to manually call the js methods to initialize the component. USWDS doesn't have any concept of the angular router so it has no way of knowing when a navigation has happened.

https://github.com/uswds/uswds?tab=readme-ov-file#js-customization

**Comment by deebloo** [comment]
you can also remove the initial script you have included. ONLY doing it via importing and .on, don't have the global script
