### ISSUE TITLE
Operationalize Usability Research: Conduct Zebra tests

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#5703]
After [completing the research plan](https://github.com/uswds/uswds-team/issues/322), conduct the Zebra tests using the new research process.

**Comment by jaclinec** [comment]
All usability testing sessions have been conducted. We spoke with 8 participants total. All user management tracking is logged in the [USWDS Participant Tracking spreadsheet](https://docs.google.com/spreadsheets/d/1Cy1SJCqaTLi24CPP4LsXu3TtVZu2Qvwsz347CX5Kgu0/edit?usp=sharing) (see Zebra testing tab) :lock:

Next steps:

- [analyzing and synthesizing the data (#328)](https://github.com/uswds/uswds-team/issues/328) 
- [share findings with team and public](https://github.com/uswds/uswds/issues/5704)
- Improve process documentation to make it easier to test in the future from a process perspective
