### ISSUE TITLE
Disabled States: Publish supporting research

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#5710]
The draft of the [disabled states literature review ](https://docs.google.com/document/d/1VP6HHXE0diVQBqYBdQhhLDo489V2DtbI9xrF031nJ-I/edit?usp=sharing)meant for publishing in the wiki was created last year and we are ready to re-review. Once content is finalized, I will publish it in the wiki which will make it available to the USWDS community.

**Comment by jaclinec** [comment]
I went through and revised some of the content to tighten it up and to ensure it largely matches a lot of the language we use in the disabled states phase 1 site content we are publishing soon. @sarah-sch and/or @finekatie - the draft is ready for your review. Thank you!

**Comment by jaclinec** [comment]
This has been reviewed by CS and is now ready for review from @annepetersen and/or @thisisdano . Not marking for fed final review yet as I suspect there could be more back and forth with editing.

**Comment by jaclinec** [comment]
Anne has reviewed and I've accepted suggestions - marking this for FFR.

**Comment by jaclinec** [comment]
I've published the [disabled states research findings in our Github wiki.](https://github.com/uswds/uswds/wiki/Disabled-States-Research-Findings-2023) This issue can be marked as 'done' - thanks, team!
