### ISSUE TITLE
Jan '24 POAM

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#5714]
Log and update the POAM document.

**Comment by mahoneycm** [comment]
## New vulnerability
- [Follow Redirects improperly handles URLs in the url.parse() function](https://github.com/uswds/public-sans/security/dependabot/67)
- Fix: [Bump follow-redirects from 1.15.3 to 1.15.4 #5287 ](https://github.com/uswds/public-sans/pull/287)

## Ruby vulnerabilities

Code scanning is flagging 5 vulnerabilities based on our `URI` usage. Looking into it.

**Comment by thisisdano** [comment]
Done
