### ISSUE TITLE
USWDS - Bug: JAWS closes all Chrome browsers when Skip to Main Content link activated

### ISSUE THREAD

**Issue by kerns-accessibility** [uswds/uswds#5718]
### Describe the bug

JAWS closes all Chrome browsers when the Skip to Main Content link is activated.

### Steps to reproduce the bug

   1.	Navigate with JAWS to the Skip to Main Content link.  
   2.	Select the ENTER key to activate the link.  
   3.	That causes JAWS to close all Chrome browsers.

**Occurs on these webpages below:**
   1.	TPGI:  https://www.tpgi.com/jaws-wide-open 
   2.	W3C:  https://www.w3.org
   3.	IRS:  https://www.irs.gov
   4.	State of California:  https://www.ca.gov
   5.	Department of Rehabilitation:  https://www.dor.ca.gov
   6.	Franchise Tax Board:  https://www.ftb.ca.gov

### Expected Behavior

Using JAWS, navigate to the Skip to Main Content link.  Select the ENTER key to activate the link.  That causes JAWS to skip past the top navigation and go to main heading/content on the webpage.

### System setup

OS and browser:
   1.	OS Edition: Windows 10 Enterprise
   2.	OS Version: 22H2
   3.	Browser: Google Chrome
   4.	Browser version: 120.0.6099.200

JAWS version: 2021.2107.12 ILM

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by alex-hull** [comment]
Was able to replicate with JAWS on USWDS, IRS and State of California site. 

WCAG [success criteria 2.4.1](https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks.html), bypass blocks, states the following: ...is to allow people who navigate sequentially through content more direct access to the primary content of the Web page. 

Typically these are in place to allow a user to move through a site with repeated content, ie. navigation bars/headers at the top, as a user could potentially have to go through each list under the navigation bar. Skip links could reduce the cognitive load for a user trying to find one specific item in the main content region.

**Comment by brunerae** [comment]
@mahoneycm / @alex-hull would y'all be able to sync on this Issue, clarify what is happening in the bug and update the Issue with any relevant info? Thanks!!

**Comment by mahoneycm** [comment]
Closing because we were not able to replicate. This does not appear to be a USWDS related issue.
