### ISSUE TITLE
Web Components: Initially establish working group

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#5719]
For any **federal projects** interested in joining the working group, please email uswds@gsa.gov. 

## Done when

- [x] Drafted a plan for the purpose of this group
- [x] Have a list of candidates (tracker of potential candidates [[gSheet](https://docs.google.com/spreadsheets/d/1yFJ-ik8FKH2g5CN-WBPlk3TJtf5qUkJKzehksCXYaV4/edit#gid=0) 🔒])
- [x] Outreach email has been sent.

**Comment by anselmbradford** [comment]
What's involved in joining this group?

**Comment by mejiaj** [comment]
@anselmbradford we're in the planning stages for identifying teams that have experience implementing web components. We'd like to share what we're thinking and see how others are tackling challenges, like multilingual, customizations, etc.

**Comment by deebloo** [comment]
There are a few of us that been working on this for a while and would love to be involved!

**Comment by brunerae** [comment]
Hi @deebloo - would you be able to send us an email at uswds@gsa.gov so we can chat more? Thanks!

**Comment by brunerae** [comment]
I am closing this Issue for initially establishing the working group. I've:

- [ ] Documented who is interested 
- [ ] Updated Issue description to direct folks on how to join
- [ ] Held some initial round meetings with early groups

We'll create follow-up Issues for future meetings.
