### ISSUE TITLE
JSON Tokens: Compare other design system's JSON settings and configs

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#5727]
To inform our strategy, review other design system's approach to JSON settings and configs. For more information, see the [notes from our Jan '24 JSON Tokens meeting](https://docs.google.com/document/d/1N3s_qgILXya49xmWEHFht05J9Mit8zgPwxWYn2dHfxs/edit#heading=h.hfb5a1f1q09j)

**Comment by mahoneycm** [comment]
Findings shared with team during Engineering working session.

[Meeting notes](https://docs.google.com/document/d/1fQy7omleRuR5qyAyDOXlorxXAwLrfC26WpJBBrSNisQ/edit#heading=h.JSON-tokens) (🔒) 
[Presentation slides](https://docs.google.com/presentation/d/1nt0F4Mkppo92N6W5gwAGRVMW3nHxI1g4vxGDhf2d43k/edit?usp=sharing) (🔒)
