### ISSUE TITLE
JSON Tokens: Determine preferred config/token structure

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#5728]
Based on research and landscape analysis, determine how we want to structure config/tokens. Compile findings and analyze conclusions. For more information, see the [notes from our Jan '24 JSON Tokens meeting](https://docs.google.com/document/d/1N3s_qgILXya49xmWEHFht05J9Mit8zgPwxWYn2dHfxs/edit#heading=h.hfb5a1f1q09j)

**Comment by mahoneycm** [comment]
Based on my findings for #5727 and our current token structure, the plan is to have our JSON token structure match our current SCSS [token structure](https://github.com/uswds/uswds/tree/202448875393d39d663614d2d8f9a12c91fed75e/packages/uswds-core/src/styles/tokens)

- tokens
   - color
   - font
   - units

Once we get an MVP together of these tokens, additional work may need to be done to convert `$system-properties` sass map to JSON as a lot of [tokens within Site data](https://github.com/uswds/uswds-site/tree/ee594656076f9e66d72a44cb261f81a736f89424/_data/tokens) are derived from this map. I'll be taking an iterative approach to convert these values to JSON and use style-dictionary to convert and match current scss output.
