### ISSUE TITLE
Convert system tokens to JSON

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds#5775]
MVP for JSON token conversion.

Convert Scss tokens/variables to JSON and use style-dictionary to return to the current Scss structure.

## Progress tracker

- [ ] #5863
    - [ ]  Standard colors
    - [ ]  black-transparent
    - [ ]  Decide whether or not to convert other sass map files
- [ ] #5864
    - [ ]  _index.scss
    - [ ]  base-cap-height.scss
    - [ ]  line-height.scss
    - [ ]  measure.scss
    - [ ]  stacks.scss
    - [ ]  type-scale.scss
    - [ ]  typefaces.scss
- [ ] #5865
    - [ ]  _index.scss
    - [ ]  breakpoints.scss
    - [ ]  column-gaps.scss
    - [ ]  layout-grid-widths.scss
    - [ ]  neg-prefix.scss
    - [ ]  spacing-em.scss
    - [ ]  spacing.scss
- [ ] #5866

**Comment by brunerae** [comment]
Closing in favor of scoped Issues (linked in description).
