### ISSUE TITLE
USWDS - Bug: Checkbox and Radio Button disabled styles

### ISSUE THREAD

**Issue by danbrady** [uswds/uswds#5802]
### Describe the bug

I notice the disabled checkbox and radio button controls don't have the gray fill like the other form controls. The disabled text color was darkened in 3.6.0, but visually it nows looks pretty close the default text color, making it hard to perceive the control being disabled. 

### Steps to reproduce the bug

1. Compare a disabled radio button or checkbox to other form controls

### Expected Behavior

Disabled radio buttons and checkbox should clearly visualize being in a disabled state.

### Screenshots

![image](https://github.com/uswds/uswds/assets/381190/5a2b38d6-2554-477a-adfd-409068c06f94)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
@jaclinec Do you have any findings from your user tests about the current styling of disabled radio buttons and checkboxes? If not, would this be a good candidate for future user testing?

**Comment by jaclinec** [comment]
@amyleadem and @danbrady yes we recently tested disabled states for the tiled radio button and a submit button on a prototype form with 8 participants (5 visually impaired, 3 with typical sight including a person with ADHD). We hope to publish those findings on our research page and wiki soon!

Although our new upcoming guidance will be to encourage folks to try to AVOID using disabled states (instead, keep enabled and provide feedback), we did test the disabled tiled radio button and it performed well. All participants were able to perceive that the button was disabled and most understood WHY it was disabled as well. 

Granted, there is a border around the option which may have made this easier to perceive. But also, when you hover over it, a little strikeout icon appears next to the mouse cursor as another indicator. Here's a screenshot of the radio buttons tested (with the last option disabled):

<img width="635" alt="image" src="https://github.com/uswds/uswds/assets/109540526/ef7d36aa-e4bc-4617-a180-9f7f784acb85">

As for whether to fill the radio button or checkbox with the gray filler, we have not tested this. One concern I'd have is that it might make the option appear already filled in or checked. I do think testing a default radio button (i.e. not tiled) and disabled checkboxes could be worthwhile, but again, we generally want to discourage disabling form elements at all.

**Comment by danbrady** [comment]
Hi @jaclinec! Thanks so much for the detailed response. I look forward to reading those findings when published!

Based on these findings, is it fair to say that there is _not_ an accessibility issue with the current text coloring in regular/not-tiled checkboxes and radio buttons? We strongly discourage disabled states too and could recommend the same hover treatment and explanation text in our guidance, but I want to make sure we are prepared and have a backup for any questions. Thanks again!

Including a screenshot and [code mock up](https://codepen.io/danbrady/pen/oNOrMVe) for reference:

<img width="399" alt="image" src="https://github.com/uswds/uswds/assets/381190/08e1b1af-07a2-4c7f-8ab5-b69611944c80">

**Comment by jaclinec** [comment]
Hey @danbrady are you referring to the contrast of the disabled text? If so, I think that's fair to say. We didn't observe any substantial issues with it. There was one person with low vision and using zoom magnification software who said that the hint text underneath was a little hard to see/read, seemingly because of the small font combined with the gray color. But it does meet contrast ratio standards for WCAG and that participant was able to read it - it didn't seem like a big pain point.

**Comment by danbrady** [comment]
Great, thanks for the details!
