### ISSUE TITLE
Assess USWDS race and ethnicity guidance

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds#5804]
Purpose
The purpose of this issue is to assess [race and ethnicity guidance](https://designsystem.digital.gov/patterns/create-a-user-profile/race-and-ethnicity/) on the USWDS website, per concerns raised in [this issue from the USWDS repository.](https://github.com/uswds/uswds/issues/5762) 

Concerns with current guidance
Agencies need to capture data about how much of the population served is Hispanic or Latino vs. not Hispanic or Latino. There are concerns that the open-ended text pattern recommended by USWDS could lead to under-reporting of Hispanic and Latino respondents, which would undermine programs' efforts to understand and meet the needs of the populations they serve.

Next steps for USWDS team

- [x] #5805
- [ ] After gathering expert input, the team will make appropriate updates to guidance on collecting race and ethnicity data
- [x] #5806

**Comment by annepetersen** [comment]
Relevant update, which we were anticipating: https://www.whitehouse.gov/omb/briefing-room/2024/03/28/omb-publishes-revisions-to-statistical-policy-directive-no-15-standards-for-maintaining-collecting-and-presenting-federal-data-on-race-and-ethnicity/

**Comment by sarah-sch** [comment]
Thanks for adding, @annepetersen!

**Comment by finekatie** [comment]
I think this is covered by the issue Dan created as noted above. Should we close this issue, @annepetersen ?
