### ISSUE TITLE
Consult experts in collection of race/ethnicity data

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds#5805]
Per discussion at CS/UX sync on 3/6, @thisisdano will contact colleagues who are experts in the collection of race/ethnicity data for advice about USWDS's race and ethnicity guidance (see #5804 for additional context).

**Comment by annepetersen** [comment]
Relevant update: https://www.whitehouse.gov/omb/briefing-room/2024/03/28/omb-publishes-revisions-to-statistical-policy-directive-no-15-standards-for-maintaining-collecting-and-presenting-federal-data-on-race-and-ethnicity/
