### ISSUE TITLE
Update USWDS guidance related to race and ethnicity data

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds#5806]
Background
The team agreed to prioritize updates to [Race and ethnicity guidance](https://designsystem.digital.gov/patterns/create-a-user-profile/race-and-ethnicity/) on the USWDS website based on [feedback from the community](https://github.com/uswds/uswds/issues/5762) and issues flagged in the content audit. See the notes from the 3/6/204 CS/UX/a11y sync for additional details.

Work to be done

- [x] #5808
- [ ] Align on new recommendations based on [conversations with experts](https://github.com/uswds/uswds/issues/5805)
- [ ] Under "if being collected for statistical, administrative, or compliance purposes ..." add more information about pattern for formal OMB catetory
- [ ] Spell out use cases that fall outside of collection for "statistical, administrative or compliance purposes" and point users to the appropriate guidance for these pages
- [ ] Make other text updates based on content audit recommendations
- [ ] Flag pages for regular review and updates as guidance and best practices evolve

**Comment by brunerae** [comment]
@brunerae break down some of the checklist items into discrete Issues, schedule into upcoming Sprints

**Comment by annepetersen** [comment]
Should probably be added to the checklist: https://www.whitehouse.gov/omb/briefing-room/2024/03/28/omb-publishes-revisions-to-statistical-policy-directive-no-15-standards-for-maintaining-collecting-and-presenting-federal-data-on-race-and-ethnicity/

**Comment by finekatie** [comment]
I have started a draft doc for the main race and ethnicity pattern page: https://docs.google.com/document/d/1iAJkHR-rPvx_97zY9S4TtMm8bAQFqAU52I_S9o3sZTA. When we have kickoff meeting, this can be discussed.

**Comment by sarah-sch** [comment]
Closing this issue because this work stream has been updated to reflect new guidance in [#2598](Closing this issue because work for these updates has been captured in #2598).
