### ISSUE TITLE
Identify pages on the Site that would be affected by changes to guidance about data collection on race and ethnicity

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#5808]
Document locations and any other relevant information on site pages related to this work. This part of larger initiative: #2598

**Comment by finekatie** [comment]
Hey @brunerae, can I move this to current sprint?

**Comment by finekatie** [comment]
Did a search on the site today. Started this doc: https://docs.google.com/spreadsheets/d/1AvqvBqNP_kGn-uZlVzyJXGcZ8vz8mjjD6hdBFai-Qp0
Should probably check out GitHub?

**Comment by finekatie** [comment]
I reviewed this with team in Office Hours on 4/25.  We were unable to locate any content in GH at this time. This ticket is closed. Will use spreadsheet to ensure all changes are made where needed.
