### ISSUE TITLE
USWDS - Bug: Buttons in nested button groups have mismatched heights

### ISSUE THREAD

**Issue by lpsinger** [uswds/uswds#5825]
### Describe the bug

Buttons in nested button groups have mismatched heights. We use button groups that contain buttons and segmented button groups in our USWDS site, https://gcn.nasa.gov.

This bug was introduced in USWDS 3.8.0.

### Steps to reproduce the bug

Save the HTML in the "Related code" section to a file and open it in your browser.

### Expected Behavior

Buttons should have equal heights, as in the USWDS 3.7.1 screen shot below.

### Related code

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <script
      src="https://cdn.jsdelivr.net/npm/@uswds/uswds@3.8.0/dist/js/uswds.min.js"
      integrity="sha256-9nBQm/0+Y4ff0QkGywBPFB7Yp8BA6hcCw7YJBgqI9rM="
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@uswds/uswds@3.8.0/dist/css/uswds.min.css"
      integrity="sha256-JPPhCvsnyRXrsY+Sms9v8JredBM6Zdweq8bcHEBp09U="
      crossorigin="anonymous"
    />
    <!-- <script
      src="https://cdn.jsdelivr.net/npm/@uswds/uswds@3.7.1/dist/js/uswds.min.js"
      integrity="sha256-t/niBrhFzTw5Q8BtSqImb5X3WE451khfo2zPd9DYXpU="
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@uswds/uswds@3.7.1/dist/css/uswds.min.css"
      integrity="sha256-iszgb7UBBBxmQSLukBUB9DnzjuPCkW6je7g5/5JwBFk="
      crossorigin="anonymous"
    /> -->
  </head>
  <body>
    <ul class="usa-button-group">
      <li class="usa-button-group__item">
        <button class="usa-button" type="button">Foo</button>
      </li>
      <li class="usa-button-group__item">
        <ul class="usa-button-group usa-button-group--segmented">
          <li class="usa-button-group__item">
            <button class="usa-button" type="button">Bar</button>
          </li>
          <li class="usa-button-group__item">
            <button class="usa-button" type="button">Bat</button>
          </li>
        </ul>
      </li>
      <li class="usa-button-group__item">
        <button class="usa-button" type="button">Baz</button>
      </li>
    </ul>
  </body>
</html>
```

### Screenshots

# USWDS 3.7.1

![Screenshot 2024-03-19 at 08 04 20](https://github.com/uswds/uswds/assets/728407/91e535b2-f6dc-405f-8ad2-03a18ba2de18)

# USWDS 3.8.0

![Screenshot 2024-03-19 at 08 04 36](https://github.com/uswds/uswds/assets/728407/9d4bafc2-6ef9-4a85-8091-d8395fb60d2f)

### System setup

- USWDS version: 3.8.0
- Device: MacBook Pro
- Operating system: macOS Sonoma 14.3.1
- Browser: Safari Version 17.3.1 (19617.2.4.11.12)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
Confirming that the presentation of nested button groups did change with the introduction of 3.8.0. This change occurs in Chrome, Firefox, and Safari. I am marking this as "Needs:discussion" because we need to discuss the use case of nested button groups before we can classify the issue as a bug and move it to scheduling.

This screenshot captures a nested button group using the button group code from the component code accordion:

![Image](https://github.com/uswds/uswds/assets/93996430/59422bd0-2cb7-4451-b67d-04d10088ceed)

```html
<ul class="usa-button-group">
  <li class="usa-button-group__item">
    <a href="#" class="usa-button usa-button--outline">Back</a>
  </li>
  <li class="usa-button-group__item">
    <ul class="usa-button-group">
      <li class="usa-button-group__item">
        <a href="#" class="usa-button usa-button--outline">Back</a>
      </li>
      <li class="usa-button-group__item">
         <button type="button" class="usa-button">Continue</button>
      </li>
    </ul>  
  </li>
</ul>
```

**Comment by lpsinger** [comment]
> I am marking this as "Needs:discussion" because we need to discuss the use case of nested button groups before we can classify the issue as a bug and move it to scheduling.

We use nested button groups (generally a non-segmented group containing several segmented groups) in our site (https://gcn.nasa.gov/).

**Comment by amyleadem** [comment]
@lpsinger Forgive me if I missed it on the page you sent, but curious if you can send a link to a page on your site that shows a nested button group. Seeing the pattern in action will help inform our discussion. Thanks!

**Comment by lpsinger** [comment]
> @lpsinger Forgive me if I missed it on the page you sent, but curious if you can send a link to a page on your site that shows a nested button group. Seeing the pattern in action will help inform our discussion. Thanks!

https://gcn.nasa.gov/circulars/36059
