### ISSUE TITLE
USWDS - Bug: color.scss Error: Undefined variable. @if map.has-key($project-color-shortcodes, $value) {

### ISSUE THREAD

**Issue by ameshkin** [uswds/uswds#5837]
### Describe the bug

We are having an issue that has to do with the ordering of our stylesheet.  The error goes away if I comment out the uswds-theme file, however, the site will obviously break. I don't have any custom variables in uswds-theme.scss so I have no idea why this is happening. I have the uswds-theme and uswds forwarded on the top of the stylesheet above any custom code.  Putting it at the bottom causes other issues, and then styles aren't overwritten.  This error doesn't make any sense and started showing up out of nowhere after a successful compliation.

```
@forward "uswds-theme";
@forward "uswds";
```

FULL ERROR
`node_modules/@uswds/uswds/packages/uswds-core/src/styles/functions/utilities/color.scss
Error: Undefined variable.
╷
59 │     @if map.has-key($project-color-shortcodes, $value) {
│                     ^^^^^^^^^^^^^^^^^^^^^^^^^
╵
node_modules/@uswds/uswds/packages/uswds-core/src/styles/functions/utilities/color.scss 59:21  color()
node_modules/@uswds/uswds/packages/uswds-core/src/styles/mixins/typography/typeset.scss 75:10  typeset-link()
node_modules/@uswds/uswds/packages/usa-link/src/styles/_usa-link.scss 4:3                      @forward
node_modules/@uswds/uswds/packages/usa-link/src/styles/_index.scss 4:1                         @forward
node_modules/@uswds/uswds/packages/usa-link/_index.scss 6:1                                    @forward
node_modules/@uswds/uswds/packages/uswds-typography/_index.scss 7:1                            @forward
node_modules/@uswds/uswds/packages/uswds/_index.scss 13:1                                      @forward
sass/styles.scss 3:1           
`

### Steps to reproduce the bug

npx gulp;

### Expected Behavior

I shouldn't have any errors as long as uswds-themeis before uswds

### Related code

uswds-theme.scss contents here.

`/*
----------------------------------------
USWDS with settings overrides
----------------------------------------
Uncomment the following lines and add a list of changed settings
in the form $setting: value,
----------------------------------------
*/

//
//  @use "uswds-core" with (
//    $setting: value,
//    $setting: value
//  );
//

/*
Note: the @use "uswds-core" with () configuration accepts only current USWDS settings variables.
 If you receive the error This module was already loaded, so it can't be configured using "with",
 confirm that all your declared variables exist in the in the list of USWDS settings and try compiling again.
*/

@use "uswds-core" with (
	$theme-link-color: "blue",
	$theme-color-accent-warm: #ffbe2e,
  $theme-color-base: #666666,
	$theme-color-base-lighter: "gray-warm-3",
	$theme-color-primary-lightest: "blue-warm-5",
	$theme-banner-max-width: "tablet-lg",
	$theme-footer-max-width: "tablet-lg",
	$theme-header-max-width: "tablet-lg",
	$theme-header-min-width: "tablet-lg",
	$theme-identifier-max-width: "tablet-lg",
	$theme-site-alert-max-width: "tablet-lg",
	$theme-grid-container-max-width: "tablet-lg",
	$theme-site-margins-breakpoint: "tablet-lg",
	$theme-font-type-sans: "public-sans",
	$theme-font-weight-semibold: 600,
	$theme-font-weight-heavy: 800,
	$theme-utility-breakpoints: (
	  "tablet-lg": true,
	  ),
	// $float-settings: (
	//   responsive: true,
	// ),

	// $height-settings: (
	//   responsive: true,
	// ),

	// $position-settings: (
	//   responsive: true,
	// ),
);
`

### System setup

uswds 3.0

Drupal 

        "drupal/uswds": "^3.0",
        "drupal/uswds_base": "^3.7",
        "drupal/uswds_ckeditor_integration": "^2.0",
        "drupal/uswds_paragraph_components": "^2.2",

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
Hello @ameshkin,
Thanks for reaching out. I did some preliminary testing and I believe the issue you're experiencing is related to the value for `$theme-link-color` in your settings configuration. "blue" is a valid CSS value, but the system is looking for a [USWDS color token](https://designsystem.digital.gov/design-tokens/color/system-tokens/#blue) (or a hex value) there. Can you try the following settings configuration in `uswds-theme.scss` and let me know if it resolves the error?

```diff
@use "uswds-core" with (
- $theme-link-color: "blue",
+ $theme-link-color: "blue-60",
$theme-color-accent-warm: #ffbe2e,
$theme-color-base: #666666,
$theme-color-base-lighter: "gray-warm-3",
$theme-color-primary-lightest: "blue-warm-5",
$theme-banner-max-width: "tablet-lg",
$theme-footer-max-width: "tablet-lg",
$theme-header-max-width: "tablet-lg",
$theme-header-min-width: "tablet-lg",
$theme-identifier-max-width: "tablet-lg",
$theme-site-alert-max-width: "tablet-lg",
$theme-grid-container-max-width: "tablet-lg",
$theme-site-margins-breakpoint: "tablet-lg",
$theme-font-type-sans: "public-sans",
$theme-font-weight-semibold: 600,
$theme-font-weight-heavy: 800,
$theme-utility-breakpoints: (
  "tablet-lg": true,
  )
);
```

**Comment by ameshkin** [comment]
Thank you, it was set to blue-60vh for some reason and I changed it to 'blue'.

**Comment by amyleadem** [comment]
Great! I'm glad that helped. Let us know if you need anything else!
