### ISSUE TITLE
Create canned text for proposal communication

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds#5838]
This ticket tracks the work of creating and approving standard text to communicate about new component proposals. We are working on the following text:

- [ ] [GitHub post to communicate that USWDS team is creating a proposal](https://docs.google.com/document/d/1bTBOFwRL4LIZyQFjD-cpbzrEcKuzszddBA8cBs0BfSQ/edit?usp=sharing)
- [ ] [GitHub post to share new proposal](https://docs.google.com/document/d/1OemnXbOkxkauSbS3P-Uazhy02eT4UKyFJvkKjMWWDOg/edit?usp=sharing)
- [ ] [Slack message to share new proposal](https://docs.google.com/document/d/1kToQ-xGVqoKZUqJV7lV3uLI71e2OAmpOd4OAMqxgO84/edit?usp=sharing)

We should also be sure to mention new formal proposals in the USWDS newsletter. Approval of this copy will be handled in the newsletter itself.

**Comment by sarah-sch** [comment]
[GitHub post to communicate that USWDS team is creating a proposal](https://docs.google.com/document/d/1bTBOFwRL4LIZyQFjD-cpbzrEcKuzszddBA8cBs0BfSQ/edit?usp=sharing) has been reviewed by internal team and is ready for review by @annepetersen as they're available.

[GitHub post to share new proposal](https://docs.google.com/document/d/1OemnXbOkxkauSbS3P-Uazhy02eT4UKyFJvkKjMWWDOg/edit?usp=sharing) and [Slack message to share new proposal](https://docs.google.com/document/d/1kToQ-xGVqoKZUqJV7lV3uLI71e2OAmpOd4OAMqxgO84/edit?usp=sharing) are with @finekatie for internal review.

**Comment by sarah-sch** [comment]
Passing these two documents on to @amyleadem and @mahoneycm for feedback:
[GitHub post to share new proposal](https://docs.google.com/document/d/1OemnXbOkxkauSbS3P-Uazhy02eT4UKyFJvkKjMWWDOg/edit?usp=sharing)
 [Slack message to share new proposal](https://docs.google.com/document/d/1kToQ-xGVqoKZUqJV7lV3uLI71e2OAmpOd4OAMqxgO84/edit?usp=sharing)

**Comment by mahoneycm** [comment]
@sarah-sch Those look good to me! No feedback 🥇

**Comment by sarah-sch** [comment]
Passed on for FFR on 3/28

**Comment by annepetersen** [comment]
I had reviewed on [GitHub post to communicate that USWDS team is creating a proposal](https://docs.google.com/document/d/1bTBOFwRL4LIZyQFjD-cpbzrEcKuzszddBA8cBs0BfSQ/edit?usp=sharing) and [GitHub post to share new proposal](https://docs.google.com/document/d/1OemnXbOkxkauSbS3P-Uazhy02eT4UKyFJvkKjMWWDOg/edit?usp=sharing) on 3/29: my changes and comments are still outstanding on both.

Now moving to [Slack message to share new proposal](https://docs.google.com/document/d/1kToQ-xGVqoKZUqJV7lV3uLI71e2OAmpOd4OAMqxgO84/edit?usp=sharing)

**Comment by sarah-sch** [comment]
Thanks, @annepetersen! I've made some adjustments in response to your feedback. You had a question about emoji voting in Slack, and I think we should discuss that during CS/UX sync because the only voting process we outline for the public right now is via Github upvotes. I added it to the agenda for Wed.

**Comment by sarah-sch** [comment]
@annepetersen - This is ready for your re-review. Thanks!

**Comment by annepetersen** [comment]
Re-reviewed: much closer here, thanks

**Comment by sarah-sch** [comment]
Thanks, @annepetersen! Accepted your suggestions and am passing on to @thisisdano for final review.

**Comment by thisisdano** [comment]
I've reviewed. There are just a few edits. Once we've agreed and merged all the edits, I can approve and close this one

**Comment by sarah-sch** [comment]
@finekatie - thanks for the ping! @thisisdano, I have accepted all of your changes. I think the next step is sharing with the dev team who are working on new component proposals, agreeing on a spot for this canned text to "live" going forward, and agreeing on a process for using it when needed (i.e., who will be responsible for posting these messages in GitHub and Slack as new proposals are drafted and shared for feedback).

**Comment by brunerae** [comment]
Added this to 7/2 Dev Sync agenda

**Comment by brunerae** [comment]
Next Step: we'll move these canned texts into one document and create a link to that in our proposal process documentation.

**Comment by annepetersen** [comment]
Templates are a [suggested feature for GitHub discussions](https://github.com/orgs/community/discussions/2838), but this feature isn't available yet, so, as @brunerae says, these should probably live in a single Google Doc for our reference now. Once we create that and link it up, we can close this out

**Comment by brunerae** [comment]
Next step: @brunerae to combine Google docs and update with link here, then close Issue.

**Comment by annepetersen** [comment]
Only thought of this after the discussion, but determining who's responsible is probably the only other outstanding piece here (per last item [here](https://github.com/uswds/uswds/issues/5838#issuecomment-2161207303))

**Comment by brunerae** [comment]
Here's a [link to the combined document](https://docs.google.com/document/d/1bTBOFwRL4LIZyQFjD-cpbzrEcKuzszddBA8cBs0BfSQ/edit). The next step, as @annepetersen says above, is to determine who is responsible for posting these. I'll add a quick CS/UX Sync agenda item

**Comment by brunerae** [comment]
Discussed this with @JaymeCharles - we agree that it makes the most sense for the proposal evaluators to post the canned text responses in Discussion threads/Slack threads. @jaclinec / @amyleadem - we can coordinate on how best to integrate this into the evaluation process.
