### ISSUE TITLE
USWDS - Bug: Incorrect text in Spanish language versions of the identifier component

### ISSUE THREAD

**Issue by mariamarrero** [uswds/uswds#5853]
### Describe the bug

The Spanish version of the [identifier component](https://designsystem.digital.gov/components/identifier/#identifier-preview) needs to be updated to reflect the following changes:

- change "Visite USA.gov en Español" (https://www.usa.gov/espanol/) to "Visite USAGov en Español" (https://www.usa.gov/es/)
- take out "An" from "An Un sitio web oficial de ..."

### Steps to reproduce the bug

Text changes in the Identifier component - changes listed under "describe the bug"

### Expected Behavior

Requested changes in "describe the bug"

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by brunerae** [comment]
Thank you for flagging this @mariamarrero, we've scheduled into our sprint sequence.

**Comment by amyleadem** [comment]
Confirming that this issue happens when the system builds out `html-templates` with `npm run build:html`. The issue does not appear in the component's Storybook preview. 

Tagging this issue for 3.8.1, but it might end up being a better candidate for 3.9.0.

**Comment by amyleadem** [comment]
Update: I have separated out the accidental "An" piece of this issue into its own issue: #5893
