### ISSUE TITLE
USWDS - Feature: Support responsive breakpoint prefix for text alignment

### ISSUE THREAD

**Issue by fallenturtle** [uswds/uswds#5855]
### Is your feature request related to a problem? Please describe.

I want to use different text alignment depending on the viewport width.

### Describe the solution you'd like

Support responsive breakpoint prefix for text alignment

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by amyleadem** [comment]
Hi @fallenturtle, 
Are you using USWDS 3? If so, this functionality should already exist in USWDS. You should be able to add the following code to your [USWDS settings configuration](https://designsystem.digital.gov/documentation/settings/#configuring-custom-uswds-settings) in Sass to turn on responsive breakpoints for the [text alignment utility classes](https://designsystem.digital.gov/utilities/paragraph-styles/#text-align):

```
@use "uswds-core" with (
  $text-align-settings: (
    responsive: true
  )
);
```

You can learn more about using responsive variants on our [paragraph style utility classes page](https://designsystem.digital.gov/utilities/paragraph-styles/#responsive-variants-2).

 Hopefully that gets you what you are looking for. Please let us know if that gives you any trouble.
