### ISSUE TITLE
USWDS - Bug: Update capitalization of npm In README

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds#5876]
This issue is for the [README](https://github.com/uswds/uswds/blob/develop/README.md) which also updates the site [Documentation page](https://designsystem.digital.gov/documentation/developers/). Where possible, avoid beginning sentences with words like "npm" that conventionally begin with a lowercase letter. When it appears at the beginning of a sentence, capitalize the N in npm.  

[See this conversation in Slack for more context](https://gsa-tts.slack.com/archives/C050HRGN7/p1713367302497929) on the decision about why to capitalize the N in npm at the beginning of a sentence.

**Comment by mahoneycm** [comment]
Looks like there is only one instance that might need changing, where it appears at the [beginning of the sentence](https://arc.net/l/quote/wzaichgz).

Any ideas on how we should rewrite that sentence so `npm` isn't the first word? If not, we can simply capitalize.

**Comment by sarah-sch** [comment]
@mahoneycm - How about "Use the npm package manager for Node-based projects."?

**Comment by mahoneycm** [comment]
@sarah-sch - I noticed that there's another use of `npm` at the beginning of the sentence in the same paragraph! 

> ...and compiled files. **npm** packages make it easy to update and install the design system from the command line.

Taking a crack at rewriting both sentences:

> The package manager npm can be used for Node-based projects. USWDS maintains the @uswds/uswds package that includes both the pre-compiled and compiled files. With npm packages, updating and installing the design system from the command line is easy.

Feel free to modify as you see fit!

Also, I found a sentence on the [npm website](https://arc.net/l/quote/stddvsjk) where they actually start a sentence with `npm` without capitalizing.

> **About npm**
> **npm is the world's largest software registry**. Open source developers from every continent use npm to share and borrow packages, and many organizations use npm to manage private development as well.

For our site, its probably still better to continue avoiding using it at the beginning of any sentences but wanted to share!

**Comment by mahoneycm** [comment]
@sarah-sch My initial hangup was with "npm package manager" because I hadn't seen it referred to it that way. It was always "the package manager, npm" or "npm is a package manager". I think because it reads like saying "ATM machine" since it gets it's name from "node package manager".

That said, I looked around and found that [Node.js](https://arc.net/l/quote/bokclcnr) has said the same thing on their site:

> An introduction to the npm package manager
