### ISSUE TITLE
USWDS - Bug: [ILIKETURQUOISE]

### ISSUE THREAD

**Issue by ILIKETURQUOISE** [uswds/uswds#5958]
[Spam content removed.]

**Comment by annepetersen** [comment]
Hi there @ILIKETURQUOISE . We consider this comment off-topic and will treat it as spam. We will block you as a user of this repo if you continue.

From [the USWDS community page](https://designsystem.digital.gov/about/community/):
>By voluntarily participating in a USWDS community, you are agreeing to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, be patient, practice constructive criticism, and stay organized.
