### ISSUE TITLE
Research web component accessibility

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds#5975]
Review/discovery and research web component accessibility. Find out limitations, benefits and how users can recheck their implementation. Specifically focus on ARIA, keyboard, or other a11y-specific testing

- [ Sample resource is here](https://www.erikkroes.nl/blog/accessibility/the-guide-to-accessible-web-components-draft/).
- [StackOverflow](https://stackoverflow.com/questions/75546623/web-components-a11y)
- [Accessibility and shadow roots ](https://dev.to/westbrook/testing-accessibility-with-shadow-roots-55cm)
- Related to above example: [GitHub ARIA delegation](https://github.com/leobalter/cross-root-aria-delegation/blob/main/explainer.md)
- [Web component accessibility](https://www.matuzo.at/blog/2023/web-components-accessibility-faq/)
- [Javascript and accessibility](https://www.boia.org/blog/does-javascript-make-my-site-less-accessible)

Resources provided by UXR and Dev team
- [Web Components Accessibility FAQ - Manuel Matuzovic](https://www.matuzo.at/blog/2023/web-components-accessibility-faq/)
- [Are Web Components Accessible? | HTML with Superpowers](https://htmlwithsuperpowers.netlify.app/faq/accessibility.html)
- [Shadow DOM and accessibility: the trouble with ARIA | Read the Tea Leaves](https://nolanlawson.com/2022/11/28/shadow-dom-and-accessibility-the-trouble-with-aria/)

[Documentation will live here](https://docs.google.com/document/d/1kCfjUJYj8m68wd28d8RaRxI5Ul35P5NhesO0Io9CGbA/edit?usp=sharing)

**Comment by alex-hull** [comment]
Thank you, @jaclinec! Will add these to our list above.

**Comment by amycole501** [comment]
Dug into several resources, created a list of definitions and found three issues to be aware of when creating web components:
1. Missing semantic meaning which exists in native HTML
2. Shadow dom can hide content from accessibility APIs that screen readers use
3. Custom elements can disrupt the natural focus flow of a webpage. We need to be sure to check focus order and use tabindex attributes

**Comment by amycole501** [comment]
Added additional resources to the documentation, will reopen issue or clone issue for further research at a later sprint.
