### ISSUE TITLE
USWDS - Feature: Add theme setting for custom breakpoints

### ISSUE THREAD

**Issue by jamigibbs** [uswds/uswds#5984]
### Is your feature request related to a problem? Please describe.

When the USWDS system is integrated into an existing site, there are sometimes additional breakpoints already integrated that do not exist in the USWDS system. This means that the USWDS utilities are incomplete because the system doesn't allow for adding additional breakpoints.

### Describe the solution you'd like

I would like to be able to use the USWDS system breakpoints as well as optionally add a custom breakpoint for generating utility classes.

### Additional context

The VA.gov system uses a breakpoint called `medium-screen` which is 768px (or 48rem). This breakpoint does not exist in the USWDS system but we would like to continue to use it along with the other breakpoints USWDS offers. This breakpoint is being used in [167+ files in VA.gov](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-website%20medium-screen&type=code).

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by mejiaj** [comment]
Moving issue back to `In progress` while we quickly look into supporting layout grid classes based on custom breakpoint.

CC @amyleadem
