### ISSUE TITLE
USWDS - Bug: file upload component is incompatible with a typical content security policy (CSP)

### ISSUE THREAD

**Issue by jeffpw-goog** [uswds/uswds#5990]
### Describe the bug

The [file input component](https://designsystem.digital.gov/components/file-input/) uses an `onerror` inline Javascript event handler which is incompatible with a typical [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). [This page](https://web.dev/articles/strict-csp#refactor) explains in more detail that inline javascript is not allowed with a nonce- or hash-based approach to strict CSP.

### Steps to reproduce the bug

1. Create a page with a file input component
2. Set a content security policy on the page, e.g. "script-src 'nonce-st+WdPSI/W6r3q3iFeG/hQ==' 'strict-dynamic' https:" (in production the nonce value changes on each request). You can do this by setting the `Content-Security-Policy` HTTP header, or adding an HTML meta element `<meta http-equiv="Content-Security-Policy" content="script-src 'nonce-st+WdPSI/W6r3q3iFeG/hQ==' 'strict-dynamic' https:" />`
3. On your local machine, create an empty text file and rename it to *.jpg
4. Open the page and upload the file to the file input component
5. Observe that the file preview is a broken image and the browser console shows this error: `Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-st+WdPSI/W6r3q3iFeG/hQ==' 'strict-dynamic' https:".

### Expected Behavior

The file preview image is a generic document icon rather than a broken image, and there are no browser security errors.

### Related code

The `onerror` inline event handler is used several times in this section: https://github.com/uswds/uswds/blob/369cf3fdf9abf721a357e864a0f6adbf667ba862/packages/usa-file-input/src/index.js#L394-L427

To meet CSP requirements, these event handlers should be added via addEventListener on the image element rather than the `onerror` attribute.

### Screenshots

**Actual:**
<img width="492" alt="image" src="https://github.com/user-attachments/assets/2728de03-240b-4d63-97d2-073f8288e670">

**Browser console error:**
<img width="576" alt="image" src="https://github.com/user-attachments/assets/1bf2a883-f682-45ec-ac05-671cbe2afc58">

**Expected:**
<img width="489" alt="image" src="https://github.com/user-attachments/assets/6c4874af-9c2e-4ed2-b7f1-c1a90c97e08f">

### System setup

- USWDS version: 3.6.0
- Device: Macbook
- Operating system: Mac OS 14.5
- Browser and version: Chrome 126.0.6478.184 (arm64)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
Thanks for reporting this and creating the PR. I've added this issue to our current sprint for confirmation and scheduling the work for review.

**Comment by mahoneycm** [comment]
Confirming I was able to replicate the issue by adding `<meta http-equiv="Content-Security-Policy" content="script-src 'nonce-st+WdPSI/W6r3q3iFeG/hQ==' 'strict-dynamic' https:" />` to the storybook iframe document in devTools and follow steps 3-5.

I was having difficulty testing adding the tag to the local build or within USWDS Sandbox. It was refusing to load the JS due to the CSP preventing it for some reason.

**Comment by jeffpw-goog** [comment]
@mahoneycm I'm happy to help with any issues you see; feel free to DM me on the GSA slack. I'm not sure exactly what you're seeing vs expecting, but if you add the CSP header then all script tags have to have a 'nonce="st+WdPSI/W6r3q3iFeG/hQ=="' attribute in order to load. Here is the branch I used to test on uswds-sandbox: https://github.com/uswds/uswds-sandbox/compare/main...jeffpw-goog:uswds-sandbox:csp-test.

**Comment by mahoneycm** [comment]
@jeffpw-goog Thank you for the demo repo! This helps streamline testing the bug.

I believe my issue surrounded the default way my demo repo was importing the USWDS JS. We'll schedule and test #5997 and reach out if we have any change requests! Thanks again for your engagement on this issue

**Comment by jeffpw-goog** [comment]
Hi @mahoneycm just checking if there's anything else I can do to help get this completed! I'll be rolling off our project and would love to see it wrapped up.

**Comment by mahoneycm** [comment]
Thanks for the bump @jeffpw-goog ! Just got back from some time off and I've updated the issue meta data and added it to our next sprint to review!

**Comment by mahoneycm** [comment]
@jeffpw-goog while we wait for additional peer review, would you be able to submit a [changelog](https://github.com/uswds/uswds-site/blob/fc5a598e92c2711863b3184b2c23282cd85e7e6d/_data/changelogs/component-file-input.yml) for this item? You can leave the date as `NNNN-NN-NN` and version number as `N.N.N.`.  You can find additional information in the USWDS site [changelog readme](https://github.com/uswds/uswds-site/blob/fc5a598e92c2711863b3184b2c23282cd85e7e6d/_data/changelogs/_CHANGELOG-README.md#L4)

If you're able to create a PR for the changelog, please add a link to it i the PR description here.

If you're unable to, just let us know!

Thanks Jeff

**Comment by jeffpw-goog** [comment]
@mahoneycm I created a pull request for the changelog as requested: https://github.com/uswds/uswds-site/pull/2912 and added a link under "Related pull requests" in https://github.com/uswds/uswds/pull/5997 - let me know if I did anything wrong!
