### ISSUE TITLE
USWDS - Forms: Form group error left border only viewable on wide widths

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds#5998]
# Description

The red border added to `usa-form-group--error` divs has a negative margin of `-2.5` units. This is equal to the border size + its padding so it causes the margin to be pushed off screen unless the user has added additional padding to its parent element.

This error border helps to signify the form's error state and should be maintained in desktop views.

## Steps to reproduce the issue

1. Visit form error state storybook preview
2. Resize the window from horizontally
3. In smaller views, the error border will be visible
4. In wider views, the error border will be pushed out of view.

### Related code

https://github.com/uswds/uswds/blob/df175b5916fb5cca5cb380f918fd5e1b1a85018e/src/patterns/components/usa-form-group/_usa-form-group.scss#L1-L11

**Comment by amyleadem** [comment]
Removing this issue from the 3.9.0 milestone because we decided to not move forward with it at this time.

**Comment by amyleadem** [comment]
@mahoneycm will explore an alternative solution where we just add padding/margin to the storybook preview so that the error state is visible at wide window widths.
