### ISSUE TITLE
USWDS - Bug: SVG images in 3.8.0+ release interfere with Cypress DOM snapshot style injection

### ISSUE THREAD

**Issue by Mwindo** [uswds/uswds#6011]
### Describe the bug

We run Cypress for end-to-end tests. After the test has run, Cypress allows you to look back at snapshots of the DOM at different points for debugging purposes. However, the release of USWDS 3.8.0 was bundled with a few SVGs that look something like this:

<img width="1418" alt="Screenshot 2024-08-05 at 6 04 08 PM" src="https://github.com/user-attachments/assets/87ffe956-330e-4bca-813a-3a4240d3859c">

The style blocks here interfere with Cypress DOM snapshots style injection (at least in our case), which can render the DOM snapshot unhelpful because none of the styles are applied (so images are often far too big, the page layout is incorrect, etc.). This makes debugging in certain cases quite difficult. Here is a screen shot of the garbled CSS in a Cypress DOM snapshot:

<img width="527" alt="Screenshot 2024-08-06 at 8 25 02 AM" src="https://github.com/user-attachments/assets/758253b7-413d-491e-9c5d-1352a868af32">

To fix this, I can run svgo, e.g., in package.json, `"postinstall": "cd ./node_modules/@uswds/uswds/dist/img && npx svgo -r ."`. After this, styles are injected appropriately:

<img width="678" alt="Screenshot 2024-08-06 at 8 37 31 AM" src="https://github.com/user-attachments/assets/0b00bb34-38ec-48ec-9c76-71560d9365e4">

Obviously, it would be preferable if the images were fixed to avoid this issue in the first place!

### Steps to reproduce the bug

Unfortunately, this is probably not easy to reproduce, and, frankly, while I "see" the issue, I do not fully understand the mechanisms at play. (E.g., is there something in our _particular_ setup that also contributes to the issue?) In any case:

1. Create a React project that uses USWDS
2. Write an end-to-end test with Cypress
3. Run Cypress in headed mode in a Chromium browser
4. Navigate to a DOM snapshot after the test has run. You should find that the style is incorrectly injected into the DOM (truncated strings directly inserted into the DOM)

### Expected Behavior

When I select a DOM snapshot in Cypress, I expect the styling of the page to be correct: Cypress should have injected the styles into the DOM appropriately.

### Additional context

This is effectively just a request to clean up existing and future SVGs using, e.g., svgo, before releasing.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by zachrog** [comment]
This is a major problem for us as well. We cannot review our failing tests, nor can we review accessibility violations that are generated by cypress.

**Comment by Mwindo** [comment]
Everything I said above still holds, but a quick update for more context:

We use esbuild with SVGs loaded via `dataurl` (and therefore inlined), and this is relevant to re-creating the issue. Loading SVGs via `file`--which, to be clear, is not something we wish to do--avoids the issue.

**Comment by mejiaj** [comment]
Need to confirm if other SVGs in USWDS include style tags. 

If not, we should consider:

- [ ] Automate SVGO before releasing
- [ ] Remove style tags from SVGs
- [ ] Document this requirement (no style tags in SVGs)

**Comment by Mwindo** [comment]
I just wanted to follow up on this issue and see if there’s any update or if I can provide more information. We'd like to be able to update the USWDS version in our project!

**Comment by amyleadem** [comment]
Priority is to fix the existing SVGs first. From there, we should evaluate the LOE to automate SVGO and update docs. These tasks might need to be a separate issue.
