### ISSUE TITLE
Add August Monthly Call to Monthly Calls page

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds#6025]
### Purpose
To add the August monthly call video and video (if available) to the [USWDS monthly calls page](https://designsystem.digital.gov/about/monthly-calls/).

### References
[Digital.gov August event page](https://digital.gov/event/2024/08/15/uswds-monthly-call-august-2024/)

### Steps to be completed

- [x] [Draft copy](https://docs.google.com/document/d/1vsLWj_MPeHL0UytBYK8eOY8cSBdebaoaFfFHSLnZIAA) for monthly calls page
- [x] Get feedback from dev team
- [x] Get approval of content from fed team
- [x] Work with team on adding August MC Q&A
- [x] Create branch to update YML page
- [x] Submit pull request - will be closed by: [2827](https://github.com/uswds/uswds-site/pull/2827) 
- [x] Pull request approval

**Comment by JaymeCharles** [comment]
Drafted page copy on 8/16 and flagged for FFR on 8/21

**Comment by JaymeCharles** [comment]
Posted the Q&A discussion yesterday
Dan approved the [event page copy](https://docs.google.com/document/d/1vsLWj_MPeHL0UytBYK8eOY8cSBdebaoaFfFHSLnZIAA/edit?usp=sharing), so ready for a PR

**Comment by finekatie** [comment]
PR created: [2827](https://github.com/uswds/uswds-site/pull/2827)

**Comment by finekatie** [comment]
Dan added changelog and approved for merge. This is done.
