### ISSUE TITLE
USWDS - Bug: Inconsistent use of classname constants in modal JS file

### ISSUE THREAD

**Issue by sanason** [uswds/uswds#6027]
### Describe the bug

In the JavaScript for the modal component, CSS classname strings are referenced via const variables in most but not all places where they are used. I need the code to use the const variables in _all_ places because I'm [trying to build](https://github.com/GSA/touchpoints/blob/3795f1302345b4f8ac40df633c9a65e35f072397/gulpfile.js#L50) the modal package with my own prefix (for example, `fba-usa-` instead of `usa-`) which only works if all classnames are constructed from the `PREFIX` constant.

### Steps to reproduce the bug

N/A exactly but here is a "bad code" example from packages/usa-modal/src/index.js.

```
const { prefix: PREFIX } = require("../../uswds-core/src/js/config");
const MODAL_CLASSNAME = `${PREFIX}-modal`;
...
  const openFocusEl = targetModal.querySelector(INITIAL_FOCUS)
    ? targetModal.querySelector(INITIAL_FOCUS)
    : targetModal.querySelector(".usa-modal");
```

### Expected Behavior

And here is a good code example.

```
const { prefix: PREFIX } = require("../../uswds-core/src/js/config");
const MODAL_CLASSNAME = `${PREFIX}-modal`;
...
if (clickedElement.closest(`.${MODAL_CLASSNAME}`)) {...}

```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
@sanason @cathybaptista thanks for those code examples. 

I'd like to confirm; is there a conflict currently with combining your custom class with `usa-modal`? For example something like below causes issues:
```
<div class="fb-modal usa-modal"></div>
```

**Comment by sanason** [comment]
> I'd like to confirm; is there a conflict currently with combining your custom class with `usa-modal`? For example something like below causes issues:

In our use case, `<div class="fba-modal usa-modal"></div>` is part of a widget that is embedded on someone else's webpage and that webpage very likely is loading its own copy of the USWDS code. Depending on the order in which the code loads, the webpage's copy of USWDS might also try to initialize the widget's modal, causing it to be initialized twice (which breaks stuff, as I've seen). 
A whole series of problems like that can be avoided if our widget's div instead looks like `<div class="fba-usa-modal"></div>`.
