### ISSUE TITLE
USWDS - Bug: Some colors cannot be set to custom values

### ISSUE THREAD

**Issue by szeinedd-nrel** [uswds/uswds#6059]
### Describe the bug

Certain color settings (e.g. `$theme-link-color`) only accept color tokens, and not custom colors (e.g. hex value), even with `$theme-show-compile-warnings` set to false.

When assigning one of these settings to a hex color code, the following error is output:
```
X [ERROR] "Only use quoted color tokens in USWDS functions and mixins. See designsystem.digital.gov/design-tokens/color for more information."
   ╷
46 │   $value: general.smart-quote($value);
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@uswds\uswds\packages\uswds-core\src\styles\functions\utilities\color.scss 46:11  color()
  node_modules\@uswds\uswds\packages\usa-button\src\styles\_usa-button.scss 142:34               @forward
  usa-button\src\_index.scss 4:1                                                                 @forward
  _index.scss 19:1                                                                               @forward
  src\styles\main.scss 2:1                                                                       root stylesheet [plugin angular-sass]

    angular:styles/global:styles:1:8:
      1 │ @import 'src/styles/main.scss';
        ╵         ~~~~~~~~~~~~~~~~~~~~~~
```

I believe the colors that will only accept color tokens are the ones listed under "General colors" in `packages/uswds-core/src/styles/setttings/_settings-color.scss`, which include:
* $theme-body-background-color
* $theme-text-color
* $theme-text-reverse-color
* $theme-link-color
* $theme-link-visited-color
* $theme-link-hover-color
* $theme-link-active-color
* $theme-link-reverse-color
* $theme-link-reverse-hover-color
* $theme-link-reverse-active-color

### Steps to reproduce the bug

Attempt to override the link color with a hex value.

```
@use "uswds-core" with (
  $theme-show-compile-warnings: false,
  $theme-link-color: #0071b8,
);
```

### Expected Behavior

sets the link color to the specified value

### System setup

"@uswds/uswds": "3.8.2"

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
Thanks for reaching out, @szeinedd-nrel. 

In general, we encourage you to use USWDS color tokens whenever possible. Using our color tokens increases consistency across government websites and also enables some of our Sass features like color contrast checks for accessibility and the ability to move up or down a grade for things like hover states. 

Here is an excerpt from the ["Using color" page](https://designsystem.digital.gov/design-tokens/color/overview/) on our documentation website:

> **Use USWDS color tokens, and avoid custom colors whenever possible.**
> Creating coherent government sites and services helps provide a good user experience to the public.

So if possible, it would be ideal to use one of the [USWDS system color tokens](https://designsystem.digital.gov/design-tokens/color/system-tokens/) to define your project's link color. There is even a helpful [color picker tool](https://civicactions.github.io/uswds-color-tool/) that can help you find a close match for your hex color with USWDS tokens. This tool also lets you see your custom color side-by-side with other USWDS color tokens.  Hopefully you can find an acceptable match there!

--- 

All of that said, we understand that sometimes there are certain project mandates that mean you must use a specific hex value in place of our system color tokens. For that reason, we have enabled the use of custom hex values to define [USWDS theme colors](https://designsystem.digital.gov/design-tokens/color/theme-tokens/). 

To accomplish the goal outlined in the issue above, you'd need to first define the value of a theme color setting, then use that token to define the link color. Here is an example of what that could look like:

```scss
@use "uswds-core" with (
  $theme-color-primary-vivid: #0071b8,
  $theme-link-color: "primary-vivid",
);
```
Note: The "primary-vivid" color token might not be the correct choice for your project, but wanted to show you how the mechanism works. 

I hope that helps! Please let us know if you have questions.

**Comment by thisisdano** [comment]
Hi there — as we've both addressed above there is some method to the distinction between color settings that accept custom hex and those that do not:

- What we consider `Theme color tokens` ([theme colors docs link](https://designsystem.digital.gov/design-tokens/color/theme-tokens/)) and `State color tokens` ([state colors docs link](https://designsystem.digital.gov/design-tokens/color/state-tokens/)) can be set to custom hex. We prefer that teams use System color tokens, but understand that sometimes custom hex is the only option. 
- The 65 color settings that accept custom hex are for those Theme and State tokens. Teams should use these Theme and State tokens to set the values of any additional color settings (whether in color settings or in component settings). So, for example, we'd suggest that teams set a custom hex for a value like `$theme-color-primary` and then use that `primary` token as the value for a setting like `$theme-link-color`.

For now, these are the limits we will maintain: allow custom hex for tokenized colors only (Theme and State), not for other color settings.
