### ISSUE TITLE
USWDS - Bug: Time picker instructions need more specificity to pass WCAG

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds#6061]
### Describe the bug

The existing visible instructions for time picker aren't sufficient to prevent errors; we need to add clarity to the format and options to prevent users from typing in potentially invalid times.
See https://www.w3.org/TR/WCAG20/#minimize-error-cues for clarification on 3.3.2

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/components/time-picker/
2. View hh:mm
3. Try typing in 12:15
4. Try typing in 19:30

Findings: hh:mm may not provide enough instructions for a user to select a valid time.

### Expected Behavior

Suggest adding more clear instructions. For example:

Start typing or select an AM or PM time in half-hour increments. 

### Additional context

FYI there's a related issue here for adding a 24 hour option https://github.com/uswds/uswds/issues/4947

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by mejiaj** [comment]
Removed `Site` from the issue title to avoid confusion.
