### ISSUE TITLE
October 2024 Newsletter

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds#6086]
### Helpful links:
[October newsletter draft here
](https://docs.google.com/document/d/13ZDT8yWCOVMsIXzg9yFs4y4lAd0zmV8bof0FcomyON8/edit?usp=sharing)[2024 Newsletter folder in Google Drive](https://drive.google.com/drive/folders/1mErWw9qfDP3wqrJDfZEAFhKYKTUFqSQK)
[GovDelivery](https://admin.govdelivery.com/session/new)

### Steps to send newsletter

**Draft copy**

- [x] New release/compile -
- [x] New USWDS sites -
- [x] Accessibility feature -
- [x] Featured component discussions
- [x] September monthly call recap
- [x] October monthly call info
- [x] Section about Web components?

**Review**
- [x] Review by content team
- [x] Review and feedback from larger team if needed
- [ ] FFR - Approval by Anne and Dan

**Compile**
- [ ] Add content to GovDelivery
- [ ] Proofread
- [ ] Publish

**Comment by JaymeCharles** [comment]
Sent to FFR 10/10. Anne has reviewed.

**Comment by finekatie** [comment]
Draft is ready. Awaiting FFR so we can publish

**Comment by JaymeCharles** [comment]
Katie finished setting up in GovDelivery. I reviewed and replied with a few low-lift edits. Hoping to send out the newsletter today or tomorrow.

**Comment by finekatie** [comment]
Newsletter scheduled for delivery 10/16 9am EDT. This is complete.
