### ISSUE TITLE
USWDS - Bug: xlink:href deprecated

### ISSUE THREAD

**Issue by caseywatts** [uswds/uswds#6088]
### Describe the bug

Currently we recommend folks use `xlink:href` in the [icon components](https://designsystem.digital.gov/components/icon/).

The `xlink:href` attribute of the svg `<use>` directive is deprecated:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

The switch is pretty straightforward - we should be able to switch references from `xlink:href` to just `href` and things will just work!

I ran into this when I was creating an icons web component using [Lit](https://lit.dev/), and I learned that [Lit doesn't support xlink:href](https://github.com/lit/lit/pull/1072#issuecomment-577299216) (because it's deprecated).

### Steps to reproduce the bug

Find references to `xlink:href` in the repo, and update them:
https://github.com/search?q=repo%3Auswds%2Fuswds%20%22xlink%3Ahref%22&type=code

### Expected Behavior

Expect no instances of `xlink:href` in the code

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
Thanks for including the helpful links here @caseywatts!

**Comment by amyleadem** [comment]
## Next steps
1. Evaluate the impact of removing `xlink:href` from our component code.
    - Does removing `xlink:href` cause any regressions in our supported environments? ([More info about href support on `use` on MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use))
    - If it doesn't cause regressions, we can replace `xlink:href` with `href` ([More info on MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href)). 
    - If it does cause regressions, we should explore using `xlink:href` as a fallback and investigate the impact of this when using libraries like Lit. 
1. Update all references to `xlink:href` in the uswds repo
1. Update all references to `xlink:href` in the uswds-site repo
