### ISSUE TITLE
USWDS - Bug: Focus ring in footer links is cut off

### ISSUE THREAD

**Issue by 6TELOIV** [uswds/uswds#6092]
### Describe the bug

The focus ring around footer links is cut off.

![Image](https://github.com/user-attachments/assets/7ea7c49c-af90-4191-a421-c4a81911a018)

### Steps to reproduce the bug

1. Create a footer using code like so:
```html
<!DOCTYPE html>
<html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/@uswds/uswds@3.9.0/dist/css/uswds.min.css" rel="stylesheet">
</head>
<body class="display-flex flex-column" style="min-height: 100vh;">
  <main class="flex-1"></main>
  <footer class="usa-footer usa-footer--medium">
    <div class="usa-footer__primary-section">
      <nav class="usa-footer__nav">
        <ul class="grid-row grid-gap">
          <li class="desktop:grid-col-auto usa-footer__primary-content mobile-lg:grid-col-4">
            <a class="usa-footer__primary-link" href="#">Test</a>
          </li>
          <li class="desktop:grid-col-auto usa-footer__primary-content mobile-lg:grid-col-4">
            <a class="usa-footer__primary-link" href="#">Test</a>
          </li>
        </ul>
      </nav>
    </div>
  </footer>
</body>
</html>
```
2. Observe that the top half of the focus ring is cut off

### Expected Behavior

The focus ring should show fully around the links in the footer.

![Image](https://github.com/user-attachments/assets/0a7dd8eb-fcb4-4f2a-a3fc-b8b2d11947bf)

### Screenshots

Current behavior:

![Image](https://github.com/user-attachments/assets/7ea7c49c-af90-4191-a421-c4a81911a018)

Expected behavior:

![Image](https://github.com/user-attachments/assets/0a7dd8eb-fcb4-4f2a-a3fc-b8b2d11947bf)

### System setup

- USWDS version: 3.9.0
- browser: all major browsers

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [x] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by 6TELOIV** [comment]
Updated the code example to point to the correct NPM package on jsdelivr and bump to latest version (3.9.0 at time of writing)

**Comment by brunerae** [comment]
@cathybaptista / @RachelCorsino to assess impact of this fix

**Comment by amyleadem** [comment]
> [!note]
> Added this to the November release milestone since it seems like a good candidate for the next release. I expect it will be a low level of effort to review and will likely be a quick win. If the review LOE grows, this might need to be bumped to a later release.

**Comment by mahoneycm** [comment]
After reviewing the proposed solution I noticed some minor visual differences across footer variants. We might want to consider bumping this to the next release to take a closer look at making each variant more uniform.
