### ISSUE TITLE
USWDS: Draft 3.11.0 release notes

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#6221]
## Summary
Draft release notes for USWDS 3.11.0 based on [this template](https://docs.google.com/document/d/1tfyTNyLA1CQ6P8maCQKC82HQrotixBnwhnTsRtZMuUA/edit?tab=t.0#heading=h.fa3sv1ray42g) (Google Docs :lock:).

**Comment by amyleadem** [comment]
# What's new in USWDS 3.11.0
## Features

Package | A11y | Breaking | Markup change | Description
:-- | :-- | :-- | :-- | :--
`package-name` | - | - | - | **Change description** Additional description.(#NNNN)
`package-name` | - | - | - | **Change description** Additional description.(#NNNN)

## Bug fixes

Package | A11y | Breaking | Markup change | Description
:-- | :-- | :-- | :-- | :--
`package-name` | - | - | - | **Change description** Additional description.(#NNNN) 
`package-name` | - | - | - | **Change description** Additional description.(#NNNN)

## Dependencies and security

| Dependency name                       | Previous version | New version |
| :------------------------------------ | :--------------- | :---------- |
| dependency                   |     N.N.N        |   N.N.N    |
| dependency                   |     N.N.N        |   N.N.N    |

`N` vulnerabilities in regular dependencies (dependencies for USWDS projects installed with `npm install @uswds/uswds`)
`NN` moderate, `NN` high vulnerabilities in devDependencies (development dependencies).

Release TGZ SHA-256 hash: (replace hash below) ``

**Comment by mahoneycm** [comment]
@amyleadem  for the `xlink:href` are we only listing packages with markup changes? Or should we list _all_ affected packages (for example, button and file input)

**Comment by mahoneycm** [comment]
Also heads up, we're working on a dependency update PR right now. I'll compare and update the dependency table once that is up 👍

**Comment by mahoneycm** [comment]
**question:** For the `xlink:href`, should we add a note for users to recommend removing as well?

If so:

**Suggestion:** ✏ Teams should remove this deprecated attribute from their components as well

**Comment by amyleadem** [comment]
> **question:** For the `xlink:href`, should we add a note for users to recommend removing as well?
> 
> If so:
> 
> **Suggestion:** ✏ Teams should remove this deprecated attribute from their components as well

@mahoneycm

Interesting note! My initial thought was to say it is outside the scope of USWDS, but a note like this might help keep users aware that support might drop. What do you think of something like this?
 

 ✏ MDN warns that [the deprecated `xlink:href` attribute can stop working at any time](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href). Teams should update this attribute in their projects.

**Comment by mahoneycm** [comment]
@amyleadem lgtm! Small optional suggestion would be to add that teams should "review their markup and update this attribute if needed" or something along those lines. Potentially unnecessary though!

**Comment by amyleadem** [comment]
Made some updates:
- Added an entry for #5555. Wasn't sure if we consider this a feature or a bug, so let me know if you want this moved. 
- Added a "teams should..." note to #6165. I went in a different direction than we discussed because once I saw it in the context of other release notes, it felt like we could scope it closer to USWDS.

**Comment by mahoneycm** [comment]
Looks like the the final vulnerability count got added to the bottom of the dependency table. Other than that, lgtm!

If we include dependency updates from #6255 and #6256 we should make sure to include these changes in the table.

**Comment by amyleadem** [comment]
Update: added `uswds-core` to the package list for #6232

**Comment by amyleadem** [comment]
Update: Added a line break to move the vulnerability section out of the dependency table

**Comment by mejiaj** [comment]
> Made some updates:
> 
> * Added an entry for [USWDS - Normalize: Remove outdated normalizations #5555](https://github.com/uswds/uswds/pull/5555). Wasn't sure if we consider this a feature or a bug, so let me know if you want this moved.

@amyleadem **re: bug vs feature:** seems like a feature because nothing is currently broken.


### xlink for SVGs

I like the idea of a note. If possible, it'd be helpful to have the generic note and an example of what that looks like in context of USWDS component. 

**For example**
```
✏ Teams should use `href` instead of `xlink:href` (deprecated) when referencing any SVG icon sprites, for example when using USA Icon.
```


```diff
<!-- USA Icon example -->
<svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
-  <use xlink:href="./img/sprite.svg#close"></use>
+  <use href="./img/sprite.svg#close"></use>
</svg>
```

**Comment by amyleadem** [comment]
Realized I accidentally saved over some of my changes in the release notes (:doh:), so I restored the entry for #5555, added a markup changes section, and added a "teams should..." note for #6165.
Let me know if you want any changes.

**Comment by mejiaj** [comment]
LGTM

**Comment by amyleadem** [comment]
Note: Need to update the dependency tables after POAM PRs are merged

**Comment by thisisdano** [comment]
Done!
