### ISSUE TITLE
USWDS - Bug: `jsdom` is causing unit test failures due to `nwsapi` update

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds#6242]
### Describe the bug

The node package, `nwsapi`, was recently updated and is causing our unit tests to fail due to classes containing `:`.

It doesn't seem to fail for all components/tests containing the character, but consistently for the big footer unit tests.

[CircleCI test failure →](https://app.circleci.com/pipelines/github/uswds/uswds/6490/workflows/ff861a1f-3fff-4373-9595-fe0062d2ef93/jobs/10965)

> [!IMPORTANT]
> This bug is found on on `main` and `develop` branches

### Steps to reproduce the bug

1. On `develop`, delete the `node_modules` and `package-lock.json` files
2. Run `npm install`
3. Run `npm run test:unit`
4. See failures in the terminal

### Expected Behavior

Tests should pass as expected

### Additional context

Potential solutions discussed:
- Removing the classes with `:` in the template makes tests pass.
- Reverting to `jsdom@23.2.0`, which replaced `nwsapi` (their CSS selector engine).
  - Unfortunately this package is from January 2024! The new selector engine was later removed because of performance (timeouts) issues.
- Create an override for `nwsapi@2.2.13` to specify which version our dependencies should use.
  - This allows us to specify the version without installing the package on our project.
- Install `nwsapi@2.2.13` on our project.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [x] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by asamuzaK** [comment]
Another solution suggestion:

Install [@asamuzakjp/dom-selector](https://github.com/asamuzaK/domSelector) and [monkey patch jsdom](https://github.com/asamuzaK/domSelector?tab=readme-ov-file#monkey-patch-jsdom).

`dom-selector` is the one that was previously added to jsdom and removed.
But with improvements since then, there should be few performance issues anymore (I hope).
