### ISSUE TITLE
Make Entire Code Example Available

### ISSUE THREAD

**Issue by dvito** [uswds/uswds#849]
Currently the code examples only have the HTML makeup available, it would be really nice if the related JS/CSS was easily available broken out in this area.

Example, https://playbook.cio.gov/designstandards/accordions would be a lot more useful if the JS / CSS was fully available.

**Comment by mollieru** [comment]
Thanks @dvito -- we'll consider this!

cc @carodew @colinpmacarthur

**Comment by Journerdism** [comment]
Adding all components to Marigold

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now.
