### ISSUE TITLE
Use WDS in SCSS-way

### ISSUE THREAD

**Issue by kottenator** [uswds/uswds#889]
`web-design-standards` (WDS) uses Neat which documentation says:

> We built Neat with the aim of promoting clean and semantic markup

This means that Neat wants to avoid `.another-grid > .col-3` by using SCSS mixins instead of CSS classes. 

But WDS provides own grid CSS classes on top of Neat: `.usa-grid > .usa-width-one-third` which is opposite to Neat's aim...

I understand that it's necessary in order to use plain CSS instead of SCSS.

So I come to a general question: **do you strictly recommend to use plain CSS? Or do you also recommend to use SCSS with "pure" Neat and Bourbon?**

It would be great if you'd provide how-to / quickstart / guides for SCSS-way as well as for CSS-way (currently there are code snippets only for CSS-way).

Could I help you with that? I may prepare a pull-request to your docs.

**Comment by maya** [comment]
@kottenator Currently we're more open ended to either approach depending on the needs of developers and how they wish to structure their projects. Some may want to quickly prototype something in CSS. Others may want to use the strict, semantic approach.

I agree that we should add documentation stating how you can use grids with CSS and semantically with Sass mixins. Durring the next phase of work, we'll be working to improve our developer documentation, but we're not quite ready to begin any substantial overhauling yet. 

Feel free to draft some ideas here that we can refer to when we're ready.
