### ISSUE TITLE
Create a shared modal dialogue pattern

### ISSUE THREAD

**Issue by KHarshawat** [uswds/uswds#911]
We've found a need for using a modal dialogue especially when a user is about to destroy work they have created (by canceling an appeal certification for example). 

As guidance, Google significantly increased comprehension and adherence of Chrome SSL warnings by following some basic principles, providing: 
- Clear instruction
- Attractive preferred choice
- Unattractive other choice

Old: ![image](https://cloud.githubusercontent.com/assets/6335546/11607898/df1f8afa-9b26-11e5-8525-68fc2e067627.png)
New: ![image](https://cloud.githubusercontent.com/assets/6335546/11607903/1304edce-9b27-11e5-9953-5ef0fa2286f8.png)

Results: ![image](https://cloud.githubusercontent.com/assets/6335546/11607900/f9dee2fa-9b26-11e5-9c3c-e65de1968611.png)

Other examples of deterring interfaces: 
![image](https://cloud.githubusercontent.com/assets/6335546/11607846/2d24ebd4-9b25-11e5-8bee-e35f3a322e31.png)

Our team would also like to use modals to grab users attention and collect in-app feedback with a text-area input box.

You can check out my first pass at designs for this in our Caseflow app, here: https://github.com/department-of-veterans-affairs/caseflow/issues/307

**Some things to consider:**
- How do you de-emphasize dangerous actions or alternately how do you warn the use that a dangerous action will take place
- How do you handle text input in a modal? Can modals support multiple input fields?
- Is there a secondary escape hatch like an `X` in the upper corner?
- Can a user drag the modal around the window?
- How will actions be laid out (single button, 2 buttons, 1 button 1 link, 2 links, etc)
- How will titles be handled?
- How do we change the page behind to make the modal stand out? (add a dark overlay, change the entire color of the page to a solid red, or yellow, or white), something else?)

**Comment by mebates** [comment]
We need "Are you sure?" modals as well for certify.SBA.gov. Right now we're using the default javascript alert box.

**Comment by maya** [comment]
Moving this note about a11y from duplicate issue #1477:

- ensure you focus on the the modal content when the button is pressed
- ensure focus doesn't escape the modal window and leak onto the page behind it
- make sure there's an escape button that's also keyboard accessible

**Comment by maya** [comment]
Quite a nice modal here: https://design.cms.gov/components/dialog/

We have a `usa-overlay` class that could be used to darken the background (used on the mobile navigation).

Note: we'd want to abstract some of the accessibility features added in #2347 into this as well (trap focus, `esc` to escape, etc...)

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now.
