### ISSUE TITLE
Add indeterminate checkbox styling

### ISSUE THREAD

**Issue by cvrebert** [uswds/uswds#918]
See https://developer.mozilla.org/en-US/docs/Web/CSS/%3Aindeterminate

## To Do

- [x] Create indeterminate styles - https://github.com/uswds/uswds/pull/5549
- [ ] Cleanup storybook previews - https://github.com/uswds/uswds/pull/5650
- [ ] Create high contrast styles - https://github.com/uswds/uswds/pull/5648

**Comment by carodew** [comment]
Hi @cvrebert, thanks for the suggestions. We'd like to look more holistically at how this pattern fits within a broader UI flow so we can also offer guidance on how it will be used. We'll look into it in the next phase!

**Comment by lpsinger** [comment]
Would you please re-open this? We use indeterminate check boxes on our USWDS-derived site (https://gcn.nasa.gov), and we are considering contributing our code upstream.

**Comment by mejiaj** [comment]
Reopening due to #5549.
