### ISSUE TITLE
Tabbed pattern?

### ISSUE THREAD

**Issue by ErieMeyer** [uswds/uswds#946]
Hello! This may be here but I'm unable to find it -- is there a tabbed pattern in the styleguide?

The specific use case is from this issue over on team VA: https://github.com/department-of-veterans-affairs/caseflow/issues/438

**Comment by maya** [comment]
@ErieMeyer we currently do not have a tabbed pattern in the library, but that's a good idea! We can revisit this for the next phase of work and see if there's a strong need.

Adding some links here for accessible tabs: 
http://heydonworks.com/practical_aria_examples/#tab-interface
http://getbootstrap.com/javascript/#tabs
http://foundation.zurb.com/sites/docs/v/5.5.3/components/tabs.html#tabs-deeplink-3

**Comment by ErieMeyer** [comment]
Thank you!!

**Comment by webinista** [comment]
A work in progress: http://codepen.io/webinista/pen/WrjMNo

- It borrows heavily from the [Refills](http://refills.bourbon.io/#accordion-tabs) accordion/tabs pattern.
- Our use-case is for internal software, so this example isn't (yet) optimized for touch input or smaller screens.

**Comment by maya** [comment]
Adding a note for possible design: We could take a cue from bordered accordion component bc its function is similar to the tabbed pattern. https://playbook.cio.gov/designstandards/accordions/

**Comment by carodew** [comment]
Not exactly tabs but USAJOBS has a horizontal nav pattern that could be the starting point for tabs: http://usajobs.github.io/design-system/nav-secondary/

**Comment by arvalarva** [comment]
In case it helps:

http://uspto.github.io/designpatterns/1.x/docs/components/tabs.html

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now.

**Comment by sawyerh** [comment]
Just sharing for others landing on this ticket: the CMS Design System has a [Tabs pattern](https://design.cms.gov/components/tabs/), which was heavily inspired by a Tabs pattern used by the Board of Veterans' Appeals team.

**Comment by thisisdano** [comment]
Thanks @sawyerh — We'll be expanding our supported components in 2019 and it's very likely that tabs will be a part of that group of work. And the work that you and others have done on a component is an important factor in our decision whether or not to pursue official support
