### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Drakenhart** [uswds/uswds#959]
**Use Case:** A long laundry list may require pagination.This differs depending on user base.
- ex. 
  - inboxes with many messages
  -  to-do list with multiple dates that span the course of a year or more
  - lists of medications
  - list of appointments that go back a year or more
  - event tracking over a year or more, etc)

**Issue:** Individuals with cognitive impairments may not be able to handle a long, continuous scrolling, list. it is often too much at once. The visual overload can cause confusion.

**Conflicting Issue:** Individuals with vision impairments who use speech synthesizers (like google Vox or JAWS) to surf a web site are more comfortable with a laundry list that they can skip through using keyboard functions.

**Comment by Drakenhart** [comment]
User testing suggests that text-only pagination controls are too much, and visual button-like controls are too little.

Wording choices used is also important for clarity of what function or action is expected by the user.

A hybrid approach is suggested. 

Location (left, middle, or right & top of list, bottom of list, or both). Top right, and if the list is long enough adding it to the bottom is also suggested.

Further testing in encouraged.

**Comment by maya** [comment]
@Drakenhart thanks for the request! We already have pagination designed as part of search results here: https://github.com/18F/web-design-standards/issues/703. We haven't prioritized building that out yet, but will let you know when we do / any further developments.

Related to: #785.

**Comment by mebates** [comment]
I'm still in need of pagination! Regardless of search ...

**Comment by joshbruce** [comment]
This component is prioritized for my project. We will share when we get the HTML and SASS...see what y'all think. 

We are considering two styles: One rectangular outline and one based on the #703 ticket.

<prev 1 ... 5 6 [7] 8 9 ... *n* next>

- This would keep the number of links down to something like 10 per page. 
- Always able to get to the first. 
- Always able to get to the last.
- Always able to navigate from the current page plus or minus 2 or 3.

The difficulty we're running into is mobile presentation. Should we go vertical? Let it wrap? Convert to a select? And so on.

**Comment by Drakenhart** [comment]
Seems both hit the primary best practices. Although I think the layout you have here is a bit more usable then the other (although the visual treatment for the other works very well. Maybe a hybrid approach?

As for mobile what if it was like this?

<   page 1 of x   > ?

With target area around the elements so they don't accidentally trigger each other?

**Comment by joshbruce** [comment]
Thanks @Drakenhart - When we first started talking about it we did consider progressively enhancing into the load more button. I think we decided to avoid infinite scrolling, and maybe that's a type of pagination?

Good tip on the hit area - when I did #346 that was the reasoning we had (adding @vkatari123 and @tarandhupar for heads up).

[iOS HIG](https://developer.apple.com/ios/human-interface-guidelines/visual-design/layout/)

> Provide ample spacing for interactive elements. Try to maintain a minimum tappable area of 44pt x 44pt for all controls.

**Comment by Drakenhart** [comment]
Thanks @joshbruce !  I do try to be helpful. ^.^

Thinking about your comment, maybe the load more button _is_ a type of pagination. o.O It's not what one might think of when someone says "pagination", to be sure. But thinking more on the functionality of it, it kind of does fit the bill in a slightly abstract super minimal sense.

And, yeah, I agree that infinite scrolling for certain content isn't a good way to go. I'm not a fan of parallax scrolling either, personally (I haven't found anything to quite win me over, yet).  Especially when you are looking at users who may have cognitive needs (memory, information overload, difficulty reading, etc).

Again, I think it's a context need. Not all pagination will fit the content type. (Search page versus image gallery). Maybe that's something to consider? Kind of in the same idea of how the footers were worked out, where you have a couple different versions maybe?

Articles, tabular data, lists, could have a specific kind of pagination. Where as Image galleries, "Carousels", slide shows (power point like), and such might have a different version? You'd still have the consistency, but it would be based on a pattern *type*. Thoughts?

**Comment by joshbruce** [comment]
Adding another team member: @jagannathch

**Comment by maya** [comment]
Sample prototype for pagination: https://codepen.io/USWDS/pen/eVzGzq

**Comment by buckaroogeek** [comment]
Greetings - just checking to see if there has been progress beyond the useful prototype on codepen.

**Comment by maya** [comment]
Hi @buckaroogeek, thanks for following up! There are no updates beyond the prototype on CodePen at this time.

**Comment by buckaroogeek** [comment]
Thank you

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now.

**Comment by maya** [comment]
Will add the UX designs we have for mobile pagination:
<img width="880" alt="screen shot 2018-07-24 at 3 41 30 pm" src="https://user-images.githubusercontent.com/5249443/43170016-1f68add0-8f58-11e8-9d28-2ae0e115d14d.png">

Visual design:
<img width="514" alt="screen shot 2018-07-24 at 3 42 46 pm" src="https://user-images.githubusercontent.com/5249443/43170033-3b1edd42-8f58-11e8-8c1f-e2fe47fc0cf3.png">
