### ISSUE TITLE
Styling for description lists?

### ISSUE THREAD

**Issue by BrianDiggs** [uswds/uswds#964]
I would like to make a feature request for some included styling for description lists (previously called dictionary lists). I realize that there is some subtly since the relationship between terms and definitions can be one-to-one, many-to-one, or one-to-many (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl has several examples). 
Description lists are referenced in the usability section of the table documentation (https://playbook.cio.gov/designstandards/tables/).

```
Depending on the type of content, consider using other presentation formats 
such as definition lists or hierarchical lists. 
```

**Comment by maya** [comment]
Thanks for the request, @BrianDiggs! Next week we'll be roadmapping and prioritizing new features for the next 6-12 months. So we'll have a better idea of what we'll be building then.

**Comment by jhfrench** [comment]
@BrianDiggs do you have any guidance on what styling variations you'd like to see for `DL`s? Were you thinking of something along the lines of [Bootstrap's styling of description lists](http://getbootstrap.com/css/#description)?

**Comment by BrianDiggs** [comment]
I did not have any specific suggestions or recommendations in mind. Looking at Bootstrap's styling, those seem to be reasonable suggestions, and I particularly like the inclusion of a `dl-horizontal` option and the built in responsiveness.

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now.
