### ISSUE TITLE
Guidance for semantic controls — e.g. phone numbers, credit card numbers, SSNs, etc

### ISSUE THREAD

**Issue by simsong** [uswds/uswds#986]
Many USG websites have text fields that require semantic validation on their input. For example, it's common to have a text field that accepts a phone number, a credit card number, or a SSN.

Currently different websites accept this information in different, mutually incompatible formats. Many do not improve usability.

For example, many USG websites require that phone numbers be entered as 10-digit numbers, e.g. 2025551212. These website specifically require taking out dashes (202-555-1212), even though the dashes improve readability and ease-of-entering. 

Another problem is that there is a broad range of input formats required to provide support for all citizens, but frequently web designers are not aware of the variety. 

Can the web design standards be expanded to include semantic information? I would like to see widgets for inputting:
- Phone numbers
- Credit card numbers.
- Social Security Numbers
- US addresses (including military bases abroad).
- Lat/Lon 
- Dates
- Times
- Date ranges

**Comment by carodew** [comment]
@simsong I think this is a great idea and it's something I personally hope to offer in the standards at some point in the future. Can't give a firm timeline on that at the moment, but it's definitely something that is being discussed.

I'm curious – what contexts do you encounter the need to enter latitude and longitude? The others are all pretty self evident.

**Comment by simsong** [comment]
Some scientific websites that display maps take lat/lon. For example, http://earthexplorer.usgs.gov

If you wish, I would be happy putting together some proposed semantic standards for various kinds of typed data. Having textual descriptions is an important first step before having code.

**Comment by carodew** [comment]
@simsong – what do you mean by 'proposed semantic standards'? Is that just a description of what it should look like? 

It sounds like it would be helpful, I just can't picture it at the moment. :+1:

**Comment by Drakenhart** [comment]
@simsong Are you speaking about microfromats and structured content?

**Comment by simsong** [comment]
Sort of. But I'm speaking about *entering* the data, rather than displaying it.

**Comment by simsong** [comment]
Sure. Here is an example:

Phone numbers in the North American Numbering Plan should be entered in a single text field. Phone numbers can be entered as NNN-NNN-NNNN or NNNNNNNNNN. Phone numbers are automatically segmented for display. If a +1 or "1" is entered at the beginning of the number, they are displayed for the user convenience. Internally numbers are converted to a standardized representation.

Explanation: Currently some USG systems require that phone numbers be entered as NNNNNNNNNN while others use three text fields and have people enter the numbers as [NNN] [NNN] [NNNN] with clever JavaScript that bumps you from the first-field to the second-field when you type the  3rd digit, but which doesn't intercept the delete or backspace to go back. 

The same applies to SSN and Credit Card Numbers.  SSNs are printed NNN-NN-NNNN for a reason—it is less error-prone to read and enter chunked numbers. However MANY USG systems require that SSNs be entered as NNNNNNNNN and generate an error when the dashes are inserted, even though it's less than a line of code to take out the "-". 

Likewise, CCNs are printed on the card NNNN NNNN NNNN NNNN (well, MC and VISA numbers), but MANY systems require that they be entered NNNNNNNNNNNNNNNN and generate user-errors when they are not.

This is a huge barrier to usability, both because of the inconsistency between systems, and because programmers are forcing users to enter and read numbers in a manner *that we know is more error prone*.

I think that 18F should have standardized GUI elements — that have been *user tested* — for entering many kinds of structured information. This includes CCNs, SSN, dates, times, etc.

**Comment by carodew** [comment]
Thanks! This is great, and exactly the way I think we should be thinking about these patterns (best practices, backed by usability testing, etc).

One thing that @colinpmacarthur and I have struggled with is that input masking – while usually great for sighted users – is terrible for people using screen readers. Check out this recording: https://docs.google.com/a/gsa.gov/file/d/0B9rGmqNcHo-mRGpMS0xQbzVzeGM/edit

We've implemented [PoliteSpace by Filament Group](https://github.com/filamentgroup/politespace) in cases where we've wanted to use input masking to get around this problem, but the implementation isn't perfect. For one, it doesn't provide visual hints when the text field has focus, so that doesn't actually help sighted users while they're typing (our initial research indicates that they want this). Also, when there is also password masking available, things get a little wonky (see issue #494). Not sure that particular issue bothers sighted users a whole lot but it might. 

We're still looking for solutions for the above, and how to address the needs of both sighted and unsighted users. 

Similarly, three separate text fields that use JS to automatically advance focus is really bad for keyboard users (it's hard or impossible to move back to an earlier text box if there is a mistake).

**Comment by simsong** [comment]
The three boxes with JS to automatically advance could work better. It's
not an impossibility, it's just that the implementations out there are very
poor. However, I believe that 3 boxes is fundamentally wrong, because it
doesn't handle copy-and-paste properly.

I'm not familiar with the term "input masking." Can you define it for me?

**Comment by carodew** [comment]
I've heard input masking used to refer to two different things: 
1. automagically adding in formatting (such as the -'s within an ssn) to a text field as the user types
2. hiding what a user types by replacing all characters with a symbol, e.g. if a user is typing into a password field, you often don't see what they are inputing but instead see a series of ••••• 

Internally we started referring to the first as input masking, and the second as password masking, just for clarity's sake. 

I agree about copy/paste.

**Comment by rogeruiz** [comment]
Pairing with @yozlet 

Would be interesting to replace Politespace with [FieldKit](https://square.github.io/field-kit/) since Politespace doesn't support not using jQuery #1351.

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now.
