### ISSUE TITLE
Collapsible and Dismissible Alert Examples

### ISSUE THREAD

**Issue by harrisj** [uswds/uswds#988]
It would be nice if alerts also included options the following actions:
- Dismissing the alert entirely (with an appropriate dismissal icon on the right)
- Collapsing/expanding the body of the alert (so the title would still be there)

I am not sure if this would mean doing JS for these actions or just providing some guidance on appropriate styling, but it would be useful for me on a current and some future projects.

**Comment by msecret** [comment]
I agree that a component like this would be good from a dev standpoint(interested in hearing from design). The code could almost be re-used for the accordion. In general, it'd be pretty easy to implement for a dev perspective.

**Comment by mollieru** [comment]
This isn't exactly an ideal implementation, but here's an example of one
existing adaptation of collapsable alert:
https://certify.sba.gov/am-i-eligible/app?

On Fri, Feb 5, 2016 at 5:01 PM, Marco Segreto <notifications@github.com>
wrote:

> I agree that a component like this would be good from a dev
> standpoint(interested in hearing from design). The code could almost be
> re-used for the accordion. In general, it'd be pretty easy to implement for
> a dev perspective.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/web-design-standards/issues/988#issuecomment-180584854>
> .
>



-- 

*Mollie Ruskin*
US Digital Service
Office of Management and Budget | Executive Office of the President

**Comment by joshbruce** [comment]
See #1124

**Comment by bradnunnally** [comment]
Closing the related PR and will use the information contained in #1124 when creating the new component.

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now.
