### ISSUE TITLE
[ style ] Leveraging Bourbon and migrating to 5.0.0

### ISSUE THREAD

**Issue by rogeruiz** [uswds/uswds#994]
This issue is the place to discuss how the `uswds` package leverages Bourbon. Currently the styles leverage parts of Bourbon that will be deprecated in `v5.0.0` which is in [beta at the time of this comment](https://github.com/thoughtbot/bourbon/releases/tag/v5.0.0.beta.1). This will need to be updated before we choose to upgrade to `v5.0.0`.

Thanks @tysongach for opening the first PR contributing towards this refactor => #989 :eyes:.

**Comment by tysongach** [comment]
Here to help and answer any questions!

The best resource to reference when upgrading is our [`NEWS`](https://github.com/thoughtbot/bourbon/blob/master/NEWS.md) document. Keep in mind, migrating from `4.2.x` to `5.0` would include the changes from the alpha and beta of Bourbon 5.0.

**Comment by rogeruiz** [comment]
@msecret brought up a good point here https://github.com/18F/web-design-standards/pull/1048#issuecomment-199391657 about leveraging Bourbon Neat's `media` mixin rather than using our own. I agree with this, but it requires us to refactor our current calls to `[uswds-]media` with Neat's version of `media`. Ours only takes one argument, while theirs takes three.

**Comment by msecret** [comment]
So wouldn't this require to change calls like this:

```
@include uswds-media($medium-screen);

@include media($medium);
```

**Comment by tysongach** [comment]
The Neat `media` mixin accepts two arguments: `$query` and `$total-columns`. Though, `$query` is a list so it appears as though there are more arguments. The documentation for this mixin can be found here: http://thoughtbot.github.io/neat-docs/latest/#media

@msecret Yes, I believe you are correct, since you all have the variables all set up: https://github.com/18F/web-design-standards/blob/18f-pages-staging/src/stylesheets/core/_grid-settings.scss#L9

So…

```scss
@include media($medium)
```

…would output:

```css
@media screen and (min-width: 600px)
```

**Comment by maya** [comment]
Thanks @tysongach!

Would the other variables (`@include media($small)` and `@include media($large)`) map out to our current breakpoints as well (481px and 1201px respectively)?

**Comment by tysongach** [comment]
@maya Yes, both mixins are looking at the same variables: https://github.com/18F/web-design-standards/blob/18f-pages-staging/src/stylesheets/core/_grid-settings.scss

**Comment by maya** [comment]
We hope to sunset Bourbon in 2.0, so this is no longer needed.
